tests/hold-release/13-ready-restart.t, tests/hold-release/13-ready-restart/bin/my-file-poll, tests/hold-release/13-ready-restart/bin/my-log-grepper, tests/hold-release/13-ready-restart/suite.rc
This test proves that we can close #958.
Stop suite `--now` while a task is in ready state. Restart with `--hold` and
then release. The ready task should continue instead of being set to
waiting.
=> Test for #958

lib/cylc/batch_sys_manager.py, tests/jobscript/05-slurm-no-directives.t, tests/jobscript/05-slurm-no-directives/suite.rc
This fixes a bug where a task is submitted without output, error, or name
directives if it has no directives specified in the suite.rc. I've added
a test (which does not require SLURM to be installed).
Example fix suggested by @matthewrmshin.
=> cylc jobscript: fix no-user-directives bug.

bin/cylc-poll, lib/cylc/gui/SuiteControl.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/cylc-poll/03-poll-all.t, tests/cylc-poll/03-poll-all/reference.log, tests/cylc-poll/03-poll-all/suite.rc
Closes #1177
Tests added.
Polls all tasks when no options are given at the command line.
Note that in my environment including on master tests/cylc-show/03-clock-triggered-non-utc-mode.t fails.
=> cylc poll-all: no options given then poll all

lib/cylc/gui/SuiteControlTree.py, lib/cylc/gui/TreeUpdater.py
Closes #1229 
Uses underlying data and not the displayed data.
=> cylc gcylc: sort date-times correct

lib/cylc/gui/TreeUpdater.py
This closes #940.
The previous behaviour of the tree view on update was to clear the tree
model then rebuild it. This caused a noticeable blip for largish suites
and made it difficult to focus on a particular row.
The new behaviour is to update the tree view in place if possible (if
there has been no structural changes), or to carefully reconstruct it
when there are structural changes. This is done piece by piece rather
than clearing and rebuilding from scratch.
The time taken to update the tree is much reduced for most updates,
but slightly more when a reconstruction is necessary. In all cases it is
no longer as jumpy.
=> #940: cylc gui: optimise tree view updating.

lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py
* close #1284 - stop job submission in simulation mode, once a shutdown is requested
* allow task kill (manual, or by stop --kill) in simulation mode
* some tidying of associated code (the commits are logcially separated)
Test battery passes.
@kaday - please review.
=> Simulation mode: shutdown bug fix, and task kill.

admin/get-repo-version, lib/cylc/version.py
Replaces #1275 (as per https://github.com/cylc/cylc/pull/1275#issuecomment-70774708).
I cherry-picked @trwhitcomb's commit.  My testing showed that it fixed the explicit error but returned nothing for the repo version - the directory had to be quoted in ```admin/get-repo-version``` too.
I have not checked for other dire consequences of having spaces in CYLC_DIR ... presumably Tim would have mentioned if there were any.
=> Handle spaces in CYLC_DIR for git repo version.

lib/cylc/gui/SuiteControl.py
Removed the obsolete --quick stop option.
Fixed broken stop-after-task option.
Tidied the layout and text.
Some code style corrections.
=> Cleaned up the gcylc stop-suite dialog.

bin/cylc-cat-log
This ensures that `localhost` does not require an SSH.
=> cylc cat-log: improve check for remote host

bin/cylc-gui, lib/cylc/gui/GraphUpdater.py, lib/cylc/gui/SuiteControl.py, lib/cylc/gui/SuiteControlGraph.py
In #1260 (since last release) I broke gcylc's ability to open without targetting a specific suite.  This fixes the problem by moving the suite share directory code into the graph updater class, which is the only place it's used.
=> Fix gcylc open with no suite specified.

bin/cylc-restart, lib/cylc/run.py, lib/cylc/rundb.py, tests/special/05-clock-triggered-utc.t
This looks to implement some of the ideas raised by @hjoliver in #1213, in particular:
> * instead of aborting with uncommitted updates [to the private db], could we first write those commits to a special recovery db, and then issue instructions on how to unlock the private db (i.e. find the errant process with fuser and kill it?); and how to update the the private db from the recovery one (or could we do that automatically on restart?)
and
> * even though the missing information exists in the private db, we might still want to write a special recovery db because an external process (e.g. a resync utility) could bring down the suite by reading the private db. Options might include:
This should ensure that if a database becomes locked all pending commits/updates to it are backed up and run …
=> rundb: dump out db operations queue on failure

lib/cylc/batch_sys_handlers/slurm.py
This fixes #1257. It makes sure the poll for e.g. a failed-with-no-task-message job
returns correctly when the job is still in SLURM's active job memory (can be up
to 5 minutes).
=> Fix SLURM poll failed job in active state

bin/cylc-submit, doc/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/host_select.py, lib/cylc/run_get_stdout.py, lib/cylc/version.py, tests/cylc-submit/09-bad.t, tests/cylc-submit/09-bad/suite.rc, tests/host-select/01-timeout.t, tests/host-select/01-timeout/reference.log, tests/host-select/01-timeout/suite.rc, tests/validate/27-mixed-syntax-global-suite.t, tests/validate/27-mixed-syntax-global-suite/suite.rc
This change allows the task host selection command to timeout. Consider something like this:
```cfg
[runtime]
[[t1]]
[[[remote]]]
host = $(command-that-hangs-for-some-reason)
```
Something similar has caused our suites to hang. This change will allow the job submission to fail.
While testing the new functionality, I have discovered and fixed 2 bugs:
* `cylc submit` does not return non-zero if task host selection command fails.
* If `global.rc` has old date-time syntax, all suites in new date-time syntax will fail; and vice versa. (#1277).
=> Task host select timeout

conf/cylc.vim
This fixes our `.vimrc` advice, avoiding a `E518: Unknown option: foldlevelstart=99` error for
non-fold-supporting versions of `vi`.
=> Fix .vimrc vi folding compatibility

bin/cylc, bin/cylc-graph, bin/cylc-graph-diff, lib/cylc/cylc_xdot.py, tests/cylc-graph-diff/00-simple-control/suite.rc, tests/cylc-graph-diff/00-simple-diffs/suite.rc, tests/cylc-graph-diff/00-simple-same, tests/cylc-graph-diff/00-simple.t, tests/cylc-graph-diff/test_header, tests/lib/bash/test_header
This adds a new command called `cylc graph-diff` which is intended
to help the user compare dependencies (or runtime hierarchies)
across suites. This should help the upgrade process from cylc 5
syntax.
This closes #1296 and is also related to #1068.
This introduces a `cylc graph --reference` option, which is used to
provide sorted structural output describing the suite graph. This
improves the test battery, which used to do this after the fact.
cylc graph-diff is a thin wrapper on top of two calls to `cylc
graph --reference`.
Note that `bin/cylc` needed a change to allow one cylc command
to be a subset of another (`graph` vs `graph-diff`). This also means
that e.g. typing `cylc gr` will bring up an error announcing more than
one command for that abbreviation.
@hjoliver, please test on …
=> cylc graph-diff: new utility to compare suite graphs.

lib/cylc/config.py, lib/cylc/gui/updater_graph.py
This fixes a blank cylc gui Graph View when a suite is re-run
while the cylc gui is still around from the previous run. The
root cause is the initial request for the last run's oldest and
newest cycle times, which gets stored in the 'actual_first_point'
variable (indirectly). This means that the subsequent requests
for the correct cycle point range do not give valid graphs,
because they appear to be well before the actual first point.
I've also fixed a bug in the purely-base-node-cycle-point cropping,
which would not have redrawn and uncropped the graph if e.g. a node
was re-inserted.
This addresses part of #1240, if not all of it.
=> Fix cylc gui blank graph for new runs with existing gui

lib/cylc/gui/updater.py
On current master, the following sequence of actions results in blank GUI views, although the suite summary icons update as normal in status bar:
1. run a suite
2. kill the suite so that the port file remains on disk
3. start up gcylc for the suite
4. remove the port file
5. start the suite
6. (observe the open gcylc instance)
The variable referencing the state summary Pyro proxy object needs to be set to ```None``` before attempting to reconnect.
=> Fixed a reconnection bug in gcylc.

lib/cylc/gui/app_gcylc.py
There's no need to have these developer-only options in the GUI.
This is a trivial aspect of #830.
=> Removed ref test options from gcylc.

lib/cylc/gui/app_gcylc.py
@matthewrmshin - in response to https://github.com/cylc/cylc/pull/1322#issuecomment-73863233, this adds the missing ```--no-detach``` option to the gcylc run suite dialog, thereby making the "options" label less silly.  (better overall layout could done too, later...)
=> gcylc run suite dialog options

lib/cylc/gui/gsummary.py
This fixes a broken import for `cylc gsummary`  and `cylc gpanel`.
=> Fix cylc gsummary and cylc gpanel

bin/cylc-submit, bin/cylc-trigger, lib/cylc/CylcOptionParsers.py, lib/cylc/gui/app_gcylc.py, lib/cylc/job_logs.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/cylc-trigger/03-edit-run.t, tests/cylc-trigger/03-edit-run/bin/my-edit, tests/cylc-trigger/03-edit-run/conf/global.rc, tests/cylc-trigger/03-edit-run/suite.rc
This should allow us to finally close #91.
It works now, but is not quite ready for review yet - I still need to:
* tidy the affected task proxy code,
* make the new functionality available via the GUI,
* restrict use to single tasks (not families or matched groups of tasks)
* (consider use of this via gcylc running on another host)
*Implementation* [update: this has changed, see below]
The ```cylc trigger``` command gets a new option ```--edit``` that causes the suite daemon to get the target task to write its job script, set itself to ```held```, and then return without actually submitting the job.  Then ```cylc trigger``` fires up the user's editor on the new job script (waiting for it to be written if necessary). When the editor is exited, it tells the daemon to release the task, …
=> SMS-style edit-run functionality

lib/cylc/gui/updater_graph.py
=> cylc gui: fix off-centre initial graph view

tests/hold-release/11-retrying/suite.rc, tests/hold-release/hold-after/suite.rc, tests/hold-release/run-hold-after/suite.rc
Three tests under ```tests/hold-release/``` are failing on my desktop box at work.
* ```11-retrying.t``` - the problem reported in https://github.com/cylc/cylc/pull/1324#issuecomment-74208499 was caused by this bash 4.2 behaviour: https://github.com/cylc/cylc/pull/1108#discussion_r16582794
* ```15-hold-after.t``` and ```16-run-hold-after.t``` need to run in UTC mode, for compatibility with the UTC start and stop times extracted from the reference logs.
@arjclark - please review.
=> Tests.niwa fixes

INSTALL, README, bin/cylc, bin/cylc-check-versions, bin/cylc-get-suite-version, bin/cylc-version, doc/cug.tex, doc/siterc.tex, lib/cylc/remote.py
Close #1335 
* exports CYLC_VERSION before remote command invocation
* aliases ```cylc -v``` to a new command ```cylc version``` which can take the ```--host``` and ```--user``` options (better for testing this sort of thing) [UPDATE: adds the new command but does not alias the old main-command options to it]
* updates ```cylc check-versions``` which did not reflect global settings for remote login shell etc.
* updates installation documentation to emphasize the need to use the version wrapper
=> 1335.cylc version

conf/cylc.lang, conf/cylc.vim, conf/cylc.xml
A common convention (at our site, anyway) is to name include files `suite-something.rc` (usually
runtime includes, specific to a particular subset of the suite). This sets `suite*.rc` to be the glob
for matching cylc suite.rc configuration files.
I haven't altered the emacs one because I couldn't find the relevant setting - I guess this is done
manually by the user.
=> Allow suite*.rc for syntax highlighting filenames

lib/cylc/run.py, tests/restart/21-deleted-logs.t, tests/restart/deleted-logs/suite.rc
The suite run tree is only being created at cold-start. #1217 added a new log sub-directory (for suite definitions), so suites started with an earlier cylc version will fail to restart at 6.2.0--6.3.0 when they attempt to use the new directory.
This is a trivial fix, plus PEP8 compliance, and a new test.
=> Restart - create suite run tree if necessary.

lib/parsec/config.py, lib/parsec/example/cfgspec.py, lib/parsec/fileparse.py, lib/parsec/tests/getcfg/bin/one-line.py, lib/parsec/tests/nullcfg/bin/empty.py, lib/parsec/tests/nullcfg/bin/missing.py, lib/parsec/tests/synonyms/lib/python/cfgspec.py, lib/parsec/upgrade.py, lib/parsec/util.py, lib/parsec/validate.py
On some machines (distributions), the parsec tests (but not parsec itself) can fail with:
```
File "/opt/cylc/lib/parsec/tests/getcfg/bin/one-line.py", line 13, in <module>
from config import config
File "/opt/cylc-master/lib/parsec/tests/getcfg/bin/../../../config.py", line 212, in <module>
from validate import validate, check_compulsory, expand, validator
ImportError: cannot import name validate
```
This is due to a `validate.py` module shipped with the distribution.
This change makes sure that the parsec modules are imported with the 'parsec' namespace.
=> parsec: fix import module conflict in tests

bin/cylc-trigger, tests/cylc-trigger/03-edit-run.t
The new test for cylc trigger --edit fails under Python 2.7 because
of a change in difflib output detailed here: https://bugs.python.org/issue7585
This change adds some dummy filenames (which aren't necessary, but are nice
to have) and strips the extra space from the Python 2.6 difflib output so that both
Python versions pass the test.
=> cylc trigger --edit: fix Python 2.7 test failure.

lib/cylc/config.py
This just fixes a bug in the "task not defined" error message, which if triggered results in a traceback instead of the intended error message.  It looks like it might have originated in a cut-n-paste error, although I haven't checked.
@arjclark - please review.
=> Fixed an error message.

doc/cug.tex, doc/suiterc.tex
The job submission command template now accepts a single `%(job)s` for
the path name to the job file.
Close #1371.
=> CUG: fix job submission command template descr

doc/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/job_host.py, lib/cylc/remote.py, lib/cylc/task_proxy.py
This should make it more consistent with the `remote copy template`
setting.
=> global.rc: remote shell template is now a prefix

bin/cylc-restart, lib/cylc/job_host.py, lib/cylc/scheduler.py, tests/restart/22-bad-job-host.t, tests/restart/22-bad-job-host/suite.rc
On restart, the suite attempts to re-initialise the suite run directory
on remote hosts with submitted or running jobs. The suite is currently
unable to restart if any of these remote hosts is unavailable. This
change allows the suite to restart with a warning message written to the
log.
Fix #1327.
=> Fix restart crash if remote job host unavailable

bin/cylc-gpanel
This fixes the hardcoding of e.g. `/some/path/to/cylc-6.3.1` in the bonobo server
files for cylc gpanel. When using the wrapper script (`/some/path/to/cylc` is a
symlink to `/some/path/to/cylc-6.3.1`), use the 'cylc' symlink if it evaluates the
same.
Fix #1356.
=> #1356: fix cylc gpanel cylc version path hardcoding.

lib/cylc/gui/updater.py
This fixes #1243. It provides a warning dialog if the daemon and GUI versions do not match.
=> gcylc: daemon version mismatch warning

lib/cylc/gui/gsummary.py
This makes the `cylc gsummary` window slightly larger by default.
It was arguably over-small and cut off the `y` in our setup here.
=> cylc gsummary: larger default window size

lib/cylc/task_pool.py
The `incl_runahead` argument has been removed from the `get_tasks` method by #1320. This causes various failures in the test battery.
=> Fix keyword arg broken at #1320

lib/cylc/scheduler.py, tests/cylc-cat-state/01-issue1358.t, tests/cylc-cat-state/01-issue1358/suite.rc
Fix #1358.  Removing a task when nothing else is happening did not result in the state dump being updated.
=> Update state dump more often.

bin/cylc-show, lib/cylc/config.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/taskdef.py, tests/cylc-show/00-simple.t, tests/cylc-show/01-clock-triggered.t, tests/cylc-show/02-clock-triggered-alt-tz.t, tests/cylc-show/03-clock-triggered-non-utc-mode.t, tests/cylc-show/simple/suite.rc, tests/graph-equivalence/00-oneline.t, tests/graph-equivalence/01-twolines.t, tests/graph-equivalence/02-splitline.t, tests/graph-equivalence/03-multiline_and1.t, tests/graph-equivalence/04-multiline_and2.t, tests/graph-equivalence/multiline_and_refs/c-ref, tests/graph-equivalence/splitline_refs/a-ref, tests/graph-equivalence/splitline_refs/b-ref, tests/graph-equivalence/splitline_refs/c-ref, tests/manual/00-reset-with-deps.t
The ```cylc-show``` command was slightly broken:
* it failed for the suite-only case (no task argument)
* it didn't exit with error status if a non-existent task name or instance was given
* cycle point input was not standardized
And the output formatting was a bit crap (e.g. blank lines printed if the suite had no title or description).
=> Fix and tidy the show command.

lib/cylc/gui/app_gcylc.py
Initial gcylc task filter settings (namely filtering out runahead tasks) are displayed in the status bar but don't actually have any effect until the filter window is first popped up.  This fixes the bug.
@benfitzpatrick - please review (if possible I'd like this in the imminent new release as it's a completed bug fix).
=> Action initial gcylc filter settings.

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/combo_logviewer.py
Fixes a bug introduced by #1385 - the combo log viewer started off showing the content of ```job.out``` even if *View -> job script* was chosen (although the filename on the drop-down combo box was correct).
For good measure I've allowed choice of job out or err directly from the right-click menu.
@matthewrmshin - please review (another small bug fix, it might as well go in *next release* if possible)
=> gcylc - initialize log viewer with correct log file.

doc/siterc.tex
=> Corrected case of "pyro" item in global config reference.

lib/cylc/gui/gsummary.py
If `cylc cat-state` fails for a suite, `cylc gsummary` will crash with a traceback like this:
```
File "/opt/cylc/lib/cylc/gui/gsummary.py", line 972, in get_new_statuses_and_stop_summaries_updatetime
get_task_cycle_statuses_updatetime(host, suite, owner=owner))
TypeError: 'NoneType' object is not iterable
```
This fixes the problem and outputs the stderr from the suite.
You can recreate the bug simply by removing an active suite's state file.
@arjclark, please review.
=> cylc gsummary: fix handling of cylc cat-state failure

lib/cylc/__init__.py
It no longer exists.
Is there any reason why we need to add `$CYLC_DIR/bin` to `$PATH` and `$CYLC_DIR/lib` to `$PYTHONPATH` at this point? The only reason I can think of are:
* `$CYLC_DIR/bin` is not in path, and someone calls `cylc` with a full path. (Very unlikely.)
* Something like `./cylc/bin` is in `$PATH`. (Even less likely.)
* Somone needs to use cylc's Python library outside of the `cylc` executable. (Highly unlikely.)
=> Remove $CYLC_DIR/util from init

bin/cylc-kill
The logic suggests that POINT is compulsory, but the help string was
marking it as optional.
@arjclark please review.
=> cylc help kill: POINT is compulsory

doc/suiterc.tex, lib/cylc/config.py, tests/special/08-clock-triggered-0.t, tests/special/clock/suite.rc
Instead of forcing users to put `clock-triggered=foo(PT0H)`.
Close #1417. @benfitzpatrick please review.
=> cylc.config: allow `clock-triggered=foo` syntax

lib/cylc/task_proxy.py, tests/cylc-insert/03-insert-old.t, tests/cylc-insert/insert-old/reference.log, tests/cylc-insert/insert-old/suite.rc
This fixes #1422. Inserting a task that has been removed from the task pool causes
a `DatabaseIntegrityError` warning in the log/suite/err. This is due to the task already
having an entry in the `task_states` table when the new task proxy is created.
@arjclark, please review.
=> cylc insert: fix DatabaseIntegrityError warning when old task re-inserted

lib/cylc/gui/updater_graph.py
The current filtering logic will always remove base family nodes,
sometimes leaving their sub-dependencies isolated in a separate
part of the graph.
=> cylc gui: fix filtering out of base node families.

.mailmap
This should improve the output from `git shortlog` for the cylc repository.
=> Add `.mailmap` to improve shortlog display

tests/cylc-job-poll/03-slurm.t
This fixes the slurm cylc-job-poll test, which has been failing intermittently.
=> cylc test-battery: fix slurm job poll problems

bin/cylc-documentation, doc/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/config.py, lib/cylc/gui/app_gcylc.py, lib/cylc/gui/view_graph.py, lib/cylc/remote.py, lib/cylc/state_summary.py, tests/cylc-doc/00-cylc-doc.t, tests/cylc-doc/01-suite-urls.t, tests/cylc-doc/01-suite-urls/suite.rc, tests/cylc-doc/test_header, tests/cylc-get-config/00-simple/section2.stdout
Close #1399.
This adds a ```URL``` item to runtime namespaces, and a top level one for the suite too.  If present, it is shown in task tooltips in the GUI, and can be browsed via the task right-click menu. Uses global config browser. [update: not in tooltips; can be browsed from gcylc or the ```cylc doc``` command]
Motivation: NIWA's operational system has extensive web documentation on each task for operational suite operators - too much to put in the in-suite task ```description```s.  This makes it much easier to find the documentation for a failed task, for example.
=> Clickable task documentation URLs

lib/cylc/config.py, lib/cylc/scheduler.py, tests/cli-cycle-points/00-simple.t, tests/cli-cycle-points/00-simple/suite.rc, tests/cli-cycle-points/test_header
```
[scheduling]
initial cycle point = 2015-01
final cycle point = 2015-02
[[[P1M]]]
graph = foo
```
Now override initial and final point on the command line:
```
cylc run --until=2015-05 my.suite 2015-04
...
SuiteConfigError: 'The initial cycle point:2015-04 is after the final cycle point:2015-02'
```
The CLI final cycle point is not being considered in the validation check against initial point.
=> Use CLI final point before checking is > initial point.

lib/cylc/broadcast_report.py, tests/broadcast/07-float-setting.t, tests/broadcast/07-float-setting/reference.log, tests/broadcast/07-float-setting/suite.rc
This fixes `cylc broadcast` when the configuration setting to be changed is held as a float (e.g. the timeout settings).
=> cylc broadcast: fix broadcasting a float setting

lib/cylc/batch_sys_manager.py, tests/job-submission/06-garbage.t, tests/job-submission/06-garbage/lib/bad.py, tests/job-submission/06-garbage/reference.log, tests/job-submission/06-garbage/suite.rc
Python's `subprocess.Popen` has a bad habit of not setting the command's
executable name in `OSError.filename` (e.g. command's executable does not
exist or does not have the correct permission).
@hjoliver Is this sufficient to close #1443?
=> job submit: add filename to OSError

tests/pyc/00-simple.t, tests/pyc/test_header
This checks for any remaining `.pyc` files that do not have a `.py` module. These can
cause imports to succeed where they should really fail.
=> cylc test-battery: check for orphaned pyc files

lib/cylc/gui/updater_graph.py, lib/cylc/gui/updater_tree.py, lib/cylc/state_summary.py, lib/cylc/task_proxy.py, tests/hold-release/11-retrying/suite.rc
Task summary now includes the submit number. This gets displayed by `cylc gui` tree view latest message, and tool tips in other views.
On retry, the latest message includes the delay interval and the time after which it will retry.
On initiation of job submit, poll and kill, log the submit number.
Close #30.
=> cylc.task_proxy: more info in summary messages

lib/cylc/suite_state_dumping.py
Close #1448.
@benfitzpatrick please review.
=> cylc.suite_state_dumping: ensure handle is defined

bin/cylc-graph, lib/cylc/config.py, lib/cylc/cylc_xdot.py, lib/cylc/graphing.py, lib/cylc/gui/updater_graph.py, tests/graphing/03-filter.t, tests/graphing/03-filter/graph.plain.ref.filtered, tests/graphing/03-filter/graph.plain.ref.orig, tests/graphing/03-filter/suite.rc, tests/graphing/04-filter-siblings.t, tests/graphing/04-filter-siblings/graph.plain.ref.filtered, tests/graphing/04-filter-siblings/graph.plain.ref.orig, tests/graphing/04-filter-siblings/suite.rc
Currently, when a node is filtered out, the incoming
and outgoing edges from it are discarded. This can split the
graph and can mislead the user. This can be particularly bad
for runahead nodes/groups of nodes where intervening base
node cycles are filtered out.
This change replaces all connected groups of filtered-out nodes
with small placeholder special nodes.
This fixes #1423, but is more of an enhancement that's up for
critique - I'm not wedded to the display choices (scissors text, dotted lines, etc)
particularly.
It adds an extra option to cylc graph to turn on filtering for
test purposes.
The following image shows the extra functionality compared with the image in #1423:
=> cylc gui: preserve edges on node filter out

lib/cylc/task_proxy.py
Previously, only the host name is displayed after a successful submit.
It will now display both the `[user@]host` and the `batch_sys_name` even after a failed submit.
Close #1452.
=> cylc gui: tree: display user@host on submit fail

lib/cylc/dbstatecheck.py
If suite polling fails because the target db is locked, we get:
```
cylc.dbstatecheck.DBOperationError: Suite database not found at: database is locked
```
This corrects the error message string.
=> Corrected a bad db error message.

doc/cug.tex, doc/siterc.tex, doc/suiterc.tex
Share and work directory documentation was not very clear.
@matthewrmshin - this is another small one for tomorrow's release, if it happens to pass review in time.
=> Updated the documentation of task work and share directories.

lib/cylc/task_proxy.py
Add poll/kill failed to latest message for GUI. Close #1457.
=> cylc.task_proxy: GUI poll/kill failed message

tests/restart/retrying/suite.rc, tests/restart/running/suite.rc, tests/restart/submit-failed/suite.rc
Writing the directives as a Jinja2 string as an environment variable
casuses the tests to die in error if we add multiple lines of site
specific directives to a batch system and that the key of line 2(+)
contains an invalid identifier as an environment variable.
@benfitzpatrick please review.
=> tests/restart: remove unnecessary env

bin/cylc-scan
If localhost + multiple hosts are configured for scan, and if the user
is logged in to one of the mutliple hosts, the host will be reported
twice. This change ensures that localhost is only reported once.
=> cylc scan: ensure localhost is only scanned once

lib/cylc/gui/gsummary.py
Fix #1465. I guess the intention of the `last_updated_time` variable is to log when an update occurred on the client side?
@kaday please review.
=> cylc gsummary: fix UnboundLocalError

bin/cylc, bin/cylc-gsummary, lib/cylc/CylcOptionParsers.py, lib/cylc/__init__.py, lib/cylc/gui/gsummary.py
cylc:
* Prepend its `../lib/` to `sys.path` - if the `lib/` of a different version of `cylc` is already in the `PYTHONPATH`, it will ensure that the library of the current invocation of `cylc` is in the front. (The old logic *appends* `../lib/` to `sys.path`, which means that it loads `lib/cylc/__init__.py` from an incorrect version, but which would by chance sets `PYTHONPATH` correctly again to the correct version. It *works* but is not safe.)
* Don't add `CYLC_DIR` to front of `PATH` - this allows wrapper to look for `cylc` using `CYLC_VERSION`.
* `cylc` will no longer rely on sub-commands to be in `PATH`. It now calls them from its own location.
* On `OSError` executing a sub-command, it will now print the file name of the sub-command.
cylc gsummary:
* When launching `cylc gui`, it …
=> cylc: friendlier init for admin/cylc-wrapper

lib/cylc/config.py, tests/validate/36-pass-special-tasks-non-word-names.t
This fixes the task name validity check for special task configuration.
It also allows undefined task names in special task config lists, except in strict validation mode - so
you can temporarily comment tasks out of the graph without having to alter the ```[[special tasks]]``` section as well - which I think is consistent with allowing naked dummy tasks in non-strict mode.
=> Fix special task name check

tests/job-kill/01-remote/suite.rc, tests/restart/22-bad-job-host/suite.rc
These tests will work just fine in my environment with `background` job submission, but they could hang then fail if `at` does not work correctly on the tests' remote host.
=> Don't use "at" for remote hosts tests

lib/cylc/batch_sys_manager.py, lib/cylc/job_logs.py, lib/cylc/task_proxy.py, tests/job-kill/02-loadleveler/suite.rc, tests/job-kill/03-slurm/suite.rc, tests/job-kill/04-pbs/suite.rc
It was always returning 1.
Also ensure that the exit codes of submit, poll, kill, etc commands are
logged in the `job-activity.log`.
Fix #1472.
=> cylc.batch_sys_manager: fix job kill ret code

lib/cylc/graphing.py
My recent change (since last release) to use non "strict" graphs in order to reveal self-dependence loops, has also revealed that extra edges are added within cycle point sub-graphs when sub-graph grouping is turned on.  E.g. on master:
and on this branch:
@benfitzpatrick - can you review the small change here, and confirm that there isn't some circumstance under which the extra edges really do need to be added?
=> Graph - don't add extra edges when grouping by cycle.

lib/cylc/gui/tailer.py
If invalid utf-8 bytes are present in a job's standard out or err, the log file viewer in `cylc gui` will have a blank display and some stderr may be spit out like this from gtk:
```
GtkWarning: gtk_text_buffer_emit_insert: assertion `g_utf8_validate (text, len, NULL)' failed
self.logbuffer.insert( self.logbuffer.get_end_iter(), line )
```
This change tests for corrupt stuff.
Invalid log files can be created by running e.g. `head /dev/urandom >>job.err` (although it is possible it might produce totally sensible text!). Our software that produced the garbage bytes had been killed by Slurm in an out-of-memory situation.
=> cylc gui: handle invalid utf-8 bytes in log files

lib/cylc/config.py, lib/cylc/graphing.py, tests/validate/35-fail-self-edges.t
Close #1481.  Restores graphviz ```strict=True``` and detects self-edges earlier on, when first creating the graph edges.
=> 1481.fix family edges

lib/cylc/gui/app_gcylc.py
Fixes issue #1485.
The gcylc suite status strings are quite varied; we need to be careful in matching them to determine widget sensitivities.
@kaday - please review.  Check that your problem was exactly the same as the one I've identified and fixed (i.e. that it was triggered by the use of final cycle point, and hence a "running to POINT" status string).
=> gcylc - fix handling of "running to" status.

lib/cylc/config.py, tests/validate/20-fail-no-scheduling.t, tests/validate/21-fail-no-dependencies/suite.rc, tests/validate/37-fail-double-runahead.t, tests/validate/37-fail-double-runahead/suite.rc
Currently you can set both ```runahead limit``` and ```max active cycle points```, and the former silently takes precedence.
=> Fail use of both runahead config items.

lib/cylc/config.py, tests/validate/38-clock-trigger-task-not-defined.t
On clock triggered task not defined.
Fix #1498. @kaday please review.
=> cylc validate: fix error format logic

lib/cylc/scheduler.py
This adds a check in the main scheduler loop that checks the suite directory still exists.
We have seen the situation where users will have a suite fail, have notifications from the handlers and not take any action. Some time later they will delete the suite directory, leaving suite processes lying around on our servers. This adds a periodic check to make sure the suite directory is still there and shut it down if not.
@hjoliver - please review. N.B. I can adjust the check to be frequent if so desired.
=> scheduler.py : fix for deleting a suite out from under a process

doc/siterc.tex, doc/suiterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/cfgspec/utils.py
Addresses setting of the [cylc] section entries at site level from #802.
This change allows the following to have defaults set at the site level (and if not set use the existing defaults):
* [cylc] -> UTC mode
* [cylc] -> [event hooks] -> startup handler
* [cylc] -> [event hooks] -> shutdown handler
* [cylc] -> [event hooks] -> timeout handler
* [cylc] -> [event hooks] -> timeout
I've made a minor documentation addition but this should probably be expanded on.
@hjoliver - can you take an initial look and see what you think? If you're happy then I'll finish up the documentation. The main aim here is to be able to set timeout handlers at the site level (the other entries are an added bonus).
=> Allow setting of cylc section hooks at site level.

tests/database/00-simple.t
@arjclark - please review - the printed db schema order seems to have changed (probably via the recent db refactor, but I haven't checked).  Or if the order is not consistent across sqlite versions, we'll need to sort the reference version...
=> Fix order of db schema in test.

lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py
Closes #1502 
If the kill part of shutdown --kill fails then a suite won't shutdown. This allows the suite to shutdown if the kill operation has failed.
@hjoliver - please review. I've been testing this by running a job on a remote machine and turning said machine off while the task was running then attempting to stop the suite. I'd imagine the same sort of testing would be possible if one were to disconnect from a network.
Can you give this a careful check over, I think this is right but am worried I may have missed one of the other shutdown combinations.
=> Allow shutdown if kill failed.

lib/cylc/scheduler.py
Update the time calculations used for periodic checking of file system to use time.time rather than datetime as recommended in #1518 
@matthewrmshin  - please review this minor change as a speedup of the existing code.
=> Replace datetime calls with time.time equivalents.

lib/cylc/gui/updater_graph.py
This fixes a bug where filtered out family nodes can reappear as
base nodes in the graph view. They are only filtered out if they
appear in the fam_state_summary, which itself is prone to being
filtered.
Closes #1517.
=> cylc gui: fix family graph filtering base nodes.

lib/cylc/scheduler.py, tests/ext-trigger/01-no-nudge.t, tests/ext-trigger/01-no-nudge/suite.rc
External triggers are similar to clock triggers: they have to be triggered outside of task processing (and if one is triggered, that should stimulate task processing).  The external trigger matching was being done in the task processing block, so task processing wasn't stimulated by an external trigger unless other things were happening in the suite at the same time (else a "nudge" was required). 
(yes, we need event-driven processing!)
@matthewrmshin - please review or reassign.
=> Moved call to external trigger matching.

lib/cylc/network/suite_broadcast.py
Close #1539 
Make use of locking to prevent simultaneous dumping and changing of `self.settings` in the BroadcastServer object.
@matthewrmshin - please review (I haven't broken anything as far as I can tell)
=> Add locking around operations on settings in broadcast

lib/cylc/config.py, lib/cylc/scheduler.py, lib/cylc/suite_host.py, lib/cylc/task_state.py, tests/inheritance/01-circular.t
This closes #294. It removes some unnecessary/inappropriate sys.exit calls from the code.
The remaining calls are limited to code only used by clients (GUIs, commands).
The inheritance change in `lib/cylc/config.py` is probably the only one that can interfere with
threading and ports files.
@kaday, please review 2.
=> cylc codebase: remove some bad sys.exit calls

doc/cug.tex
This was missing from the examples in Advanced Cycling.
=> doc: add R1 at final cycle point example

lib/cylc/run.py
=> New runtime blurb message.

lib/cylc/batch_sys_handlers/loadleveler.py, lib/cylc/batch_sys_handlers/lsf.py, lib/cylc/batch_sys_handlers/pbs.py, lib/cylc/batch_sys_handlers/sge.py, lib/cylc/batch_sys_handlers/slurm.py, lib/cylc/config.py, lib/cylc/scheduler.py, lib/cylc/task_proxy.py, lib/parsec/OrderedDict.py, lib/parsec/config.py, lib/parsec/fileparse.py, lib/parsec/util.py, lib/parsec/validate.py, tests/inheritance/00-namespace-list.t
This reduces parsec memory usage for configurations with lots of default settings. For a suite like this:
```ini
#!jinja2
[scheduling]
graph = shutdown => LOTS
[runtime]
[[shutdown]]
command scripting = "cylc shutdown $CYLC_SUITE_NAME; sleep 60"
[[LOTS]]
command scripting = echo MY_NUM
{%- for i in range(10000) %}
{%- set i_label = "%05d" % i %}
[[foo_{{i_label}}]]
inherit = LOTS
[[[environment]]]
MY_NUM = {{i}}
{%- endfor %}
```
it reduces total `cylc run` memory use by a factor of 2. It isn't quite as dramatic for some suites, though. It doesn't appear to significantly impact CPU usage.
When you have a parsec section with lots of defaults, the basic premise is that instead of copying them into the main configuration, you add a redirect reference to the defaults …
=> Reduce memory for suite configs with lots of defaults

lib/cylc/cfgspec/gcylc.py
gcylc currently aborts if no user config file is found - probably broken by #1556 .
=> The gcylc user config file should be optional.

lib/cylc/cfgspec/suite.py, tests/deprecations/00-all/suite.rc
#1398 deprecated "command scripting" etc.
A suite like this fails to validate:
```
[scheduling]
graph = foo
[runtime]
[[foo]]
command scripting = true
[[[dummy mode]]]
command scripting = true
```
with:
```
'Illegal item: [runtime][foo][dummy mode]command scripting'
```
This change applies the deprecation fix to the dummy mode items as well.
=> suite.rc: Add backcompat for dummy section entries.

bin/cylc-trigger
The old logic compares the localhost time with the timestamp of the job
file. A problem occurs when our desktops and our file system servers
have gone out of sync with time, with the file system servers being a
bit behind, so the old logic thinks that the job file is never updated.
The safer way to detect change is to look at the time stamp of the job
file before and after.
@hjoliver please review
=> cylc trigger --edit: fix timestamp cmp

lib/cylc/cfgspec/globalcfg.py, tests/cylc-cat-log/01-remote.t, tests/events/10-task-event-job-logs-retrieve.t, tests/events/11-cycle-task-event-job-logs-retrieve.t, tests/validate/41-mixed-syntax-global-suite.t
Validation of a `suite.rc` is currently failing if `global.rc` has
different date-time syntax for minutes intervals. This change fixes the
problem.
New test fails on current master (6.6.0).
@hjoliver @arjclark please review 1 and 2.
=> Allow suite.rc/global.rc to mix date-time syntax

lib/cylc/broadcast_report.py
Trying to make the broadcast error clearer when there is a mismatch in items set with the items in the suite. For example the name of the task.
=> cylc broadcast: error message clarification

lib/cylc/task_message.py, tests/cylc-message/00-ssh.t, tests/cylc-message/00-ssh/reference.log, tests/cylc-message/00-ssh/suite.rc, tests/cylc-message/test_header
On success, SSH messaging should not fall through to Pyro.
Fix #1582.
=> Fix SSH messaging fall through to Pyro

tests/cylc-cat-log/00-local.t, tests/events/task-iso/suite.rc, tests/events/task/suite.rc, tests/graph-equivalence/00-oneline.t, tests/graph-equivalence/01-twolines.t, tests/graph-equivalence/02-splitline.t, tests/graph-equivalence/03-multiline_and1.t, tests/graph-equivalence/04-multiline_and2.t, tests/runahead/no_final/suite.rc
The final tests in ```tests/graph-equivalence/*.t``` could fail due to the suite not being initialized before ```cylc show``` is called on it.
@matthewrmshin - please review 1.
=> Made graph equivalence tests etc. more stable.

doc/changes.html, lib/cylc/gui/app_gcylc.py
Closes #1566 
Adds a separator between poll and kill and forces a prompt to be raised in case of issuing a kill via the gui.
@benfitzpatrick - please review 1
@hjoliver - please review2
=> Add divider and force a prompt for kill

bin/cylc-suite-state, lib/cylc/dbstatecheck.py
From `cylc suite-state --help`:
```
The suite database does not need to exist at the time polling commences but allocated
polls are consumed waiting for it (consider max-polls*interval as an overall timeout).
```
However, on master polling aborts immediately if the db doesn't exist.  The intended behaviour is correct, as it means you don't have to start up interdependent suites in the right order.   Also tests in ```tests/authentication/``` are somewhat reliant on this (they start a suite daemon then immediately begin polling for a task to finish).
@matthewrmshin - please review 1.
=> Allow suite state polling before a run db exists.

doc/changes.html, lib/parsec/Jinja2Support.py, lib/parsec/__init__.py, lib/parsec/fileparse.py, tests/validate/42-jinja2-template-syntax-error-main.t, tests/validate/42-jinja2-template-syntax-error-main/suite.rc, tests/validate/43-jinja2-template-syntax-error-cylc-include.t, tests/validate/43-jinja2-template-syntax-error-cylc-include/suite-includeme.rc, tests/validate/43-jinja2-template-syntax-error-cylc-include/suite.rc, tests/validate/44-jinja2-template-syntax-error-jinja-include.t, tests/validate/44-jinja2-template-syntax-error-jinja-include/suite-includeme.rc, tests/validate/44-jinja2-template-syntax-error-jinja-include/suite.rc, tests/validate/45-jinja2-template-error-main.t, tests/validate/45-jinja2-template-error-main/suite.rc, tests/validate/46-jinja2-template-not-found.t, tests/validate/46-jinja2-template-not-found/suite.rc, tests/validate/47-jinja2-type-error.t, tests/validate/47-jinja2-type-error/suite.rc
This improves the output of some Jinja2 template error messages.
I've included some tests for the situations where Jinja2 doesn't provide
any line information.
The change to the list of exceptions that are handled is because
they inherited from the Jinja2 `TemplateError` anyway!
@matthewrmshin, please review 2.
=> parsec: jinja2 error reporting

tests/validate/45-jinja2-template-error-main.t
The test was Python 2.6 specific.
@benfitzpatrick - please review.  Was revealed by your #1593 (but not caused by it ... my Python version has gone up).
=> Fixed tests/validate/45-jinja2-template-error-main.t

lib/cylc/mp_pool.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/events/08-task-event-handler-retry.t, tests/events/08-task-event-handler-retry/suite.rc, tests/events/09-task-event-mail.t, tests/events/10-task-event-job-logs-retrieve.t, tests/events/11-cycle-task-event-job-logs-retrieve.t, tests/job-submission/05-activity-log.t
This is the 2nd part of #1591.
* Send single email for similar task events - less clutter up of your mail box on multiple failures.
* Group `rsync` commands by remote hosts to retrieve job logs.
The task proxy objects will now create the contexts for the task event handlers, but will not run them immediately. The task pool will loop through them, group similar items together, before adding the items to the process pool.
=> Group built-in task event handlers where possible

lib/cylc/run.py
The new start-up blurb can get screwed up by a narrow terminal window; this cuts its width down a bit.
Old:
```
,_,                                                               
| |                     The Cylc Suite Engine [6.6.0]             
,_____,_, ,_| |_____,               Copyright (C) 2008-2015 NIWA              
| ,___| | | | | ,___|  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
| |___| |_| | | |___   This program comes with ABSOLUTELY NO WARRANTY.   It is
\_____\___, |_\_____|  free software; you are welcome to redistribute it under
,___| |          certain conditions: "cylc warranty", "cylc conditions".
\_____| 
```
New:
```
,_,                                                       
| |            The Cylc Suite Engine …
```
=> Narrower start-up blurb.

lib/cylc/gui/updater_tree.py
Addresses @benfitzpatrick's reported error in https://github.com/cylc/cylc/issues/1564#issuecomment-127516311 
Simple suite to test with:
```
[scheduling]
graph = foo => bar => baz
[runtime]
[[foo,bar,baz]]
command scripting = sleep 50
```
Testing steps:
* run suite
* remove all reference to "bar" from the suite.rc file
* reload suite
* master should throw an error, this branch should handle it
N.B. I don't think this fixes all the issues reported in #1564
=> Fix gui ancestors KeyError.

tests/integer-cycling/00-satellite/suite.rc
This increases the timeout for this test suite.
Previously had been flakey in my environment as to whether or not the test would pass https://github.com/cylc/cylc/pull/1609#issuecomment-141375926
@hjoliver - please review.
=> integer-cycling satellite test: Increase timeout.

lib/cylc/network/connection_validator.py, tests/authentication/07-back-compat.t
This fixes #1578.
@matthewrmshin, please review 1.
@hjoliver, please review 2.
=> cylc authentication: don't report old client fails

conf/cylc-mode.el
Prevent warning from emacs:
http://stackoverflow.com/questions/24779041/disable-warning-about-emacs-d-in-load-path
=> Emacs cylc-mode: correct installation instructions

lib/cylc/gui/updater_graph.py
This fixes #1546.
Base nodes don't appear in the updater state summaries.
The updater state summaries are used to create a list of filtered-out ids,
so base nodes don't appear in that list, and can't be filtered out.
This change manually checks any base node name against the name
string filter, if it's given.
@kaday, please review 2.
=> cylc gui: fix graph view base name filter.

tests/cylc-cat-log/01-remote.t, tests/cylc-cat-log/02-remote-custom-runtime-viewer-pbs.t, tests/cylc-job-poll/02-loadleveler.t, tests/cylc-job-poll/03-slurm.t, tests/cylc-job-poll/04-pbs.t, tests/cylc-job-poll/05-lsf.t, tests/cylc-kill/00-kill-multi-hosts.t, tests/cylc-message/00-ssh.t, tests/cylc-poll/04-poll-multi-hosts.t, tests/cylc-scan/01-hosts.t, tests/cylc-submit/00-bg.t, tests/database/03-remote.t, tests/directives/00-loadleveler.t, tests/events/10-task-event-job-logs-retrieve.t, tests/events/11-cycle-task-event-job-logs-retrieve.t, tests/job-kill/01-remote.t, tests/job-kill/02-loadleveler.t, tests/job-submission/02-job-nn-remote-host.t, tests/job-submission/03-job-nn-remote-host-with-shared-fs.t, tests/job-submission/07-multi.t, tests/restart/13-bad-job-host.t, tests/vacation/01-loadleveler.t
Test battery was outputting extra error messages for skipped tests. This was mostly due to error messages from `cylc get-global-cfg`.
=> Fix tests error messages before skip alls

admin/get-repo-version, bin/cylc, bin/cylc-submit, lib/cylc/remote.py, lib/cylc/rundb.py, tests/vacation/00-sigusr1.t
This change speeds up suite and test-battery elapsed times.
It leads to fewer database commits and fewer calls to cylc.version,
both of which can be slow under certain circumstances. For example,
importing cylc.version under a cylc git clone can lead to a 0.5 second
overhead for each call to `cylc jobs-submit` and `cylc task message`.
I can now happily run the test battery with `-j 30`!
=> cylc performance: speed up suite elapsed time

lib/cylc/network/client_reporter.py
This closes #1623.
Client identify requests are not logged unless in debug mode.
There will be a warning logged if there is a really high rate of ID requests.
I've chosen >=1 per second over the last hour, but this is fairly arbitrary.
I've tested this by setting `CLIENT_ID_REPORT_SECONDS = 10` and launching
quite a lot of parallel cylc scans.
@matthewrmshin, please test and review 1.
@hjoliver, please review 2.
=> cylc scan: do not report id requests unless overwhelmed

lib/cylc/gui/app_gcylc.py
Close #1631.
Calls to `prog_bar_stop()` are made via `gobject.idle_add()` only if the prog bar is active.  Under load it is presumably possible for multiple callbacks to be queued before an idle period is reached.  Documentation of `gobject.idle_add()` http://www.pygtk.org/pygtk2reference/gobject-functions.html#function-gobject--idle-add says *If callback returns FALSE it is automatically removed from the list of event sources and will not be called again*.  I took this to imply that multiple calls would not be an issue, but I can artificially reproduce the bug by putting in an additional consecutive call to `gobject.idle_add(self.info_bar.prog_bar_stop)`, which shows we do need to be prepared for multiple calls to the stop method - which is what this fix does. 
@arjclark - please review.
=> Handle multiple calls to stop progress bar.

lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/events/10-task-event-job-logs-retrieve.t
The logic was not reading the setting correctly.
Also reduced the amount of internal object information going into the log.
=> global.rc: fix retrieve job logs retry delays

lib/cylc/batch_sys_manager.py
A bug introduced at 6.7.0 means that it was ignoring leading white
spaces. Fix #1628.
=> Fix remote job file parser for CYLC_DIR line

lib/cylc/rundb.py, tests/cylc-cat-log/03-bad-suite.t
`cylc cat-log 'bad-name' 'whatever.1'` was resulting in a trace back.
This change improves the error message.
Close #1637. @hjoliver @arjclark please review.
=> cylc cat-log: improve message on bad suites

doc/cug.tex, lib/cylc/cylc_xdot.py, lib/cylc/gui/updater_graph.py
This make graph mode more user friendly when there are lots of suicide triggers in a suites design.
=> cylc gcylc: ignore suicide triggers as default

lib/xdot.py
On my newer systems I've been getting a lot of this:
```
$ cylc graph foo
warning: xdot version 1.7, but supported is 1.6
```
This branch makes the same minor changes as https://github.com/jrfonseca/xdot.py/commit/cd75658cb56b2042433d62f4b6aa7dc84eaf3b5a
@matthewrmshin - please assign reviews.
=> Support xdot format 1.7

bin/cylc-graph
Prevented "make" and "cylc graph --help" if X Windows not available.
@matthewrmshin - please review (trivial).
=> Remove early gtk import

lib/cylc/config.py
Issue #1463 added the capability to fail cyclic dependencies when
validating a suite.  However, if the graphviz library is not available
the graphing_disabled flag is set, but not checked for the cyclic
dependency generation.  This results either an error with traceback
(for cylc 6.6.1) or a cryptic "global name 'graphing' is not defined'
error in 6.7.1 but the validation always fails.
This updates the cyclic dependence check to run only if the graphing
module was imported successfully.  If the graphing module is not
available, a warning message is printed out (even if the suite is
otherwise valid).
=> Fix validation error when graphviz is not available

bin/cylc-test-battery, tests/events/09-task-event-mail.t, tests/vacation/00-sigusr1.t
Remove and rebuild `*.pyc` files only if directory is writable.
Skip mail related tests if `mail` command not available.
=> Fix test battery on VMs

doc/siterc.tex, doc/suiterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/task_proxy.py, tests/events/08-task-event-handler-retry/suite.rc, tests/events/15-host-task-event-handler-retry-globalcfg, tests/events/15-host-task-event-handler-retry-globalcfg.t
Per-host task event handler retry delays was not enabled. This change
fixes it.
=> Fix host specific task event handler retry delays

bin/cylc-graph, doc/cug.tex, lib/cylc/cylc_xdot.py, lib/cylc/gui/updater_graph.py, tests/graphing/05-suicide-family.t, tests/graphing/05-suicide-family/graph.plain.ref, tests/graphing/05-suicide-family/graph.plain.suicide.ref
Hides the suicide triggers with cylc gcylc and cylc graph.
Option --show-graph for cylc graph so that it opens with the graph displaying.
=> cylc gcylc/graph: hide suicide triggers as default

bin/cylc-cat-log, doc/cug.tex, doc/gcylcrc.tex, doc/siterc.tex, lib/cylc/batch_sys_manager.py, lib/cylc/cfgspec/globalcfg.py, lib/cylc/gui/tailer.py
* Close #1659.
* New `cylc cat-log --tail` option.
* Cleans up a bunch of section heading format inconsistencies in the user guide site.rc reference
@matthewrmshin - please review 1 and assign review 2.  I'd like to get this in for 6.7.2 if possible.
=> Configurable job file tailer

tests/authentication/00-identity.t, tests/authentication/01-description.t, tests/authentication/02-state-totals.t, tests/authentication/03-full-read.t, tests/authentication/04-shutdown.t, tests/authentication/05-full-control.t, tests/authentication/06-suite-override.t, tests/authentication/07-back-compat.t, tests/cylc-cat-log/01-remote.t, tests/cylc-cat-log/02-remote-custom-runtime-viewer-pbs.t, tests/cylc-cat-log/05-remote-tail.t, tests/cylc-kill/00-kill-multi-hosts.t, tests/cylc-message/00-ssh.t, tests/cylc-poll/04-poll-multi-hosts.t, tests/cylc-submit/00-bg.t, tests/database/03-remote.t, tests/directives/00-loadleveler.t, tests/documentation/00-make.t, tests/events/10-task-event-job-logs-retrieve.t, tests/events/11-cycle-task-event-job-logs-retrieve.t, tests/events/15-host-task-event-handler-retry-globalcfg.t, tests/job-kill/01-remote.t, tests/job-kill/02-loadleveler.t, tests/job-submission/02-job-nn-remote-host.t, tests/job-submission/03-job-nn-remote-host-with-shared-fs.t, tests/job-submission/07-multi.t, tests/restart/13-bad-job-host.t, tests/vacation/01-loadleveler.t
Use quotes consistently around configuration settings for skip-all messages.
Remove random "Suite initializing..." messages.
@hjoliver please review. (2nd review not necessary?)
=> tests: improve messages

doc/cug.tex, lib/cylc/job_host.py, lib/cylc/scheduler.py, tests/restart/bad-job-host/suite.rc
~~Address~~ Close #1669. On failure to initialise the suite run directory of remote a job host, it should now print out the failed command, its return code, and its standard output/error.
=> cylc.job_host: more diagnostics on init failure

bin/cylc-monitor
The current align-column option is only useful for small suites, but for
larger suites using the monitor the current list of tasks is presented in
a non-intuitive order.  This changeset allows a command-line option to
sort the names of the task proxies (using standard Python string sort order)
before displaying in the text-based `cylc monitor`.
I'd really like it if the normal behavior was to have the sort turned on, but my goal with this initial PR is to create as minimal a change as required to test the functionality and get it merged.  There will be no arguments from me if the developers want to have this enabled by default!
It looks like the documentation gets automatically updated based on the help string, but please let me know if this change needs to be propagated elsewhere.
=> Sort task names in the text-based monitor.

lib/cylc/batch_sys_manager.py, lib/cylc/task_proxy.py
On a very slow share file system, suite daemon may be writing to the job
activity log while the NN link is being recreated by job submission.
This could bring down a suite. This chnage makes this less likely:
* NN link is now only recreated if necessary.
* Failing to write to the `job-activity.log` will no longer bring down
the suite.
=> Improve robustness on write to NN/job-activity.log

bin/cylc-monitor, doc/siterc.tex, lib/cylc/cfgspec/globalcfg.py
Sort by `[runtime]` definition order by default, alphanumeric by option.  Works with aligned and non-aligned display.
Follow up on #1676; close #1677.
@trwhitcomb - note definition order is the default to be consistent with the GUI. I suppose if you don't like this we could make the default sorting site/user configurable...
=> cylc monitor - sort by alphanumeric or definition order.

doc/siterc.tex, doc/suiterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/mp_pool.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/cylc-get-config/00-simple/section2.stdout, tests/events/16-task-event-job-logs-register-globalcfg.t, tests/events/16-task-event-job-logs-register-globalcfg/reference.log, tests/events/16-task-event-job-logs-register-globalcfg/suite.rc, tests/events/17-task-event-job-logs-retrieve-command, tests/events/17-task-event-job-logs-retrieve-command.t, tests/lib/bash/test_header
Allow retry when adding items to the `task_job_logs` table. A missing
`job.out` or `job.err` normally indicates a failure. The logic is
already part of retrieve-job-logs for remote jobs.
Register `job`, `job-activity.log` etc on job submission.
Also:
* configurable retrieve remote job logs command
* fix multi task event mail and job logs retrival reporting logic
Close #1655.
=> task job logs register retry delays

bin/cylc-check-triggering, tests/broadcast/08-space/suite.rc
This error has no consequence, except if a reference test run submits no jobs at all due to starting beyond the final cycle point, then it reports that the wrong log (new vs reference) had no triggering info in it.
Also fixes https://github.com/cylc/cylc/pull/1684#issuecomment-163004073, which revealed this problem (sets UTC mode for the test).
@matthewrmshin - one review should be enough for this.
=> Test battery: fix ref test log analyser args order.

lib/cylc/config.py
Need to do an `re.search` instead of an `re.match`.
(Fix message trigger related tests broken by #1695.)
Improve pattern to match a single pair of square braces.
=> Improve message cycle offset placeholder pattern

tests/cylc-submit/00-bg.t, tests/cylc-submit/00-bg/suite.rc
@matthewrmshin - this fixes a test that was passing for the wrong reasons here.  Site directives were not being used.  In the suite.rc the site directives are only used for loadleveler jobs, which seems odd (you might want to briefly consider how that affects your site?).
=> Fix a test - site directives not used.

lib/cylc/network/port_file.py
Address #1697 (whether or not we should close the issue remains to be seen...)
I'll merge this un-reviewed for today's release as it only changes a single error message string, and thus can't possibly have any deleterious effects!
=> Make local and remote port file exception messages consistent.

doc/cug.tex, lib/cylc/batch_sys_manager.py, lib/cylc/scheduler.py, lib/parsec/fileparse.py, tests/jinja2/08-local-lib-python.t, tests/jinja2/08-local-lib-python/Jinja2Filters/qualify.py, tests/jinja2/08-local-lib-python/lib/python/local_lookup.py, tests/jinja2/08-local-lib-python/suite.rc, tests/jinja2/08-local-lib-python/suite.rc.jproc, tests/job-submission/00-user/lib/python/my_background2.py, tests/job-submission/00-user/reference.log, tests/job-submission/00-user/suite.rc
Close #1675,
Local `lib/python` directory is appended to `sys.path` before the suite is parsed, to allow Jinja2 filters to use local python modules; and again for job submission processes, to allow custom job submission methods.  In the later case the deprecated `python` directory (no `lib/`) is still supported too.
@matthewrmshin - please assign reviews.
=> Support for local lib/python dir.

bin/cylc-suite-state, doc/cug.tex
Closes #1682 
Adds clarification that cylc suite-state doesn't support triggering off task messages to CLI and main manual documentation.
@hjoliver - please review. I don't think this needs a review 2 but feel free to assign a second reviewer if you think its appropriate.
=> Clarify cylc suite-state only works off states.

lib/cylc/scheduler.py
This should allow gcylc to detect normal shutdowns.
Close #1697.
@kaday @arjclark - please review.
It might still be *possible* for a suite to shut down before the GUI can read the final status update from the daemon, but I haven't seen that happen while testing this change - so I hope we can avoid having to read the suite logs to to detect a clean shutdown.
=> Do a final state summary update before shutdown.

bin/cylc-graph, lib/cylc/gui/graph.py, tests/graphing/08-ungrouped.t, tests/graphing/08-ungrouped/graph.plain.ref, tests/graphing/08-ungrouped/graph.plain.ungrouped.ref, tests/graphing/08-ungrouped/suite.rc
Currently we can't print an ungrouped graph with `cylc graph -O foo-graph.png foo` if suite `foo` has any task families (although we can do it via the GUI, of course). This provides an option to start with the graph ungrouped.
=> Graph viewer option to start ungrouped.

doc/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/network/connection_validator.py, lib/cylc/network/port_scan.py, lib/cylc/network/pyro_base.py, lib/parsec/util.py, lib/parsec/validate.py, tests/authentication/07-back-compat.t, tests/validate/50-fail-authentication-hashes.t
This change allows a site or user configuration of the hashing
algorithm used in Pyro communication. MD5 is not really recommended for
HMAC use, and is actually disabled on some POSIX systems.
Multiple hash algorithms are now allowed for both client and daemon.
The daemon can accept authentication in any of the configured hash
algorithms, and the client will work through any of the configured hash
algorithms until one works.
The default is SHA256 followed by MD5 as a fallback and for scanning.
This allows MD5 (old) suites to work - it preserves
old-client/new-daemon and new-scan-client/old-daemons.
Closes #1629.
=> cylc auth: allow hash choice, SHA256 by default

lib/cylc/batch_sys_handlers/at.py
It seems like `at` can throw a different error string when `atd` is not running. This change handles another known case.
=> Add another known *atd not running* warning string

lib/cylc/batch_sys_handlers/at.py, lib/cylc/batch_sys_handlers/background.py, lib/cylc/batch_sys_manager.py
When polling "at" jobs, if a job appears to have exited "atq", check PID
of job to see if it is still alive. In some systems, the job may not be
on "atq" while it is still running as a normal Unix process.
Close #1661.
=> batch sys: at: poll exit, poll PID is alive or not

lib/cylc/rundb.py
The current logic continues with the next query on any failure. In rare occasions, this may cause queries to be issued in the wrong order - causing the public database to be out of sync with the private one. This PR changes the logic to break out as soon as there is a failure. This should be safer on retry, as it will ensure that queries after the previous failure are issued in the correct order.
=> cylc.rundb: improve retry and diagnostics

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/view_dot.py, lib/cylc/gui/view_graph.py, lib/cylc/gui/view_tree.py
Addresses #1321 
Trigger (now and edit), poll and kill right-click menu options are now enabled/disabled based on the task state.
@hjoliver - please review 1
@kaday - please review 2
I've played around with a running suite to check things are working but you'll probably want to do some manual testing yourselves. Please also double-check I've covered the right states for these actions.
=> gcylc right-click menu specificity

lib/cylc/gui/updater.py
On suite stop, reset host and port for each pyro client.
Fix #1725. @hjoliver @kaday please review.
=> cylc gui: on suite stop, reset host and port

bin/cylc-ping, doc/siterc.tex, lib/cylc/network/suite_info.py
This is a follow on to #1700. The `scan hash` configuration is used for `cylc scan` for
better backwards compatibility with older daemons, and it needs to be used for `cylc ping`
for the same reasons. This avoids having a spurious connection denied warning in the suite
err log.
@hjoliver and @arjclark please review.
=> cylc ping: use 'scan hash' for communications

lib/cylc/gui/app_gcylc.py
Slight oversight from #1709.
This re-enables the view menu to allow viewing of pre-requisites for tasks that haven't run yet and instead disables job err/out/log etc. if it hasn't been run.
@matthewrmshin - please review 1
@hjoliver - please review 2
=> Re-enable view menu for viewing pre-reqs.

doc/cug.tex
Trivial pull request. Some links in the documentation are generating HTTP redirects. This pull request uses the destination link, rather than the one being redirected. I believe the Google Code link is the only one that is going to the wrong place. No other broken links in the documentation :grinning:
=> Fix link redirects (W3C Link Checker)

lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/state-dump/03-queued-no-repeats.t, tests/state-dump/03-queued-no-repeats/reference.log, tests/state-dump/03-queued-no-repeats/suite.rc
This fixes #1744 where the state file is continually dumped
if the task pool contains a queued task.
This is due to the ready_to_run check in process_tasks in scheduler.py
returning True if any task is queued and has reached its start time.
The fix is to only update the state summary if we really think
something has changed. This is a good thing to be doing anyway.
@hjoliver, @matthewrmshin please review.
=> Fix constant state dumps for queued tasks

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater.py
The gui was not using the poll schd delay scheme when started on stopped
suites, (i.e. if we launched the gui on a stopped suite, it would continue to poll every second).
This fixes the problem. (I have also improved the diagnostic for debug mode, and improved the pylint score for the cylc.gui.updater module.)
=> cylc gui: fix updater poll schd on stopped suite

bin/cylc-scan, lib/cylc/gui/gscan.py, lib/cylc/network/port_scan.py, lib/cylc/suite_host.py, lib/cylc/task_proxy.py
Memoize results of `is_remote_host` with a dict to prevent many network
related system calls, e.g. DNS lookups.
Functions in `cylc.suite_host` are now wrapped by a singleton object to improve
encapsulation and style.
Move `scan_all` from `bin/cylc-scan` to `cylc.network.port_scan`.
`cylc gscan` now uses the `scan_all` function in `cylc.network.port_scan` instead of subprocess calls to `cylc scan --raw`.
* Should benefit from the memoize logic in `cylc.suite_host` module.
* Now require no string parsing, only going down a data structure.
`cylc scan` fixes:
* `--owner=OWNER` did not work (but `-o OWNER` is fine) because `bin/cylc` modifies `--owner=OWNER` options to `--user=OWNER`. Option modified to `--suite-owner=OWNER` instead.
`cylc gscan` fixes:
* Typo that caused unnecessary `cylc …
=> cylc.suite_host: improve logic

doc/cug.tex, lib/cylc/task_pool.py, tests/events/16-task-event-job-logs-register-globalcfg.t, tests/events/16-task-event-job-logs-register-globalcfg/suite.rc
Previously, both `job.out` and `job.err` must exist to give an OK
condition. This is now relaxed to the existence of either `job.out` or
`job.err`.
=> Modify retrieve job logs OK condition

lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/reload/17-state-summary.t, tests/reload/17-state-summary/suite.rc, tests/startup/02-state-summary.t, tests/startup/02-state-summary/suite.rc
Follow-up to #1745, which it turns out was a little bit overzealous.  The state summary is not being updated at start-up until the first task state change (so a suite with no immediate active tasks stays in "initializing...", with no state to display, until a task triggers) or when a reload completes (so the GUI keeps reporting "reloading..." until a task triggers).
@benfitzpatrick, @matthewrmshin - please review.
Note my fix for the second problem is a bit ugly!  Alternative suggestions welcome, but we need to get this fix out pretty quickly.   For efficiency, in future we might want to separate this sort of simple global information from the task state summary updates, which might be time consuming in large suites.
=> Fix.state summary update

tests/cylc-scan/01-hosts.t
The test `tests/cylc-scan/01-hosts.t` was a bit flaky here, this fixes it. 
@matthewrmshin - this is trivial, one review will do.
=> Made cylc-scan test more robust.

lib/cylc/broker.py, lib/cylc/prerequisite.py, lib/cylc/task_proxy.py
This partially satisfies #1688.
It filters down the amount of `for` looping and comparisons by doing a set intersection on
known dependencies and outputs beforehand. It speeds up our 1000-tasks-per-cycle `dev/suites/busy`
suite by 50x!
@hjoliver, @matthewrmshin please review.
=> Speed up dependency matching

bin/cylc-copy, bin/cylc-monitor, bin/cylc-print, bin/cylc-refresh, bin/cylc-register, bin/cylc-reregister, bin/cylc-restart, bin/cylc-run, bin/cylc-submit, bin/cylc-unregister, bin/cylc-upgrade-db, lib/cylc/CylcOptionParsers.py, lib/cylc/gui/dbchooser.py, lib/cylc/network/port_scan.py, lib/cylc/network/pyro_base.py, lib/cylc/registration.py, tests/cylc-refresh/00-title.t, tests/cylc-refresh/00-title/reference.log, tests/cylc-refresh/00-title/suite.rc, tests/cylc-refresh/test_header
It was nuking the passphrase by doing an unregister and a new register
on suite title change. This is not necessary, and on running suites,
will cause subsequent client commands to fail.
Also modified `cylc.registration` to improve its pylint score.
The new test would time out before this change, because the refresh
command would reset the passphrase, which would make it impossible for
subsequent task jobs to report progress back to the suite.
Related to metomi/rose#1846. @hjoliver @arjclark please review.
=> cylc refresh: don't nuke passphrase on title change

lib/cylc/config.py
The current edge comparison routine under validation used to check for cyclic dependencies is inefficient. For suites with very large numbers of inter task dependencies e.g. LARGE_FAM1:succeed-all => LARGE_FAM2 the current calculation means the suite is effectively un-validatable. Solves point 2 of #1776
This dramatically speeds up the comparison by reducing it to (effectively) order N from order ~N**2
In the case of the real user suite it gets the calculation down from 2.5+ hours (estimate based on the chunk I ran before giving up and assuming it can be read into memory) to 1 second.
@matthewrmshin - please review1
@hjoliver - please review2
=> validation: Reduce O(N**2) edge comparison to O(N)

lib/cylc/gui/app_gcylc.py
Open gcylc for a stopped suite, first use of the Run dialog results in this warning message:
```
/home/oliverh/cylc/cylc.git/lib/cylc/gui/app_gcylc.py:1936:
GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
vbox.pack_start(hbox)
```
A Gtk.HBox was being packed into the same container twice.  This fixes it.  @matthewrmshin - one review should be enough on this.
=> Fixed twice-packed Gtk box.

lib/cylc/daemonize.py, lib/cylc/scheduler.py
The pgrep command suggested for detecting running suites was broken.  This fixes it, and makes it print full info for just the parent process (instead of just PID for parent and all sub-processes), and also suggests `scan` and `ping` commands that work from other hosts.
Example output:
```
ERROR: port file exists: /home/oliverh/.cylc/ports/foo
If foo is not running, delete the port file and try again.  If it is
running but not responsive, kill any left over suite processes too.
To see if foo is running on 'niwa-34403.niwa.local:7766':
* cylc scan -n '\bfoo\b' niwa-34403.niwa.local
* cylc ping -v --host=niwa-34403.niwa.local foo
* ssh niwa-34403.niwa.local "pgrep -a -P 1 -fu $USER 'cylc-r.* \bfoo\b'"
'ERROR, port file exists: /home/oliverh/.cylc/ports/foo'
```
And for the suggested …
=> Fix and improve suite find info in run/restart stdout.

lib/cylc/gui/gscan.py
closes #1785 
`gtk.MenuItem` uses underscores to mark mnemonics, behaviour can be escaped by using a double underscore.
@arjclark Please Review
=> Fixed problem with underscores in suite names.

doc/cug.tex
Corrects a typo of:
```
$CYLC_TASK_TRY_NUBMER
```
to:
```
$CYLC_TASK_TRY_NUMBER
```
@hjoliver - please review.
=> Fix typo in docs

lib/cylc/task_proxy.py, tests/job-submission/11-garbage-host-command.t, tests/job-submission/11-garbage-host-command/reference.log, tests/job-submission/11-garbage-host-command/suite.rc
Otherwise, a job entry will be missing from the task_jobs table in the
runtime database if, e.g. a host select command fails.
=> Insert an entry of task_jobs at earliest

lib/cylc/rundb.py, tests/database/04-lock-recover.t, tests/database/04-lock-recover/suite.rc
~~Commit as soon as statements are executed correctly - should reset roll back point.~~
~~Roll back as soon as statements are not executed correctly - should prevent roll back of more statements than intended.~~
Commit and delete all queued items only on success. Roll back if anything dies, and retry all queued items next time. This ensures statements are never missed on retry.
Print statement diagnostics on DB connect error for write.
@hjoliver please take an initial look.
=> cylc.rundb: improve commit/rollback logic

lib/cylc/batch_sys_manager.py, lib/cylc/task_proxy.py
Loadleveler job poll failing in 6.8.1:
```
2016-03-16T10:55:52+13 ERROR - 2016-03-16T10:55:52+13 [jobs-poll cmd] cylc jobs-poll --host=wrh-1.hpcf.niwa.co.nz -- '$HOME/cylc-run/foo/log/job' 1/foo/01
2016-03-16T10:55:52+13 [jobs-poll ret_code] 1
2016-03-16T10:55:52+13 [jobs-poll err]
File "/home/oliverh/cylc/cylc.git/bin/cylc-jobs-poll", line 43, in <module>
main()
File "/home/oliverh/cylc/cylc.git/bin/cylc-jobs-poll", line 37, in main
BATCH_SYS_MANAGER.jobs_poll(args[0], args[1:])
File "/gpfs_hpcf/filesets/hpcf/home/oliverh/cylc/cylc.git/lib/cylc/batch_sys_manager.py", line 321, in jobs_poll
job_log_root, batch_sys_name, my_ctx_list)
File "/gpfs_hpcf/filesets/hpcf/home/oliverh/cylc/cylc.git/lib/cylc/batch_sys_manager.py", line 638, in _jobs_poll_batch_sys …
```
=> Fix polling of jobs submitted to Loadleveler.

lib/cylc/task_proxy.py, tests/lib/bash/test_header, tests/task-proc-loop/00-count.t, tests/task-proc-loop/00-count/suite.rc, tests/task-proc-loop/test_header
Close #1787 
New logic explained by the new in-source comment.
Test battery passes here.
@matthewrmshin - please review/assign
(I can probably make a new test for this, that relies on counting logged iterations through the main scheduling loop in a suite with two tasks - one queued task and one running ... but that'll have to be tomorrow).
=> Don't repeatedly mark queued tasks as ready to run.

bin/cylc-unregister, lib/cylc/registration.py, tests/registration/03-skip-run.t, tests/registration/04-pattern.t, tests/registration/05-unregister-delete.t
Also ensure that `cylc unregister bar` does not unregister a suite
called `foobar`.
Close #1796.
=> cylc unregister: skip suites with port files

bin/cylc-monitor, lib/cylc/dump.py, lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater.py, lib/cylc/network/suite_state.py
A minor refactor to give suite status the same treatment as task status in #1775.
@matthewrmshin - please review and/or assign.  Note that this branch includes the (small) changes in #1805.  It was meant to be a second commit on that PR, but I forgot to push the change up before you reviewed it.  If you like, leave this till 1805 is merged then I'll rebase this.
=> Use string constants for suite status.

lib/cylc/task_proxy.py
This change reduces the time taken to submit a minimal task by around 40% in a modified 'busy' suite (would be more for larger tasks?) on a fast filesystem. (When the filesystem is slow, more of the time will be taken in writing the job script file).
For extremely active suites (100s of 1 second tasks active at once) the pdeepcopy and poverride here can be one of the dominant costs. I find it amazing how much time it takes just to move or re-organise data structures!
The rtconfig is chucked away in the `set_from_rtconfig` method that follows, so I don't think this saves memory in the long run.
The speedup won't apply if there are broadcast overrides, so some of our larger suites that use broadcasts of reservation ids for each task, etc, won't benefit.
@arjclark, @matthewrmshin please …
=> task proxy: reduce unnecessary rtconfig deepcopy on submit

bin/cylc-restart, bin/cylc-run, lib/cylc/network/task_msgqueue.py, lib/cylc/run.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py
Each task currently has its own individual message queue, which contains a relatively expensive `Queue.Queue` object. As we get more and more tasks in a suite, this becomes increasingly unwieldy to keep in memory and to keep checking for new messages.
This change rolls the queues up into a single task pool message queue. It saves around 20% of the per-task memory for the minimal tasks I've tested, which is around 10% of the total memory usage - a surprising amount. The CPU usage is reduced by a couple of percent for a 'super-busy' suite, largely just due to not calling `qsize` as much.
Due to the communication change, this will break daemon-task mismatched versions before and after this PR, so I've initially put this in the `soon` milestone.
I've also added a proper profiling behaviour on …
=> cylc task-message: unified message queue

lib/cylc/network/suite_state.py
This change roughly halves the cost of updating of suite state summaries, which is our old expensive friend, and (still) usually the dominant cost in an active suite. 
Some of the expensive stuff has been moved to a new method, purely for profiling reasons and for later speed ups.
The speed up mostly comes from doing fewer, more targeted loops and from avoiding as many `.items()` calls, which the profiler alleges to be expensive (may just be profiler overhead - not sure).
@matthewrmshin, @kaday please review.
=> cylc.network.suite_state: speed up updating

lib/cylc/task_pool.py
This speeds up the `process_queued_db_ops` method by around 40% (for the modified busy suite on a fast filesystem). The for loop and the calls to `sorted` and `items` cost a fair bit (according to the profiler) in the null dictionary case.
@arjclark, @hjoliver please review.
=> cylc.task_pool: speed up queued db ops

lib/cylc/config.py, lib/cylc/task_id.py
It was attempted in #1779 but the fix had a speed issue. This attempt
improves the speed and reduces the complexity of the original fix.
@arjclark @hjoliver please review.
=> cylc validate: improve family name validate

lib/cylc/prerequisite.py, lib/cylc/task_proxy.py
This adds some caching to speed up task proxy `ready_to_run`.
(By the way, all these speed up PRs are coming from a single branch I've been working on for a few weeks. I've decided to split it up into related pieces.)
If a task doesn't have conditional prerequisites, then we can simply cache the 'am I satisfied' result instead of rechecking it every loop. We only normally need to recheck it once one or more relevant outputs have been found in `satisfy_me`.
I've moved the conditional expression checking into its own method for neatness and ease of future profiling - I wonder how much it costs if we have lots of 'OR' dependent tasks!
This reduces the cost of calling `ready_to_run` (another dominant cost in a modified `busy` suite with lots of waiting tasks) by around two thirds.
@hjoliver, …
=> task_proxy: cache prereq status for speed

lib/cylc/dump.py, lib/cylc/network/suite_state.py
Follow up #1815, which follows up #1806 
This restores the individual components of the suite status string to the summary dict, so that the change now works for both old client + new daemon and new client + old daemon.
It also addresses two earlier feedback comments: https://github.com/cylc/cylc/pull/1806#discussion_r60707128 and https://github.com/cylc/cylc/pull/1815#discussion_r61218720
@matthewrmshin - please review and/or assign.
=> new suite status string - back compat both ways

lib/cylc/gui/app_gcylc.py
The stop point entry box text was not read due to a premature
`window.destroy` statement.
@arjclark @benfitzpatrick please review.
=> gcylc: fix insert dialog stop point not read

bin/cylc, bin/cylc-refresh, lib/cylc/config.py, lib/cylc/scheduler.py
Allow `cylc test battery` to pass on Ubuntu 16.04LTS.
@hjoliver please review (and please feel free to reassign milestone to next-release).
=> Improve style to pass PEP8 1.7.0

lib/cylc/graphnode.py, lib/cylc/poll_timer.py, lib/cylc/prerequisite.py, lib/cylc/task_outputs.py, lib/cylc/task_proxy.py, lib/cylc/task_trigger.py, lib/cylc/taskdef.py
These things are great. We freeze the possible attributes of a class (fine, since we nearly always declare everything in the init method anyway) and in return, the memory penalty from our thousands of instances of smallish classes drops to practically nothing.
This change reduces the daemon memory usage by a third in my 10000 tasks/cycle busy suite.
https://docs.python.org/2/reference/datamodel.html#slots
http://stackoverflow.com/questions/472000/python-slots
I thought about adding `__slots__` for the task proxy class itself - maybe later. I think there could be scope for doing this for our `OrderedDictWithDefaults` parsec class, but that depends on the ancestor classes having slots set (not sure that's true for the `collections` `OrderedDict`).
I also moved the `PollTimer` class away …
=> Use class __slots__ to reduce daemon memory use

lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/reload/18-remove-add-alter-task.t, tests/reload/remove-add-alter-task/reference.log, tests/reload/remove-add-alter-task/suite.rc
This closes #1759. A task that became a reload orphan always stayed an orphan in future reloads and couldn't be changed via reload.
It also fixes a small issue I found when debugging - reload in itself doesn't trigger a state summary update. This isn't always necessary (e.g. when just altering the runtime) but seems like a good idea.
@arjclark, @hjoliver please review.
=> Fix reload-alteration of a reload-removed then reload-added task

bin/cylc-restart, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/reload/16-waiting/suite.rc
Close #1818 - simplify reload logic by not delaying reload of active tasks. Instead just log a warning that the job is already active under the old settings.
Now preserves task outputs across the reload, so there's no need for the delayed reload any more even if task outputs are changed in the reloaded suite definition.
=> Don't delay reload of active tasks.

lib/cylc/gui/updater.py
Close #1750.
Turns out this "idle" speculation was correct: https://github.com/cylc/cylc/issues/1750#issuecomment-192091119
`git blame` suggests the problem was introduced first in Dec 2015, by f3e65f4
@matthewrmshin - please review/assign.
I'd like to get this out quickly in the next minor release as it has been a somewhat maddening problem!
=> gcylc updater: change title bar by idle_add.

lib/cylc/gui/updater_dot.py, lib/cylc/gui/updater_graph.py, lib/cylc/gui/updater_tree.py
Close #1840. 
I've checked that this change restores normal CPU loading, and keeps the right-click menu fix of #1781 (note I found an easier way to reveal that bug: https://github.com/cylc/cylc/issues/1781#issuecomment-219217889).
@matthewrmshin - please review/assign
=> gcylc CPU load fix: unset updater action flags

bin/cylc
I just noticed that since f81ee558  (cylc-6.7.3 Nov 2015) "cylc help" is printing command summaries as tuples, e.g.:
```
$ cylc help prep
CATEGORY: preparation - Suite editing, validation, visualization, etc.
HELP: cylc [preparation] COMMAND help,--help
You can abbreviate preparation and COMMAND.
The category preparation may be omitted.
COMMANDS:
('5to6', '...........', 'Improve the cylc 6 compatibility of a cylc 5 suite file')
('diff|compare', '...', 'Compare two suite definitions and print differences')
('edit', '...........', 'Edit suite definitions, optionally inlined')
('graph', '..........', 'Plot suite dependency graphs and runtime hierarchies')
('graph-diff', '.....', 'Compare two suite dependencies or runtime hierarchies')
('jobscript', '......', 'Generate a task job script and …
```
=> Fixed format of 'cylc help' command summaries.

lib/cylc/registration.py, tests/authentication/11-suite2-stop-suite1.t
It was loading the passphrase of the current suite, instead of the
passphrase of the target suite.
Fix #1843.
=> Fix suite client call from task of another suite

doc/cug.tex, doc/gscanrc.tex, lib/cylc/cfgspec/gscan.py, lib/cylc/gui/gpanel.py, lib/cylc/gui/gscan.py
Closes #1830 
Closes #1834 
Added gscan.rc config file, currently it configures:
- The data columns for `cylc gscan`.
- Whether `cylc gpanel` activates on startup or not.
If you can think of any other behaviour that could be described by this file please comment.
=> gscan, gpanel: gscan.rc config file.

tests/cylc-job-poll/03-slurm.t, tests/directives/slurm/suite.rc, tests/job-kill/03-slurm/suite.rc
The directives here don't make a lot of sense (I've learnt quite a lot more about Slurm since writing these tests...). The Slurm default is to have 1 task, so these were redundant.
=> cylc test-battery: tidy Slurm directives

lib/cylc/task_state.py, tests/cylc-trigger/06-reset-ready.t, tests/cylc-trigger/06-reset-ready/reference.log, tests/cylc-trigger/06-reset-ready/suite.rc
A manually triggered task should have its outputs reset to all incomplete.
Fix #1852.
@benfitzpatrick @hjoliver please review.
=> Triggering a task should reset its outputs

doc/gcylcrc.tex, lib/cylc/cfgspec/gcylc.py, lib/cylc/gui/app_gcylc.py, lib/cylc/gui/view_tree.py
Closes #934 (bullet two)
Closes #817 
Closes #1622 
Added the following settings to gcylc.rc:
- `sort column` (#1622)
- `sort column ascending` (#1622)
- `transpose dot` (#934)
- `transpose graph` (#934)
- `window size` (#817)
Open to suggestions for better names for these settings.
=> gcylc.rc enhancements

bin/cylc-insert, lib/cylc/gui/app_gcylc.py, lib/cylc/task_id.py, tests/cylc-insert/10-wildcard.t, tests/cylc-insert/10-wildcard/reference.log, tests/cylc-insert/10-wildcard/suite.rc
#1814 has been too strict when checking the argument to `cylc insert`. This change relaxes the check.
=> cylc insert: wildcard OK in task ID arguments

lib/cylc/scheduler.py
By moving the logic to process the command queue to an earlier position
in the main loop.
Allow an inserted task to be released from the runahead pool so that it
is listed as a waiting task by the GUI. Previously, it would be listed
as a runahead task, and a nudge would be needed to release it to the
pool.
=> Nudge insert

conf/cylc.lang, conf/cylc.xml, doc/siterc.tex, doc/suiterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/events/23-suite-stalled-handler.t, tests/events/23-suite-stalled-handler/reference.log, tests/events/23-suite-stalled-handler/suite.rc, tests/events/24-abort-on-stalled.t, tests/events/24-abort-on-stalled/reference.log, tests/events/24-abort-on-stalled/suite.rc
Close #1286 
First pass attempt at implementing a suite stalled handler.
This takes a look at the current task pool and if no tasks are active, submitting (ready), queued or awaiting a clock trigger then the suite is deemed to have stalled. Given the way the scheduler loop runs, the "am I stalled" check needs to indicate a stalled state for two consecutive loops in order to fire off the stalled handler/abort on stalled. This captures where a state has updated to succeeded/failed but the follow on task has yet to trigger (happening in the next scheduler loop).
@hjoliver - can you take an initial look through and see if you think I've missed anything? If you're happy then I'll start writing tests, documenting etc.
=> Implement suite stalled handler.

tests/cylc-kill/02-submitted/suite.rc
Ensure that the started message from killer task is sent and received
before issuing the kill command. This prevents the kill command from
killing the killer task itself.
The test has become a bit flaky, possibly due to #1855.
=> Fix cylc-kill test 2

lib/cylc/task_pool.py
As reported by @dpmatthews I neglected to cater for held tasks which can result in an unhelpful stalled suite handler triggering if you start the suite in held status.
@matthewrmshin - please review. Not sure if it needs a review 2 given how simple the fix is - up to you.
=> stalled handler: Cater for held tasks.

tests/events/25-held-not-stalled.t, tests/events/25-held-not-stalled/suite.rc
Test abort on stalled setting when a suite is started up with --hold.
Test for #1860. @arjclark please review.
The test suite will stall and die with the version just before #1860, but will release itself on timeout with current HEAD.
=> t: abort on stalled with --hold

lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/utils.py, tests/cylc-get-site-config/01-defaults.t, tests/validate/54-null-timeout.t
Close #1865 
@arjclark - can you review & reassign (Matt says he's away for the rest of the week).
=> Allow explicit empty config values for intervals.

lib/cylc/daemonize.py, lib/cylc/scheduler.py
And after configuring Pyro daemon. This should make sure that we cannot run 2
suites simultaneously on the same directory by accident.
The problem this fixes can be serious after #1847.
=> Scheduler.start: check port file exists at start

lib/cylc/cycling/iso8601.py
This addresses part of #1053.
I did have a more elegant partial solution, which this pull request is too small to contain.
This one is OK.
@arjclark, please review and test.
@hjoliver, please review 2.
=> Cache recent points for get_next_point speedup

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater.py, lib/cylc/gui/updater_graph.py, lib/cylc/gui/updater_tree.py, lib/cylc/gui/view_tree.py
Rename `Reset Connection Polling` to `Reset Connection Schedule` to avoid terminology confusion (with polling of task jobs).
Add tool button for `Reset Connection Schedule`.
Set sensitivity of `Reset Connection Schedule` to True only when suite is stopped.
Reconnection count down in ISO8601 duration next to last update time.
Partially address #1576. @hjoliver @benfitzpatrick please review.
=> gcylc: count down to next reconnect attempt

conf/cylc-mode.el, conf/cylc.xml
Closes #1573 
Added syntax highlighting to kate and emacs for multi-line jinja2 comment strings of the form:
```
{# foo bar
baz #}
```
=> cylc syntax highlighting: support multiline Jinja2

doc/cug.tex, lib/cylc/config.py, tests/cyclers/44-icp_fcp_notation.t, tests/cyclers/44-icp_fcp_notation/suite.rc
Closes #1038 
Sections can now be specified like:
- `[[[ R1/^+PT1H ]]]`
- `[[[ R1/$-PT1H ]]]`
=> special notation for initial and final cycle points

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater_tree.py, lib/cylc/gui/view_dot.py, lib/cylc/gui/view_graph.py, lib/cylc/gui/view_tree.py
Closes #1536 
For multiple selection the right click context menu yields all the normal items minus:
- Browse task URL
- View
- Trigger (edit run)
For multiple selection the following right click items are greyed out unless the action is valid for all tasks in the selection:
- Trigger (run now)
- Poll
- Kill
=> cylc gui: enabled multiple selection in tree view

bin/cylc-submit, bin/cylc-trigger, lib/cylc/batch_sys_manager.py, lib/cylc/job_file.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py
`job_conf` in `TaskProxy`:
* is now a local variable with very limited scope.
* will no longer be populated for poll/kill.
Motivation: while looking at the logic for #1413, it appears that we have been populating `job_conf` for poll/kill for no reason. (It has not been necessary for a while now.) With that gone, the only remaining purpose of `job_conf` is for writing the job file, so it will now only be generated just before writing the job file.
(I think part 2 will be to see if we can remove `job_conf` all together.)
=> job_conf related logic refactor part 1

lib/cylc/network/pyro_daemon.py
Close #1890.
@matthewrmshin - I think your passphrase utility refactor somehow exposed this bug rather than caused it.  It does seem to result from Pyro threads still running and raising a routine exception (it happens constantly as a suite runs) - as the traceback says - when the Python interpreter is in the process of shutting down, hence the bizarre uncaught exception behaviour.  The solution we discussed doesn't work, it just causes other problems.  I found a Pyro method that explicitly joins the threads.  Haven't seen any adverse side-effects in testing.
=> Force Pyro threads to join before shutdown.

lib/cylc/task_proxy.py, tests/job-submission/13-tidy-submits-of-prev-run-remote-host.t
Don't try to remove `NN` with `rmtree`.
Ignore `rmtree` errors.
This should fix job submission tests 13 and 14.
=> Tidy submits of previous runs on suite host

lib/cylc/gui/updater_dot.py, lib/cylc/gui/view_dot.py, lib/cylc/gui/view_graph.py
Closes #132 
Families can now be expanded/collapsed in the dot view.
=> gcylc dot-view: collapse and expand individual namespaces

bin/cylc-scan
Close #1912
Test with `cylc scan -c`.
@matthewrmshin - please review or assign.
=> Fixed typo in scan CLI colour code.

lib/cylc/config.py, tests/validate/55-missing-parentage.t, tests/validate/55-missing-parentage/suite.rc
This fixes a problem where a suite with a null string for a task inherit option will produce the following traceback on validate:
```
File "/opt/cylc/bin/cylc-validate", line 124, in <module>
main()
File "/opt/cylc/bin/cylc-validate", line 73, in main
write_proc=not options.nowrite)
File "/opt/cylc/lib/cylc/config.py", line 149, in get_inst
vis_start_string, vis_stop_string, mem_log_func)
File "/opt/cylc/lib/cylc/config.py", line 316, in __init__
self.compute_family_tree()
File "/opt/cylc/lib/cylc/config.py", line 839, in compute_family_tree
if pts[0] == "None":
IndexError: list index out of range
```
It now produces a nice `ERROR: null parentage for foo`.
The new test is a copy of tests/validate/07-null-parentage.t, but with the necessary change to the …
=> cylc validate: better error for blank inherit

tests/job-kill/03-slurm/suite.rc
This fixes some redundant directives in the Slurm job-kill test that can cause it to fail.
Cylc sets good defaults for these directives anyway.
@arjclark, please review.
=> cylc test-battery: remove redundant Slurm output file directives

lib/cylc/gui/gscan.py, lib/cylc/network/suite_identifier.py, lib/cylc/network/suite_state.py
Closes #1244 
Added tooltip text for the status indicators in gscan. The 5 most recent tasks are displayed, ordered by the most recent of `submitted_time_string`, `started_time_string` and `finished_time_string`. If the row is displaying tasks at a given cycle point the tooltip will show only tasks at that point.
=> gscan: information on hover.

lib/cylc/task_proxy.py
No reason to use a custom class when all keys are unique, and when ordering does not matter. I have also removed the `'submission try number'` entry, as it is not used by anything.
1st follow-on from #1880.
=> cylc.task_proxy: job_conf is now normal dict

bin/cylc-remove, tests/cylc-remove/02-cycling.t, tests/cylc-remove/02-cycling/reference.log, tests/cylc-remove/02-cycling/suite.rc
This fixes the bug revealed by Jerry on the cylc group today - `cylc remove` should force a task to spawn its successor before removal, by default - and provides a test to maintain the behaviour (our existing "remove" tests were based on non-cycling suites so didn't catch this).
@matthewrmshin - it appears this was caused by command arg backward compatibility concerns in #1715 .  I'm not sure my change is the cleanest way to fix it.  Can you also consider if the few other instances of `_=None` args you introduced there are ok?
=> Fix spawn before remove. 

lib/cylc/scheduler.py, tests/reload/20-broadcast-insert.t, tests/reload/20-broadcast-insert/reference.log, tests/reload/20-broadcast-insert/suite-2.rc, tests/reload/20-broadcast-insert/suite.rc
Before this change, suite would die when:
* Reload with a new task.
* Broadcast an unrelated setting.
* Insert the new task at a cycle point that has the broadcast setting.
This change ensures that `linearized_ancestors` in the broadcast server is renewed after a reload.
=> Fix insert new task after a reload+broadcast

lib/cylc/task_state.py
This simple change should fix #1600. It is, however, extremely difficult to write a reliable test - as it relies on the timing in the main loop of the scheduler.
=> Don't reset task outputs on retry

bin/cylc-version, conf/cylc-bash-completion
Closes #667 
Implements basic tab completion of cylc commands. Required the addition of a `--long` option to cylc version in order to get the path to the cylc bin directory.
@oliver-sanders @hjoliver please review.
=> cylc tab completion.

lib/cylc/task_pool.py, tests/events/10-task-event-job-logs-retrieve.t, tests/events/15-host-task-event-handler-retry-globalcfg.t
Reduce event handler failure (retries exhausted) to WARNING.
Only report attempt 1 if there is a delay.
Only report attempt 1 and retries on debug mode.
=> Increase task event handler (re)try log levels

lib/cylc/config.py, tests/validate/57-hyphen-finish.t
Something like this was failing to validate. This change fixes the issue.
```
graph = foo-bar:finish => baz
```
=> Fix graph: foo-bar:finish now validates

lib/cylc/batch_sys_manager.py, lib/cylc/task_pool.py, tests/shutdown/06-kill-fail.t, tests/shutdown/06-kill-fail/suite.rc
Ensure `cylc jobs-kill` produces output on missing `job.status` file.
Ensure callback of `cylc jobs-kill` works without standard output.
(The symptom was that `cylc stop --kill` causes the suite to attempt kill continuously if `cylc jobs-kill` returns no sensible standard output.)
@benfitzpatrick @arjclark please review.
=> Fix stop --kill on jobs-kill command fail

INSTALL.md
Was going to install cylc again on a new notebook, but the documentation link is actually going to the project home page. I think that's the correct URL.
Thanks
ps: the site changed since the last time I accessed it, and it's looking great. Kudos!
=> Fix documentation guide link in the INSTALL.md file

lib/cylc/cfgspec/suite.py
#1929 upgrade logic is causing issues. (I think it is caused by an ordering problem not revealed by my previous tests.)
Old configuration sections need to be deprecated with no new settings then removed.
=> Fix #1929 configuration upgrade logic

.travis.yml, lib/cylc/gui/updater_dot.py, requirements.txt, tests/database/00-simple.t, tests/ext-trigger/00-satellite/suite.rc, tests/pre-initial/warm-insert/suite.rc
Follow-up (after a bit of a delay!) to #1137.  This gets the whole test battery passing on Travis CI, include graphing and related tests that require GTK import and an X environment (I'm using Xvfb).  Only platform-specific tests get skipped, and four tests that need mail functionality.  @ScottWales - maybe you could take a quick look at this in case I've done anything silly?
(For @cylc/core - Travis CI set-up is very easy, just log in to www.travis-ci.org with GitHub credentials and allow access to your cylc fork), then any commit pushed to GitHub will cause the test battery to run.  I may have to separately configure it to respond to pull requests on the master repo, once this PR is merged...)
=> Travis CI config update - run the whole test battery.

lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/cfgspec/utils.py, lib/cylc/config.py, lib/cylc/job_file.py, lib/cylc/scheduler.py, lib/cylc/syntax_flags.py, lib/cylc/task_proxy.py, lib/parsec/util.py, lib/parsec/validate.py, tests/config-log/00-basic.t, tests/cylc-get-config/00-simple.t, tests/cylc-get-config/00-simple/section1.stdout, tests/cylc-get-config/00-simple/section2.stdout, tests/cylc-get-config/02-cycling.t, tests/cylc-get-config/02-cycling/suite.rc, tests/cylc-get-config/03-cycling-compat.t, tests/cylc-get-config/03-cycling-compat/suite.rc, tests/inheritance/00-namespace-list.t, tests/validate/55-missing-parentage/suite.rc
The configuration generated by `cylc get-config` and in a suite's `~/cylc-run/SUITE/log/suiterc/` should now pass `cylc validate`.
Ability to skip printing settings with `None` values.
Duration will now be dumped in ISO8601 format by default.
Improve quoting of values in lists.
Triple quote multi-line values.
Allow empty values for settings expecting a set of predefined strings.
Settings expecting `int`, `float` and `boolean` are now set to `None` if given empty values.
If an `inherit` setting has an empty value, it will default to `inherit = root`.
4 spaces indent instead of 3.
And some style updates to pass pylint and pep8.
Close #1915.
=> Improve configuration dumping logic

examples/polling/suite.rc, lib/cylc/cfgspec/suite.py, lib/cylc/syntax_flags.py, tests/cyclers/34-implicit-back-compat.t, tests/cylc-5to6/00-simple-start-up.t, tests/lib/bash/test_header, tests/repeated-items/00-one.t, tests/special/04-clock-triggered.t, tests/special/05-clock-triggered-utc.t, tests/special/06-clock-triggered-iso.t, tests/special/08-clock-triggered-0.t, tests/special/clock/suite.rc
We should add deprecation warnings for the nearly-2-years-old cylc 5 syntax.
=> Deprecate cylc 5 cycling syntax

.travis.yml, lib/cylc/scheduler.py
Fix a logic bug whereby the stalled checks weren't being run in the absence of a site config.
@matthewrmshin - please review 1
@hjoliver - please review 2/reassign
=> Fix logic bug leading to test battery issue.

lib/cylc/cfgspec/suite.py, lib/cylc/config.py, lib/cylc/task_proxy.py, lib/cylc/taskdef.py, tests/cylc-get-config/00-simple/section1.stdout, tests/spawn-max/00-basic.t, tests/spawn-max/00-basic/reference.log, tests/spawn-max/00-basic/suite.rc, tests/spawn-max/test_header
Close #1904.  Allows tasks to run out of order.  See the discussion in #1538.  
I decided against the "interim fix" of spawning two cycles ahead because it turns out to be quite difficult, and downstream stalls can still occur (it just takes two failures instead of one).  Instead, as advocated by @benfitzpatrick and @matthewrmshin in #1538, on this branch you can set `[scheduling]spawn to max active cycle points` (...which is pretty self-descriptive).
This makes cylc behave exactly "as advertised" (no implicit dependence on previous-instance submit, tasks can run out of order, no stalling downstream of failed tasks) BUT spawn-on-submit has to remain the default for now because of the potential impact of the extra task proxies on:
* performance (more dependency matching)
* memory (pending …
=> Optionally spawn to max active cycle points.

bin/cylc-stop, lib/cylc/exceptions.py, lib/cylc/gui/app_gcylc.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/hold-release/13-ready-restart/suite.rc, tests/shutdown/07-task-fail.t, tests/shutdown/07-task-fail/suite.rc, tests/shutdown/08-now1.t, tests/shutdown/08-now1/suite.rc, tests/shutdown/09-now2.t, tests/shutdown/09-now2/suite.rc
Internal refactor:
* Group stop logic towards the end of the main loop.
* Remove unnecessary attribute variables.
* Rename methods and variables for internal consistency.
* Generate reference log with filter (https://github.com/cylc/cylc/pull/1892#issuecomment-227383351).
Improve diagnostic:
* Improve orphaned tasks warnings - list orphaned tasks and their states.
* Improve labelling of shut down reasons.
Wait for event handlers to complete:
* On shut down due to task failures.
* On `cylc stop --now`.
Terminate immediately on `cylc stop --now --now`.
Partially address #1282. (Recording event handlers progress in suite DB and running left over event handlers on restart will be done in a separate PR.)
=> suite stop logic improvement

tests/hold-release/12-hold-then-retry/suite.rc
Remove dependency on `at`.
Less time driven. More event driven.
This test has started failing randomly in my environment and in Travis CI in at least 2 occasions. I believe removing the dependency on `at` and the broadcast should make it more robust.
Note: Instead of `t-hold` silently killing `t-submit-retry-able`, `t-submit-retry-able` will now silently exit (before it says `started`) on 1st submit.
@arjclark please sanity check.
=> tests: hold-release-12: improve stability

lib/cylc/gui/gscan.py, lib/cylc/network/suite_state.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py
Closes #1887 
If over six tasks fail between `update` calls then only the six most recent failures will be reported as 'new' warnings, the remainder will be passed over. Otherwise all failures will be shown when hovering over the error icon until dismissed (by clicking on the icon itself).
@benfitzpatrick Please review
@hjoliver Please review
=> gscan: visual notification of new errors

bin/cylc-validate, lib/cylc/profiler.py, lib/cylc/scheduler.py
Factor out cProfile, pstats, and memory logging code, and enable profiling of validation as well as scheduler.  (motivation: performance testing on #1953)
@matthewrmshin - please review/assign (one is probably enough for this).
=> Profiling option for validation too.

lib/cylc/task_proxy.py, lib/cylc/wallclock.py, tests/cylc.wallclock/00-single.t, tests/cylc.wallclock/test_header
This supercedes #1974.
`get_unix_time_from_time_string` had become a major performance bottleneck due to
initialisation of the `TimePointParser` on every function call.
This change reduces the amount of calls to the function, uses a pre-initialised parser, and
uses `datetime` where possible. The use of `datetime` also fixes the non-Gregorian calendar issues reported in #1974. It's now very fast when the time_string input is in UTC, and still less than half a millisecond per call for non-UTC time strings.
@matthewrmshin, @hjoliver please review.
=> Remove get_unix_time_from_time_string bottleneck and fix non-Gregorian logging times

lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/runahead/06-release-update.t, tests/runahead/release-update/suite.rc
Currently the suite state summary does not get updated immediately when runahead tasks are released to the main pool, if nothing else is happening at the time.  This becomes apparent if you have an inter-cycle trigger, and a pending clock-trigger, and set `max active cycles = 1`.   A test suite that does this:
```
[cylc]
cycle point format = %Y
[scheduling]
initial cycle point = now
max active cycle points = 1
[[special tasks]]
clock-trigger = foo(P0Y)
[[[P1Y]]]
graph = """foo => bar
bar[-P1Y] => bar""" # (or sequential bar)
[runtime]
[[root]]
script = sleep 5
```
When the second `foo` is waiting for 1 year real time, there will be no waiting tasks visible in the GUI (or `cylc dump`) even though they have been released to the main pool.  A `cylc nudge` will make them …
=> Update state summary on runahead release.

lib/cylc/gui/app_gcylc.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_state.py, tests/pre-initial/warm-insert-stall/suite.rc
The test hanged when the insert happened quite late in the suite. A task
would be `held` beyond the stop point. The stall check would always
return False if any task were in the `held` state, so the suite did not
stall, and did not trigger the stall abort logic.
In the fix, we will ignore tasks that are beyond the stop point in the
stall checking logic.
I have also:
* Added `TASK_STATUS_SUBMIT_RETRYING` to the list of non-stalling statuses.
* Added `TASK_STATUS_EXPIRED` to the list of final statuses.
* Changed `sleep 5` to `true` for a faster turn around of the suite in the no-longer failing test.
* Done some minor refactor to reduce repeated logic.
@hjoliver @arjclark please review/reassign.
=> Fix hanging warm insert stall test

lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py
It is now clear that the next release is going to be 6.11.0 instead of 6.10.3.
=> Update deprecate version strings to 6.11.0

tests/runahead/06-release-update.t
Instead of `sleep 10`... Poll the log for a given event, then `sleep 1`
to ensure the main loop has done its stuff before calling `cylc dump`.
Close #1983. @hjoliver please review.
=> t: runahead 06: improve stability

lib/cylc/config.py
Getting this trace back on a suite.
```
File "/home/matt/cylc.git/bin/cylc-validate", line 134, in <module>
main()
File "/home/matt/cylc.git/bin/cylc-validate", line 82, in main
mem_log_func=profiler.log_memory)
File "/home/matt/cylc.git/lib/cylc/config.py", line 134, in get_inst
vis_start_string, vis_stop_string, mem_log_func)
File "/home/matt/cylc.git/lib/cylc/config.py", line 340, in __init__
self.compute_family_tree()
File "/home/matt/cylc.git/lib/cylc/config.py", line 952, in compute_family_tree
log_msg += " +", p, "as parent of '" + n + "'"
TypeError: cannot concatenate 'str' and 'tuple' objects
```
Looks like the `,` before and after `p` are turning right hand side into a tuple.
=> cylc validate: fix demoted info concat

lib/cylc/prerequisite.py
Follow on from #1990, fixed 'No handlers found for logger "err"' messages.
@arjclark Please Review.
=> Fixed 'No handlers found...' error.

lib/cylc/graph_parser.py, tests/validate/58-succeed-sub.t
If an LHS contained `foo` and `foo:fail`, `foo:fail` would be modified
to `foo:succeed:fail` incorrectly. This change fixes the problem.
=> Graph parser: fix bad succeed substitution

lib/cylc/graph_parser.py, tests/cylc-cat-log/06-log-rotation.t, tests/events/25-held-not-stalled/suite.rc, tests/validate/59-offset-no-offset.t
First PR targeting the new 6.11.x branch.
Conditional expression processing is failing if the same task name appears in an expression with and without a cycle point offset, e.g.:
```
graph = foo | foo[-P1D] => bar
```
(NIWA has an operational suite with this sort of construct in it).
```
cylc val test
2016-09-17T23:23:01Z ERROR - name 'foo_colon_succeed_leftsquarebracket__minus_P1D_rightsquarebracket_' is not defined
'"(foo_colon_succeed | foo_colon_succeed_leftsquarebracket__minus_P1D_rightsquarebracket_)"'
'ERROR, bar: invalid trigger expression.'
```
This shows the problem is that the explicit `:succeed` trigger is getting substituted in before the offset `foo:succeed[-P1D]` instead of after it `foo[-P1D]:succeed`. (only if the same name occurs with and without an offset in the same …
=> Fix new graph parser bug (PR to 6.11.1)

lib/cylc/batch_sys_handlers/background.py
(Bug discovered while running a busy suite - when the OS refuses to fork any more process for the current user, causing an OSError. On error handling, the logic is wrong because `command` is not defined.)
=> Fix background OSError handling

lib/cylc/gui/gscan.py
Fixes an issue in gscan where the status icons can jump back and forth when hovered over providing that the cycle points of the suite have been expanded.
Uses a blank pixbuf rather than setting `visible` to `False` for hiding error icons where they are not needed / wanted.
@arjclark Please Review / Assign second if desired
=> gscan: fix jumping status icons

lib/cylc/gui/app_gcylc.py
=> cylc gui: fix remove task after spawn

doc/cug.tex, doc/siterc.tex
Minor changes to `doc/cug.tex` and `doc/siterc.tex` to change `cylc log` to `cylc cat-log` to remove ambiguity in searching the online Cylc user guide.
Close #2029
=> Fix "cylc cat-log" documentation.

doc/siterc.tex, doc/suiterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/events/09-task-event-mail.t, tests/events/09-task-event-mail/suite.rc, tests/events/18-suite-event-mail.t, tests/events/18-suite-event-mail/suite.rc
Allow a configurable event mail footer setting (suite or global) to be
added to all event mails. The new setting, although specified at the
suite level, will apply to both suite events and task events.
Move task event handler logic from `cylc.task_pool` to `cylc.scheduler`
for easier access to suite variables.
Close #2022. (This change should be appropriate to replace what we currently have for `rose suite-hook --mail`.)
=> Configurable event mail footer

doc/cug.tex, doc/siterc.tex
This is the 6.11.x version of #2030.
=> Cylc cat log documentation change 6.11.x

lib/cylc/scheduler.py, lib/cylc/task_proxy.py, lib/cylc/task_state.py
Closes #1825 
* Applies slotting to the TaskProxy class
* Also applies it to TaskState
* removes a redundant `itask.try_number` assignment from `scheduler.py` (not used anywhere)
@matthewrmshin @hjoliver please review.
=> 1825.slot task proxy

doc/cug.tex, doc/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/gui/app_gcylc.py, lib/cylc/rundb.py, lib/cylc/scheduler.py, lib/cylc/scheduler_cli.py, tests/restart/19-checkpoint.t, tests/restart/19-checkpoint/reference.log, tests/restart/19-checkpoint/suite.rc, tests/restart/19-checkpoint/suite2.rc
Command line option and GUI entry box updated to allow restart from a
different checkpoint.
The new `--checkpoint=CHECKPOINT` option replaces the old `STATE` argument.
Also:
* mark `state dump rolling archive length` in `global.rc` as obsolete.
* fix the logging interface for diagnostic on restart loading from DB.
* fix generation of `reference.log`.
@arjclark @hjoliver please review.
(Despite a debate to death in #1827 and deferring to #1735, it looks like there is an immediate use case for doing a restart with a pre-reload checkpoint. Thank goodness I only have to put in a small logic change for the user interface, as `cylc.rundb` already leaves room in anticipation for this functionality.)
=> restart: allow restart from a different checkpoint

lib/cylc/gui/app_gcylc.py, lib/cylc/scheduler.py
Occasionally, we can be in a state where a task's job `user@host` is not
yet set. The pop up job log viewer can die because of this. This fixes
the issue.
Equivalence of #2015. Address #2012 for 6.11.x.
=> cylc gui: fix None error on job log display

doc/suiterc.tex
Equivalent to #2042 for 6.11.x branch
@hjoliver - please review
=> Document spawn to max active cycle points.

bin/cylc-insert, bin/cylc-show, lib/cylc/gui/app_gcylc.py, lib/cylc/network/https/suite_info_server.py, lib/cylc/scheduler.py, lib/cylc/task_id.py, lib/cylc/task_pool.py, tests/authentication/03-full-read.t, tests/authentication/04-shutdown.t, tests/authentication/05-full-control.t, tests/authentication/06-suite-override.t, tests/authentication/07-sha-hash.t, tests/cylc-show/04-multi.t, tests/cylc-show/04-multi/reference.log, tests/cylc-show/04-multi/suite.rc
- cylc show: can now show multiple task name and/or task ID.
- cylc gui: fix view prerequisites for runahead tasks.
Fix #2045. @hjoliver @arjclark please review.
=> cylc show: multi-task interface

lib/cylc/task_proxy.py, tests/job-poll/02-intervals.t
Skip correctly if value is not in global configuration.
Also remove unnecessary diagnostic from a new test.
=> Fix KeyError exception handling

.travis.yml
Travis-ci: re-run any failed tests as we have done in rose (https://github.com/metomi/rose/pull/1999).
Example with failed test (see bottom of file):
https://travis-ci.org/metomi/rose/builds/172332817
=> travis: re-run failed tests.

.travis.yml, bin/cylc-scan, lib/cylc/gui/dbchooser.py, lib/cylc/gui/gscan.py, lib/cylc/network/__init__.py, lib/cylc/network/https/base_client.py, lib/cylc/network/https/port_scan.py, tests/cylc-scan/02-sigstop.t, tests/cylc-scan/02-sigstop/suite.rc
Manage custom process pool instead of using `mutliprocess.Pool`.
This allows the logic to terminate processes with hanging connections - about 10 seconds of inactivity.
Report each `host:port` that causes a process to hang or has timed out connection.
Also:
* Default connection timeout reduced to 5 seconds - a long time for modern intra-network traffic.
* Child processes are used as workers.
Each worker runs a loop to receive messages from main process to scan the next `host:port`.
Previously, each process pool job scans all ports (in range) of a host.
* Single UUID for all jobs.
* Remove cylc 6.5 compatibility logic.
Cylc 7 port scan does not work with cylc 6 suites any way.
* Improve returned data structure.
=> port scan inactivity timeout

lib/cylc/network/https/daemon.py
Should address https://github.com/cylc/cylc/pull/2019#issuecomment-259634449 
This shuffles the generated list of acceptable ports to reduce chances of the race condition mentioned.
In practice, it's probably better to pick a random port for use rather than sequentially trying through a consistently ordered list anyway.
@matthewrmshin - please review 1, up to you if you think it needs review 2 (one liner)
=> https port selection: Shuffle list of acceptable ports.

lib/cylc/gui/gscan.py
Closes #2061.
Traceback was caused by the feature that reports "And <N> more" at the bottom of the tooltip text when hovering over task status icons.
@arjclark Please review
=> Fixed traceback.

bin/cylc-gscan, lib/cylc/gui/gscan.py
Partially addresses #1625 
Adds  --name option for filtering suites to display in gscan as per cylc scan.
@oliver-sanders - please review1
@matthewrmshin - please review2
=> cylc gscan: add --name option

lib/cylc/cfgspec/suite.py, tests/validate/58-icp-quoted-now.t
Previously, quotes were stripped too late.
@arjclark @oliver-sanders please review.
Issue reported via: https://groups.google.com/forum/?fromgroups#!topic/cylc/-WtAc13IoTg
=> Fix: initial cycle point = "now"

lib/cylc/gui/gscan.py
The code shouldn't fail but I think it can in strange situations where GTK PixBuffRenderers register as having no width during settup?
To remove the potential for errors I've stuck it in a try catch.
@arjclark Please review / assign if you like.
=> gscan: removed possible weakness

lib/cylc/config.py
Closes #1911 - don't use a visualisation section stop point for validation purposes in the absence of a final cycle point.
=> #1911: Don't use visualisation stop point in pure validation.

tests/restart/19-checkpoint/suite.rc
I suspect that the suite hangs because `t1.2017` times out too quickly for it to call `cylc release`. Let's see if this change fixes it or not.
=> t: restart-19: attempt to fix hang

lib/cylc/config.py, tests/restart/19-checkpoint.t
This should prevent the `RuntimeError: dictionary changed size during iteration` issue. Note: I am unable to repeat the issue on Python 2.7.12 (on Ubuntu 16.04). In his report, the user said he was on Python 2.7.10.
However, on Python 3, a loop such as this one:
```python
x = {1:2, 2:4, 3:6}
for key, value in x.items():
if key == 3:
del x[key]
```
will definitely give:
```
File "<stdin>", line 1, in <module>
RuntimeError: dictionary changed size during iteration
```
(Was something back ported to Python 2.7.10, but removed again on Python 2.7.12?)
=> cylc.config: improve q iter logic

doc/cug.tex
Cleaned up "cycling workflow" documentation in light of terminology settled on before the Libson workshop.
~~Not quite done - will finish tomorrow.~~
=> User Guide: update cycling documentation

lib/cylc/cfgspec/suite.py, lib/parsec/upgrade.py, tests/deprecations/00-all.t
Closes #2094 
**Note:** #2094 was reported with 6.11.2, I can backport this if we are planning another 6.11.x release.
**1) Fixes a problem in the `upgrader` class** whereby the following config:
```
[runtime]
[[foo]]
[[[job submission]]]
zarquon = True
```
Would fail to be caught by this upgrader:
```
u = upgrader(cfg, descr)
u.obsolete(
'7.0.0',
['runtime', '__MANY__', 'job', 'zarquon'])
u.upgrade()
```
Old behaviour:
```
$ cylc validate .
Illegal item: [runtime][foo][job]zarquon
```
New behaviour:
```
[osanders@eld668 temp2]$ cylc validate --verbose .
...
WARNING: deprecated items were automatically upgraded in 'suite definition':
* (7.0.0) [runtime][foo][job][zarquon] - DELETED (OBSOLETE)
...
Valid for cylc-7.0.0-dirty
```
**2. Fixes upgrading of mixed-syntax `job submission`/`job` …
=> Upgrade mixed syntax

lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/restart/26-remote-kill.t, tests/restart/26-remote-kill/suite.rc
Ensure that `itask.task_owner` and `itask.task_host` are set on restart.
Previously, it only set `itask.user_at_host` which was not enough for
job management commands such as poll/kill.
Remove `TaskProxy.user_at_host` as an attribute, as it duplicates the
functionality of `TaskProxy.task_owner` and `TaskProxy.task_host` and
confuses matter.
Also fix diagnostic log after successful kill - it should not say retry
after P0Y.
=> Fix submitted/running task owner/host on restart

lib/cylc/scheduler.py, lib/cylc/task_pool.py
Ensure that `itask.task_owner` and `itask.task_host` are set on restart.
Previously, it only set `itask.user_at_host` which was not enough for
job management commands such as poll/kill.
(Back port of #2097.)
=> 6.11.x - Fix submitted/running task owner/host on restart

lib/cylc/job_host.py, lib/cylc/scheduler.py, lib/cylc/task_proxy.py
Localise and simplify logic. (I noticed a FIXME in the logic just after #2097.)
=> Refactor restart job host init logic

bin/cylc-gscan, bin/cylc-scan, doc/gscanrc.tex, lib/cylc/cfgspec/gscan.py, lib/cylc/gui/gpanel.py, lib/cylc/gui/gscan.py, lib/cylc/gui/scanutil.py, lib/cylc/network/__init__.py, lib/cylc/network/https/suite_identifier_server.py
Can now filter by suite owners.
Display host column by default, if scanning multiple hosts.
New owner column, display by default if scanning other users.
Refactor:
* Results dict key now a tuple of (host, owner, suite) - as multiple
users can run suites with the same names on the same hosts.
* Remove unnecessary logic, e.g. pointless class inheritance, multiple caching of previous results, etc.
* Can now use the data structure returned by port scan without fiddling.
* Use `cylc ls-checkpoint` instead of `cylc cat-state` to get info for
a stopped suite.
* Moved shared functions between `cylc.gui.gpanel` and `cylc.gui.gscan`
to a separate module `cylc.gui.scanutil`.
Close #1625.
=> gscan: new -a and -o OWNER-PATTERN options

lib/parsec/OrderedDict.py, tests/cylc-get-config/00-simple.t
Closes #2073 
Removed the 'un-helpfull' `__repr__` in `OrderedDictWithDefaults` which was preventing its output from being parsable.
=> get-config: fixed --python option

doc/cug-html.tex, doc/cug-pdf.tex, doc/cug.tex
Minor doc correction.
Also gets rid of paragraph indentation (which is annoying in a technical manual with a lot of very short lines...)
=> Document syntax-driven line continuation in graphs.

lib/cylc/task_state.py, tests/hold-release/20-reset-waiting-output.t, tests/hold-release/20-reset-waiting-output/reference.log, tests/hold-release/20-reset-waiting-output/suite.rc, tests/restart/19-checkpoint/suite.rc
On suite hold, reset a task to succeeded then reset to waiting. On suite
release, its dependent would run immediately before this fix.
Fix #2115.
=> Fix edge case reset outputs

bin/cylc, lib/cylc/__init__.py, tests/restart/19-checkpoint/suite.rc
Using `cylc validate` as an example, the sequence of event is a bit like this:
1. `bin/cylc` is invoked.
2. `prelude` in `bin/cylc` puts bundled `lib` in front of `sys.path`.
3. `bin/cylc` imports `cylc`.
4. `environ_init` in `lib/cylc/__init__.py` puts bundled `lib` in front of `PYTHONPATH`.
5. *After this change, `environ_init` in `lib/cylc/__init__.py` puts bundled `lib` in front of `sys.path` as well.*
6. `bin/cylc` invokes `bin/cylc-validate`.
7. `bin/cylc-validate` imports `cylc`.
8. `environ_init` in `lib/cylc/__init__.py` puts bundled `lib` in front of `PYTHONPATH`.
9. *After this change, `environ_init` in `lib/cylc/__init__.py` puts bundled `lib` in front of `sys.path` as well.*
=> Improve logic for adding cylc lib to sys.path

doc/cug.tex, doc/siterc.tex, doc/suiterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/scheduler.py, lib/cylc/task_proxy.py, tests/events/29-task-event-mail-1.t, tests/events/29-task-event-mail-1/reference.log, tests/events/29-task-event-mail-1/suite.rc, tests/events/30-task-event-mail-2.t, tests/events/30-task-event-mail-2/reference.log, tests/events/30-task-event-mail-2/suite.rc
Group task event mail notifications in 5 minutes chunks. As soon as a
task event mail is sent, set a flag for 5 minutes from the current
time.  Only allow other task event mail to process when the delay is
done, or if the suite is stopping.
Close #2099.
=> task event mail: group in intervals

lib/cylc/task_pool.py, tests/events/31-dont-stall-succeeded.t, tests/events/31-dont-stall-succeeded/suite.rc
Occasionally, the suite can be marked as stalled, even though the task
pool only contains succeeded tasks. This change fixes the problem.
=> Improve stall logic

lib/cylc/gui/app_gcylc.py
For menu item, this brings in a more consistent behaviour. Also remove some redundant arguments in callback methods.
Close #1956.
=> gui: use activate instead of button-release-event

lib/cylc/scheduler.py, lib/cylc/task_proxy.py, tests/reload/19-remote-kill.t, tests/reload/19-remote-kill/reference.log, tests/reload/19-remote-kill/suite.rc
Looks like `itask.task_owner` and `itask.task_host` are lost after a reload. I'll raise a simpler back port for 6.11.x as well.
=> Fix remote kill after reload

lib/cylc/batch_sys_handlers/lsf.py
Need bracket, or the `%` gets applied first, turning the operation into a `str` divided by an `int`.
=> Fix lsf execution time limit logic

lib/parsec/include.py, tests/validate/61-include-missing-quote.t
`IncludeFileError` is not defined anywhere.
Reported by @kaday.
=> Fix error on missing quote in suite.rc %include

bin/cylc-diff, bin/cylc-get-suite-config, bin/cylc-graph-diff, bin/cylc-insert, bin/cylc-list, bin/cylc-submit, bin/cylc-validate, lib/cylc/cylc_xdot.py, lib/cylc/option_parsers.py, tests/cylc-diff/03-icp.t, tests/cylc-diff/04-icp-2.t, tests/cylc-get-config/03-icp.t, tests/cylc-graph-diff/01-icp.t, tests/cylc-list/01-icp.t, tests/jobscript/09-icp.t
Allow initial cycle point to be specified if missing from `suite.rc`.
Close #1000.
=> Add `--icp=CYCLE_POINT` option for various commands

lib/cylc/suite_srv_files_mgr.py, tests/lib/bash/test_header, tests/registration/01-no-skip1.t, tests/registration/basic/suite.rc
Allow listing to descend at the top level, regardless of items in the directory.
=> cylc print: always descend at top level

bin/cylc-suite-state, lib/cylc/dbstatecheck.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/suite-state/06-format.t, tests/suite-state/format/suite.rc
=> #1332: Implement auto use of cycle-point format in a remote suite.

lib/cylc/gui/gscan.py
A user reported this:
> Suppose someone decided to open `cylc gscan`,
> and then played around with the size of the window and perhaps did some too 
> drastic changes resulting in error messages something like
> ```
>    cell_index = ((cell_x - dot_offset) // dot_width) + 1
> ZeroDivisionError: integer division or modulo by zero
> ```
=> gscan: catch potential ZeroDivisionError

lib/parsec/jinja2support.py
`jinja2support.py` uses `None` to indicate that no Jinja2 template variables are defined. This causes an error when passed to the Jinja2 render method, which expects a dictionary. The suggested solution involves converting None into an empty dictionary.
Close #2164.
=> #2164 - fix Jinja2 processing of site config

lib/cylc/scheduler.py, lib/cylc/task_proxy.py
And suspected bad restart timer loading logic.
=> Fix traceback print usage

lib/cylc/gui/app_gcylc.py
=> gui: insert --no-check

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/view_graph.py
Closes #2154
Not the nicest of solutions, but this maintains as much functionality as possible by using the "activate" event in submenus for non "graph" views and using the "button-release-event" event for the sub-menus when in "graph" view. The only detectable difference to the user will be that "enter"/"return" won't do anything in r-click sub-menus for the graph view.
@matthewrmshin @oliver-sanders - please review and manually test carefully
=> #2154: Fix r-click sub-menu in graph view

lib/cylc/network/https/base_client.py, lib/cylc/suite_srv_files_mgr.py
1. Client no longer removes domain suffix from host. Fix #2167.
2. Re-create SSL certificate on change to host. E.g. if a suite is registered on host A, but is later run on host B (with a shared file system with host A), the new logic will create a new SSL certificate. This ensures that the certificate is valid for the run host. (Change 2 is essential on our site after change 1, and may be related to the `SSLError` reported on [this Google Groups thread](https://groups.google.com/forum/?fromgroups#!topic/cylc/Eahss_mXgqM).)
=> Improve SSL certificate logic

lib/cylc/network/https/suite_info_server.py, tests/api-suite-info/01-get-graph-raw-2.t, tests/api-suite-info/01-get-graph-raw-2/bin/ctb-get-graph-raw, tests/api-suite-info/01-get-graph-raw-2/reference.log, tests/api-suite-info/01-get-graph-raw-2/suite.rc
Suite info server, `get_graph_raw` was not handling `stop_point_str=None` correctly.
Fix #2176.
=> Fix gui graph view filter runahead

doc/cug.tex, lib/Jinja2Filters/strftime.py, tests/jinja2/09-custom-jinja2-filters.t, tests/jinja2/09-custom-jinja2-filters/suite.rc
Add a strptime option to the strftime filter to enable its usage with custom timepoint formats.
=> Strftime jinja2 filter: Add strptime option

lib/cylc/scheduler.py, tests/events/32-task-event-job-logs-retrieve-2.t, tests/events/32-task-event-job-logs-retrieve-2/reference.log, tests/events/32-task-event-job-logs-retrieve-2/suite.rc, tests/events/33-task-event-job-logs-retrieve-3.t, tests/events/33-task-event-job-logs-retrieve-3/reference.log, tests/events/33-task-event-job-logs-retrieve-3/suite.rc
Expect `job.out` for all completed jobs.
Expect `job.err` for task not in succeeded state.
Previously:
* It expects either `job.out` and `job.err`.
* Failed retrieval not reported to `job-activity.log`.
=> Improve logic for recording a good job log retrieval

lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_state.py, tests/events/32-stall-despite-clock-trig.t, tests/events/32-stall-despite-clock-trig/suite.rc
Before this change, if the suite has any clock triggered tasks, the
suite will wait for all clock triggered times to reach before considering
the suite as stalled, even if the clock triggered tasks can never be
triggered due to dependencies issues.
With this change, the suite will treat waiting clock triggered tasks
with unsatisfied dependencies the same as other waiting tasks with
unsatisfied dependencies. However, it will consider a clock triggered
task as an *active* task if it has its dependencies satisfied but is
only waiting for the clock triggered time.
The change allows the stalled event to be raised as soon as the
following conditions are satisfied:
* There is no activity after one main loop.
* The task pool is left with only inactive tasks.
* Active tasks are those that are not …
=> Improve stall logic in presence of clock trigger

bin/cylc, lib/cylc/gui/scanutil.py, tests/cylc-list/00-options.t
Exact matches are now always good, so `cylc ls` is no longer considered
a clash with `cylc ls-checkpoints`.
Close #2179. Supersede #2180.
=> Improve command and command category matching

bin/cylc-profile-battery, lib/cylc/profiling/__init__.py, lib/cylc/profiling/analysis.py
1. Fixes a bug where the CLI help refused to display if cylc is not a git repository.
2. Removes an un-necessary dependency on `collections.OrderedDict`.
=> profile-battery: address dependencies

lib/cylc/suite_srv_files_mgr.py, tests/suite-host-self-id/00-address.t, tests/suite-host-self-id/00-address/suite.rc
The modified test hangs on Ubuntu 16.04 metomi-vms - due to task unable to communicate back. We need to use `get_suite_host` in SSL certificate extension to ensure that the preferred suite host self ID is written to the certificate.
Reported by @dpmatthews.
=> Use preferred suite host self ID in SSL cert

lib/cylc/task_proxy.py, tests/restart/27-broadcast-timeout.t, tests/restart/27-broadcast-timeout/reference.log, tests/restart/27-broadcast-timeout/suite.rc
Suites were dying on restart when there is a submission timeout
broadcast. On restart, submission timeout values became unicode, which
caused job submission timeout logic to die. This fix ensures that the
values are converted back to float.
(We thought #2166 would fix the issue, but it looks like the real problem was overlooked.)
=> Fix broadcast submission timeout restart

lib/cylc/job.sh, tests/jobscript/13-hostname.t, tests/jobscript/13-hostname/reference.log, tests/jobscript/13-hostname/suite.rc
`HOSTNAME` was the main problem reported here. It is apparently a bash
built-in. To avoid local shell function variables from overriding the
environment or shell built-in, this change modifies all local shell
function variables to lower case. All other global shell and environment
variables should be protected by the `CYLC_` prefix or by setting them
to their most usual values only if they are not set (e.g. using syntax
such as `USER="${USER:-$(whoami)}"`).
Reported by @steoxley.
=> job.sh: avoid overriding environment/shell builtin

doc/cug.tex, lib/parsec/jinja2support.py, tests/jinja2/10-builtin-functions.t, tests/jinja2/10-builtin-functions/suite.rc
Closes #2184 
Adds `assert` and `raise` functions to parsecs Jinja2 processing.
```
{{ raise('Some error text') }}
{{ assert(VARIABLE is defined, 'Some error text') }}
```
These could be implemented as custom filters but the syntax would be somewhat strange:
```
{{ 'Some error text' | raise }}
{{ 'Some error text' | assert( VARIABLE is defined ) }}
```
Caveat: Exceptions appear without context lines, i.e. you only see the exception text and not the code which called it. I've taken a look at this but I don't think it can be done without hacking Jinja2 itself.
=> Added raise and assert Jinja2 functions.

lib/cylc/gui/scanutil.py
Runtime database `task_pool` table has been updated with an extra column.
Fix #2190.
=> gscan: fix stopped suite checker

bin/cylc-show, lib/cylc/network/https/suite_info_server.py, lib/cylc/prerequisite.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_state.py, tests/cylc-show/05-complex.t, tests/cylc-show/05-complex/suite.rc, tests/triggering/16-fam-expansion.t
Closes #1346 
Closes #2147?
Before
```
prerequisites (- => not satisfied):
-     LABEL: a_colon_succeed = a.1 succeeded
-     LABEL: b_colon_succeed = b.1 succeeded
-     LABEL: c_colon_succeed = c.1 succeeded
-     LABEL: d_colon_succeed = d.1 succeeded
- CONDITION: a_colon_succeed&b_colon_succeed&(c_colon_succeed|d_colon_succeed)
```
After
```
prerequisites (- => not satisfied):
- 0 & 1 & (2 | 3)
- 	0 = a.1 succeeded
- 	1 = b.1 succeeded
- 	2 = c.1 succeeded
- 	3 = d.1 succeeded
```
Adds `--list-prereqs` option which results in:
```
a.1 succeeded
b.1 succeeded
c.1 succeeded
d.1 succeeded
```
=> cylc show: More user friendly pre-requisite labels

lib/cylc/suite_srv_files_mgr.py
Use suite host name instead of suite name.
=> Fix common name of SSL cert

lib/cylc/batch_sys_handlers/sge.py, tests/jobscript/14-sge-format.t, tests/jobscript/14-sge-format/suite.rc
Reported at BoM: under SGE the new(ish) `execution time limit` setting gets formatted as:
```
#$ -l h_rt 0:20:00
```
instead of
```
#$ -l h_rt=0:20:00
```
This patch fixes the problem.
=> Fix SGE directives with space in key.

doc/src/suite-design-guide/general-principles.tex, doc/src/suite-design-guide/portable-suites.tex, doc/src/suite-design-guide/preamble.tex, doc/src/suite-design-guide/style-guide.tex
Small updates to the Suite Design Guide after TISD feedback on the final draft. Mainly:
- changed advice on indenting script strings in light of the fact that *here docs should not be indented*
- documented include-file syntax
(Intending to "publish" this at last, after one more change at most: describing environment config options...)
=> Sdg updates

lib/cylc/gui/app_gcylc.py
Could have sworn this was fixed in #2155...
This fixes the right click sub-menu items for "view prereqs" and "cylc show" under graph view.
=> Fix view prereqs and cylc show sub-menu items.

bin/cylc-gui, bin/cylc-monitor, tests/cylc-scan/03-monitor.t
Closes #1752 
Adds an optional argument to `cylc monitor` and `gcylc` to enable output from cylc scan to be used for these commands.
i.e:
```bash
gcylc $(cylc scan | grep <suite_name>)
cylc monitor $(cylc scan | grep <suite_name>)
```
=> Add user at host option to cylc monitor/gui.

lib/cylc/gui/scanutil.py, lib/cylc/network/https/suite_identifier_server.py
See also #2194. Looks like there is another `SuiteStillInitialisingError` we have missed on the server side.
=> gscan: fix suite still init traceback again

lib/cylc/job.sh, tests/api-suite-info/03-get-graph-raw-4/suite.rc, tests/jobscript/12-err-script.t, tests/jobscript/15-semicolon.t, tests/jobscript/15-semicolon/reference.log, tests/jobscript/15-semicolon/suite.rc
Turn on `set -e` so that if `cmd1` fails in a `cmd1; cmd2` syntax, the
failure is trapped.
=> job.sh: fix ERR trap

lib/cylc/gui/updater_dot.py
Closes #1707
Doesn't go as far as Ben's incremental build suggestion (https://github.com/cylc/cylc/issues/1707#issuecomment-167763411).
=> gcylc: dot view - maintain user selection during update

lib/cylc/gui/app_gcylc.py
Once a job has been run 10 times a strange issue occurs with the job log popup window in gcylc causing it to display the log for the 9th run rather than the 10th ect.
=> gcylc: fix job log order.

lib/cylc/config.py, tests/validate/63-collapse-secondary-parent.t
Close #2229.
For the example in #2229:
```
$ cylc validate foo
'ERROR [visualization]collapsed families: BAR is not a first parent'
```
=> 2229.fix fam collapse

lib/cylc/network/__init__.py, lib/cylc/network/https/client_reporter.py, lib/cylc/network/https/suite_log_server.py
Also for consistency, only use `.warning` (instead of `.warn`).
Fix #2228.
=> Fix log warning calls

bin/cylc-gscan, lib/cylc/gui/gscan.py, lib/cylc/gui/scanutil.py
Closes #2227 
Fixed bug where menu icons didn't display properly.
=> gscan: Added stop and release menu items

examples/task-states/bin/change-my-job-sub-method.sh, examples/task-states/suite.rc
Minor fix to one example suite (was using obsolete `cylc broadcast` syntax).  One review will do for this.
=> Fix example/task-states.

bin/cylc-gscan, lib/cylc/gui/gpanel.py, lib/cylc/gui/gscan.py, lib/cylc/gui/scanutil.py, lib/cylc/network/https/port_scan.py
=> gscan: handle ctrl-c

lib/cylc/network/https/client_reporter.py
The delete at line 146 was causing traceback due to the key being removed by the delete at line 133.
=> Fix client_reporter traceback.

lib/cylc/job_file.py, tests/jobscript/10-bad-syntax.t
If runtime script value has comment only, don't generate a function for
it in the job script. Otherwise, it becomes a syntax error.
If job file (temporary) fails shell dry-run, leave for debugging purpose.
=> Handle comment-only script values

bin/cylc-graph
=> Allow "cylc graph --help" in absence of X environment.

lib/cylc/profiling/git.py
For handling revisions with tags like `7.1.0-32-gf973e18`.
=> profile-battery can now handle dirty revs better

lib/cylc/gui/gpanel.py
gpanel used to order adding of items by name of suite. Currently it is adding them in in order of hostname.
This restores the previous behaviour.
=> Sort adding of entries to gpanel by name

lib/cylc/scheduler.py
To reduce memory footprint of child processes.
=> Start mp pool before comms

lib/cylc/gui/updater.py, lib/cylc/network/https/base_client.py, lib/cylc/network/https/suite_info_client.py, tests/api-suite-info/04-api-suite-info-unit-tests.t
Removes redundant calls to getting suite state info and bundles some http requests into one http connection. Addresses issue in #2256 as per suggestions from @matthewrmshin.
=> Reduce number of HTTP connections to address CPU usage

doc/src/cylc-user-guide/suiterc.tex, lib/cylc/config.py, lib/cylc/scheduler.py, lib/cylc/task_proxy.py, tests/events/08-task-event-handler-retry.t, tests/events/08-task-event-handler-retry/suite.rc, tests/events/20-suite-event-handlers.t, tests/events/20-suite-event-handlers/suite.rc
Close #2275 
~~Not for review yet - just needs tests.~~  Tests added (or rather, existing tests upgraded).
=> Supply URLs to suite and task event handlers.

lib/cylc/network/https/base_client.py
Fixes GUI bug introduced by #2271.
(For reference from earlier email chain):
> No, I think it's something to do with 
> https://github.com/cylc/cylc/pull/2271/
> 
> cylc gui --debug SUITE says:
> 
> UPDATE 2017-05-11T20:03:30+10
> (connected)
>   CONNECTION LOST local variable 'func_dict' referenced before assignment  # <---- !!
>   ConnectSchd start
>   reconnection... succeeded
>   ConnectSchd stop
> ....
>
=> Fix bug in gui after http-connection change

lib/cylc/cycling/__init__.py, tests/graph_parser/00-unittests.t
`cylc/cycling/__init__.py` contains base classes that are used to inherit from to create the `ISO8601Sequence`, `IS8601Interval`, `ISO8601Point` classes. This PR really just tidies up the base classes implementation so they are more pythonic abstract base classes. (Rather than just a bunch of "`raise NotImplementedErrors`".) It also prevents the base classes being instantiated on their own, and ensures that the base class methods are defined in any subclasses created. 
(~~It's a prequel to solving the rest of issue #1960~~<sup>1</sup>, but I thought I would check this doesn't break anything first, or it's a terrible idea etc..)
<sup>1</sup>Not absolutely essential to this issue now.
=> Cycling abstract base classes refactor

bin/cylc-cat-log, bin/cylc-view, lib/cylc/cycling/iso8601.py, lib/cylc/gui/app_gcylc.py
`cylc cat-log` - allow opening job logs in users' editor ( temporary read only copy ); same via gcylc.
~~[not ready for review yet - coming soon]~~
=> Cat-log - open job logs in editor

tests/validate/04-builtin-suites.t
It was printing out `find: 'dev/suites': No such file or directory` in my environment.
=> Fix error message from test battery

lib/cylc/cfgspec/globalcfg.py
Fix bug that affects boolean derived host items set to False when the same localhost item is set to True.
Found by trying to set `use login shell = False` in job hosts, with `use login shell = True` in localhost.
> git blame: 0ac4ac8a lib/cylc/cfgspec/site.py      (Hilary James Oliver 2014-02-09 15:44:42 +1300 625)  
(Ouch somewhat surprising this hadn't shown up before).
This code fixes the bug - I'll add a test later tonight - hopefully we can get this in cylc-7.4 tomorrow.
=> Distinguish False and None properly in global config.

doc/src/cylc-user-guide/gcylcrc.tex, doc/src/cylc-user-guide/gscanrc.tex, lib/cylc/cfgspec/gscan.py, lib/cylc/gui/gpanel.py, lib/cylc/gui/gscan.py, lib/cylc/gui/scanutil.py
(From late one night in a hotel room on recent trip).  Motivation: gscan looks so minimalist that new users tend to assume it is lacking in functionality; plus the right-click menu should really be for context (click-target) sensitive options, not for general view configuration options.
* right-click menu is now only for suite operations (open gcylc; stop, hold, release)
* extend "stop" functionality - via right-click sub-menu - to all suite stop methods
* new main menu and toolbar for general view configuration (columns, theme, etc.)
* new collapse/expand-all toolbar buttons
* new configurable state icon size (like gcylc)
* state key window now updates in-place if theme is changed
* right-click below suites now shows: "click on a suite or group"
~~Not for review yet - needs tidying - but …
=> some gscan improvements

doc/src/cylc-user-guide/cug.tex
@matthewrmshin - I think this paragraph is obsolete, since your task proxy refactor?
=> Remove obsolete advice in CUG.

lib/cylc/config.py, lib/cylc/taskdef.py
Whilst profiling cylc's memory usage for a suite I noticed that a taskdef was using 7.3Mb. This was largely due to 48'000 items (mostly duplicates) in the `taskdef.intercycle_offsets` list. This pull reduces this memory usage to 2.9Mb which amounts to roughly a 5% reduction in memory usage for the `Scheduler` object in this case.
The example in question is a somewhat extreme case, profiling results for the complex suite show a much smaller improvement:
| Version | Run | Elapsed Time (s) | CPU Time - Total (s) | Max Memory (kb) |
| ------- | --- | ---------------- | -------------------- | --------------- |
| intercycle-offsets-to-set | complex suite | 1064.4 | 316.7 | 84456.0 |
| master | complex suite | 1049.4 | 317.4 | 84552.0 |
=> Change Intercycle offsets from list to set.

lib/cylc/rundb.py, lib/cylc/suite_db_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_pool.py, tests/database/00-simple/schema.out, tests/restart/28-execution-timeout.t, tests/restart/28-execution-timeout/reference.log, tests/restart/28-execution-timeout/suite.rc
Store timer timeout value (for submitted and running tasks) in suite
runtime database. Repopulate task attribute on restart.
Repopulate task submitted and started time attributes on restart.
Only report a submission timeout if submitted time is defined.
Only report an execution timeout if started time is defined.
Not yet ready for review.
=> Fix poll timer after restart

lib/cylc/cfgspec/globalcfg.py, lib/parsec/validate.py
For discussion:
The `vmin` and `vmax` validator arguments would appear to be redundant. Should we remove them or implement these bounds in the validator?
=> parsec: vmin, vmax - redundant variables

lib/cylc/scheduler.py, lib/cylc/suite_db_mgr.py, tests/pre-initial/12-warm-restart.t
=> Record and reuse warmstart points for restarts

doc/src/cylc-user-guide/cug.tex
A minor tidy-up of one CUG section, but mainly: we hadn't documented that custom batch system handlers have to be installed on both suite and job hosts (a fact that I've verified experimentally, just to be sure).
One review should do on this.
=> Update docs on custom batch system handlers.

conf/cylc.lang, conf/cylc.xml, lib/cylc/cfgspec/suite.py, lib/cylc/task_events_mgr.py, tests/cylc-get-config/00-simple/section2.stdout, tests/events/task/events.log, tests/events/task/suite.rc
=> Add CRITICAL event handler.

bin/cylc-message, lib/cylc/job.sh, lib/cylc/task_events_mgr.py, lib/cylc/task_message.py, tests/events/34-task-abort.t, tests/events/34-task-abort/suite.rc
Close #2274 
* ~~general CRITICAL event handler (c.f. our current WARNING handler)~~ [now in #2304]
* custom abort-with-message function with message passed to the 'failed' event handler.
Test case to show the abort function works properly with execution retries (abort message is logged each try, but only passed to the failed handler at last try) and compare with trapped exit:
```
[scheduling]
graph = t-abort & t-fail
[runtime]
[[root]]
[[[job]]]
execution retry delays = PT5S
[[[events]]]
failed handler = echo "!!!FAILED!!! "
[[t-abort]]
script = """
echo ONE; sleep 5
cylc__job_abort "ERROR: rust never sleeps"
sleep 5; echo TWO"""
[[t-fail]]
script = """
echo ONE; sleep 5
/bin/false
sleep 5; echo TWO"""
```
@matthewrmshin - see if you agree with the approach before I and …
=> Abort  job script with custom message.

lib/cylc/config.py, lib/cylc/job_file.py, lib/cylc/task_job_mgr.py, lib/cylc/taskdef.py, tests/cylc-get-config/05-param-vars.t, tests/cylc-get-config/05-param-vars/suite.rc
Parameterized task environment "CYLC_TASK_PARAM_task" is now available in suite envionments.
Close #2225
=> Parameterized task environment moved to suite environments

lib/cylc/job.sh
PATH may not be set correctly by scripts in prelude, and also not inherited from the environment where the job was submitted.
See this conversation in [cylc Google Groups](https://groups.google.com/forum/?fromgroups#!topic/cylc/2_5AMM6qfwI).
=> job.sh: ensure cylc command is in PATH

bin/cylc, bin/cylc-report-timings, bin/cylc-show-times, lib/cylc/rundb.py
Add a new query to the run database and a top-level driver
script that will allow interrogation of task times to facilitate
generation of statistics about wallclock time required for tasks,
including information necessary to generate batch queue wait times,
task run time (which was already available through the GUI), and
total wallclock time for the task.
=> Add new cylc command to show task timings.

lib/cylc/gui/updater_tree.py
On master: view a cycling suite in gcylc treeview, click filter options, click and unclick 'runahead':
```
File "/home/vagrant/cylc.git/lib/cylc/gui/app_gcylc.py", line 3133, in check_task_filter_buttons
self.refresh_views()
File "/home/vagrant/cylc.git/lib/cylc/gui/app_gcylc.py", line 3177, in refresh_views
view.refresh()
File "/home/vagrant/cylc.git/lib/cylc/gui/view_tree.py", line 274, in refresh
self.t.update_gui()
File "/home/vagrant/cylc.git/lib/cylc/gui/updater_tree.py", line 245, in update_gui
t_info[dt] = summary[id][dt]
KeyError: 'submitted_time_string'
```
=> Fix gcylc treeview (broken after 7.4.0).

lib/cylc/config.py, lib/cylc/cycling/__init__.py, lib/cylc/cycling/iso8601.py, lib/cylc/graphing.py, lib/cylc/graphnode.py, tests/api-suite-info/00-get-graph-raw-1.t, tests/cyclers/27-9999_rollover.t, tests/cyclers/36-icp_fcp_notation.t
Reduce validation time. This is part of the work to look at why it would take 30 minutes to validate a user suite (`cylc validate --strict`). This change reduces the validation time of the suite to ~10 minutes~ ~6 minutes~ 4 minutes. Still not good enough, but moving towards the right direction.
The main change is the restructure of the variable `self.edges`. It is now a `dict`. Each key is a unique sequence, and each value is a `set` of `(left, right, suicide, conditional)` tuples. This change allows `get_graph_raw` to look at each unique sequence once instead of multiple times. There is also caching at various points to reduce the number of expensive calls to regular expression matching and date-time functionality.
Other minor changes include:
* Remove unused variables.
* Use compiled …
=> Optimise time taken to get raw graph

lib/cylc/mp_pool.py
Should print the external command to LOG in debug mode.
See this [Google Groups conversation](https://groups.google.com/forum/?fromgroups=#!topic/cylc/ZoBE1ppJ9h8).
=> Fix pool command debug mode diagnostic

doc/src/cylc-user-guide/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/task_events_mgr.py, tests/cylc-get-config/00-simple/section2.stdout, tests/events/35-task-event-handler-importance.t, tests/events/35-task-event-handler-importance/suite.rc
New runtime config item "importance" is provided for priority based alerting. 
Close #2289
=> New runtime config item "importance"

lib/cylc/task_job_mgr.py
On failure writing to the `job-activity.log`, ensure STDOUT/STDERR lines
of actual job submit or job kill commands are still printed to the suite
log.
=> Improve job submit/kill STDOUT/ERR diag

lib/cylc/cycling/__init__.py, lib/cylc/cycling/integer.py, lib/cylc/cycling/iso8601.py, lib/cylc/time_parser.py
Efficiency changes which reduce the memory and CPU impact of cycling objects:
- Avoid creating multiple parser instances.
- Move regex compilation out of the `__init__` method.
- Slot classes.
- Minor fiddling with exclusions objects (@dvalters could you check these changes).
In combination with slotting of the isodatetime library (https://github.com/metomi/isodatetime/pull/74) this reduces the resource requirements of suites with multiple sequences defined in the graphing.
The following results were obtained running `cylc validate` over the following suite varying the value of `sequences`:
```
[scheduling]
initial cycle point = 2000
spawn to max active cycle points = true
max active cycle points = 5
{% for seq_no in range(sequences | default(10) | int) %}
{% set minutes …
```
=> Optimise cycling objects

lib/cylc/graph_parser.py
(Continue the theme from #2312.)
Avoid usage of costly regular expressions - use cheaper string replace instead.
Avoid doing the same string replacement multiple times.
Result of profile-battery on *complex-validate*.
```
Version            Run            Elapsed Time (s)  CPU Time - Total (s)  Max Memory (kb)
master             complex suite  9.7               9.8                   73156.0        
more-validate-opt  complex suite  8.6               8.6                   72928.0        
```
=> More validate optimisation

bin/cylc-submit, tests/authentication/08-shared-fs.t, tests/cylc-cat-log/01-remote.t, tests/cylc-kill/00-multi-hosts-compat.t, tests/cylc-kill/01-multi-hosts.t, tests/cylc-poll/04-poll-multi-hosts.t, tests/job-submission/07-multi.t
Tests probably broken by #2314 and #2319, (and not covered by CI).
=> Fix site-only tests

lib/cylc/gui/updater_dot.py, lib/cylc/gui/view_tree.py
cylc gui can sometimes throw the following traceback when initially swapping view to the text view:
```
File "/net/home/h03/fcm/cylc-7.3.0/lib/cylc/gui/updater_dot.py", line 482, in update_gui
self.ledview_widgets()
File "/net/home/h03/fcm/cylc-7.3.0/lib/cylc/gui/updater_dot.py", line 347, in ledview_widgets
self._get_selected_rows()  # Make a note of selected rows.
File "/net/home/h03/fcm/cylc-7.3.0/lib/cylc/gui/updater_dot.py", line 315, in _get_selected_rows
_, selected_paths = self.led_treeview.get_selection(
AttributeError: 'NoneType' object has no attribute 'get_selected_rows'
```
i.e. when there are no selected rows.
This fixes `_get_selected_rows()` and `_set_selected_rows()` so they won't try and do anything if there are no rows to work with.
=> cylc gui: Fix traceback on no selected rows

lib/cylc/graph_parser.py, tests/suite-state/00-polling.t, tests/suite-state/01-polling.t, tests/suite-state/polling/reference.log, tests/suite-state/polling/suite.rc, tests/suite-state/upstream/suite.rc
Upstream task names are not following the latest convention.
Fix #2336.
=> graph parser: fix suite state polling regex

tests/authentication/08-shared-fs.t, tests/authentication/08-shared-fs/suite.rc
The test would fail pretty much every time in a busy environment, but
would pass on re-run (when the system would be much quieter). This
change should help.
=> t: authentication-08: improve timeout timing

lib/cylc/cycling/iso8601.py
_Before_
```python
str(ISO8601Sequence('PT6H'), start, end)
>>> 'PT6H![]'
```
_After_
```python
str(ISO8601Sequence('PT6H'), start, end)
>>> 'PT6H'
```
The `IntegerSequence` class has no equivalent method.
=> Fix iso8601 exclusions to string method

lib/cylc/gui/gscan.py
`cylc gscan localhost` will no longer add a host column by default.
=> gscan: if localhost only, don't add host column

lib/cylc/rundb.py, lib/cylc/task_pool.py, tests/cylc-insert/12-cycle-500-tasks.t, tests/cylc-insert/12-cycle-500-tasks/reference.log, tests/cylc-insert/12-cycle-500-tasks/suite.rc
This would have caused an error with SQLite, which does not like >999 arguments in its prepared statement.
On `cylc insert SUITE '*.CYCLE'`, and `CYCLE` has 500 or more tasks, we would get a traceback in the suite log similar to the following:
```
File "/opt/cylc-7.3.0/lib/cylc/scheduler.py", line 704, in process_command_queue
*args, **kwargs)
File "/opt/cylc-7.3.0/lib/cylc/scheduler.py", line 917, in command_insert_tasks
return self.pool.insert_tasks(items, stop_point_string, no_check)
File "/opt/cylc-7.3.0/lib/cylc/task_pool.py", line 209, in insert_tasks
["submit_num"], task_ids)
File "/opt/cylc-7.3.0/lib/cylc/rundb.py", line 614, in select_task_states_by_task_ids
for row in self.connect().execute(stmt, stmt_args):
OperationalError: too many SQL …
```
=> Allow insert cycle with 500+ tasks

admin/make-tarball, bin/cylc, bin/cylc-email-suite, bin/cylc-email-task, bin/cylc-import-examples, bin/cylc-test-battery, lib/cylc/cylc_xdot.py
One file (cylc_xdot.py) with a wrong shebang - I think - and some minor fixes for the "red" errors in `shellcheck`.
```
grep -r -H '#!/bin/bash' . | awk -F: '{print $1}' | sort | uniq | grep -v '/tests/' | xargs -I {} shellcheck {}
```
I've had a few issues recently with scripts for Linux *and* for Mac, and found that shellcheck helps a lot to write scripts that just work on multiple platforms (normally, until you find a command with different syntax in GNU/BSD/etc... then you have to put a bunch of if's :-) )
=> Fix shebang in one file, and surround with quotes to avoid problems with white spaces (for Shell scripts)

doc/src/suite-design-guide/general-principles.tex, doc/src/suite-design-guide/portable-suites.tex
Following a discussion with @dpmatthews, we think it would be good to make the following recommendations in the suite design guide:
* When symlinking files in via an install task have it fail if the source is missing - if done via rose file install this can be achieved using `mode=symlink+`
* Where possible have your apps point to files within the suite structure rather than possible external ones. Use linking to bring the external files in instead.
Both the above should make apps more portable and help ensure that you don't get several hours into a run before noticing an external file is missing (something which can be easier to diagnose as missing by waiting to hit a runtime failure in some suites as things stand).
@hjoliver - please review and see if you agree.
=> Suite Design Guide: Add entries for symlink+ and file referencing in apps

lib/cylc/config.py, lib/cylc/task_pool.py
A user reported that a suite was brought down by a KeyError with `myq`. Unfortunately, we were unable to reproduce the condition for triggering this failure, so this change is only an attempt to reduce the likelihood of the problem happening again.
```
File "/opt/cylc-7.4.0/lib/cylc/scheduler.py", line 232, in start
self.run()
File "/opt/cylc-7.4.0/lib/cylc/scheduler.py", line 1130, in run
if self.pool.release_runahead_tasks():
File "/opt/cylc-7.4.0/lib/cylc/task_pool.py", line 253, in release_runahead_tasks
self.release_runahead_task(itask)
File "/opt/cylc-7.4.0/lib/cylc/task_pool.py", line 447, in release_runahead_task
queue = self.myq[itask.tdef.name]
KeyError: u'fcm_make_meto_xc40_cce_utils_serial_safe_omp'
```
=> Attempt to fix traceback on runahead task release

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/gcylcrc.tex, doc/src/cylc-user-guide/siterc.tex, doc/src/cylc-user-guide/suiterc.tex
As revealed by @trwhitcomb, we're still saying its possible to use YYYYMMDDHH (which it isn't).
While I was at it, also made consistent use of:
* `e.g.\ `  (short trailing space as it's not end of sentence)
* "date-time" (vs "date/time" vs "date time")
And removed some erroneous escaping of `%` in string formatting docs (% doesn't start a LaTeX comment inside an lst environment).
=> Fix documentation of legacy cycle point format

bin/cylc, bin/cylc-email-suite, bin/cylc-email-task, bin/cylc-help, lib/cylc/cfgspec/globalcfg.py, lib/cylc/suite_srv_files_mgr.py
Close #2340 
Close #526
* default to localhost in service files manager (currently just falls over if `--user` specified but not `--host`)
* if localhost, attempt to read remote (i.e. other user) suite contact file via the local filesystem first, so that non-interactive ssh is not needed to the suite account.
=> Default to localhost in srv files mgr.

lib/cylc/gui/gscan.py
With the configure hosts dialog moved to a proper menu in Cylc 7,
the dialog would not display for some users.  Investigation showed
that the function to create and display the dialog was not called,
because the button press signal was not being registered.  Replacing
button press with "activate" signal resulted in the dialog displaying
properly.
=> Update signal for gscan menu dialog.

bin/cylc-suite-state, lib/cylc/dbstatecheck.py, lib/cylc/job.sh, lib/cylc/rundb.py, lib/cylc/scheduler.py, lib/cylc/suite_db_mgr.py, lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_message.py, lib/cylc/task_outputs.py, lib/cylc/task_pool.py, lib/cylc/task_state.py, tests/database/00-simple.t, tests/database/00-simple/schema.out, tests/database/00-simple/select-task-events.out, tests/execution-time-limit/00-background/suite.rc, tests/execution-time-limit/04-poll/suite.rc, tests/job-file-trap/02-pipefail.t, tests/restart/25-hold-suite.t, tests/restart/25-hold-suite/suite.rc, tests/restart/30-outputs.t, tests/restart/30-outputs/reference.log, tests/restart/30-outputs/suite.rc
Store custom outputs in separate DB table `task_outputs`.
* Each task proxy (that has custom outputs) has a single row in the new table. The completed outputs are stored as a single value in the `outputs` column of the row. The value is a multi-line string, each line is a `trigger=message` pair.
* Remove custom outputs and duplicated outputs from the `task_events` table.
* Update `cylc suite-state` to query the new table instead of `task_events`.
Correctly load completed custom outputs on restart.
* For running, succeeded and failed tasks, which may have some completed outputs.
* Instead of setting all outputs to completed only for succeeded tasks.
Fix `job.status` exit time on failure.
* This was lost, as we no longer pass the `failed` argument to `cylc message` on failure.
Fix DB task …
=> Improve handling of custom task outputs

bin/cylc-suite-state
I think there's no reason to keep the `--template` option for `cylc suite-state`.  The target suite cycle point format has been determined automatically since cylc-7.1.1, and no one should be polling cylc-6 suites with cylc-7 clients (which doesn't leave much of a compatibility gap) ... agree?
=> Remove "cylc suite-state" cycle point template

doc/src/cylc-user-guide/cug.tex
After #2346 nodes on implicit sequences are graphed as ghost nodes.
=> docs: update documentation after #2346

tests/events/task/suite.rc
On my laptop VM, `tests/events/01-task.t` always passes at home, and always fails when on the work network because an expected job submission timeout event apparently does not occur.
The test suite uses `[remote]host = NOHOST` for one task.  During job host init, `ssh NOHOST ...` returns immediately with "Name or service not known" at home, but it takes 10 seconds to time out and return at work.  Adding a non-existent domain name as well makes it return immediately, and the test passes.
=> Fixed a test.

lib/cylc/cylc_xdot.py, tests/graphing/10-ghost-nodes/graph.plain.ref, tests/graphing/10-ghost-nodes/suite.rc
Follow-on fix from #2346
This PR fixes the somewhat over-zealous detection of ghost nodes and handles the case that a task is defined but not used.
Detection of ghost-families has been removed as it is doesn't make sense without analysing the suite's triggers individually which is perhaps beyond the scope of `cylc graph`.
=> graph: ghost node detection fix

bin/cylc-check-software
Always checks for OpenSSL now, regardless of global.rc config. (as raised by @dpmatthews)
=> Fix to cylc-check-software

lib/cylc/task_pool.py
Fixed a bug introduced before 7.4.0, by (I think) #2157 - manual task state reset to failed results in a traceback (although the state reset still succeeds)
```
2017-08-13T08:18:07+12 WARNING - Traceback (most recent call last):
File "/home/vagrant/cylc.git/lib/cylc/scheduler.py", line 527, in process_command_queue
*args, **kwargs)
File "/home/vagrant/cylc.git/lib/cylc/scheduler.py", line 1618, in command_reset_task_states
return self.pool.reset_task_states(items, state, outputs)
File "/home/vagrant/cylc.git/lib/cylc/task_pool.py", line 1081, in reset_task_states
itask.set_event_time('finished', time())
File "/home/vagrant/cylc.git/lib/cylc/task_proxy.py", line 241, in set_event_time
get_unix_time_from_time_string(time_str))
File "/home/vagrant/cylc.git/lib/cylc/wallclock.py", line 226, …
```
=> Fixed a bug in a set_event_time call.

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex
Close #2401 
Documents `cylc__job_abort`.  And also the new "critical" task event handler.
@matthewrmshin - sounds like you're around Monday?  If not, one review is probably enough on this (doc only, small).
=> Documented cylc__job_abort function.

lib/cylc/job.sh
The current shell script will source files and redirect all output
to /dev/null - this works very nicely unless there is an error hiding
in one of those files (or, more specifically, in a users ~/.profile or
~/.bashrc or equivalent).
Create verbose output when sourcing other files if the debug flag is
enabled to give at least some information when trying to trace errors.
First choice was to check error codes, but I can't make that work with
sourcing files (rather than calling them as scripts).
=> Allow debug output to include shell sources

lib/cylc/task_events_mgr.py
Previously only display batch system ID (submit_method_id).
```
2017-08-17T16:08:24+01 INFO - [foo.1] -submit_method_id=29483
```
Now display submit number, [user@]host, batch system name and batch system ID.
```
2017-08-17T16:08:24+01 INFO - [foo.1] -job[01] submitted to localhost:background[29483]
```
=> Improve suite log on job submission

doc/src/cylc-user-guide/cug-html.tex, doc/src/cylc-user-guide/cug-pdf.tex, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/job-host.tex
Adds an appendix showing exact transcripts of all remote job host interaction by a suite daemon.  This was done for BoM, might as well record it in the user guide for info.
=> Document remote job host interaction.

lib/cylc/network/https/suite_command_server.py
The (infrequently used!) spawn command was killing target tasks ... looks like a cut-n-paste error in the new network layer.
As this is a bug, and easily fixed, we'd better put it in next release.  Clearly we need `cylc spawn` tests with this - but I won't have time tonight.
=> Fix spawn kill mix-up.

lib/cylc/daemonize.py, lib/cylc/scheduler.py, lib/cylc/suite_logging.py, tests/logging/02-duplicates.t, tests/logging/02-duplicates/suite.rc
Close #2411 
Changes:
- When the suite is running in detached mode stdout and stderr redirected to log/out and log/err respectively. When the logs rotate these streams are re-directed again so as to pick up the new file.
- Logs are only re-directed to stdout/stderr when running in non-detatched mode
=> Fix redirection of stdout and stderr to suite logs

lib/cylc/c3mro.py, tests/inheritance/02-bad-reinherit.t, tests/inheritance/02-bad-reinherit/suite.rc
The current error message for bad multiple inheritance doesn't include the name of the family or task that led to the error - this change adds it.
=> Add namespace to multi inheritance error message

bin/cylc-gsummary
Typo in one of the cylc commands: `gsummary` should call `cylc-gscan`, not `cylc-scan`.
=> Fix gsummary/gscan alias

bin/cylc-validate, lib/cylc/prerequisite.py, lib/cylc/rundb.py, lib/cylc/task_pool.py, lib/cylc/task_state.py, lib/cylc/task_trigger.py, lib/cylc/taskdef.py, tests/cylc-show/simple/suite.rc
Eclectic changes removing unused/unnecessary code. Highlights:
- Slotted `CylcSuiteDAO` objects.
- Removed the un-used `cylc.TaskDef.implicit_sequences` variable.
- Remove data duplication in the `Prerequisite` class.
- Tidy the `TaskState` and `Prerequisite` classes.
Also `cylc validate` now displays traceback when in `--debug` mode.
| Version |                                  Run |           Elapsed Time (s) | CPU Time - Total (s) | Max Memory (kb) |
| --- | --- | --- | --- | --- |
| master | complex suite | 1071.4           | 308.2                | 71956.0        |
| HEAD | complex suite | 1071.8           | 308.9                | 67924.0    |
=> Small efficiency changes

lib/cylc/gui/gscan.py
The Help...About dialog was not displaying properly for some users.
Change the signal for the Help...About menu item so the dialog
box is properly displayed.
See #2374 
Also, like in #2374 I had to change this to get it to work on my system, so I haven't been able to check and make sure it didn't break on other platforms.  Low probability  of damage, considering that the same change in #2374 worked just fine.
=> Update signal for gscan About dialog.

bin/cylc
`bin/cylc` at 7.5.0 is broken on AIX machines, where `sed` doesn't support the `-r` (extended regex syntax) option.  We don't seem to need the option, however, so this removes it.  @dvalters - do you agree?
=> Removed unnecessary sed option (-r).

lib/parsec/validate.py, tests/lib/bash/test_header, tests/validate/66-fail-consec-spaces.t
=> Fail __MANY__ names with consecutive spaces.

bin/cylc-poll, conf/cylc.lang, conf/cylc.xml, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/gui/app_gcylc.py, lib/cylc/network/httpserver.py, lib/cylc/option_parsers.py, lib/cylc/scheduler.py, lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_outputs.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, lib/cylc/task_state.py, tests/cylc-get-config/00-simple/section2.stdout, tests/cylc-poll/12-reverse-state.t, tests/cylc-poll/12-reverse-state/reference.log, tests/cylc-poll/12-reverse-state/suite.rc, tests/suite-state/05-message.t, tests/suite-state/message/suite.rc
Close #1792.
* Allow reset to 'submitted' or 'running'.
* Allow polling of 'succeeded' or 'failed' tasks (but not 'succeeded' by default).
* Poll to confirm, if a message implies a state reversal (the message could be, e.g. a late - and therefore out-of-order - poll result)
* Remove 'enable resurrection' - any task can return from failed.
* Document how to handle preemption in light of these changes.
~~Not ready for review yet.  TODO~~
* ~~tidy up code - callback args complicated by is_second_poll flag~~
* ~~test: e.g. manually reset a long-running task to succeeded, then poll to return it to running~~
* ~~don't automatically poll succeeded tasks~~
=> 1792 - task polling logic and state reset.

bin/cylc-monitor
This makes `cylc monitor` reset and reconnect if a suite shuts down and restarts on a different port.
=> Reset cylc monitor if connection lost

lib/cylc/gui/tailer.py, lib/cylc/gui/view_graph.py
Log viewer tailer.
Graph view missing right click menu items.
Fix #2428.
=> cylc gui: fix broken by #2375

lib/cylc/task_events_mgr.py, tests/cylc-message/01-newline.t, tests/cylc-message/01-newline/suite.rc
A user was wondering why "MESSAGE at TIME" was delivered to her event handler via `custom handler = %(message)s`, rather than the expected "MESSAGE".  
The message contained newlines, and our time stripping regex was assuming a single-line string.
=> Fix 'at TIME' stripping from multi-line task messages

bin/cylc-scan, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/gui/gscan.py, lib/cylc/scheduler.py, lib/cylc/suite_status.py
Migrate `group` setting to under `[meta]` as well.
On suite `identify` API call, return full set of suite `[meta]` settings on `description` privilege level.
=> group setting now in suite meta

bin/cylc-help
=> Added report-timings info to bin/cylc-help.

bin/cylc-documentation
With `global.rc`:
```
[document viewers]
html = zilch
```
On master:
```
$ cylc browse SUITE
[Errno 2] No such file or directory 
```
```
$ cylc browse SUITE                                                                          
ERROR, failed to execute: "zilch http://suites.baz/"
```
(And full traceback with `--debug`).
=> Better error msg for global config browser.

lib/cylc/dbstatecheck.py, tests/suite-state/07-message2.t, tests/suite-state/07-message2/suite.rc
`cylc suite-state` fails if querying a task output message from a task proxy that exists (or existed before suite shutdown) but which has not generated its message output yet.  E.g.:
```
[cylc]
cycle point format = %Y
[scheduling]
initial cycle point = 2010
final cycle point = 2012
[[[P1Y]]]
graph = "foo:x => bar"
[runtime]
[[foo]]
script = cylc message "the quick brown fox"
[[[outputs]]]
x = "the quick brown fox"
[[bar]]
script = true
```
Run this suite to completion. It shuts down with waiting task proxies recorded in the final+1 cycle (2013):
```
$ cylc suite-state baz
foo, 2010, succeeded
bar, 2010, succeeded
foo, 2011, succeeded
foo, 2012, succeeded
bar, 2011, succeeded
foo, 2013, waiting  # <---
bar, 2012, succeeded
bar, 2013, waiting  # <---
```
Querying foo's …
=> suite_state: don't return null db results

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/config.py, lib/cylc/task_events_mgr.py, lib/cylc/task_proxy.py, tests/events/39-task-event-template-all.t, tests/events/39-task-event-template-all/bin/checkargs, tests/events/39-task-event-template-all/suite.rc
(what it says)
Example:
```
[scheduling]
graph = "foo"
[runtime]
[[foo]]
[[[events]]]
succeeded handler = echo !!! %(batch_sys_name)s %(batch_sys_job_id)s 
```
run the suite, then
```
$ cylc cat-log -a test foo.1
[jobs-submit ret_code] 0
[jobs-submit out] 2017-10-09T21:47:01+13|2010/foo/01|0|11995
2017-10-09T21:47:01+13 [STDOUT] 11995
[(('event-handler-00', 'succeeded'), 1) cmd] echo !!! background 11995 succeeded
[(('event-handler-00', 'succeeded'), 1) ret_code] 0
[(('event-handler-00', 'succeeded'), 1) out] !!! background 11995 succeeded
```
=> Allow batch system name and job ID as event handler args.

lib/cylc/broadcast_mgr.py, lib/cylc/scheduler.py, lib/cylc/suite_db_mgr.py, lib/cylc/suite_events.py, lib/cylc/suite_logging.py, lib/cylc/task_job_mgr.py, lib/cylc/task_pool.py, tests/cylc-cat-log/00-local.t, tests/job-file-trap/00-sigusr1.t, tests/restart/15-state-to-db.t, tests/restart/20-event-retry.t, tests/restart/21-task-elapsed.t, tests/restart/22-hold.t, tests/restart/23-hold-retry.t
Avoid sending items to OUT from a running suite.
Ensure that the verbosity level makes sense for ERR. (E.g. `ERR.debug` never actually did anything before!)
=> Improve logging

conf/job-init-env-default.sh, doc/src/cylc-user-guide/cug.tex, lib/cylc/job.sh, lib/cylc/job_file.py, tests/jobscript/00-torture/foo.ref-jobfile, tests/jobscript/11-shell-ksh.t
=> job file to use login shell

bin/cylc-cat-log, bin/cylc-documentation, bin/cylc-gscan, bin/cylc-scan, doc/src/cylc-user-guide/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/gui/app_gcylc.py, lib/cylc/gui/dbchooser.py, lib/cylc/gui/gpanel.py, lib/cylc/gui/updater.py, lib/cylc/host_select.py, lib/cylc/hostuserutil.py, lib/cylc/network/httpclient.py, lib/cylc/network/httpserver.py, lib/cylc/network/port_scan.py, lib/cylc/option_parsers.py, lib/cylc/remote.py, lib/cylc/scheduler.py, lib/cylc/suite_events.py, lib/cylc/suite_srv_files_mgr.py, lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, tests/suite-host-self-id/00-address.t, tests/suite-host-self-id/01-unit.t
A CLI specified host name with no domain part was causing the HTTPS
client to fail because it is unable to match the host name in the SSL
certificate (in which the host name has the domain name).
Rename `cylc.suite_host` to `cylc.hostuserutil` (as the module is now a generic utility for working with hosts and users).
Should fix #2422.
=> Fix HTTPS client host no domain issue

bin/cylc
The command `cylc help control` results in an error message due to a missing space.
=> Fix cylc category command.

lib/cylc/batch_sys_handlers/sge.py
Closes #2439
The default `qstat <jobid>` is no longer valid syntax for SGE.  There is no option to query a specific job id and return tabular output which cylc is currently relying on.
Add `get_poll_many_cmd` method to sge handler. This will use `qstat` with no arguments to list the user's jobs in the required format and then the code already in `batch_sys_manager._jobs_poll_batch_sys()` will check that any of the submitted or running jobs is the one requested.
=> Fix job polling for SGE

bin/cylc-trigger, lib/cylc/network/httpserver.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/cylc-trigger/07-edit-run-abort.t, tests/cylc-trigger/07-edit-run-abort/bin/my-edit, tests/cylc-trigger/07-edit-run-abort/suite.rc
The trivial bug fix part of #2460 
Once this goes in, we may want to just remove the bug label on #2460 but change the title and leave it open for the daemon-served job file solution, longer term.
~~TODO - add a test~~
=> Fix re-trigger after aborted edit run.

lib/cylc/config.py, lib/cylc/task_proxy.py, lib/cylc/taskdef.py, tests/cyclers/48-icp-cutoff.t
Reported via email by @benfitzpatrick. The new test would fail on current master.
=> Fix ICP cutoff badness

lib/cylc/config.py, lib/cylc/task_events_mgr.py, tests/events/39-task-event-template-all/bin/checkargs, tests/events/39-task-event-template-all/suite.rc
Following on from #2441 - allow remaining task summary data as event handler args: submit_time, start_time, finish_time, user@host.  This lets us use event handler scripts for routine reporting, at least until we hash out the details of #2442 
@cylc/core do you see any reason not to do this, before I go ahead with documentation and extending the tests?
=> Alow more task summary info as event handler args.

bin/cylc-documentation, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/config.py, lib/cylc/gui/app_gcylc.py, lib/cylc/state_summary_mgr.py, tests/cylc-doc/02-suite-urls-new.t, tests/cylc-doc/02-suite-urls-new/suite.rc
A user reminded me that browsing suite and task URLs from the GUI does not work if (a) the GUI is not running on the suite host account; *and* (b) the GUI account does not have non-interactive ssh access to the suite host account.  Reason: the GUI simply invokes the `cylc doc` / `cylc browse` command, which parses the suite definition - which can't be done from a remote account with no non-interactive ssh access to the suite host account.
Main change in this PR:
* store suite and task URLs in the daemon state summary, for use by the GUI
Also:
* allow use of string templates to replace suite and task names in URLs (was our old-style pseudo environment variable syntax, retained as well for back-compatibility) 
* tidy some associated GUI code a little
* User Guide: document exact …
=> GUI browse URL improvements

bin/cylc-message, lib/cylc/suite_srv_files_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_message.py, tests/cylc-message/00-ssh.t
Fix #2463 (no frills). Main points:
* Handle `cylc message --env=KEY=VALUE ...`.
* Fix typo that causes the logic in `cylc.suite_srv_files_mgr` to fail to load contact file on the server side.
* Don't `scp` passphrase and SSL certificate files if remote host is on SSH+HTTP(S) messaging.
* Ensure `cylc message` on remote host fails when it fails to talk back via SSH communication.
* Fix broken test.
=> Fix cylc message by SSH

lib/cylc/state_summary_mgr.py, tests/events/39-task-event-template-all/bin/checkargs, tests/events/39-task-event-template-all/suite.rc
Use of `subprocess.check_outputs` relies on Python 2.7, so test was failing in Python 2.6. Solution should be forward compatible.
Use of dict comprehension relies on Python 2.7 (PEP274), so code base fails in Python 2.6 at the moment.
=> Python 2.6 compat

lib/cylc/network/httpclient.py, lib/cylc/network/port_scan.py, lib/cylc/scheduler.py, lib/cylc/suite_srv_files_mgr.py, tests/shutdown/18-client-on-dead-suite.t
On a failed connection, the client will check if the suite has stopped based on the information of the contact file. If the client is sure that the suite is no longer running, it will remove the contact file and report that the suite has stopped.
Adjust general error message on detection of a contact file of an active suite - more information on the old suite is and how to shut it down.
Run `fsync` on writing a contact file.
The client running in HTTP protocol will no longer attempt to fetch the non-existent SSL certificate file.
If contact file is loaded, always use the values in it to avoid conflicting host strings in SSL certificate file, etc.
=> Smarter network client logic

lib/cylc/task_events_mgr.py, tests/events/39-task-event-template-all/bin/checkargs
The new task event handler arg `%(user@host)s` is currently passed the internal variable `user_at_host`, which only has `<user>@` prepended if needed for ssh - i.e. if user is not suite owner.  This change preprends `<user>@` in that case.
Existing test updated accordingly.
=> Expand user@host for event handlers.

lib/cylc/cfgspec/globalcfg.py
A few days ago, #2464 broke installation of auth files to job hosts (w/o shared FS).
=> Set default task comms to client server comms.

lib/cylc/job_file.py, tests/env-filter/00-filter.t, tests/jobscript/00-torture/foo.ref-jobfile
It would be useful to have user environment variables exported as soon as they are defined, so they could be used in further definitions like so:
```
FOO='foo'
BAR=$(script_using_FOO)
```
instead of:
```
FOO='foo'
BAR=$(export FOO; script_using_FOO)
```
This pull request moves the export of variables before their definition, which makes them exported as soon as they are defined.
=> Export user variables before their definition

doc/src/cylc-user-guide/cug.tex
The "Task States Explained" section was missing explanations of "runahead" and "expired".
=> CUG: Updated task state documentation.

doc/src/cylc-user-guide/gcylcrc.tex, doc/src/cylc-user-guide/gscanrc.tex, lib/cylc/cfgspec/gscan.py, lib/cylc/gui/gscan.py
Small change after multiple user requests; seems reasonable.
=> Configurable gscan menubar vis at start-up.

bin/cylc-gscan, bin/cylc-scan, lib/cylc/gui/dbchooser.py, lib/cylc/gui/scanutil.py, lib/cylc/network/httpclient.py, lib/cylc/network/port_scan.py, tests/authentication/01-description.t, tests/authentication/02-state-totals.t, tests/authentication/03-full-read.t, tests/authentication/04-shutdown.t, tests/authentication/05-full-control.t, tests/authentication/06-suite-override.t, tests/authentication/07-sha-hash.t
Unify `cylc scan` logic with `cylc gscan` - get list of running suites via file system by default.
* `--all` option now used to scan all known hosts.
* Also apply to `cylc gui` *Open Another Suite...* dialog.
Check regular expressions in `--name=PATTERN` and `--suite-owner=PATTERN`
before use.
Use object attr instead of `global` to configure callable in `bin/cylc-scan`.
(Follow on from #2430.)
=> cylc scan: list suites via file system by default

bin/cylc-poll, bin/cylc-trigger, lib/cylc/network/httpclient.py, lib/cylc/network/httpserver.py, lib/cylc/scheduler.py, lib/cylc/suite_srv_files_mgr.py
This provides limited API backward compatibility between latest client with 7.0.0-7.5.0 suites.
* Set API version to 1 for now. Add this information to contact file.
* If API version is not found in contact file by the client, it will use the old API.
* `cylc gui` compat is not perfect or efficient, as the latest API relies on server side sessions and is more streamlined. 
* (Apart from the `identify` client function for `cylc scan` etc, an old client will still be unable to connect to a suite running on the latest version.)
=> Limited client compat with 7.5.0 suites

examples/satellite/ext-trigger/suite.rc, lib/cylc/task_job_mgr.py, lib/parsec/OrderedDict.py, lib/parsec/util.py, tests/ext-trigger/00-satellite/suite.rc
Ensure that broadcasted environment variables, which target user environment sections, are defined before the other (truly user-defined) variables - which may need to reference the broadcasted ones.
Adds a prepend method to our customized OrderedDict to achieve this.  Existing test updated (fails on master, passes here).
Sort-of-Bug reported by @trwhitcomb
=> Prepend new broadcast items to config OrderedDict.

bin/cylc-report-timings
If a task succeeded, and was later re-added to the task pool and ran,
there would be multiple entries in the suite run database for the
succeeded task at the same cycle point.  This caused problems with
creating the Pandas pivot table to re-organize the data by task name
for the diagnostic plots as part of the report-timings command.
This fix adds a check for when this error will occur and uses a
different reshaping method that avoids the original error.
Also, per the original suggested change, this bumps the maximum
column width to avoid truncation of printed data frames (especially
important for long task names).
See #2509.
=> Fix duplicate index bug in timings report.

lib/cylc/gui/app_gcylc.py
The `control -> stop suite` form could generate traceback due to an unset variable.
@matthewrmshin, @hjoliver - whoever gets back first please review.
=> gui: fix traceback on suite stop form

bin/cylc-trigger
Close #2511 
I don't understand why `stdin=open(os.devnull)` inside the `call()` arg list has any effect on `raw_input()` later in the script, but it does!
=> Fix stdin manip in edit-run.

bin/cylc-edit, bin/cylc-view
Further to #2512, #2511.
For me `cylc view` fails and `cylc edit` causes the terminal to fail.
=> Remove dev/null stdin pipes to editor commands.

lib/cylc/network/port_scan.py
Selecting "File -> Open Another Suite" in the `cylc gui` (in `--debug` mode) can have ill consequences DNTTAH.
In my case it bricks my machine *(I ran `sleep 20; killall python` to test)*.
=> Fix get_scan_items_from_fs traceback

bin/cylc-jobscript, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/gui/app_gcylc.py
* Fix and document the `extra log files` setting (now takes a relative path).
* Add "view in editor" support for `extra log files` in `gcylc`.
* Add text-editor functionality to `cylc jobscript`.
* Add "preview jobscript" functionality to `gcylc`.
=> gcylc: job log files

lib/cylc/task_pool.py, lib/cylc/task_state.py, lib/cylc/task_trigger.py, tests/triggering/17-suicide-multi.t, tests/triggering/suicide-multi/reference.log, tests/triggering/suicide-multi/suite.rc
When multiple suicide triggers are used tasks may go un-triggered.
See `tests/triggering/suicide-multi/suite.rc` for an example (removing the second suicide trigger in each case results in correct behaviour).
Also add `__str__` methods for the `task_trigger` classes for debugging.
=> Fix behaviour with multiple suicide triggers.

lib/cylc/prompt.py
User request for the "Trigger edited task..." prompt to appear on-top of the gcylc window as it does not appear in the task-bar so can become difficult to re-locate once lost.
As the gui calls trigger and other commands via subprocess the prompts displayed are not associated with any parent window and so fancy trickery is not possible, we can, however, place the prompts above all windows.
This change affects the following commands:
* hold
* insert
* kill
* poll
* release
* reload
* remove
* reset
* set
* spawn
* stop
* trigger
=> Place prompts above all windows.

bin/cylc-cat-log, bin/cylc-edit
Another fix for recent stdin changes, like #2531 
`cylc cat-log -t` was broken, for editor vim (which I guess takes keyboard command from stdin).
(and another case in `cylc edit`)
=> Don't redirect stdin to /dev/null for editor.

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater.py, lib/cylc/gui/updater_graph.py
Working on #2531 I noticed it was possible to kill the parent terminal session of a `gcylc` window causing and un-closable `OSError` dialogue.
I don't know whether we want to do anything to handle this convoluted scenario. A simple solution is to protect `print` statements with `except OSError` to handle this detachment.
=> gui - protect print statements.

lib/cylc/gui/gscan.py
If your desktop settings show text labels under gscan menu-bar buttons, this button label was wrong.
=> Fix gscan Collapse-all button label

.travis.yml, admin/get-repo-version, bin/cylc, bin/cylc-check-versions, lib/cylc/profiling/git.py, tests/cylc-get-cylc-version/00-basic/suite.rc, tests/documentation/00-make.t, tests/profile-battery/00-compatability.t
Update to use `cylc.task_remote_mgr` instead of `cylc.host_select`.
Ensure we have the correct package to make documentation.
Use `git describe --always` to prevent it from failing.
Fix test broken by #2468. Fix tests due to recent change to Travis CI? (Package for LaTex and behaviour of `git describe`.)
=> Fix check-versions and other tests

lib/cylc/gui/dbchooser.py
This change is due to #2430 and #2492, where listing of running suites
is now done via the local file system.
Fix bullet point 1 of #2544.
=> gui dbchooser: don't duplicate running suites

lib/cylc/task_events_mgr.py, tests/message-triggers/02-action.t, tests/message-triggers/02-action/suite.rc
A recent change has stopped ~~suicide triggers~~  [custom outputs] getting actioned immediately if nothing else is happening at the time.
Still needs a closer look and a test.
=> Action on custom outputs immediately.

lib/cylc/gui/scanutil.py
Stopped suites will now retain its *group* string.
Tick box 3 of #2284.
=> gscan: fix display of group stopped suites

lib/cylc/scheduler.py, tests/reload/20-stop-point.t, tests/reload/20-stop-point/reference.log, tests/reload/20-stop-point/suite.rc
Reload will no longer reset existing stop point. This is one way to fix #2535 and fix #2536.
=> Fix reload with stop point

bin/cylc-graph, lib/cylc/cylc_xdot.py
In `-O` or `-r` mode `cylc graph` acts as a CLI command rather than a GUI. Both modes, however share the GUI codebase `cylc.cylc_xdot`. This PR prevents the GUI dialogues introduced in #2474 from being displayed in these CLI modes.
I've refactored the `MyDotWindow` constructors but have shied away from more significant work which I would be tempted to put off until #1873.
https://github.com/cylc/cylc/blob/7.5.0/lib/cylc/cylc_xdot.py#L32
Ideally the GUI and CLI code would be separated at the same time.
=> graph: don't display gui prompt for cli actions

lib/cylc/gui/app_gcylc.py
Close #2559 
`SuiteLog` is a singleton - which I guess it should not be! - and so it didn't switch to the new suite.  My fix is a bit unpleasant, but I think it'll do for this rather trivial problem.
=> gui: switch suite, switch logs.

lib/cylc/gui/util.py
Whilst reviewing #2574 I noticed that when I obtained a exception traceback in `gscan` in a pop-up dialog window, the window would immediately re-open after being prompted to close via clicking of the 'OK' button or the 'Close Window' cross corner iron (ad infinitum with further attempts to close it).
_To recreate_: open gscan so it provides any 'entry' traceback e.g. by providing invalid arguments to it such as `cylc gscan -o '*' -n '*'` or by editing the code in `lib/cylc/gui/gscan.py` to create an error there.
I have resolved this by changing an argument so that (as I understand the logic) the `set_exception_hook_dialog` function will only launch an exception dialog if it has not already been launched. The variable `old_hook` was in fact already initialised within the function but not …
=> Fix gscan exception hook dialog closure incapacity

lib/cylc/gui/updater_tree.py
An (internal Met Office operational) user has noticed a traceback dialog in the GUI:
```
File "<HOME>/cylc.git/lib/cylc/gui/updater_tree.py", line 257, in update_gui
100 * (tnow - tstart) / (tetc_unix - tstart))
ZeroDivisionError: float division
```
A brief look at the code reveals this is due to tasks which have a mean elapsed time value of zero - quite how this has occurred in a real suite is still a bit of a mystery to me and while the fix was trivial and the logic easy to follow, the difficultly here was reproducing the error (for self-review purposes) i.e. setting up a suite so that at least one task would have mean elapsed time of zero.
Eventually I just did a bodge job, so (unless you can easily come up with a more clever idea!) to recreate, just …
=> Fix gcylc zero division error from task mean elapsed time

lib/cylc/task_job_mgr.py, tests/job-submission/15-garbage-host-command-2.t, tests/job-submission/15-garbage-host-command-2/bin/my-host-select, tests/job-submission/15-garbage-host-command-2/reference.log, tests/job-submission/15-garbage-host-command-2/suite.rc
Recovery of a failed host select command was a bit broken. This change
ensures that the result is reset as soon as it is consumed.
This also ensures that the retry timer is set for submission retry on host select command failure.
=> Fix recovery of a failed host select command

lib/cylc/option_parsers.py
=> Fix CLI help for --debug.

lib/cylc/scheduler.py, lib/cylc/suite_db_mgr.py, tests/database/00-simple.t, tests/database/00-simple/select-suite-params.out, tests/restart/15-state-to-db.t
Address the remaining two items on the 'parameters' checklist of #1032 and amend affected tests. Additionally (as spotted while in local testing phase) fix error in ``tests/restart/15-state-to-db.t`` whereby sub-test 12 was a duplicate of 10 (``15-state-to-db-suite_params.stdout-cmp-ok``) presumably due to omission of alteration to the filename for comparison after lifting and pasting the equivalent code line.
=> Add parameters to suite DB, fix test error

lib/cylc/scheduler.py, tests/cylc-trigger/08-edit-run-host-select.t, tests/cylc-trigger/08-edit-run-host-select/bin/my-edit, tests/cylc-trigger/08-edit-run-host-select/suite.rc
`cylc trigger --edit` broken if task's remote host setting is a host select command. (Sorry.) This change fixes it.
=> Fix trigger --edit with host select

lib/cylc/scheduler.py, tests/restart/15-state-to-db.t
Amends an issue with the recently-merged PR #2575 (my own!), which occurred because I did not fully clarify what was required from verbal feedback response from @matthewrmshin who pointed out a newly-introduced issue after the feedback response commit but approved before I implemented it. Namely, `GLOBAL_CFG.get(['cylc', 'UTC mode'])` does not produce the correct UTC mode parameter (being the global and not suite-specific setting), unlike the original `cylc.flags.utc`. When looking at the `suite.rc` file for the `restart/15-state-to-db.t` test, one sees that `UTC mode = True` is in fact set, demonstrating this is the case, as the added test wrongly specified it should appear in the database as the default `False`.
My apologies for the muddle / need for a separate PR @hjoliver!
=> Fix suite DB UTC mode parameter error

doc/src/cylc-user-guide/cug.tex, lib/cylc/task_pool.py, tests/queues/02-queueorder.t, tests/queues/02-queueorder/reference.log, tests/queues/02-queueorder/suite.rc
=> Use OrderedDict for queues to make them FIFO

lib/cylc/gui/updater_tree.py
Fix unreproducible bug whereby the gui attempts to display a negative progress value when a task's status is juggled about via `cylc reset`, see traceback:
```
/data/local/fcm/cylc-7.5.0/lib/cylc/gui/view_tree.py:318: Warning: value "-43" of type `gint' is invalid or out of range for property `value' of type `gint'
cell.set_property('value', percent)
```
=> gcylc: prevent negative job progress

bin/cylc-trigger, lib/cylc/job_file.py, lib/cylc/network/httpserver.py, lib/cylc/scheduler.py, lib/cylc/task_job_mgr.py, tests/cylc-trigger/03-edit-run.t, tests/cylc-trigger/03-edit-run/bin/my-edit, tests/cylc-trigger/03-edit-run/suite.rc
At present the cylc job file writer aborts on syntax error, this causes `cylc trigger` to hang as no job file is written. This PR skips the syntax check for dry runs so that users can attempt to fix their scripts at runtime via `cylc trigger --edit`.
Possibly related to reported intermittent hanging of `cylc trigger --edit`.
=> Permit syntax errors with trigger edits.

bin/cylc-message, bin/cylc-submit, lib/cylc/job_file.py, lib/cylc/scheduler.py, tests/jobscript/18-no-err.t, tests/jobscript/18-no-err/suite.rc
Just noticed in job.err files:
```
$ cylc cat-log -e foo foo.1
/home/vagrant/cylc.git/lib/cylc/job.sh: line 29: False: command not found
```
Due to use of Python `str(bool)` as a shell boolean, or testing of  such a value in the job script - broken sometime since last release.
=> Lowercase for shell bool vars.

tests/hold-release/13-ready-restart.t, tests/hold-release/13-ready-restart/suite.rc
Close #2610 
See https://github.com/cylc/cylc/issues/2610#issuecomment-376287090
This modified test, using kill instead of shutdown, seems to work reliably.  Watching the process table, the suite kill clearly leaves the job submit process running, so no chance of ending up with foo-1 submit-failed instead of ready.
=> Fix test 13-ready-restart.

lib/cylc/gui/updater_graph.py, lib/cylc/gui/view_graph.py
This is supposed to fix the argument (which may end up with lots of `base:` prefix) for inserting a family via the graph view.
=> Fix gui insert nested family

lib/cylc/suite_srv_files_mgr.py
Using `.` as a suite path e.g:
```
cylc validate .
```
works intermittently in my environment.
PR adds a failsafe to ensure this behaviour is reliable in these circumstances (whatever they turn out to be).
=> Ensure '.' can be used for inspection commands.

bin/cylc-edit, bin/cylc-gui, bin/cylc-profile-battery, bin/cylc-search, bin/cylc-upgrade-run-dir, lib/cylc/cycling/integer.py, lib/cylc/cylc_xdot.py, lib/cylc/envvar.py, lib/cylc/graph_parser.py, lib/cylc/gui/cylc_logviewer.py, lib/cylc/log_diagnosis.py, lib/cylc/network/httpserver.py, lib/cylc/param_expand.py, lib/cylc/print_tree.py, lib/cylc/profiling/__init__.py, lib/cylc/task_events_mgr.py, lib/cylc/time_parser.py, lib/cylc/wallclock.py, lib/parsec/config.py, lib/parsec/fileparse.py, lib/parsec/include.py, tests/syntax/01-pycodestyle.t
W605 invalid escape sequence:
- In this PR, I have modified the code to raw quote regular expression strings with escape sequence.
W503 line break before binary operator and W504 line break after binary operator:
- PEP8 allows both style. For old code, line break after binary operator is OK (i.e. binary operator at end of first line). For new code, we should begin to adopt line break before binary operator style (i.e. binary operator at beginning of continuation line). In this PR, I have modify the test to ignore both.
=> pycodestyle: fixes

lib/cylc/job.sh
Bash may put HERE documents in a temporary file, which is not efficient.
On older versions of Bash, it may even create temporary files under
`/tmp` instead of using `mktemp`, which can be problematic on systems
with only a small amount of space in `/tmp`.
Problem first raised by @steoxley.
=> job.sh: replace HERE document with echo commands

bin/cylc-reset, lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_outputs.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, lib/cylc/task_state.py, tests/cylc-kill/00-multi-hosts-compat.t, tests/cylc-reset/03-output-2.t, tests/cylc-show/00-simple.t, tests/cylc-show/05-complex.t, tests/cylc-show/06-prereqs-outputs.t, tests/cylc-show/prereqs-outputs/suite.rc, tests/job-submission/04-submit-num/suite.rc, tests/pre-initial/warm-insert/suite.rc, tests/registration/00-simple.t, tests/registration/01-no-skip1.t
Close #2599 
Address a problem first revealed in #2561 (no one had tried to use task prerequisites for external purposes until now, I guess).
Principally, at certain task state changes prerequisites were being set to all-met or all-not-met.  This was at best unnecessary and at worst wrong: in conditional triggers, or manual triggering, tasks can submit without all prerequisites being met.
* prerequisites are only unset on task state reset to 'waiting'. Otherwise they're left alone (e.g. if manually triggered, any un-met prerequisites now remain un-met).
* outputs on the other hand are manipulated to stay consistent with state changes (otherwise triggering of downstream tasks would not work).
Also:
* disallows manual reset to `ready` (this state is really a detail of …
=> Fix prerequisite and output manipulation on state changes.

lib/cylc/gui/app_gcylc.py
I have observed a minor bug in the GUI. When attempting to view the ``prereq's & outputs`` file from the ``View`` menu for task that is completed (naturally I discovered this when trying to access this file for a task that was on the verge of completing & must have completed before I hit the button), one gets either of the following tracebacks on ``master``:
```
File "${HOME}/cylc.git/lib/cylc/gui/app_gcylc.py", line 1633, in popup_requisites
if not results or task_id in bad_items:
UnboundLocalError: local variable 'results' referenced before assignment
```
or:
```
File "${HOME}/cylc.git/lib/cylc/gui/app_gcylc.py", line 1629, in popup_requisites
results, bad_items = self.updater.client.get_info(
AttributeError: …
```
=> gcylc: Fix bug in pop-up for tasks (soon to be) removed

lib/cylc/remote.py
PR #2582 merged with urgency (as significant conflict resolution necessary for follow-on/dependent PRs), with typo outstanding. Trivial hence one reviewer sufficient.
=> Fix docstring typo in #2582

lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, tests/events/40-task-event-host-select-fail.t
To reproduce.
```
[scheduling]
graph = t1
[runtime]
[[t1]]
script = true
[[[remote]]]
host = $(false)
[[[events]]]
submission failed handler = echo %(id)s
```
On current master, the failed remote host select will cause a `KeyError` that will take down the suite with something like this:
```
2018-04-20T12:27:36+01 CRITICAL - Traceback (most recent call last):
File "/home/matt/cylc.git/lib/cylc/scheduler.py", line 231, in start
self.run()
File "/home/matt/cylc.git/lib/cylc/scheduler.py", line 1377, in run
self.process_task_pool()
File "/home/matt/cylc.git/lib/cylc/scheduler.py", line 1212, in process_task_pool
self.suite, itasks, self.run_mode == 'simulation')
File "/home/matt/cylc.git/lib/cylc/task_job_mgr.py", line 195, in submit_task_jobs
prepared_tasks, bad_tasks = …
```
=> Fix submission failed handler on bad host select

lib/cylc/suite_srv_files_mgr.py
Don't use SSH to get contact2. It never exists on the suite host, and is only created on demand for task hosts that require SSH+HTTPS communications. Follow up of #2582.
=> Improve contact2 locate logic

doc/src/cylc-user-guide/suiterc.tex
Adds missing details for 365 and 366 day calendars to user guide.
=> Documentation: Add missing 365 and 366 day calendar entries

bin/cylc-cat-log, tests/cylc-cat-log/10-remote-no-retrieve.t, tests/cylc-cat-log/11-remote-retrieve.t, tests/cylc-cat-log/remote-simple/suite.rc
A small follow-up to #2503, to avoid unnecessary ssh connections.  Current cat-log tests all pass on this branch with log retrieval or not configured in `global-tests.rc`, but before requesting review I'll add another test to distinguish the two cases.
=> cat-log: view retrieved remote logs locally.

lib/cylc/graph_parser.py
This fixes the tests for https://github.com/cylc/cylc/issues/2645 and now also the root cause of the problem.
The tests for order of trigger and parameter were correctly raising a
GraphParseError, but, not for the reason thought. They were raising
the error because parameters were not defined, not because the order
was being correctly identified. I have now added in the parameters,
and they do not pass anymore.
Originally, the exception message thrown said:
```python
File "lib/cylc/graph_parser.py", line 681, in test_bad_node_syntax
gp.parse_graph("foo[-P1Y]<m,n> => bar")
File "lib/cylc/graph_parser.py", line 252, in parse_graph
raise GraphParseError(str(exc))
GraphParseError: ERROR, parameter m is not defined in <m,n>: foo[-P1Y]<m,n> => bar
```
With …
=> Fix graph_parser validation for incorrect syntax order in a node

bin/cylc-jobs-submit, lib/cylc/batch_sys_manager.py, lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, tests/job-submission/07-multi.t
Close #2642 
@matthewrmshin @sadielbartholomew - apologies, I didn't notice you were assigned to the issue before I did this.  I won't bother adding a test in case you've already done so.  We can close this PR if you have a better way of doing it.
I found that T-submit was in the wrong time zone in the DB as well in the GUI.  The reason is, T-submit comes from inside `cylc jobs-submit` executing on the job host, and that does not currently know about the suite's UTC mode.  So I've added a `--utc-mode` option to the job submit command.
I've checked this works in UTC mode and not, when the system clock is in local time.  I haven't checked what happens when the system clock is UTC.
It might be sufficient to make a test that checks for consistent appearance of `Z` or `+12` (e.g.) on all times …
=> Make T-submit respect suite UTC mode.

lib/cylc/graph_parser.py
As mentioned by @hjoliver in https://github.com/cylc/cylc/pull/2646#discussion_r185194352, there was a duplicate assertion. This removes it. I added an extra one in too.
=> Remove duplicate assertion in graph_parser unittests and add an extra one

lib/cylc/cycling/iso8601.py
Remove unnecessary duplicate iso8601 parsers from the `SuiteSpecifics` class. Saves about 1MB of ram.
Run results for a hello-world cycling suite:
| Version | Max Memory (kb) |
| --- | --- |
| master | 28234.4 |
| consolidate-iso8601-parsers | 27308.0 |
=> remove duplicate parsers

tests/triggering/20-and-outputs-suicide/suite.rc
Minor follow up of #2656.
Adjust graphing for triggering final task to be more precise.
Otherwise, timing for a very busy test battery run may cause
inconsistency with the reference log.
=> test: triggering 20

bin/cylc-cat-log
Correct argument order of `is_remote(host, user)` call.
=> cat-log: fix is_remote arguments

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/mp_pool.py, tests/events/44-timeout.t, tests/events/44-timeout/bin/sleeper.sh, tests/events/44-timeout/suite.rc, tests/job-submission/16-timeout.t, tests/job-submission/16-timeout/suite.rc
Hung or long-running event handlers (etc.) can cause a suite to stall with tasks in the 'ready' state (i.e. with job submit commands queued but unable to execute because the max number of subprocesses is used up).
(I have some evidence that this has happened at BoM: a suite stalled with 'ready' tasks after reportedly spawning job polling commands that hung for some reason).
This kills subprocesses that are still running after 10 seconds.  Easier to do than I expected.  @cylc/core - thoughts? (should we do this; should it be configurable; is this approach OK?)
=> Kill proc pool commands that take too long.

CHANGES.md, bin/cylc-scan, lib/cylc/daemonize.py, lib/cylc/gui/gscan.py, lib/cylc/network/port_scan.py
By default, scan only running suites of current user by looking at
`~/cylc-run/*/.service/contact` of current user.
Address the bug label of #2663.
=> scan/gscan: consistent default behaviour

bin/cylc-cat-log
It was not tidying up when its SSHD dies. Fix #2664.
=> cat-log --host=HOST tail mode now tidies up

conf/DEPRECATED.md, conf/cylc-bash-completion, conf/cylc-mode.el, conf/cylc.lang, conf/cylc.vim, conf/cylc.xml
Ideally we would deprecate configurations, paths etc in the current version and obsolete them at the next major version.
As many people have symlinked these files in their editors configuration we could maintain symlinks until cylc 8.
@hjoliver I'll leave the choice to you
=> deprecate conf/ syntax files

lib/cylc/job.sh
Address niche issue involving exit signals issued in the narrow gap between job success and exit.
We recently came across a user with a `.bash_logout` script containing the `clear` command. Since #2438 this can cause an exit `ERR` ("TERM environment variable not set.", we can't clean the terminal if there isn't a terminal to clean).
This results in two exit entries in the `job.status` file, in my tests cylc typically fails but sometimes succeeds tasks in this state.
=> trap error after cylc message success

CHANGES.md, bin/cylc-cat-log, lib/cylc/remote.py, tests/cylc-cat-log/05-remote-tail.t
Follow-up aborted #2672 and earlier attempts at avoiding orphaned tail processes on job hosts.
No need for watch-and kill threads or killing process groups.  Just kill invoked subprocesses (either ssh command reinvocation or tail-follow command) if main process's PPID or PPPID (etc) changes.
Example:  on host A: `cylc cat-log --host=B <suite> <task-on-C>`
* => on host A: cat-log spawns subprocess `ssh B "cylc cat-log <suite> <task-on-C>"`
* =>  on host B: cat-log spawns subprocess `ssh C "cylc cat-log --remote <suite> <task-on-C>"` 
* => on host C: cat-log spawns subprocess `tail -f <task-on-C>.out`
Ctrl-C (or exit GUI viewer) on host-A:
* ssh from A to B dies
* => on B: cat-log detects the previous, and kills its ssh subprocess to C
* => on C: cat-log detects the previous, and kills its …
=> Cat log remote tidy fix.

lib/cylc/gui/logviewer.py
Partly reverse 54408924ce. Apparently this dazzles some users.
=> gui log viewer: undo bold font

bin/cylc-check-software
@dpmatthews has reported that ``cylc check-software`` is not providing the right outcome for TeX modules on RHEL7. We have discussed why this might be & accordingly I have changed the full command to use to search for all TeX modules. Ultimately, it is a bad idea to use ``locate`` (or even ``find``). ``kpsewhich`` makes the search simpler than ``kpsepath`` & bypasses the need to use those (or a pipeline, or a ``wc`` instead of a string-length test due to possible overlong output.)
=> check-software: revise TeX module search function

bin/cylc-check-software
Another bug has been found in ``check-software``. When a Python module import fails within the ``check_py_module_ver()`` function, ``module_version`` does not get defined, leading to a traceback when trying to compare that variable with the (un)specified minimum version & report the result.
=> check-software: fix undefined variable traceback

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex
I thought it made sense for these two urls to be clickable like most are in the documentation. Also, fixed the url for graphviz documentation (no longer Documentation.php).
=> modified a python.org and graphviz.org link to be clickable in tex files

lib/cylc/suite_srv_files_mgr.py
Browsers don't like multiple certificates with the same number and issuer.
=> Random ssl cert serial numbers.

bin/cylc-gscan, lib/cylc/profiling/analysis.py, tests/cli/01-help.t
Invoking the commands with `--help` should no longer require DISPLAY.
Fix #2681.
=> Fix gscan and profile-battery --help display issue

tests/cli/01-help.t
After #2690, the number of sub-tests run for `cli/01-help.t` depends on the number of cylc 'library' commands, so whenever a command is added or removed, this test will throw an exit status of 1 & needs to be edited (as I discovered in creating a new command in a separate PR). For orthogonality, we can determine this number on the fly.
=> Auto-generate number of sub-tests in 'cli/01-help.t'

bin/cylc-cat-log
Currently, we get orphaned processes.
=> gui --host=HOST edit job log requires X11 forward

doc/src/cylc-user-guide/cug.tex, lib/cylc/network/httpclient.py
Obviously, we are aware of the security issues on the affected
platforms, but these warnings serve no purpose on those platforms except
to confuse or annoy users.
Sufficient to close #2686. (Real fix will require #1874.)
=> Add filter for security warnings from urllib3

doc/src/cylc-user-guide/gcylcrc.tex, lib/cylc/cfgspec/gcylc.py, lib/cylc/gui/updater_graph.py, lib/cylc/gui/view_graph.py
Hi there
As per [this](https://groups.google.com/forum/#!topic/cylc/RwE1q4Dxs3U) post on the Cylc Google group, here is a branch to allow GCylc to show subgraphs on start up.
Cheers
Jonny
=> Changes to allow grouped sub-graphs to be visible on GCylc startup.

bin/cylc, bin/cylc-help
Something like this good enough? https://groups.google.com/forum/#!topic/cylc/Z9Kt2dDTQGA
=> page cylc help output

lib/cylc/network/httpclient.py
cylc scan & cylc ping connect to suites using the user `anon` and using `verify=False`.
As a result of #2688, we now get `InsecureRequestWarning` warnings from urllib3 with these commands with python versions >= 2.7.9.
Also, rather than filter `SecurityWarning` (with python versions <2.7.9), we should filter `InsecurePlatformWarning` (the specific warning which was the problem in #2686).
Fix #2713.
=> Fix InsecureRequestWarning when using anonymous access

lib/cylc/task_events_mgr.py
Ensure that polling intervals lists are not overridden.
=> fix poll timers list override issue

README.md, etc/examples/parameters/chunking1/suite.rc, etc/examples/parameters/chunking2/suite.rc
Added the CYLC_TASK_PARAM prefix to environment variable names referenced by runtime scripts in the etc/examples/parameters/chunking*/suite.rc examples
=> Fix parameterized chunking task examples

lib/cylc/scheduler.py
I am debugging the code around `scheduler.py` to learn more about how it works, and while doing so, noticed that one instance of `SuiteProcPool` was always created just to be replaced by a new instance. Without ever being used.
`Scheduler()` (i.e. `__init__()`) will create a member variable `self.proc_pool = None`. Later, when  `scheduler_cli.py` calls the `Scheduler.start()` method, it will instantiate it with `self.proc_pool = SuiteProcPool()`.
At this point, `self.proc_pool` has been instantiated, but not used. Then the `start()` method calls the `configure()` method. One of the first things the `configure()` method does, is to replace the existing instance, by calling `self.proc_pool = SuiteProcPoo()` again.
This pull request simply prevents that by leaving only the first instance, …
=> Avoid creating an unnecessary SuiteProcPool and persist the instance of the SuiteLog on the first call

lib/cylc/scheduler.py, lib/cylc/suite_db_mgr.py, lib/cylc/task_pool.py, tests/restart/32-reload-runahead-no-stop-point.t, tests/restart/32-reload-runahead-no-stop-point/reference.log, tests/restart/32-reload-runahead-no-stop-point/suite.rc
For a suite with no final cycle point and tasks in the runahead point
(e.g. due to max active cycle points), a restart followed by a reload
would bring down the suite because the stop point was loaded from the
database as a string 'None' instead of a proper None.
This change should fix it.
Fix #2722.
=> Fix restart-reload release runahead bug

lib/cylc/remote.py, tests/job-submission/17-remote-localtime.t, tests/job-submission/17-remote-localtime/reference.log, tests/job-submission/17-remote-localtime/suite.rc
This fixes remote commands running in UTC mode when UTC mode is `False` or not set.
=> Fix remote always in UTC

bin/cylc
Not all git working copies have a `.git` directory.
=> better test for git working copy

lib/cylc/cycling/__init__.py, lib/cylc/cycling/iso8601.py, tests/cyclers/exclusions/graph.plain.ref, tests/cyclers/exclusions/reference.log, tests/cyclers/exclusions/suite.rc, tests/cyclers/exclusions_advanced/graph.plain.ref, tests/cyclers/exclusions_advanced/reference.log, tests/cyclers/exclusions_advanced/suite.rc
Fixes a curious runtime error caused by a combination of the later two recurrences in the following example:
```ini
[[[ R1 ]]]
graph = initial => main
[[[ P1M ! $ ]]]
graph = main => post
[[[ R1/$ ]]]
graph = post => final
```
Cylc plays nicely with these recurrences individually but when both present in the same suite:
```
...
File "cylc/lib/cylc/task_state.py", line 444, in _add_prerequisites
prv = seq.get_nearest_prev_point(point)
File "cylc/lib/cylc/cycling/iso8601.py", line 497, in get_nearest_prev_point
recurrence_iso_point in self.exclusions.p_iso_exclusions)
File "cylc/lib/isodatetime/data.py", line 1298, in __cmp__
type(other).__name__
TypeError: Invalid comparison type 'str' - should be TimePoint.
```
=> fix exclusions get_nearest_prev_point traceback

lib/cylc/batch_sys_manager.py, lib/cylc/task_job_mgr.py, tests/job-submission/05-activity-log.t
* Improve the readability of poll messages in the job activity log.
* Add a new metric `batch_sys_call_no_lines` which provides the number of lines of stdout output received from the batch system call (e.g. `qstat` for `pbs`) for help with debugging polling issues.
=> improve poll logging

tests/cylc-cat-log/10-remote-no-retrieve.t, tests/cylc-cat-log/11-remote-retrieve.t, tests/host-select/00-simple.t, tests/job-kill/04-pbs/suite.rc, tests/job-submission/05-activity-log.t, tests/remote/00-basic.t
Purge remote suite directory.
Fix job-kill 04 PBS out of memory issue.
(1 review probably sufficient, as it is only a tidy up of the tests.)
=> Remote tests tidy

lib/cylc/gui/scanutil.py
Remove unnecessary stuffs from About diaglog.
Improve help string for Hosts dialog.
Should be sufficient to close #2731.
=> gscan: improve hosts comments

bin/cylc
Uses the option `git --git-dir` instead of `git -C` to set the directory.
Resolves #2743
=> cylc --version backwards compatibility with older git versions

doc/src/cylc-user-guide/suiterc.tex
Hi, I am writing (or trying to write) a few suites with dynamic host selection, and noticed that the syntax of the example changed in this pull request looked a bit odd. I think it had an extra `)`?
Thanks
Bruno
=> Fix dynamic remote host selection command syntax

lib/cylc/scheduler.py
Trivial change.
Since the change in copyright notice the cylc logo and blurb no longer fit on an 80 character display.
=> make cylc logo/blurb fit on 80 character terminal

.travis.yml, bin/cylc-test-battery, tests/rnd/00-test-battery-chunking.t, tests/rnd/test_header
Deal with our travis-ci time limit woes. Chunk the battery into four parts which run in parallel, these take 10-15 mins to complete so we get faster results. On failure, we only need to re-run the failed chunk(s).
Due to the large amount of installation required for the cylc test battery 10 min jobs seem sensible.
=> travis-ci: chunk cylc test battery

bin/cylc-validate, tests/validate/67-task-proxy-sequence-bounds-err.t
Allow in normal mode (like `cylc run` will do).
Fail in strict mode.
Report in verbose mode.
Fix #2735.
=> validate: handle task proxy sequence bounds error

doc/src/cylc-user-guide/cug.tex, lib/parsec/jinja2support.py, tests/validate/44-jinja2-template-not-found.t
The future plan is to have proper API for Cylc, but this future is still quite far away. In the meantime, we could have some improvements to make the templating experience better. This PR adds two such improvements:
1) Support for Jinja2Tests and Jinja2Globals to complement the existing Jinja2Filters (thus enabling custom additions to all three namespaces used in Jinja2). This is useful as some Jinja2 functionality is awkward to use without them, e.g., `select`/`reject` filters, which use the `tests` namespace.
2) Support for importing Python modules in the same way as the template modules. This is useful, because the default Jinja2 functionality is fairly bare bones and there are some glaring omissions, like no Python `zip` equivalent, which makes some basic programming tasks quite …
=> Jinja2 enhancements

bin/cylc-monitor
=> Clean Ctrl-C exit from monitor.

.travis.yml, bin/cylc-test-battery
Nicer approach to wrapping prove which get rid of the whole prove re-running all tests when supplying the `--state=failed` flag problem.
=> improve test battery chunking

lib/cylc/gui/updater_tree.py
Hi, I believe sometimes when `should_rebuild_tree` is `True`, we are missing a few entries in the `for`-loop for updating the UI due to the variable `i` being used in both outer and inner loop.
Did a quick test printing values in both `for`'s (having a small glitch with debugger, and can't run the GUI in Eclipse), using the example suite for cycling hourly daily, and the output was slightly different in the logs.
The output in the GUI looks OK though.
Cheers
Bruno
=> Prevent re-declaring variable i in another for-loop

bin/cylc-ping, tests/cylc-ping/simple/suite.rc
While working on another Cylc PR (#2693) I noticed that within ``bin/cylc-ping`` there was a call to the global configuration that referenced a setting that was non-existent (either obsolete or a typo for a correct setting), breaking the ``--print-ports`` option. I am updating the setting in question anyway in that PR, so the bug will be fixed when that is merged (soon!), but given that it was not picked up by the test-battery, a new test should be added.
To aid review on the original PR I am requesting this new sub-test separately. To keep Travis CI etc. happy, this requires fixing the bug in the meantime.
=> cylc ping: remove option to print port range

CONTRIBUTING.md, etc/cylc-bash-completion
Currently cylc-bash-complete will complete cylc commands if cylc is the first word.
This modification will complete cylc commands if cylc is the only word and will complete registered suite names when specific commands (which take suite names) are the second word.
suite_cmds is ugly but I felt manually inputting commands that take suite names was better than completing suite names for all commands.
First time contributing so please let me know if I am missing anything.
=> cylc-bash-complete completes registered suite names when a command takes suite names

bin/cylc-check-software, doc/src/cylc-user-guide/cug.tex, tests/empy/00-simple.t
As requested in https://github.com/cylc/cylc/pull/2734#issuecomment-409254273, return a zero or non-zero output for a software dependency pass or fail, respectively. ``cylc check-software`` will under this implementation accept as an argument any module listed in the specification (the keys under ``opt_spec``, including the lower-case form). Without arguments it behaves as before.
=> check-software: update to accept module arguments

bin/cylc-cat-log, bin/cylc-get-host-metrics, bin/cylc-gpanel, bin/cylc-gscan, bin/cylc-help, bin/cylc-run, bin/cylc-scan, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/utils.py, lib/cylc/network/httpclient.py, lib/cylc/network/httpserver.py, lib/cylc/network/port_scan.py, lib/cylc/remote.py, lib/cylc/scheduler_cli.py, tests/cli/01-help.t, tests/cylc-get-host-metrics/00-simple.t, tests/cylc-get-host-metrics/test_header, tests/cylc-poll/17-pbs-cant-connect.t, tests/cylc-scan/01-hosts.t, tests/cylc.scheduler_cli/00-host-appointer.t, tests/cylc.scheduler_cli/test_header, tests/remote/01-unittests.t
Close #2323 & partially address #1885 & #988. To cover the **first three major points** in the host-selection master plan outlined by @matthewrmshin, copied verbatim into the following checklist:
1. Using `rose.host_select` as reference, develop new logic in cylc to select
the best suite host:
- load (uptime)
- memory (free)
- df (disk usage)
2. New settings in `global.rc`:
and `[communication]maximum number of ports` settings.~~)~~
3. - [x] Modify start up logic of `cylc run` and `cylc restart` to make use of the
new settings and host select logic where appropriate.
4. - [Later PR] Scheduler main loop to reload `global.rc` at regular intervals. Check if
current suite host is still a good host for running suites. Shutdown and
restart itself if required.
5. - [Later PR] Document new …
=> Incorporate suite host selection logic

lib/cylc/gui/combo_logviewer.py
As reported by a Met Office user:
```
File "/net/home/h03/fcm/cylc-7.7.2/lib/cylc/gui/app_gcylc.py", line 1271, in view_task_logs
self._popup_logview(task_id, task_state_summary, choice)
File "/net/home/h03/fcm/cylc-7.7.2/lib/cylc/gui/app_gcylc.py", line 2210, in _popup_logview
nsubmits, self.get_remote_run_opts())
File "/net/home/h03/fcm/cylc-7.7.2/lib/cylc/gui/combo_logviewer.py", line 47, in __init__
logviewer.__init__(self)
File "/net/home/h03/fcm/cylc-7.7.2/lib/cylc/gui/logviewer.py", line 37, in __init__
self.create_gui_panel()
File "/net/home/h03/fcm/cylc-7.7.2/lib/cylc/gui/combo_logviewer.py", line 69, in create_gui_panel
combobox2.set_active(snums.index(self.nsubmit))
ValueError: list.index(x): x not in list
```
Solving ``x not in range(1, x+1)`` with ``self.nsubmit`` as ``x``, …
=> gcylc: fix log viewer bug with zero submits

lib/cylc/task_remote_mgr.py, tests/communication-method/00-simple-https.t, tests/communication-method/01-simple-http.t, tests/communication-method/02-simple-defaultcomms.t, tests/communication-method/simple/reference.log, tests/communication-method/simple/suite.rc, tests/profile-battery/00-compatability.t, tests/restart/bad-job-host/suite.rc
Reduce chance of restart/13 test hanging.
Tidy up temporary logs on success of profile-battery/00 test.
Allow communication-method/* tests to complete before tidy by using no-detach reference tests.
Fix attribute that should be `subprocess.Popen.returncode`.
=> Tidy up tests/temporary locations on success

bin/cylc-cat-log, bin/cylc-get-host-metrics, bin/cylc-ping, bin/cylc-scan
A few unused imports (did not touch a few `import cylc` as they appear to be expected to be there even if unused to initialize the environment/dirs/etc).
Waited till Travis-CI passed the tests in my fork, so hopefully it won't fail this pull request :haircut_man:
=> Remove unused imports

bin/cylc-trigger
Restore nice relative symlink `NN -> [submit-number]` on edit-run back-out.  See https://github.com/cylc/cylc/pull/2803#issuecomment-430435400
No test needed - just a cosmetic change.
=> Relative NN symlink on edit-run backout.

lib/cylc/conditional_simplifier.py, lib/cylc/graph_parser.py, lib/cylc/profiling/analysis.py, lib/cylc/tests/test_conditional_simplifier.py, lib/cylc/tests/test_graph_parser.py
This pull request addresses issues reported in Coday about replacing `for x in range(len(abc))` by `for x, _ in enumerate(abc)`.
Using `range(len)` can be [faster](https://stackoverflow.com/a/11990189), but loses in readability (arguably, we could write assembly/cython/c/etc in parts of the `GraphParser` instead, and get better microbenchmarking, but read/maintainability would reduce?) . So I think it's OK to replace the entries in `ConditionalSimplifier` and `GraphParser`. Also changed the `profiling/analysis.py` entries, though I didn't write unit tests for those.
If changing this is too risky, or others think it is not necessary, I would still like to keep the pull request, remove the changes, and leave the tests :grimacing: as that would increase more the coverage for Python 3. No …
=> Replace range(len) by enumeration

bin/cylc-cat-log, doc/src/cylc-user-guide/cug.tex, lib/cylc/rundb.py, lib/cylc/tests/test_rundb.py
There is one security issue in Codacy that looks possible to be exploited. This pull request follows up a [recent discussion in another ticket](https://github.com/cylc/cylc/issues/2800#issuecomment-430166049), and removes a parameter that was not used, but that if used would change the columns used for the returned values.
Removing that part of the code, I expect Codacy to ignore the error now too. It may still report the issue due to other string concatenations, but at least this one is not a parameter, reducing the risk I believe.
=> Fix security issue reported in Codacy for CylcSuiteDAO.select_task_job in rundb

doc/src/cylc-user-guide/cug.tex, lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_outputs.py, lib/cylc/task_proxy.py, tests/cylc-message/01-newline.t, tests/events/38-task-event-handler-custom.t, tests/events/45-task-event-handler-multi-warning.t, tests/events/46-task-output-as-event.t
Fix #2806.
(Plus new functionality: task output based events).
=> Fix task event handler simul multi warnings

bin/cylc-register, doc/src/cylc-user-guide/cug.tex, lib/cylc/scheduler.py, lib/cylc/scheduler_cli.py, lib/cylc/suite_srv_files_mgr.py, tests/authentication/08-shared-fs.t, tests/authentication/10-remote-suite-passphrase-cache.t, tests/authentication/11-suite2-stop-suite1.t, tests/registration/00-simple.t, tests/registration/02-on-the-fly.t
Close #2758 
Close #2749 
[UPDATED description 15 Oct]:
Abort suite registration if:
* `suite.rc`not found in target directory (this allows us to distinguish correct arg order)
* name is an absolute path (can only be relative).
* name is already registered to another suite
- but allow forced re-use of existing name and run directory with `--redirect`
Also support:
- auto-registration of suite in `$PWD`
- `cylc reg NAME` (auto-reg)
- `cylc reg` (auto reg and auto-name - with name of parent dir)
- on-the-fly  auto-registration by "cylc run" (of suite in `$PWD`, with name of parent dir).
- replacing (via `exec`) process `cylc run` with `cylc run NAME` for easy identification with `ps` etc.
=> Cylc registration fix.

bin/cylc-cat-log, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/job.sh, tests/job-submission/01-job-nn-localhost/suite.rc
Fix a small but long-standing niggle.  Users (/jobs) can write custom files to task job log directories via `$CYLC_TASK_LOG_ROOT`, which is not very intuitively named and which is actually the full path of the job script.  I think(?) this was originally intended to encourage users to prefix all custom filenames with "job", but there's really no reason why they can't have entirely different filenames in the job log directory (in fact I'd argue the "job" prefix should be reserved for files automatically generated by cylc, to make custom ones stand out) ... and this doesn't stop them anyway (via `$(dirname $CYLC_TASK_LOG_ROOT)/my-file`).  
So this PR adds `$CYLC_TASK_LOG_DIR` to job environments.  (And modifies one test enough to ensure that the variable exists).
=> New job env var: CYLC_TASK_LOG_DIR.

bin/cylc-register, lib/cylc/scheduler_cli.py, lib/cylc/suite_srv_files_mgr.py, tests/registration/00-simple.t
Follow-up to #2759 (sorry) to disallow a confusing edge case.
On master, `cylc reg NAME` (i.e. PATH arg omitted) does nothing if NAME is already registered to another suite, but it registers a suite in `$PWD` as NAME [if it isn't already registered]. 
The former case is not correct.  If deriving suite path or name from current directory path, it doesn't make sense to simply "re-register" an existing suite in a different location.
So now, on this branch `cylc reg NAME` always "tries to" point NAME at `$PWD/suite.rc`.  By "tries to" I mean does so if NAME is not already used, otherwise abort unless `--redirect` is used (because overwriting an existing run directory is potentially dangerous).  This is consistent with `cylc reg NAME PATH` always trying to register `$PWD/suite.rc` as NAME. 
In …
=> Cylc reg tweak.

lib/cylc/gui/gscan.py
Don't force host/owner visibility in multi-host/owner modes. (Ref #2096.)
=> gscan: don't force host/owner vis

lib/cylc/scheduler_cli.py, lib/cylc/suite_srv_files_mgr.py, tests/registration/02-on-the-fly.t
With #2759 we accidentally broke the ability to write a suite in the `cylc-run` directory and execute it in place without registration. (see https://github.com/cylc/cylc/pull/2759/files#diff-cc8dd196aae04c5bc5e5df82839b59eaL425)
With this change if a suite directory exists but the `.service` doesn't, Cylc will register the suite as `cylc-run/REG`. Can we think of a better check than the presence of the `.service` dir?
Happy to change approach but feel free to take over this one if it will speed up the release.
=> fix cylc run REG without cylc register

lib/cylc/hostuserutil.py, lib/cylc/network/port_scan.py
As reported by @jonnyhtw on the mail forum, 
```
cylc (g)scan zilch
``` 
drops a large number of nasty tracebacks if host `zilch` does not exist - difficult for users to understand.
On this branch, you get multiple lines of this instead:
```
ERROR: [Errno -2] Name or service not known: zilch
```
There are multiple errors because we attempt to scan multiple ports.  It would be a bit harder to report the error only once, but probably not necessary.
=> Print simple socket error.

bin/cylc-suite-state, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/config.py, lib/cylc/task_job_mgr.py, tests/cylc-get-config/00-simple/section2.stdout, tests/suite-state/00-polling.t, tests/suite-state/01-polling.t, tests/suite-state/polling/reference.log, tests/suite-state/polling/suite.rc, tests/suite-state/upstream/suite.rc
Close #2739 (fix `cylc suite-state` and automatic polling task documentation omissions).
Also, for completeness, makes auto suite-state polling tasks work with the newer `--message` option (poll for task message instead of status).
=> 2739 doc fixes

etc/syntax/cylc-mode.el
The ``emacs`` editor is lacking the basic level of syntax highlighting all-inclusive support provided for the other editors supported to some extent (see first 7 rows of the table given in #2752). In particular, Jinja2 ``{% ... %}`` & multi-line statements should at least be fully supported & this is implemented here.
=> suite.rc syntax lexers: improve emacs support

lib/parsec/tests/unit/01-util.t, lib/parsec/util.py
Group sequences of 3 or more integers, equal steps `START..END[..STEP]`
syntax or same number `N*INT` syntax.
(It writes the full list currently, so for something like the port range, we can get 100 numbers written out, which is not very nice.)
=> parsec configuration dump: nicer int list values

bin/cylc-cat-log
Trivial change to handle use of non-standard run directories on job hosts.
E.g. with:
```
[hosts]
[[wizard]]
run directory = /nfs/otherhome/$USER
```
=> cat-log remote env vars.

lib/cylc/cycling/iso8601.py, lib/cylc/wallclock.py, lib/isodatetime/__init__.py, lib/isodatetime/data.py, lib/isodatetime/dumpers.py, lib/isodatetime/parser_spec.py, lib/isodatetime/parsers.py, lib/isodatetime/run_tests, lib/isodatetime/tests.py, lib/isodatetime/timezone.py, lib/isodatetime/util.py
Updates `isodatetime` to the latest version available (thanks @matthewrmshin !), and fixes code for compatibility.
There was one [bug](https://github.com/metomi/isodatetime/issues/102) which I fixed in [pr#103](https://github.com/metomi/isodatetime/pull/103), but it caused an issue in Cylc fixed in this commit:
https://github.com/cylc/cylc/commit/4aa8a8bc117819e2f67fcadfa3c608916a0be5e6
I will wait for Travis-CI to kick in and verify this pull request, but it is also important that others with more experience with the `iso8601.py` have a look to see if they agree with the change.
To me, it appears it was always working, because we were always having a `KeyError` coming from `isodatetime`, but after fixing this behaviour in `isodatetime`, I think it makes sense to switch the order of the …
=> Update isodatetime to 2018.11.0

lib/cylc/gui/app_gcylc.py
... & make all the docstrings in ``app_gcylc.py`` consistent in format.
To recreate, launch the GUI with no suite(s) as argument(s) i.e. ``gcylc &``. I get the traceback:
```
File "<...>/lib/cylc/gui/app_gcylc.py", line 444, in _log_widget_launch_hook
self.log_launch_hook()
File "<...>/lib/cylc/gui/app_gcylc.py", line 3205, in <lambda>
lambda: self.run_suite_log(None, log="e"))
File "<...>/lib/cylc/gui/app_gcylc.py", line 3318, in run_suite_log
self.updater.task_list)
AttributeError: 'NoneType' object has no attribute 'task_list'
```
I started by trying to bypass this directly, via starting ``run_suite_log()`` with:
```
task_listing = None
if self.updater is not None:
task_listing = self.updater.task_list
```
& making ``task_listing`` the new final argument to the following …
=> gui: fix error on generic (argument-free) launch

lib/cylc/graph_parser.py
Some days ago while writing a Jupyter Notebook and looking at the `GraphParser` API, I realized its `print_triggers` function had a weird output of tuples. Further investigation showed this function was never used.
It was, however, mentioned in a comment. Suggesting that this could  be useful when debugging. However, it is also possible to see the same structure in a debugger, and less code is less code for us to maintain and to worry about when porting to Python 3 :grin: (and one post-is less on my monitor)
=> Remove unused GraphParser's print_triggers function

lib/cylc/batch_sys_handlers/__init__.py, lib/cylc/c3mro.py, lib/cylc/cfgspec/__init__.py, lib/cylc/gui/__init__.py, lib/cylc/log_diagnosis.py, lib/cylc/xtriggers/__init__.py, lib/parsec/tests/getcfg/bin/one-line.py, lib/parsec/tests/nullcfg/bin/empty.py, lib/parsec/tests/synonyms/bin/synonyms.py
While working on the unit tests for parsec, I noticed that `OrderedDictCompat.py` did not have the license header. So I added a post-it to submit this pull request later.
Did a `find lib/{parsec,cylc} -name "*.py" -exec grep -H -L "THIS FILE IS PART OF THE CYLC SUITE ENGINE." {} \;` to locate the files without the license header, and fixed most of them.
The only file I did not fix, in the end, was `OrderedDictCompat.py`... because a) looks like the code is actually [MIT licensed](http://code.activestate.com/recipes/576693-ordered-dictionary-for-py24/), so not sure whether it can be simply re-licensed or if we must include the header with copyright to the original coder, and b) because we will remove it anyway when we go Python 3.
=> Add missing license headers

lib/parsec/util.py
Another one found while writing unit tests for parsec, and reading the code of some of the Python files within the package.
In this case, I believe this assignment of `target = OrderedDictWithDefaults()` creates a local variable `target`, and returns.
There is another `target`, an argument, that is unaffected by this. So I think we can safely remove it.
=> Remove unnecessary assignment to target variable

lib/cylc/gui/app_gcylc.py
Possible solution to https://github.com/cylc/cylc/issues/2727. Not yet ready for review, I just want Travis to take a look.
=> nsubmits for use in gui retrieved from submit no rather than len(hosts)

tests/execution-time-limit/02-slurm.t, tests/execution-time-limit/03-pbs.t, tests/job-submission/07-multi/suite.rc
Cut lines that are commented out but functional without the comment marker, clearly originating from development or testing or debug stages.
I've checked the tests don't rely on these lines e.g. via ``sed`` substitution to remove them & then incorporate the lines.
Trivial, hence lone reviewer sufficient (& I'll pick on the author :grin:).
=> Remove commented-out functional lines in tests

lib/cylc/batch_sys_manager.py, lib/cylc/task_job_mgr.py, tests/cylc-review/00-basic.t, tests/database/00-simple.t, tests/database/00-simple/select-task-jobs.out, tests/database/01-broadcast.t, tests/database/02-retry.t, tests/database/03-remote.t
Ensure that `localhost` background/at jobs are recorded as running on the host name of the current suite host, rather than just `localhost`. On suite restart on a different suite host, this allows the restart logic to correctly poll the status of the background/at jobs that may still be running on the previous suite host.
Perfect companion of #2809.
=> localhost background/at jobs: record host name

lib/cylc/task_pool.py
This check is unnecessary, because it is repeated in branch 1 and 2 in the subsequent `if..elif..elif..else` block, and causes the logic to skip branch 3 unnecessarily.
=> Fix restart unnecessary task action timer check
