cylc/cylc-flow

doc/siterc.tex, lib/cylc/cfgspec/globalcfg.py, lib/cylc/cfgspec/suite.py, lib/cylc/job_file.py, tests/jobscript/05-global-config.t, tests/jobscript/05-global-config/conf/global.rc, tests/jobscript/05-global-config/reference.log, tests/jobscript/05-global-config/suite.rc
Close #802. Close #1266.
Tested locally and works for me.
No test added to the test battery yet - unsure how to do this therefore investigating.
=> cylc globalcfg: upgrade to ISO syn, doc, back comp.

lib/cylc/scheduler.py, tests/validate/26-fail-initial-greater-final/suite.rc
=> 1283.run mode cmd line parsing

lib/cylc/task_proxy.py, tests/hold-release/14-hold-kill.t, tests/hold-release/14-hold-kill/reference.log, tests/hold-release/14-hold-kill/suite.rc
=> Hold task from retrying while killing its job

tests/directives/00-loadleveler.t, tests/events/00-suite.t, tests/hold-release/11-retrying.t, tests/hold-release/12-hold-then-retry.t, tests/hold-release/13-ready-restart.t, tests/hold-release/14-hold-kill.t, tests/job-kill/02-loadleveler.t, tests/lib/bash/test_header, tests/restart/03-retrying.t, tests/restart/04-running.t, tests/restart/08-retrying-loadleveler.t, tests/restart/09-running-loadleveler.t, tests/restart/10-submit-failed-loadleveler.t
Purge helper suites.
Purge remote suite directories.
Fix incorrect purge arguments.
=> test-battery: fix purge suite

lib/cylc/config.py, tests/cyclers/integer1/graph.plain.ref, tests/graphing/02-icp-task-missing.t, tests/graphing/02-icp-task-missing/graph.plain.ref, tests/graphing/02-icp-task-missing/suite.rc
=> Fix initial right-hand-dep task graphing bug

lib/cylc/task_pool.py
Fix #1351.
It's not clear how to make a test for this.  It could be done by restarting with all tasks succeeded or failed (at least one failed to prevent shutdown) then checking the output of ```cylc dump```, because runahead pool tasks are currently not dumped.  However, they probably should be dumped as part of #1320, so that would be a short-lived test.
Test battery passes.
@matthewrmshin - please review or reassign.
=> Release any finished tasks in the runahead pool.

doc/cug.tex, doc/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/config.py, tests/validate/28-fail-constrained-initial.t, tests/validate/28-fail-constrained-initial/suite.rc, tests/validate/29-fail-constrained-final.t, tests/validate/29-fail-constrained-final/suite.rc, tests/validate/30-pass-constrained-initial.t, tests/validate/30-pass-constrained-initial/suite.rc, tests/validate/31-pass-constrained-final.t, tests/validate/31-pass-constrained-final/suite.rc
Close #1279.
Adds:
* New entry for constraining initial and final cycle points
* Tests
* Update documentation
=> Implement initial and final cycle point constraints.

lib/cylc/gui/gpanel.py, lib/cylc/gui/gsummary.py
=> cylc gsummary: update time from suite

lib/cylc/config.py, tests/validate/28-fail-graph-double-ampsand.t, tests/validate/28-fail-graph-double-ampsand/suite.rc, tests/validate/29-fail-graph-double-pipe/suite.rc
Closes #1352 
Tested and tests added.
=> cylc validate: fail if && in graphing

lib/cylc/config.py, tests/validate/30-fail-max-active-cycle-points-zero.t, tests/validate/30-fail-max-active-cycle-points-zero/suite.rc
Closes #1365 
Tested and tests added.
=> cylc validate: max active cycle points > 0

bin/cylc-cycle-point
=> Fixed a command help typo.

lib/cylc/batch_sys_handlers/at.py, lib/cylc/batch_sys_manager.py
If `Can't open /var/run/atd.pid to signal atd. No atd running?` line is
in STDERR of `at` command, kill the submitted job and fail the submit.
Close #1280.
=> cylc.batch_sys_handlers.at: handle atd not running

lib/cylc/config.py
Closes #1360 
Allows use of relative final cycle points in visualization settings.
=> Fix visualising offset final

doc/cug.tex
@benfitzpatrick please review.
=> CUG: improve usage doc of job submit directives

examples/jinja2/cities/suite.rc
=> Fix test broken by #1380

lib/cylc/gui/app_gcylc.py
=> gcylc: fix view task prerequisites

doc/cug.tex
=> document manual trigger and edit run

bin/cylc-broadcast, lib/cylc/broadcast.py, lib/cylc/broadcast_report.py, tests/broadcast/05-bad-point.t, tests/broadcast/05-bad-point/suite.rc, tests/broadcast/06-bad-namespace.t, tests/broadcast/06-bad-namespace/suite.rc
=> Handle broadcast to invalid cycle points and namespaces.

lib/cylc/config.py, tests/validate/32-fail-not-integer.t, tests/validate/32-fail-not-integer/suite.rc
=> cylc validate: integer v cycling conflict

doc/cug.tex
Should have been done as part of #1166.
=> CUG: document `~/.cylc/job-init-env.sh` + friends

lib/cylc/gui/gsummary.py
=> cylc gsummary: retrieval time not suite updated

lib/cylc/config.py, tests/validate/33-fail-graph-bracket-missing.t, tests/validate/33-fail-graph-bracket-missing/suite.rc
=> validate fail missing bracket pair

bin/cylc-hold, bin/cylc-poll, bin/cylc-release, bin/cylc-remove, bin/cylc-reset
@matthewrmshin - please review or reassign.  This is essentially a bit more of #1430.  If it passes muster today, upgrade the milestone to include in tomorrow's release.
=> Correct some CLI help and arg checking.

lib/cylc/rundb.py
Closes #1213 - both databases dump unwritten output as of #1295, this adds final piece of puzzle to allow increased robustness against public database locking.
Defines separate commit_attempt values for the private and public databases.
Also relates to #1476 
@hjoliver - please review.
=> increase secondary db retries

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater.py
Fixes lack of a reload progress bar if the suite has a final point.
Close #1484 
@arjclark - please review.  Apologies if you'd already done some work on this.
=> gcylc - tidied state string handling.

bin/cylc-gsummary, bin/cylc-scan, lib/cylc/CylcOptionParsers.py
=> Restore command option ordering.

lib/cylc/gui/updater_tree.py, lib/cylc/gui/view_tree.py
Task progress bars based on the mean completion time for each task.
=> gcylc - tree view task progress bars

bin/cylc-restart, lib/cylc/suite_state_dumping.py, tests/restart/back-comp-restart/state
=> Fix restart status string.

lib/cylc/cfgspec/globalcfg.py
=> Set process pool size default to 4

doc/siterc.tex
Addresses documentation mistake from #1501 
@hjoliver - this should now be correct.
=> Fix documentation missing entry.

lib/cylc/config.py
This closes #1525.
Assigned to me for some thorough testing.
=> Daemon now caches graph edges

lib/cylc/batch_sys_handlers/moab.py
Supersedes #1438 (taken from @chanwilson, then spurious comments deleted as discussed there).
@matthewrmshin - please review.  I think we can assume this was tested by @chanwilson.
=> Chan Wilson's moab support.

lib/cylc/config.py, lib/cylc/graphing.py, tests/graphing/05-suicide-family.t, tests/graphing/05-suicide-family/graph.plain.ref, tests/graphing/05-suicide-family/suite.rc
This removes some spurious code added on the recent cyclic graph detection branch, which was making suicide-triggered families graph wrongly.
Close #1526
=> Fixed graphing of suicide-triggered families.

lib/cylc/broadcast_report.py, lib/cylc/network/suite_broadcast.py, lib/cylc/rundb.py, lib/cylc/task_pool.py, tests/broadcast/00-simple.t, tests/database/00-simple/schema.out, tests/database/01-broadcast.t
Add `broadcast_states` table for current broadcasts.
Rename table `broadcasts` to `broadcast_events`.
Close #1519.
=> cylc.rundb: add broadcast_states table

lib/cylc/cycling/__init__.py, lib/cylc/cycling/iso8601.py, tests/validate/39-degenerate-point-format.t, tests/validate/39-degenerate-point-format/suite.rc
=> Disallow too-coarse-grained cycle point formats

lib/xdot.py
=> cylc gui: click to re-centre graph node

lib/cylc/scheduler.py, tests/cylc-insert/04-insert-family.t, tests/cylc-insert/insert-family/reference.log, tests/cylc-insert/insert-family/suite.rc
Broken recently by #1493; looks like we don't have any tests for insertion of families (yet...)
=> Fixed task family insertion.

lib/cylc/network/suite_broadcast.py
Addresses: https://github.com/cylc/cylc/pull/1545#issuecomment-125488722
Adds locking to prune operation. 
@benfitzpatrick please review 1.
=> Add extra locking in _prune method.

lib/cylc/gui/gsummary.py
At some point we lost the ability to resize columns in gsummary.
This adds it back in.
@kaday - please review 1.
@benfitzpatrick or @hjoliver please review 2.
=> Make gsummary columns resizable.

lib/cylc/batch_sys_handlers/moab.py
See https://github.com/cylc/cylc/pull/1533#issuecomment-136521366
=> Corrected moab job submit template.

conf/gcylcrc/gcylc.rc.eg, doc/gcylcrc.tex, lib/cylc/cfgspec/gcylc.py, lib/cylc/gui/app_gcylc.py
=> cylc gcylc: side-by-side view option in gcylc.rc

lib/cylc/network/suite_broadcast.py
Follow up from #1545.
Adds in the missing locking required under `expire()`, as found during ps36 (see 6.4.1.u2).
Also protect a further part of the load() code.
@matthewrmshin - please review 1.
=> broadcast.py: Add further locking protection.

lib/cylc/gui/app_gcylc.py
Close #1590.
@m214089 - can you confirm this fixes the problem in your environment?
@matthewrmshin - please review 1.
=> Handle use of GUI task filtering before a suite is connected.

bin/cylc, lib/cylc/gui/app_gcylc.py, lib/cylc/prerequisite.py
Close #1616.
Also removes GUI code for the no longer existing `cylc depend` command.
@benfitzpatrick @kaday - please review.
=> 1616.fix prereq print error

lib/cylc/gui/updater_tree.py
Should fix #1564 (line 402 problem).
=> GUI: fix tree updater KeyError

lib/cylc/config.py, tests/validate/48-fail-bad-vis-nod-attrs.t, tests/validate/48-fail-bad-vis-nod-attrs/suite.rc
Fixes a minor bug, to close #1561.
=> Better warnings for bad vis config.

lib/cylc/conditional_simplifier.py, lib/cylc/prerequisite.py, tests/graphing/06-family-or.t
@matthewrmshin & @arjclark - please review - very carefully as I'm not the expert on this bit of code! 
Close #1626
=> Fix pre-initial simplification bug.

doc/cug.tex, lib/cylc/cylc_xdot.py, lib/cylc/gui/updater_graph.py
Reverts cylc/cylc#1641 so we are still on course for a release tomorrow.
=> Revert "cylc gcylc: ignore suicide triggers as default"

tests/authentication/07-back-compat.t
Test will no longer print "Suite initializing..." randomly to screen.
@hjoliver please review. (I don't think review 2 is necessary.)
=> t: fix random "Suite initializing..." message

lib/cylc/gui/tailer.py
On signal to `ssh` client, a signal is sent to `sshd` on server.
However, `sshd` cannot send a signal to the `tail` command, because it
is not a terminal. This leaves the `tail` command in a zombie state.
Apparently, we can use `ssh -t` or `ssh -tt`, but that just causes the
command to hang for some reason, (which hangs the GUI as well). A quick
hack here is to do something like `tail --pid=$PPID`, so `tail` dies as
soon as `PPID` dies.
=> cylc.gui.tailer: fix SSH zombie tail

lib/cylc/network/connection_validator.py, tests/authentication/07-back-compat.t
=> Fixed back-compat for old clients with passphrase.

tests/events/01-task.t, tests/events/07-task-iso.t, tests/events/task-iso/bin/log-check.sh, tests/events/task-iso/events.log, tests/events/task-iso/suite.rc, tests/events/task/bin/log-check.sh, tests/events/task/suite.rc
Should resolve Ubuntu 14.04 issue reported in #1656.
=> tests: tune timing for passing on Ubuntu VM

lib/cylc/gui/app_gcylc.py
Close #1668.
@matthewrmshin - please review (one review is probably enough in this case).
=> Refresh views after filter update, not before.

bin/cylc-test-battery
Similar change to metomi/rose#1761 and metomi/fcm#211.
=> Improve doc for test-battery command

tests/validate/42-jinja2-template-syntax-error-main.t
We have missed this in #1687.
@arjclark please review. (I don't think we need review 2 for this one.)
=> tests: purge registration on completion, more

lib/cylc/task_proxy.py
This change should be sufficient to close #1690.
On polling an individual task, you will get a latest message in the GUI tree view like: *submitted (polled)*.
On polling all, you will still not get a *Command queued* message window, but each item polled will get the message above.
@arjclark @hjoliver please review.
=> cylc gui: reinstate poll/kill message

lib/cylc/config.py, tests/message-triggers/03-placeholder.t, tests/message-triggers/03-placeholder/suite.rc
Close #1547.
@matthewrmshin - please review (one review is probably enough).
=> Check for cycle offset placeholder in message outputs.

bin/cylc-graph, lib/cylc/config.py, lib/parsec/Jinja2Support.py, tests/graphing/07-stop-at-final-point.t, tests/graphing/07-stop-at-final-point/graph.plain.ref, tests/graphing/07-stop-at-final-point/suite.rc
=> Don't plot graph past final cycle point.

bin/cylc-restart, bin/cylc-run, doc/suiterc.tex, lib/cylc/cfgspec/suite.py, lib/cylc/scheduler.py, tests/shutdown/05-auto.t, tests/shutdown/05-auto/suite.rc
Close #1711.  @matthewrmshin - please assign reviews.
=> 1711.suite auto shutdown

lib/cylc/gui/app_gcylc.py
=> cylc gcylc: inverting the button event to release

lib/cylc/gui/view_dot.py, lib/cylc/gui/view_graph.py, lib/cylc/gui/view_tree.py
Closes #1740 
Haven't been able to duplicate circumstances locally.
@arjclark please review.
=> cylc gui: handle missing task status when setting up right-click menu

lib/cylc/batch_sys_handlers/at.py, lib/cylc/batch_sys_manager.py, tests/job-submission/10-at-shell.t, tests/job-submission/10-at-shell/reference.log, tests/job-submission/10-at-shell/suite.rc
=> job submit with at: force SHELL=/bin/sh

bin/cylc-message, lib/cylc/job_file.py, lib/cylc/task_message.py, tests/broadcast/00-simple/suite.rc
Turn on `set -x` with a PS4 string that produces a time stamp on
verbose+debug mode.
Close #1719.
=> job file: time stamp xtrace on debug mode

tests/reload/17-state-summary.t
=> cylc test-battery: reload state test: add cylc reload call

tests/state-dump/03-queued-no-repeats.t
Make the tests/state-dump/03-queued-no-repeats.t test work more reliably.
The important thing is that the state files are all different, not the number of state files.
=> cylc test-battery: more reliable queued state dump test

lib/parsec/Jinja2Support.py, lib/parsec/fileparse.py, tests/validate/51-jinja2-undefined-error.t, tests/validate/51-jinja2-undefined-error/suite.rc
This closes #1714.
@hjoliver, @matthewrmshin please review.
=> parsec: better jinja2 type/undef errors

lib/cylc/gui/view_tree.py
closes #1781 
@arjclark Please Review
=> cylc gui: fixed right click not showing bug.

doc/cug.tex
This documents how to avoid some of the memory issues encountered in #1776 (for the benefit of both validate and runtime).
@hjoliver - please review. As its a documentation update I'll leave it to you to decide if you want a second reviewer.
=> Document writing efficient inter-family triggering.

bin/cylc-monitor, lib/cylc/gui/updater.py, lib/cylc/network/suite_state.py
Follow-up to #1806, which broke monitor and GUI compatibility with older suite daemons.
@matthewrmshin - please review and/or assign.
=> Make 1806 work with older suite daemons.

lib/cylc/gui/gscan.py
This also fixes back compat with suites running at 6.4.X or below.
=> gscan: display running suites with no states

lib/cylc/gui/view_tree.py
This closes #1770.
@arjclark, @hjoliver please review. Next-release-inclusion optional, I think.
=> cylc gui text view: allow right click menu on cycle point

requirements.txt
@matthewrmshin - I believe this line should no longer be in there following #1755.
=> Remove Pyro requirements.txt entry as its now bundled in cylc.

lib/cylc/registration.py
It was caching passphrases for any remote connections (regardless of where the passphrase was loaded from). The problem was introduced by #1729. It was harmless, but could cause disk issues if caught unaware.
=> Only cache passphrase on disk if loaded via SSH

lib/cylc/cfgspec/suite.py, tests/events/22-suite-reset-timer.t, tests/events/22-suite-reset-timer/suite.rc
It has lost the default=True setting due to #1743. Fix #1837.
=> Fix reset timer

doc/siterc.tex, doc/suiterc.tex
@arjclark - one review should do it.
=> Fixed several minor CUG typos.

lib/cylc/network/suite_state.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, tests/reload/19-graphing-change.t, tests/reload/graphing-change/suite-1.rc, tests/reload/graphing-change/suite-2.rc, tests/reload/graphing-change/suite.rc
Closes #1265 
Closed #1867 
@arjclark Please Review
=> cylc reload: report added/removed tasks

lib/cylc/batch_sys_manager.py, tests/job-submission/12-tidy-submits-of-prev-run.t, tests/job-submission/12-tidy-submits-of-prev-run/reference.log, tests/job-submission/12-tidy-submits-of-prev-run/suite.rc, tests/job-submission/13-tidy-submits-of-prev-run-remote-host, tests/job-submission/13-tidy-submits-of-prev-run-remote-host.t, tests/job-submission/14-tidy-submits-of-prev-run-remote-host-with-shared-fs, tests/job-submission/14-tidy-submits-of-prev-run-remote-host-with-shared-fs.t
Should be enough to close #480.
=> job submit 01 removes old 02+ logs

lib/cylc/gui/app_gcylc.py
@hjoliver I think a single review should do.
=> Remove trailing whitespace

doc/cug.tex, lib/cylc/cycling/integer.py
Closes #1870 
Accompanied by https://github.com/metomi/rose/pull/1926
@hjoliver Please review and assign second if desired.
=> recurrence terminology: repeat -> run

lib/cylc/config.py, lib/cylc/task_proxy.py, tests/modes/02-dummy-message-outputs.t, tests/modes/dummy-message-outputs/reference.log, tests/modes/dummy-message-outputs/suite.rc
Close #1420 (knocking off a quick "small" issue).
@matthewrmshin - please review/assign.
=> 1420.dummy mode custom outputs

tests/cylc-trigger/03-edit-run.t, tests/integer-cycling/00-satellite/suite.rc, tests/jobscript/00-torture/foo.ref-jobfile
Looks like #1910 has broken some tests. (I get the blame.) Here is the fix.
=> Fix tests broken by #1910

doc/suiterc.tex
Should be enough to close #1916.
@arjclark please review.
=> Doc: fix suite.rc event hooks syntax

lib/cylc/gui/updater_dot.py
Closes #1933 
@hjoliver Please review.
@benfitzpatrick Please review.
=> gcylc: fixed definition order sort bug

lib/cylc/task_pool.py
Closes #1941 
@hjoliver - please review (assign review 2 if you think necessary)
=> 1941: Add retrying to non stalled states.

tests/cycletime/02-template.t
Close #1157 
@hjoliver - please review and/or assign review 2 as necessary.
=> Add cyclepoint template tests

lib/cylc/config.py, tests/validate/56-self-suicide.t, tests/validate/56-self-suicide/suite.rc
Closes #1946 
@hjoliver - please review (minor change so up to you if you want review 2)
=> Remove validation self suicide warning.

tests/runahead/default-simple/suite.rc
A trivial change to close #1824.
@matthewrmshin - please review or reassign.  (Or anyone else can, if Matt's still away).
=> Increased a test suite timeout.

lib/cylc/scheduler.py
Profiling is not currently outputting a 'loop' entry every minute.
@benfitzpatrick Please Review / Reassign / Assign
=> profiling: main loop profiling fix

README.md
=> Link to Travis CI master build status from README

tests/database/01-broadcast/suite.rc, tests/events/10-task-event-job-logs-retrieve.t, tests/events/11-cycle-task-event-job-logs-retrieve.t, tests/job-submission/05-activity-log/suite.rc
These 2 have been failing randomly under Travis CI. I am tweaking them slightly to see if they behave better or not.
=> tests: even more stability improvements

bin/cylc-submit, lib/cylc/suite_logging.py, lib/cylc/task_proxy.py
Closes #1988 
@arjclark Please Review
=> Fixed 'No Handlers found...' error.

tests/cylc-cat-log/06-log-rotation.t
Rewrite test to use our common test tool kit to set up temporary suite location, etc. to ensure generated items are tidied up.
@oliver-sanders please review.
=> tests cylc-cat-log 06: tidy temporary directory

tests/events/25-held-not-stalled/suite.rc
Ensure that it overrides a `True` setting in `global.rc`.
@hjoliver please review or reassign.
=> test events-25: add `abort on inactivity set=False`

lib/cylc/graph_parser.py, tests/validate/59-offset-no-offset.t
This is #2002 (on 6.11.x) for master.
=> Fix new graph parser bug (PR to master)

lib/cylc/batch_sys_handlers/background.py
Equivalent of #2006 for 6.11.x. @hjoliver please review.
=> 6.11.x: fix background OSError handling

lib/cylc/gui/gscan.py
Fixes a relatively rare bit of traceback from gscan.
@hjoliver Please review / bump milestone.
=> Fix gscan traceback

doc/scripts/make-index.sh
=> Fixed CHANGES.md url

lib/cylc/gui/gscan.py
Equivalence #2028.
@matthewrmshin Please review / assign.
=> 6.11.x.gscan status icon fix

lib/cylc/gui/app_gcylc.py
Address #2010 for 6.11.x. @hjoliver @oliver-sanders please review.
=> cylc gui: fix remove tasks after spawn

lib/cylc/gui/updater.py
The pop up warning dialog can be very annoying on suite start up and
automatic shut down. Now that we have the connection count down, we
don't really need to use the warning dialog on connection error.
Equivalence of #2021, but for 6.11.x.
=> gui: don't warn on connection error

bin/cylc-stop, bin/cylc-suite-state, lib/cylc/command_polling.py
No need to use suite logging facility for a client command.
Minor refactor to improve style and flow.
Equivalence of #2017. Address #2011 for 6.11.x. @hjoliver @oliver-sanders please review.
=> Restore command polling simple print/write

doc/cug.tex
With an example on relationship between qsub/qstat for pbs, moab and
sge.
Should be sufficient to close #1879.
=> doc: add polling batch command requirement

lib/cylc/gui/app_gcylc.py, lib/cylc/task_pool.py
Simpler version of #2046. Address #2045 for 6.11.x.
=> cylc gui: fix view prerequisites for runahead task

doc/suiterc.tex
Missing doc entry to go with #1966 
@hjoliver - please review. Hopefully this covers the caveats you wanted to go with it.
=> Document spawn to max active cycle points.

lib/cylc/network/https/suite_broadcast_server.py, lib/cylc/rundb.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/database/00-simple/schema.out, tests/restart/19-event-retry.t, tests/restart/19-event-retry/bin/my-handler, tests/restart/19-event-retry/suite.rc, tests/shutdown/07-task-fail.t, tests/shutdown/09-now2.t
Store task event handler try states in DB.
Load task event handler try states from DB on restart.
Close #1282. @hjoliver @arjclark please review and/or reassign.
=> Contine task event handler on restart

doc/suiterc.tex
Closes #2068 
Update TeX documentation to reflect correct level of suite-level authentication section.
=> Update documentation for authentication

lib/cylc/config.py, tests/cylc-get-config/04-dummy-mode-output.t, tests/cylc-get-config/04-dummy-mode-output/suite.rc
Close #2064.
@arjclark @oliver-sanders please review.
=> Fix outputs + dummy mode script override issue

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/updater.py
Should fix #2035.
@hjoliver please let me know if this fixes the issue or not.
=> gui: fix status widget flashing with stopped suite

lib/cylc/gui/updater.py
=> gcylc: fix blank suite TypeError

bin/cylc-show, lib/cylc/graph_parser.py, tests/cylc-show/00-simple.t, tests/cylc-show/01-clock-triggered.t, tests/cylc-show/02-clock-triggered-alt-tz.t, tests/cylc-show/03-clock-triggered-non-utc-mode.t, tests/cylc-show/04-multi.t, tests/graph-equivalence/03-multiline_and1.t, tests/graph-equivalence/04-multiline_and2.t, tests/triggering/16-fam-expansion.t, tests/triggering/fam-expansion/suite.rc
Closes #2080 
* Adds a test in for correct behaviour
* Also corrects an ordering inconsistency between `cylc show` and `cylc gui => view prereq's`
=> graph parser: Fix expansion of (FAM:finish-all & FAM:fail-anyi) type triggers.

lib/cylc/task_pool.py
=> Fix cold-start causing dependents to be immortals

bin/cylc, bin/cylc-get-suite-contact, tests/cylc-get-suite-contact/00-basic.t, tests/cylc-get-suite-contact/test_header
Print content of suite contact file.
Close #1967.
=> cylc get-suite-contact: new command

lib/cylc/cfgspec/suite.py
See https://github.com/cylc/cylc/pull/2095#discussion_r95122511.
@hjoliver Please review.
=> Removed duplicate deprecation

lib/cylc/cfgspec/suite.py, lib/parsec/upgrade.py
Backport of #2095, fixes #2094 for 6.11.x, @matthewrmshin / @hjoliver please review.
=> 6.11.x upgrade mixed syntax

bin/cylc-cat-state, bin/cylc-ls-checkpoints, lib/cylc/rundb.py, tests/restart/19-checkpoint.t, tests/restart/19-checkpoint/suite.rc
Should be sufficient to close #2093.
=> t: embed ls-checkpoints tests

lib/cylc/graph_parser.py, tests/triggering/16-fam-expansion.t, tests/triggering/fam-expansion/suite.rc
Backports the graph parsing part of #2087 into cylc 6.11.x
=> Backport parsing fix from 2087 to cylc 6.11.x branch.

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/dbchooser.py
Should be sufficient to close #341. Implemented using option 1 in description of #341.
=> cylc gui: open another suite in new window

bin/cylc, bin/cylc-checkpoint, doc/cug.tex, lib/cylc/network/https/suite_command_server.py, lib/cylc/scheduler.py, lib/cylc/scheduler_cli.py, tests/cylc-take-checkpoints/00-basic.t, tests/cylc-take-checkpoints/00-basic/reference.log, tests/cylc-take-checkpoints/00-basic/suite.rc, tests/cylc-take-checkpoints/test_header
New command to tell a suite to checkpoint itself.
Close #1735.
=> cylc checkpoint: new command

lib/cylc/task_proxy.py
=> 6.11.x: Fix remote kill after reload

bin/cylc-diff, tests/cylc-diff/00-basic.t, tests/cylc-diff/test_header
Likely a #2067 breakage. Sorry.
=> Fix cylc diff + add basic test

doc/siterc.tex
=> CUG: fix description of remote shell/copy template

bin/cylc-diff, lib/cylc/cfgspec/suite.py, lib/cylc/config.py, lib/cylc/scheduler.py, tests/cylc-diff/01-same.t, tests/cylc-diff/02-identical.t
Also fix docs on identical suites.
Fix #2130.
=> cylc diff: fix diff 2 suites with same suite.rc

lib/cylc/job_host.py
Ensure that the error message is only printed when there is a genuine error.
=> Fix job host contact file clean up logic

lib/cylc/gui/app_gcylc.py
Adds task state *Select All* and *Select None* buttons; a *Reset* button for the filter text entry; and clearer tooltip info.
=> gcylc - improved filtering dialog

doc/cug.tex, doc/siterc.tex
Should be sufficient to close #2137.
=> doc: remove reference to port file

doc/cug.tex
=> Doc: add PBS -l setting quirk.

lib/cylc/__init__.py, lib/cylc/network/https/suite_info_server.py, lib/cylc/version.py, tests/api-suite-info/00-get-graph-raw-1.t, tests/api-suite-info/00-get-graph-raw-1/bin/ctb-get-graph-raw, tests/api-suite-info/00-get-graph-raw-1/reference.log, tests/api-suite-info/00-get-graph-raw-1/suite.rc, tests/api-suite-info/test_header
=> gui: fix graph view family ungroup

doc/cug.tex
(Doc does not build on my desktop. This fixes the issue.)
=> Doc: Remove extra close brace

tests/cylc-get-site-config/02-jinja2.t
=> Test: jinja2 in global.rc

doc/cug.tex
=> Document how the graph determines task creation.

lib/cylc/gui/gscan.py, lib/cylc/network/https/port_scan.py
Display "(updating)" suffix in title.
Catch traceback for still initialising suites.
=> gscan: improve diag while updating

lib/cylc/network/https/port_scan.py
Should be sufficient to fix #2039.
=> port scan: handle OSError on forking new process

lib/cylc/graph_parser.py, tests/validate/62-null-task-name.t
Fix #2200. (Picked option 2, but happy to change this to option 1.)
=> Fail graph with null string nodes

doc/cug-pdf.tex, doc/cug.tex
@dpmatthews - user guide Installation section updated in response to your email.  I've removed a bunch of obsolete stuff and tidied what remains.  See what you think...
=> Updated CUG installation section.

tests/jobscript/16-midfail.t, tests/jobscript/16-midfail/reference.log, tests/jobscript/16-midfail/suite.rc, tests/jobscript/17-envfail.t, tests/jobscript/17-envfail/reference.log, tests/jobscript/17-envfail/suite.rc
Follow-up to #2218  - see https://github.com/cylc/cylc/pull/2218#issuecomment-289899324
=> Two new tests added.

bin/cylc-profile-battery, dev/profile-experiments/example, dev/suites/chains/suite.rc, dev/suites/diamond/suite.rc, lib/cylc/profiling/profile.py
Adds the ability to set global.rc items for profile-battery experiments.
=> profile battery: add globalrc functionality

lib/cylc/param_expand.py
Improves an otherwise slightly cryptic error message.
=> Added warning for missing parameter in template.

doc/src/cylc-user-guide/cug.tex
User Guide documentation of server logs.
=> Added server log documentation.

lib/cylc/gui/app_gcylc.py
Follow-up final comment on #2220
=> Added dummy-local mode to GUI start dialog.

bin/cylc-monitor, lib/cylc/gui/gscan.py, lib/cylc/gui/updater.py, lib/cylc/network/https/port_scan.py, lib/cylc/network/https/suite_identifier_server.py, lib/cylc/network/https/suite_state_client.py, lib/cylc/network/https/suite_state_server.py, lib/cylc/network/suite_state_client.py
GUI can check whether summary update time is defined or not to determine
if the suite is initialising or not.
Close #2238.
=> Remove SuiteStillInitialisingError

lib/cylc/suite_srv_files_mgr.py, tests/authentication/00-identity.t, tests/authentication/01-description.t, tests/authentication/02-state-totals.t, tests/authentication/03-full-read.t, tests/authentication/04-shutdown.t, tests/authentication/05-full-control.t, tests/authentication/06-suite-override.t, tests/authentication/07-sha-hash.t
Allow curl, browser, etc to connect to the suite.
=> SSL cert: add serial number

bin/cylc-graph, tests/graphing/09-ref-graph.t, tests/graphing/09-ref-graph/graph.ref, tests/graphing/09-ref-graph/suite.rc
Fix a minor bug (which won't have affected normal users).
=> Fix.cylc ref graph

lib/cylc/gui/scanutil.py
Sorry, `cylc gpanel` broken by #2257.
=> Fix gpanel broken by #2257

lib/cylc/config.py, tests/suite-state/00-polling.t, tests/suite-state/01-polling.t
Close #2268 
Code fixed, just need to look at why the tests didn't catch this.
=> Fix auto suite-state polling tasks.

lib/cylc/graph_parser.py, tests/validate/62-null-task-name.t
Closes #2267 
Adds more generic logic for detecting null tasks.
=> Added generic checking for null tasks.

tests/cylc-get-site-config/03-host-bool-override.t
=> Test for cylc/cylc#2282

bin/cylc-monitor, bin/cylc-scan, lib/cylc/dump.py, lib/cylc/gui/updater.py, lib/cylc/gui/updater_graph.py, lib/cylc/gui/updater_tree.py, lib/cylc/network/https/suite_state_client.py, lib/cylc/network/https/suite_state_server.py, lib/cylc/network/suite_state_client.py
What it says.  Plus some associated minor refactoring.
@matthewrmshin - please review and/or assign.
=> Remove some obsolete back compat code and help text.

bin/cylc-cycle-point, lib/cylc/batch_sys_handlers/at.py, lib/cylc/batch_sys_handlers/loadleveler.py, lib/cylc/conditional_simplifier.py, lib/cylc/config.py, lib/cylc/graph_parser.py, lib/cylc/graphing.py, lib/cylc/gui/updater_tree.py, lib/cylc/network/https/suite_broadcast_server.py, lib/cylc/profiling/profile.py, lib/cylc/scheduler.py, lib/cylc/task_pool.py, lib/isodatetime/data.py, lib/parsec/util.py
~Graph parser: improve results data structure. Unify variable names where possible.~
Conditional simplifier:
* faster `listify` method, convert expression directly into nested list.
* ~new `deep_replace` method~
`get_graph_raw`:
* More caching.
* ~Reduce number of `(name, point)` <=> `name.point` conversions, but it means there is an API change.~
graphing:
* Don't style node and edge on validation.
Initial tests suggest a good reduction of memory usage (from 920MB to 750MB) and a small reduction of user time and elapsed time (about 6%) to validate the nasty suite in my work environment.
=> Even more validate opt

doc/src/cylc-user-guide/cug.tex
Minor CUG section update.  Matt please review or re-assign.
=> Corrected CUG section on implicit cycling.

lib/cylc/scheduler.py
Refactoring main loop (`run()` in `scheduler.py`) into smaller methods for readability/maintainability.
=> Main run loop refactor

lib/cylc/suite_events.py, lib/cylc/task_events_mgr.py, tests/events/36-task-event-bad-custom-template.t, tests/events/36-task-event-bad-custom-template/reference.log, tests/events/36-task-event-bad-custom-template/suite.rc, tests/events/37-suite-event-bad-custom-template.t, tests/events/37-suite-event-bad-custom-template/reference.log, tests/events/37-suite-event-bad-custom-template/suite.rc
Print an ERROR entry to log.
For suite event + abort on ... handler fails, abort gracefully.
Address main problem of #2350.
=> Custom event handlers: handle bad template

bin/cylc-graph, lib/cylc/config.py, lib/cylc/cylc_xdot.py, lib/cylc/graphing.py, tests/graphing/09-close-fam.t, tests/graphing/09-close-fam/graph.plain.ref, tests/graphing/09-close-fam/graph.plain.ungrouped.ref, tests/graphing/09-close-fam/suite.rc
Also improve pylint score.
Should now fix #2351 as well.
=> cylc graph: fix no option no arg error message

lib/cylc/batch_sys_handlers/at.py, lib/cylc/batch_sys_handlers/background.py, lib/cylc/batch_sys_handlers/loadleveler.py, lib/cylc/batch_sys_handlers/lsf.py, lib/cylc/batch_sys_handlers/moab.py, lib/cylc/batch_sys_handlers/pbs.py, lib/cylc/batch_sys_handlers/sge.py, lib/cylc/batch_sys_handlers/slurm.py, lib/cylc/batch_sys_manager.py
=> Remove POLL_CMD_TMPL

lib/cylc/config.py, tests/graphing/11-nested-fam.t, tests/graphing/11-nested-fam/graph.plain.ref, tests/graphing/11-nested-fam/graph.plain.ungrouped.ref, tests/graphing/11-nested-fam/suite.rc
=> cylc graph: fix nested fam issue

doc/src/cylc-user-guide/cug.tex
Close #2341 
(This went from correcting the remote control documentation, to a mid-size rewrite of several parts of the "Running Suites" section - and a few other bits that connect to it).
@matthewrmshin - please review and/or assign.
=> Tidied CUG "Running Suites" section.

lib/cylc/task_job_mgr.py
=> Fix problem with remote job suite

.travis.yml
Related to recent Travis CI change and #2355, similar to metomi/rose#2100.
=> Travis CI install: add pyopenssl

lib/isodatetime/__init__.py, lib/isodatetime/data.py, lib/isodatetime/parsers.py
See https://github.com/metomi/isodatetime/releases/tag/2017.08.0
=> Upgrade to isodatetime-2017.08.0

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex
=> doc: event handler substitution quote behaviour

lib/cylc/gui/app_gcylc.py, lib/cylc/gui/cat_state.py, lib/cylc/suite_host.py, tests/suite-host-self-id/00-address.t, tests/suite-host-self-id/01-unit.t
And:
* Improve `--host=HOST` logic.
* Fix attempt to write None in debug mode.
Should fix #2377.
UPDATE: close #2399
=> gui: improve start suite --owner=USER logic

bin/cylc-profile-battery
Closes #2402 
Create missing results file as required.
=> Handle missing results file.

lib/cylc/config.py, tests/events/38-task-event-handler-custom/suite.rc, tests/validate/65-bad-task-event-handler-tmpl.t
=> validate: fail on bad task event handler templates

doc/src/cylc-user-guide/suiterc.tex
=> Minor CUG doc fix [skip ci].

lib/cylc/gui/app_gcylc.py
=> Fix gcylc filter dialog bug (introduced since last release)

doc/src/cylc-user-guide/suiterc.tex
Trivial fix to the mail events examples.
=> Fix mail events examples

lib/cylc/cylc_xdot.py
Error encountered when refreshing the view in the cylc graph gui is printed out to the terminal where it may be missed. As the previous graph is left behind if the user makes an invalid change to the suite.rc file they may be left under the impression that nothing has changed.
This PR pops up a dialogue box and clears the previous graph.
=> graph: dialog on reload error

doc/src/cylc-user-guide/cug.tex
Some minor additions to the User Guide, to record things I've had to explain to users recently by email.
=> CUG updates

doc/src/cylc-user-guide/cug.tex
A section re-order and a little refinement of the recent rewrite of remote control documentation.
=> CUG: refine remote control info.

admin/make-tarball
=> Fix #2482 make tarball

lib/parsec/jinja2support.py, tests/jinja2/10-builtin-functions.t, tests/jinja2/10-builtin-functions/suite.rc
It would appear that since the latest Jinja2 upgrade functions now print their return value in all cases.
See #2189 
Added a test for the success case.
@matthewrmshin, @hjoliver - someone please review.
=> Fix Jinja2 assert function

lib/cylc/task_message.py
Format stderr output for easier debugging in the event of communication error.
=> Add timestamps to cylc message.

lib/cylc/gui/updater_graph.py, lib/cylc/gui/view_graph.py
=> graph: re-instate the right click menu for ghost nodes

bin/cylc-cat-log, bin/cylc-cat-state, bin/cylc-check-versions, bin/cylc-cycle-point, bin/cylc-diff, bin/cylc-documentation, bin/cylc-edit, bin/cylc-ext-trigger, bin/cylc-get-gui-config, bin/cylc-get-site-config, bin/cylc-get-suite-config, bin/cylc-get-suite-version, bin/cylc-gpanel, bin/cylc-gscan, bin/cylc-gui, bin/cylc-help, bin/cylc-jobs-kill, bin/cylc-jobs-poll, bin/cylc-jobs-submit, bin/cylc-kill, bin/cylc-monitor, bin/cylc-profile-battery, bin/cylc-register, bin/cylc-report-timings, bin/cylc-scan, bin/cylc-suite-state, bin/cylc-trigger, bin/cylc-upgrade-run-dir, bin/cylc-version, lib/cylc/gui/gpanel.py
Even more changes to improve pylint happiness.
=> pylint bin: unused imports and variables

lib/cylc/gui/gscan.py
=> gscan: don't display title for every cycle point

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex
=> Doc kill-to-hold with retries

doc/src/cylc-user-guide/cug.tex
The best way is to start from scratch, or at least a commented out file.
=> Fix doc advice for generating initial global.rc

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/suiterc.tex
=> Doc task remote

lib/isodatetime/__init__.py, lib/isodatetime/data.py, lib/isodatetime/dumpers.py, lib/isodatetime/parser_spec.py, lib/isodatetime/parsers.py, lib/isodatetime/tests.py, lib/isodatetime/timezone.py, lib/isodatetime/util.py
Upgrade to isodatetime-2018.02.0.
=> isodatetime-2018.02.0

lib/cylc/gui/tailer.py
To repeat, run a suite such as this one:
```cfg
[scheduling]
graph = t1
[runtime]
[[t1]]
script = sleep 120
[[[remote]]]
host = myremotehost
```
Launch `gcylc`. Right click on the task when it is running. Attempt to view job standard output will result in this traceback:
```
Exception in thread Thread-3:
File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
self.run()
File "/opt/cylc-7.6.0/lib/cylc/gui/tailer.py", line 100, in run
preexec_fn=os.setpgrp)
File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
errread, errwrite)
File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
raise child_exception
TypeError: execv() arg 2 must contain only strings
```
Reported by @steoxley
=> gcylc: fix tailer of remote job log

doc/src/suite-design-guide/style-guide.tex, lib/parsec/util.py, lib/parsec/validate.py
For prettier job scripts, etc.
=> Use textwrap.dedent on multi-line config values

lib/cylc/gui/scanutil.py
On port range scan with no owner filter, default should continue to show
suites of current user only.
Fix #2573.
=> gscan: fix scan host port range owner behaviour

README.md, doc/src/suite-design-guide/general-principles.tex
=> Add set -o pipefail to design guide basic functionality section

doc/src/cylc-user-guide/cug.tex
Small doc update for https://github.com/cylc/cylc/issues/2534#issuecomment-367476066
=> Amend suite state polling task documentation.

lib/cylc/gui/tailer.py
Support for `select.poll` is not universal across all python setups on all UNIX platforms.
I'm not too familiar with the `poll` and `select` commands, hopefully this is a sufficient substitute.
@matthewrmshin assign a second reviewer once you are happy.
=> Swap select.poll for select.select.

bin/cylc-check-software
Blueprint with the aim to close #2203. It's a work in progress, so I will be self-reviewing and updating after Christmas/New Year leave but ongoing feedback would be helpful if anyone has time.
I was 'inspired' (read: copied under the blessing of open-source with modest adaptations) the shell-command- and version- checking functions and other code snippets from the 'rose-check-software-docs' program file as written by @oliver-sanders so much credit to Oliver. To see what I have and have not written myself for attribution purposes simply compare this code to that file.
I have based external software needs on the' cylc user guide' but if anyone knows of more specific requirements, particularly minimum versions, then please let me know or point me to somewhere where this may be specified. …
=> check-software: improve with redesign in Python

doc/src/cylc-user-guide/cug.tex, lib/cylc/job_file.py, lib/cylc/task_job_mgr.py, tests/cylc-trigger/03-edit-run.t, tests/jobscript/00-torture/foo.ref-jobfile, tests/jobscript/18-env-task-dependencies.t, tests/jobscript/18-env-task-dependencies/reference.log, tests/jobscript/18-env-task-dependencies/suite.rc
=> add dependencies variable to job script

.gitignore, CHANGES.md, bin/cylc-scan, bin/cylc-view, doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/scripts/make-html.sh, doc/src/cylc-user-guide/scripts/make-pdf.sh, lib/cylc/job.sh
* moved the last file out of `conf/` and into `etc/` - `job-init-env.sh`
=> More prep for 7.7.0

bin/cylc-scan
Hopefully, this should now be fully consistent with gscan.
=> scan HOST: default to suites of current user

CHANGES.md
(taken from aborted #2672) - change log only, and already seen - so I will just merge this.
=> Update change log (more) for 7.7.0

lib/cylc/task_pool.py
First release casualty... :disappointed: Sorry.
It may accidentally load the data structure as an event timer, which can cause a strange error.
=> Fix restart task action timers load old poll timer

doc/src/cylc-user-guide/cug.tex
=> Trivial CUG doc fix.

CONTRIBUTING.md
A bit more clarity on the contributor guidelines.  Is the wording OK?
=> Update contributor guidelines.

lib/parsec/empysupport.py, tests/job-submission/17-remote-localtime.t
Trivial change. 1 review enough.
=> Update copyright notices for missed files

tests/validate/04-builtin-suites.t
=> test built-in suites: allow empy suite to skip

lib/cylc/cfgspec/gscan.py, lib/cylc/gui/gscan.py, lib/cylc/scheduler.py, lib/cylc/suite_status.py, tests/authentication/00-identity.t, tests/authentication/01-description.t, tests/authentication/02-state-totals.t, tests/authentication/03-full-read.t, tests/authentication/04-shutdown.t, tests/authentication/05-full-control.t, tests/authentication/06-suite-override.t, tests/authentication/07-sha-hash.t
Allow suites to report its cylc version to (g)scan.
=> gscan: display cylc versions of suites

lib/isodatetime/__init__.py, lib/isodatetime/data.py, lib/isodatetime/run_tests, lib/isodatetime/tests.py
Update to isodatetime-2018.09.0.
=> Update to isodatetime-2018.09.0

lib/cylc/task_pool.py, tests/restart/33-simulation.t
=> Fix restart sim mode suite with running tasks

doc/src/cylc-user-guide/cug.tex, doc/src/cylc-user-guide/siterc.tex
Fixed two LaTeX errors (one preventing the build); removed an unnecessary section that replicated some global.rc information and had got out of sync with it; and some minor rewording in one section.
=> Minor CUG fixes and mods.

doc/src/cylc-user-guide/suiterc.tex, lib/cylc/config.py, lib/cylc/task_events_mgr.py, tests/events/39-task-event-template-all/bin/checkargs, tests/events/39-task-event-template-all/suite.rc
For completeness (submit number is already available).
~~To Do:~~
- ~~add to tests~~
- ~~add to CUG~~
Done -ready for review.
=> Make "try num" available to task event handlers.

lib/cylc/conditional_simplifier.py
Broken by: https://github.com/cylc/cylc/commit/63b98cf267e6c34918a2f39a194fb8edc95ee8d7
=> fix python 2.6 breakage

tests/authentication/09-remote-suite-same-name.t
The register command was failing and printing its output to screen.
=> Fix placebo remote command in test

doc/src/cylc-user-guide/siterc.tex, lib/cylc/job.sh
Trivial companion to https://github.com/metomi/rose/pull/2252
=> suite run dir bin path, and cylc run dir doc tweak.

lib/cylc/remote.py
The SSH command ran on current host, not on remote host, so the previous message was not strictly correct.
Simplify format to use a shell prompt like syntax.
Use cylc logger if it has any handlers.
=> remote command debug log: fix format

lib/cylc/batch_sys_manager.py
=> Corrected a comment in the new variant PBS handler.

doc/src/conf.py
=> Use higher contrast link colours.

lib/cylc/task_job_mgr.py
This is really just a syntax error.
=> Fix bad unary `+` syntax on a str

lib/cylc/task_events_mgr.py
=> Backport #2981

CONTRIBUTING.md, doc/src/suite-config.rst, lib/cylc/config.py, lib/cylc/scheduler.py
Suite context availability - replica of pull [2963](https://github.com/cylc/cylc/pull/2963) for 7.8.x
=> Make suite context available before config parsing [7.8.x]

tests/jobscript/11-shell-ksh.t
Similar change already applied for master at 5ecd766906da01f27b1aae48d2803c8905c58c37 (#2966.)
=> fix ksh test [7.8.x]

lib/cylc/task_events_mgr.py, lib/cylc/task_job_mgr.py, lib/cylc/task_pool.py, lib/cylc/task_proxy.py, tests/reload/21-submit-fail.t, tests/reload/21-submit-fail/bin/mycylcrun, tests/reload/21-submit-fail/reference.log, tests/reload/21-submit-fail/suite.rc
=> Fix submit failed after reload

.travis/install.sh, bin/cylc-check-software, tests/validate/04-builtin-suites.t
=> empy: re-enable EmPy templating

lib/cylc/task_state_prop.py, lib/cylc/tests/test_task_state_prop.py
=> Remove GTK labels from task states

lib/cylc/xtriggers/xrandom.py
=> Add check for zero to xrandom (7.8.x backport)

tests/cylc-show/06-prereqs-outputs.t, tests/cylc-show/prereqs-outputs/suite.rc
Flaky test fix back port, roughly based on 75e376ac43.
=> Fix tests/cylc-show/06: back port to [7.8.x]

lib/cylc/subprocpool.py, lib/cylc/task_remote_mgr.py, lib/cylc/tests/test_subprocpool.py
=> Subprocpool: use SpooledTemporaryFile instead of TemporaryFile [7.8.x]

CONTRIBUTING.md
=> contribution addition

CONTRIBUTING.md
=> contrib addition 7.8.x

.mailmap
For git log/shortlog happiness.
Back port of #3058.
=> Add entries to .mailmap for 7.8.x

lib/cylc/cfgspec/globalcfg.py
=> Remove globalcfg add_bin_dir and use_ssh, codacy issue about unused code

.travis.yml
=> 7.8.x: Travis CI build with Python 2.7

tests/cyclers/00-daily.t
=> Fix work loc assumption in a test. (master version)

CHANGES.md, INSTALL.md, README.md, bin/cylc-test-battery, doc/src/suite-design-guide/sdg-introduction.rst, lib/cylc/cfgspec/globalcfg.py
=> Fix links in README and other files

setup.cfg
Cylc is now Cylc-Flow.
Description can only be a one line summary.
=> setup.cfg: renamed cylc-flow + reduced summary

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
Adds templates for:
- Pull Request, with requirements check list
- Issues:
- Bug Report
- Feature Request
@matthewrmshin - please review or reassign.
If approved I'll post the same as a PR to master.
Based on templates in one of @kinow's repositories (which you can also play with to see how they work): https://github.com/kinow/testlink-java-api/tree/master/.github  ... thanks @kinow 👍
=> Add GitHub PR and Issue templates.

cylc/flow/exceptions.py, cylc/flow/task_state.py
Just a few typos. One review will do?
=> Fix a few typos

cylc/flow/prerequisite.py
I think this is already [covered by tests](https://codecov.io/gh/cylc/cylc-flow/src/master/cylc/flow/prerequisite.py#L125), and as it is not changing the previous behaviour it should be OK? No need to include in the `CHANGE.md` either IMO, but happy to add a short description if necessary.
=> Simplify if expression in prerequisite.py

CHANGES.md
These changes close #2700
Forgot to add a changelog for #3003. Also closing #2700 with this.
=> Add changelog entry for #3003 (fix inheritance PR)

CHANGES.md, lib/cylc/config.py, tests/cli/02-now.t
=> [7.8.x] fix `cylc run --icp=now SUITE` restart

CONTRIBUTING.md
I can't believe I haven't done this yet!
[My PR History](https://github.com/cylc/cylc-flow/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awxtim+)
=> Add me to CONTRIBUTING.md

cylc/flow/network/schema.py
=> Compare with not instead of using empty list

cylc/flow/network/resolvers.py
These changes close #3216
Test with bash script:
```
#!/bin/bash
read -r -d '' flatTree <<_args_
{
"request_string": "
query flatTree(\$wIds: [ID], \$tIds: [ID], \$nIds: [ID], \$nStates: [String], \$minDepth: Int, \$maxDepth: Int) {
workflows(ids: \$wIds) {
id
name
status
stateTotals {
runahead
waiting
held
queued
expired
ready
submitFailed
submitRetrying
submitted
retrying
running
failed
succeeded
}
treeDepth
tasks(ids: \$tIds, mindepth: \$minDepth, maxdepth: \$maxDepth){
name
meta {
title
description
URL
userDefined
}
proxies(ids: \$nIds, states: \$nStates){
cyclePoint
state
}
}
}
}",
"variables": {
"wIds": ["*/${1}"],
"nIds": ["20*/*"],
"tIds": ["*"],
"nStates": ["succeeded", "waiting", "held", "running"],
"minDepth": 0,
"maxDepth": 4
}
}
_args_
echo "${!2}"
echo ${!2} | time cylc …
```
=> tasks query bug fix

bin/cylc-client, bin/cylc-ls-checkpoints, bin/cylc-report-timings
=> Remove unused imports

bin/cylc-check-versions
=> Use correct variable to avoid traceback

README.md
Sorry, forgot to remove the link in the `README.md` file.
=> Remove one more mention/link of ACKNOWLEDGEMENT.md

cylc/flow/tests/network/test_scan.py
=> Add unit tests for cylc.flow.network.scan

.github/PULL_REQUEST_TEMPLATE.md
- fix bad URL to cylc-doc
- add two new lines:
- tests not needed
- documentation not needed
- remove obsolete instruction to delete COMMENT lines
- (made some existing lines more concise)
=> Pr template update

cylc/flow/batch_sys_handlers/background.py, cylc/flow/batch_sys_manager.py, cylc/flow/cylc_subproc.py, cylc/flow/daemonize.py, cylc/flow/job_file.py, cylc/flow/profiler.py, cylc/flow/remote.py, cylc/flow/run_get_stdout.py, cylc/flow/scheduler.py, cylc/flow/subprocpool.py, cylc/flow/suite_srv_files_mgr.py, cylc/flow/task_remote_mgr.py
An example PR for #3264. But having changes in the scheduler, the pool of processes, and other areas that are still a bit dark to me, I think this will be more a reference for @hjoliver, @matthewrmshin or anybody with more experience with Cylc internals and that may be able to work on that issue :+1: 
=> Close resources open for subprocess.Popen and open

tests/restart/25-hold-suite.t
Fix a possible cause of flakiness in a test. Master companion of #3291 - see comments there.
=> Fix use of poll in a test (master)

tests/restart/25-hold-suite.t
Fix a possible cause of test flakiness.
=> Fix use of poll in a test.

CHANGES.md, lib/cylc/task_pool.py, tests/reload/21-remove-task-cycling.t
=> Reload fix 7.8.x

CHANGES.md, cylc/flow/task_pool.py, tests/reload/22-remove-task-cycling.t
These changes close #3306
Master companion of #3307
=> Reload fix c8

cylc/flow/network/schema.py, cylc/flow/ws_data_mgr.py
=> Fix a few docstrings

cylc/flow/rundb.py
Very little risk, but just to avoid accidentally using the incorrect `name` or `cycle` variable. Also updates docstrings.
=> Use different variable names in nested loops

tests/reload/21-remove-task-cycling.t
7.8.x counterpart of #3319
One review should do.
=> Fix flaky test 7.8.x

doc/src/appendices/site-user-config-ref.rst, lib/cylc/cfgspec/globalcfg.py
=> Remove broken run dir housekeeping config

bin/cylc
These changes close #3341
One review will do.  I've checked the remaining categories are still valid (`cylc CATEGORY --help` lists all the commands in the category).
=> Removed obsolete command categories.

cylc/flow/tests/util.py
=> Fix unit tests running with Python 3.8.0b4

bin/cylc-cat-log
=> Remove duplicate and unnecessary tail_tmpl variable in cylc-cat-log

cylc/flow/network/resolvers.py, cylc/flow/network/schema.py
These changes close https://github.com/cylc/cylc-ui/issues/238
Allows camel or snake case sort `key`, adds default (`False`) to `reverse`.
=> Allow camel or snake sort key

cylc/flow/__init__.py
=> fix-version-no-in-__init__

CHANGES.md
These changes partially address #xxxx
These changes close #xxxx
=> Update 8.0a1 release date in CHANGES.md

cylc/flow/network/resolvers.py, cylc/flow/network/schema.py, cylc/flow/terminal.py, cylc/flow/tests/test_zmq.py, cylc/flow/unicode_rules.py, etc/bin/defn-order-test.py, etc/bin/live-graph-movie.sh, etc/bin/make-tarball, etc/bin/start-group-demo.sh, etc/bin/stop-group-demo.sh, etc/bin/updatecopyright.sh
Following the discussion on #3041 this pull request is a followup of #3393.
These changes partially address ##3041
=> Fix license and copyright headers

CONTRIBUTING.md, cylc/flow/network/authentication.py, cylc/flow/network/schema.py
Hi,
These changes close #3396 
=> Fixed some typos in cylc.flow.network module

.gitignore, cylc/flow/task_trigger.py, cylc/flow/tests/test_task_trigger.py
=> task trigger testing

setup.py
Added pandas to fix cylc-report-timings issue.
These changes close #3364
=> Add pandas dependency

CONTRIBUTING.md, cylc/flow/network/scan.py, tests/cylc-scan/02-sigstop.t
=> add log to scan error or timeout exceptions

bin/cylc, bin/cylc-jobscript
See https://github.com/cylc/cylc-flow/issues/2957#issuecomment-535222497
These changes partially address #2957 
=> cli: remove dependence on less

cylc/flow/jinja/filters/duration_as.py
=> Cover missing branch in duration_as (doctest)

cylc/flow/suite_db_mgr.py
=> Remove unused final_stop_point variable

doc/src/suite-config.rst
Backport of https://github.com/cylc/cylc-doc/pull/103 for 7.8.5.
=> Fix example in parameter expansion

cylc/flow/platform_lookup.py, cylc/flow/rundb.py, cylc/flow/tests/test_platform_lookup.py, cylc/flow/tests/test_rundb.py, cylc/flow/tests/util.py
Part of the work towards creating job platforms.
The database stores the host and batch_system, we would need to upgrade This could be done towards the end, you might need to put off upgrading the DB but instead upgrade the information coming out of the database.
=> Database upgrader

cylc/flow/rundb.py
Working from home, and found a post-it that I wrote while working on #2800 . Trivial change, one review should do?
=> Use list.clear() as we are using Py3.3+

cylc/flow/cfgspec/suite.py, cylc/flow/platform_lookup.py, cylc/flow/tests/test_config_upgrader.py, cylc/flow/tests/test_platform_lookup.py
Function to upgrade the suite configuration objects to use platform rather than various settings in `[runtime][task]`.
=> [Failing Codecov only] Platforms: Config Upgrader

CHANGES.md, lib/cylc/gui/gscan.py
These changes close #3281 
Original PR against 7.9.x is here: https://github.com/cylc/cylc-flow/pull/3513
=> [7.8.x] Fix expanded ids for GScan

cylc/flow/parsec/config.py, cylc/flow/tests/parsec/test_config.py
These changes close #3383 
I guess one review should do assuming Travis is happy with it.
=> Remove ParsecConfig checkspec unused function

cylc/flow/data_store_mgr.py, cylc/flow/job_pool.py, cylc/flow/task_events_mgr.py, cylc/flow/task_job_mgr.py, cylc/flow/tests/test_job_pool.py
=> Remove job pool scaffolding

CHANGES.md, lib/cylc/gui/view_tree.py
=> [7.8.x] Fix sorting of tasks

CHANGES.md, lib/cylc/gui/view_tree.py
These changes close #3299 
Sibling PR of https://github.com/cylc/cylc-flow/pull/3526. Cherry picked all the commits of that PR with the exception of the last one with the changelog. Then created this PR, and finally pushed one more commit with the new changelog for 7.9.x.
=> [7.9.x] Fix sorting of tasks

CONTRIBUTING.md, lib/cylc/cfgspec/globalcfg.py, lib/parsec/upgrade.py, tests/deprecations/01-overwrite.t, tests/deprecations/01-overwrite/suite.rc, tests/hold-release/hold-after-point/suite.rc
These changes partially address #3494 
=> Fix 3494 deprecation upgrade bug

CONTRIBUTING.md, lib/cylc/cfgspec/globalcfg.py, lib/parsec/upgrade.py, tests/deprecations/01-overwrite.t, tests/deprecations/01-overwrite/suite.rc, tests/hold-release/hold-after-point/suite.rc
Copy of merged PR #3524 (from 7.8.x branch)
=> Fix #3494 deprecation upgrade bug on 7.9.x

CONTRIBUTING.md, lib/cylc/gui/gscan.py, lib/cylc/network/port_scan.py
These changes partially address #3516
These changes close #3518
=> Fs scan forwards compatibility

cylc/flow/data_store_mgr.py
=> absolute trigger data-store prune fix

cylc/flow/config.py
I think it offers some performance improvement, though probably not perceptible.
=> Compile regex used in a loop

cylc/flow/main_loop/__init__.py, setup.cfg
=> Load main loop plug-ins automatically

lib/cylc/task_job_mgr.py, lib/cylc/task_remote_mgr.py, tests/events/49-task-event-host-select-fail.t
These changes  partially address #3472 
=> Fix 3472 host selection command failure not handled properly

cylc/flow/daemonize.py
Utterly trivial suggestion for @oliver-sanders
=> Add TUI to the ways you can look at a suite

cylc/flow/scripts/cylc_cat_log.py
Close #3586 
@kinow - given @oliver-sanders response on the issue, one review will do here.
=> Fix cat-log python invocation.

CHANGES.md
Minor change log update:
- add entry for recently-merged PR
- move several recent entries to the 8.0a2 section, since we haven't made the release yet.
=> Update change log.

.travis.yml, CHANGES.md, lib/cylc/suite_db_mgr.py, tests/lib/bash/test_header, tests/shutdown/14-no-dir-check.t
7.8.x companion of #3596 
These changes partially address #xxxx
These changes close #xxxx
=> Fix task_action_timers table houskeeeping 7.8.x

cylc/flow/network/subscriber.py
(One reviewer should do)
Sibling PR to https://github.com/cylc/cylc-uiserver/pull/135
(This one needs to go in first)
Useful as non-blocking receive on subscription won't hang on stoppage.
=> non-blocking subscription receive

cylc/flow/cfgspec/globalcfg.py
Small problem, fixes pycodestyle in global config.
Should help actions style pass.
=> Fix pycodestyle global_config

cylc/flow/cfgspec/suite.py, cylc/flow/hostuserutil.py
=> conf: remove old reference and link to script items

cylc/flow/hostuserutil.py
I managed to sneak the patch I use for Mac OS onto master, apologies.
=> hostuserutil: revert hostname logic

tests/cylc-cat-log/09-cat-running/reference.log, tests/cylc-cat-log/09-cat-running/suite.rc
Test was missing its reference log for some reason.
Simple review, just check it passes!
=> tests: fix tests/cylc-cat-log/09

flakytests/job-submission/18-check-chunking.t
This test would fail if you defined any sections in your `flow-tests.rc` file.
E.G:
```ini
[test battery]
remote host = abc
```
This change should enable this test to pass in that situation.
=> tests: fix tests/job-submission/18

tests/cylc-get-site-config/05-host-bool-override.t
So trivial I don't think that it needs a second review.
=> remove unwanted debug from test

cylc/flow/hostuserutil.py
=> hostuserutil: revert acidental change

cylc/flow/tests/test_job_file.py
Probably one review should do, I think. Here's how I confirmed that was creating the file by looking at the variable just before it was used in the debugger.
To review, probably either reading the code, and/or running `pytest` and confirming the random files are not created should be enough.
=> Use NamedTemporaryFile

cylc/flow/profiler.py, cylc/flow/scheduler.py
Quick change to write out the profiler data file for analysis with standard tooling e.g. snakeviz.
No tests ATM, may include in integration battery later.
=> profiler: dump data file for analysis

CHANGES.md
Fill in the release date (the last PR got merged before I got the chance).
=> prepare 8.0a2 release

pytest.ini
Follow on from #3654 
Clean up the `pytest.ini` file.
=> pytest: remove unnecessarily ignored files

cylc/flow/config.py, cylc/flow/cycling/iso8601.py, cylc/flow/jinja/filters/duration_as.py, cylc/flow/jinja/filters/strftime.py, cylc/flow/parsec/validate.py, cylc/flow/scheduler.py, cylc/flow/scripts/cylc_cycle_point.py, cylc/flow/time_parser.py, setup.py
=> Update to metomi-isodatetime 2.0.2

cylc/flow/cfgspec/suite.py
Fix a broken URL.
https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting
=> cfgspec: fix broken url

setup.py
Slacken some over-strict dependency coupling.
=> setup: change version pinning

setup.cfg
=> Update PYPI classifiers as Cylc Flow supports 3.8 too

cylc/flow/data_store_mgr.py
Issues found by the IDE while reviewing #3707 .
=> Declare exception variable before its use, and add docstring for workflow_id

.codacy.yml, .coveragerc, .gitignore
Remove references to stuff which isn't there any more.
=> tidy up legacy junk

cylc/flow/main_loop/__init__.py, etc/bin/run-functional-tests, tests/flakyfunctional/README.md, tests/functional/README.md, tests/functional/cylc-run/02-format.t, tests/functional/rnd/00-run-funtional-tests.t, tests/integration/README.md, tests/unit/README.md, tests/unit/parsec/test_types.py
Noticed some markdown wasn't rendering headers properly.
=> Replace non-breaking spaces

tests/functional/spawn-on-demand/07-abs-triggers/suite.rc
One of the new SoD tests is flaky, this fixes it.
One review will do.
=> Fix a new functional test.

SECURITY.md
(Follow-up from last meeting). One review will do @oliver-sanders
=> Email swap on security doc.

tests/functional/authentication/00-shared-fs.t
Another remote test which slipped the net.
=> tests/f: fix authentication/00

SECURITY.md
Close #3711 
Small follow-up to #3728
=> Forum URL fix on security doc.

cylc/flow/__init__.py
Related to https://github.com/cylc/cylc-uiserver/pull/145 (can be merged separately)
=> Prepare for the next 8.0a3 release (dev for now)

.github/workflows/test.yml
After one of my PR's testing hung and was going for 1hr+. (Default job timeout is 6 hours)
=> gh-actions: Set time limits for test jobs

cylc/flow/batch_sys_handlers/__init__.py, cylc/flow/batch_sys_handlers/at.py, cylc/flow/batch_sys_handlers/background.py, cylc/flow/batch_sys_handlers/loadleveler.py, cylc/flow/batch_sys_handlers/lsf.py, cylc/flow/batch_sys_handlers/moab.py, cylc/flow/batch_sys_handlers/pbs.py, cylc/flow/batch_sys_handlers/sge.py, cylc/flow/batch_sys_handlers/slurm.py, cylc/flow/cfgspec/suite.py, cylc/flow/jinja/filters/duration_as.py, cylc/flow/jinja/filters/pad.py, cylc/flow/jinja/filters/strftime.py, etc/bin/run-functional-tests, tests/flakyfunctional/cyclers/19-async_integer.t
Sibling PR: https://github.com/cylc/cylc-doc/pull/148
Auto-generate documentation within Cylc Flow for:
* Jinja2 Filters.
* Batch Sys Handlers.
=> auto-document cylc modules

.github/bin/mail, .github/workflows/test.yml, tests/functional/lib/bash/test_header
=> GH Actions: add mail

cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/suite.py, cylc/flow/parsec/OrderedDict.py
Update: I realised the original aim of this PR wasn't practical. Instead I've just tidied the code & comments ever so slightly.
=> Tidy cfgspec/parsec slightly

cylc/flow/async_util.py
Trivial comment line-length hot-fix.  Will merge immediately, just putting up via a PR for visibility.
=> Style fix.

cylc/flow/network/scan.py
Fixes the integration test battery.
=> scan: flow.cylc file compatibility

.github/workflows/test.yml, tests/functional/cyclers/20-multidaily_local.t, tests/functional/cylc-show/03-clock-triggered-non-utc-mode.t
(The two tests that expected timezone format to be e.g. +01 instead of +0100)
These changes close #3794
=> Fix time zone related tests

lib/cylc/gui/view_tree.py
=> Tree view - sort by definition order boolean now honored

cylc/flow/scripts/cylc_scan.py
This is a tiny change with no associated Issue.
Sorry - this spelling error just caught my eye.
=> spelling error fix

cylc/flow/scripts/cylc_scan.py
* Make the submitted colour more distinct from the running colour (can improve this when working on Tui)
* Use a hard-coded grey colour rather than "dim" as "dim" is not always grey.
=> scan: improve colour output

cylc/flow/task_trigger.py, tests/unit/test_task_trigger.py
=> task-trigger: unittest galore

cylc/flow/profiler.py, cylc/flow/scripts/cylc_validate.py
=> validate: fix profiling

cylc/flow/network/scan.py, cylc/flow/parsec/validate.py, cylc/flow/platforms.py, cylc/flow/remote.py, cylc/flow/scheduler.py, cylc/flow/suite_files.py, cylc/flow/task_pool.py, cylc/flow/task_remote_cmd.py, cylc/flow/task_remote_mgr.py, cylc/flow/task_state.py, cylc/flow/time_parser.py, cylc/flow/xtriggers/suite_state.py, cylc/flow/xtriggers/xrandom.py
This is a small change with no associated Issue. Found one strange thing some code that was not in the PR I was reviewing (#3423) so ran a complete code analysis with the IDE, and selected the issues that seemed to be legit (it actually shows heaps more warnings, especially related to typing - for some other day).
=> Fix minor issues found while reviewing task states PR's

cylc/flow/config.py, tests/functional/runahead/01-check-default-simple.t
A tiny style fix and a comment in a functional test.
One review will do!
=> Style and comment

cylc/flow/context_node.py, cylc/flow/host_select.py, cylc/flow/scripts/cylc_extract_resources.py, cylc/flow/scripts/cylc_help.py, cylc/flow/scripts/cylc_psutil.py, cylc/flow/tui/data.py, tests/functional/jinja2/08-local-lib-python/Jinja2Filters/qualify.py, tests/functional/jinja2/08-local-lib-python/lib/python/local_lookup.py, tests/functional/jinja2/filters/Jinja2Filters/hello.py, tests/functional/jinja2/filters/Jinja2Filters/truly.py, tests/functional/rnd/02-lib-python-in-job/lib/python/pub/beer.py, tests/functional/xtriggers/02-persistence/faker_fail.py, tests/functional/xtriggers/02-persistence/faker_succ.py, tests/integration/test_client.py, tests/unit/main_loop/auto_restart.py, tests/unit/main_loop/log_data_store.py, tests/unit/main_loop/log_main_loop.py, tests/unit/main_loop/log_memory.py, tests/unit/main_loop/main_loop.py, tests/unit/option_parsers.py, tests/unit/parsec/test_config_node.py, tests/unit/parsec/test_dict_tree.py, tests/unit/parsec/test_types.py, tests/unit/test_context_node.py, tests/unit/test_host_select_remote.py, tests/unit/tui/test_data.py, tests/unit/tui/test_overlay.py, tests/unit/tui/test_util.py
(seriously, people might think there's nothing else going on because of some sort of disease...)
Just say if you think I should remove the change from the trivially small files, otherwise don't wish to waste any more time on this.
=> add copyright notices to files where it was missing.

cylc/flow/cfgspec/suite.py
=> Fix deprecation upgrade warning message

cylc/flow/cfgspec/suite.py
These changes go some way to fixing issues identified by @MetRonnie  in https://github.com/cylc/cylc-flow/pull/3846.
=> Glbl cfg update.mail

cylc/flow/cfgspec/suite.py, cylc/flow/parsec/validate.py
Small doc changes to match https://github.com/cylc/cylc-doc/pull/166.
=> doc: update reference labels

cylc/flow/cfgspec/globalcfg.py, tests/functional/cylc-get-site-config/00-basic.t
Remove sections agreed to be obsolete.
Change log and documentation to be done as separate PR at the end of #3696
=> remove documentation and document viewers section from global config.

cylc/flow/task_events_mgr.py, tests/functional/remote/03-polled-task-started.t, tests/functional/remote/03-polled-task-started/flow.cylc, tests/functional/remote/03-polled-task-started/reference.log
=> Fix polled task:start bug

cylc/flow/network/graphql.py, tests/unit/network/test_graphql.py
=> fix null-stripping of repeated composite fields

CHANGES.md, CONTRIBUTING.md, tests/unit/test_remote.py
=> Remote newline strip

cylc/flow/main_loop/__init__.py, cylc/flow/scheduler.py, cylc/flow/scheduler_cli.py, cylc/flow/suite_events.py, etc/bin/start-group-demo.sh, tests/functional/remote/03-polled-task-started/flow.cylc, tests/functional/restart/53-task-prerequisites/flow.cylc, tests/unit/conftest.py, tests/unit/test_config.py
Clean up a couple of dangling `[cylc]` references.
=> conf: cylc->scheduler

tests/functional/reload/20-stop-point.t, tests/functional/reload/20-stop-point/flow.cylc, tests/functional/restart/submit-failed/flow.cylc
A couple of small test fixes, likely rebase errors that crept in.
=> tests/f: fix reload/20, restart/05

tests/functional/restart/34-auto-restart-basic.t
fix a shared filesystem test (not currently run by the swarm)
=> tests/f: fix restart/34

etc/bin/swarm
@oliver-sanders - one review will do.
=> Tweak swarm help iptables advice.

cylc/flow/scripts/scan.py, tests/integration/test_scan_api.py, tests/unit/test_scan.py
* Add a `--ping` option to `cylc scan` which forces a connection to the running workflow.
* Ensure that `cylc scan --ping` will remove a contact file from a crashed flow.
=> scan: ping

cylc/flow/cfgspec/suite.py, cylc/flow/etc/syntax/cylc.lang, cylc/flow/etc/syntax/cylc.xml, cylc/flow/scheduler.py, tests/functional/deprecations/01-cylc8-basic/flow.cylc, tests/functional/deprecations/01-cylc8-basic/validation.stderr
These changes partially address #3696
=> conf: disable suite event handlers

tests/functional/restart/53-task-prerequisites.t
=> Fix test description

CHANGES.md, doc/src/task-job-submission.rst, lib/cylc/batch_sys_handlers/slurm.py, lib/cylc/batch_sys_handlers/slurm_packjob.py, lib/cylc/tests/test_slurm.py, lib/cylc/tests/test_slurm_packjob.py
These changes partially address #3964 (will be closed by sibling PR to master)
See description, example and questions on the master version #3971 (example needs adapting to Cylc 7, of course)
=> Slurm heterogeneous job support 7.8.x

CHANGES.md, cylc/flow/suite_db_mgr.py, cylc/flow/task_events_mgr.py, cylc/flow/task_pool.py
closes #3975 
foreport of #3948
=> db: only write task event timers when changed

tests/functional/remote/01-file-install.t, tests/functional/remote/02-install-target.t
=> Fix remote functional tests

cylc/flow/scheduler.py, cylc/flow/task_job_mgr.py
These changes close #3994 
Job submit was waiting on remote install but not remote init.
@datamel - this seems to fix the problem, but can you check that I got it right?
=> Fix wait on remote file install.

cylc/flow/cfgspec/suite.py, cylc/flow/config.py, tests/flakyfunctional/job-submission/18-check-chunking.t, tests/flakyfunctional/restart/46-stop-clock-time.t, tests/functional/cylc-get-config/05-param-vars/flow.cylc, tests/functional/deprecations/01-cylc8-basic/flow.cylc, tests/functional/deprecations/01-cylc8-basic/validation.stderr, tests/functional/job-submission/15-garbage-platform-command-2/flow.cylc, tests/functional/param_expand/01-basic.t, tests/functional/param_expand/02-param_val.t, tests/functional/param_expand/03-env-tmpl/flow.cylc, tests/functional/queues/02-queueorder/flow.cylc, tests/functional/restart/34-auto-restart-basic.t, tests/functional/restart/45-stop-task.t, tests/functional/validate/64-circular.t, tests/unit/test_config.py
also: Replace [scheduling][parameter templates] with [task parameters][templates]
- ~[x] No documentation update required: Log entry change to be made at the end of the issue.~
-  [ ] cylc-doc PR required
=> Replace [scheduling][parameters] with [task parameters]

cylc/flow/cfgspec/globalcfg.py, cylc/flow/task_remote_mgr.py
These changes partially address #3696 and #3593
=> Remove `[platforms][PLATFORM][owner]` from conf

tests/functional/cylc-run/03-remote-run-host.t
=> attempt to test remote

CHANGES.md, cylc/flow/cfgspec/globalcfg.py, cylc/flow/job_runner_handlers/loadleveler.py, cylc/flow/job_runner_handlers/lsf.py, cylc/flow/job_runner_handlers/moab.py, cylc/flow/job_runner_handlers/pbs.py, cylc/flow/job_runner_handlers/sge.py, cylc/flow/job_runner_handlers/slurm.py
Sorry, was too eager pressing the merge button on #3992, some hangover:
* Re-write some code examples.
* Tidy a couple of dangling `batch system` mentions.
* Add the missing changelog.
=> job runner: mop up

cylc/flow/job_runner_handlers/sge.py, cylc/flow/job_runner_handlers/slurm.py
=> remove job section

cylc/flow/network/schema.py, cylc/flow/scripts/broadcast.py
* Fix the default value for `mode`.
* Change `settings` to use a new special input type (so the UI can display it differently).
=> schema: broadcast changes

cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/suite.py
Fix some doc issues / RST formatting problems.
=> cfgspec: fix doc issues

.github/workflows/update_copyright.yml
Ready for review after https://github.com/cylc/release-actions/pull/8
=> GH Actions: Prevent update_copyright workflow running on forks

tests/functional/restart/41-auto-restart-local-jobs.t, tests/functional/restart/42-auto-restart-ping-pong.t, tests/functional/restart/43-auto-restart-force-override-normal.t
=> Fix some functional tests that don't run on GH Actions

setup.py
Does this dependency do anything, methinks not, let's find out.
=> remove codecov dependency

tests/flakyfunctional/job-submission/19-chatty.t
=> Fix flaky-functional job-submission/19-chatty

.github/workflows/bash.yml, .github/workflows/test_fast.yml, .github/workflows/test_functional.yml
Run tests on pushes to master (which includes merged PRs) because:
1. It looks like this is needed to properly track coverage (see discussion: https://github.com/cylc/cylc-flow/pull/4048#issuecomment-767606529)
2. It's the only way to be sure different PRs don't break each other when merged
=> Run tests on master

cylc/flow/platforms.py, cylc/flow/scheduler.py, cylc/flow/scripts/remote_init.py, cylc/flow/task_remote_mgr.py, tests/unit/test_task_remote_mgr.py
=> Fix remote init bug

cylc/flow/network/schema.py
This is a small change with no associated Issue. Related to https://github.com/cylc/cylc-ui/pull/586
=> GraphiQL: Document what stripNull does

cylc/flow/etc/syntax/cylc.lang, cylc/flow/etc/syntax/cylc.xml, etc/bin/syntax_generator.py, tests/unit/test_syntax_generator.py
These changes partially address #3860 
Questions:
- Is this approach sane?
- Can we apply this to the VSCode extension?
- Does this functionality belong within or without this repo?
- Do we want to add output to repo .gitignore to avoid being spammed with change PRs by GH Actions?
=> [ONLY CODECOV FAILING] Syntax-generator

tests/functional/lib/bash/test_header, tests/functional/platforms/02-host-to-platform-upgrade.t, tests/functional/platforms/02-host-to-platform-upgrade/flow.cylc, tests/functional/remote/03-polled-task-started.t, tests/functional/remote/03-polled-task-started/flow.cylc
=> Fix and tidy functional tests

tests/functional/spawn-on-demand/08-lost-parents.t
Test was running install suite unnecessarily, causing it to report an error.
=> Fix install error on sod test

tests/functional/events/42-late-then-restart.t, tests/functional/spawn-on-demand/03-conditional.t, tests/functional/spawn-on-demand/04-branch.t, tests/functional/spawn-on-demand/05-stop-flow.t, tests/functional/spawn-on-demand/06-stop-flow-2.t
Some tests were duplicating the install suite, resulting in errors in the output.
I have removed the unnecessary  installs.
=> Prevent duplicate install in some functional tests

.github/workflows/test_fast.yml, .github/workflows/test_functional.yml
Give in to Codecov's badgering for fetch-depth<1, let's see if it makes a difference.
=> actions: set fetch-depth: 2 to make codecov happy

tests/functional/cylc-clean/00-basic.t, tests/functional/cylc-install/03-file-transfer.t
sibling: https://github.com/cylc/cylc-rose/pull/34
Test fix associated with https://github.com/cylc/cylc-rose/pull/34
=> remove lines which break.

tests/functional/cli/01-help.t, tests/functional/job-submission/18-clean-env.t
To placate our new version of shellcheck on GH Actions
=> Remove whiches

cylc/flow/scripts/reinstall.py
Companion to [cylc-rose PR 42](https://github.com/cylc/cylc-rose/pull/42). 
These changes partially address [cylc-rose issue 41](https://github.com/cylc/cylc-rose/issues/41)
=> Cylc reinstall  `--clear-rose-install-options`

cylc/flow/pathutil.py, cylc/flow/platforms.py, cylc/flow/suite_files.py, cylc/flow/task_job_mgr.py, cylc/flow/task_remote_mgr.py, tests/unit/test_platforms_get_platform.py
These changes close https://github.com/cylc/cylc-flow/issues/4060
=> Replace string literals of localhost with function returning config

cylc/flow/platforms.py, tests/functional/platforms/07-localhost-set-if-not-in-globalcfg.t, tests/functional/platforms/07-localhost-set-if-not-in-globalcfg/flow.cylc, tests/unit/test_platforms.py, tests/unit/test_platforms_get_platform.py
- Unit test: Check handling of commas in platforms name.
- Unit tests to check handling of platforms where localhost in list.
- Functional test for comma in platform names bug.
These changes (probably) close #4117 
=> Allow comma lists in platform names.

cylc/flow/main_loop/auto_restart.py
Found a broken reference, quick fix.
To test build the docs and make sure that all the links are clickable.
=> doc: improve main-loop docs

cylc/flow/option_parsers.py
=> cli: remove pyro option

cylc/flow/data_store_mgr.py
=> Remove queued/held delta filter

cylc/flow/cfgspec/globalcfg.py
Document the `[scheduler][run host]ranking` configuration.
=> conf: document run host rankings

CHANGES.md, cylc/flow/__init__.py
=> 8.0b1 -> 8.0b2.dev

setup.py
Find out if the pytest-asyncio patch works for us on GH actions...
Yes, yes it does.
=> setup: bump pytest-asyncio version

cylc/flow/subprocpool.py
Currently workflows can crash during shutdown whilst trying to terminate processes in the subprocpool.
See https://github.com/cylc/cylc-flow/pull/4213#issuecomment-844305766, example traceback (from GH action s):
```
Workflow shutting down - REQUEST(NOW-NOW)
Error during shutdown
[Errno 1] Operation not permitted
File "~/cylc-flow/cylc/flow/scheduler.py", line 1629, in shutdown
await self._shutdown(reason)
File "~/cylc-flow/cylc/flow/scheduler.py", line 1673, in _shutdown
self.proc_pool.terminate()
File "~/cylc-flow/cylc/flow/subprocpool.py", line 270, in terminate
os.killpg(proc.pid, SIGKILL)
PermissionError: [Errno 1] Operation not permitted
INFO - DONE
```
Given that we know these subprocess were started by the user this `PermissionError` does not …
=> subprocpool: handle PermissionError on killpg

cylc/flow/scheduler.py
Instead of this:
```
INFO - Command succeeded: hold(['bar.2'])
INFO - Processing 1 queued command(s)
+       hold(['bar.2'])
```
log this
```
INFO - Processing 1 queued command(s)
INFO - Command succeeded: hold(['bar.2'])
```
=> Log "processing n queued commands" before they've completed instead of after

.github/workflows/test_fast.yml, cylc/flow/cfgspec/globalcfg.py, setup.py
@kinow - this should be uncontroversial, one review will do.
=> Handle mypy 0.900.

.github/workflows/test_fast.yml, mypy.ini, setup.py
`conda-environment.yml`. (No, because they're only dependencies for tests)
=> Mypy 0.9 follow-up

cylc/flow/cfgspec/globalcfg.py, cylc/flow/scripts/config.py, tests/functional/cylc-cat-log/02-remote-custom-runtime-viewer-pbs.t, tests/functional/cylc-clean/01-remote.t, tests/functional/cylc-get-config/00-simple.t, tests/functional/cylc-get-config/00-simple/flow.cylc, tests/functional/cylc-get-site-config/00-basic.t, tests/functional/cylc-get-site-config/01-defaults.t, tests/functional/cylc-get-site-config/02-jinja2.t, tests/functional/inheritance/00-namespace-list.t, tests/functional/lib/bash/test_header, tests/functional/param_expand/01-basic.t, tests/functional/remote/01-file-install.t, tests/functional/remote/04-symlink-dirs.t, tests/functional/rnd/01-editors.t, tests/functional/workflow-host-self-id/00-address.t, tests/functional/workflow-state/00-polling.t, tests/functional/workflow-state/01-polling.t, tests/functional/workflow-state/polling/flow.cylc, tests/functional/workflow-state/upstream/flow.cylc
closes #4143
Something we could do with getting into the next beta to avoid having two rounds of disruption.
=> config: make --sparse the defalt

cylc/flow/data_store_mgr.py
=> remove updated delta with pruned

.github/workflows/test_fast.yml, .github/workflows/test_functional.yml
Reverts https://github.com/cylc/cylc-flow/pull/4176/commits/f0b43a5af5a3d0d1669790c3d4a5fd8e2074c3f8 which is no longer needed.
=> actions: revert dns hack

cylc/flow/network/scan.py, tests/integration/test_scan.py
Required to solve https://github.com/cylc/cylc-uiserver/issues/223
* Add a workflow_params scan filter for reading the db workflow_params table
* This allows us to determine the workflow run UUID string when the
scheduler is down (important for the UIS)
=> scan: workflow_params

cylc/flow/job_runner_handlers/pbs.py
Found during chat in Element with John and @hjoliver . One review should do (not assigning anyone).
- [] Applied any dependency changes to both `setup.py` and
=> Fix global.cylc extension in comment

.mailmap, CHANGES.md, CONTRIBUTING.md, lib/cylc/task_job_mgr.py
=> Extra log file replication fix

cylc/flow/exceptions.py, cylc/flow/network/__init__.py, tests/unit/network/test__init__.py
These changes partially address #4309
=> Log failure where attempting to use Cylc 8 on installed Cylc 7 workflow.

CHANGES.md, cylc/flow/workflow_files.py, tests/unit/test_workflow_files.py
These changes close https://github.com/cylc/cylc-flow/issues/4318
=> Update rsync to skip cylc dirs work and share

.coveragerc, .github/workflows/bash.yml, .github/workflows/test_fast.yml, .github/workflows/test_functional.yml
- Apparently coverage doesn't work properly with pytest if you don't `pip install -e` (editable mode)
- Switched from the deprecated Codecov bash uploader to Codecov's dedicated GH Action
=> Fix coverage

tests/functional/cylc-install/04-symlinks-not-resolved.t
=> test for symlinks to being chased

cylc/flow/cfgspec/globalcfg.py
This is a small change with no associated Issue. This is just the tidying cherry picked from #4339 
=> Tidy globalcfg

.codecov.yml
Remove some configs which were set to the default values. Some of these configs appear to have since moved, I wonder if that was causing us problems?
=> codecov: fiddle configuration

cylc/flow/cfgspec/globalcfg.py, cylc/flow/task_events_mgr.py
=> Remove Task Mail  section

cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/workflow.py
These changes partially address #4342 
=> Improvements to documentation of platforms

CHANGES.md, usr/bin/cylc
Follow-up to #4367: add change log, and a quick upgrade to the "how this wrapper works" in-file doc.
=> cylc wrapper change log and comments update

.github/workflows/test_fast.yml
Also use [`PYTEST_ADDOPTS`](https://docs.pytest.org/en/stable/reference.html#envvar-PYTEST_ADDOPTS) to avoid repetition
=> Add colour to GH Actions pytest log

cylc/flow/cycling/iso8601.py, cylc/flow/platforms.py, cylc/flow/scripts/scan.py, cylc/flow/task_job_mgr.py, cylc/flow/task_pool.py
Recent changes to [flake8 Simplify](https://github.com/MartinThoma/flake8-simplify/commits/master) highlighted some over-complex logic in Cylc. This PR simplifies this logic.
=> fix flake8-simplify failures caused by recently added checks.

lib/cylc/batch_sys_manager.py
These changes partially address #4431  - The remaining thing to do is to check that same bug doesn't exist at Cylc8
=> prevent slow polling producing incorrect submit-fail

.coveragerc
This is a small change with no associated Issue
Fix broken coverage checking.
=> Fix broken tests

cylc/flow/network/resolvers.py
These changes close https://github.com/cylc/cylc-ui/issues/834
Issue introduced with #4479 
=> Remove yield delay on graphql subscription delta processing

cylc/flow/network/resolvers.py, cylc/flow/scripts/set_outputs.py, cylc/flow/task_pool.py, tests/functional/cli/04-cli-error.t, tests/functional/spawn-on-demand/12-set-outputs-no-reflow.t, tests/functional/spawn-on-demand/12-set-outputs-no-reflow/flow.cylc, tests/functional/spawn-on-demand/12-set-outputs-no-reflow/reference.log
Similar to #4487, but for `cylc set-outputs` and equivalent via the GUI.
=> set-outputs mutation fix

.github/workflows/test_functional.yml
This is a small change with no associated Issue: Fix the failure of Pip to cope with repos with symlinks in them.
=> Don't install rose

.codecov.yml, .github/workflows/test_functional.yml, cylc/flow/exceptions.py, cylc/flow/workflow_files.py, tests/functional/cylc-graph-diff/00-simple.t, tests/functional/cylc-install/02-failures.t, tests/functional/cylc-reinstall/02-failures.t, tests/unit/test_workflow_files.py
=> Review of Cylc Install error messages

cylc/flow/config.py, cylc/flow/network/graphql.py, cylc/flow/parsec/util.py, cylc/flow/scripts/cycle_point.py, tests/unit/network/test_graphql.py
The latest version of Flake8 simplify identified 3 locations where our code could be simpler.
=> Take suggestions from flake8 simplify

cylc/flow/option_parsers.py, tests/functional/cylc-install/06-check-logs-svn.t, tests/functional/lib/bash/test_header, tests/functional/test_functions/00-grep_fail.t, tests/functional/test_functions/test_header
=> Grep fail should only pass if file exists *and* grep fails

conda-environment.yml, cylc/flow/network/ssh_client.py, setup.cfg
Closes https://github.com/cylc/cylc-flow/issues/4129
=> add async request to ssh client

cylc/flow/resources.py
=> get-resources.only run backup logic if resource is tutorial

tests/unit/parsec/test_validate.py
This is a small change with no associated Issue. There seems to have been a change to the way `pytest.approx()` can be used in assertions.
```
E               AssertionError: approx() is not supported in a boolean context.
E               Did you mean: `assert a == approx(b)`?
```
=> Fix unit tests

cylc/flow/broadcast_mgr.py, cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/workflow.py, cylc/flow/main_loop/__init__.py, cylc/flow/parsec/validate.py
This is a small change with no associated Issue: Fix some misspellings
=> Fix small spelling errors

cylc/flow/network/schema.py
Flake8-simplify has been updated on CI.
*SIM904: Assign values to dictionary directly at initialization*
One review will do.
=> Fix for new flake8-simplify rule.

tests/functional/cylc-clean/00-basic.t, tests/functional/cylc-clean/02-targeted.t, tests/functional/cylc-clean/03-multi.t, tests/functional/cylc-clean/basic-workflow/flow.cylc, tests/functional/lib/bash/test_header
=> Add func test for multi clean

tests/functional/job-submission/03-job-nn-remote-host-with-shared-fs.t
Install no longer creates the `.service` directory.
=> tests/f: fix job-submission/03

tests/integration/test_server.py
* Hopefully closes #4708.
* Switch from run to start (no need to have main loop running for tests).
* Add a timeout just in case.
* Fix tests and add a positive test case to prevent them breaking again.
=> tests/i: attempt to stabilise test_server tests

cylc/flow/parsec/upgrade.py, tests/unit/parsec/test_upgrade.py
=> Config upgrader: ignore conflicting items if null value.

cylc/flow/data_store_mgr.py, cylc/flow/task_pool.py, cylc/flow/util.py, cylc/flow/workflow_db_mgr.py, tests/unit/test_util.py
These changes close https://github.com/cylc/cylc-flow/issues/4672
=> serialise/deserialise added for flow_nums consistency

cylc/flow/cfgspec/globalcfg.py
(please ensure this builds against cylc-doc correctly)
=> config: add default for entries for shared global config items

cylc/flow/task_pool.py
=> Fix spawning bug.

cylc/flow/__init__.py
=> Bump version number

cylc/flow/scripts/stop.py, tests/unit/scripts/test_stop.py
Disallow `cylc stop --flow=n TASK_ID`
Address comment #https://github.com/cylc/cylc-flow/issues/4741#issuecomment-1074550522
=> Check cylc stop options.

tests/integration/test_scheduler.py
=> Fix integration test.

cylc/flow/workflow_files.py, setup.cfg, tests/functional/cylc-cat-log/03-bad-workflow.t, tests/functional/cylc-graph-diff/00-simple.t, tests/functional/cylc-reinstall/02-failures.t, tests/unit/test_id_cli.py, tests/unit/test_subprocpool.py, tests/unit/test_workflow_files.py
These changes close https://github.com/cylc/cylc-flow/issues/4766
=> Fix Error Message for RunN Workflow IDs

conda-environment.yml, setup.cfg
Add an explanatory comment on protobuf version pinning. Somewhat obvious with a moment's thought, but no harm in being clear about it.
Motivated by: https://github.com/cylc/cylc-flow/issues/4796#issuecomment-1088365632
=> Comment to explain protobuf version pinning.

cylc/flow/task_events_mgr.py, tests/flakyfunctional/events/44-timeout.t, tests/functional/events/10-task-event-job-logs-retrieve.t
These changes address https://github.com/cylc/cylc-flow/pull/4800#discussion_r842883460
Example: delay job log retrieval for a task that succeeded.
On master:
```
2022-04-19T11:06:22+12:00 DEBUG - 1/a/01 ('job-logs-retrieve', 'succeeded')            
will run after PT10S (after 2022-04-19T11:06:32+12:00) 
```
```
2022-04-19T11:19:44+12:00 DEBUG - 1/a/01 handler:job-logs-retrieve for task event:succeeded
will run after PT10S (after 2022-04-19T11:19:54+12:00)                                   
```
=> Better event handler failure and retry messages.

cylc/flow/network/resolvers.py
Add explanatory comments, are these ok?
=> resolvers: add a couple of comments

cylc/flow/__init__.py
Edit: I may have gotten a bit ahead of the release process https://github.com/cylc/cylc-admin/issues/153, oh well
=> Bump to next dev version

cylc/flow/id_match.py
In this case the suggested refactor would IMO make the code
less rather than more readable.
=> Added a noqa tag to a new flake8-simplify case.

.github/workflows/test_fast.yml, cylc/flow/hostuserutil.py, cylc/flow/option_parsers.py, pytest.ini, tests/unit/test_links.py
These changes close #4807 
Well that mission creeped - 
- I used a shortened the link because I couldn't get it to work in the CLI help otherwise.
- I thought I should test links because `cylc-doc`'s `make clean linkcheck` doesn't test this link (I hoped it might because this help is ingested into the docs), or other links embedded in the code-base.
- I wrote a test to check URLs in the codebase.
- Found at least one reference to a website which is broken. Replaced it with the Smithstonian's internet archive link.
=> Added note to --icp in cylc play CLI that it can take intervals

lib/cylc/review.py
After merge/release of https://github.com/cylc/cylc-flow/pull/4836. Cylc review will need updating.
These changes close https://github.com/cylc/cylc-flow/issues/4839
=> Update cylc review

cylc/flow/cfgspec/globalcfg.py, cylc/flow/job_runner_mgr.py, tests/functional/platforms/07-localhost-set-if-not-in-globalcfg.t, tests/unit/test_job_file.py
This is a small change with no associated Issue. 
=> Fix some outdated terminology.

cylc/flow/cfgspec/workflow.py
These changes partially address #4915
=> added simple docs for default queues.

cylc/flow/scheduler.py
A small flake8 failure appears to have crept into master.
=> fix flake8 bug which crept into master

cylc/flow/cfgspec/globalcfg.py
- A flake8 problem has been accidentally committed to master.
=> fix flake8

cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/workflow.py
These changes close #4915 
Nail remaining config item descriptions.
=> Add remaining workflow config item descriptions.

cylc/flow/network/replier.py, cylc/flow/network/server.py, cylc/flow/task_events_mgr.py
=> spelling fixes

cylc/flow/cfgspec/globalcfg.py
These changes close https://github.com/cylc/cylc-doc/issues/481
=> Document the 'abort' config items.

cylc/flow/scripts/cat_log.py, cylc/flow/scripts/check_versions.py, cylc/flow/scripts/ext_trigger.py, cylc/flow/scripts/message.py, cylc/flow/scripts/reload.py, cylc/flow/scripts/set_outputs.py, cylc/flow/scripts/stop.py, cylc/flow/scripts/validate.py
Had a quick review of the CLI docs, found a couple of small things.
Reformatted a couple of paragraphs which were unnecessarily "narrow" due to being copied from the schema docs?
=> cli: minor docs changes for 8.0.0 release

CHANGES.md, cylc/flow/network/schema.py, cylc/flow/scripts/broadcast.py, cylc/flow/workflow_status.py, tests/functional/graphql/01-workflow.t
=> Merge 8.0.x into master

.github/workflows/1_create_release_pr.yml, .github/workflows/bash.yml, .github/workflows/test_conda-build.yml, .github/workflows/test_fast.yml, .github/workflows/test_functional.yml, .github/workflows/test_tutorial_workflow.yml, CHANGES.md, cylc/flow/cycling/__init__.py, cylc/flow/cycling/iso8601.py, cylc/flow/time_parser.py, tests/unit/test_config.py
=> 8.1.0:  Merged Fix chained offset bug

cylc/flow/network/__init__.py, cylc/flow/parsec/fileparse.py, cylc/flow/tui/app.py, cylc/flow/workflow_files.py, cylc/flow/xtriggers/echo.py
=> small flake8 fixes

cylc/flow/network/scan.py
Spotted by Dave whilst reviewing DB use:
* The workflow_params function was using the private DB to list workflow params.
* Really it should be using the public DB as only the scheduler process/thread should be accessing the private DB to avoid the potential for DB locking.
Note this functionality was prepared ahead of use in the UIS (https://github.com/cylc/cylc-uiserver/issues/371) but this work has been pushed back so it's currently unused.
So this code is a bug "in waiting", if this interface were to be called it would cause DB locking, similar to the `rose_prune` issue.
=> scan: update workflow_params to use public db

cylc/flow/exceptions.py, cylc/flow/network/__init__.py, cylc/flow/network/client.py
Needed for https://github.com/cylc/cylc-uiserver/pull/379
**Check List**
=> Add workflow field to `ClientError`, `ClientTimeout`

cylc/flow/tui/data.py
Had need of this today.
**Check List**
=> tui: add poll mutation

cylc/flow/option_parsers.py
=> Fix.rose arguments

lib/cylc/cylc-review/static/js/search.js
* Closes #5019
* Escaped `/` characters are un-escaped by Apache in URLs, move this parameter to the request header.
**Check List**
=> review: fix search error on Apache under WSGI

cylc/flow/data_store_mgr.py
Back-port https://github.com/cylc/cylc-flow/pull/5149 onto 8.0.x.
=> 8.0.x patch

.github/workflows/2_auto_publish_release.yml
Needs cylc/release-actions#43
**Check List**
=> Auto bump dev version on release

.github/workflows/2_auto_publish_release.yml, .github/workflows/bash.yml, .github/workflows/test_fast.yml, .github/workflows/test_functional.yml, .github/workflows/test_tutorial_workflow.yml
Cherry picks:
- #5136 
- #5141
as these seem to be needed on the 8.0.x branch as well
=> Cherry picked GH Actions updates for 8.0.x

tests/functional/retries/01-submission-retry.t
=> Fix erroneous test skip

cylc/flow/install_plugins/log_vc_info.py, cylc/flow/network/scan.py, cylc/flow/workflow_files.py, tests/integration/test_scan.py, tests/unit/post_install/test_log_vc_info.py, tests/unit/test_workflow_files.py
Rationalize where constants are kept. Came out of reviewing #5140 
**Check List**
=> move references to sub-folders into workflow files

.github/workflows/test_functional.yml, CHANGES.md, cylc/flow/rundb.py, cylc/flow/scheduler.py, cylc/flow/task_pool.py, cylc/flow/workflow_db_mgr.py, cylc/flow/workflow_files.py, tests/functional/job-submission/01-job-nn-localhost/db.sqlite3, tests/functional/restart/57-ghost-job/db.sqlite3, tests/functional/retries/01-submission-retry.t, tests/integration/conftest.py, tests/integration/test_task_pool.py, tests/integration/test_workflow_db_mgr.py
=> 8.0.x.patch

cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/workflow.py
=> tiny spelling fix

cylc/flow/cfgspec/globalcfg.py, cylc/flow/cfgspec/workflow.py
Answers some of https://github.com/cylc/cylc-doc/issues/505
=> minor handling docs PR

cylc/flow/xtrigger_mgr.py
=> Fix minor issue with xtrigger docs

cylc/flow/scheduler_cli.py
Fix unformatted prompt message when restarting an 8.0 workflow with 8.1
Follow-up to #5074
**Check List**
=> Fix prompt message

CHANGES.md, cylc/flow/workflow_files.py, tests/functional/cylc-install/02-failures.t, tests/functional/cylc-reinstall/02-failures.t, tests/unit/test_workflow_files.py
Close #5223 
(Title is description)
**Check List**
=> install: disallow reserved names only at top level source dir

tests/functional/cylc-clean/05-old-remote-contact.t
A new shellcheck rule has been added.
=> shellcheck: disable warning

.github/workflows/test_functional.yml, tests/functional/cylc-clean/05-old-remote-contact.t
Needed to get style check to pass. First come, first merge
=> 8.0.x -> master

cylc/flow/data_store_mgr.py
Closes https://github.com/cylc/cylc-ui/issues/1145
**Check List**
=> all job messages each delta

CHANGES.md, cylc/flow/remote.py, cylc/flow/scheduler.py, cylc/flow/task_remote_mgr.py, tests/functional/intelligent-host-selection/01-periodic-clear-badhosts.t, tests/functional/intelligent-host-selection/05-from-platform-group.t, tests/functional/remote/04-symlink-dirs.t, tests/functional/remote/09-restart-running-file-install.t
Closes https://github.com/cylc/cylc-flow/issues/5204
**Check List**
=> Fix restart remote install

CHANGES.md, cylc/flow/host_select.py, cylc/flow/network/ssh_client.py, cylc/flow/remote.py, cylc/flow/scheduler.py, cylc/flow/scheduler_cli.py, cylc/flow/scripts/cat_log.py, cylc/flow/scripts/check_versions.py, cylc/flow/task_events_mgr.py, cylc/flow/task_job_mgr.py, cylc/flow/task_remote_mgr.py, cylc/flow/workflow_files.py, tests/functional/events/51-task-event-job-logs-retrieve-4.t, tests/functional/intelligent-host-selection/01-periodic-clear-badhosts.t, tests/functional/intelligent-host-selection/05-from-platform-group.t, tests/functional/remote/04-symlink-dirs.t, tests/functional/remote/09-restart-running-file-install.t, tests/integration/test_task_job_mgr.py, tests/unit/scripts/test_check_versions.py, tests/unit/test_host_select.py
> **Bugfix PR**: Do not squash-merge!
=> 8.0.x sync

cylc/flow/data_store_mgr.py, tests/unit/test_data_store_mgr.py
=> Method calculating task mean elapsed time returns an integer

cylc/flow/__init__.py
* Created `8.1.x` branch.
* Bumping master to `8.2.0`.
=> bump version: 8.2.0

.github/workflows/test_fast.yml, conda-environment.yml, cylc/flow/hostuserutil.py, setup.cfg, tests/unit/test_links.py
Also cherry-picked #5333
**Check List**
=> Fix linkcheck by excluding web.archive.org

cylc/flow/network/client_factory.py
Small fix to ensure mypy works.
=> fix mypy fail caused by https://github.com/python/mypy/pull/13969

cylc/flow/data_store_mgr.py
=> data store: support unsatisfied ext_trigger

cylc/flow/network/resolvers.py
> Sibling: https://github.com/cylc/cylc-ui/pull/1230
* A couple of ID lists were being converted to sets which caused the return order to become jumbled.
* Switch to a function which removes duplicates whilst maintaining order
* Closes #5366
**Check List**
=> graphql: stabilise ID iteration order

.github/workflows/2_auto_publish_release.yml, CHANGES.md, cylc/flow/scripts/install.py
=> 8.1.x -> master

cylc/flow/network/schema.py
Sibling PRs: https://github.com/cylc/cylc-uiserver/pull/418, https://github.com/cylc/cylc-ui/pull/1224
This enables buttons to be disabled in the ui, based on workflow state.
Closes https://github.com/cylc/cylc-flow/issues/4726, https://github.com/cylc/cylc-ui/issues/868
**Check List**
=> Update Descriptions in Schema

cylc/flow/cycling/iso8601.py, tests/unit/conftest.py, tests/unit/cycling/test_iso8601.py
* Convert unit tests to pytests.
* Fix issue where the setup of one test changed the environment of the next.
* Fixed an issue where a test was missing a setup step so failed unless run after a test which performed the required setup.
**Check List**
=> tests/u: cycling/test_iso8601 - unittest -> pytest

cylc/flow/exceptions.py
=> Fix possible IndexError during shutdown

cylc/flow/option_parsers.py, cylc/flow/platforms.py, cylc/flow/scripts/validate_reinstall.py, tests/functional/cylc-combination-scripts/01-vr-reload.t, tests/functional/cylc-combination-scripts/07-vr-remote.t, tests/functional/cylc-combination-scripts/vr_workflow_stop/flow.cylc
> Sync PR: Do not squash merge.
=> Fix cleanup_sysargv (for remote play in vip and vr) (#5377)

cylc/flow/scheduler.py
From recent correspondence I think some users are encountering critical error, but not reporting them to us.
Add a message to accompany tracebacks encouraging error reporting.
**Check List**
=> add instruction to report critical traceback

cylc/flow/scripts/cat_log.py, tests/functional/cylc-cat-log/00-local.t, tests/functional/cylc-cat-log/01-remote.t
Reject non-normalised paths.
**Check List**
=> cat-log: reject non-normalised paths

cylc/flow/install.py
A simple one word fix for a typo...
**Check List**
=> fix a typo in document

cylc/flow/cfgspec/globalcfg.py
=> Improve documentation for retrieve job logs command

cylc/flow/scripts/reinstall.py, cylc/flow/scripts/validate_reinstall.py
* The reload message is not applicable when using `cylc vr` because it does it for you.
* Closes #5344
**Check List**
=> validate-reinstall: don't print reload message

.github/workflows/test_fast.yml, .github/workflows/test_functional.yml
=> (Cherry pick) Upload coverage to Codecov in separate job

CHANGES.md, cylc/flow/hostuserutil.py, cylc/flow/task_job_mgr.py, cylc/flow/task_remote_mgr.py, tests/functional/platforms/10-do-not-host-check-platforms.t, tests/unit/test_hostuserutil.py
=> Fix localhost platform matching

.github/workflows/build.yml
Cherry-picked from the postponed https://github.com/cylc/cylc-flow/pull/5251, previous runs from that branch here: https://github.com/cylc/cylc-flow/actions/workflows/build.yml
Add an action to ensure the setuptools build is working ok.
https://github.com/cylc/cylc-uiserver/blob/master/.github/workflows/build.yml
**Check List**
=> actions: add build test

CHANGES.md, cylc/flow/prerequisite.py, cylc/flow/task_state.py, cylc/flow/task_trigger.py, tests/unit/test_task_state.py
- Avoid duplicate prerequisites due to other recurrences with coincident points.
Close #5465
**Check List**
=> Avoid duplicate prerequisites from multiple recurrences.

CONTRIBUTING.md, cylc/flow/platforms.py
Dusted off an idle branch just so that the formatting follow-up to #5502 would not take up a whole PR 😅
**Check List**
=> Platforms code tidy

.github/workflows/1_create_release_pr.yml, .github/workflows/2_auto_publish_release.yml, .github/workflows/build.yml, .github/workflows/test_fast.yml, .github/workflows/test_functional.yml, .github/workflows/test_manylinux.yml, cylc/flow/scheduler.py, cylc/flow/scripts/cylc.py, cylc/flow/scripts/lint.py, cylc/flow/task_remote_mgr.py, setup.cfg, tests/integration/test_workflow_files.py
Add Python 3.11 support.
**Check List**
=> actions: test up to python 3.11

tests/functional/platforms/11-platform-gone-on-restart.t
=> Further fix for flaky test

cylc/flow/scripts/lint.py, tests/unit/scripts/test_lint.py
Minor refactor with no functionality changes:
* Read and lint one line at a time.
* Write annotations one line a time.
* Refactor tests to avoid mocking file opens or writing to the filesystem.
Reduce the number of tests from 2221 to 127.
**Check List**
=> lint: read files one line at a time

.github/workflows/branch_sync.yml
=> GH Actions patch

cylc/flow/scripts/lint.py, tests/unit/scripts/test_lint.py
Follow-up to #5536 (was merged with failing tests)
**Check List**
=> Fix cylc lint S011 (commented-out Jinja2) bug

cylc/flow/clean.py, cylc/flow/exceptions.py, cylc/flow/network/client.py, cylc/flow/scheduler.py, cylc/flow/scheduler_cli.py, cylc/flow/scripts/validate_reinstall.py, cylc/flow/workflow_files.py, tests/integration/test_workflow_files.py, tests/unit/test_clean.py
This is a small change with no associated issue.
**Check List**
=> Use more sensible exception class for `detect_old_contact_file()`

cylc/flow/scripts/cat_log.py, tests/functional/cylc-cat-log/00-local.t, tests/functional/cylc-cat-log/00-local/flow.cylc
Small change with no associated issue.
**Check List**
=> cat-log: handle filenames with spaces

tests/functional/job-submission/15-garbage-platform-command-2.t, tests/functional/job-submission/15-garbage-platform-command-2/flow.cylc, tests/functional/job-submission/15-garbage-platform-command-2/reference.log
Simplify and speed up one functional test.
@wxtim - this test predates your platforms work, but you're probably the best to review this ... I can't see why this test needs to 5 tasks rather than just one??
=> Simplify one functional test.

cylc/flow/task_pool.py
Small change with no associated issue
**Check List**
=> Fix simulation mode TypeError

cylc/flow/cycling/iso8601.py, cylc/flow/time_parser.py, tests/unit/cycling/test_iso8601.py
=> cycling exclusions: supress spurious warning for exclusion points

cylc/flow/etc/tutorial/runtime-tutorial/flow.cylc
Tutorial Changes to go with https://github.com/cylc/cylc-doc/pull/653
- Make order of obs stations match tutorial in docs.
- Make it necessary to carry follow step 2 of the tutorial and insert ICP and FCP.
- Make it necessary to add a jinja2 shebang, as in the tutorial.
IMO we should not merge these PR's until @joehickson and I have had a chance to skim the whole tutorial.
=> respond to @joehickson comments

setup.cfg, tests/unit/test_id_cli.py
https://github.com/pytest-dev/pytest-asyncio/issues/655
**Check List**
=> Exclude broken pytest-asyncio version; remove pytest-mock

tests/unit/test_remote.py
=> Fix test polluted by env vars

tests/integration/README.md
@oliver-sanders - this adds your comments [here](https://github.com/cylc/cylc-flow/pull/5658#issuecomment-1737182596) to `tests/integration/README.md` - OK?
=> Expand integration test docs.

setup.cfg
https://github.com/pytest-dev/pytest-asyncio/issues/706
**Check List**
=> Exclude broken pytest-asyncio version

cylc/flow/etc/syntax/cylc.lang, cylc/flow/etc/syntax/cylc.xml
This is a small change to update the Syntax files in the Cylc Repo.
=> Auto update syntax files

cylc/flow/log_level.py, cylc/flow/option_parsers.py
=> Added missing union type import

cylc/flow/network/schema.py
=> Tidy network code

cylc/flow/xtriggers/suite_state.py
=> fixed flake8

cylc/flow/clean.py, cylc/flow/exceptions.py, cylc/flow/task_remote_mgr.py, cylc/flow/util.py, cylc/flow/workflow_files.py
Might as well clean these up as I still get the mypy errors since I can only run `mypy --python-version 3.8`, no lower, when developing using Python 3.10
**Check List**
=> Fix type checking errors

cylc/flow/cfgspec/workflow.py
=> Docs: add version-added admonition

cylc/flow/etc/syntax/cylc.nanorc
Follow-up to #6072 
**Check List**
=> Fix Nano syntax highlighter installation instruction

cylc/flow/xtriggers/echo.py, cylc/flow/xtriggers/wall_clock.py, cylc/flow/xtriggers/workflow_state.py, cylc/flow/xtriggers/xrandom.py
Fixes a few issues spotted whilst reviewing https://github.com/cylc/cylc-doc/pull/686
**Check List**
=> xtriggers: docstring formatting fixes

cylc/flow/xtriggers/xrandom.py
=> Improve xrandom validate function docstring

.github/workflows/test_fast.yml, changes.d/5873.feat.md
=> GH Actions: print towncrier draft in job summary

cylc/flow/network/graphql.py, cylc/flow/network/resolvers.py, cylc/flow/network/schema.py
Originally created this branch to deal with #6023, however ended up fixing that in the uiserver at cylc/cylc-uiserver#566
**Check List**
=> GraphQL: Improve schema error handling & tidy

cylc/flow/cfgspec/workflow.py
Small change with no associated issue
**Check List**
=> Improve event handler doc

cylc/flow/network/ssh_client.py
Can't replicate this lint error locally (py 3.9, mypy 1.10.0), but it's flagged by CI.
Hopefully this'll do it.
=> fix lint error

cylc/flow/workflow_files.py
Small change to improve the logging of workflow_files checking for contact files.
**Check List**
=> Improve error logging for contact file checks.

cylc/flow/scripts/stop.py, tests/functional/shutdown/08-now1.t, tests/functional/shutdown/08-now1/flow.cylc
=> `cylc stop --now`: fix flaky test & clarify docs

cylc/flow/network/schema.py, cylc/flow/task_outputs.py, cylc/flow/tui/updater.py
New rule C420 added; https://github.com/adamchainz/flake8-comprehensions?tab=readme-ov-file#c420-unnecessary-dict-comprehension---rewrite-using-dictfromkeys
**Check List**
=> flake8-comprehensions

cylc/flow/scripts/install.py
=> install: fix colour formatting

cylc/flow/clean.py
Recommend using `--local-only` rather than removing the DB (does the same thing at the end of the day).
**Check List**
=> clean: change DB corruption advice

cylc/flow/cfgspec/globalcfg.py
Link the config into the user guide section.
=> doc: add link to task comms section

cylc/flow/loggingutil.py, tests/unit/test_loggingutil.py
A `glbl_cfg().get()` call can have the side effect of expanding the global config object, so should be avoided in the course of emitting log messages.
This will close #6244 by itself, but this is also supplementary to #6249; IMO both this and #6249 are worth having merged.
The added test is in a separate commit for ease of running against 8.3.x
**Check List**
=> Logging: do not access global config object during emit

cylc/flow/option_parsers.py, cylc/flow/terminal.py
Fixes help text colour formatting not working for individual CLI options (follow-up to #6021). E.g. in
```
-m STRING, --mode=STRING
[validate, play] Run mode: live, dummy, simulation
(default live).
```
`[validate, play]` should normally be coloured.
**Check List**
=> Fix help text colour for CLI options

tests/functional/flow-triggers/11-wait-merge.t, tests/functional/lib/bash/test_header, tests/functional/modes/04-simulation-runtime.t
See https://github.com/cylc/cylc-flow/issues/6276
**Check List**
=> Skip some failing functional tests on MacOS GH Actions runner

cylc/flow/network/schema.py
Fixes tiny lint failure from #6299
=> fixeth lint failure

cylc/flow/scripts/lint.py
Fixes a failure to pass tests on master.
**Check List**
IMO it only needs one Review.
=> Ensure that lint S014 has a proper test.

tests/unit/test_loggingutil.py
Follow-up to https://github.com/cylc/cylc-flow/pull/6327
=> Minor test follow-up

tests/integration/test_data_store_mgr.py
Add an integration test to cover #6114.
=> tests/i: add test for #6114

cylc/flow/data_store_mgr.py, cylc/flow/taskdef.py
Split off #6370 
**Check List**
=> Add type annotations & fix possible type error

changes.d/6364.fix.md, changes.d/6376.fix.md, cylc/flow/clean.py, cylc/flow/pathutil.py, cylc/flow/subprocpool.py, tests/unit/filetree.py, tests/unit/test_clean.py, tests/unit/test_pathutil.py
🤦‍♂️
- https://github.com/cylc/cylc-flow/pull/6364
- https://github.com/cylc/cylc-flow/pull/6376
=> Cherry pick bugfixes erroneously opened against master

cylc/flow/data_store_mgr.py, tests/integration/test_compat_mode.py
=> graphdepth update on remove fix

tests/conftest.py, tests/unit/post_install/test_log_vc_info.py
Just adding some tests after doing the same in https://github.com/metomi/rose/pull/2818
**Check List**
=> `log_vc_info`: add tests for when VCS not installed

cylc/flow/scripts/view.py
Fix issue from https://github.com/cylc/cylc-flow/pull/6476 causing test failures
**Check List**
=> Re-add a options.jinja2 removed in error.

cylc/flow/scheduler.py
Avoid using `'/'.split(id_)`.
**Check List**
=> convert from ids to tokens

cylc/flow/etc/syntax/cylc.lang
Utterly trivial, unless you are a user on the new VDI system...
=> update possible Gnome Versions in the cylc.lang instructions

cylc/flow/__init__.py
I've updated all 8.4.1 PRs to have a base branch of 8.4.x
=> Bump dev version

.wci.yml
Add metadata file `.wci.yml` for [WCI (Workflows Community Initiative) listing](https://workflows.community/systems/contribute)
Cylc is already listed, but adding this to our repository gives us more control of over the information, and a bit more detail.
The YAML validates OK.
(Inconsequential for Cylc functionality, but may be important for outreach).
=> Add WCI YAML metadata file.

cylc/flow/unicode_rules.py
=> Revert "🤖 Merge 8.4.x-sync into master"

cylc/flow/unicode_rules.py
Mistakenly squash-merged https://github.com/cylc/cylc-flow/pull/6672
=> Refine documentation of Validators (#6661)

cylc/flow/tui/overlay.py, tests/integration/tui/test_logs.py
See also discussion in https://github.com/cylc/cylc-flow/pull/6692
These were added to branch master separately to those fixed in 8.4.x/
=> more nonlocals

cylc/flow/cfgspec/workflow.py, cylc/flow/etc/examples/extending-workflow/index.rst, cylc/flow/scripts/set.py, cylc/flow/task_pool.py, tests/functional/hold-release/02-hold-on-spawn.t, tests/functional/hold-release/08-hold.t, tests/functional/hold-release/18-hold-cycle-globs/flow.cylc, tests/functional/hold-release/19-no-reset-prereq-on-waiting/flow.cylc, tests/functional/restart/22-hold/flow.cylc, tests/functional/runahead/06-release-update.t, tests/functional/spawn-on-demand/07-abs-triggers/flow.cylc, tests/integration/test_task_pool.py
Companion of ~~https://github.com/cylc/cylc-doc/pull/798~~ superseded by: https://github.com/cylc/cylc-doc/pull/824
Disambiguate "active" terminology.
<!--
Thanks for your contribution! Please:
* List any related issues with a "closes" or "addresses" tag.
* Add a helpful title & description.
* Complete the checklist.
=> Fix a doc ref.

tests/functional/restart/41-auto-restart-local-jobs.t
The `cylc workflow-state` call in this test wasn't properly updated after recent(ish) changes.
=> tests/f: fix restart/41

conda-environment.yml
Dependency was updated in setup.cfg but not in conda-environment.yml, probs my fault.
=> conda: bump urwid dependency

cylc/flow/scripts/reload.py
Follow-up to #6509 
Somewhat cryptic message
```console
$ cylc reload workflow --global
RequestError: Unknown argument "reloadGlobal" on field "reload" of type "Mutations".
(Workflow is running in Cylc 8.4.3)
```
```console
$ cylc reload workflow --global
InputError: The --global option is not supported by the version of Cylc running the workflow (8.4.3).
```
However this does not solve the problem that **reload is now broken in the GUI** for workflows running <8.5.0
**Check List**
=> Improve error message when trying global reload on workflow running in <8.5.0

.github/workflows/shortlog.yml, .mailmap, CONTRIBUTING.md
Mirror https://github.com/metomi/rose/pull/2911
=> Actions: run shortlog weekly

cylc/flow/cfgspec/globalcfg.py
=> Fix symlink dirs docs

tests/README.md, tests/functional/README.md
I found some [old notes](https://cylc.github.io/cylc-admin/howto/testing.md) on testing in cylc-admin!
Transferring the bits that aren't already covered (or outdated) into the test notes here.
=> more developer docs

pyproject.toml
=> Update ruff/black python target version to 3.12
