lib/cylc/tests/test_c3mro.py
lib/cylc/tests/test_exceptions.py
lib/cylc/tests/test_task_id.py
lib/cylc/tests/test_task_state_prop.py
lib/cylc/tests/test_templatevars.py
lib/cylc/tests/test_unicode_util.py

Another batch of unit tests for the cylc package. These tests simply validate current behaviour, to allow us to quickly update these files to Python 3, while also increasing the coverage in unit tests, so that we can detect regressions faster in our build process.

Increase coverage for assorted files from cylc package

---

bin/cylc-reset
lib/cylc/cfgspec/gcylc.py
lib/cylc/cfgspec/globalcfg.py
lib/cylc/cfgspec/gscan.py
lib/cylc/daemonize.py
lib/cylc/log_diagnosis.py
lib/cylc/mkdir_p.py
lib/cylc/rundb.py
lib/cylc/scheduler.py
lib/cylc/suite_srv_files_mgr.py
lib/cylc/task_events_mgr.py
lib/cylc/task_job_mgr.py
lib/parsec/upgrade.py
tests/cylc-5to6/00-simple-start-up.t
tests/deprecations/00-all.t
tests/registration/00-simple.t
tests/restart/broadcast/suite.rc
tests/restart/failed/suite.rc
tests/restart/lib/suite-runtime-restart.rc
tests/restart/multicycle/suite.rc
tests/restart/retrying/suite.rc
tests/restart/running/suite.rc
tests/restart/submit-failed/suite.rc
tests/restart/succeeded/suite.rc
tests/restart/waiting/suite.rc

Use DEBUG level for site files - users may not be able to fix them
easily. Use WARNING level for all other files to better alert users.
* See also #2781 and metomi/rose#2257.
Remove more `print` or `sys.std*.write` statements by converting them to use `logging`.
* Remove some unnecessary diagnostics.
* Remove some debug flag check in favour logging level check.
* Exit with error message instead of `print` error then `sys.exit(1)`.

Improve config deprecated upgrade log, etc

---

etc/syntax/cylc-mode.el

Found a small issue in the installation instructions, in the emacs syntax highlighting file. Plus a couple of typos.
Cheers
Bruno

Fix installation instructions for emacs syntax highlighting, and a couple of typos

---

doc/src/cylc-user-guide/cug.tex

Correct an invalid example recurrence graph section heading from **page 58 of the User Guide**, as picked up by validation as ``ERROR: Cannot process recurrence ...``. I cannot find any further instances of a similar invalid format nearby, or by searching for the pattern ``[[[ <digit>``, in the CUG.

Amend invalid documented run-once recurrence

---

lib/cylc/config.py

Hi, I was not able to find any reference to the constant `NUM_RUNAHEAD_SEQ_POINTS`. 
Looking at the Cylc User Guide, it looks like the `runahead limiting` is set to three by default, and superseded by `max active cyclepoints`, also set to three by default.
I guess it's OK to remove it then?
Cheers

Remove unused constant from config.py

---

bin/cylc-submit
lib/cylc/config.py
lib/cylc/scheduler.py

Remove a global variable that duplicates a suite configuration. Supersede #2865.

Remove cylc.flags.cycling_mode

---

lib/cylc/suite_srv_files_mgr.py
tests/registration/02-on-the-fly.t

Follow on from the various registration fixes.
We lost, then regained the ability to write a suite in the `cylc-run` directory and run it without registration.
Unfortunately the fix only covered `cylc run`, this PR returns coverage of this feature to the other Cylc sub-commands.

allow cylc commands to work with un-registered suites

---

lib/cylc/flags.py
lib/cylc/scheduler.py
lib/cylc/task_events_mgr.py
lib/cylc/task_job_mgr.py
lib/cylc/task_proxy.py
lib/cylc/task_state.py

Remove a global state variable.
* Record same info using object attributes of scheduler and tasks.
* Update to any task's `.summary['latest_message']` now correctly triggers a summary update.
Inspired by our recent discussion (#2865), I thought I'll have a go at migrating the global `cylc.flags.iflag` variable to become local object attributes. The solution is not perfect, because I am no longer able to use a single variable (without making this change a lot bigger), but it is a workable solution without compromising the current logic.

Remove cylc.flags.iflag

---

doc/src/cylc-user-guide/suiterc.tex
lib/cylc/cfgspec/suite.py
lib/cylc/job.sh
lib/cylc/job_file.py
lib/cylc/task_job_mgr.py
tests/cylc-get-config/00-simple/section2.stdout
tests/jobscript/19-exit-script.t
tests/jobscript/19-exit-script/suite.rc
tests/lib/bash/test_header

(Coded on a long-haul flight, when I couldn't sleep).
Add support for a new `exit-script` runtime setting, for scripting that is executed at the very last before a job exits ~~, whether normal exit, or fail, or kill (except SIGKILL, obviously)~~ [successfully].
Similar to the existing `err-script`, which executes on job failure.
Use case example: automatic deletion heavily used job temp directories, e.g. for jobs that don't use the work directories provided by cylc. (This is evidently a thing for direct ports from SMS at one of our main sites).
Tests added (~~expect a few test failures based on a new config item being added without adjusting the config tests - TODO~~)
~~I won't bother adding documentation until or if agreed that this change is good (or at least, not unreasonable).~~ …

job exit script

---

pytest.ini

Ignore code based on optional dependencies: GTK, PyGraphviz and EmPy. Follow up of #2766.

pytest.ini: add ignores

---

lib/cylc/task_job_mgr.py
tests/job-submission/18-check-chunking.t

Address part of #2857 
Temporary PR to check fix on codacy.

Batching job-submit tasks to avoid blocking Stdout/err pipes

---

lib/cylc/subprocpool.py
tests/events/47-long-output.t

Ensure that pipes with lots of output do not block the command.
Fully fix #2857.

subprocpool: handle long STDOUT/ERR from commands

---

lib/parsec/example/cfgspec.py
lib/parsec/example/test.py

Had fixed the examples before while working on the `setup.py` #2834 PR, but removed it as it doesn't really belong there.
Instead submitting a separated PR. After fixing it, the `test.py` prints:
```bash
title = parsec torture test
[list values]
[[integer lists]]
foo = 1..3, 3, 3, 4, 4
bar = 1..3, 3, 3, 4, 4
[[float lists]]
foo = 1.0, 2.0, 2.0, 2.0, 3.0, 4.0, 4.0
bar = 1.0, 2.0, 2.0, 2.0, 3.0, 4.0, 4.0
[[string lists]]
compulsory = one, two
one = the quick, brown fox
two = the quick, brown fox
thr = the quick, brown fox
fou = 'the, quick', 'brown , fox'
fiv = 'the #quick', 'brown #fox'
[single values]
[[integers]]
one = 1
two = 1
thr = 1
[[multiline strings with internal comments]]
one = """
the quick # or slow
brown fox # or lazy dog
"""
two = """
the quick # or slow
brown fox # or lazy …
```

Fix parsec example code

---

users.md

www.emc.ncep.noaa.gov/ is a bit weird with HTTPS, but works OK with HTTP for me. The other link is missing the protocol, so the browser tries something like cylc.github.io/cylc/forecast...

Fix a couple broken links in the site

---

lib/cylc/batch_sys_handlers/pbs_multi_cluster.py
lib/cylc/batch_sys_manager.py
lib/cylc/tests/test_pbs_multi_cluster.py

Close #2779
New batch system handler `lib/cylc/batch_sys_handlers/pbs_multi_cluster.py` docstring:
```
Support PBS clients that front heterogeneous clusters where the Job ID returned
by qsub is <id>.<server>. PBS 13 qstat and qdel need <id>.<server>@<server>.
From PBS 14, the standard cylc PBS module works ("@<server>" is not needed).
So this PBS handler writes "job_id@server" to the job status file, and appends
"@server" to Job IDs returned by qstat, to matched the stored IDs.
```
This should be an easy review: you might not be able to test it, but you can tell that it won't affect any existing cases. 
Not assigning @kinow to review as he doesn't have access to PBS.  I've tested this on an Azure cluster with PBS, set up to mimic this "multi cluster" heterogeneous environment. 
I don't …

PBS 13 "multi-cluster" support.

---

lib/cylc/task_remote_mgr.py

A user has sent us a report that on closing the temporary file, the attempted `os.unlink` issued by the `tempfile` module on the temporary file was taking down the suite with `OSError: [Errno 2] No such file or directory`. Occurs on a platform that we have to support. However, I am still not sure how to repeat this in general.

remote-init: fix bad unlink taking down the suite

---

lib/cylc/cfgspec/globalcfg.py
lib/cylc/log_diagnosis.py
lib/cylc/rundb.py
lib/cylc/suite_srv_files_mgr.py
lib/cylc/task_events_mgr.py
lib/cylc/task_job_mgr.py
lib/cylc/task_state.py

I think the `cylc.flags` ones are from #2865 & #2871. The other `sys` imports must have crawled somewhere over the last changes.
Not removing the unused `LOG`, as even though they are not used, I remember disabling one somewhere some time ago, and logging/debug stopped working. I think that's by design.

Remove a few unused imports

---

doc/src/cylc-user-guide/cug.tex

A PR, but also a question. Should it be `rose` in the instructions for setting up Apache httpd + Cylc Review, or should it be `cylc` now?

Fix WSGI docs (s/rose/cylc)

---

CHANGES.md

@cylc/core - anyone want to take a quick look at this, to see if I missed anything important?

Update change log for 7.8 release

---

lib/cylc/hostuserutil.py
lib/cylc/tests/test_hostuserutil.py

On failure of `socket.gethostbyname_ex`, add bad host name to error.
Fix #2875.

cylc.hostuserutil: get_fqdn_by_host: include bad host name in error

---

lib/cylc/time_parser.py
tests/recurrence-min/00-basic/suite.rc

In the cylc documentation there are spaces between the arguments to the `min()` function (at least when you copy the examples from the PDF).
These spaces result in cryptic error messages. This PR permits arbitrary whitespace between the parenthesis as well as between the arguments and the argument separator.
*I've put this against "soon" to make the release easier, can promote if reviewed in time?*

graphing: spaces in min expressions

---

doc/src/cylc-user-guide/suiterc.tex
lib/cylc/config.py
lib/cylc/scheduler.py
lib/cylc/suite_db_mgr.py
lib/cylc/suite_events.py
lib/cylc/task_events_mgr.py
lib/cylc/task_remote_mgr.py
tests/events/08-task-event-handler-retry.t
tests/events/08-task-event-handler-retry/suite.rc
tests/events/20-suite-event-handlers.t
tests/events/20-suite-event-handlers/suite.rc

Support suite UUID in suite/task event handlers

---

lib/cylc/task_events_mgr.py
lib/cylc/tests/test_task_events_mgr.py

From https://groups.google.com/forum/#!topic/cylc/dP2I1Gxqi20. Started testing it, and realized that I had copied the wrong command (`rsync -v -rltgoD --chmod=Du=rwx,Dgo=rx,Fu=rw, Fgo=r` it had a space after the last `F`).
Running locally it would exit with an error. But when I executed the job for Cylc with a remote task on another PBS server, it did not complain. Reason is that the `job.out` exists, and the task succeeded. However, it does not mean the log retrieval command succeeded as well.
Output without this patch: 
```bash
2018-12-22T04:24:57Z INFO - [a.1] -submit-num=1, owner@host=pbs
2018-12-22T04:24:58Z INFO - [a.1] -(current:ready) submitted at 2018-12-22T04:24:58Z
2018-12-22T04:24:58Z INFO - [a.1] -health check settings: submission timeout=None
2018-12-22T04:24:59Z INFO - …
```

Log when the log retrieval command exited with error code

---

lib/cylc/suite_srv_files_mgr.py
lib/cylc/tests/test_suite_srv_files_mgr.py
tests/registration/00-simple.t

Rose suites that were installed prior to cylc-7.8.0 are unable to start up due to `cylc register` command failing on e.g. `cylc register foo /home/matt/cylc-run/foo`.
Restore prior behaviour when run directory is the source directory - create source symbolic link to point to `..` - this also allows the suite run directory to move without causing issues. E.g. `mv ~/cylc-run/foo ~/cylc-run/foo-new` would cause issue in 7.8.0, because `~/cylc-run/foo-new/.service/source` would be pointing to ``~/cylc-run/foo`.

register: fix run directory == source directory

---

lib/cylc/loggingutil.py
lib/cylc/scheduler.py
lib/cylc/tests/test_loggingutil.py
lib/cylc/tests/test_scheduler.py

In the event of a filesystem issue Cylc will attempt to shutdown and in the process it will try to close the logging handlers. This results in an `IOError` resulting in traceback which logging attempts to log, which will fail due to the filesystem issue resulting in traceback which logging attempts to log and so on so forth.
Example traceback:
```
File "cylc/bin/cylc-run", line 25, in <module>
main(is_restart=False)
File "cylc/lib/cylc/scheduler_cli.py", line 134, in main
scheduler.start()
File "cylc/lib/cylc/scheduler.py", line 278, in start
self.close_logs()
File "cylc/lib/cylc/scheduler.py", line 291, in close_logs
handler.close()
File "/usr/lib64/python2.6/logging/__init__.py", line 844, in close
self.stream.close()
IOError: [Errno 122] Disk quota exceeded
Traceback (most recent call …
```

loggingutil: fix infinite loop on IOError

---

doc/src/cylc-user-guide/README
doc/src/cylc-user-guide/cug.tex
doc/src/cylc-user-guide/job-host-2.tex
doc/src/cylc-user-guide/siterc.tex
doc/src/cylc-user-guide/suiterc.tex
doc/src/suite-design-guide/portable-suites.tex

Few typos found in documentation. Saw the typo that @lhuggett fixed in a pull request (intial I think) and decided to open some of the tex files with IDE and with `mwic`, and spotted a few ones that could be fixed.
I think this would have - if merged - to be included in @sadielbartholomew #2910 PR (if the typo is still there?).
Cheers
Bruno

Typos in documentation

---

doc/src/cylc-user-guide/cug.tex

Close #2896 
Fix several errors is our new-ish Cylc Review documentation:

Fix cylc review documentation.

---

bin/cylc-validate
lib/cylc/loggingutil.py
tests/deprecations/00-all.t
tests/validate/04-builtin-suites.t
tests/validate/67-task-proxy-sequence-bounds-err.t

* Changed an error to a warning in cylc validate as it would drive users nuts.
* Removed timestamps from `cylc validate` log output (unless in debug mode). *Contriversial?*
*Background: "Out of bounds error" refers to recurrences which lie before the `initial cycle point`.*
In #2738 (7.8.0) we added nicer handling of exceptions in `cylc validate` which can result from out of bounds recurrences in some niche cases. `cylc validate` now fails for out of bounds sequences when running in `--strict` mode for *all* cases (not just the ones resulting in traceback).
There are some cases where it might be sensible to hard code behaviour for certain cycle points up front allowing users choice of initial and final cycle points.
writing suites with out of bounds sequences might make some sort of …

Out of bounds warning

---

lib/cylc/option_parsers.py
lib/cylc/subprocpool.py
lib/cylc/task_job_mgr.py
tests/job-submission/19-chatty.t
tests/job-submission/19-chatty/bin/talkingnonsense
tests/job-submission/19-chatty/suite.rc

Most likely :bug: introduced by #2876. Sorry.
Read each ready pipe once after each poll. Poll again after read.
If `cylc jobs-submit` returns with incomplete summary for all expected
tasks, report tasks that do not have a summary line as submission
failed.
Fix #2929.

Fix subprocpool pipe polling

---

.travis.yml

Adding a `sed` command to our `.travis.yml` to use an absolute directory for the coverage data file. This way when processes are forked, they will use the same location, instead of a location relative to their working directory.
This should increase the coverage of the project, and cover files such as `daemonize.py`.
Bruno

Set location of coverage file in Travis

---

lib/cylc/host_appointer.py

On SSH call with login shell, sites/users may have logic in profile
scripts writing to STDOUT. This causes the logic that expects JSON to
fail to load the output. This change attempts to drop all lines before
it finds the first open curly bracket `{`, which should be good enough
to denote the start of JSON content in most cases.
Close #2897. (Need to back port to to 7.8.2.)

host appointer: improve handling of unexpected out

---

lib/cylc/suite_srv_files_mgr.py

On file system such as an NFS mounted file system, we may have a delay
before the file becomes visible from other process running on other
host. We already have a 1st fsync to ensure that the data of the contact
file is written to disk. This change adds a 2nd fsync to ensure that the
file metadata of the contact file is written as well - by doing an fsync
on its directory.
(The issue is causing `rose suite-run` to fail to launch `cylc gui` after calling `cylc run` successfully to start up a suite.)
(Need to back port to 7.8.2.)

contact file creation: fsync parent directory

---

etc/syntax/reference-files/suite.rc
etc/syntax/reference-files/suite_empy.rc
etc/syntax/reference-files/suite_jinja2.rc

Addresses #2915 
Add some example Cylc files for testing lexers, the numbering matches the table in #2752.

syntax: add reference syntax files for testing lexers

---

bin/cylc-cycle-point
bin/cylc-documentation
bin/cylc-get-gui-config
bin/cylc-get-site-config
lib/cylc/option_parsers.py
lib/parsec/__init__.py

So, cylc logger will always have a handler. CylcOptionParser will ensure
that commands will have a valid logging handler. Scheduler will do
likewise for daemonized suites.
Use CylcOptionParser for all remaining user commands:
* cylc cycle-point
* cylc documentation
* cylc get-gui-config
* cylc get-site-config
This ensures that these commands will have logging handlers set.
Fix #2940.

Give logger a null handler on start up

---

CHANGES.md

I've just noticed that the version ``7.8.1`` entry in the change log contains links to PRs/Issues which are all broken due to a consistent foreign ``#`` symbol. This fixes all links, as from a ``grep`` on ``/#`` there are no further identical instances across the entire change log.
[Trivial hence lone reviewer sufficient.]

Fix broken links for cylc-7.8.1 change log entry

---

doc/src/conf.py

Adjust the link colours to be higher contrast to aid with visibility.
Just deleting the colour settings results in using the values from the "classic" theme which are hard to read on the white background of the nav bar. As such have explicitly used colours based on what appears to once have been the "default" values for links and visited links. 
Built in my homespace and readable in my Firefox browser.

Use higher contrast link colours.

---

doc/src/suite-config.rst
doc/src/tutorial.rst
etc/examples/tutorial/oneoff/jinja2/suite.rc

Close #2953 & fix numerous long-term errors in that section (``7.26.``) & a similar section (``9.6.4.``) of the docs.
Most of the context is explained in https://github.com/cylc/cylc/issues/2953#issuecomment-463327389, but for further clarification on changes to the ``9.6.4.`` example suite, it:
* was at some point (not during the Sphinx conversion!) hard-coded into the docs instead of included from the ``etc/`` directory as with other example suites, & had not been updated in line with changes, so notably contained an obsolete ``[[[0]]]`` recurrence expression;
* was referred to as ``foo`` despite not being assigned that name.

docs: fix jinja2 variable setting example suites

---

Makefile

Duplicate for the feature branch of #2951, to close #2950, where changes to ``site-user-config-ref.rst`` are omitted to copy as they apply to amended text that has is not (yet, depending on merge order of another PR) been changed as required in ``7.8.x``.

docs: amend makefile command; address warning

---

lib/cylc/cylc-review/template/cycles.html
lib/cylc/cylc-review/template/job-entry.html
lib/cylc/cylc-review/template/suites.html
lib/cylc/cylc-review/template/taskjobs.html
lib/cylc/cylc-review/template/view.html
lib/cylc/review.py

I have noticed a security flaw in the Cylc Review service, originating from its Rose Bush origin, which I raised & which has been discussed offline. Naturally, I will not provide details for recreation here (publicly) but I will email details across.
For general context it concerns a specific route for code injection which I demonstrated can execute malicious JavaScript to e.g. redirect the entire service upon viewing of any listing including one exploitative suite.
Patch this known vulnerability:
* autoescape HTML & XML markup [in the Jinja2 templates](http://jinja.pocoo.org/docs/2.10/api/#autoescaping);
* use the Jinja2 ``safe`` filter to:
* (now on a case-by-case basis, as required) unescape ampersands ``&amp;`` to ``&`` to ensure URLs containing queries are still valid;
* ensure the …

review: security patch to prevent code injection

---

lib/cylc/cfgspec/gcylc.py

Bug causing failure at GUI start-up if `gcylc.rc` has illegal config items, on attempt to log the error message.
PR to 7.8.x only, as the GUI is getting nuked on master.
(Should be a quick review!)

Fix missing import in gcylc cfgspec.

---

.gitignore

I think we need to ignore the directory with the generated single page for sphinx? It appeared in my git changes are `cylc make-docs`.

Ignore sphinx built-sphinx-single directory

---

bin/cylc-get-host-metrics
etc/dev-suites/xtrigger/kafka/consumer/lib/python/cylc_kafka_consumer.py
etc/dev-suites/xtrigger/kafka/producer/bin/cylc_kafka_producer.py
lib/cylc/cycling/util.py
lib/cylc/review.py
lib/cylc/ws.py
lib/cylc/xtrigger_mgr.py
lib/cylc/xtriggers/echo.py
lib/cylc/xtriggers/suite_state.py
lib/cylc/xtriggers/wall_clock.py
lib/cylc/xtriggers/xrandom.py
lib/parsec/empysupport.py
tests/xtriggers/02-persistence/faker_fail.py
tests/xtriggers/02-persistence/faker_succ.py

Fix a few `#!/usr/bin/env python(2)` lines.  For 7.8.x.
One review should do.
(My own env currently defaults to Python 3).

Fix missing python2 hash-bang lines.

---

bin/cylc-gui

Fix for #2898 , in the 7.8.x branch (see [previous pull request for more](https://github.com/cylc/cylc/pull/2985)).
Encloses GTK main loop in a try/catch, to wait for `KeyboardInterrupt` and quit nicely.
Another workaround is to use `CTRL + \`, which sends `SIGKILL`, but not a well known short-cut (nor really nice/polite to go `SIGKILL`ing processes around :grimacing: 
Tested locally from `master` branch, but alas going with no unit/functional tests, so Codecov won't be happy.
Bruno

Fix issue #2898: close app nicely on CTRL+C

---

lib/cylc/task_events_mgr.py

Use calculated event_time instead of new current_time call

---

lib/cylc/config.py
tests/cli/00-cycle-points.t
tests/cli/00-cycle-points/suite.rc
tests/cyclers/28-implicit-disallowed.t
tests/events/36-task-event-bad-custom-template.t
tests/inheritance/01-circular.t
tests/validate/10-bad-recurrence.t
tests/validate/17-fail-old-syntax-6.t
tests/validate/37-clock-trigger-task-not-defined.t
tests/validate/64-circular.t
tests/validate/65-bad-task-event-handler-tmpl.t

Response to user request for more informative feedback in the event that a user misses a `-s` flag when attempting to run a non-cycling suite e.g:
```console
$ cylc run mysuite FOO=BAR
...
Conflicting syntax: 'integer vs cycling suite: are you missing a [dependencies][[[R1]]] section?'
```
It's difficult to provide suggestive feedback as it is not clear what the user's intent was. Also there are other ways we could end up with a malformed `=` separated pair on the CLI.
```console
$ cylc run mysuite mode=simulation
```

config: more helpful error message on cli misuse

---

CONTRIBUTING.md
doc/src/suite-config.rst
lib/cylc/config.py
lib/cylc/scheduler.py

**Problem**
In order to have information available in the environment for template filters (Jinja2 ...etc), it needs to be exported before parsing/processing the suite.rc. For example I may want to reference the installed or source directory:
```
#!/usr/bin/env python
import os
def get_file_items(ITEMS):
suiterun = os.environ['CYLC_SUITE_RUN_DIR']
infile = open(os.path.join(suiterun,'dat','items.dat'))
ITEMS = [line.rstrip('\n') for line in infile]
return ITEMS.sort()
```
With the run path not always being the same as the def/source path, and PWD not being consistent anyway, the alternative is to hard code this somewhere before running (or create some awkward workaround?).
The suite context is available locally after startup (on reload).
A test suite with the above (and below) filter …

Make suite context available before config parsing

---

.travis.yml
CHANGES.md
bin/cylc-cycle-point
bin/cylc-documentation
bin/cylc-get-gui-config
bin/cylc-get-site-config
etc/syntax/reference-files/suite.rc
etc/syntax/reference-files/suite_empy.rc
etc/syntax/reference-files/suite_jinja2.rc
lib/cylc/host_appointer.py
lib/cylc/option_parsers.py
lib/cylc/suite_srv_files_mgr.py
lib/parsec/__init__.py

Cherry picked: #2916, #2937, #2941, #2943, #2944.

7.8.x patch 1

---

tox.ini

In #3007, @ColemanTom reported that running `pycodestyle` against his branch reported false positives for files within the `.git` directory.
I thought that was funny, and decided to try, and indeed creating a branch with `git checkout -b delete.py` and running `pycodestyle` results in some 4 or so lines with incorrect values.
The reason for that is that [pycodestyle contains a list of default exclusions](https://github.com/PyCQA/pycodestyle/blob/96d2db0fa17cc41ae45bcc6fa5ca72e6f712d1bf/pycodestyle.py#L83), which includes `.git`.
But in our `tox.ini` file, we specify the list of exclusions to cover only `jinja2` and `markupsafe` folders (as they are imported modules, it makes sense to exclude them).
The issue happens as we have replaced the `.git` by our values. The original exclusion list …

Fix pycodestyle exclusion list (add from their default)

---

bin/cylc-check-versions
bin/cylc-submit
lib/cylc/scheduler.py
lib/cylc/subprocctx.py
lib/cylc/subprocpool.py
lib/cylc/task_job_mgr.py
lib/cylc/task_remote_mgr.py
lib/cylc/tests/test_subprocpool.py

Users are experiencing issues on one of the platforms we deploy Cylc
where remote submission fails intermittently with a file not found error
complaining that a temporary file cannot be found. (The file is used for
piping service files as a tar archive via STDIN (to the SSH) command.) This should not
be the case, as the temporary file handle should still be referenced,
but clearly there was an issue.
In this change, we pass the temporary file handle directly instead of
passing the name of the temporary file to the process pool. This appears
to fix the issue. (Note: Before #2590, we were unable to pass the file
handle because the context needs to be serialised for the
multiprocessing.Pool. This is no longer a requirement in our own
subprocess pool, so it is now safe to pass the handle.) …

task remote init: fix strange tempfile issue

---

CONTRIBUTING.md
lib/cylc/job_file.py
lib/cylc/tests/test_job_file.py

Tests for part of job_file.py. It's failing in my build environment because pycodestyle is looking in the .git directory (perhaps there is a bug in the travis pycodestyle setup?) because my branch name was originally `<...>.py`, as per below. So I'm going to rely on the output from the official tests in the pull request.
```
./.git/logs/refs/remotes/origin/add_test_for_job_file.py:1:80: E501 line too long (156 > 79 characters)
./.git/logs/refs/remotes/origin/add_test_for_job_file.py:1:99: E225 missing whitespace around operator
./.git/logs/refs/remotes/origin/add_test_for_job_file.py:1:124: E225 missing whitespace around operator
./.git/logs/refs/remotes/origin/add_test_for_job_file.py:1:138: E225 missing whitespace around operator …
```

Add tests for quoting of tilde expressions in environment section

---

lib/cylc/task_job_mgr.py

Cylc8 variant of #3009
This addresses traceback we have seen (on 7.8.1), probably resulting from a sickly system.
```python
File "/net/home/h03/fcm/cylc-7.8.1/lib/cylc/task_job_mgr.py", line 509, in _manip_task_jobs_callback
del bad_tasks[(point, name, submit_num)]
KeyError: ...
```

task_job_mgr: except KeyError

---

doc/src/external-triggers.rst

Hi,
I removed the `dev-suites` in https://github.com/cylc/cylc/pull/3006/commits/479eaa27c38ae333d02becfbf39326d50ac30625, but forgot to properly search for other occurrences.
While following up some discussion on Riot about issues in the External Triggers documentation, found this one while running `cylc make-docs` from `master`.
I do not believe it should be backported to 7.8. And it is a simple find-replace for `dev-suites` by `examples`.

Fix dev-suites reference in docs (now in examples)

---

bin/cylc-check-versions
bin/cylc-submit
lib/cylc/cylc-review/template/cycles.html
lib/cylc/cylc-review/template/job-entry.html
lib/cylc/cylc-review/template/suites.html
lib/cylc/cylc-review/template/taskjobs.html
lib/cylc/cylc-review/template/view.html
lib/cylc/review.py
lib/cylc/scheduler.py
lib/cylc/subprocctx.py
lib/cylc/subprocpool.py
lib/cylc/task_job_mgr.py
lib/cylc/task_remote_mgr.py
lib/cylc/tests/test_subprocpool.py

7.8.x patch2

---

bin/cylc-check-software

cylc-8 companion of #3021 
(@sadielbartholomew - same question applies re `cylc check-software`).

Removed LaTeX support from check-software.

---

tests/validate/04-builtin-suites.t

Sorry, missed this one after removing `dev-suites`. Checked the source directory, but not the tests. Found it as it raises a warning, without failing the test, complaining about not being able to locate the `dev-suites` folder.
Did a `grep` and found no more `dev-suites`, so this should be the last one. Executed the test locally with `cylc test-battery tests/validate/04-builtin-suites.t` with no errors.
Probably 1 review should be enough?

Remove dev-suites from tests

---

lib/cylc/conditional_simplifier.py
lib/cylc/tests/test_conditional_simplifier.py

I think this one slipped in during the Python3 conversion. The real issue was in the lack of a test to cover this code.
Added a test that fails with previous code, as calling `reverse()` on the result of `range` (some view/iterator, not a list) results in an error. This could cause parsing suites to fail.
Should not be backported to 7.x, as this happens only with Py3.

Convert range to list so that we can use reduce

---

lib/parsec/README.md

Another one of those small pull requests for typos. This one has just one for parsec. One review should be enough?

Trivial typo in parsec README

---

lib/cylc/batch_sys_handlers/loadleveler.py
lib/cylc/batch_sys_handlers/lsf.py
lib/cylc/batch_sys_handlers/moab.py
lib/cylc/batch_sys_handlers/pbs.py
lib/cylc/batch_sys_handlers/sge.py
lib/cylc/cfgspec/suite.py
lib/cylc/cfgvalidate.py
lib/cylc/network/__init__.py
lib/cylc/network/scan.py
lib/parsec/fileparse.py
lib/parsec/validate.py

Fixing docstrings where single double or single quotes were used instead of triple quotes, and also added some parameters that were missing from methods documentation.
I do not thing we need this for Cylc 7.8.x.

Minor improvements for docstrings

---

lib/cylc/xtriggers/xrandom.py

Fix #3039 
Prevents `ZeroDivisionError` in `xrandom`. Adds docstrings and doctests (thought a unittest for it wouldn't be really necessary as it's an example only? We were running doctests anyway for coverage...)
Cheers
Bruno

Add check for zero to xrandom

---

lib/cylc/subprocpool.py
lib/cylc/task_remote_mgr.py
lib/cylc/tests/test_subprocpool.py

Use SpooledTemporaryFile to avoid using the file system - should in theory eliminate the reliance on TMPDIR.
Note: The biggest usage of this is remote job submission - with up to 100 job files being sent via STDIN to the remote host per command. A job file is typically about 1-2K in size, so even 100 of them should only be ~200K. In the default configuration where we have a pool of 4 sub-processes, this should still be less than 1M. Unlikely to be a big issue for a modern computing host?
Fix #2999.

Subprocpool: use SpooledTemporaryFile instead of TemporaryFile

---

bin/cylc-check-software

Not happening any time soon, as we don't have a dependency to `OTHER` tool in `check-software`, but only to `PY` tools for now.
But if we had one, then it would crash due to an array access moved to next line. The code is still perfectly fine, so in theory no syntax error. Except that our intention here is to access one of the elements of the tuple returned by process `communicate()` method.
Tested locally by adding
```diff
diff --git a/bin/cylc-check-software b/bin/cylc-check-software
index 4d8843d43..ff2bfb878 100755
--- a/bin/cylc-check-software
+++ b/bin/cylc-check-software
@@ -54,6 +54,8 @@ req_py_ver_range = ((3,6),)
opt_spec = {
'EmPy': [None, 'TEMPLATING', 'PY'],
'sphinx': [(1, 5, 3), 'HTMLDOCS', 'PY'],
+    'graphviz': [None, 'TEMPLATING', 'OTHER',
+            (['dot'], '-V', …
```

Fix syntax for array access in cylc check-software

---

lib/cylc/loggingutil.py
lib/cylc/scheduler.py
tests/shutdown/19-log-reference.t

Not sure if it was better to modify to read binary, but we are doing `line in array_of_strings`... so would have to modify that array too I think. I thought this would be the simplest way to fix it.
Added a functional test (my very first!) for this case of `scheduler#shutodown` when `--reference-log` is used :+1: 
Not applicable to 7.8.x
Cheers
Bruno

Fix scheduler#shutdown when reference-log option is used

---

bin/cylc-get-host-metrics
bin/cylc-search
lib/cylc/cfgvalidate.py
lib/cylc/cycling/iso8601.py
lib/cylc/graph_parser.py
lib/cylc/param_expand.py
lib/cylc/task_remote_mgr.py
lib/cylc/time_parser.py
lib/parsec/fileparse.py
lib/parsec/include.py
lib/parsec/validate.py

When using `[...]` in regexes, I believe we do not need to escape `.`, `:`, `)`, `<`, `>`, etc. As far as I know, we need to escape only the closing `]`, and the normal sequences like `\n`, `\r`, `\t`.
Python regex engine does the job of escaping these character anyway, but being regexes not always the fastest option, perhaps removing unnecessary escapes is a good idea?
Also included one more change (second commit) to use ```([`\])``` instead of ```(`|\)```. For two characters it makes no difference performance-wise. With more characters ```[`\]``` would probably be faster. But it's still easier to read I think?
Low priority, for Cylc 8 or later, without backport to Cylc 7 (I do not think it's necessary for the 7.8.x release series).
Cheers
Bruno

Simplify regexes

---

lib/cylc/config.py
lib/cylc/scheduler.py
lib/cylc/xtrigger_mgr.py
tests/validate/04-builtin-suites.t

As described in this issue:
https://github.com/cylc/cylc/issues/3054
**Problem**
The suite freezes completely when a xtrigger is declared with a non-existent function (i.e. a misspell of `wall_clock` as `wallclock`).. This can be devastating, as the only course of action is to kill the suite program/process via the OS...
**Solution**
This change will:
- Catch non-existent function errors on suite configure, by attempting to load each xtrigger function before passing it to the manager.
- Catch the Type error exception causing the suite to freeze (in case the python scripts of a running suite are deleted/moved)
Given the following suite section:
```
[[xtriggers]]
oopsie = not_a_function()
clock_pt1h = wall_clock(offset=PT1H)
jin_state = suite_state(jin, baz, %(point)s, …
```

Fix suite freeze on non-existent xtrigger

---

.codacy.yml
lib/cylc/config.py
lib/cylc/tests/test_config.py
lib/cylc/tests/test_subprocpool.py

@dwsutherland, @hjoliver here are the unit tests for `get_func`, and that part of the `SuiteConfig` code that checks if the Xtrigger function is a callable.
One of the final unit tests was to check what would happen if we got an `AttributeError`, instead of an `ImportError`/`ModuleNotFoundError`. That is possible when you have a Xtrigger file `cylc.py` but without the `cylc()` function (I believe xtrigger module and function name are expected to match).
@dwsutherland I reckon this `AttributeError` would also cause the suite to hang? That error was propagated, instead of a `SuiteConfigError`, so I included a commit in this pull request to catch that error as well.
Now wait for Travis. Took a bit longer because decided to write using pytest instead of unittest the new test for `cylc.config` …

Fix bug when an AttributeError is raised, and add unit tests for xtrigger

---

lib/cylc/config.py
lib/cylc/scheduler.py
lib/cylc/xtrigger_mgr.py
tests/validate/04-builtin-suites.t

Port of [pull/3056](https://github.com/cylc/cylc/pull/3056)

Fix suite freeze on non-existent xtrigger - 7.8.x

---

lib/cylc/config.py
lib/cylc/tests/test_config.py
lib/cylc/tests/test_subprocpool.py

Backport for pr #3060 
NB: this is slightly different than #3060 in the tests, as I used Python 3.6 features, and pytest, which are not supported in our 7.8.x branch with Python 2.
The number of commits is the same as #3060, because I dropped the `codacy.yml` commit, as that file is not required, and added one commit to adjust the test code. So better to wait for Travis!

7.8.x backport pr 3060

---

.travis.yml
bin/cylc-check-software
doc/src/installation.rst

python: make 3.7 the min version for Cylc

---

doc/src/appendices/suiterc-config-ref.rst

init, env, pre, post, err, exit, and script have been adjusted
to be displayed in the docs in chronological order.
This targets 7.8.x

Update docs for order of scripts sections

---

doc/src/appendices/suiterc-config-ref.rst

I noticed that the `exit-script` section in the docs referred to itself rather than `err-script`, so this just adjusts that.
I did contemplate another adjustment. In the order of the docs, it has `exit-script` above `err-script`. But in the `See also ...` parts for these script sections, it lists `err-script` before `exit-script`. I'm not sure what the ordering in here is meant to be, but I would suggest that it should be order of execution really for both - it makes the documentation more intuitive.

minor fix to docs about exit-script

---

.travis/install.sh
INSTALL.md
bin/cylc-check-software
doc/src/global-site-user-conf.rst
doc/src/installation.rst
etc/global.rc.eg
usr/bin/cylc

I found a few remaining references to the old User Guide build.
Very simple - see the commit logs for specifics.  Also updated INSTALL.md to look like the one on master (removing actual `cylc check-sofware` output, as that is prone to getting out of date).

Remove latex refs 7

---

lib/cylc/network/client.py

See: https://github.com/cylc/cylc/pull/3004#discussion_r266685170

zmq: use global client context

---

lib/cylc/cfgspec/globalcfg.py

While looking at an issue in Codacy for #3060 , I noted that there was another issue about these two unused functions/lambdas in `globalcfg`. Not sure if they are used anywhere. IDE pointing as not used, and `grep` found only `use_ssh` for `optparse`, which I think is unrelated.
Sending PR with low priority, to see if Travis and Codacy are happy with the change, and so others can review and perhaps chime in in case this is some code that needs to be kept in Cylc 8. Not sure if it needs to be backported to Cylc 7.8?

Remove globalcfg add_bin_dir and use_ssh, codacy issue about unused code

---

bin/cylc-get-directory

Never used this command (also not sure if will be kept in Cylc 8, e.g. #2972), and it works in my local environment. But I suspect if `remrun` returns true, it will probably raise `ImportError` or `ModuleNotFoundError`, as the `import sys` is after the call to `sys.exit`.

Fix import issues in cylc get-directory

---

bin/cylc-jobscript
bin/cylc-test-battery
lib/cylc/job.sh

Revert a few lines of #3068
In several places: remove outer quotes that incorrectly turn a whole bunch of args into a single arg containing spaces.
@kinow - one review will do, since functional tests currently broken by the bug
@oliver-sanders can take a look afterwards to check that I've done the right thing...

Fix recent shellcheck-inspired quoting errors.

---

bin/cylc-search

```
cylc search /home/kinow/cylc-run/five/share foo*
```
Works fine. But using another directory, the previous version would print usage and exit with a non zero exit code. Current version in `master` is broken.
```
$ cylc search /home/kinow/cylc-run/five/share foo*
File "/home/kinow/Development/python/workspace/cylc/venv/bin/cylc-search", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/kinow/Development/python/workspace/cylc/bin/cylc-search", line 196, in <module>
main()
File "/home/kinow/Development/python/workspace/cylc/lib/cylc/terminal.py", line 65, in wrapper
function(*args, **kwargs)
File "/home/kinow/Development/python/workspace/cylc/bin/cylc-search", line 94, in main
parser.error("File not found: " + suiterc)
NameError: …
```

Fix cylc-search for directories without suite.rc

---

bin/cylc-test-battery

Part of #3046.
To run `prove` with the `--timer` option. From their help page:
```
--timer           Print elapsed time after each test.
```
That should give us an idea of how long the tests are taking to run. Should increase a bit the total execution time, but it shouldn't be a considerable increase.

Run prove with --timer

---

lib/cylc/network/server.py

Fix #3079 
- Adds docstrings fixing warnings that appeared in the IDE.
- Fixes a few typos
- Defines the instance `context` in the constructor

Docstrings and minor fixes server

---

lib/cylc/cylc-review/static/js/cylc-review.js
lib/cylc/cylc-review/template/job-entry.html
lib/cylc/cylc-review/template/pager.html
lib/cylc/cylc-review/template/taskjobs.html
lib/cylc/review.py
lib/cylc/review_dao.py
tests/cylc-review/00-basic.t
tests/cylc-review/10-jobs-task-status.t

We were [joining](https://www.w3schools.com/sql/sql_join.asp) the tasks and jobs tables. In SQL terms `JOIN` means intersection. As waiting tasks do not have jobs they were excluded in the intersection. I've changed the `JOIN` to `LEFT JOIN` to include tasks with out jobs.

review: fix waiting tasks

---

tests/job-kill/00-local.t
tests/job-kill/00-local/reference.log
tests/job-kill/00-local/suite.rc

Extend an existing `cylc kill`functional test to cover the "kill all active tasks" use case.
cylc-8 counterpart of #3100 (on master, the functionality already works, but the test coverage was lacking).

Add kill all to functional tests.

---

lib/cylc/network/httpserver.py
tests/job-kill/00-local.t
tests/job-kill/00-local/reference.log
tests/job-kill/00-local/suite.rc

Close #3094 
`cylc kill SUITE` should kill all active tasks
Extended an existing functional test to cover this.

Cylc kill fix

---

tests/cyclers/00-daily.t

This fixes the bug noted here: https://github.com/cylc/cylc/issues/3098#issuecomment-481505878
(A test fails if `global-tests.rc` configures a non-standard run directory but leaves `work directory` in the default location).
Posting a PR since I looked at the problem and fixed this test. (And same on master next).
NOTE: there are almost certainly other tests that have a similar problem (assuming standard location of run or work directory instead of querying the relevant config, or assuming that the work directory is under the run directory.  However, IMO we shouldn't blow any time on this now ... it is unlikely that anyone needs to run the test battery with different run and work locations, and we have "bigger fish to fry".

Fix work loc assumption in a test.

---

lib/parsec/jinja2support.py

Close #3109 
(Apparently the right thing to do is insert new `sys.path` elements at the 2nd position, not the 1st - because the 1st element is supposed to contain the location of the current script).

Prepend custom Jinja2 paths.

---

lib/cylc/config.py
lib/cylc/graphing.py
lib/cylc/tests/test_graphing.py

Address #2965 
... (may or may not close the issue, depending)
1) consistent use of desktop theme foreground and background colors:
- always use desktop theme foreground for default node boundary, edge, and font color
- always use desktop theme background for default node fill color
- (if users set non-default colors for some attributes, it is up to them to manage contrast with any remaining default colors still being used). 
2) fix `default node attributes`
- now it has exactly the same effect as styling root (and can be overridden by styling root).

Graph color fixes

---

CHANGES.md
INSTALL.md
README.md
bin/cylc-test-battery
doc/src/suite-design-guide/sdg-introduction.rst
lib/cylc/cfgspec/globalcfg.py

Found broken issues in the README, but not because of the project rename. Then started looking for other occurrences of `/cylc/`. The Changelog works without the changes... with this change it just avoids the HTTP redirect, but happy to remove it.
I also changed, then reset the contents, of the joss-paper metadata, as I was not sure if it would be OK to change those files :+1:

Fix links in README and other files

---

CHANGES.md

Small issue. While backporting #3124 to `7.8.x`, there was a cherry-pick merge conflict that made me open GitHub UI to really look at the files.
Took me a moment to understand why this text would be different in `master` and `7.8.x`, then I realized that this text was probably renamed by accident as we fixed the shebangs during the port Py2 to Py3.
But just for the sake of correctness, a quick PR to adjust the text. One review enough?

Fix text in changelog

---

setup.cfg

`python3 setup.py bdist_wheel` was giving us `dist/cylc-8.0a0-py2-py3-none-any.whl`. It now gives `dist/cylc-8.0a0-py3-none-any.whl`

setup.cfg: remove py2 compat for wheel

---

SECURITY.md

Master companion of #3128 - same, but without the Jinja2 CVE note.

Added SECURITY.md (master)

---

CHANGES.md
SECURITY.md

Close https://github.com/cylc/cylc-admin/issues/11
Based on https://github.com/standard/standard/blob/master/SECURITY.md
For 7.8.x adds a note on the recent Jinja2 CVE and why it is not an issue for Cylc.
@kinow - do you think this is the appropriate place for such "alerts"?

Add SECURITY.md (7.8.x)

---

.gitignore

We need now to include the egg info file with the new module name to the gitignore. One review should do I think?
Cheers
Bruno

Add cylc-flow egg info to gitignore after module rename

---

lib/cylc/cylc-review/template/broadcast-events.html
lib/cylc/cylc-review/template/broadcast-states.html
lib/cylc/cylc-review/template/cycles.html
lib/cylc/cylc-review/template/job-entry.html
lib/cylc/cylc-review/template/pager.html
lib/cylc/cylc-review/template/search-form.html
lib/cylc/cylc-review/template/suite-base.html
lib/cylc/cylc-review/template/suites.html
lib/cylc/cylc-review/template/taskjobs.html
lib/cylc/cylc-review/template/view-mode.html
lib/cylc/cylc-review/template/view.html

Close #3121 
Close #3119 
Use Jinja2's `urlencode` filter instead of replacing characters individually. Tested with Cylc suites "cylc1" and "%63ylc1". Links working as below.
EDIT: added another close #3119 as it appears to fix both issues :+1:

cylc review: URL encode links

---

doc/src/appendices/suiterc-config-ref.rst
doc/src/suite-config.rst
doc/src/suite-name-reg.rst
doc/src/tutorial.rst

For task names with including one or more ``+`` characters (which I anticipate could be quite common to include date-time records e.g. ``mytask_T+030`` etc.), clicking the hyperlinked name under the "task name" column of the table on the task jobs page directs to a page (with the URL having the identical query parameter ``&tasks=mytask_T+030``) where the plus characters are converted to whitespace characters for the task name glob displayed, leading to no recognition of such named tasks & hence a blank table. (This is probably clearer to understand visually, so see the screenshots below).
This is a bug deriving from Rose Bush, as I have tested & observed it on that original utility too.
1. Define this **suite.rc**:
```ini
[scheduling]
graph = "mytask_T+030"
[runtime] …
```

task/suite name validity: consistency & explicitness

---

lib/cylc/cylc-review/template/pager.html

Close #3145
Looks like I added one urlencode too many.
This one was causing URL's to be encoded twice. So I assume JQuery when posting the form was automatically encoding it again.
Tested manually after applying the change. Steps to reproduce:
- create and register suite `%63ylc`
- with the content:
```
[scheduling]
graph = """
mytask_T+030 =>
my_task =>
my_task-ski-bop =>
my_task-DOO_WAP =>
my_task+100 =>
my_task@my_suite =>
t@a@s@k@y@m@c@g@e@e =>
4_my_task =>
_OLDTASKYLAD =>
3000  =>
__ =>
le_cyl%63
C++ =>
20130808T00 =>
__init__ =>
now =>
cylc =>
help
#a_very_long_task_name_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa …
```

7.8.x cylc review fix pager

---

lib/cylc/parsec/jinja2support.py
tests/hold-release/08-hold-family-inexact.t

address bandit b701 jinja2_autoescape_false

select_autoescape

---

doc/src/custom/make-commands.sh
doc/src/installation.rst
doc/src/suite-config.rst

(I can see how this happened, with the crazy way sphinx determines heading level ... you can't determine the level locally, have to compare the heading "adornment" with that of other headings!)
@sadielbartholomew - are you able to do a quick sanity check?  (Otherwise I might merge this unilaterally as a hot fix in order to put the release out ... it doesn't affect the code, and is fairly obviously correct - I compared heading levels in the table of contents with those in the old LaTeX-generated PDF at 7.8.0).
Also switches order of labels and headings in the auto-generated command reference, which was generating an error message (at least for my version of Sphinx).
I'll do the same for master once I've made the 7.8.x release...

Fix some doc heading levels

---

lib/cylc/network/client.py
lib/cylc/network/server.py
lib/cylc/tests/test_zmq.py

closes #3075 
Also adds a nice error message in the event that ZMQ fails to bind to the specified port(s).

zmq: support single port configuration

---

lib/cylc/network/client.py
tests/shutdown/10-no-port-file.t
tests/shutdown/18-client-on-dead-suite.t

Tentative fix for #3014 
Simply makes `SuiteRuntimeClient` child of `ZMQClient`, and call its constructor. Also updates docstrings, adds PEP-484 notation, and a TODO about a function that exits the program.
I remembered about this issue last week while working on the `setup.py` issue (#2989), as I noticed a couple warnings in Codacy that I __think__ may disappear with this change too.
Travis-CI passed on my fork, but still pending Codacy inspection :+1:

Extend ZMQClient and update docstrings

---

doc/src/custom/make-commands.sh
doc/src/installation.rst
doc/src/suite-config.rst

Master companion of #3148 
One review should do it.

Fix doc heading levels - master

---

lib/cylc/network/scan.py

Fix a really embarrassing bug in the `async_map` function (which is used for the `--ordered` option to `cylc scan`) :cry: .

async_map: fix bug

---

lib/cylc/network/scan.py

Damn, shouldn't have rushed that one, thanks for spotting.
One review should suffice for removing an unused variable.

async_map: remove changed variable

---

doc/src/appendices/suiterc-config-ref.rst

When text is wrapped in ``..`` tags, it appears to not need to have
the \ character. Everywhere else it is required though.
master part of https://github.com/cylc/cylc-flow/issues/3156

Fix \ in doco when wrapped in ``..``

---

bin/cylc
bin/cylc-get-site-config
cylc/flow/__init__.py
cylc/flow/cfgspec/globalcfg.py
cylc/flow/job.sh
cylc/flow/job_file.py
cylc/flow/network/client.py
cylc/flow/scheduler.py
cylc/flow/suite_srv_files_mgr.py
tests/cylc-trigger/03-edit-run.t
tests/cylc-trigger/08-edit-run-host-select.t
tests/events/47-long-output.t
tests/jobscript/00-torture/foo.ref-jobfile

#3133 (not sure if this is enough to close the issue).
This pull request removes some places where `CYLC_DIR` was used. For the test-battery, we used a temporary fix pre-setup.py, where the TRAVIS home is being set to CYLC_DIR.

Update how CYLC_DIR is used in Cylc

---

lib/isodatetime/data.py

This syntax does not work in Python 2.6:
```python
mydict = {key: value for item in items}
```
So we need to change the syntax to:
```python
mydict = dict((key, value) for item in items)
```
Unfortunately, we still have to support various platforms that will stay on Python 2.6 for some time.

7.8.x: restore compat for Python 2.6

---

bin/cylc-message
cylc/flow/task_message.py

At present `cylc message` can return nasty traceback about an undefined python variable.
This PR fixes this going back to the old, fail silently unless in debug mode approach. Whether this is the correct approach or not ...

message: fix pclient undefined error

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Master branch companion of #3141 
@kinow - one review will do.

Added GitHub Issue and PR templates.

---

CHANGES.md

First draft of `CHANGES.md`. I did not know whether it should include all issues post Cylc 7 under a single cylc-8.0.0 release, or one for each alpha.
But I realized that it would be simpler to go through each change in the [8.0a1 Milestone](https://github.com/cylc/cylc-flow/milestone/77?closed=1) that was closed, and add those before the 8.0a0 tag date to one release, and everything else to the 8.0a1 pending release.
As it would be easier to undo it, grouping all together, rather than doing the reverse, and having to split them.
No tests for this change. But should I include a change log, in the `CHANGES.md`, for the change in the `CHANGES.md`? :grimacing: 

Update changelog to include current alpha releases

---

SECURITY.md

The link to one of the e-mails was missing the `mailto`. Found via IDE analysis, then confirmed that in the GitHub UI it points to a 404 location.

Fix security email link

---

cylc/flow/cycling/iso8601.py

One variable being declared twice. First to an empty array, just to be initialized right after that. Probably one review is enough?

Remove unnecessary duplicate variable declaration

---

CHANGES.md
cylc/flow/job_file.py
cylc/flow/tests/test_job_file.py

Fix NameError on invalid cylc command

---

.github/PULL_REQUEST_TEMPLATE.md

Tweak the new PR template, to make it clear that some PRs don't require accompanying tests or a change log entry.  While I was at it, made the wording a little more concise.

PR template update.

---

cylc/flow/etc/job.sh
doc/src/suite-config.rst
tests/rnd/02-lib-python-in-job.t
tests/rnd/02-lib-python-in-job/lib/python/pub/beer.py
tests/rnd/02-lib-python-in-job/suite.rc

Small change to add `<suitedir>/lib/python` into PYTHONPATH in the task execution environment.
The motive here is to make it easier for users to link the task scripts in the suite bin directory to suite-specific Python libraries. Currently the user is responsible for doing the PYTHONPATH melding.
1. Users could do something stupid like create the file `<suitedir>/lib/python/os.py`
2. We are now mixing lots of different libraries into the same `lib/python` dir.
3. The `CYLC_SUITE_RUN_DIR` / `CYLC_SUITE_DEF_PATH` arrangement is horrible, this will get resolved with this with the migration of `rose suite-run` functionality?

jobscript: add lib/python to PYTHONPATH

---

CHANGES.md
lib/cylc/gui/gcapture.py

Address issue similar to the #3183 PR, but on commands such as `cylc trigger --edit` via the GUI.
Reported by @steoxley.

cylc.gcapture: don't split command

---

CHANGES.md

There is an extra space for all links (probably from some script adding the link format framework at once) to PRs in the new changelog entry, so they are not recognised as markdown links when rendered.
Trivial, hence one reviewer sufficient.
********
/
/

Fix PR markdown links of 7.8.3 changelog entry

---

cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/tests/test_xtrigger_mgr.py
cylc/flow/xtrigger_mgr.py

Fix for #3057 
Removes one dependency from `TaskPool`, moving the `check_xtriggers` code from there to the `XtriggerManager` in `cylc.xtrigger_mgr.py`.
A few more changes added here, including:
- removal of unnecessary parentheses
- organized imports
- removed unused parameter of `XtriggerManager` constructor `suite_work_dir`
- forced named parameters for `XtriggerManager`'s constructor, to avoid assigning variables incorrectly
- added docstrings with PEP-484 types
- add first unit tests for `XtriggerManager`

Xtrigger minor improvements

---

README.md

Refresh the Cylc project badges as displayed in markdown in the README. Notably, add in (amongst others):
* a badge linking to the **PyPI** project page;
* a **Discourse** badge to make it clear that it is the new, & active, home for support queries;
* a link to the **website & the documentation** (both already linked in the text, but handy as a prominent badge at the top of the file)
(These are most relevant to the ``cylc`` GitHub organisation & all repositories under it, rather than the ``cylc-flow`` specifically, but so is all of the ``README.md`` content, so that is a separate issue to discuss.)
As previewed in an online Markdown editor, these new badges will appear as follows:
******
******

Update & organise project README badges

---

cylc/flow/parsec/validate.py
cylc/flow/tests/parsec/test_validate.py
cylc/flow/tests/test_config.py

Hi,
I was doing some clean up in my local branches, and found one with a fix for #2700. As I am waiting for some code to be fixed for the `setup.py`, decided to work on this issue today in the afternoon.
The issue #2700 happens due to the regex used, which misses the second unquoted value of the `inherit` configuration. 
Here's an example of what happens: https://pythex.org/?regex=%27(%5B%5E%27%5C%5C%5D*(%3F%3A%5C%5C.%5B%5E%27%5C%5C%5D*)*)%27&test_string=%27BIGFAM%27%2C%20SOMEFAM&ignorecase=1&multiline=1&dotall=1&verbose=0
I think we could try to fix that regex... possibly combining more regexes to match other cases? But an alternative solution would be to use the `shlex` module (used in other parts of Cylc I believe) in `strip_and_unquote_list()`.
>The shlex class makes it easy to write …

Fix inheritance with quotes using shlex

---

cylc/flow/scheduler.py

The copyright notice printed to STDOUT for ``cylc run`` & ``cylc restart`` recently had its ending cut off.
Upon investigation, this started at v. ``7.8.0`` & was due to the addition of a new line ("& British Crown...") to the notice & the [behaviour of ``zip()`` function](https://docs.python.org/3.3/library/functions.html#zip) which aggregates elements from *uneven-length* inputs up to the length of the *shortest* input. (The copyright text had one more line then the logo, so the final line was lost in the ``zip()``.) See the 'Outputs' section below for a breakdown by illustrative version.
I could have just padded out the logo line, but it seemed more maintainable to convert the ``zip()`` to an equivalent function ``itertools.zip_longest()`` which will pad out the shorter input as …

run/restart: re-add cut off user notice line

---

tests/execution-time-limit/00-background.t
tests/execution-time-limit/00-background/reference.log
tests/execution-time-limit/00-background/suite.rc
tests/lib/bash/test_header

Reduce chance of test failure by not doing a retry. (The test should also take less time.)
These changes partially address #2894.

tests/execution-time-limit/00: reduce failure chance

---

bin/cylc-cat-log
tests/cylc-cat-log/00-local.t
tests/cylc-cat-log/00-local/suite.rc
tests/cylc-cat-log/03-bad-suite.t

Abort if "-f" option used with suite log.
These changes close #3194 

Fix minor bug in cat-log command.

---

tests/modes/dummy-message-outputs/suite.rc

Test would previously fail randomly with the dummy task job being terminated with XCPU signal or the suite timing out prematurely. This change reduces the task job run length, but removes the time constraint on the suite. Hopefully, these changes should be sufficient to prevent flakiness seen previously.
These changes partially address #2894.

tests/modes/02: remove time constraint

---

CHANGES.md
etc/dev-bin/create-version-file

For compat with new repository name (cylc -> cylc-flow).
Following standard installation instructions, typing `make` in the unpacked release directory puts "flow-7.8.3" (e.g.) in the VERSION file, instead of just "7.8.3".
Which means, `cylc --version` will return `flow-7.8.3`!
No need for forward port: Cylc-8 version is determined differently.
- (This change cannot really be tested - it affects unpacked releases only).

Fix version file creation for new repo name.

---

cylc/flow/hostuserutil.py

This PR uses `contextlib` to suppress `IOError`, and also to close the socket (`socket` implements context manager since [Python 3.2](https://docs.python.org/3/library/socket.html#socket-objects)). Found while investigating an issue in `cylc-uiserver` regarding file leaks in sockets earlier this week. Even though the leak was not here, I thought it was still worth updating it - and then wrote a post-it to remind me later :grimacing:
`suppress` is available since [Python 3.4](https://docs.python.org/3/library/contextlib.html#contextlib.suppress), so I think it should be fine to use it.

Use contextlib for suppressing IOError and closing socket

---

cylc/flow/tests/parsec/test_validate.py

While fixing a previous issue in Exeter regarding quotes with `shlex`, I wrote this unit test and ran it a few times in my IDE, so it passed. And it also worked on Travis, but as I named the function the same as a previous function, I am not sure which method was actually executed.
Luckily as I ran with the IDE too, so the code was actually tested. With the change in this PR, `pytest` is passing OK and both tests are working fine :relieved: 
```
cylc/flow/tests/parsec/test_validate.py::TestValidate::test_strip_and_unquote PASSED                                                                                    [ 93%]
cylc/flow/tests/parsec/test_validate.py::TestValidate::test_strip_and_unquote_list_cylc PASSED …
```

Fix duplicate test name test_strip_and_unquote_list

---

CHANGES.md
doc/src/task-job-submission.rst

This is a small change with no associated Issue (doc typo fix only).
7.8.x companion of https://github.com/cylc/cylc-doc/pull/35
One review will do.

Fix doc typo.

---

cylc/flow/network/schema.py

These changes partially address #3216 (the table that is not rendered returns, populated with the suite's data, but the GraphQL error on 'state' is still there & needs further investigation).
This PR essentially reverts #3211 (bar one line), because whilst ``not X`` to test for a sequence being non-empty in a conditional is the Pythonic way advocated by PEP8, in this context the logic on ``field_ids`` needs to distinguish between an empty list & ``None`` (which that form does not do, as both are "falsy").
This is because ``field_ids = getattr(root, field_name, None)`` returns ``None`` as the default, & seems to be doing so for all the suites I have tried out to test this (as observed by adding in a ``print()`` function to check), whereas the query field argument default is an empty list …

Fix schema error & in turn per-suite UI data provision

---

bin/cylc-print
cylc/flow/network/scan.py
cylc/flow/suite_srv_files_mgr.py

These changes close #3227, by excluding ``log`` sub-directories within run directory levels from being traversed by the ``os.walk``, so that suites under multiple directory levels from the root Cylc run directory & hierarchically-named suites can still be detected, but without needlessly trawling through highly-nested & easily numerous core Cylc directories.
Update: this is done by removing the original ``SuiteSrvFilesManager.list_suites()`` method used in ``bin/cylc-print``, & replacing it with a slight modification on ``get_scan_items_from_fs()``, which was largely duplicating it, including excluding ``log`` directories from being traversed already.
This approach does assume that suites won't be created in levels within directories named with those keywords, e.g. a suite named …

Remove possibility for very slow cylc print

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Just wondering if others prefer to have the comments in the templates as comments? It just helps not having to remember to delete the comments, but if others think this could confuse users (especially the parts they have to choose only one option?), then I think it's fine the way it is :+1: 

Comment comments in issue and PR templates?

---

bin/cylc-cycle-point
bin/cylc-suite-state
cylc/flow/cfgspec/suite.py
cylc/flow/config.py
cylc/flow/cycling/iso8601.py
cylc/flow/cycling/loader.py
cylc/flow/cycling/util.py
cylc/flow/jinja/filters/duration_as.py
cylc/flow/jinja/filters/strftime.py
cylc/flow/parsec/validate.py
cylc/flow/scheduler.py
cylc/flow/task_proxy.py
cylc/flow/time_parser.py
cylc/flow/wallclock.py
cylc/flow/xtriggers/suite_state.py
flakytests/cylc-poll/16-execution-time-limit.t
setup.py
tests/cylc.wallclock/00-single.t
tests/restart/37-auto-restart-delay.t

The isodatetime module was recently renamed metomi.isodatetime ([PR 132](https://github.com/metomi/isodatetime/pull/132)). 
This PR changes the namespaces in cylc to reflect this.

Upgrade isodatetime to metomi isodatetime

---

CHANGES.md
cylc/flow/rundb.py
cylc/flow/task_pool.py
tests/cylc-insert/13-family-submit-num.t
tests/cylc-insert/13-family-submit-num/reference.log
tests/cylc-insert/13-family-submit-num/suite.rc

On insert of a family with tasks that had submitted jobs before, the submit
numbers of the tasks were not incremented. This changes fixes the issue.
These changes close #3210.

Fix insert family submit-num increment

---

bin/cylc-extract-pkg-resources

The ``cylc extract-pkg-resources`` command was originally called ``get-pkg-resources`` & it seems the docstring was missed when it was renamed, so this is a small PR to update the docstring accordingly.
This change is not immaterial, since the docs (for now) generate the Command Reference section from the command module doctrings, meaning the docs will record this command under the old name until this update is made. So the docs currently describe a command which doesn't exist, & are missing the one that does.
I have ``grep``-ped through the codebase & there are no other uses of the old command name; this is the only one.
Trivial, hence one reviewer sufficient.

extract-pkg-resources: update docstring w/ rename

---

CHANGES.md
cylc/flow/etc/job.sh
tests/jobscript/20-isodatetime-envs.t

Set calendar mode and reference time for the `isodatetime` command (for date-time cycling suites).

job.sh: export ISODATETIMECALENDAR ISODATETIMEREF

---

bin/cylc-extract-resources
bin/cylc-help
cylc/flow/resources.py
cylc/flow/suite_srv_files_mgr.py
cylc/flow/task_remote_cmd.py
cylc/flow/tests/test_resources.py
cylc/flow/tests/test_suite_srv_files_mgr.py

Running Cylc commands from within the `cylc/flow` directory can cause traceback due to a namespace conflict with the Python `pkg_resources` module.
Rename `pkg_resources` to `resources` which doesn't have a stdlib counterpart:
```console
$ cd cylc.git/cylc/flow
$ cylc validate generic
File "....cylc/bin/cylc-validate", line 4, in <module>
__import__('pkg_resources').require('cylc-flow==8.0a0')
AttributeError: module 'pkg_resources' has no attribute 'require'
$ cd ../
$ cylc validate generic
Valid for cylc-8.0a0
```

rename pkg_resources module to avoid namespace conflict

---

cylc/flow/config.py

Minuscule change, just to replace the `is` by `==` for strings. Harmless, but raises a warning when you run `cylc run --no-detach five` when Python is compiled with the pydebug flag.

Compare string with equal sign

---

CHANGES.md
doc/src/external-triggers.rst
lib/cylc/tests/test_xtrigger_mgr.py
lib/cylc/xtrigger_mgr.py

Avoid %% escape in xtrigger func args (7.8.x).

---

CHANGES.md
cylc/flow/tests/test_xtrigger_mgr.py
cylc/flow/xtrigger_mgr.py

This is the master branch (cylc-8) companion of #3257 - see documentation there.
These changes close #3256 

Avoid %% escape in xtrigger func args (master).

---

CHANGES.md
etc/dev-suites/outputs/suite.rc
etc/profile-experiments/outputs.json
lib/cylc/config.py
lib/cylc/taskdef.py

This speeds up suite validation significantly for tasks with
large numbers of outputs.  The list used required an O(N)
check for membership which, when combined with being run for
each output resulted in O(N**2) complexity.
Using the builtin set should bypass any deprecated libraries in
Python 2.
These changes closes #3255

Replace O(N) lookup with O(1) for task outputs (7.8.x)

---

cylc/flow/resources.py
cylc/flow/scheduler_cli.py
cylc/flow/suite_srv_files_mgr.py
cylc/flow/tests/test_suite_srv_files_mgr.py

These changes close #3250
Extract `job.sh` to the suite service directory at start-up, not registration time.

Extract job.sh at suite start-up.

---

CHANGES.md
cylc/flow/xtrigger_mgr.py
flakytests/xtriggers/01-suite_state.t

These changes close #3275.
Using the example xtrigger from the Issue above I now see in the suite log, as expected:
```console
2019-08-06T20:05:28+01:00 INFO - Broadcast set:
+ [foo.20190806T2005+01] [environment]succeeding_ONE=one
+ [foo.20190806T2005+01] [environment]succeeding_TWO=two
+ [foo.20190806T2005+01] [environment]succeeding_THREE=three
2019-08-06T20:05:28+01:00 INFO - [foo.20190806T2005+01] -submit-num=01, owner@host=...
```

Record all broadcast values in xtrigger return signature

---

CHANGES.md
cylc/flow/suite_srv_files_mgr.py
cylc/flow/tests/test_suite_srv_files_mgr.py
cylc/flow/unicode_rules.py

**For Discussion**
address "suite registration" point of #2979 
Create a `unicode_rules` module:
* Centralise unicode restrictions (e.g. suite / task names) for consistency.
* Provide user with an informative error explaining which rule an invalid name has broken.
* Allow us to auto-document text restrictions.
**Questions**

restrict suite name character set

---

bin/cylc-jobscript

- fix `cylc jobscript` command - it's not printing the generated jobscript as advertised
- and  update its command help
On current master the command generates a jobscript then claims that it doesn't exist (so printing it fails):
```
(venv) [oliverh@drugs-and-money cylc-flow]$ cylc jobscript foo bar_m09_n07.20000101T0000+12                                                                                      
Task Job Script Generated: /home/oliverh/cylc-run/foo/log/job/20000101T0000+12/bar_m09_n07/01/job
/home/oliverh/cylc-run/foo/log/job/20000101T0000+12/bar_m09_n07/01/job: No such file or directory
```
Using the "open in editor" option instead, with vim, reveals the problem is a control code added to the filename by colorama:
``` …
```

Turn colour off in jobscript generation command.

---

CHANGES.md
lib/cylc/xtrigger_mgr.py
tests/xtriggers/01-suite_state.t

These changes close (for ``7.8.x``) #3275.
This PR is a direct equivalent to #3276, to backport it to ``7.8.x``. For reviewing, note the only difference to the counterpart PR is that ``xtriggers/01-suite_state.t`` still sits under ``tests/`` here, rather than under ``flakytests/``.

Record all broadcast values in xtrigger return [backport]

---

tests/lib/bash/test_header

We use a `poll` function in a bunch of tests, to repeatedly run a command until we get the desired result - for one minute.  However, the test scripts just continue as normal if one minute is reached without getting the desired result.  This seems like a potential source of test flakiness under high load conditions (if not an actual source, because one minute is quite long).
This PR causes the `poll` function to abort the test with a sensible message, on timeout.
@matthewrmshin (original author of `poll` according to git!) - if you agree with this, I'll copy it to master as well.

Test header: poll abort on timeout.

---

flakytests/database/00-simple.t

The test `tests/database/00-simple.t` has been failing on Travis for 7.8.x (is under `flakytests` on master):
```
cat: unrecognized option '--cmp-ok.stderr'
Try 'cat --help' for more information.
cp: unrecognized option '--cmp-ok.stderr'
Try 'cp --help' for more information.
stdout and stderr stored in: /tmp/travis/cylctb-20190813T121051Z/database/00-simple
./tests/database/00-simple.t ................................. Failed 1/21 subtests 
```
This passes locally, but something (maybe bash version?) has changed on T-CI recently to cause the `cat` and `cp` errors above.  
A closer look shows that `cmp_ok` in the test script has its args in the wrong order (`-` for stdin should be the second arg, as documented in the file header) and even when the test passes, the test name is being …

Fix cmp_ok arg order in a test (master).

---

tests/database/00-simple.t

7.8.x companion of #3289 - see there for documentation there.

Fix cmp_ok arg order in a test.

---

CHANGES.md
lib/cylc/config.py
lib/cylc/task_pool.py
lib/cylc/task_state.py
lib/cylc/taskdef.py
lib/cylc/tests/test_config.py
lib/cylc/xtrigger_mgr.py
tests/cylc-review/00-basic.t
tests/cylc-review/01-title.t
tests/database/00-simple.t
tests/database/01-broadcast.t
tests/database/02-retry.t
tests/runahead/06-release-update.t
tests/validate/69-bare-clock-xtrigger.t
tests/validate/70-no-clock-int-cycle.t
tests/xtriggers/03-sequence.t

These changes partially address #3283  (companion PR to master will complete).
Major:
- record xtrigger functions against cycling sequence, and only use those valid for the sequence when task proxies are instantiated.
Minor:
- better unifies the handling of clock- and general-xtriggers
- `wall_clock` works with positional or keyword `offset` arg (another problem identified by @trwhitcomb)
- disallows clock triggers with integer cycling

Xtrigger sequence fix

---

.travis/install.sh
setup.py

Changes the version range of `graphene` to match the version requirement of `graphene-tornado`. Without this change, users installing `cylc-uiserver` face either a warning or a possible error. This happens because `cylc-uiserver` installs `graphene-tornado`, which is bringing `graphene==2.1.7`.
But `cylc-flow` had a hard-requirement on `==2.1.6`, due to an error on Travis.
The error on Travis was due to the Travis environment coming with `six <1.12`, while `graphql-relay` requires `>=1.12`.

Update graphene version range in setup.py

---

bin/cylc-insert
cylc/flow/option_parsers.py

These changes close #3284 (for ``master``/Cylc-8). Note I am applying a different approach for the equivalent PR to 7 & 8, adding the necessary text directly into the ``insert`` docstring for 7 since the version is soon to be dormant, but creating an alternative option-parser-level pattern matching text section here for 8 where something reusable & more maintainable could well be useful for CLI or functionality changes that may come in future.

insert: globbing capability docstring correction (Cylc-8)

---

bin/cylc-insert

These changes close #3284 (for ``7.8.x``). Note I am applying a different approach for the equivalent PR to 7 & 8, adding the necessary text directly into the ``insert`` docstring for here 7 since the version is soon to be dormant, but creating an alternative option-parser-level pattern matching text section for 8 where something reusable & more maintainable could well be useful for CLI or functionality changes that may come in future.

insert: globbing capability docstring correction (Cylc-7)

---

.codacy.yml
.codecov.yml
.coveragerc
cylc/flow/config.py
cylc/flow/cycling/integer.py
cylc/flow/job_pool.py
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
cylc/flow/tests/network/test_resolvers.py
cylc/flow/tests/network/test_server.py
cylc/flow/tests/test_ws_data_mgr.py
cylc/flow/tests/util.py
cylc/flow/ws_data_mgr.py
cylc/flow/ws_messages.proto
cylc/flow/ws_messages_pb2.py
setup.py
tests/graphql/01-workflow.t
tests/graphql/01-workflow/suite.rc
tests/graphql/02-root-queries.t
tests/graphql/02-root-queries/suite.rc

The current data-store generation is inefficient (as was the old `state_summary_mgr.py`), in that it generates an entirely new data-store on every loop where *any* change has flagged...
The update/creation has been granulated into the following actions/methods:
1) Creation of workflow/taskdef/familydef data elements.
2) Generation of graph edges and ghost-nodes/ghost-instances/ghost-proxies (containing def data and tree relationships) for each new cycle point in the pool.
3) Update/population of [ghost] task instance fields with dynamic data (i.e. status info) for given pool tasks.
4) Update/population of [ghost] family instance fields with dynamic data (i.e. status info) according to given cycle points (i.e. those cycle points of the updated tasks).
5) Update/population of workflow (data …

Incremental data-store generation

---

CHANGES.md
bin/cylc-hold
bin/cylc-insert
bin/cylc-kill
bin/cylc-poll
bin/cylc-release
bin/cylc-remove
bin/cylc-reset
bin/cylc-show
bin/cylc-spawn
bin/cylc-trigger
cylc/flow/option_parsers.py

Update CLI globbing help, post #3296 
(We need to be very clear that CLI globbing matches against the current task pool, not abstract tasks in the workflow)
(This may need updating again if we implement pseudo-spawn-on-demand with automatic insertion of tasks not in the pool).
----

Amend CLI globbing help text.

---

CHANGES.md
bin/cylc-documentation
bin/cylc-hold
bin/cylc-insert
bin/cylc-kill
bin/cylc-poll
bin/cylc-release
bin/cylc-remove
bin/cylc-reset
bin/cylc-show
bin/cylc-shutdown
bin/cylc-spawn
bin/cylc-trigger
bin/cylc-view
lib/cylc/option_parsers.py
tests/cylc-insert/08-insert-family-compat/suite.rc

7.8.x companion of #3302
-----

Amend CLI globbing help text (7.8.x)

---

cylc/flow/cylc_subproc.py
cylc/flow/tests/test_cylc_subproc.py
setup.cfg
setup.py

Whilst looking at the ``cylc-xtriggers`` repo I noticed the setup script had a copyright notice that did not include this year (cylc/cylc-xtriggers#5). Since the likelihood is that one template for these scripts was copied across repos & amended accordingly, I thought I would check that similar files in other repos were up-to-date.
In this case, it was not, & there were also three other instances remaining of outdated notices from a ``git grep "\-2018"`` (& the equivalent with a few other preceding years).
Trivial change, hence one reviewer sufficient.

Update copyright notices for setup (& other) files

---

bin/cylc
bin/cylc-help

Follow-up #3286, which removed the last remaining "hook" command, but forgot to remove the associated command category (noticed when I tried to build the docs).  @kinow - one review will do.

Remove obsolete command category "hook".

---

cylc/flow/subprocpool.py

We do not require the `stopping` variable in the function scope, being able to simply return the `self.stopping` value.
This is a small change with no associated Issue. Also updates the docstrings.

Remove unnecessary variable stopping

---

tests/reload/22-remove-task-cycling.t

Ensure that a new test is not flaky under load on Travis-CI.  Failed here because task `bar` (sleep 10) completed before the reload: https://github.com/cylc/cylc-flow/pull/3317#issuecomment-525050475

Make new test more robust.

---

doc/src/external-triggers.rst

A requested back-port of cylc/cylc-doc#68, which will close cylc/cylc-doc#66 (for Cylc-7).
Trivial enough, & already reviewed for Cylc-8, hence one reviewer sufficient.

docs: Python versions required for xtriggers (Cylc-7)

---

doc/src/external-triggers.rst

A requested back-port of cylc/cylc-doc#41, which will close cylc/cylc-doc#69 (for Cylc-7).
Trivial enough, & already reviewed for Cylc-8, hence one reviewer sufficient.

docs: format of xtrigger results dictionary (Cylc-7)

---

cylc/flow/tests/test_zmq.py

`cylc/flow/tests/test_zmq.py:test_single_port` passes on Travis CI (Python 3.7.1, pytest 4.4.2) but fails in my local environment (Python 3.7.3, pytest 5.1.1):
```
cylc-flow]$ pytest cylc/flow/tests/test_zmq.py 
============================================================ test session starts ===========================================================================
platform linux -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0 -- /home/oliverh/cylc/cylc-flow/venv/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/oliverh/cylc/cylc-flow, inifile: pytest.ini
collected 1 item …
```

Fix a cylc ZMQ unit test.

---

CHANGES.md
cylc/flow/config.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/task_state.py
cylc/flow/taskdef.py
cylc/flow/tests/test_config.py
cylc/flow/tests/test_xtrigger_mgr.py
cylc/flow/xtrigger_mgr.py
tests/validate/69-bare-clock-xtrigger.t
tests/validate/70-no-clock-int-cycle.t
tests/xtriggers/03-sequence.t

master companion of #3285 
These changes (along with #3285) close #3283 
TODO:
- ~~some basic Python 3 upgrade (e.g. format strings)~~
- ~~fix some xtrigger unit tests~~

xtrigger sequence fix - master

---

cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/ws_data_mgr.py
cylc/flow/ws_messages.proto
cylc/flow/ws_messages_pb2.py
tests/graphql/01-workflow.t
tests/graphql/02-root-queries.t
tests/graphql/03-is-held-arg.t
tests/graphql/03-is-held-arg/suite.rc
tests/job-submission/01-job-nn-localhost/db.sqlite3

These changes close #3278
This change:
- Removes `held` from state totals.
- Adds `isHeldTotal` to workflow query.
- Makes state totals agnostic to internal suite state names.
- Adds `is_held`/`isHeld` field to the data-store and GraphQL Schema
- stateTotals is resolved at the GraphQL side, states names imported from cylc.flow.
- Query field stateTotals returns all states (no need to specify sub-fields)

isHeld API addition

---

CHANGES.md
bin/cylc-register
cylc/flow/suite_srv_files_mgr.py
tests/registration/00-simple.t

These changes close #2797
Supersedes #2817 (On reflection my initial take on this was unnecessarily focused - for historical reasons - on the idea of using an absolute suite path (instead of a registered suite name) to distinguish this from a normal run.  In fact, registration is really an entirely orthogonal concept.  The basic requirement (/desired feature) is:
_Better support for quick-running sub-suites (of jobs that run on a single node?) by allowing sub-suite run directories to be located on fast local disk or RAM disk._
Why? 1)  too many small files kills HPC shared filesystems like Lustre; and 2) top-level suite run directories rapidly proliferate if you use sub-suites in a cycling suite.  
This trivial PR just adds a new registration option …

Support symlinked alternate run directories (cylc 8).

---

cylc/flow/network/server.py

After showing cylc-ui + uiserver to @hjoliver today I left a workflow running, and then had a quick look at the logs to confirm there was nothing wrong after some time. And then saw all the logs again that were taking most of the space in my console buffer :disappointed: .
This PR simply removes the two lines that were logging it. Tested locally, but better wait for Travis to make sure there are no tests expecting some line with `zmq:send`, etc
These changes close #3300 

Remove zmq message logging

---

INSTALL.md

The master branch INSTALL.md still gave cylc-7 installation instructions.

Update master INSTALL.md.

---

cylc/flow/parsec/upgrade.py
cylc/flow/tests/parsec/test_upgrade.py

Whist working on the new config I noticed that at times the method `cylc.flow.parsec.upgrader.obsolete` appeared to work in the same manner as `cylc.flow.parsec.upgrader.deprecate` taking the kwarg `newkeys` which it then does nothing with. I have suggested that this argument be removed.

prevented parsec.upgrader.obselete acting as parsec.upgrade.deprecate

---

CHANGES.md
bin/cylc
bin/cylc-graph
bin/cylc-help
bin/cylc-ref-graph
doc/src/installation.rst
tests/cylc-graph-diff/00-simple.t

These changes close #3343
Provides a new command, `cylc ref-graph SUITE` to generate text-format "reference graphs" without pygtk (back-port of @oliver-sanders' `cylc graph` on master for Cylc 8). 
Under the circumstances, I don't think there is any need to properly incorporate this into the main Cylc 7 `cylc graph` command.
Also updated the "misleading" PyGTK installation documentation.

Cylc 7 ref graphs without pygtk

---

CHANGES.md
cylc/flow/config.py
cylc/flow/taskdef.py

These changes close #3255. Supersedes #3268.

Replace O(N) lookup with O(1) for task outputs (master)

---

bin/cylc-set-verbosity
tests/cli/03-set-verbosity.t

Executing something like `cylc set-verbosity five ubirajara`, you will get:
```bash
File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-set-verbosity", line 63, in main
severity = LOGGING_LVL_OF[severity_str]
KeyError: 'ubirajara'
During handling of the above exception, another exception occurred:
File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-set-verbosity", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-set-verbosity", line 77, in <module>
main()
File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/terminal.py", line 137, in wrapper …
```

Fix exception when set-severity receives invalid logging level

---

.codecov.yml

Sets code coverage minimum acceptable before failure at 85%, and patch at 95% (how much of the code changed in a PR needs to be covered).

Adjust codecov thresholds (85 general, 95 patch)

---

cylc/flow/network/server.py

Was poking around the code today, and noticed that the server thread's loop returns a value when an error occurs decoding the message the value will be returned, the job error log will contain some error, but the suite output won't contain anything.
So maybe instead we could raise a `CylcError` (or would it be better a `ValueError`? or just log it? anyhoo). This way at least we get the exception + traceback in the logs.
Cheers
Bruno

Log exception when a decrypt error occurs

---

tests/deprecations/00-pre-cylc8.t
tests/deprecations/00-pre-cylc8/suite.rc
tests/deprecations/01-cylc8-basic.t
tests/deprecations/01-cylc8-basic/suite.rc

Whilst working on the updated `????.rc` file spec I came across the following issue:
There is a test for deprecated/obsolete `suite.rc` config items, but it's not been kept up-to-date. I think that this may be very useful in the config re-alignment work, but I want it up to date on master. 
This PR attempts to rectify this problem.
I have renamed the existing test `00-pre-cylc8` and added a new test `01-cylc8-basic`, on the basis that future work is likely to lead to `0N-cylc8-why-it-is-complex`.

updated cylc-deprecate tests

---

CHANGES.md
cylc/flow/batch_sys_handlers/pbs.py
cylc/flow/tests/batch_sys_handlers/test_pbs.py

Add unit test for the directives formatter function for PBS handler.
Also upgrade default PBS job name line length from 15 to 236, i.e. assuming PBS version >=13.
This is a small change with no associated Issue. The purpose is to observe the test coverage of a source file that is currently untested on Travis CI.

Unit test PBS directives formatter

---

cylc/flow/parsec/config.py
cylc/flow/parsec/exceptions.py
cylc/flow/parsec/fileparse.py
cylc/flow/parsec/include.py
cylc/flow/tests/parsec/test_fileparse.py
cylc/flow/tests/parsec/test_include.py
cylc/flow/tests/parsec/test_parsec.py
tests/validate/61-include-missing-quote.t

These changes partially address #2425 
Result of kicking about at a recent conference. Probably enough to close 2425?
**Comparison Of Error Output**
*before*
```
$ cylc validate .
FileParseError: Invalid line 3813: 600
```
*after*
```
$ cylc validate .
FileParseError: Invalid line (line 3813):
600
(line numbers match 'cylc view -p')
```
**Off Topic Changes**
* Improves the `FileParseError` exception so that its data is stored as attributes. Besides being nicer this means tests can be safer (less fragile to test an attribute of an error than the entire error message).
* Add file path information to `FileParseError` where available (which it almost never is).
* Changes `mismatched quotes` error from `ParsecError` to `FileParseError`.

parsec: improve file parse error messages

---

CHANGES.md
cylc/flow/etc/job.sh

These changes close #3376
- remove support for sourcing user `job-init-env.sh` in task job scripts
- (site `job-init-env.sh` already removed during CYLC_DIR removal for Cylc 8)
- I have retained support for `init-script` because it provides some additional flexibility (e.g.: can be configured centrally on the suite host, rather than by modifying login scripts on all job hosts) but documented that use of login scripts is preferred

Remove job-init-env.sh support.

---

README.md

When copying the summary statement for Cylc into a conda-forge recipe, I noticed it is phrased strangely, where there is a 'however' grouping two essentially equivalent statements:
> Cylc is a general workflow engine, *however* it is not specialized to forecasting in any way.
I think the 'however' was intended to be tied to the previous, contrasting, sentence, where it makes sense contextually (if I am wrong, let me know & I am happy to close this, but it doesn't flow well to me).
Trivial hence one reviewer sufficient.
********************************

Re-phrase README summary statement

---

CONTRIBUTING.md
cylc/flow/tests/test_wallclock.py

Improve coverage of get_unix_time_from_time_string

pytest check cover value error

---

bin/cylc-get-host-metrics
tests/cylc-get-host-metrics/00-simple.t

Whilst trying to compare the available memory between two differently provisioned servers I did a quick bit of reading into the MemAvailable field of `/proc/meminfo`.
This field isn't universally available (hence why it wasn't used before) but we should use it by default and fallback to calculating our own estimate only when we have to.
Can backport if we have another 7.8.x release.

host-metrics: use MemAvailable field where present

---

cylc/flow/tests/batch_sys_handlers/test_loadleveler.py
cylc/flow/tests/batch_sys_handlers/test_moab.py

Increase test coverage for batch system handlers, moab and loadleveler.
These changes close #3372

Tests added covering moab.py and loadleveler.py

---

cylc/flow/network/schema.py
cylc/flow/tests/network/test_schema.py

Sibling PRs:
- https://github.com/cylc/cylc-ui/pull/280
- https://github.com/cylc/cylc-uiserver/pull/82

Add subscriptions

---

CHANGES.md
cylc/flow/scheduler_cli.py
tests/cylc-run/01-invalid-suite.t
tests/cylc-run/test_header

Prevent cylc-run of creating directories for invalid suites

---

cylc/flow/network/server.py

These changes partially address #3414 
`recv_string` may raise a `ZMQError` that is not caught anywhere, which makes it harder to troubleshoot ZMQ errors like in #3414.

Log if a ZMQError happens in the ZMQServer loop

---

cylc/flow/network/authorisation.py

ATM links in docstrings are broken, there is no integrity check for this (difficult, might come up with a solution soon).

docs: fix api reference

---

bin/cylc-cat-log

Low priority. Without the change:
After change:

Suppress KeyboardInterrupt for cat-log

---

CHANGES.md
cylc/flow/remote.py
cylc/flow/task_remote_mgr.py

If a workflow has a remote job, remote run remote directory tidy at suite shutdown will fail here:
```
File "/home/oliverh/cylc/cylc-flow/venv/lib/python3.7/site-packages/cylc/flow/task_remote_mgr.py", line 244, in remote_tidy
Popen(cmd, stdout=PIPE, stderr=PIPE, stdin=open(DEVNULL)))
ValueError: negative file descriptor
```

Fix remote tidy subprocess call.

---

lib/cylc/cylc-review/template/view.html

(There is one ``7.8.x``-tagged PR up, so I'll put in this small PR in case there is ever enough to warrant a ``7.8.5`` release.)
When viewing any files under Cylc Review, if the window width is made small enough, the line numbers will detach from the lines they describe:
This small change prevents this from happening without influencing the UI otherwise. Otherwise, the design is largely responsive & could probably be viewed on a mobile or tablet without any glaring UI issues.

Cylc Review: stop line numbers detaching from lines

---

lib/cylc/param_expand.py

A Python 2 bug which should not require forward porting.
The `expand_parent_params` method is dependent on dictionary ordering which produces incorrect results.
```ini
[cylc]
[[parameters]]
a = 1..1
b = 1..1
c = 1..1
d = 1..1
[scheduling]
graph = <a, b, c, d>
[runtime]
[[<a>]]
[[<a, b>]]
[[<a, b, c>]]  # Cylc converts this to <a, c, b> because of py2 dict ordering
[[foo<a>]]
inherit = <a>
[[foo<a, b>]]
inherit = "<a, b>"
[[foo<a, b, c>]]
inherit = "<a, b, c>"
```
At 7.8.x this happens:
```console
$ cylc get-config --sparse .        
ERROR, undefined parent for foo_a1_b1_c1: _a1_c1_b1
```

fix param inherit family bug

---

tests/jinja2/11-logging.t

Test associated with https://github.com/cylc/cylc-doc/pull/102.

jinja2: test that cylc logger is available to jinja2 at load time

---

cylc/flow/parsec/validate.py
cylc/flow/subprocctx.py
cylc/flow/tests/parsec/test_validate.py

Document the parsec "types" from within Pasec for use by autodocumentation systems.
* add doctests for each coercer
* make all coercers classmethods
* document coercers
* test examples in documentation
Trying for the simplest, least hassle way of doing this, in the long run we will want to refactor things somewhat. At Cylc9 we may well brush this code aside entirely.
This documentation will be used to generate reference material like this:
These changes partially address #3253, https://github.com/cylc/cylc-doc/issues/101

parsec: add help for coercers (data types)

---

flakytests/hold-release/13-ready-restart/suite.rc

Fixes `flakytests/hold-release/13` on `sgaist/move_to_entry_points` (#3413)
I think this test failure is due to the way cylc commands get re-executed causing a different process signature which jiggered up the pattern matching employed.
`sed` is a better solution.

tests: fix hold-release/13

---

cylc/flow/xtriggers/echo.py
cylc/flow/xtriggers/suite_state.py
cylc/flow/xtriggers/xrandom.py

Provide Xtriggers with docstrings suitable for auto-documentation via Sphinx.
Part-addresses https://github.com/cylc/cylc-xtriggers/issues/4

xtriggers: documentation

---

cylc/flow/exceptions.py
cylc/flow/platform_lookup.py
cylc/flow/tests/test_platform_lookup.py

Added forward lookup method 
- checks if specified platform (will come from suite.rc file) is a valid platfrom (listed in global.rc file). 
- checks in reverse order to ensure user platform selection overrides global setting. 
- If no platform is selected by user, defaults to 'localhost'.
- If platform not found in list, returns a Platform error.
Tests added to ensure working as required.
These changes relate to Platform support #3453

job platforms: Forward lookup

---

cylc/flow/scheduler.py

Follow-up on comment from @wxtim on Riot.
> Should the exception at cylc/flow/scheduler.py:1700 leave traceback in the log? It looks like this is an inevitable and, presumably, accepted consquence of the way this is written?
@wxtim yes I think you're right, printing traceback isn't particularly helpful as there is nothing to be gained from the stack trace (we already know where the error came from) and it kinda makes it look like something went wrong with Cylc itself.
The `SchedulerError` class, despite its name, is actually used to implement user-defined shutdown behaviour for fail case scenarios.

suppress traceback for scheduler error

---

cylc/flow/data_store_mgr.py
cylc/flow/network/server.py
cylc/flow/scheduler.py
cylc/flow/tests/network/test_client.py
cylc/flow/tests/network/test_publisher.py
cylc/flow/tests/network/test_resolvers.py
cylc/flow/tests/network/test_server.py
cylc/flow/tests/network/test_subscriber.py
cylc/flow/tests/test_data_store_mgr.py

These changes partially address https://github.com/cylc/cylc-uiserver/issues/112
The `jobs` topic of the data store wasn't getting pruned, so the job elements were piling up:
```
data-store:   44.45 KB|edges: 32,    8.23 KB|families: 9,    1.70 KB|family_proxies: 45,   12.02 KB|jobs: 58,   11.74 KB|tasks: 8,    1.55 KB|task_proxies: 32,    7.48 KB|workflow: 1,   80     B|delta_times: 7,  960     B
data-store:   44.62 KB|edges: 32,    8.23 KB|families: 9,    1.70 KB|family_proxies: 45,   12.02 KB|jobs: 59,   11.91 KB|tasks: 8,    1.55 KB|task_proxies: 32,    7.48 KB|workflow: 1,   80     B|delta_times: 7,  960     B
data-store:   45.44 KB|edges: 32,    8.23 KB|families: 9,    1.70 KB|family_proxies: 45,   12.02 KB|jobs: 64,   12.73 KB|tasks: 8,    1.55 KB|task_proxies: 32,    7.48 …
```

Data store memory leak fixes

---

CHANGES.md
setup.py

These changes partially address #2572 
Updates `jinja2` requirement to **2.11.0** or greater, which effectively means **2.11.1** today, and `pyzmq` to **18.1.***, which means **18.1.0** today.

Update jinja2 and pyzmq, as well as some test/dev dependencies

---

cylc/flow/rundb.py

Left-over from #2800 #3361 . When migrating the code to SqlAlchemy was looking at their usages, but found nothing for `select_table_schema`. Then ran `vulture` against `rundb.py` (which I am a wee more familiar with now) and it pointed that `select_broadcast_events` was not used as well.
Waited for Travis CI to run on my fork before submitting. Should pass when it builds again this PR :crossed_fingers: 
Double checked using IDE, found no other usages with IDE code & file searches. 

Remove dead code in rundb

---

CHANGES.md
lib/cylc/gui/gscan.py

These changes close #3281
I am looking at the old GScan to understand how it creates the states + states totals (related to https://github.com/cylc/cylc-ui/issues/401), and also want to understand how Cylc 8's `cylc monitor` is doing that.
While doing it I remembered there was a bug in GScan regarding expanded rows. And since I had some experience with Cylc UI's tree and expanded/collapsed states decided to check if there was a simple fix. Took 20 mins after attaching a debugger to find one possible solution.
Not sure if the best one as I don't have a lot of experience with the old GUI, but just in case that's helpful.

[7.9.x] Fix expanded ids for GScan

---

cylc/flow/config.py

These changes close #3043 
See linked issue for more. The `else` statement is never used in our code. We never override the default value of the parameter removed.
And the code in the `else` statement would raise an error due to the unbound `ad_result` variable. This PR simply removes that code, and the parameter too. (I guess it should be safe, as we can use `git` to look at the old versions and re-implement the code if necessary?)

Remove unused code block, and function parameter in cylc.config

---

CHANGES.md
cylc/flow/batch_sys_handlers/slurm.py
cylc/flow/tests/batch_sys_handlers/test_slurm.py

The `%` character in `--output=...` and `--error=...` needs escape.

slurm: sbatch output/error: handle % character

---

CHANGES.md
lib/cylc/batch_sys_handlers/slurm.py
tests/jobscript/06-slurm-no-directives.t
tests/jobscript/06-slurm-no-directives/suite.rc

Back port of #3531. The `%` character in `--output=...` and `--error=...` needs escape.

7.8.x: slurm: sbatch output/error: handle % character

---

CHANGES.md
lib/cylc/batch_sys_handlers/slurm.py
tests/jobscript/06-slurm-no-directives.t
tests/jobscript/06-slurm-no-directives/suite.rc

Back port of #3531.
The `%` character in `--output=...` and `--error=...` needs escape.

7.9.x: slurm: sbatch output/error: handle % character

---

CHANGES.md
lib/cylc/config.py
tests/queues/03-warnings.t

These changes partially address #3470 (close after PR port to 7.9.x and master as well)

Queue warning

---

CHANGES.md
lib/cylc/config.py
tests/queues/03-warnings.t

These changes partially address #3470 (close after PR port to 7.8.x and master as well)
7.9.x port of #3539 (full description there)

Queue warning 79

---

CHANGES.md
cylc/flow/subprocpool.py
setup.py

These changes close #3535 
This is a potential fix for the infinite loop observed in the subprocpool process polling logic on darwin (BSD).
Not sure what is causing the bug, however, in the Cylc code it surfaces in `_poll_proc_pipes` where every time we go around the loop we get `data == ''` even long after the process has completed.

3535: prevent subprocpool infinite loop

---

cylc/flow/daemonize.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
cylc/flow/tests/test_scheduler.py
tests/cylc-run/02-format.t

These changes close #3451 
* Add a `--format` option to `cylc run`.
* Add `json` format which dumps the host,pid,port info to stdout.
* Testy test.
This should make the workflow spawner service slightly easier as otherwise we would have to go to the filesystem to get this information.

cylc run: parsable output

---

CONTRIBUTING.md
cylc/flow/cfgspec/suite.py
cylc/flow/parsec/upgrade.py
tests/deprecations/02-overwrite.t
tests/deprecations/02-overwrite/suite.rc

Replica of PR #3524 from 7.8.x, but with extra change to deal with `[scheduling][dependencies][X]graph -> [scheduling][graph]X` which is handled separately

Fix 3494 deprecation upgrade bug on master

---

cylc/flow/scheduler.py

Trivial change. While reviewing the main loop plugins, the IDE had a warning for this line (not in that PR). Probably a left-over from some other change.

Remove statement with no effect

---

.travis.yml
CONTRIBUTING.md
lib/cylc/network/port_scan.py

These changes partially address #3516
These changes close #3518

Forwards compatible fs search

---

cylc/flow/job_pool.py
cylc/flow/rundb.py
cylc/flow/scheduler.py
cylc/flow/scripts/cylc_client.py
cylc/flow/scripts/cylc_submit.py
cylc/flow/task_job_mgr.py
cylc/flow/tests/test_job_pool.py
cylc/flow/tests/util.py

This PR fixes a bug where no job display data is available on restart.
DB data is used to create job elements for display by WUI/TUI data-store on restart using DB data.
**Before**
**After**

Load DB jobs on restart

---

cylc/flow/tests/tui/test_data.py
cylc/flow/tests/tui/test_overlay.py
cylc/flow/tests/tui/test_util.py
cylc/flow/tui/app.py
cylc/flow/tui/data.py
cylc/flow/tui/overlay.py
cylc/flow/tui/util.py

These changes partially address #3529 
* Implement basic hard-coded mutations in Cylc Tui.
* Obtain cycle points using `cyclePoints: familyProxies(ids: ["root"])` trick.
* Bonus testing.
This should open up the path to getting Cylc out for alpha testing.

tui: mutations

---

.gitignore

I have a `cylc_flow.egg-info` directory that is not ignored on this branch (but is on master)

Ignore *.egg-info

---

CHANGES.md
lib/cylc/cfgspec/globalcfg.py
lib/cylc/tests/test_global_config.py

These changes close #3507 
In global config host settings, default-to-localhost was broken for list-valued items.  In the spec, these need to default to `None` (It was empty list looks like "item-set-to-nothing" rather than "item-not-set").
Apparently broken in 7.8.0 ?
Once finished, this needs to go to 7.9.x as well.  But not to master as the platforms changes will render this irrelevant there? - ping @wxtim

Fix global config default-to-localhost.

---

CHANGES.md

One review should do I think. Yesterday by change scrolled down the `CHANGES.md` and my eye immediately landed on a line with wrong PR number and link.
Did a quick regex parsing to locate other lines that were incorrect and prepared a quick PR :+1: 
Travis CI not important for this one.

Fix incorrect links for PRs in the changelog

---

cylc/flow/time_parser.py

Was reading the code while looking at what was not being unit tested (though it could). When I found this `expr_offset_item` being set twice. Clearly the second value is used, whilst the first is discarded.
Removing the first assignment of `expr_offset_item`, the code above it appears to be dangling, not in use, so it should be safe to remove it I guess?

Remove dead code in time_parser.py

---

etc/bin/run-functional-tests.sh

Fix tests which are testing for the presence of `$PWD` in output on platforms where `TMPDIR` is a symlink.
This will cause `etc/bin/run-functional-tests` to bail if `TMPDIR` is not defined, but actually that's quite nice as the tests would pass anyway.

portability: fix relpath related test failures

---

flakytests/events/05-timeout-ref-dummy/suite.rc
tests/authentication/basic/suite.rc
tests/authentication/override/suite.rc
tests/cli/00-cycle-points/suite.rc
tests/clock-expire/00-basic/suite.rc
tests/cylc-insert/04-insert-family/suite.rc
tests/cylc-insert/08-insert-family-compat/suite.rc
tests/cylc-trigger/03-edit-run.t
tests/cylc-trigger/03-edit-run/bin/my-edit
tests/cylc-trigger/03-edit-run/suite.rc
tests/cylc-trigger/07-edit-run-abort/bin/my-edit
tests/cylc-trigger/08-edit-run-host-select.t
tests/cylc-trigger/08-edit-run-host-select/bin/my-edit
tests/cylc-trigger/08-edit-run-host-select/suite.rc
tests/events/suite/hidden/shutdown/suite.rc
tests/events/suite/hidden/startup/suite.rc
tests/events/suite/hidden/timeout/suite.rc
tests/events/timeout-ref/suite.rc
tests/events/timeout/suite.rc
tests/host-select/00-simple/suite.rc
tests/intercycle/00-past/suite.rc
tests/intercycle/01-future/suite.rc
tests/message-triggers/00-basic/suite.rc
tests/remote/basic/suite.rc
tests/restart/pre-init-2/suite.rc
tests/shutdown/05-auto/suite.rc
tests/suite-state/upstream/suite.rc

* `true` is a shell builtin available everywhere.
* `/bin/true` is not available on all platforms.
* `/usr/bin/true` would appear to be present on most.
Options:
1) ~Change to `/usr/bin/true`.~ Not a valid option.
2) Change to `true`.
Happy to go either way.

portability: /bin/true -> /usr/bin/true

---

flakytests/database/00-simple.t
flakytests/database/01-broadcast.t
flakytests/database/02-retry.t
tests/database/03-remote.t
tests/lib/bash/test_header
tests/restart/34-auto-restart-basic.t
tests/restart/41-auto-restart-local-jobs.t
tests/restart/42-auto-restart-ping-pong.t

Unfortunately `hostname -f` does not always match `cylc.flow.hostuserutil.get_fqdn_by_host`.
This causes some tests to fail, I've observed this on:
* GitHub Actions - ubuntu-latest
* Mac OS

portability: add get_fqdn_by_host function

---

cylc/flow/data_messages.proto
cylc/flow/data_messages_pb2.py
cylc/flow/data_store_mgr.py
setup.py

These changes close #3589 
Held icons no longer linger in WUI/TUI  🎉 

protobuf 3.12 optional fields pre-release

---

.github/workflows/test.yml
cylc/flow/suite_db_mgr.py
tests/lib/bash/test_header
tests/shutdown/14-no-dir-check.t

These changes close #3590 
Bug allows `task_action_timers` DB table housekeeping to be skipped, so the table grows forever, and causes screeds of warning messages on restart.

Fix DB action timers housekeeping.

---

tox.ini

Allow the GH actions tests to pass by fixing an exclusion for the compiled protobuf file.
One review should be sufficient.

tox: exclude pb2.py

---

.github/workflows/test.yml

In our Github Actions setup: pycodestyle is running unnecessarily on the build directory:

Run pycodestyle only on cylc/flow (avoid build).

---

cylc/flow/cfgspec/globalcfg.py

Merge after #3619
This directive somehow slipped the net, it will cause cylc-doc to fail.
All done

config: remove todo directive

---

CHANGES.md
cylc/flow/config.py
cylc/flow/tests/test_config.py

This is a small change with no associated Issue.  Result of a user complaint today.
The following queue validation warning applies if the task `bar` (assigned to a queue) is not defined under `[runtime]` **or** if it is defined there but is simply not used in the graph:
```
WARNING - Queue configuration warnings:
+ q1: ignoring bar (task not defined)
```
On this branch, the warning in the latter case changes to: 
```
WARNING - Queue configuration warnings:
+ q1: ignoring bar (task not used in the graph)
```

Better queue config warning.

---

setup.py

Change from Protobuf pre-release #3594  to 3.12.1.
Compile with new resulted in no change:
```
(flow) sutherlander@cortex-vbox:flow$ protoc --experimental_allow_proto3_optional -I=./ --python_out=./ data_messages.proto
(flow) sutherlander@cortex-vbox:flow$ git status
On branch protobuf-3.12.1
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   ../../setup.py
no changes added to commit (use "git add" and/or "git commit -a")
(flow) sutherlander@cortex-vbox:flow$ protoc --version
libprotoc 3.12.1
```
One review will probably do.

Protobuf from pre-release to 3.12.1

---

cylc/flow/graph_parser.py
cylc/flow/scripts/cylc_report_timings.py
setup.py

I think we are being overly specific with dependency versions, particularly for testing.
We now have conflicting dependencies between different Cylc repositories which causes pip to install dependencies at undesirable versions which is worse than not version pinning at all.
Today's annoying conflict was between the version of pycodestyle used be Cylc-flow and flake8.

setup: loosen version pinning

---

cylc/flow/__init__.py
cylc/flow/data_store_mgr.py
cylc/flow/job_pool.py
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/prerequisite.py
cylc/flow/tests/network/test_resolvers.py
cylc/flow/tests/test_data_store_mgr.py
cylc/flow/tests/test_job_pool.py
cylc/flow/tui/util.py
tests/graphql/02-root-queries.t
tests/graphql/03-is-held-arg.t

This PR:
- Centralises the ID delimiter.
- Fixes bug in ID generated in prerequisites dump.
- Imports to functional tests
Sibling PR: https://github.com/cylc/cylc-uiserver/pull/140
(needs to be merge after this one)
The centralisation/put-at-lower-level is needed due to:
- A circular import error occurred while trying to fix the prerequisite dump. (ID_DELIM defined in `data_store_mgr`, but `prerequisites` is imported to `data_store_mgr` indirectly)
- Future proofing.
Justification for `cylc/flow/__init__.py` location:
- Not only used by tasks (i.e. shouldn't go in `cylc/flow/task_id.py`), used for workflow/jobs/families ...etc.
- Used by multiple modules (i.e. tasks/jobs/data-store/..etc) and UIS, but also as we become more event driven (i.e. the change in state might create a data …

Centralise general id delimiter

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/context_node.py
cylc/flow/parsec/config.py
cylc/flow/tests/parsec/test_config_node.py
cylc/flow/tests/test_context_node.py

Allow sections in the specification to inherit from other sections e.g:
```python
with Conf('foo.rc'):
with Conf('<animal>') as Animal:
Conf('legs', VDR.V_INTEGER, default=0)
Conf('noise', VDR.V_STRING)
with Conf('elephant', meta=Animal) as Elephant:
Conf('legs', VDR.V_INTEGER, default=4)
>>> Animal['legs'].default
0
>>> Elephant['legs'].default
4
>>> Elephant['noise'].default
None
```
This is desirable for defining `localhost` in the ongoing platforms work.
I've also converted `[cylc][main loop][health check]` to inherit from `[<plugin name>]`.
In the documentation the configuration is marked as inheriting from the template section and only configurations made on the new section are documented (as the inherited configurations are already documented in the template section).
> **Note** …

config node: inheritance

---

tests/broadcast/00-simple/suite.rc

Quick patch to prevent a test from failing as a result of https://github.com/cylc/cylc-flow/issues/3585.
Explanation: Those pesky bash filedescriptor lines are getting into a file which is compared to "known good output" during the test.
Simple fix, one review should be sufficient.

tests: broadcast/00 - patch for bash file descriptor bug

---

cylc/flow/task_message.py
cylc/flow/task_remote_mgr.py

* Fix Cylc remote functionality when `task communication method = poll`.
* Presently `remote_init` is getting skipped in this event.
* Use the presence of the `contact` file to determine when to use TCP messaging.
* Presently TCP messaging is always attempted which results in traceback.
* Since the removal of `contact2` (a good thing) we need a new indicator of comms method, ATM we only have polling and TCP so the presence of the `contact` will do. We will need to review this when we add tcp+ssh as a method.
Example development configuration for a remote host with polling:
```ini
[hosts]
[[ubuntu]]
task communication method = poll
execution polling intervals = 5*PT1S, 5*PT5S, PT15S
submission polling intervals = PT1S
```

remote_init: prevent init skipping for polling configurations

---

cylc/flow/tests/conftest.py
cylc/flow/tests/test_host_select.py
cylc/flow/tests/test_host_select_remote.py
cylc/flow/tests/test_rundb.py
cylc/flow/tests/util.py

By popular demand, some sort of explanation...
* Document the `mock_glbl_cfg` fixture.
* Move the fixture into the `conftest.py` file (so you don't have to import it to use it).
* Remove the `setup_global_config` fixture
* We will want to revive this for the integration test battery.
* Best remove it here to prevent integration tests creeping into the unittests.

tests: document mock_glbl_cfg fixture

---

cylc/flow/cycling/iso8601.py

* Replace the old custom `memoize` decorator with the built-in `functools.lru_cache`.
* Cache `is_on_sequence`.
* This saves ~40s CPU time for the complex suite which is ~7% of total CPU.

iso8601 cycler: lru_caching

---

tests/restart/bad-job-host/suite.rc

Test is flaky especially when run in a group.
flaky flow could get stuck with a running task which has actually
succeeded but is not pollable due to a bad hostname

tests: fix tests/restart/13

---

cylc/flow/remote.py

Remove logging which is causing some remote tests to fail.
After this change there should be three failure under `tests/` (fixes upcoming in a future PR):
* `tests/cylc-submit/01`
* `tests/cylc-submit/04`
* `tests/cylc-cat-log/09`
Kinda hard to review, here's an example of a test which would fail before:
* `tests/cylc-kill/00`

remote: remove debug logging to fix tests

---

tests/lib/bash/test_header
tests/restart/34-auto-restart-basic.t
tests/restart/35-auto-restart-recovery.t
tests/restart/41-auto-restart-local-jobs.t
tests/restart/42-auto-restart-ping-pong.t

These are nasty timing-dependent tests, at some point they have become broken, the functionality they are testing is fine though!
This should make them a bit more robust.

tests: fix auto restart tests

---

cylc/flow/profiler.py

The `--profile` options has been broken since the original Python3 upgrade (sorry).
I've not added any tests as I'm not sure what the future for this option is or what the role of on-board profiling will be in Cylc's asynchronous future. Standard profiling libraries may be better placed to take on this role, but for now...
Profiling results look a bit different then they did at Cylc7 largley due to changes in code structure:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000   58.706   58.706 /home/oliver/cylc-flow/cylc/flow/scheduler.py:1503(run)
4    0.000    0.000   58.704   14.676 /home/oliver/miniconda3/envs/cylc8/lib/python3.7/asyncio/base_events.py:533(run_until_complete)
4    0.001    0.000   58.703   14.676 …
```

profiler: use psutil

---

cylc/flow/hostuserutil.py

Whoops, I didn't fix it properly, again, sorry 😐.
But to confirm that it's definitely back the way it was:
```diff
$ git diff 8.0a1 cylc/flow/hostuserutil.py 
diff --git a/cylc/flow/hostuserutil.py b/cylc/flow/hostuserutil.py
index b992d70e0..1b0bfc37d 100644
--- a/cylc/flow/hostuserutil.py
+++ b/cylc/flow/hostuserutil.py
@@ -1,7 +1,5 @@
-#!/usr/bin/env python3
-
-# Copyright (C) 2008-2019 NIWA & British Crown (Met Office) & Contributors.
+# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
```

hostuserutil: fix accidental breakage

---

cylc/flow/network/authentication.py
cylc/flow/network/client.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
cylc/flow/suite_files.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_cmd.py
cylc/flow/task_remote_mgr.py
cylc/flow/tests/network/key_setup.py
cylc/flow/tests/network/test_client.py
cylc/flow/tests/network/test_server.py
cylc/flow/tests/network/test_zmq.py
tests/cylc-scan/02-sigstop.t

These changes close #3499 and #3443 
Client keys are now being generated on remote platforms - private keys are now not travelling!
Instead, server generates a pair of keys, platform generates a pair of keys. The public keys are transferred.

Generate client keys on remote platforms

---

cylc/flow/network/authentication.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
tests/authentication/03-check-keys-local.t
tests/authentication/04-check-keys-remote.t

These changes follow on from Generate client keys on remote platforms #3608  
These changes close #3660
Note to reviewers - my functional tests need checking. I'm very much a novice at writing these and have probably made some mistakes! Sorry in advance.

Remove scheduler keys on shutdown

---

setup.py

Fix the unit tests to deal with a change in isodatetime.
In retrospect, maybe we should have released this as `2.1.0`. My bad, anyway, for now this is a simple, if crude fix.
We should upgrade isodatetime in 8.0a3.

setup: pin isodatetime

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/parsec/fileparse.py
tests/cylc-get-site-config/06-cylc-conf-path.t

Fiddle the way we interpret `CYLC_CONF_PATH`.
* If specified it must exist
* If it's not readable you get and error because thats your fault
* It can specify a file or a directory
* also use pathlib because it's pretty
> **FYI:** The immediate motivation for this change is to allow the integration tests to use the `flow-tests.rc` file which is not really possible at the moment as you cannot change `CYLC_CONF_PATH` from within pytest as the global configuration has already been loaded.

CYLC_CONF_PATH: modify interpretation

---

tests/functional/cylc-get-site-config/06-cylc-conf-path.t

Reinstate test accidentally deleted during conflict resolution on the integration battery branch - sorry.
Well spotted @TomekTrzeciak.

tests: reinstate tests/f/cylc-get-site-config/06

---

.github/PULL_REQUEST_TEMPLATE.md

A change for the pull request template, so that if we change `setup.py`, we are reminded to create an issue with the change.
When someone prepares the next conda release, s/he can go through the open issues, and update the recipe. We cannot prepare a PR as if merged that could create a new release.
Noticed we now have quite a few items in the template. Maybe for this one we could have just the `[ ] Created an issue blabla`, and the OP can choose whether to check or not that box. Same for changelog? That would be less 2 checks required :grimacing:

Update PR template for conda-forge files

---

CHANGES.md
cylc/flow/cfgspec/globalcfg.py
tests/functional/rnd/01-editors.t

From the platforms proposal document: https://cylc.github.io/cylc-admin/proposal-config-changes.html#editors

conf: default to $EDITOR/$GEDITOR

---

cylc/flow/option_parsers.py
cylc/flow/scheduler_cli.py

Quick change to highlight bash comments in CLI usage.
The idea is to improve the readability of examples e.g:
```bash
Lorel ipsum dolor sid amet apising elit.
Examples:
$ foo bar baz
$ bar baz pub
```
To reduce any unwanted effects this only highlights comments which are prefixed by spaces or on lines beginning with `$` i.e:
```
$ foo # will highlight
foo # won't highlight 
```
We can re-format CLI help as and when.
Caveats:
* I've picked `$` for `$PS1` since this is the most common choice (I know total [bashism](https://linux.die.net/man/1/checkbashisms) right).
* The `--help` text will come out in colour whether you want it or not.

cli: highlight comments in usage strings

---

cylc/flow/scheduler.py

The integration test changes accidentally broke the restart `remote-init` functionality, this aught to fix it.
The contact file can't be written until the TCP servers have started which now happens later on in the process than it did before.
This bug is covered by the remote tests (e.g. `tests/f/restart/26`) which should fail on master at the moment.

scheduler: remote-init after server start

---

CHANGES.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/suite.py
cylc/flow/config.py

- Cycle points now obey value specified in global config
- Suite cfgspec default `False` no longer overrides value specified in global config file
These changes close #3631 

Fix global UTC mode bug

---

cylc/flow/data_messages.proto

(brought up here: https://github.com/cylc/cylc-flow/pull/3515#discussion_r444628940)
A warning to leave the field number of in-use fields alone (no tidying or re-indexing to remove gaps or order the fields after addition):
https://developers.google.com/protocol-buffers/docs/proto3#assigning_field_numbers

add protobuf field number warning

---

cylc/flow/tui/data.py
cylc/flow/tui/util.py
tests/unit/tui/test_util.py

Given a multiple parents, i.e.:
```
[[qux]]
inherit = FAM4
[[[meta]]]
description = "some task qux"
[[[environment]]]
GREETING = "Hello from qux!"
[[qaz]]
inherit = FAM4, FAM
[[[meta]]]
description = "some task qaz"
[[[environment]]]
GREETING = "Hello from qaz!"
[[[outputs]]]
trigger1 = "data ready"
[[qar]]
inherit = FAM, FAM5, FAM4
[[[meta]]]
description = "some task qar"
[[[environment]]]
GREETING = "Hello from qar!"
[[[outputs]]]
trigger1 = "data ready"
```
The visual parent in TUI could be any one of those in the inheritance, because the node `task.parents` doesn't conserve order:
This PR fixes the issue by using `task.firstParent` field instead:

fix tui task parent grouping

---

setup.py

When building the Conda metapackage, we are seeing issues when instead of 2.0.1, we get 2.0.2 installed.
We should be able to use 2.0.* (i.e. any 2.0.x release). Although I think we had some breaking changes in 2.0.2 by accident (exceptions changed somewhere I think?).

Use any 2.0.x version of metomi-isodatetime

---

cylc/flow/data_store_mgr.py
cylc/flow/network/graphql.py
tests/functional/graphql/02-root-queries.t

This is a small change containing a fix for the issue described here:
https://github.com/cylc/cylc-ui/pull/458#issuecomment-663472156
The data-store family nodes have been reduced to only the first parent ancestors of the graphed tasks.

Reduce data-store family nodes to first parent ancestors

---

cylc/flow/host_select.py
tests/unit/test_host_select.py

`socket.gethostbyname_ex` raises `socket.gaierror` in the event that a hostname is not recognised e.g. `socket.gethostbyname_ex('elephant')`, however, this behaviour it would appear, is dependent on network configuration/platform.
I don't think anything is *depending* on this behaviour ATM so I'm whipping out the tests (which can fail) and updating the docs in this PR.

host-select: remove the assurance of socket.gaierror

---

cylc/flow/graphnode.py

This is a small change with no associated Issue; it follows https://github.com/cylc/cylc-flow/pull/3515#pullrequestreview-457277970 
Converts a variable (assigned from an `re` match group) from `^` (character) or `None`, to boolean type as per expectations based on name and use of the variable.  This should not result in any functional change as the variable is only used in tests of the kind `if var: ...`.
If tests pass, one review should be enough.

Fix ICP offset var type.

---

tests/unit/parsec/test_jinja2support.py

There would appear to be a platform-dependent bug in this test. On my system the python syntax error causes the test to fail. It seems that this doesn't happen on all platforms. Not sure what's going on here, easy solution is to fix the test, which I've done in the second commit. I also upgraded from unittest to pytest in the process.

Fix jinja2 test failures

---

.github/workflows/test.yml

Cylc should support 3.7+.
As previously discussed we should run the unittests against all supported versions.

actions: run unittests against all supported python versions

---

tests/unit/test_job_file.py

Change test write job file to just check non-empty file is created, rather than tying it to a size of file which can change on updated cylc version. 

Make write jobfile test more robust

---

tests/integration/README.md
tests/unit/README.md

Worked out why we weren't able to disable distribution using `-n0` (as documented in pytest-xdist), it's because of the `--dist` option specified in `pytest.ini` which is set to ensure that tests in the same module get run together (which is needed for the integration tests as otherwise module-level fixtures would compete with each other from different processes).
There is an issue up on pytest to make `--dist=no` implicit with `-n0` but for now lets just document the current workaround.

tests: document how to turn xdist off

---

CHANGES.md
cylc/flow/config.py
cylc/flow/unicode_rules.py
tests/functional/validate/73-xtrigger-names.t

C-lose https://github.com/cylc/cylc-flow/issues/3703 (master)
Companion to: https://github.com/cylc/cylc-doc/pull/140
Validate xtrigger names to prevent nasty runtime issues.

xtriggers: validate labels (master)

---

CHANGES.md
doc/src/external-triggers.rst
lib/cylc/config.py
lib/cylc/unicode_rules.py
tests/validate/73-xtrigger-names.t

Closes ~~3707~~ #3703 (7.8.x, 7.9.x)
Back port of #3732 with:
* Some of the unicode_rules stuff stripped out.
* Fstrings converted to `%` syntax.
* Manual docs.

xtriggers: validate labels (7.8.x)

---

CONTRIBUTING.md
lib/cylc/gui/view_tree.py

gui: fix tree-view out-of-sequence tasks caused by default sorting on wrong column index
Unclear as to the reason why this bug does not show up with newer versions of Python or GTK, but this fixes the problem on my end and does not appear to hurt anything else.
These changes close #3698 

Bugfix: cylc-gui - tasks momentarily out of sequence

---

.github/workflows/bash.yml
dockerfiles/bash/Dockerfile
dockerfiles/bash/build-bash
dockerfiles/bash/build-bash-versions

Related to #3572
This PR uses a Docker image with several versions of bash (3.2, 4.2, 5.0) and sets up Python and a few more Linux utilities to enable Cylc Flow to run (re-using work from the SLURM PR #3521).
It would take too long to run the test battery for each bash version, so I was thinking more along the lines of selecting a few (5-20) tests that were useful for confirm the `job.sh` and other Shell-related features/code in Cylc 8 work correctly with different versions of `bash`.
Docker image and Travis implementation based on [bashup's excellent CI setup](https://github.com/themattrix/bashup). 
We could have other Bash versions, but not being very familiar with Bash or Shell, I chose the versions above without thinking too hard :grimacing: 

Test Cylc with different bash versions

---

setup.py

Closes https://github.com/cylc/cylc-flow/issues/3776
> Either limit upper version of pytest-xdist, or upgrade pytest to fix setuptools issue
¿Porque no los dos?

setup: bump pytest version

---

cylc/flow/cycling/iso8601.py

Sibling PR: https://github.com/cylc/cylc-doc/pull/141
Fix a new and interesting bug which effects non-gregorian date-time cycling modes, but only on certain days of the month, such as, conveniently, today, the 31st.
Spotted in this test, but may effect others:
```
tests/f/special/07-clock-triggered-360.t
```
The issue has surfaced now since the recent change to isodatetime which means that out-of-bounds date-times (e.g. the 31st of Feb) are rejected on sight. The `ingest_time` logic was attempting to load todays date into a different calendar which causes trouble, if say, it's the 31st of the month and you are using a 360 day calendar.

cyclers: fix ingest_time

---

cylc/flow/taskdef.py
tests/functional/spawn-on-demand/08-lost-parents.t
tests/functional/spawn-on-demand/08-lost-parents/flow.cylc
tests/functional/spawn-on-demand/08-lost-parents/reference.log

This change addresses a bug (and untested functionality, evidently) found by @TomekTrzeciak in https://github.com/cylc/cylc-flow/issues/3740#issuecomment-669130391
In the following example, `bar` should trigger off of `foo` in the first 3 cycles, then subsequent `bar`'s should trigger automatically (no parents):
```
R3//P1 = "foo => bar"
P1 = "bar"
```
On this branch it works, but on master the scheduler shuts down finished after cycle point 3.
Since spawn-on-demand we auto-spawn parent-less tasks when their previous instance leaves the runahead pool (they have no parents to spawn them "on demand").  In this example, `bar.3` has a parent (`foo.3`) but `bar.4` has no parents and so has to be auto-spawned.  To do this, when `bar.3` leaves the runahead pool we look at the next cycle point …

Fix sequence bounds check for parent tasks.

---

tests/functional/spawn-on-demand/08-lost-parents/flow.cylc
tests/functional/spawn-on-demand/08-lost-parents/reference.log

Small follow-up to #3756 - makes the new test more stringent by briefly bringing back the parent task (so, a task has to be spawned on demand by a parent for a few cycles, then auto-spawned, then on demand again, then auto-spawned until FCP). @oliver-sanders - one brief sanity check will do (this was semi-inspired by your test case on 3756).

Upgrade one functional test.

---

cylc/flow/network/server.py

Remove the `task identifier` reference which has somehow become broken.
Since this interface is going to get deleted shortly the simple solution is just to remove the problem.

fix broken references

---

cylc/flow/scheduler.py
tests/functional/startup/01-log-flow-config.t

A few things slipped the net in #3755 
These changes partially address #3689 

Rename _rc -> _config

---

CHANGES.md
cylc/flow/__init__.py
cylc/flow/config.py
cylc/flow/scripts/cylc_message.py
cylc/flow/scripts/cylc_set_verbosity.py
cylc/flow/task_events_mgr.py
cylc/flow/unicode_rules.py
tests/unit/test_suite_files.py
tests/unit/test_unicode_rules.py

These changes close #3428 
Task messages, e.g. in
```
[runtime]
[[my_task]]
[[[outputs]]]
foo = I am an invalid task message: the colon is to blame
```
can only have colons in them if the first part of the message is a logging severity level plus colon, e.g. `INFO:`, because everything before the first colon is treated as a severity level.
This PR causes validation to fail if colons are misused.

Validate task messages

---

.github/workflows/bash.yml
CHANGES.md
cylc/flow/network/__init__.py
cylc/flow/network/client.py
cylc/flow/network/graphql.py
cylc/flow/network/resolvers.py
cylc/flow/scheduler.py
cylc/flow/scripts/cylc_ping.py
cylc/flow/task_pool.py
cylc/flow/task_remote_mgr.py
cylc/flow/tui/tree.py
cylc/flow/xtrigger_mgr.py
cylc/flow/xtriggers/suite_state.py
tests/functional/cylc-ping/00-simple/flow.cylc

`cylc ping --verbose five` is broken :cry: 
```bash
(venv) kinow@ranma:~/Development/python/workspace/cylc-flow$ cylc ping five --verbose
2020-08-29T23:25:03+12:00 DEBUG - Loading site/user config
files
2020-08-29T23:25:03+12:00 DEBUG - zmq:send {'command':
'ping_suite', 'args': {}, 'meta': {'prog': 'cylc-ping', 'host': 'ranma'}}
2020-08-29T23:25:03+12:00 DEBUG - zmq:recv {'data': True,
'user': 'kinow'}
File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-ping", line 11, in <module>
load_entry_point('cylc-flow', 'console_scripts', 'cylc-ping')()
File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/terminal.py", line 183, in wrapper
wrapped_function(*wrapped_args, …
```

Fix cylc ping verbose (and a few minor docs improvements)

---

tests/flakyfunctional/cyclers/19-async_integer.t
tests/functional/cylc-cat-log/02-remote-custom-runtime-viewer-pbs.t
tests/functional/cylc-cat-log/02-remote-custom-runtime-viewer-pbs/flow.cylc
tests/functional/cylc-poll/06-loadleveler.t
tests/functional/cylc-poll/06-loadleveler/flow.cylc
tests/functional/cylc-poll/07-pbs/flow.cylc
tests/functional/cylc-poll/08-slurm/flow.cylc
tests/functional/cylc-poll/09-lsf/flow.cylc
tests/functional/cylc-poll/17-pbs-cant-connect.t
tests/functional/cylc-poll/17-pbs-cant-connect/flow.cylc
tests/functional/directives/00-loadleveler.t
tests/functional/directives/loadleveler/flow.cylc
tests/functional/directives/pbs/flow.cylc
tests/functional/directives/slurm/flow.cylc
tests/functional/events/suite/flow.cylc
tests/functional/job-file-trap/01-loadleveler.t
tests/functional/job-file-trap/01-loadleveler/flow.cylc
tests/functional/job-kill/00-local/flow.cylc
tests/functional/job-kill/02-loadleveler.t
tests/functional/job-kill/02-loadleveler/flow.cylc
tests/functional/job-kill/03-slurm/flow.cylc
tests/functional/job-kill/04-pbs/flow.cylc
tests/functional/jobscript/00-torture/flow.cylc
tests/functional/startup/01-log-flow-config.t

I missed a set of tests (mainly those dependent on batch systems that I don't have immediate access to) when I created the platforms work. This PR attempts to remedy this failure.
Additionally, I messed up tests `tests/functional[job kill|directives]/[loadleveler|slurm|lsf|pbs]` because in many cases these have a single test with different `flow.cylc` files for each batch system: I had hardcoded the batch system name into the `global.cylc` file created in the base test which would have broken all the tests which were symlinked to it.
Review -
Unless you happen to have the batch system in question set up locally you probably cannot check that these tests actually work so this review may need to be a proof-read and sanity check only. (Slurm tests work at the Met Office)

Platforms.fix tests

---

cylc/flow/async_util.py
cylc/flow/network/scan.py

Just noticed a warning which can occur if `scandir` attempts to scan an empty directory.
I think this is harmless ATM as the only use of `scandir` is workflow scanning, if a workflow dir is empty then it's not a workflow dir so can be safely skipped.
Also add a small update post-#3755.

async util: handle empty dirs better

---

CHANGES.md
cylc/flow/cfgspec/suite.py
cylc/flow/config.py
cylc/flow/data_messages.proto
cylc/flow/job_file.py
cylc/flow/job_pool.py
cylc/flow/network/schema.py
cylc/flow/parsec/upgrade.py
cylc/flow/task_job_mgr.py
tests/functional/param_expand/03-env-tmpl/flow.cylc
tests/integration/test_job_pool.py
tests/unit/test_config.py
tests/unit/test_config_upgrader.py
tests/unit/test_job_file.py

This is #3784 ported to master. These changes address #3446
Merge `[runtime][X][parameter environment templates]` into `[runtime][X][environment]` so that users can choose the order of definition of the variables.
- Any valid Python template in the `[environment]` section that matches a parameter will be interpolated/substituted.
- An existing `[parameter environment templates]` section in a suiterc will get prepended to `[environment]` to maintain backwards compatibility with the current behaviour.

Deprecate [runtime][X][parameter environment templates]

---

.github/workflows/test.yml

The github action was still using the old `cylc scan -f` syntax.

actions: fix debug step

---

.github/workflows/test.yml
cylc/flow/unicode_rules.py
tests/unit/README.md

I noticed that the doctests don't seem to be run on GH Actions.

GH Actions: run doctests

---

cylc/flow/async_util.py
tests/integration/conftest.py
tests/integration/test_scan_api.py

**built on #3805**
On master you get some cryptic feedback when running tests:
```console
$ pytest tests/i/test_scan_api.py
...
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() done, defined at /Users/oliver/miniconda3/envs/cylc8/lib/python3.7/asyncio/queues.py:150> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() running at /Users/oliver/miniconda3/envs/cylc8/lib/python3.7/asyncio/queues.py:159> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ffa32096dd0>()]>>
Exception ignored in: <coroutine object Queue.get at 0x7ffa32042dd0>
...
```
These `Queue.get` tasks appear to be orphaned, since we only use `asyncio.Queue` in one place I'm guessing this is the …

Task was destroyed but it is pending

---

cylc/flow/task_message.py

Found this one yesterday while reviewing @dwsutherland 's #3757 . I think there was some change in `task_message.py` but on different lines (IOW this was not part of his change, so I added a post-it to review this separately later)
I think if you have 2 messages, one with one severity level, and the other with another severity level, then you could miss flushing one of the handle/streams.

Write to stream, then flush

---

cylc/flow/network/schema.py

Noticed a but when looking up node relationships via the `workflow` parent while resolving GraphQL queries.. This PR addresses this.
One review should do.

fix resolve via workflow parent lookup

---

CHANGES.md
lib/cylc/scheduler.py

Small bug in the auto-restart logic which has gone unnoticed since its creation.
Before attempting auto-restart Cylc is supposed to wait for all locally running jobs (i.e. those submitted via background or at) on the suite host to finish.
Unfortunately this functionality is somewhat overzealous and is waiting for all jobs submitted via background or at *on any host* to complete before restarting.
Some users have exceptionally long-running background jobs (pollers) which have highlighted this bug.

7.8.x: auto-restart: only wait for local jobs running on localhost

---

CHANGES.md
cylc/flow/scheduler.py

Cylc8 port of https://github.com/cylc/cylc-flow/pull/3814.
Before attempting auto-restart Cylc is supposed to wait for all locally running jobs
(i.e. those submitted via background or at) on the suite host to finish.
Unfortunately this functionality is somewhat overzealous and is waiting for all jobs
submitted via background or at on any host to complete before restarting.
Some users have exceptionally long-running background jobs (pollers) which
have highlighted this bug.

auto-restart: only wait for local jobs running on localhost

---

CHANGES.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/scripts/cylc_get_site_config.py
etc/bin/run-functional-tests
tests/functional/cylc-get-site-config/00-basic.t
tests/functional/lib/bash/test_header
tests/unit/parsec/test_config.py

These changes close #3689
> Cylc will attempt to load the global configuration (``global.cylc``) from a hierarchy of locations, including the site directory (defaults to ``/etc/cylc/flow/``) and the user directory at ``~/.cylc/flow/``. E.g. for Cylc version 8.0.1, the hierarchy would be, in order of ascending priority:
>
> * ``${CYLC_SITE_CONF_PATH}/global.cylc``
> * ``${CYLC_SITE_CONF_PATH}/8/global.cylc``
> * ``${CYLC_SITE_CONF_PATH}/8.0/global.cylc``
> * ``${CYLC_SITE_CONF_PATH}/8.0.1/global.cylc``
> * ``~/.cylc/flow/global.cylc``
> * ``~/.cylc/flow/8/global.cylc``
> * ``~/.cylc/flow/8.0/global.cylc``
> * ``~/.cylc/flow/8.0.1/global.cylc``
>
> A setting in a file lower down in the list will override the same setting from those higher up (but if a setting is present in a file higher up …

Global config hierarchy

---

cylc/flow/network/scan.py
tests/integration/test_scan_api.py
tests/integration/utils/flow_tools.py

Last minute fiddling on my scan PR created a somewhat odd bug which caused the scan client to miss any hierarchically registered suites (note the unit tests have logic to check for hier suites and were still passing 😕).
This is a nice logic simplification removing an unnecessary queue and the related lag it caused, why did I use a queue there, no idea, what was I thinking‽
Added an integration test to make doubly sure hier logic is preserved.

scan: fix hierarchically registered suites

---

cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py

Follow up to #3791 focused on comments from @oliver-sanders reproduced here:
The log messages contain a bit of duplicated info and could do with being tidied up a bit:
```
DEBUG - ['bash', '-c', 'echo
localhost']
DEBUG - [remote-host-select cmd] bash -c
'echo localhost'
[remote-host-select ret_code] 0
[remote-host-select out] localhost
DEBUG - for task foo.1: platform =
$(echo localhost) evaluated as localhost
```
One message should suffice for this case, note the second log message comes from the subprocpool and contains all the required info.
```
DEBUG - Traceback (most recent call
last):
File "/Users/oliver/cylc-flow/cylc/flow/task_job_mgr.py", line 866, in
_prep_submit_task_job
platform = get_platform(rtconfig)
File "/Users/oliver/cylc-flow/cylc/flow/platforms.py", line 82, in …
```

Cleaned up logging a little

---

tests/functional/platforms/05-host-to-platform-upgrade-fail.t
tests/functional/platforms/05-host-to-platform-upgrade-fail/flow.cylc

@datamel found a test which hung rather than worked as desired. On examination I also fixed:
- Incorrect tab size for project.
- Added a grep to ensure that the suite had failed for the reason we are testing for.
- Added a description of the workflow to the metadata section of the test `flow.cylc`

test-fix: platforms/05

---

tests/flakyfunctional/modes/03-dummy-env.t
tests/flakyfunctional/modes/03-dummy-env/flow.cylc

Follow up a larger PR on #3482 
I do not believe that previously there was any test that dummy-local turns off pre and post scripts.

Improve the thoroughness of dummy-local functional test

---

cylc/flow/platforms.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py
tests/functional/job-submission/18-platform_select.t
tests/functional/job-submission/18-platform_select/flow.cylc
tests/unit/test_platforms_get_platform.py

Fix: #3825 , subsidiary response to #3672 
Built on #3791 
In Cylc 7 the host setting for a task could be set as a bash subshell either in the form
```bash
$(my-command)   # or
`my-command`
```
my-command```. @dpmatthews proposes dropping support for the backtick ``my-command`` syntax for platforms at Cylc 8. 
Reasons why:
- This is very, very old syntax.
- Handling of single quotes and backslash escaping inside backticks is horrible.
- Nested backticks are hard to read.
- Backticks are visually difficult to distinguish from single quotes.
- Backticks are increasingly rarely used.

Platforms.eval platform cmd.no backticks

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/suite.py
cylc/flow/network/authorisation.py
cylc/flow/network/server.py
tests/functional/deprecations/01-cylc8-basic.t
tests/functional/deprecations/01-cylc8-basic/flow.cylc

Refers to Cylc8 [Config Proposal agreed at CylcCon Wellington](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-config-changes.md#cylcforce-run-mode--required-run-mode---obsolete).
Do we want to attach a follow on to carry out more heavy-duty removal of this functionality?

flow-cfg-update.authentication

---

cylc/flow/cfgspec/suite.py
cylc/flow/config.py
cylc/flow/etc/syntax/cylc.lang
cylc/flow/etc/syntax/cylc.xml
cylc/flow/scheduler.py
tests/flakyfunctional/execution-time-limit/04-poll.t
tests/functional/broadcast/08-space.t
tests/functional/deprecations/01-cylc8-basic.t
tests/functional/deprecations/01-cylc8-basic/flow.cylc
tests/functional/hold-release/18-hold-cycle-globs.t
tests/functional/hold-release/19-no-reset-prereq-on-waiting.t
tests/functional/lib/bash/test_header
tests/functional/modes/01-dummy.t
tests/functional/modes/01-dummy/flow.cylc

Partially addresses #3696 #3690 
Refers to Cylc8 [Config Proposal agreed at CylcCon Wellington](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-config-changes.md#cylcforce-run-mode--required-run-mode---obsolete).
[cylc]force run mode & required run mode -> obsolete

workflow config update: remove force/require run mode

---

doc/src/suite-config.rst

Because Sphinx turns every heading into a reference within the scope of the current document this link was referencing the section it is contained in.
> **Cylc7 doc reminder:** `cd doc; make html; <browser> build/build/html/index.html`

docs: fix link to external triggers

---

CHANGES.md
cylc/flow/network/schema.py
cylc/flow/task_state.py
cylc/flow/task_state_prop.py
cylc/flow/tui/app.py
cylc/flow/tui/overlay.py
tests/functional/graphql/01-workflow.t
tests/functional/startup/00-state-summary.t

Since spawn-on-demand, there is no `runahead` task state anymore - instead, `waiting` tasks hidden in the runahead pool.

Remove last vestiges of the runahead task state.

---

CHANGES.md
cylc/flow/rundb.py
tests/functional/broadcast/14-broadcast-checkpoint.t
tests/functional/broadcast/14-broadcast-checkpoint/flow.cylc

Found an issue with IDE about the `id_key` not being used. Looking at the query generated, it was always returning all the broadcast states, regardless of the ID I selected, e.g. `cylc ls-broadcast five 1`.

Use the ID key when querying for broadcast checkpoints

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/suite.py
cylc/flow/etc/syntax/cylc.lang
cylc/flow/etc/syntax/cylc.xml
cylc/flow/scheduler.py
cylc/flow/suite_events.py
cylc/flow/task_events_mgr.py
tests/functional/cylc-get-config/00-simple/section2.stdout
tests/functional/deprecations/01-cylc8-basic.t
tests/functional/deprecations/01-cylc8-basic/flow.cylc
tests/functional/deprecations/01-cylc8-basic/validation.stderr
tests/functional/events/09-task-event-mail.t
tests/functional/events/09-task-event-mail/flow.cylc
tests/functional/events/18-suite-event-mail.t
tests/functional/events/18-suite-event-mail/flow.cylc
tests/functional/events/29-task-event-mail-1/flow.cylc
tests/functional/events/30-task-event-mail-2.t
tests/functional/events/30-task-event-mail-2/flow.cylc
tests/unit/test_suite_events.py

Closes #3691 
These changes partially address issue described in [the config changes summary](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-config-changes.md#cylceventsmail----schedulermail)
[cylc][events]mail * -> [scheduler][mail]
mail from, mail smtp, mail to and mail footer can apply to both scheduler and task events so move them to a separate section and remove mail from the name. 
[cylc]task event mail interval -> [scheduler][mail]task event batch interval
I got rid of the `mail retry delays` config item too.
reference [discussion](https://github.com/cylc/cylc-flow/pull/3348#discussion_r333229597)

move [cylc][events]mail (.*) -> [cylc][mail]

---

CHANGES.md
cylc/flow/network/scan.py
cylc/flow/suite_files.py
tests/unit/test_suite_files.py

These changes close #3835
This PR prevents registering a suite in a subdirectory of another run directory, or registering a suite in a directory whose children contain a run directory. It does this by checking upwards for the existence of a flow config file or a `.service` dir in successive parent dirs up to the cylc run dir, as well as checking downwards in subdirectories to a depth of 4 (the default `cylc scan` depth).

Disallow nested run directories

---

CHANGES.md
setup.cfg

These changes close #3713 
`author_email` is one of the keys available for `pip`'s packaging metadata. But it is not mandatory (see https://github.com/pypa/pip/blob/50aca38eafde71ac0314d14246f7ebf043695f5e/src/pip/_vendor/distlib/metadata.py#L620 for the mandatory ones—couldn't find in their docs, had to locate in the code :cry: )
The `author_email` requires a valid [RFC-822](https://packaging.python.org/specifications/core-metadata/#author-email) address. Since we are not using Google Groups, and Discourse does not offer an e-mail address, I think the best option is to simply remove it.
If users want to get in contact, they will need to visit our project URL (which is in the packaging metadata) and find how to reach us.

Remove author_email from our Python packaging metadata

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/suite.py
tests/functional/deprecations/00-pre-cylc8.t
tests/functional/deprecations/00-pre-cylc8/flow.cylc

These changes probably close #3690 
- I'm happy about the items I have removed from `cylc/flow/cfgspec/suite.py`.
- I'm happy that I have removed items from `tests/functional/deprecations/01...`
- I'm more uncertain about how I've dealt with the global config deprecation items - I don't think that the config object can do without an upgrader, and I was loathe to remove too much infrastructure, because I imagine that after the clean break between Cylc7 and Cylc8 we might want to be able to carry out upgrades to `global.cylc` and `user.cylc` in future.

Config.remove old deprecations

---

cylc/flow/scripts/cylc_cat_log.py

Fix a bug in `cylc cat-log` detected in remote tests.
Likely a rebase error.

cat-log: fix probable rebase error

---

CHANGES.md
cylc/flow/network/graphql.py
tests/unit/network/test_graphql.py

Fail the query with a helpful message if the variables defined do not match the expected values

---

.github/workflows/test.yml

This is a small change with no associated Issue. 1 reviewer should be enough.
See [the GitHub changelog announcement](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) and [the docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable).

GH Actions: Upgrade deprecated add-path command

---

cylc/flow/network/schema.py
cylc/flow/scripts/cylc_set_outputs.py
cylc/flow/task_pool.py

Related to https://github.com/cylc/cylc-ui/pull/504
The `setOutputs` mutation has no required fields which means that on the surface it looks like something you can do without providing any input (like `kill` or `trigger`).

schema: move default into schema for set-outputs

---

.github/workflows/bash.yml
.github/workflows/test.yml

This is how GH actions handles experimental [Java](https://github.com/apache/commons-imaging/blob/752c546f711a6f27ab71ef7e720de1a9b8826a4d/.github/workflows/maven.yml) versions. I guess it should work with [Python](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-preventing-a-specific-failing-matrix-job-from-failing-a-workflow-run) versions too…

Add Python 3.9 for unit tests in CI (experimental, do not stop other builds if it fails)

---

CHANGES.md
CONTRIBUTING.md
tests/unit/test_hostuserutil.py

Changed the test test_get_fqdn_by_host_on_bad_host to check the exception thrown by socket.gethostbyname_ex using a regex to account for variations in error message returned in different environments.
Also changed the test to use a context manager to test whether an exception is raised. This should prevent the test from incorrectly passing if no exception is thrown.
These changes close #3916.

Fix bad host test

---

cylc/flow/data_store_mgr.py

Small change to use the output message instead of the graph label, as the key to the task outputs:
```
[[wiz]]
pre-script = sleep 2
post-script = sleep 2; cylc message "B I N G O"
[[[meta]]]
description = "first task wig"
[[[environment]]]
GREETING = "Hello from wig!"
[[[outputs]]]
bingo = "B I N G O"
```

Use message not label for API task outputs

---

cylc/flow/scheduler_cli.py

Mop up from #3899 
Fix reinvocation of `cylc run|restart` using the `--host` option.
This was broken because we used to use commands like `cylc-run` whereas we now use `cylc run` so the argument list is one shorter than it was before.

cli: fix --host reinvocation

---

tests/functional/lib/bash/test_header

Typo, missing `_` means that it is attempting to purge local platforms (i.e. ssh'ing when not necessary).

tests: correct purge logic for local platforms

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/suite.py
cylc/flow/parsec/upgrade.py
cylc/flow/scheduler.py
cylc/flow/task_events_mgr.py
tests/functional/cylc-get-config/00-simple/section2.stdout
tests/functional/deprecations/01-cylc8-basic/flow.cylc
tests/functional/deprecations/01-cylc8-basic/validation.stderr
tests/functional/events/09-task-event-mail.t
tests/functional/events/09-task-event-mail/flow.cylc
tests/functional/events/18-suite-event-mail.t
tests/functional/events/18-suite-event-mail/flow.cylc
tests/functional/events/29-task-event-mail-1.t
tests/functional/events/29-task-event-mail-1/flow.cylc
tests/functional/events/30-task-event-mail-2.t
tests/functional/events/30-task-event-mail-2/flow.cylc
tests/unit/parsec/test_upgrade.py

global:
- `[task events]mail smtp` -> obsolete
- `[task events]mail retry delays` -> obsolete
flow:
- `[cylc][events]mail smtp` -> obsolete
- `[runtime][X][events]mail smtp` -> obsolete

Finish off mail config changes

---

.github/workflows/bash.yml
.github/workflows/test_functional.yml

@oliver-sanders this just adds an artifact upload section to the bash test config.  Hoping it'll allow us to diagnose the `broadcast/00-simple` test problem.  See comments from here: https://github.com/cylc/cylc-flow/pull/3933#issuecomment-725800905  The change looks simple but all I did was copy your section from the other file, so you'd best check it.
[UPDATE: now for bash and main functional test actions]

Upload cylc-run artifact on test fail.

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/loggingutil.py
cylc/flow/pathutil.py
cylc/flow/subprocpool.py
etc/bin/run-functional-tests
tests/flakyfunctional/events/44-timeout.t
tests/flakyfunctional/job-submission/18-check-chunking.t
tests/flakyfunctional/job-submission/19-chatty.t
tests/functional/events/47-long-output.t
tests/functional/job-submission/16-timeout.t
tests/functional/lib/bash/test_header
tests/functional/logging/03-roll.t
tests/unit/test_pathutil.py

These changes partially address #3696
- `process pool *` -> `[scheduler]process pool *`
- `[suite logging]` -> `[scheduler][logging]`
- `run directory rolling archive length` -> `[scheduler]run directory rolling archive length`
Also the `test_header` function `create_test_global_config` has been simplified to only arg which is appended to the user's global config, as there are no longer any top-level global config items that would need to be prepended.

Global config changes: process pool, logging

---

cylc/flow/host_select.py
cylc/flow/remote.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/cat_log.py
cylc/flow/scripts/check_versions.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py

* Make the default way of constructing / running ssh stuff platform orientated.
* Prefix the underlying primitive "host" commands with `_` to make the danger (no platform conf) clear.

remote: clarify platform/host commands

---

cylc/flow/scripts/__init__.py
cylc/flow/scripts/cylc.py
tests/functional/cli/01-help.t

Supersedes #3950 
```
$ cylc --version
8.0a3.dev
$ cylc version
8.0a3.dev
$ cylc version --long  # conda environment
8.0a2 (/home/oliverh/miniconda3/envs/cylc-8.0a2)
$ cylc version --long  # "pip install ." with venv in git clone
8.0a3.dev (/home/oliverh/cylc/cylc-flow.git/venv)
```
Path reported is the top level of the virtual environment, for both conda and Python venv.
@kinow - you might want a quick re-review since I've gone back to the more conventional `--long` option.

Cylc version long take 2

---

cylc/flow/task_remote_cmd.py
tests/unit/test_task_remote_cmd.py

While debugging a different issue, I noticed that remote init was not correctly failing. 
It was printing `REMOTE INIT FAILED` but not returning, hence, continuing making keys and also printing `REMOTE INIT DONE`, resulting in the workflow continuing, incorrectly.
To test this bug...
1. On master, create a key in the .service directory of the workflow you will run in step 2, something like `client_wrong.key` would work.
2. Run your workflow (should have a task to run on the remote).
The workflow does not raise an error correctly, and just carries on.

Fix remote init failures

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/host_select.py
cylc/flow/hostuserutil.py
cylc/flow/main_loop/auto_restart.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
tests/flakyfunctional/restart/39-auto-restart-no-suitable-host.t
tests/flakyfunctional/restart/40-auto-restart-force-stop.t
tests/functional/lib/bash/test_header
tests/functional/restart/34-auto-restart-basic.t
tests/functional/restart/35-auto-restart-recovery.t
tests/functional/restart/37-auto-restart-delay.t
tests/functional/restart/38-auto-restart-stopping.t
tests/functional/restart/41-auto-restart-local-jobs.t
tests/functional/restart/42-auto-restart-ping-pong.t
tests/functional/restart/43-auto-restart-force-override-normal.t
tests/functional/suite-host-self-id/00-address.t
tests/integration/conftest.py
tests/unit/network/test_publisher.py
tests/unit/test_host_select.py
tests/unit/test_host_select_remote.py

These changes partially address #3696
They are last changes earmarked for the global config 🎉

move suite servers to scheduler section of global config

---

cylc/flow/suite_files.py

This code should probably have been removed in the pr which removed get_auth_items (https://github.com/cylc/cylc-flow/pull/3509)
This is a very small change with no associated Issue.

Remove redundant _dump_item method

---

usr/bin/cylc

New `cylc` wrapper for Cylc 8 conda and pip virtual envs.
Based on @dpmatthews original, tweaked a bit.
With this installed in `$PATH`:
- no need to activate venvs manually, the wrapper does it for you
- select versions via `CYLC_VERSION` (releases) or `CYLC_HOME` (between-release venvs in a git clone, e.g.)
- jobs can automatically see the same cylc as their parent scheduler, without hardwiring a single version in your environment
- supports release-version venvs name `cylc-$CYLC_VERSION` ~~and `cylc-flow-$CYLC_VERSION`~~
Need upcoming PR to divorce jobs from scheduler environment (later today...) to test this properly (currently on master local jobs inherit the scheduler's venv, which get in front of the wrapper in `$PATH`).
Documented in comments in the file, for now (explaining it …

Update cylc wrapper.

---

.github/workflows/test_functional.yml
CHANGES.md
cylc/flow/etc/cylc-bash-completion
cylc/flow/pathutil.py
cylc/flow/platforms.py
cylc/flow/scripts/clean.py
cylc/flow/suite_files.py
setup.cfg
tests/functional/cylc-clean/00-basic.t
tests/functional/cylc-clean/test_header
tests/unit/test_pathutil.py
tests/unit/test_suite_files.py

These changes partially address #3887
> 1. Remove stopped workflows on the local scheduler filesystem
Implements a new command
```
$ cylc clean workflow_name
```
Note: Cleaning remote directories will come in a later PR.

cylc clean - initial implementation

---

CHANGES.md
lib/cylc/suite_db_mgr.py
lib/cylc/task_events_mgr.py
lib/cylc/task_pool.py

Follow-on from #3597
Close #3818 
Only write task event timers to the database when they have changed.
Currently the entire DB table is rebuilt twice per main loop even when the scheduler is inactive or stalled.

db: only write task event timers when changed

---

cylc/flow/batch_sys_handlers/loadleveler.py
cylc/flow/batch_sys_handlers/lsf.py
cylc/flow/cfgspec/suite.py
cylc/flow/config.py
cylc/flow/data_store_mgr.py
cylc/flow/task_job_mgr.py
tests/functional/cylc-get-config/00-simple/section2.stdout
tests/functional/deprecations/01-cylc8-basic/flow.cylc
tests/functional/deprecations/01-cylc8-basic/validation.stderr
tests/functional/validate/23-fail-old-syntax-7/flow.cylc

These five items needed to be moved from `[scheduling][TASK][job]` to `[scheduling][TASK]`:
* execution polling intervals
* execution retry delays
* execution time limit
* submission polling intervals
* submission retry delays

Move items from [task][job] to [task]

---

tests/flakyfunctional/execution-time-limit/00-background.t
tests/functional/cylc-poll/06-loadleveler.t
tests/functional/directives/00-loadleveler.t
tests/functional/execution-time-limit/02-slurm.t
tests/functional/execution-time-limit/03-pbs.t
tests/functional/job-kill/02-loadleveler.t

A few batch sys tests were broken, likely a rebase error.
The way tests are skipped is an especially nasty feature of the test framework, will address when converting to pytest whenever that happens.

tests: fix disabled batch sys tests

---

cylc/flow/main_loop/auto_restart.py

@oliver-sanders  - I think this is a 1-person review. Tag someone if you disagree.

Fix docstring broken WRT config changes

---

CHANGES.md
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py

These changes close #3946
<kbd>Ctrl</kbd>+<kbd>C</kbd> was failing to shutdown the scheduler on Python 3.8+ due to the fact that `asyncio.CanclledError` changed from subclassing `Exception` to `BaseException`. See https://stackoverflow.com/a/60167684/3217306 and https://docs.python.org/3.8/library/asyncio-exceptions.html#asyncio.CancelledError
I'm new to asyncio, and there seems to be another way of handling signal interruptions: https://www.roguelynn.com/words/asyncio-graceful-shutdowns/. However, the changes I've made are very simple and seem to work.

Fix failure to shutdown on keyboard interrupt

---

cylc/flow/batch_sys_handlers/at.py
cylc/flow/batch_sys_handlers/background.py
cylc/flow/batch_sys_handlers/loadleveler.py
cylc/flow/batch_sys_handlers/lsf.py
cylc/flow/batch_sys_handlers/moab.py
cylc/flow/batch_sys_handlers/pbs.py
cylc/flow/batch_sys_handlers/sge.py
cylc/flow/batch_sys_handlers/slurm.py
cylc/flow/cfgspec/globalcfg.py
cylc/flow/main_loop/__init__.py

Fixes the cylc-flow side of the documentation failures. After this to get the docs building again a small number of references to configurations in cylc-doc need to be updated.

doc: fix documentation in source files

---

cylc/flow/remote.py
cylc/flow/scheduler.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_cmd.py
cylc/flow/task_remote_mgr.py
tests/flakyfunctional/events/01-task.t
tests/functional/remote/04-symlink-dirs.t
tests/functional/restart/53-task-prerequisites.t

Moves rsync to the subprocpool.
These changes close Rsync to subprocpool #3840.

Rsync to subprocpool

---

cylc/flow/data_store_mgr.py
cylc/flow/scripts/cylc.py
cylc/flow/task_job_mgr.py
tests/flakyfunctional/xtriggers/01-suite_state.t
tests/functional/platforms/02-host-to-platform-upgrade.t
tests/functional/platforms/05-host-to-platform-upgrade-fail.t
tests/integration/test_data_store_mgr.py
tests/integration/test_scan.py
tests/unit/main_loop/auto_restart.py
tests/unit/main_loop/main_loop.py
tests/unit/test_host_select.py
tests/unit/test_host_select_remote.py
tests/unit/test_loggingutil.py
tests/unit/test_platforms.py
tests/unit/test_platforms_get_platform.py
tests/unit/test_remote.py
tests/unit/test_task_remote_cmd.py
tests/unit/test_templatevars.py

Yesterday ran the IDE linter against Cylc UI, and started doing the same with Cylc Flow. There are two issues it found that might be bugs, but they require understanding about the task pool (which is great for me learning :grimacing: probably bothering @hjoliver and others soon in Element).
This PR fixes typos, removes unused imports, and also renames two test functions that had duplicated names. They are pretty similar, but not identical, so I left both of them.
If CI passes, I think one review should be enough.

Fix typos and unused imports

---

cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/scheduler.py
cylc/flow/scripts/poll.py
cylc/flow/task_job_mgr.py

Remove the (inactive) `--succeeded` option to `cylc poll`.
This does not make sense post-SoD since there aren't any succeeded tasks in the pool anyway.

poll: remove poll_succ option

---

tests/functional/cylc-run/03-remote-run-host.t

Follow up to #3992, this patch partially address #3910

Fix reference to batch sys -> job runner

---

cylc/flow/job_runner_handlers/slurm.py

Follow up to #4004, this fix allows the docs to build

job runner: mop up: mop up

---

README.md

I noticed the documentation badge on README was pointing to a 404 page

Fix docs status badge on README

---

.github/workflows/1_create_release_pr.yml
.github/workflows/2_auto_publish_release.yml
.github/workflows/update_copyright.yml
CHANGES.md
README.md
cylc/flow/scripts/__init__.py

Automated release process and auto update copyright year

---

cylc/flow/config.py
cylc/flow/job_pool.py
cylc/flow/parsec/fileparse.py
cylc/flow/scheduler.py
cylc/flow/scripts/message.py
cylc/flow/suite_db_mgr.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py

Follow on from: https://github.com/cylc/cylc-flow/pull/3992#discussion_r542490192
Use a standard marker for indicating backwards compatibility in code. Its a totally arbitrary marker, all that matters is that we standardise and record the important information to avoid some of the issues weve had in the past with back-compat lasting longer than inteded.
In the process fix a few cases of back-compat which *should* have been removed already but was missed!

BACK COMPAT: remove old compat and update comments

---

CHANGES.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/job_runner_handlers/background.py
cylc/flow/job_runner_mgr.py
cylc/flow/scripts/jobs_submit.py
cylc/flow/task_job_mgr.py
tests/flakyfunctional/events/01-task.t
tests/flakyfunctional/events/01-task/flow.cylc
tests/flakyfunctional/job-submission/19-chatty.t
tests/functional/api-suite-info/00-get-graph-raw-1.t
tests/functional/api-suite-info/02-get-graph-raw-3.t
tests/functional/api-suite-info/03-get-graph-raw-4.t
tests/functional/job-submission/07-multi.t
tests/functional/job-submission/18-clean-env.t
tests/functional/job-submission/18-clean-env/flow.cylc
tests/functional/shutdown/12-bad-port-file-check/flow.cylc
tests/functional/shutdown/13-no-port-file-check/flow.cylc

Close #3710 
Close #3487 
Supersede #3712 
Global config platform settings to divorce job submission subprocesses from the parent environment (which for local jobs, means the scheduler environment). 
The "impasse" referred to here https://github.com/cylc/cylc-flow/pull/3712#issuecomment-678092052 was resolved (duh) by having the scheduler read relevant global config and pass the `clean_env` flag and associated environment variable names and executable paths to the job host by new `cylc jobs-submit` command line options.

Clean job submission environment.

---

cylc/flow/exceptions.py
cylc/flow/parsec/fileparse.py
cylc/flow/scripts/install.py
tests/unit/plugins/test_pre_configure.py

Closes https://github.com/cylc/cylc-rose/issues/9
Catch errors from plugins and wrap them in a Cylc error with plugin context. Should be good enough for now.
*Example `rose-suite.conf`*:
```ini
[jinja2:suite.rc]
Y=X
```
*Output:*
```console
$ cylc install .
PluginError: Error in plugin cylc.post_configure.rose
jinja2:suite.rc=Y=X: Invalid template variable: X
Must be a valid Python or Jinja2 literal (note strings "must be quoted").
```

pre_configure: capture plugin error

---

cylc/flow/terminal.py

Reported by @dpmatthews, emacs implemets `stty size` but in a broken way:
```console
$ stty size
0 0
```
Return the defined default if we get 0.
Workaround:
`alias emacs=vim`

terminal: hack around stupid emacs stty return value

---

tests/functional/rose-conf/04-opts-set-from-env/opt/rose-suite-Gaelige.conf

Master currently failing test `tests/functional/rose-conf/04-opts/set-from-env`
This is caused by in-line comment.
This may need to be addressed if it is something we need to support - quick fix for now.

remove inline #

---

tests/unit/test_hostuserutil.py

Had much fun debugging my network to find out that my ISP was very helpfully redirecting all failed DNS requests to an IPA in Ireland that is listed on malicious IP databases as being associated with DNS spoofing, thanks ISP!
To save others going though this I've added a note to the unit test where the problem is likely to be spotted first.
Converted unittest => pytest in the process.

tests/u: add note about ISP DNS meddling

---

cylc/flow/task_job_mgr.py
tests/functional/platforms/03-platform-db.t
tests/functional/platforms/03-platform-db/flow.cylc

Fixes a bug where there incorrect platform is stored in the database.
To recreate the bug - run the functional test included in PR without the fix: i.e. line 311 in `task_job_mgr.py`  :  `'platform_name': platform['name']`.

Fix database platforms bug

---

.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
etc/conf/macos-patch

Bar the outstanding DNS issue and after a spate of portability changes Cylc Flow now supports MacOS nicely.
Add `macos-latest` into the CI tests:
* All unit and integration tests
* Some of these required fixing for MacOS
* Recent example of a portability test fix - https://github.com/cylc/cylc-flow/pull/3917
* The first 1/4 of functional tests
* Running the whole test battery would be a bit much.
To sidestep the DNS issue this PR applies the [`cylc.flow.hostuserutil`](https://github.com/cylc/cylc-flow/issues/2689#issuecomment-715161888) I've been using for local development over the last year.

actions: run tests on macos

---

cylc/flow/platforms.py
tests/unit/test_platforms.py

These changes close #3812 
From `cylc/flow/parsec/OrderedDictWithDefaults.py`:
```
def keys(self):
"""Include the default keys, after the list of actually-set ones."""
```
Thus in my code `set(OrderedDictA) ≠ set(OrderedDictA.keys())`. When I originally wrote this code I had not realized that this was the case, and had failed to notice the divergence from standard dict behavior. I had done much of my testing using dicts in plact of OrderedDictWithDefault. In most cases this is fine, but here is an example of a bug which slipped through as a result.

Fix OrderedDictWithDefault comparison mistake

---

CHANGES.md
cylc/flow/config.py
cylc/flow/scripts/validate.py
tests/unit/test_config.py

These changes close #3869
> Cyclic graph validation can be quite slow and is currently included as part of `--strict`
This PR (last one of 2020!) introduces an option `--check-circular` to `cylc validate`. If the number of tasks is less than the limit (100), checking for circular graph will always happen. If the number is above the limit, the check will be skipped (with a warning) unless `--check-circular` is used.

validate: do not check for circular/cyclic graph if size is above limit

---

CHANGES.md
cylc/flow/scheduler_cli.py
cylc/flow/scripts/broadcast.py
cylc/flow/scripts/ext_trigger.py
cylc/flow/scripts/hold.py
cylc/flow/scripts/kill.py
cylc/flow/scripts/poll.py
cylc/flow/scripts/release.py
cylc/flow/scripts/reload.py
cylc/flow/scripts/remove.py
cylc/flow/scripts/set_outputs.py
cylc/flow/scripts/set_verbosity.py
cylc/flow/scripts/stop.py
cylc/flow/scripts/trigger.py
cylc/flow/task_message.py

These changes close #4010 
It seems that passing a reg with a trailing slash to the `mutations_kwargs` dict was the reason for this bug. As such I've fixed it everywhere I found a `mutations_kwargs` dict.
Does this need a functional test?

Fix trailing slash in reg (workflow name) bug

---

cylc/flow/platforms.py
tests/unit/test_platforms.py

It was noted by @MetRonnie that the function `get_platform_from_job_info`: Logic checking that items in the job section of the old style config weren't being checked for a match/mismatch against platform spec.

Platforms.fix generic items match

---

cylc/flow/task_job_mgr.py
tests/functional/remote/01-file-install.t
tests/functional/remote/05-remote-init.t
tests/functional/remote/05-remote-init/flow.cylc
tests/functional/remote/05-remote-init/reference.log

Fixes a bug whereby tasks were being grouped by install target when grouping by platform was required.
Also fixes a bug whereby the database was not being updated correctly. 
NOTE: This will be required before beta.

Fix remote init by platform

---

cylc/flow/tui/overlay.py

Keybinding is different in MacOS Terminal.app.

tui: update help for MacOS

---

tests/functional/lib/bash/test_header

Address a potential infinite loop in the test battery spotted whilst debugging hanging tests.

tests: make purge safer

---

CHANGES.md
cylc/flow/scheduler.py
tests/flakyfunctional/shutdown/00-rm-db.t

Detecting whether a workflow is still running or has shut down relies on checking for the existence of a contact file. However, before this PR, when shutting down a workflow, the contact file would get removed before shutting the database, which led to the small possiblity of problems (e.g. if the database is deleted in this short time, it would get regenerated).
This PR reverse the order, so any DB connections are definitely closed when the contact file is removed and the workflow is considered to have shut down.

Shutdown: remove contact file after closing DB connection

---

tests/functional/cylc-install/03-file-transfer.t

Tree command in Cylc install was resulting in inconsistent results based on terminal settings. Adds UTF8 to tree command, standardising the output.
Thanks to @wxtim. 

Add utf8 to tree command

---

cylc/flow/platforms.py
cylc/flow/task_remote_cmd.py
cylc/flow/task_remote_mgr.py
tests/functional/cylc-ping/04-check-keys-remote.t
tests/unit/test_platforms.py

I have kept basic functionality. This will need looking at again once the intelligent host command has been implemented, so we can adapt the tidy in case where platform fails. I have left this as a basic fix as this may be replaced by some version of `cylc clean`.

Fix Remote Tidy

---

CHANGES.md
cylc/flow/scripts/install.py
tests/functional/cylc-clean/00-basic.t
tests/functional/cylc-install/03-file-transfer.t

built on: https://github.com/cylc/cylc-flow/pull/4000
sibling: [cylc-rose PR20](https://github.com/cylc/cylc-rose/pull/20)
These changes partially address #3819 
These changes are downstream of changes in (cylc-rose:#20)[https://github.com/cylc/cylc-rose/pull/20]. The PR attempts to add command line options similar to the following `rose suite-run` options:
- `--opt-conf-key`
- `--defines`
- `--suite-defines`

Cli setting of rose opts

---

cylc/flow/scheduler.py
tests/functional/cylc-run/04-no-install.t

Fixes a bug where flows written directly in the `cylc-run` directory fail to run first time, however, succeed on subsequent attempts:
```console
$ cylc run one 
...
TypeError: expected str, bytes or os.PathLike object, not NoneType
2021-02-05T15:42:17Z CRITICAL - Suite shutting down - expected str, bytes or os.PathLike object, not NoneType
2021-02-05T15:42:17Z INFO - DONE
$ cylc run one 
...
*** listening on tcp://olivers-macbook-pro.local:43074/ ***
*** publishing on tcp://olivers-macbook-pro.local:43059 ***
...
```
The directory logic was being performed before the Scheduler.install logic had completed which was causing the issue.

run: fix un-installed flows

---

cylc/flow/cfgspec/suite.py

Small change, realised that there is nothing in the config docs to explain the irregular behaviour of recurrence settings (now that they are settings not sections) so added a quick note.

cfg: document recurrence graph addition in config

---

cylc/flow/network/scan.py
tests/integration/test_scan.py

Tweak `cylc scan` to handle `cylc install` run dir structure.
Currently on master:
```
$ cylc scan --state=all
foo/runN  # oops!
foo/run2
foo/run1
foo/_cylc-install/source  # oops!
```
```
$ cylc scan --state=all
foo/run2
foo/run1
```
Any suggestion on best way to test that cylc scan detects only what we want it to?

scan: avoid runN and source links

---

CHANGES.md
cylc/flow/etc/cylc-bash-completion
cylc/flow/scheduler.py
cylc/flow/scripts/reinstall.py
cylc/flow/suite_files.py
setup.cfg
tests/functional/cylc-install/00-simple.t
tests/functional/cylc-install/01-symlinks.t
tests/functional/cylc-install/02-failures.t
tests/functional/cylc-install/03-file-transfer.t
tests/functional/cylc-reinstall/00-simple.t
tests/functional/cylc-reinstall/01-file-transfer.t
tests/functional/cylc-reinstall/02-failures.t
tests/functional/cylc-reinstall/test_header
tests/functional/lib/bash/test_header
tests/unit/test_suite_files.py

Follows on from Cylc Install (https://github.com/cylc/cylc-flow/pull/4000)
Users can now reinstall an already installed workflow using the `cylc reinstall` command.
Proposal: https://github.com/cylc/cylc-admin/blob/master/docs/proposal-rose-suite-run.md
__________________________________________________________________
Example use cases:
`cylc install myflow`
`cylc reinstall myflow/run1`
`cylc install myflow --no-run-name`
`cylc reinstall myflow`
`cylc reinstall` from within an installed flow in the cylc run dir.
___________________________________________________________________
New reinstall log added in log directory: log/install/timestamp-reinstall.log
I have also addressed an issue (related change, https://github.com/cylc/cylc-flow/pull/4000#pullrequestreview-577209692) with the …

Cylc Reinstall

---

cylc/flow/cfgspec/suite.py
cylc/flow/parsec/validate.py
tests/functional/deprecations/01-cylc8-basic/validation.stderr

Updated docs for config sections moved from [runtime][job] to runtime.
Updated docs for parsec time interval list type to include reference to multipliers.

Added missing documentation for `flow.cylc`

---

.github/workflows/test_functional.yml

Trying to stop `_remote_background_indep_poll` from timing out so often

GH Actions: Increase functional test timeout

---

cylc/flow/suite_files.py

These changes close [Cylc-rose issue 36](https://github.com/cylc/cylc-rose/issues/36) in combination with [Cylc Rose PR 38](https://github.com/cylc/cylc-rose/pull/38)

Install rose suite.conf in cylc rose

---

cylc/flow/scripts/tui.py
cylc/flow/tui/app.py
etc/bin/shellchecker

Address a minor point on the beta-0 roadmap.
Add a warning about using with large flows until we get it delta-driven.
See https://github.com/cylc/cylc-flow/issues/3527
One off-topic change, got shellchecker to skip the `.git` dir.

Tui: warn about large flows

---

CHANGES.md
cylc/flow/parsec/fileparse.py
cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py
tests/unit/plugins/test_pre_configure.py

Tidy up some naming conventions for Cylc-rose. 
Companion [PR 40 for cylc-rose](https://github.com/cylc/cylc-rose/pull/40)

Cylc.rose pre release refactor

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/job_file.py
cylc/flow/remote.py
tests/functional/job-submission/18-clean-env.t
tests/functional/jobscript/00-torture.t
tests/unit/test_job_file.py

sibling: https://github.com/cylc/cylc-doc/pull/206
Small change that came out of `comms mode = ssh` discussions.
The `cylc executable` config is a bit strange, for remote `cylc` invocations the `cylc executable` is used, however, for job scripts the containing directory is added to the `$PATH`.
We have had to add a check in multiple places to make sure that the `cylc executable` isn't set to something which isn't `cylc`.
This PR:
* Changes `cylc executable` to `cylc path`.
* Documents the role of `cylc path` in the job script.
* Corrects the `use login shell` docs for the profile files that are sourced.

conf: cylc executable => cylc path

---

CHANGES.md
cylc/flow/network/schema.py
tests/unit/network/test_schema.py

These changes close #4114 
Transferred from Cylc UI Server repository as I realized the change had to be done in the Cylc Flow schema.

Raise an error when invalid sort keys are provided by a GraphQL client

---

cylc/flow/data_store_mgr.py

data_store: remove prparing as a job state

---

CHANGES.md
cylc/flow/cfgspec/suite.py
cylc/flow/etc/job.sh
cylc/flow/job_file.py
tests/functional/cylc-get-config/00-simple/section2.stdout
tests/functional/restart/34-auto-restart-basic.t
tests/functional/restart/35-auto-restart-recovery.t
tests/functional/restart/37-auto-restart-delay.t
tests/functional/restart/38-auto-restart-stopping.t
tests/functional/restart/42-auto-restart-ping-pong.t
tests/functional/restart/43-auto-restart-force-override-normal.t
tests/unit/test_job_file.py

These changes partially address #3696 : They are the last config change on the checklist there. 🎉 
That is:
- Remove, and add obseletion warning for config item `flow.cylc:[runtime][__TASK__][remote]suite definition directory` (But _not_ the similar platform item from `global.cylc`).
- Remove CYLC_SUITE_DEF_PATH environment variable.
- Remove CYLC_SUITE_DEF_PATH_ON_REMOTE_HOST environment variable.
Additionally I fixed a few tests broken by the change of default behavior to preventing implicit tasks. (@MetRonnie  Please extra double check these.)

Make obsolete `[runtime][][remote]suite definition directory`

---

cylc/flow/tui/util.py

Spotted whilst reviewing a PR with Tui, I had never gotten around to slapping a "natural sort" on tui tasks/cycles, easy fix.
Sort tasks and cycle points "naturally" (e.g. "9" should come before "10").

tui: apply natural sorting to tasks and cycles

---

cylc/flow/platforms.py
cylc/flow/scheduler_cli.py
cylc/flow/task_remote_cmd.py
cylc/flow/task_remote_mgr.py
tests/unit/test_task_remote_cmd.py

The aim of this PR is to ensure the reason for remote init failures is documented in the workflow log.
This PR also adds an additional check for the `client_public_keys` directory on the remote which will catch misconfigurations of the install target for platforms which share fs with localhost.

Make remote init return messages more informative

---

CHANGES.md
lib/cylc/review.py
lib/cylc/review_dao.py

These changes partially address #4113 - Depending upon discussion on that issue, this may be a complete solution.

Allow Cylc Review to access Cylc 8 Workflow data.

---

cylc/flow/scheduler_cli.py

PR: https://github.com/cylc/cylc-flow/pull/4138 added logging exceptions. This additional logging is making the logs look messier than necessary.
The reason this was added was due to an error added at cylc-tidy stage (scheduler side), was not appearing in logs for some reason. This needs further investigation (I will open an issue)

Remove error logging

---

cylc/flow/cfgspec/globalcfg.py
tests/unit/conftest.py
tests/unit/scripts/test_config.py

Required for: https://github.com/cylc/cylc-uiserver/pull/192
Required for us to use `CYLC_SITE_CONF_PATH` to source the global config for the UIS.
* Look for global config in `${CYLC_SITE_CONF_DIR}/flow/global.cylc`.
* This is to allow this env var to be used by other cylc components - namely the UIS.
* Tried to match the annotations from #4099 to minimise diff.
To explain the `:envvar:` stuff - https://github.com/cylc/cylc-doc/issues/226

CYLC_SITE_CONF_PATH: look in flow sub-dir

---

INSTALL.md
README.md

In #4008 I fixed broken documentation badges in README, however the links I added were to the 8.0a2 release. I've moved the documentation badges to under the Cylc7 and Cylc8 sections and made the links correspond
Update - needs:

Edit documentation links/badges in README

---

cylc/flow/cfgspec/suite.py
cylc/flow/platforms.py
tests/unit/cfgspec/test_suite.py
tests/unit/test_platforms.py
tests/unit/test_platforms_get_platform.py

Move validation-y parts of `get_platform()` to their own functions. Changes should help improve type safety.

Slight platforms refactor

---

cylc/flow/cfgspec/suite.py
cylc/flow/platforms.py
tests/unit/test_platforms_get_platform.py

A couple of docstrings that I thought could be better.
One person review.
Please squash on merge.

Docstring changes

---

cylc/flow/scripts/cylc.py
setup.cfg
tests/functional/cli/01-help.t

List installed plugins in `cylc version --long`.
Addresses https://github.com/cylc/cylc-admin/issues/76.
```console
$ cylc version --long
8.0b0 (/Users/oliver/miniforge/envs/cylc8)
Plugins:
cylc-rose       0.1.0   /Users/oliver/cylc-rose
cylc-uiserver   0.3.0   /Users/oliver/cylc-uiserver
Entry Points:
cylc.command:
hub = cylc.uiserver.scripts.hub:main
uiserver = cylc.uiserver.scripts.uis:main
cylc.post_install:
rose_opts = cylc.rose.entry_points:post_install
cylc.pre_configure:
rose = cylc.rose.entry_points:pre_configure
```
Plugins are detected providing that they provide at least one `cylc.*` entry point and are not contained within the `cylc.flow` distribution.
> **Context:**
> 
> We have now settled on the following points which we weren't clear on near the start of the project:
> * …

cli: list installed plugins and entry points

---

CHANGES.md
cylc/flow/__init__.py
cylc/flow/config.py
tests/functional/api-suite-info/00-get-graph-raw-1/flow.cylc
tests/functional/api-suite-info/01-get-graph-raw-2/flow.cylc
tests/functional/api-suite-info/02-get-graph-raw-3/flow.cylc
tests/functional/api-suite-info/03-get-graph-raw-4/flow.cylc
tests/functional/broadcast/00-simple/flow.cylc
tests/functional/broadcast/10-file-1/flow.cylc
tests/functional/broadcast/11-file-2/flow.cylc
tests/functional/broadcast/12-file-stdin/flow.cylc
tests/functional/broadcast/13-file-cancel/flow.cylc
tests/functional/reload/02-content/flow.cylc
tests/functional/reload/04-inheritance/flow.cylc
tests/functional/reload/05-graphing-simple/flow.cylc
tests/functional/reload/06-graphing-fam/flow.cylc
tests/functional/reload/07-final-cycle/flow.cylc
tests/functional/reload/08-cycle/flow.cylc
tests/functional/reload/12-remove-task/flow.cylc
tests/functional/reload/13-add-task/flow.cylc
tests/functional/reload/16-remove-add-alter-task/flow.cylc
tests/functional/reload/18-broadcast-insert/flow.cylc
tests/functional/reload/garbage/flow.cylc
tests/functional/reload/runahead/flow.cylc

Deprecate `CYLC_SUITE_DEF_PATH`.
It is now an alias for `CYLC_SUITE_RUN_DIR`.

CYLC_SUITE_DEF_PATH

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/pathutil.py
tests/unit/test_pathutil.py

Small change, removes `run directory rolling archive length` from config and associated functionality. This has already been removed in Cylc 7, see https://github.com/cylc/cylc-flow/pull/3326.
These changes close https://github.com/cylc/cylc-flow/issues/4033

Remove run dir housekeeping

---

CHANGES.md
cylc/flow/platforms.py
tests/functional/platforms/02-host-to-platform-upgrade.t
tests/functional/platforms/02-host-to-platform-upgrade/flow.cylc
tests/functional/platforms/02-host-to-platform-upgrade/reference.log

Discovered a bug where host ⇒ plaform upgrade only worked on first cycle.
Cause: becuase Python passes refs rather than creating objects the upgrader
function popped the required info for the first instance of a task.
Fix: have `platform_from_job_info` put popped information back when it's
finished.
These changes close #4167 

Fixed platforms subsequent cycles on localhost.

---

CHANGES.md
cylc/flow/exceptions.py
cylc/flow/platforms.py
cylc/flow/scheduler.py
tests/integration/conftest.py
tests/integration/test_scheduler.py
tests/integration/utils/flow_tools.py
tests/unit/test_exceptions.py

These changes close #4147
Ensure that if an exception occurs during shutdown, it gets logged before exiting.
<del>This is difficult to test for other than manually; see the steps to reproduce in the issue</del> I've added an integration test, but probably worth manually running the example in #4147 too

Improve error handling if exception occurs during shutdown

---

CHANGES.md
cylc/flow/data_store_mgr.py

These changes close #4157
Also fixes incorrect state totals (caused by only the deltas, and not the store totals, being collected).
Although I have noticed additional `succeeded` every now and then, which I will hunt down eventually but is only visible in TUI.

state totals fixes

---

.github/workflows/bash.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
cylc/flow/cfgspec/globalcfg.py
cylc/flow/network/client.py
cylc/flow/network/client_factory.py
cylc/flow/network/ssh_client.py
cylc/flow/task_message.py
cylc/flow/task_remote_mgr.py
etc/bin/shellchecker
setup.py
tests/flakyfunctional/cylc-poll/16-execution-time-limit.t
tests/flakyfunctional/cylc-poll/16-execution-time-limit/flow.cylc
tests/functional/cylc-poll/13-comm-method/flow.cylc
tests/functional/platforms/03-platform-db.t
tests/functional/remote/06-poll.t
tests/unit/test_task_remote_mgr.py

* Patch the broken GH DNS
* (**bug**) Fix `cylc message` so that it doesn't attempt to send TCP messages when `communication method = poll`.
* Add timeout to bash workflow.
* Pin pytest-asyncio to 0.14 due to an unresolved bug.
* Fix misclassified functional test.
* Fix tests which were broken for `comms:poll`.
* Some fiddling to get the tests passing again.
* Update exception code change in shellcheck 0.7.2 (mac os is picking up the latest)

actions: fudge /etc/hosts

---

cylc/flow/suite_files.py

Bug:
```
$ pwd
~/beef  # (not in workflow source dir)
$ cylc install -C ~/cylc-src/demo
INSTALLED beef from ~/cylc-src/demo -> ~/cylc-run/beef/run1
```
Result should be:
```
INSTALLED demo from ~/cylc-src/demo -> ~/cylc-run/demo/run1
```

Fix workflow source name determination.

---

tests/functional/remote/05-remote-init.t

test incompatible with non-default comms as it defines its own platforms.

tests/f: fix remote/05

---

CHANGES.md
cylc/flow/scripts/install.py

These changes close #4186 
Would be good to get this in for 8.0b1

Fix cylc install help examples

---

README.md

In GitHub I think the image will be still center-aligned. I tested on PyCharm with its Markdown rendered, and the result was the same with/without the `center` tag.
`<center>` is an HTML deprecated tag, so it could be the reason why it's rendered as plain-text in PYPI. The `div` tag appears to be accepter, although the `align="center"` is ignored. So on PYPI I think the image should be displayed correctly in the next release, but not center-aligned (which is not a big issue I think?).

Remove center deprecated tag in README

---

cylc/flow/parsec/exceptions.py
cylc/flow/parsec/fileparse.py
tests/unit/parsec/test_fileparse.py

Request from user support: "could we catch unclosed multi-line strings and raise a more helpful error message".
Especially when meddling with Jinja2 it can be easy to lop off the trailing `"""` by accident.
The logic in this PR:
* If there is a syntax error in the file.
* And we have just come out of a multi-line string.
* And the multi-line string contains things that look like Cylc `[sections]`.
* Then add a line to the error warning the user they may have missed a closing `"""`.

catch unclosed multi-line strings

---

conda-environment.yml
cylc/flow/cfgspec/globalcfg.py
cylc/flow/workflow_db_mgr.py
setup.py

We have acquired a dependency on packaging for version parsing. This can be done using setuptools which we are already using for this purpose:
https://github.com/cylc/cylc-flow/blob/8b25ae063cfd3273447ec2339efcb83417d721e2/cylc/flow/network/scan.py#L267
* Switched from `packaging` to `setuptools`.
* Added `setuptools` as a dependency, not sure if this is necessary but it's more explicit.

setup: remove packaging dependency

---

cylc/flow/etc/job.sh
cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py

This is a small change with no associated Issue. Follow-up to #4174 
From Teams discussion:
> define flow is very confusing (since it doesn't even do anything to the flow).
>
> So we gotta change now it anyhoo, how about `-S, --rose-template-variable`, that describes what it does without mentioning either suites or flows.
>
> I think for Rose we can just scale back on the word "suite" and try to talk more about "configurations" or the file itself.

Terminology: suite to workflow follow-up

---

CHANGES.md
cylc/flow/config.py
cylc/flow/scripts/validate.py
cylc/flow/task_id.py
cylc/flow/unicode_rules.py
tests/integration/test_config.py

Closes https://github.com/cylc/cylc-flow/issues/3160
Validate task names in the `[runtime]` section, autodocument from this code (corrects the docs on valid task name patterns).

config: validate [runtime] task names

---

cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py

This is a small change with no associated Issue, other than https://github.com/cylc/cylc-rose/pull/56#discussion_r622181398
Pluralise a variable name because it's actually a list; the singular might be misleading

Pluralise rose_template_vars

---

cylc/flow/etc/job.sh

We've previously removed the use of here-document's (#2622).
However, here-string's suffer from the same problem (using temporary files):
https://askubuntu.com/questions/678915/whats-the-difference-between-and-in-bash
These are a particular problem in bash 3.2 because it ignores $TMPDIR:
https://lists.gnu.org/archive/html/bug-bash/2013-12/msg00056.html
To remove the need for here-string's I've replaced the use of `cut` with bash parameter expansion:
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
I've also removed the use of separate `export` statements except where needed to avoid failing https://github.com/koalaman/shellcheck/wiki/SC2155.

Job script: remove the use of here-string's

---

cylc/flow/remote.py
cylc/flow/task_remote_mgr.py
cylc/flow/workflow_files.py
tests/functional/cylc-reinstall/01-file-transfer.t

rsync: change file installation rsync options
* more friendly output format
* unify local and remote fileinstall options
* use checksums not timestamps for file filtering
* log rsync command with debug level

rsync format

---

cylc/flow/__init__.py
cylc/flow/main_loop/__init__.py
cylc/flow/parsec/fileparse.py
cylc/flow/scripts/cylc.py
cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py
tests/unit/plugins/test_pre_configure.py

Centralise all of the `iter_entry_points` calls into one place.
This is kinda a good thing to do but the real motivation is to screen out the `cylc` distribution. This distribution shouldn't exist, this distribution is called `cylc-flow`, however, due to some strange factors beyond my comprehension it shows up on my system for dev installs.

entry points: centralise entry point iteration

---

usr/bin/cylc

The `cylc` wrapper script only requires minor changes in order to be used as the `rose` wrapper script as well.
For the moment, an extra bit of legacy logic has to used used to support standalone Rose installations but that can be removed once no longer using Cylc 7 / Rose 2.
Note: the alternative is that we maintain a separate `rose` wrapper (identical to the `cylc` wrapper other than the legacy logic. and the setting of `ROSE_SITE_CONF_PATH`) and then advise anyone using Rose to use the `rose` wrapper  in place of the `cylc` one.
Note that `ROSE_SITE_CONF_PATH` has to be set even when calling `cylc` in order for `rose` to work if called by the scheduler (e.g. legacy workflows using `rose host select`).
- [N/A] …

Wrapper script: add global config environment variables & support rose

---

.github/workflows/test_manylinux.yml

Ensure our dependency tree remains `manylinux1` compatible for installation on older OSes.
> **TLDR;**
>
> The `manylinux<v>` identifiers define a standardish "base" environment for Linux binaries to be compiled
> against. The `manylinux1` identifier is based off of centos5 which is beyond EOL, consequently manylinux1
> is also EOL but still fairly well supported. The purpose of this test is to scan dependency changes to ensure
> we don't end up with something which can't be built but which doesn't provide a manylinux1 binary.
[Example run](https://github.com/oliver-sanders/cylc-flow/actions/runs/777370753)

actions: test manylinux compatibility

---

cylc/flow/daemonize.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/__init__.py
tests/functional/cylc-play/02-format.t

A quick bit of fluff, because why not.
Several things have long annoyed me about the current "Cylc header" printed at the top of `cylc help` and `cylc play` stdout:
- it is too wide, and too tall
- yellow and green are the wrong way around
- the ASCII art looks:
-  decidedly crappy
- and :scream: kind of like a thinly disguised swastika (once you've seen this, you can't un-see it!)
The old:
The new:
Bolder, less verbose, more compact, not offensive! - what's not to like?

Nicer cylc header text

---

.github/workflows/test_manylinux.yml
conda-environment.yml
setup.py

aiofiles have fixed their pypi metadata and are now releasing noarch packages on conda-forge which unblocks Python 3.9 support.

aiofiles: bump from 0.5->0.7

---

CHANGES.md
cylc/flow/pathutil.py
cylc/flow/scripts/install.py
cylc/flow/workflow_files.py
tests/functional/cylc-install/00-simple.t
tests/functional/cylc-install/01-symlinks.t
tests/functional/cylc-install/02-failures.t
tests/functional/cylc-install/03-file-transfer.t
tests/functional/cylc-reinstall/00-simple.t
tests/functional/cylc-reinstall/01-file-transfer.t
tests/functional/deprecations/03-suiterc.t
tests/unit/test_pathutil.py
tests/unit/test_workflow_files.py

This PR addresses some feedback on `cylc install` from @dpmatthews.
* Logging of symlink making was inaccurate. (added a condition to dict used for logging)
* Tidied the symlinks created for `suite.rc` and `runN` so they are now relative paths 
* Symlink dirs env variables had been changed to being expanded on the scheduler, (reverted that change) 
* Standard `cylc install` now correctly installs from directories with a `.` in the name
* Updated the `cylc install` help to correctly document location of source symlink.
* Localhost symlinks are now skipped if they exist but point to another location, rather that raising a `Workflow Files Error`
* cylc install now logs the named run rather than flow_name

Cylc install update

---

cylc/flow/parsec/exceptions.py
cylc/flow/parsec/fileparse.py
cylc/flow/scheduler.py
tests/unit/parsec/test_fileparse_templating_clash.py

These changes close #4210 , alongside https://github.com/cylc/cylc-rose/pull/60.
During fixing #4210  I created a test to which revealed an additional bug, where handling of `# rose-suite.conf:[jinja2:suite.rc]` and `flow.cylc:#!empy` was not symmetrical with the templating clash being the other way around which failed in the desired manner. I moved the check above the loops which process jinja2 and empy. The code is now tidier, and more susceptible to unit testing when future bugs are found.
There is much more scope for unitizing this bit of code and testing it in bits in the future.
**tests are likely to fail in CI - manual checkout of both branches is required** 

Made a template vars clash variable and make Cylc handle it elegently

---

CHANGES.md
cylc/flow/rundb.py
cylc/flow/workflow_db_mgr.py
tests/integration/conftest.py
tests/integration/test_resolvers.py
tests/integration/utils/flow_tools.py

These changes partially address #3666
When the scheduler starts, the public database is synced with the private database. This is done by copying the private database into a tempfile, which is then renamed to replace the public database file (the tempfile is not deleted) (see https://github.com/cylc/cylc-flow/pull/1493#issuecomment-111044334 for the rationale behind this). But the file descriptor for the tempfile was not closed at any point, hence the Python process held on to the file beyond the shutdown of the scheduler.
I have not tackled the suggestion of persisting the connection(s) to the databases.

Close public database correctly

---

conda-environment.yml
cylc/flow/scripts/cylc.py
setup.py
tests/functional/cli/01-help.t

We briefly toyed with moving to click, however, only ever converted one script over and are now less sure of the correct framework.
This PR moves the one click command to argparse (stdlib) to reduce our dependency footprint.
Our CLI simplifications mean there isn't much driving us to move away from optparse, opened a low priority issue for future consideration: https://github.com/cylc/cylc-flow/issues/4231. 

cli: revert from click to argparse

---

tests/functional/job-submission/19-platform_select.t
tests/functional/job-submission/19-platform_select/flow.cylc

This is a small change with no associated Issue: 
This test was broken in that it was passing when it should not have been.
This happened because:
- Something about the for loop which did the grepping wasn't working.
- The fail_ok test was passing, because the workflow was failing in an unexpected way.

this tests appears to have been inoperative for some time

---

CHANGES.md
cylc/flow/config.py
tests/unit/conftest.py
tests/unit/test_config.py
tests/unit/test_task_trigger.py

These changes close #4225
```
$ cylc play --no-detach five --initial-cycle-point="2^2"
Cylc Workflow Engine 8.0b2.dev
Copyright (C) 2008-2021 NIWA
& British Crown (Met Office) & Contributors
2021-05-25T13:15:56+12:00 ERROR - Workflow shutting down - PointParsingError: Incompatible value for
<class 'cylc.flow.cycling.integer.IntegerPoint'>: 2^2: invalid literal for int() with base 10: '2^2'
2021-05-25T13:15:56+12:00 INFO - DONE
```

Fix ICP bug.

---

tests/unit/conftest.py
tests/unit/test_config.py
tests/unit/test_task_trigger.py

This is a small change with no associated Issue. Follow up to #4227
I have tried to make the `cycling_type` (now `set_cycling_type`) fixture simpler.
Note the difference between:
- cycling type: `integer` or `iso8601`
- cycling mode: `integer`, `gregorian`, `365day` etc.

Refactor cycling_type unit test fixture

---

.github/workflows/test_fast.yml
cylc/flow/workflow_files.py

Call to `Path.exists` was missing parentheses.

Fix mistake in workflow_files

---

cylc/flow/network/authorisation.py

Pet peeve of mine, graphql logs (especially from Tui and the UIS) fill up the suite log.
Shifted the graphql line to debug level:
* this line contains the host and script and protocol that issued the command
* later log entries contain the command and args
Lets see what tests get broken... nothing 🎉.

logging: log graphql requests at debug level

---

cylc/flow/scheduler.py

closes https://github.com/cylc/cylc-flow/issues/4243
Fixes bug where the stall detection could release runahead tasks.
Spotted by @MetRonnie on https://github.com/cylc/cylc-flow/pull/4237#issuecomment-852954395
Bug was intermittent, however, could be made dependable by jamming an `await asyncio.sleep(1)` into `tests/i/test_scan::test_scan_sigstop`.
The released can be seen an extra log message in the test output which was causing the failure:
```
E             Full diff:
E               [
E             +  (20,
E             +   '[one.1] -released from runahead'),
E                (30,...
```

pause: workflow cannot be stalled if it is paused

---

cylc/flow/network/resolvers.py
cylc/flow/network/schema.py

These changes close #4252 
Not used in `cylc-flow`/Scheduler (yet!), but requests with multiple subscriptions currently use context to store their unique ID, which is shared amongst all subscriptions in the request.
I've changed this from `info.context['sub_id']` to `info.variable_values['backend_sub_id']` which is local to the subscription not request.
(`variable_values` is only used initially to load the GraphQL document, so should be safe, but added "backend" and underscores to lessen the chance someone uses it for any other purpose)
Result is observable (with the `cylc hub` log) when printing `args['sub_id']` in any of the resolvers that are used by the subscription, i.e.:
```
INITIAL_SUB_ID
f670d768-31bd-4abb-9beb-b268a9fcc19c
<graphql.execution.base.ResolveInfo object at …
```

Use object local to GraphQL subscription for id

---

lib/cylc/review.py
lib/cylc/review_dao.py

Cylc Review Broken by name changes in the cylc flow database of "suite_params" → "workflow_params"
Testing is manual, I'm afraid. 
Suggest @MetRonnie to review & @dpmatthews to test
See comments in code for explanation.

Problem: replacement of "suite" with "workflow" breaks review.

---

CHANGES.md
cylc/flow/config.py
cylc/flow/param_expand.py
tests/functional/param_expand/03-env-tmpl.t
tests/functional/param_expand/03-env-tmpl/flow.cylc
tests/functional/param_expand/03-env-tmpl/reference.log
tests/functional/param_expand/03-env-tmpl/t1-0099-that.ref
tests/functional/param_expand/03-env-tmpl/t1-0099-this.ref
tests/functional/param_expand/03-env-tmpl/t1-0101-that.ref
tests/functional/param_expand/03-env-tmpl/t1-0101-this.ref
tests/functional/param_expand/03-env-tmpl/t2-0099-that.ref
tests/functional/param_expand/03-env-tmpl/t2-0099-this.ref
tests/functional/param_expand/03-env-tmpl/t2-0101-that.ref
tests/functional/param_expand/03-env-tmpl/t2-0101-this.ref

Fix param expansion in inherited environment.

---

lib/cylc/review.py

These changes partially address #4261 : Cylc Review is not identifying `cylc.flow` and `cylc.flow.processed` as files to be syntax highlighted.
I think that this needs only 1 review.

Add glob to have review syntax highlight flow.cylc(.processed) files.

---

cylc/flow/scheduler_cli.py

```diff
+ 
- If the workflow is not already installed (by "cylc install" or a previous run)
- it will be installed on the fly before start up.
```
This seems to be a direct translation from Cylc 7, with "register" replaced by "install", and not actually implemented.

Remove on-the-fly installation text from play help.

---

CHANGES.md
cylc/flow/data_store_mgr.py
tests/functional/graphql/01-workflow.t
tests/functional/graphql/01-workflow/flow.cylc
tests/functional/runahead/06-release-update.t

These changes close #4255
Constrain the data store n-window by the final cycle point (FCP)... (ICP doesn't appear to be an issue)
There would be two ways of doing this:
- change the `taskdef.py` function that generates children
- filter at the window expansion for children whose cycle point extends beyond the FCP.
I chose the latter, because we may wish to (or already do) record the workflow state of tasks beyond the FCP for the purpose of restarting the workflow with an extended FCP.
~~The issue only applies to those tasks in the `[scheduling][[special tasks]]sequential` section, not those defined in the graph as sequential.~~
The test `tests/functional/graphql/01-workflow.t` will fail with the filter commented out.

Constrain window by final cycle point

---

cylc/flow/scripts/__init__.py

A bit of fluff. Pushing up the tweak I made for the demo in my presentation last night.
Master:
This branch:
IMO the new one is more readable: the "Y" looks less like a "4"; the word looks less like "chic" because the "L" doesn't look like an "I"; and it is also more balanced with the tail on the "L" ... while still looking colourful and graphic.

Tweak terminal logo.

---

lib/cylc/review.py
lib/cylc/review_dao.py

(dependent on #4233 )
These changes close #4170 and a minor issue without a ticket.
- #4170 Prevent Cylc Review from following links back to source directory for workflows installed using Cylc Install.
- Prevent Cylc Review from Displaying the `runN` symlink to the latest run folder.
[marked against a Cylc 8 milestone because this change only adds support for Cylc 8 workflows, and should not change an aspect of Cylc 7 functioning]
Install a workflow with Cylc 8. 
Switch to Cylc 7 and start Cylc Review (`cylc review start`).
Ensure that you cannot see links to `~/cylc-run/<workflow>/_cylc-install` or `_cylc_install`.
Ensure that you cannot see links to `~/cylc-run/<workflow>/runN`

Cylc review fixes.skip links to source

---

lib/cylc/review.py

These changes address #4260 
I think that the problem is actually being caused by a problem in the HTML/JS - the + looks like it may be missing from the get command.
(3 Reviewers Tagged. 2nd can merge)

Hack-y fix of failure to show log files with + in title

---

cylc/flow/etc/syntax/cylc.lang
cylc/flow/etc/syntax/cylc.xml

This is a small change with no associated Issue: Whilst reviewing something else I noticed that the automated syntax highlighting script had not been run, and so some of the syntax highlighting was out of date. Fixed here.

update syntax highlighting to reflect latest changes in configs

---

lib/cylc/review_dao.py

These changes partially address #4261 : Running Cylc 8 Workflows showing as stopped under some circumstances.
Cause of bug: Contact file was being scraped for the word SUITE, not SUITE _or_ WORKFLOW.

Fix failure to show workflow status

---

cylc/flow/option_parsers.py
cylc/flow/workflow_files.py

This is a very small change with no associated Issue.
Removed suite owner from the cli options and listed options available to users for colour in the help.

Remove suite_owner option and make --colour cli help more informative

---

CHANGES.md
cylc/flow/option_parsers.py
tests/unit/test_option_parsers.py

Some of our command help pages are quite long, so I sometimes like to grep in them, or open them in an editor `cylc play --help | vim -` in which case color control codes in the output are annoying.  This hack makes `--color=never` work with `--help`.

CLI make colourization optional for cmd --help

---

CHANGES.md
cylc/flow/config.py
cylc/flow/scheduler_cli.py
cylc/flow/task_pool.py
tests/unit/test_config.py

These changes:
- close #4257 
- close #4266 
`conda-environment.yml`. (None)

Ignore pre-initial deps for --start-tasks.

---

cylc/flow/c3mro.py
mypy.ini

Allowing redefinition of variables as different types seems like a Pythonic practice, and not allowing it (as is currently the case) can be a bit annoying.
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-allow-redefinition

mypy: allow redefinition

---

cylc/flow/parsec/fileparse.py

if plugin sets 'template variables' == 'template variables' and
config does not contain a hashbang fail with an explanation that Cylc
cannot work out the correct templating engine.
These changes close https://github.com/cylc/cylc-rose/issues/67

Added check for templating language setting

---

cylc/flow/scripts/config.py
cylc/flow/scripts/graph.py
cylc/flow/scripts/install.py
cylc/flow/scripts/list.py
cylc/flow/scripts/validate.py
cylc/flow/templatevars.py
tests/unit/test_templatevars.py

These changes address #4288 
These changes are twinned with https://github.com/cylc/cylc-rose/pull/65
Make the following scripts work with cylc-rose:
Create workflows with a `rose-suite.conf` in
- `~/cylc-src/`
-  `~/cylc-run/` (using `cylc install`)
- some other folder somewhere else entirely
You might use jinja2 or empy in the workflow to carry out tests like [these](https://github.com/cylc/cylc-rose/blob/master/tests/functional/06_jinja2_thorough/flow.cylc).
Try each of the four cylc CLI commands with and without the [extra rose options provided by this function](https://github.com/wxtim/cylc/blob/5ec95b29c20fe74a49754f529317f5f10597ab6d/cylc/flow/scripts/install.py#L86)/
Ideally these commands and `cylc install` should behave in a consistent way.

cylc-rose: `cylc list` compatibility

---

CHANGES.md
cylc/flow/async_util.py
cylc/flow/network/scan.py
cylc/flow/scripts/scan.py
tests/conftest.py
tests/integration/test_scan.py
tests/unit/conftest.py

Add the `cylc scan --uninstalled` option.
> **Note:** Source isn't a workflow state because source workflows are orthogonal to run workflows. The lifecycle of the source is not the same as the lifecycle of the run. The UI will have to track source and run workflows separately.
First step towards displaying source workflows in the UI (as the UIS can use the `scan_multi` interface). Next we need to jam source workflows into the schema at the UIS and make them available to the UI.

scan: show uninstalled workflows

---

CHANGES.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/workflow.py
cylc/flow/pathutil.py
cylc/flow/scripts/install.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/00-basic.t
tests/functional/cylc-clean/01-remote.t
tests/functional/cylc-clean/02-targeted.t
tests/functional/cylc-get-site-config/04-homeless.t
tests/functional/cylc-install/01-symlinks.t
tests/functional/remote/04-symlink-dirs.t
tests/unit/conftest.py
tests/unit/test_pathutil.py
tests/unit/test_workflow_files.py

Adds cli option (`--symlink-dirs`) for over-riding localhost symlink dirs in global config when executing `cylc install`. 
Removes --no-symlink-dirs option, this is replaced by --symlink-dirs=None
Also moves symlink dirs into install section of config...(these changes close https://github.com/cylc/cylc-flow/issues/4219)

Symlink dirs cli

---

.mailmap
CONTRIBUTING.md

One github-actions[bot] commit had set the author differently to the others which caused the shortlog action to fail.
~I'm not sure why this happened, one of the actions not using the standard release-action for configuring the author~
I've edited the contributor file to force the shortlog test to run.

mailmap: associate dangling bot commit with github-actions[bot] account

---

CHANGES.md
cylc/flow/graph_parser.py
tests/unit/test_graph_parser.py

This is a small change with no associated Issue. Follow up #4334 

Fail "a => b & !b" in validation.

---

CHANGES.md
cylc/flow/cfgspec/workflow.py

These changes close https://github.com/cylc/cylc-flow/issues/4310

Make spawn to max active cylc points obsolete

---

conda-environment.yml

Effectively a backport of the conda-deps from the 8.0b2 conda-forge release:
* Bump the conda deps to the values defined in the setup.py
* Remove rx

conda: match conda deps to pypi ones

---

cylc/flow/job_runner_handlers/loadleveler.py
cylc/flow/job_runner_handlers/lsf.py
cylc/flow/job_runner_handlers/moab.py
cylc/flow/job_runner_handlers/pbs.py
cylc/flow/job_runner_handlers/sge.py
cylc/flow/job_runner_handlers/slurm.py
cylc/flow/job_runner_mgr.py
tests/unit/job_runner_handlers/test_loadleveler.py
tests/unit/job_runner_handlers/test_lsf.py
tests/unit/job_runner_handlers/test_moab.py
tests/unit/job_runner_handlers/test_pbs.py
tests/unit/job_runner_handlers/test_slurm.py
tests/unit/job_runner_handlers/test_slurm_packjob.py

* paths in directives (e.g. out/err files) should be evaluated
relative to $HOME on the platform where the job submission command
was run.
* for remote job submissions this was working fine.
* for local job submissions (excluding at/background/slurm) this was broken.
* slurm was working because it was expanding the path when writing the
directives (incorrectly).
* closes https://github.com/cylc/cylc-flow/issues/4247

job_runner_mgr: make paths in directives relative to ~

---

CHANGES.md
bin/cylc-get-suite-contact
lib/cylc/network/httpclient.py
lib/cylc/network/port_scan.py
lib/cylc/scheduler.py
lib/cylc/suite_db_mgr.py
lib/cylc/suite_srv_files_mgr.py
lib/cylc/tests/test_suite_db_mgr.py
lib/cylc/tests/test_suite_srv_files_mgr.py
tests/cylc8/00-run.t
tests/cylc8/test_header
tests/lib/bash/test_header

These changes close #4315
Give better errors and be safer with the contact file and DB when trying to use Cylc 7 commands on Cylc 8 workflows.
First create a **suite.rc** workflow that is compatible with both Cylc 7 and 8:
```ini
[cylc]
cycle point format = %Y
[scheduling]
initial cycle point = 2012
[[[P1Y]]]
graph = foo
[runtime]
[[foo]]
```
Run in Cylc 8:
```shell
$ cylc play myflow -n --pause
```
Then open a new terminal for Cylc 7:
1. `cylc hold myflow`
2. `cylc scan --debug`
3. `cylc run myflow`
4. `cylc restart myflow`
5. `cylc stop myflow`
6. `cylc get-suite-contact myflow` (Should this work?)
7. `cylc get-suite-version` (I think this ought to work, but it doesn't and I'm not sure it's worth getting it to work. At least the error prints the version anyway!)
8. `cd …

Better handling of Cylc 8 workflows

---

cylc/flow/scripts/report_timings.py

These changes partially address #4351 
**Purpose** Restore some basic functionality to `cylc review-timings` which was broken for even the simplest workflows at Cylc 8.

make review-timings work with Cylc 8

---

CHANGES.md
cylc/flow/scripts/scan.py
cylc/flow/util.py

Use natural sort order with `cylc scan`.
Place function in generic module for easy reuse.

scan: use natural sort order with --sort opt

---

CHANGES.md
cylc/flow/option_parsers.py

Removes workflow owner option. 
This was supposed to have been removed in https://github.com/cylc/cylc-flow/pull/4194 but this selection of code was missed. 

Remove workflow owner

---

cylc/flow/task_events_mgr.py

Problem noticed whilst testing with this workflow:
```
[scheduling]
initial cycle point = now
[[graph]]
PT1H = "flakey[-PT1H] => flakey"
[runtime]
[[flakey]]
platform = ??? # Use a remote platform to slow down how quickly the polling returns
script = "sleep 5; ((CYLC_TASK_TRY_NUMBER <= 9)) && exit 1; true"
execution retry delays = 10*PT5S
execution polling intervals= PT3S
```
Relevant log entries:
```
2021-08-13T13:47:14+01:00 INFO - [flakey.20210813T1346+0100] -poll now, (next in PT3S (after 2021-08-13T13:47:17+01:00))
2021-08-13T13:47:16+01:00 CRITICAL - [flakey.20210813T1346+0100] status=running: (received)failed/ERR at 2021-08-13T13:47:15+01:00  for job(03) flow(e)
2021-08-13T13:47:16+01:00 INFO - [flakey.20210813T1346+0100] -job(03) failed, retrying in PT5S (after …
```

Improve logging when a task message is received when the task is retrying

---

cylc/flow/scheduler.py
tests/functional/cylc-play/06-warnif-scp-after-fcp.t
tests/unit/test_scheduler.py

These changes close #4226
(CP = Cycle Point)
> If you have a start CP 1, and final CP 2, and define stop CP as 100, your stop CP is just going to be ignored and never used. It would be helpful to users to log a warning.

have scheduler warn if stopcp > finalcp

---

CHANGES.md
doc/src/appendices/suiterc-config-ref.rst
lib/cylc/config.py
lib/cylc/scheduler.py
lib/cylc/suite_db_mgr.py
lib/cylc/tests/test_config.py
tests/cyclers/20-multidaily_local.t
tests/cylc-show/03-clock-triggered-non-utc-mode.t
tests/database/00-simple.t
tests/database/00-simple/select-suite-params.out
tests/database/03-remote.t
tests/restart/52-cycle-point-time-zone.t

These changes close #3462
Save the cycle point time zone to the suite database upon `cylc run` (setting it to the local time zone if it isn't set in `suite.rc`), and make sure the suite always reloads & restarts using the same cycle point time zone and UTC mode value.
Backport of #3614

Store cycle point tz in DB for restart

---

cylc/flow/cfgspec/globalcfg.py

This is a small change with no associated Issue. At request of @dpmatthews
During loading of the config hierarchy, if a site global config is bad, do not skip with warning, instead raise error as happens for user global config.

Do not skip bad site config; raise instead

---

cylc/flow/parsec/fileparse.py

These changes close https://github.com/cylc/cylc-rose/issues/73

allow failure to set templating engine _anywhere_ to pass quietly.

---

.github/workflows/bash.yml
.github/workflows/test_functional.yml
tests/unit/test_workflow_files.py

It seems `asyncio.get_event_loop().run_until_complete()` might be more buggy than `asyncio.run()`? But this is the opposite of expected - https://github.com/cylc/cylc-flow/pull/4289#discussion_r664025464
Traceback from unit tests on GH Actions:
```python
>       workflow_files.init_clean(reg, opts=opts)
tests/unit/test_workflow_files.py:377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cylc/flow/workflow_files.py:674: in init_clean
contained_workflows = asyncio.get_event_loop().run_until_complete(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <asyncio.unix_events._UnixDefaultEventLoopPolicy object at 0x7ffa73b578d0>
>                              % …
```

Attempt to fix unit test flakiness on Python 3.7

---

bin/cylc-report-timings

```
> cylc report-timings -s ~me/cylc-run/myworkflow
...traceback...
"str" object is not callable
```
Unwilling to devote too much time to this because we are hoping to replace report-timings in Cylc 8, but had a quick look. 
It looks like `pandas.DataFrame.rename` may have changed interfaces and not be reliable for all python/pandas versions: @trwhitcomb  - what version of Python/Pandas did you write this with? Commenting this out fixes the problem,  at the cost of making a slightly less well labelled table. 

Commented out line in cylc report-timings causing flaky behaviour.

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/workflow.py

These changes partially address #4342 

Add `versionchanged` admonitions to certain config items

---

.codecov.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml

As GH Actions is now configured to skip the functional tests on PRs when only irrelevant files are modified (e.g. `.md` files, unit test files), this can lead to Codecov failing due to only receiving the limited coverage report of the fast tests.
This PR aims to make it carry forward the previous coverage if the functional tests report is not uploaded, hopefully preventing false coverage failures. I'm not entirely sure this will work, but at least it can't hurt.
Docs (warning: clear as mud): https://docs.codecov.com/docs/flags

Codecov: carry forward previous reports 

---

cylc/flow/network/schema.py
cylc/flow/scheduler.py
cylc/flow/scripts/cylc.py

Small changes required for https://github.com/cylc/cylc-uiserver/pull/230

Jupyter server

---

.github/workflows/1_create_release_pr.yml

Depends on https://github.com/cylc/release-actions/pull/22

GH Actions: Add test workflows badges to release PRs

---

cylc/flow/exceptions.py
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/scheduler.py
cylc/flow/scripts/stop.py
tests/unit/conftest.py

This is a small change with no associated Issue. Fixes bug probably introduced by #4331.
Stopping a workflow using the default stop mode in the UI (e.g. pressing the stop button) was resulting in an error
> command failed: stop - Error: Response not successful: Received status code 400 
Inspecting the sent mutation in the devtools console showed that the mode was 
```
mode: "REQUEST(CLEAN)"
```
However, if you clicked on the hamburger and clicked the pencil icon to edit the Stop command, and actively chose "Clean" from the mode dropdown, then it would work fine. The mutation in that case contained
```
mode: "Clean"
```
instead.
In `cylc.flow.network.schema.WorkflowStopMode`, remove the `.value` from `StopMode.REQUEST_*.value`.
I'm not really sure why this works, `graphene.Enum` is …

Fix mutation error when stopping workflow in UI

---

cylc/flow/job_file.py
cylc/flow/remote.py
cylc/flow/scheduler.py
tests/unit/test_job_file.py
usr/bin/cylc

These changes address the bulk of #4165 
**Ticket Specific Checklist**

Cylc Wrapper uses arbitrary env set at CYLC_ENV_NAME

---

tests/functional/shutdown/22-stop-now.t

Remove non-POSIX compliant grep.
See https://github.com/cylc/cylc-flow/pull/4395#issuecomment-916012828

tests/f: fix shutdown/22

---

cylc/flow/data_store_mgr.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py

These changes partially address https://github.com/cylc/cylc-ui/issues/667
Closes #4047
This PR batches all the data-store deltas post reload, and sets the `reloaded` flag on all..
Previously only the definition elements (`workflow`, `tasks`, `families`)would be batched and sent, and then the cycle point nodes/elements (`task_proxies`, `family_proxies`, `jobs`, `edges`) would be sent on the next main loop iteration (after being released from the runahead/spawn pool)..
The reason we want one batch, is to replicate an initial burst for the UI.
Along with the sibling PR: https://github.com/cylc/cylc-uiserver/pull/234
this fixes the freeze issue at the UI..
~~There is still a little delay with the reload, but is likely related to the processing of the newly loaded pool (releasing etc... which …

Deltas batched post reload

---

CHANGES.md
cylc/flow/workflow_files.py
tests/functional/cylc-install/00-simple.t
tests/functional/cylc-install/02-failures.t

Source symlink fix

---

cylc/flow/cfgspec/workflow.py

An obseletion warning referring to a config item which only ever existed (if at all) in Cylc 8 alpha or beta and not Cylc 7.  

clean up interim obselete message

---

CHANGES.md
lib/cylc/prerequisite.py

These changes close #3664  - 7.8.x sibling of #4426 

7.8.x Fix bug with task name as substring of task name.

---

CHANGES.md
cylc/flow/prerequisite.py

Fix bug with task name as substring of task name.

---

CHANGES.md
cylc/flow/daemonize.py
cylc/flow/network/client.py
cylc/flow/prerequisite.py
cylc/flow/scheduler.py
cylc/flow/scripts/psutil.py
cylc/flow/scripts/stop.py
cylc/flow/util.py
cylc/flow/workflow_files.py
tests/functional/cylc-play/02-format.t
tests/integration/test_scan_api.py
tests/integration/test_workflow_files.py
tests/unit/test_workflow_files.py

Closes #4416
Closes #3965
* Replaces the compound pid:command contact file fields with separate
pid & contact fields.
* Replaces system `ps` call with Python `psutil`.
* Fixes a bug reported on Alpine Linux & improves portability.
* Reviewed and updated the detection of stale contact files.
* Added tests.

contact: replace ps system call with psutil

---

CHANGES.md
lib/cylc/review.py

These changes close #4428 
Reqires #4430 to be merged.

Cylc review.cylc 8 file checks

---

cylc/flow/workflow_files.py
tests/unit/test_workflow_files.py

`parse_reg()`: Avoid unnecessary reg clash messages

---

.github/workflows/test_manylinux.yml
setup.py

Ubuntu 16.04 is dead, long live Ubuntu 18.04.
Note, we are purposefully using the oldest Linux available to us as this is the version most likely to flag issues.
Note, includes setup.py change to force the manylinux test to run.

actions: bump manylinux to the oldest ubuntu available

---

lib/cylc/review.py

RE: Cylc 7 Review: Make any file ending in .cylc appear highlighted as a .cylc file. `flow-processed.cylc` and `<timestamp>-start.cylc` were not previously highlighted.
V. small change on legacy system hence 1 reviewer only.

Cylc review show any *.cylc file with synatax highlighting

---

cylc/flow/pathutil.py

This is a small change with no associated Issue. Identified by @dpmatthews 
These log messages always appear on startup:
```
DEBUG - ~/cylc-run/tempflow/run1/log/workflow: directory created
DEBUG - ~/cylc-run/tempflow/run1/log/job: directory created
DEBUG - ~/cylc-run/tempflow/run1/log/flow-config: directory created
DEBUG - ~/cylc-run/tempflow/run1/share: directory created
DEBUG - ~/cylc-run/tempflow/run1/work: directory created
```
This change stops them from appearing if the directories already exist.

Remove "directory created" debug messages on workflow restart

---

cylc/flow/data_store_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/tui/__init__.py
cylc/flow/tui/app.py

Fixes:
- the datastore was creating job proxies for tasks in the `preparing` state, but labeling them as `submitted`
- the task state change to `preparing` was not being logged
- TUI had not been updated for the change from `ready` to `preparing`
Also:
- new icon to distinguish `preparing` from `waiting` in TUI

Task "preparing" state bug fixes

---

cylc/flow/cfgspec/workflow.py

Fixes the build error on https://github.com/cylc/cylc-doc/pull/306.

change back compat reference for docs

---

etc/conf/global.cylc
tests/functional/remote/06-poll.t

These changes close #4433
It seems the flakiness of the remote tests on GH Actions was caused by too much polling for the VM to handle?
With this PR we are down to 1 (from 5) of the `_remote_background_indep_poll` tests consistently failing on the first go (`tests/k/cylc-poll/16-execution-time-limit.t`), and this has also reduced the time taken to run the tests from ~21 mins to ~14 mins.

Reduce flakiness of remote func tests on GH Actions

---

CHANGES.md
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/scheduler.py
tests/integration/test_resolvers.py

These changes partially address https://github.com/cylc/cylc-uiserver/issues/242. Sibling to https://github.com/cylc/cylc-uiserver/pull/270 and https://github.com/cylc/cylc-ui/pull/823
Ping is not needed for the UI, as it must already be connected to the workflow for the UI to show the workflow in the first place. It also turns out there was not a resolver for ping anyway.

Remove ping mutation

---

cylc/flow/network/graphql.py
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py

These changes partially address https://github.com/cylc/cylc-uiserver/issues/247
Sibling to https://github.com/cylc/cylc-uiserver/pull/266
**Yield coordination**
This is needed because the async generator yields data, and the resolvers return an Observable and Promises to the server implementation.
The PR a feature into the GraphQL subscription resolvers that requires the subscription server to flag when the processing of a delta is complete. This is a compulsory feature due to the common delta-store reference of a subscription and workflow.
The only other way to avoid this type coordination is to have a reference that changes, which would still require some coordination..
**Delta clash fix**
This PR fixes the following sort of errors appearing at the UIS:
``` …
```

subscription async-gen yield coordination & delta clash fix

---

cylc/flow/data_store_mgr.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/tui/__init__.py
tests/functional/remote/05-remote-init.t
tests/functional/remote/05-remote-init/flow.cylc
tests/integration/test_data_store_mgr.py

Removes the legacy of the Cylc 7 "ready" job state and fixes some issues discovered along the way.
Fixes #4484 
Addresses https://github.com/cylc/cylc-admin/pull/47
Cylc job items are now created in the data store on submission rather than on preparation.
**Misc Fixes:**
* Jobs which failed during preparation (before job-submit) are now added to the data store.
* Before the task failed with no jobs, technically correct, but unhelpful.
* Now we get a submit-failed job with the platform information provided so users can debug.
* Tasks now have jobs when running in simulation mode.
* Fixes a bug where the job platform in the data store may be incorrect.
* This can happen if the platform it has changed during the preparation process as a result of intelligent host selection.
**Note:**
The …

Preparing job status

---

cylc/flow/flow_mgr.py
cylc/flow/network/resolvers.py
cylc/flow/scripts/trigger.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py

Fix bug in manual triggering, recently introduced by #4300.
Default triggering (i.e. with no reflow) is failing from the GUI and TUI, because missing reflow args (which are not needed for this use case) were not optional.

Trigger mutation fix

---

cylc/flow/cfgspec/README
cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/workflow.py
cylc/flow/main_loop/__init__.py
cylc/flow/main_loop/reset_bad_hosts.py
cylc/flow/network/schema.py
cylc/flow/scripts/broadcast.py
cylc/flow/scripts/ext_trigger.py
cylc/flow/scripts/hold.py
cylc/flow/scripts/poll.py
cylc/flow/scripts/release.py
cylc/flow/scripts/reload.py
cylc/flow/scripts/remove.py
cylc/flow/scripts/set_outputs.py
cylc/flow/scripts/stop.py
cylc/flow/task_job_mgr.py
tests/integration/test_examples.py

Overhaul of the config files, including responses to #4342 
[When finished] These changes close #4342  & #4091 

Docs.review spec docs

---

cylc/flow/etc/job.sh
tests/flakyfunctional/job-submission/19-chatty.t
tests/functional/remote/01-file-install.t

Latest shellcheck version fails several of our scripts, and seems to have been updated for macos on our CI:
```console
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.8.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
$ shellcheck cylc/flow/etc/job.sh
In cylc/flow/etc/job.sh line 60:
typeset host="$(hostname).$(namerslv -sn 2>'/dev/null' | awk '{print $2}')"
^--^ SC2155 (warning): Declare and assign separately to avoid masking return values.
In cylc/flow/etc/job.sh line 62:
typeset host="$(hostname -f)"
^--^ SC2155 (warning): Declare and assign separately to avoid masking return values.
For more information:
https://www.shellcheck.net/wiki/SC2155 -- Declare and assign separately to ...
```
This is a **very small** change with …

Fix shell style errors

---

CHANGES.md
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/task_proxy.py
cylc/flow/tui/data.py
tests/functional/job-submission/21-late-sub-message.t
tests/functional/job-submission/21-late-sub-message/flow.cylc
tests/functional/job-submission/21-late-sub-message/lib/python/delayed_background.py

Follow up to #4485 which delayed data store job proxy creation until job submit time, but:
- did not update job ID in the job proxy (it was trying to update before the delayed proxy creation)
- did not handle edge case where "started" message can come in before "submitted" 
- it introduced a small bug in accessing job config via the  task proxy
Also:
- gets TUI to display job finish time as well as start time

Fix new job state logic

---

cylc/flow/cfgspec/globalcfg.py

This is a small change with no associated Issue: [Cylc Docs overnight build failed](https://github.com/cylc/cylc-doc/runs/4137779097?check_suite_focus=true#step:12:127).
Effectively a follow on to #4473 .
Causes
- badly formed rst.

fix broken Cylc doc issue

---

cylc/flow/network/schema.py

The added and updated delta types are essentially identical. Usually we subscribe to the same fields for both added and updated.
This PR uses a GraphQL interface to make this slightly nicer, example using `GscanSubscriptionQuery`:
```diff
fragment GScanTreeDeltas on Deltas {
id
added {
-    ...GscanAddedData
+    ...GscanDelta
}
updated {
-    ...GscanUpdatedData
+    ...GscanDelta
}
pruned {
workflow
}
}
- fragment GscanAddedData on Added {
+ fragment GscanData on Added {
workflow {
...WorkflowData
}
}
- fragment GscanUpdatedData on Updated {
-   workflow {
-     ...WorkflowData
-   }
- }
```
Boiler plate "hello world" deltas subscription after this change:
```graphql
fragment ExampleTreeData on Delta {
workflow {
id
}
cyclePoints: familyProxies(ids: ["root"], ghosts: true) {
id
} …
```

graphql: use a common interface for added / updated deltas

---

cylc/flow/network/resolvers.py

These changes partially address a formatting issue in an error response found in:
https://github.com/cylc/cylc-uiserver/issues/250
https://github.com/cylc/cylc-uiserver/issues/269
Now has some formatting, and information on store workflows (which is just one at Scheduler):

Change formating and info on no workflow mutation error

---

cylc/flow/scripts/reinstall.py
cylc/flow/workflow_files.py
tests/functional/cylc-install/02-failures.t
tests/functional/cylc-reinstall/02-failures.t
tests/unit/test_workflow_files.py

Currently if you have both `flow.cylc` and `suite.rc` files in the run directory and cylc play. You get a log message warning that `suite.rc` has been detected and back compatibility mode has been activated. The workflow proceeds to run ignoring the `suite.rc` file and using the `flow.cylc` file.
This could cause some confusion for users and so we should raise an error if both files are detected (discussed UK end), forcing the user to decide which one should be used, rather than assuming either way.
Ideally this would be included in upcoming beta release, apologies, I understand this is frozen.
This is a small change with no associated Issue, bit of a quick fix. Looking at the code, I think there is potential for some refactoring but that would be a bigger job for another day.
To test on …

Forbid case where both `suite.rc` and `flow.cylc` files are found in src/run dir

---

lib/cylc/network/httpclient.py

**This is a small change with no associated Issue - description of issue here:**
@dpmatthews  noticed that a remote platform was not picking up custom settings for task messaging. It appears that these settings aren't loaded from the contact file before they are set for the task messaging app.

actually load contact info before sending a task message.

---

.codecov.yml

Experimental PR
**Issue**
Codecov runs before the CI has finished, causing a false negative notification.
[Documentation of setting changed](https://docs.codecov.com/docs/common-recipe-list#send-coverage-notifications-even-if-all-ci-statuses-have-not-completed)

Don't do coverage report until CI done

---

tox.ini

This is a small change with no associated Issue. Fixes failing style test on GH Actions.
We should re-enable this rule when https://github.com/PyCQA/flake8-bugbear/issues/208 is fixed

Turn off broken flake8-bugbear rule B018 (for now)

---

.github/PULL_REQUEST_TEMPLATE.md
tox.ini

Revert #4537 as the broken rule has been patched in https://github.com/PyCQA/flake8-bugbear/releases/tag/21.11.29

Revert flake8-bugbear B018 ignore

---

CHANGES.md
cylc/flow/workflow_files.py
tests/functional/cylc-install/00-simple.t
tests/functional/cylc-install/02-failures.t
tests/functional/cylc-reinstall/00-simple.t
tests/functional/cylc-reinstall/01-file-transfer.t
tests/functional/cylc-reinstall/02-failures.t
tests/functional/deprecations/03-suiterc.t
tests/functional/optional-outputs/03-c7backcompat.t
tests/unit/test_workflow_files.py

Removes the `flow.cylc` symlink created when using a `suite.rc` file. This also enabled a refactor of duplicate logic from https://github.com/cylc/cylc-flow/pull/4497.
These changes close https://github.com/cylc/cylc-flow/issues/4500
Milestone is 8.0rc1 to give time for any unforeseen problems to surface.

Remove the suite.rc flow.cylc symlink

---

cylc/flow/workflow_files.py
tests/unit/test_workflow_files.py

Modified and reinstated a unit test that was deleted in #4506. I think this test neatly parametrises several scenarios for workflow install

Tidy + reinstate deleted workflow_files unit test

---

cylc/flow/option_parsers.py
cylc/flow/scripts/get_resources.py

Small follow-up to #4536 
(Plus a small verbosity reduction for `--color`)

get-resources help tweak

---

CHANGES.md
cylc/flow/install_plugins/log_vc_info.py
tests/functional/post-install/00-log-vc-info.t
tests/unit/post_install/test_log_vc_info.py

These changes close #4546
Change the workflow version control info file format from modified INI to JSON. This is still easily human readable but is much easier to parse by programs that can't use parsec (e.g. see https://github.com/metomi/rose/pull/2520).

Change VCS info file format to JSON

---

cylc/flow/workflow_files.py
tests/functional/cylc-install/02-failures.t
tests/unit/conftest.py
tests/unit/test_workflow_files.py

This is a small change follow-up to #4394

Workflow name validation: prevent reserved dir names in workflow name

---

cylc/flow/scripts/cycle_point.py

This is a small change with no associated Issue:
While looking at tutorial workflows I noticed the following use case:
```python
Popen(
['cylc', 'cyclepoint', '--offset-hours', str(int(offset_hours))],
stdout=PIPE
).communicate()
```
In this case the subsequent commands fail because colour information chars are included in the output.
Because this command is likely to used by other scripts this should not have the colour options.

remove the color/no-colour option from cylc cyclepoint

---

CHANGES.md
cylc/flow/task_events_mgr.py
cylc/flow/task_proxy.py
tests/functional/graphql/03-is-held-arg.t
tests/functional/lib/python/diffr.py

These changes close #4551 
- (tweaked a func test to check start and submit times get into the datastore).

Fix job submit time delta.

---

cylc/flow/terminal.py

These changes close #4552  and supersede #4559 
Current colour output disabling is a bit broken.
On master, this correctly generates colour output in the terminal:
```console
$ cylc cat-log test 
```
But these cases (for example) get unnecessary color-code pollution:
```console
$ cylc cat-log test | vim -   # IN YOUR FACE emacs!!! (can't read from stdin)
$ cylc cat-log test > log
```

CLI: don't color if stdout redirected.

---

cylc/flow/scheduler.py

This is a small change with no associated Issue. Fixes lack of space in
```
INFO - cold start from1.
```

Fix start type log formatting

---

cylc/flow/config.py
tests/functional/validate/37-special-implicit-task.t

These changes partially address https://github.com/cylc/cylc-doc/issues/170
> `allow implicit tasks` (note: doesn't affect Rose2019 users) (note: **add link to migration page in warning message**)

Add link to migration guide in implicit tasks warning

---

bin/cylc-broadcast
bin/cylc-cat-state
bin/cylc-diff
bin/cylc-get-directory
bin/cylc-gscan
bin/cylc-gui
bin/cylc-insert
bin/cylc-jobs-kill
bin/cylc-jobs-poll
bin/cylc-jobs-submit
bin/cylc-print
bin/cylc-report-timings
bin/cylc-scan
bin/cylc-suite-state

Use opt parser to fill in `ARGS` automatically. Fixes incorrect usage text for `cylc insert`, as noticed by someone on Yammer and @dpmatthews 

Update usage text

---

CHANGES.md
cylc/flow/config.py
cylc/flow/scheduler.py
cylc/flow/task_events_mgr.py
cylc/flow/task_proxy.py
cylc/flow/xtrigger_mgr.py
cylc/flow/xtriggers/wall_clock.py
tests/flakyfunctional/xtriggers/00-wall_clock.t
tests/flakyfunctional/xtriggers/00-wall_clock/flow.cylc
tests/functional/clock-trigger-inexact/00-big-offset.t
tests/functional/clock-trigger-inexact/00-big-offset/flow.cylc
tests/functional/clock-trigger-inexact/test_header
tests/unit/test_task_proxy.py

These changes close #4510
Fixes clock-trigger time computation for clock xtriggers and old-style (task property) clock triggers. Also restore main-loop call to check old-style clock-triggers (must have lost that somewhere during Cylc 8 development).
The new way is very efficient, even for inexact offsets (months, years): the computation is done once at first call (add offset to cycle point, then convert to absolute trigger time in seconds since unix epoch which is used for all subsequent checks.
~~TODO:~~

Fix clock-trigger offset computation.

---

CHANGES.md
cylc/flow/workflow_files.py

Remote check for a running workflow (e.g. for `cylc scan - t rich` ~~or any scheduler-targetting `cylc` command~~) is failing, because it tries to execute `cylc cylc psutil` (too many `cylc`s!) on the workflow host.
This is the quick fix as deployed at NIWA.
TODO: check:
(off-topic: the `construct_ssh_cmd` methods could use some refactoring - e.g. there's one specifically for `cylc` commands, but it isn't used in this case).

Fix remote psutil invocation.

---

CHANGES.md
cylc/flow/cfgspec/globalcfg.py

added metadata section to platforms and platform groups config

---

cylc/flow/scripts/graph.py

Hopefully closes https://github.com/cylc/cylc-doc/issues/375
* We use Pillow to display images (when installed).
* Pillow uses other systems to handle the display itself and includes
functionality to detect which of these systems are present.
https://github.com/python-pillow/Pillow/blob/82541b6dec8452cb612067fcebba1c5a1a2bfdc8/src/PIL/ImageShow.py#L117-L263
* We have had reports that this detection has failed for one system
causing the image not to show with no error displayed.
https://github.com/cylc/cylc-doc/issues/375
* This change always prints the image file name incase the display
command fails so that the user is never left high and dry.

graph: handle potential failure of PIL.Image.show

---

CHANGES.md
cylc/flow/platforms.py
cylc/flow/task_job_mgr.py
tests/functional/intelligent-host-selection/07-cylc7-badhost.t

These changes close #4569
Prevent Cylc from incorrectly falling back to localhost if a host specified by `[runtime][<task>][remote]host` is unreachable.

Fix host selection bug for deprecated `[runtime][<task>][remote]host` syntax

---

tests/functional/directives/slurm/flow.cylc

`tests/functional/directives/03-slurm.t` was failing because Cylc didn't seem to understand the non UID format of the task listed as an expected failure.
@oliver-sanders - Is this indicative of a larger hole- should UID cope with the old format in this case?

Fix test failing due to expected task failures not using UID.

---

pytest.ini
setup.cfg
tests/integration/graphql/test_root.py
tests/integration/test_async_util.py
tests/integration/test_client.py
tests/integration/test_data_store_mgr.py
tests/integration/test_examples.py
tests/integration/test_graphql.py
tests/integration/test_id_cli.py
tests/integration/test_publisher.py
tests/integration/test_resolvers.py
tests/integration/test_scan.py
tests/integration/test_scan_api.py
tests/integration/test_scheduler.py
tests/integration/test_server.py
tests/integration/test_task_pool.py
tests/integration/test_workflow_files.py
tests/integration/utils/test_utils.py
tests/unit/network/test_scan_nt.py
tests/unit/scripts/test_clean.py
tests/unit/test_async_util.py
tests/unit/test_id_cli.py
tests/unit/test_workflow_files.py

This is a small change with no associated Issue. This removes the need to decorate async tests with `@pytest.mark.asyncio`. This also silences new warnings when running pytest with pytest-asyncio 0.17.
> Starting from `pytest-asyncio>=0.17`, three modes are provided: auto, strict and legacy (default).
> ...
> When the mode is auto, all discovered async tests are considered asyncio-driven even if they have no `@pytest.mark.asyncio marker`.
https://github.com/pytest-dev/pytest-asyncio#modes

Use new mode option in pytest-asyncio 0.17

---

cylc/flow/id_cli.py
tests/unit/test_id_cli.py

Closes #4583
* Trailing slashes in universal IDs are invalid.
* However, they are harmless and user's may add them due to CLI auto-completion.
* We should tolerate them in the context of user input.
* Note this strips the `/` at the CLI, it doesn't propagate into the code.

uid: tolerate trailing slashes in IDs on the CLI

---

tests/conftest.py

I don't like the way this plugin invades our tests, nicer to kick it out.

tests: disable pytest_tornasync

---

.github/workflows/test_tutorial_workflow.yml

The `test_tutorial_workflow` GH Actions workflow is a bit flaky, so why not exclude it from PRs that couldn't affect the tutorial workflows in any way

Limit when tutorial workflow test runs for PRs

---

cylc/flow/option_parsers.py

Upgrade of flake8-simplify to 15.0 has highlighted something new:
```
> flake8
./cylc/flow/option_parsers.py:425:22: SIM901 Use 'options.verbosity > 2' instead of 'bool(options.verbosity > 2)'
```
This is a small change with no associated Issue:

fix new issue identified by flake8-simplify after upgrade to 15.0

---

cylc/flow/scripts/graph.py

Fixes a single `task.cycle` format line the was causing `cylc graph` to render strangely.

graph: fix cylc graph output

---

cylc/flow/scripts/graph.py

Fixes a minor bug where `cylc graph` would result in traceback due to WORKFLOW_ID erroneously being marked as optional.

graph: make workflow_id a required argument

---

CHANGES.md
cylc/flow/option_parsers.py
cylc/flow/scripts/cylc.py
cylc/flow/scripts/play.py
cylc/flow/terminal.py
tests/functional/cli/05-colour.t
tests/unit/test_option_parsers.py

Tweak terminal colour handling.

---

cylc/flow/scheduler_cli.py
cylc/flow/scripts/cylc.py
tests/functional/rnd/04-conditions.t

We removed the dedicated commands for viewing the license file.
This adds in a help option that dumps the packaged COPYING file.
(note the COPYING file gets auto packaged into the dist-info thinggy)

cli: add option for viewing the license file

---

cylc/flow/config.py
cylc/flow/scripts/validate.py

* `cylc play` should do more or less everything `cylc validate` does.
* The sequence bounds check was only being run for `cylc validate`.
* This moves the logic into `cylc.flow.config` so it is run for both
`cylc validate` and `cylc play`.
* Already tested by tests/functional/validate/71-task-proxy-sequence-bounds-err.t
(not essential for rc1, but small enough to be low risk)

validate: move seqence bounds validation into the config

---

cylc/flow/task_pool.py
tests/integration/test_task_pool.py

* Make implicit globs explicit so that warning messages are more
informative.
* E.G. `cylc hold foo` should produce the warning
`no tasks matching foo/*`.

uid: make task match warning explicit

---

cylc/flow/network/__init__.py
cylc/flow/network/authorisation.py
cylc/flow/network/client.py
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/network/server.py
cylc/flow/scheduler.py
tests/functional/cylc-message/00-ssh.t
tests/integration/test_resolvers.py

Log the authenticated user executing the mutation command from the UI.
A test user pausing the workflow of another user, will result in a log message below in the workflow log:
The owner then resuming the workflow, will result in a log message..
These changes close https://github.com/cylc/cylc-flow/issues/4294 and https://github.com/cylc/cylc-uiserver/issues/224 by its sibling:

Log Authenticated User from UI-Server in Workflow Log

---

cylc/flow/resources.py

* Retrieves the DataPoint API key in text format for tutorial use.
Small feature required for the runtime-tutorial (spotted whilst reviewing #4623).

get-resources: add api-key option

---

cylc/flow/config.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/validate.py
tests/flakyfunctional/modes/03-dummy-env.t
tests/functional/platforms/06-host-to-platform-upgrade-dummy-mode.t

Small tidy-up to reflect the fact that dummy mode is now the same as dummy-local mode, and there's no need for the distinction anymore.
These changes partially address cylc/cylc-doc#297

Rename dummy-local mode to dummy mode.

---

cylc/flow/id_match.py
cylc/flow/task_pool.py

* Small fix probably resulting from the UID change.
* A warning currently shows when you trigger a task not present in the pool.

trigger: don't warn if task not already in the pool

---

tests/functional/clock-trigger-inexact/00-big-offset.t

* See https://github.com/cylc/cylc-flow/issues/4633
Skip the test for now, fix it later.

tests/f: skip flaky clock-trigger-inexact/00

---

cylc/flow/option_parsers.py
cylc/flow/scripts/cycle_point.py
cylc/flow/scripts/cylc.py
tests/functional/cyclepoint/00-time.t

* Fix bug where `cylc <cmd> --help` results in traceback for
`color=None` commands like `cylc cycle-point`.
* Improve the coverage for `cylc cycle-point` so it catches this error.
* Deal with some minor coverage thinggies found on route.

cli: fix --color bug and improve coverage

---

cylc/flow/etc/tutorial/runtime-tutorial/etc/met-office-sites.dat

Small change to tutorial workflow discovered during work on https://github.com/cylc/cylc-doc/pull/383

fixed missing symlink for tutorial workflow

---

cylc/flow/cfgspec/workflow.py

This is a small change with no associated Issue. Sibling to cylc/cylc-doc#390

Add link to list of job script env vars in `[runtime][X]script` docs

---

CHANGES.md
cylc/flow/scripts/dump.py
cylc/flow/task_pool.py
tests/flakyfunctional/hold-release/14-hold-kill/flow.cylc
tests/functional/spawn-on-demand/13-trigger-runahead.t
tests/functional/spawn-on-demand/13-trigger-runahead/flow.cylc
tests/functional/spawn-on-demand/13-trigger-runahead/reference.log

These changes close #4619 
~~Note: this branch is built on top of #4641~~ (now merged; rebased onto master)
The problem was, we were not auto-spawning the successor of a manually-triggered parentless task unless runahead limit had been recomputed, and we don't recompute the limit after manual triggering (the limit is irrelevant for that). We need to auto-spawn the successor task regardless, but only release it from runhead if the limit has been recomputed (and if the task is below below the limit, of course).

Fix manual triggering of runahead-limited parentless tasks.

---

cylc/flow/cfgspec/workflow.py

This is a small change with no associated Issue. Improve wording in docs.

Re-word `[scheduling]cycling mode` description

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/network/server.py

This is a small change with no associated Issue: I have found a couple more spelling mistakes.

Moor spilling foxes

---

CHANGES.md
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

These changes close #4665
Don't retrigger a task that is already preparing for job submission.

Check job not in prep already before triggering.

---

cylc/flow/scheduler.py
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

> Built on #4667
* RC2 with no associated issues.
* Follow on from https://github.com/cylc/cylc-flow/pull/4667.
Found three instances where `TASK_STATUS_PREPARING` might be missing from a `TASK_STATUSES_ACTIVE` state check.
If we agree the check should be extended I'll add a test to enforce it.

Preparing vs active

---

CHANGES.md
cylc/flow/data_store_mgr.py
cylc/flow/rundb.py
cylc/flow/task_pool.py
cylc/flow/workflow_db_mgr.py
tests/flakyfunctional/database/00-simple/schema.out
tests/functional/job-submission/01-job-nn-localhost/db.sqlite3
tests/functional/restart/53-task-prerequisites.t
tests/functional/restart/54-incompatible-db/db.sqlite3

These changes partially addresses #4036
(prerequisites were always available, but satisfaction not set)
At present history is only populated via the evolution/forward-march of the active pool.
History is not recovered on restart nor on the window appearing/reappearing about a trigger/reflow.
This pull request aims to fill in the history of those n>0 window nodes:
This PR also fixes a bug where triggered tasks would hang around after completion, and never get pruned.
**Note: Prerequisite DB history has been taken out (only restart prereqs available and loaded)**
So the prereq satisfaction, shown with GraphiQL below, will no longer be correct for historical tasks.
(However, this is just a one line change.. So, I've left it in)
As an example:
```
[scheduling]
initial cycle point = …
```

data-store n > 0 window DB loads

---

CHANGES.md
cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/task_queues/independent.py
tests/integration/conftest.py
tests/integration/test_data_store_mgr.py
tests/integration/test_examples.py
tests/integration/test_queues.py
tests/integration/test_scan.py
tests/integration/test_scan_api.py
tests/integration/test_scheduler.py
tests/integration/utils/__init__.py
tests/integration/utils/flow_tools.py
tests/integration/utils/test_utils.py
tests/unit/test_indep_task_queues.py

> [edit] pushed up a new commit with a new approach after discovering the problem went deeper than initially thought.
>
> There are now three issues each has its own steps to reproduce and integration test.
> The new integration tests run on master but you will need to overwite `tests/integration/conftest.py` and `sed -i 's/pre_submit_tasks/prep_submit_tasks/' cylc/flow/scheduler.py`.
* Closes:        
* https://github.com/cylc/cylc-flow/issues/4278        
* https://github.com/cylc/cylc-flow/issues/4627        
* https://github.com/cylc/cylc-flow/issues/4628        
* Makes the following changes:        
* Held tasks are no longer be released from queues.        
* `pre_prep_tasks` (previously `pre_submit_tasks`) are now included        
with active tasks for the computation of queue …

queues: fix interactions with the scheduler paused and task held states
