CHANGES.md
cylc/flow/scripts/clean.py
tests/unit/scripts/test_clean.py

These changes partially address #4673 and #4618 
The `--force` behaviour is more of a `--yes` than `--force`, so rename it.
`--force` can come back later if we want to allow users to override the current "cannot clean" scenarios - see #4450

`cylc clean`: rename `--force` to `--yes`

---

cylc/flow/network/schema.py

Flake8 broken due to [this change](https://github.com/MartinThoma/flake8-simplify/issues/92) being added to flake8-simplify.
This change fixes the only case where this affects Cylc Flow

Fix flake8-simplify

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/network/schema.py

This is a small change with no associated issue

added a note about platform regexes working in  reverse order

---

CHANGES.md
cylc/flow/network/schema.py
cylc/flow/scheduler.py
cylc/flow/task_job_mgr.py
tests/integration/conftest.py
tests/integration/test_scheduler.py

Currently we can poll a waiting task (as reloaded from the DB at restart ... and otherwise), and erroneously update it with the state of a previously submitted job of the same task. (This is partly because submit number does not increment until the task reaches the `preparing` state, before which time it matches the previous job ... but I don't think we need to poll non-active tasks anyway??)
[UPDATE] After the discussion below, pending resolution of #4678 this PR now avoids polling waiting tasks, rather than targeting active tasks.
This is a small change with no associated Issue. 

Only poll non-waiting tasks

---

CHANGES.md
cylc/flow/network/schema.py
cylc/flow/scripts/trigger.py
cylc/flow/task_pool.py
tests/flakyfunctional/xtriggers/01-workflow_state.t
tests/flakyfunctional/xtriggers/01-workflow_state/flow.cylc
tests/functional/spawn-on-demand/02-merge/flow.cylc
tests/functional/spawn-on-demand/14-trigger-flow-blocker.t
tests/functional/spawn-on-demand/14-trigger-flow-blocker/flow.cylc
tests/functional/spawn-on-demand/14-trigger-flow-blocker/reference.log

Fix flow merge into no-flow task.

---

cylc/flow/workflow_files.py
tests/integration/test_workflow_files.py

If a client fails to connect and the workflow can be proven not to be running, then the contact file will be removed.
This PR logs when contact files are removed which seems like sensible logging to have.

log removal of contact file

---

cylc/flow/workflow_files.py

While investigating healthcheck bug, I noticed the `CONTACT_FILE_EXISITS_MSG` is incorrect. It was being sent the original command rather than the process id.  
To test, 
`cylc play workflow` 
`cylc play workflow`
On master the pid is not passed to the kill command.

Fix contact file exists message

---

.gitignore
cylc/flow/network/client.py

Not a blocker for RC1.
Fixes a small bug where a `KeyError` could be raised during the process of raising a `ClientError` in the event of an error in the response causing it to not contain an "error" entry.
Also remove a .gitignore file.

Client key error

---

cylc/flow/network/client.py

Docs are failing to build with the following message:
```
~/cylc-flow/cylc/flow/network/client.py:docstring of cylc.flow.network.client.WorkflowRuntimeClient:: WARNING: py:class reference target not found: zmq.asyncio.Context
```
* Confirmed ZMQ is installed correctly in the build environment.
* Replicated locally.
* Tried quoting the type, not good enough
* Removing the hint.

docs: fix issue causing docs to fail to build

---

tests/integration/test_scan.py
tests/integration/test_scheduler.py
tests/integration/test_task_pool.py

This may reduce the risk of integration test timeouts.
* The run fixture kicks off the main loop which is typically one more moving part than the average integration test requires.
* The start fixture only starts the scheduler and leaves the test to perform any required actions to implement test logic.

tests/i: replace run with start where possible

---

CHANGES.md
conda-environment.yml
setup.cfg

```
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```
Jinja2 @ 2.11.3 has [a dependency `MarkupSafe>=0.23`](https://github.com/pallets/jinja/blob/cf215390d4a4d6f0a4de27e2687eed176878f13d/setup.py#L53 ). Unfortunately Pallets have made a breaking change in the API in MarkupSafe 2.1.0, but have no plans to patch version 2.11 of Jinja2 with an upper pin on MarkupSafe, so we have to do it ourselves.
https://github.com/pallets/jinja/issues/1585
Note: we have discussed moving to version 3.0 of Jinja2, which is the only supported version going forward (see comments from the Pallets team on the issue above). The difficulty is convincing ourselves this will not introduce breaking changes to Cylc workflows that are dependent on Jinja2. It is is unfeasible (and not our job) to …

Upper pin markupsafe

---

cylc/flow/scripts/clean.py
cylc/flow/workflow_files.py
tests/unit/test_workflow_files.py

When doing a multi workflow clean, there was no way of knowing which workflow a particular message was about

Include workflow name in `cylc clean` logging/error messages

---

cylc/flow/network/client.py

This reverts commit 21928e6b26dcf6720ce7e38ee0736d8163213c34 (#4692) as superseded by https://github.com/cylc/cylc-doc/pull/406
Needs:
- https://github.com/cylc/cylc-doc/pull/406 

Revert "docs: fix issue causing docs to fail to build"

---

.github/workflows/test_tutorial_workflow.yml
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-rainfall
setup.cfg

Fixes this error in tutorial tests:
```
ERROR: Could not find a version that satisfies the requirement metomi-rose==2.0rc2.* (from cylc-rose) (from versions: 2.0a1, 2.0b1, 2.0b2, 2.0b3, 2.0rc1)
ERROR: No matching distribution found for metomi-rose==2.0rc2.*
```
Further info:
> The `git clone` approach was used because of that symlink issue where pip install <url> was broken for Rose. Seems like it works fine now though so going back to the simpler approach.
https://github.com/cylc/cylc-rose/pull/114#discussion_r811762468

Fix tutorial workflow test

---

.github/workflows/test_manylinux.yml

> The manylinux failure is due to a combination of kiwisolver dropping manylinux1 support and pip22 failing on error (so no longer falling back to the previous version as it used to).
> 
> The (transient) kiwisolver dep is `kiwisolver>=1.0.1`, manylinux support was only dropped at the most recent `1.3.2` release so we are good here, for now...
This might be enough to patch things over for now 

actions: pin manylinux to pip<22

---

cylc/flow/main_loop/__init__.py
cylc/flow/network/server.py
tests/integration/test_examples.py
tests/integration/test_scheduler.py
tests/integration/utils/flow_tools.py
tests/unit/main_loop/test_main_loop.py
tests/unit/network/test_publisher.py

This is a small change with no associated Issue. In light of the markupsafe incident, I thought it would be a good idea to address the warnings that currently occur during pytest runs (although actually there were no warnings coming through for the markupsafe breaking change). Only exception is the `pytest.PytestUnhandledThreadExceptionWarning` which is tracked in #4706 

Fix warnings and tidy

---

tests/integration/README.md
tests/integration/test_examples.py
tests/integration/test_resolvers.py
tests/integration/test_scheduler.py
tests/integration/test_task_pool.py

* Some tests were not correctly shutting down their resources so would cause pytest to hang during the cleanup phase.
* Due to some interaction, possibly between asyncio, pytest-asyncio and pytest-xdist, this does not impact the tests when run in distributed mode.

tests/i: fix hanging tests

---

cylc/flow/network/client.py
cylc/flow/tui/app.py
cylc/flow/tui/data.py
cylc/flow/tui/overlay.py
cylc/flow/tui/util.py
tests/unit/tui/test_util.py

tui: add offline commands
* Add support for the play and clean commands.
zmq client: raise WorkflowStoped not ClientTimeout
* WorkflowClient could raise ClientTimeout for stopped workflows.
* Closes https://github.com/cylc/cylc-flow/issues/4654
tui: disable mutations for stopped workflows
* Closes https://github.com/cylc/cylc-flow/issues/4647
tui: fix context menu for cycle points
* Closes https://github.com/cylc/cylc-flow/issues/4629.
* Also adds the node ID to the context menu.
> **Note:** This PR includes a sneaky enhancement (offline) which shouldn't really be going into a
> RC release.
> It's small enough and Tui as an experimental interface is supplementary enough I think its ok, but happy to cherry-pick and delay to 8.0.1.

tui: bug fixes

---

cylc/flow/scheduler.py
tests/integration/test_scan.py

> Result of test instability spotted by @MetRonnie, posted on Element
>
>> While trying to debug the flakiness of the integration tests on GH Actions MacOS, I noticed that running the integration tests with -n 0 --dist=no to turn off pytest-xdist results in tests/integration/test_[scan.py](http://scan.py/)::test_workflow_params failing 100% of the time (on linux)
I think this is a bug because if the workflow bails during the first main loop iteration the workflow will be left in a state we cannot restart from.
If it's an issue RC2, otherwise 8.1.0.

scheduler: process DB after configure complete

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/host_select.py

Documented example was missing brackets.
Will hotfix the 8.0.0 docs.
Improved the error message a little, could be better but admin facing rather than user facing so not worth the time investment ATM. If you try testing this with the originally documented example you will see the word "RESULT" appear in the error which is an artefact of the expression processing which cannot easily be removed.

host_select: fix docs and improve error message

---

.github/workflows/test_conda-build.yml
conda-environment.yml
cylc/flow/main_loop/__init__.py
cylc/flow/main_loop/log_db.py
cylc/flow/main_loop/log_main_loop.py
setup.cfg
tests/functional/rnd/05-main-loop.t
tests/unit/main_loop/test_log_db.py
tests/unit/main_loop/test_log_main_loop.py

Impacts developer plugins not loaded in normal circumstances so a reasonably acceptable thing to sneak into an RC. Otherwise push to 8.1.
(Fixes a bug but not a user-facing one)
Contribute a patch developed during the review of #4581 for logging database operations. This helps keep track of:
* Database operations.
* Batching of operations between commit statements.
* Queries (as in the case of [#4581](https://github.com/cylc/cylc-flow/pull/4581)).
Fix an error in the `log_main_loop` plugin discovered on-route and add a test so it doesn't happen again.

main loop: fix log_main_loop and add log_db plugin

---

cylc/flow/id_cli.py
tests/unit/test_id_cli.py

Recently I encountered this
```
$ cylc stop '~rdutta/myworkflow'
UserInputError: Operating on others users' workflows is not supported
```
This PR makes it so you can pass in a full ID if the username is yours.

Allow `~user` in universal ID if it's the current user

---

cylc/flow/etc/cylc

Support the use of environments with names that do not match the cylc flow version (e.g. cylc-8.0.0-1)
Ensure workflows always run under fixed environments rather than symlinked versions which could change
Provide legacy support for rose edit & cylc review (partially address #4555)

Wrapper script enhancements

---

cylc/flow/config.py
cylc/flow/id.py
cylc/flow/scheduler_cli.py
cylc/flow/task_pool.py
cylc/flow/workflow_db_mgr.py

- Fix bug where specifying e.g. `--stopcp=reload` would mean `stopcp|reload` getting stored in `workflow_params` table in DB
- Improve some universal ID stuff

Fix a couple of things

---

cylc/flow/scripts/cycle_point.py

I think we should probably advertise the `isodatetime` command more, particularly for `isodatetime R/P1Y/2020` like uses:
https://github.com/cylc/cylc-doc/issues/428
The caveat being that we need to add something about creating a wrapper script for `isodatetime` into the installation docs:
https://github.com/cylc/cylc-doc/issues/429

cycle-point: add note about isodatetime

---

cylc/flow/workflow_files.py
tests/integration/test_workflow_files.py

Fixes possible traceback reported [here](https://github.com/cylc/cylc-uiserver/pull/324#issuecomment-1059078983).
* If we can prove that a workflow isn't running but still has a contact file we remove it.
* It is possible that the contact file will already have been removed, e.g. if there are lots of jobs running any one of their clients could remove the contact file, potentially whilst other clients are active.
* Consequently IOError can be rasied, can't remove the contact file if it has already been removed.
* Silence this error.

client: suppress IOError when removing defunct contact files

---

CHANGES.md
cylc/flow/flow_mgr.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
tests/functional/spawn-on-demand/15-reflow-incomplete-outputs.t
tests/functional/spawn-on-demand/15-reflow-incomplete-outputs/flow.cylc
tests/functional/spawn-on-demand/15-reflow-incomplete-outputs/reference.log

* Closes https://github.com/cylc/cylc-flow/issues/4687.
* Tasks that have incomplete outputs are held in the n=0 pool.
* This means as new flows approach them they merge but are not re-run.
* This change resets such tasks to waiting and re-queues them to allow them to re-run in the same way a task with complete outputs would.

task pool: fix flow behaviour with incomplete outputs

---

cylc/flow/cycling/iso8601.py
cylc/flow/main_loop/__init__.py
cylc/flow/task_job_mgr.py
cylc/flow/task_pool.py

With flake8-bugbear 22.3.20:
```console
$ flake8 cylc/flow
cylc/flow/task_pool.py:247:13: 
B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
cylc/flow/task_job_mgr.py:945:17:
B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
cylc/flow/cycling/iso8601.py:394:6:
B019 Use of `functools.lru_cache` or `functools.cache` on class methods can lead to memory leaks. 
The cache may retain instance references, preventing garbage collection.
cylc/flow/main_loop/__init__.py:341:13:
B020 Found for loop that reassigns the iterable it is iterating with each iterable value.
cylc/flow/main_loop/__init__.py:341:24:
B020 Found for loop that reassigns the iterable it is iterating …
```

Flake8 bugbear fixes

---

cylc/flow/option_parsers.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/config.py
cylc/flow/scripts/diff.py
cylc/flow/scripts/graph.py
cylc/flow/scripts/list.py
cylc/flow/scripts/validate.py

The `--icp` option is awkwardly at the bottom of the list in `cylc play --help`, nowhere near the other cycle point options. This changes that.

Change order of `--icp` option in CLI help

---

cylc/flow/cycling/__init__.py
cylc/flow/cycling/iso8601.py

Fix valid B019 bug flagged by flake8-bugbear.
This bug will cause a memory leak with `ISO8601Sequence` instances. As it happens Cylc does not release these instances anyway (since they are required by the taskdefs which must live for the life of the Scheduler) so this memory leak is of no consequence at present.

flake8: fix B019 issue

---

.github/dependabot.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml

~Turn off xdist in the hope it makes the integration tests stop hanging flakily on GH Actions~
Reduce homebrew installation and skip style, mypy, in order to speed up MacOS runs

Actions: skip certain tests on MacOS

---

cylc/flow/workflow_files.py
tests/unit/test_workflow_files.py

Trivial change to shorten a couple of workflow files error messages.
Pinging @MetRonnie as author of the original lines. One review will do.

Shorten a couple of error messages.

---

tests/functional/intelligent-host-selection/03-polling.t
tests/functional/intelligent-host-selection/03-polling/flow.cylc

These changes close #4697
This test tests that polling uses host from platform selection method, and in the case of `mixedhostplatform` has to try twice to get a usable host. `[scheduler][main loop][reset bad hosts]interval` is set to `PT1S` to ensure that the list of unreachable hosts (`bad_hosts`) is cleared before execution polling.
`stop_m` would stop the workflow without waiting for the polling of `stop_g` the test required to pass.
i.e.
```
mixedhosttask => stop_m    # stop_m shuts down the workflow
goodhosttask => stop_g     # ... whatever the state of these tasks!
```

De flake tests/f/ihs/03

---

cylc/flow/scheduler.py

Spotted whilst reviewing: https://github.com/cylc/cylc-flow/pull/4720
Command errors are logged at the warning level rather than error. These errors aren't `CRITICAL` (they don't tear down the scheduler), but they are a bit more important than the `WARNING` level which makes it harder to pick them out in the logs.
Also combine two log entries into one for clarity.

scheduler: log command failures at error level

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/log_diagnosis.py
cylc/flow/scheduler.py
cylc/flow/task_events_mgr.py
cylc/flow/workflow_events.py
tests/conftest.py
tests/flakyfunctional/events/41-task-event-template-deprecated.t
tests/functional/events/18-workflow-event-mail.t
tests/functional/events/20-workflow-event-handlers.t
tests/functional/events/20-workflow-event-handlers/flow.cylc
tests/functional/events/37-workflow-event-bad-custom-template.t
tests/integration/events/test_task_events.py
tests/integration/events/test_workflow_events.py
tests/unit/test_config.py
tests/unit/test_workflow_events.py

Closes https://github.com/cylc/cylc-flow/issues/4764
Closes https://github.com/cylc/cylc-flow/issues/4763
> **Note:** Issue has widened in scope since initial post.
> Sibling: https://github.com/cylc/cylc-doc/pull/422
Some assorted fixes for Python template variables supported in various configs.
* `[mail]footer`
* The "suite" template var is provided for scheduler events but not for task events.
* (bug) KeyError was being caught for scheduler events but not for task events.
* (bug) ValueError was not being caught for either (would tear the workflow down for a broken template).
* `[scheudler][events]`
* Formalised event data into a self-documenting enum.
* Changed `uuid_str` to `uuid` (was previously `suite_uuid`).
* (bug) Event handlers configured in the global config were ignored …

config: assorted fixes for python template variables supported in various configurations

---

CHANGES.md
cylc/flow/scheduler_cli.py
tests/unit/test_scheduler_cli.py

Escape quotes in remote command args.

---

cylc/flow/scripts/stop.py

stop: fix tracebacks

---

CHANGES.md
cylc/flow/tui/app.py

These changes close #4715 
When Cylc TUI is started it should check whether the workflow has actually been installed before doing anything to display it.

Make TUI refuse to show non-installed workflows

---

cylc/flow/tui/app.py

* Closes #4818
* Reverts regression in #4748
To test try viewing a workflow in Tui, then stop/play it multiple times.

tui: fix traceback/exit for stopped workflows

---

cylc/flow/network/schema.py

The docstring matters here because it gets fed through to the UI via API-On-The-Fly.

schema: fix formatting in docstring

---

cylc/flow/task_events_mgr.py

This `CRITICAL` log message was previously `DEBUG`. Possibly changed as a form of debugging, ironically?

Undo logging debug

---

CHANGES.md
cylc/flow/etc/tutorial/cylc-forecasting-workflow/.validate
cylc/flow/etc/tutorial/runtime-introduction/.validate
cylc/flow/install_plugins/log_vc_info.py
cylc/flow/pathutil.py
cylc/flow/scripts/cylc.py
cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py
cylc/flow/workflow_files.py
tests/flakyfunctional/xtriggers/01-workflow_state.t
tests/functional/authentication/00-shared-fs.t
tests/functional/authentication/01-remote-workflow-same-name.t
tests/functional/authentication/02-workflow2-stop-workflow1.t
tests/functional/cylc-diff/01-same.t
tests/functional/cylc-install/00-simple.t
tests/functional/cylc-install/01-symlinks.t
tests/functional/cylc-install/02-failures.t
tests/functional/cylc-install/04-symlinks-not-resolved.t
tests/functional/cylc-install/05-check-logs-git.t
tests/functional/cylc-install/06-check-logs-svn.t
tests/functional/cylc-install/07-no-recursive-installations.t
tests/functional/cylc-play/07-timezones-compat.t
tests/functional/cylc-reinstall/00-simple.t
tests/functional/cylc-reinstall/02-failures.t
tests/functional/lib/bash/test_header
tests/functional/workflow-state/00-polling.t
tests/functional/workflow-state/01-polling.t
tests/unit/scripts/test_install.py
tests/unit/test_pathutil.py
tests/unit/test_workflow_files.py

These changes close #4676 and partially address #4786
Remove `--directory` option for `cylc install` and instead allow any directory in the source arg (`cylc install [SOURCE]`):
- Implicit relative path (e.g. `foo/bar`): look for source relative to each path in `global.cylc[install]source dirs` and install first match
- Explicit relative path (e.g. `./foo/bar`): source is relative to PWD
- Absolute path (e.g. `/home/user/foo/bar`): source is at that path
- No path specified: source is PWD 
Rename `--flow-name` option to `--workflow-name` and add `-n` for short (the consensus in #4786 seemed to be `--workflow-name` is preferable to `--id`).

Remove `--directory` option for `cylc install`

---

CHANGES.md
cylc/flow/network/scan.py
tests/integration/test_scan.py

Attempted do-over of scan workflow detection, after noticing that an old workflow definition (i.e. `suite.rc`) installed by Cylc 8 is invisible (to `cylc scan`) until you run it.
New logic based on new explanatory comments in the code, which I've verified by manual testing.

Better scan workflow detection.

---

cylc/flow/id_cli.py
cylc/flow/pathutil.py
cylc/flow/workflow_files.py
tests/functional/cylc-cat-log/03-bad-workflow.t
tests/functional/cylc-graph-diff/00-simple.t
tests/functional/cylc-install/07-no-recursive-installations.t
tests/functional/cylc-reinstall/02-failures.t
tests/functional/graphing/06-family-or.t
tests/functional/validate/35-pass-special-tasks-non-word-names.t
tests/functional/validate/37-special-implicit-task.t
tests/unit/test_id_cli.py
tests/unit/test_workflow_files.py

These changes close #4615 (and supersede #4810)
Disallow the following:
```console
$ cylc val ./flow.cylc
$ cylc val ./test/flow.cylc
$ cylc val /path/to/flow.cylc
```
Additionally, I've tried to make the various error messages less confusing:
- check explicitly for a flow config filename on the command line
-  this will be a common user error, and there's no need to report it as a bad workflow ID
- distinguish between "source path does not exist" and "workflow ID/path does not exist", when that is possible.
```console
$ cylc val hydr/flow.cylc
UserInputError: Not a valid workflow ID or source directory: hydr/flow.cylc
$ cylc val ./hydr/flow.cylc
UserInputError: Not a valid workflow ID or source directory: hydr/flow.cylc
$ cylc val ./hydr  # valid source
Valid for cylc-8.0rc3.dev
$ cylc …
```

Disallow direct validation (etc.) of source FILE

---

CHANGES.md
cylc/flow/task_pool.py
tests/functional/spawn-on-demand/15-stop-flow-3.t
tests/functional/spawn-on-demand/15-stop-flow-3/flow.cylc
tests/functional/spawn-on-demand/15-stop-flow-3/reference.log

Stopping a specific flow should remove non-active tasks in `n=0` (active-waiting, incomplete) if they have no remaining flow numbers, as well as remove the specific flow number from all tasks in `n=0`.
@dpmatthews - this is related to the open question #4741 but only touches the back-end API, so it should be fine to go in.

Stop a specific flow with non-active n=0 tasks present

---

cylc/flow/scripts/install.py

This is a small change follow-up to #4823 
The usage text makes reference to "implicit" and "explicit" relative paths (e.g. `foo/bar` and `./foo/bar` respectively). These are self-coined and not standard terms, so I have removed reference to them in the user-facing text and split the `SOURCE` arg into two: `SOURCE_NAME | PATH`. Hopefully this will avoid confusion.
Pinging @cylc/core in case anyone wants to scream

Update `cylc install` usage text

---

cylc/flow/scripts/install.py
cylc/flow/workflow_files.py
tests/functional/cylc-install/02-failures.t

This is a small change with no associated Issue. Improve this error message:
```console
$ tree temp4 -L 1
temp4
|-- _cylc-install
|-- run1
|-- run2
`-- runN -> run2
$ cylc install temp4 --no-run-name
WorkflowFilesError: "~/cylc-run/temp4" exists.
To install a new run use `cylc install --run-name`, or to reinstall use `cylc reinstall`.
```
You would not be able to use `cylc install --run-name` because numbered runs are being used.

Improve `cylc install` usage text & error message

---

cylc/flow/etc/cylc

The `rosie` command is not currently functional using Rose 2 so use use Rose 2019.01 for the moment

cylc wrapper: Provide legacy support for rosie

---

cylc/flow/exceptions.py
cylc/flow/main_loop/__init__.py

These changes close #4799
Also include original exception name in `PluginError` message for a little bit of extra context.
You can manually test out by applying this change:
```diff
diff --git a/cylc/flow/main_loop/health_check.py b/cylc/flow/main_loop/health_check.py
index 3d4d9453e..d91708289 100644
--- a/cylc/flow/main_loop/health_check.py
+++ b/cylc/flow/main_loop/health_check.py
@@ -24,3 +24,3 @@ Shuts down the workflow in the event of inconsistency or error.
import os
-
+import flurblegarble
from cylc.flow import workflow_files
```
and running a workflow.

Include exception message when a failure to load main loop plugin occurs

---

cylc/flow/scheduler_cli.py

Turns out the file installation log is not closed properly. 

Close File Installation Log

---

CHANGES.md
cylc/flow/scripts/scan.py
tests/unit/scripts/test_scan.py

`cylc scan` currently fails if it encounters a corrupt contact file.
To test this, e.g.:
```console
$ touch ~/cylc-run/blah/.service/contact
$ cylc scan  # ... all hell breaks loose
```

scan CLI: handle bad contact files.

---

cylc/flow/cfgspec/workflow.py

These ones slipped through the net in #4829 

Stop a few more deprecation warnings in backward compatibility mode

---

cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/etc/job.sh
cylc/flow/parsec/fileparse.py
cylc/flow/platforms.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py
cylc/flow/workflow_events.py
cylc/flow/workflow_files.py
cylc/flow/xtrigger_mgr.py
tests/functional/cylc-play/07-timezones-compat.t
tests/functional/deprecations/01-cylc8-basic/validation.stderr
tests/functional/platforms/06-host-to-platform-upgrade-dummy-mode.t

[meeting 2022-05-04]
* Logically Cylc 9 should come at the next configuration breaking change, however, that isn't planned for some time.
(note the Python API should not break flow.cylc compatibility)
* So we will remove back-support in the 8.x series rather than waiting for Cylc 9.

bump deprecation warnings from Cylc 9 to 8.x

---

cylc/flow/workflow_files.py
tests/integration/test_workflow_files.py

* Closes #4855
* Protects the scheduler process check call against stdout pollution.

contact: process check should handle dirty JSON

---

CHANGES.md
cylc/flow/task_events_mgr.py
tests/flakyfunctional/cylc-poll/16-execution-time-limit.t
tests/functional/execution-time-limit/04-polling-intervals.t

Remove setting of execution timeout based on execution time limit

---

CHANGES.md
cylc/flow/workflow_files.py
tests/functional/cylc-install/02-failures.t
tests/unit/test_workflow_files.py

This is a (very) small change with no associated issue - it just removes a check on source dir location.
Currently `cylc install` refuses to install a source directory that is located under `~/cylc-run`, but I don't think there's a good technical reason for that, is there??  We probably just thought it indicated user CLI error or messy housekeeping practices. 
Note there's an additional check that a source dir does not contain `_cylc_install` and `log` dirs etc., which should be sufficient for catching the primary CLI error we're presumably trying to catch (i.e. referring to run directory as a source directory).
Unfortunately the location check prevents a sub-worfklow source dir installed as part of a main workflow, from being used as the `cylc install` source for sub-workflow instances …

Allow src dir in run dir

---

CHANGES.md
cylc/flow/etc/syntax/cylc-mode.el
cylc/flow/etc/syntax/cylc.lang
cylc/flow/etc/syntax/cylc.xml

Looks like the pattern was never correct even at Cylc 7!

Emacs syntax highlighting: fix filename pattern matching

---

cylc/flow/data_store_mgr.py
cylc/flow/task_proxy.py

These changes close #4868
Probably don't need tests for lack of a spurious log message.

Don't log fake task state changes (datastore)

---

CHANGES.md
cylc/flow/workflow_files.py
tests/functional/cylc-clean/04-runN.t
tests/unit/test_workflow_files.py

This is a small change with no associated Issue. This fixes the bug:
```console
$ cylc clean my-workflow/runN
WorkflowFilesError: Invalid symlink at ~/cylc-run/my-workflow/runN
The target should end with "cylc-run/my-workflow/runN"
```

Allow cylc clean to use runN

---

cylc/flow/cfgspec/globalcfg.py
tests/functional/cylc-config/10-platform-expansion.t

#4854 did not expand comma separated platform config items in the dense config.

Expand comma separated platform names correctly

---

CHANGES.md
cylc/flow/id_match.py
cylc/flow/task_proxy.py
tests/unit/test_id_match.py
tests/unit/test_task_proxy.py

- These changes close #4843 
Can manually test by following steps to reproduce in the issue above

Fix task matching bug

---

lib/cylc/task_remote_mgr.py

This is a small change with no associated Issue. Fix an `AttributeError` that could occur if a remote tidy subprocess returned with a non-zero exit code.
I have checked and this bug is not present in Cylc 8 (fixed in https://github.com/cylc/cylc-flow/commit/a917a6f1629ec53c34988a0410b28fab1dc65d10 if anyone was interested)

Fix bug in remote tidy error handling

---

CHANGES.md
cylc/flow/scripts/clean.py

Master:
```console
$ cylc clean 'sagittarius-a*'
Would clean the following workflows:
Remove these workflows (y/n): 
```
This branch:
```console
$ cylc clean 'sagittarius-a*'
No workflows matching sagittarius-a*
```

Don't prompt to clean no workflows.

---

CHANGES.md
lib/cylc/cylc-review/template/job-entry.html
lib/cylc/review.py

These changes partially address #4782 
**Features check-list**
In `cylc review`...
```ini
[platforms]
[[submitfail]]
hosts = notahost
[[submitted]]
hosts = exvcylcdev01
install target = exvcylcdev01
communication method = poll
submission polling intervals = P1Y
```
```ini
[scheduler]
allow implicit tasks = true
[scheduling]
initial cycle point = 1
R1 = """
expired & preparing & submitted  => waiting
running & submit-failed & succeeded & failed =>waiting
"""
[runtime]
[[submitted]]
platform = submitted
[[submit-failed]]
platform = submitfail
[[running]]
script = while true; do sleep 30; done
[[failed]]
script = exit 1
```
and add the following hack to Cylc flow:
```diff
diff --git a/cylc/flow/task_job_mgr.py b/cylc/flow/task_job_mgr.py
index …
```

provided a alt list of states for filtering Cylc 8 tasks

---

cylc/flow/task_proxy.py
tests/functional/spawn-on-demand/14-trigger-flow-blocker/flow.cylc

This is a small change with no associated Issue. 
Noticed when investigating #4868 
```
R1 = foo & bar => baz
```
Run this, and in the log:
```
2022-05-13T15:18:44+12:00 INFO - [1/baz waiting(runahead) job:00 flows:1] merged in flow(s) 1
```
If `foo` finishes first and spawns `baz`, when `bar` finishes and tries to spawn `baz` it will find `baz` already in the task pool. This is not a flow merge, unless `bar` belongs to a different flow.
We probably don't need tests for lack of a spurious log message.

Don't log flow merge for same flow.

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/main_loop/__init__.py
cylc/flow/main_loop/auto_restart.py
tests/unit/main_loop/test_auto_restart.py

* Closes https://github.com/cylc/cylc-flow/issues/4873
(in combination with https://github.com/cylc/cylc-doc/pull/475)
* There is now a default main loop plugin interval of `PT10M`.
This prevents any plugins without a hardcoded default from being run with every main loop cycle.
* Explicitly set a default for the `auto restart` plugin (also `PT10M`).
* Added a note on enabling plugins.
* Suppress traceback from reloading the global config in the `auto restart` plugin.
This is now logged nicely.
* Prevent plugins from being loaded twice when specified both on the CLI
(--main-loop) and in the config (global.cylc[scheduler][main loop]plugins).

main loop: improve defaults, docs and error handling

---

cylc/flow/option_parsers.py
tests/unit/test_option_parsers.py

Allow standard options (`CylcOptionParser(auto_add=True)`) in Python API `Options` class
**Before:**
```
>>> from cylc.flow.scripts.clean import CleanOptions
>>> CleanOptions(verbosity=1)
ValueError: verbosity
```
**After:**
`CleanOptions(verbosity=1)` works as expected.

Fix optparse Options class for standard options

---

cylc/flow/id_cli.py
tests/unit/test_id_cli.py

* E.G. workflow//run/cycle rather than workflow/run//cycle.
* Closes #4923

uid: warn if the run number is provided as a cycle

---

CHANGES.md
cylc/flow/network/schema.py

These changes close #4898
```
(flow) sutherlander@graphic-vbox:cylc-flow$ python -c 'from cylc.flow.network.schema import Flow; print(Flow.__doc__); print(Flow().__doc__)'
An integer or one of all, new or none.
An integer or one of all, new or none.
```
(note:  I don't know why the previous arrangement didn't work at the UI, but this does)

expand schema docstring internally

---

cylc/flow/id.py
cylc/flow/scheduler_cli.py
tests/functional/cylc-play/10-start-task-upgrade.t

* Extend CLI upgrading to the Cylc 8 --start-task option.
* Closes #4920

play: upgrade --start-task's specified in legacy format

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/workflow.py

These changes close #4851 
- Ensure config items shared by global and workflow configs have links to each other
- Centralised such items' descriptions and display the full description for the workflow item, whereas only the first paragraph for the global item
- Tidy up these docs a bit and fix the odd mistake
Would recommend a commit-by-commit review.

Improve config reference docs

---

cylc/flow/id_match.py
tests/integration/test_task_pool.py

@oliver-sanders - I think this might be a bug in your task filtering function, found too late in the day to fully investigate - can you take a quick look, and if you agree it's a bug I'll finish off the PR?
If both the hidden pool (partially satisfied prereqs) and main pool are passed to the function - which they are, from `TaskPool.filter_task_proxies()` - it seems to return two copies of matched tasks in cycle points that appear in both pools.
These changes partially address #xxxx
These changes close #xxxx

Fix task filtering.

---

CHANGES.md
cylc/flow/data_store_mgr.py
cylc/flow/task_events_mgr.py

Fix job state with pre-submitted failure

---

cylc/flow/cfgspec/globalcfg.py

Related to #4836
* Log rollover happens for each restart, if workflows are repeatedly restarted (which often happens when problems occur) the sequence of events can be lost.
* Increase the archive length from 5 to 15.
* Note we have recently reduced the rollover size from 10Mb to 1Mb.
**Question:** Does 15 seem like a sensible number?

glblcfg: increase default rolling archive length

---

cylc/flow/scripts/clean.py

Message was going to stdout which kinda made sense? Redirected it to stderr via the log so it shows up UIS side.

clean: push error message to stderr

---

cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/cycling/iso8601.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/02-targeted.t
tests/functional/cylc-install/03-file-transfer.t
tests/functional/cylc-reinstall/01-file-transfer.t
tests/functional/optional-outputs/03-c7backcompat.t
tests/functional/optional-outputs/04-c7backcompat-blocked-task.t
tests/functional/optional-outputs/05-c7backcompat-blocked-task-2.t
tests/functional/optional-outputs/06-c7backcompat-family.t
tests/functional/validate/37-special-implicit-task.t
tests/functional/validate/67-relative-icp.t
tests/unit/cfgspec/test_workflow.py
tests/unit/test_config.py

- ~Simplify graph back compat warning and include link to docs~ Cut down on back compat warnings, on the basis they're not actionable while in back compat mode
- Replace `Task foo: deprecated "host" and "batch system" use "platform"` warning with something clearer
- Clear up cryptic comments - closes https://github.com/cylc/cylc-flow/issues/4805
- Other small acts of tidying over the course of time

Cut down on back-compat warnings, plus other tidying

---

cylc/flow/config.py
tests/unit/test_config.py

Do not suggest using allow implicit tasks setting when `rose-suite.conf` present in c7 back-compat mode
This is a small change follow-up to #4943, which I forgot to stage

Back compat deprecation warnings - an addendum

---

cylc/flow/task_pool.py
tests/functional/optional-outputs/07-finish-fail-c7-backcompat.t
tests/functional/optional-outputs/08-finish-fail-c7-c8.t
tests/functional/optional-outputs/finish-fail-c7/suite.rc

Ignore incomplete tasks in computing the runahead limit, in back compat mode.
(Because: Cylc 7 ignores failed tasks in computing the limit).
These changes close #4965
From comments in the new func test workflow:
```
```

Back-compat mode tweak.

---

tests/functional/cylc-reinstall/03-external-files.t
tests/unit/test_workflow_files.py

Tests salvaged from #4953 - to test that `cylc reinstall` uses rsync delete mode as expected. Probably still useful to have?
Note the small change to the unit test on this branch is not strictly required, but still makes the code a bit clearer.

Test reinstall deletion

---

CHANGES.md
cylc/flow/task_pool.py
cylc/flow/taskdef.py
tests/functional/spawn-on-demand/16-c7backcompat-self-suicide.t
tests/functional/spawn-on-demand/16-c7backcompat-self-suicide/reference.log
tests/functional/spawn-on-demand/16-c7backcompat-self-suicide/suite.rc
tests/functional/spawn-on-demand/17-c7backcompat-self-suicide-cycling.t
tests/functional/spawn-on-demand/17-c7backcompat-self-suicide-cycling/reference.log
tests/functional/spawn-on-demand/17-c7backcompat-self-suicide-cycling/suite.rc

Back-compat: fix self-suicide: a:fail => !a

---

cylc/flow/scripts/cylc.py
cylc/flow/scripts/trigger.py

These changes close #4972 
`cylc help`:
- remove some duplication of example sub-commands
- make it clearer that listed sub-commands are not exhaustive
- reorder content by importance (abbreviations are less important than ID)

Tidy main command help.

---

cylc/flow/scripts/common.py

Supersede #4921
Compact terminal banner, with a decent rendition of the Cylc logo in block characters.
Counting explicit comments and thumbs-up, this version is declared the winner by 4 votes (including my own) to none.

CLI banner: cylc logo with block characters.

---

cylc/flow/network/schema.py
cylc/flow/scripts/broadcast.py

Small changes to the broadcast mutation docs.
Closes the cylc-flow side of #4902, the (larger) cylc-ui portion has been moved to https://github.com/cylc/cylc-ui/issues/647.

schema: small docs changes

---

.github/workflows/test_functional.yml
CHANGES.md
cylc/flow/main_loop/health_check.py
cylc/flow/network/scan.py
cylc/flow/scheduler.py
cylc/flow/task_remote_mgr.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/05-old-remote-contact.t
tests/integration/test_scan.py
tests/unit/test_workflow_files.py

From Teams:
>Cylc clean bug report... it looks like it is trying to perform the whole "is this workflow running" check on the remote side as well as the invocation side which isn't right:
>```
>$ cylc clean u-co906/run1
>INFO - Cleaning u-co906/run1 on install target: ab
>ERROR - Could not clean u-co906/run1 on install target: ab
>    platform: abc - clean up did not complete
>    COMMAND:
>        ssh CYLC_VERSION=8.0rc4.dev CYLC_ENV_NAME=cylc-8.0rc4.dev-3 \
>            bash --login -c 'exec "$0" "$@"' timeout 120 cylc clean \
>            --local-only u-co906/run1
>    RETURN CODE:
>        1
>    STDOUT:
>    STDERR:
>        CylcError: Cannot determine whether workflow is running on <scheduler-host>.
> …
```

Fix failure to clean on remote host with leftover contact file

---

CHANGES.md
cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/platforms.py
cylc/flow/task_job_mgr.py
tests/functional/events/11-cycle-task-event-job-logs-retrieve/flow.cylc
tests/functional/events/32-task-event-job-logs-retrieve-2.t
tests/functional/events/32-task-event-job-logs-retrieve-2/flow.cylc
tests/functional/events/33-task-event-job-logs-retrieve-3.t
tests/functional/events/33-task-event-job-logs-retrieve-3/flow.cylc
tests/functional/intelligent-host-selection/02-badhosts.t
tests/functional/intelligent-host-selection/02-badhosts/flow.cylc
tests/unit/test_platforms.py
tests/unit/test_platforms_get_platform.py

These changes close #4944.
> * Setting `[runtime][<task>][remote]retrieve job logs = false` on a task specified in the old way results in a "No platform found matching your task" error (my platform definition for the matching host has log retrieval enabled) . This appears to working as intended.
> * Setting `[runtime][<task>][remote]retrieve job logs = false` on a task specified using a platform does not result in a validation error so this needs fixing.

Fix lack of errors/warnings for deprecated `[runtime][<task>][remote]retrieve job logs *` settings

---

cylc/flow/rundb.py
tests/unit/test_rundb.py

Log the attempted transaction if an error occurs when trying to write to the private DB to assist with debugging.
The intention is to help debug a reported issue but makes sense to add this logging for all uses.

db: log failed transaction on error

---

CHANGES.md
cylc/flow/task_pool.py
cylc/flow/taskdef.py
tests/integration/test_task_pool.py

These changes close #5002
I've run the example out to 50 cycle points several times, with nothing strange happening 
I haven't thought of a reliable way to reproduce the problem (which was more of an inefficiency + confusing warning than a balls-to-the-wall bug) in a short test. But codecov says the change is covered in a strictly technical sense at least.

Fix spawning of absolute-triggered tasks.

---

cylc/flow/scripts/lint.py

Add spaces so that the next heading after [this one](https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/configuration.html#module-cylc.flow.scripts.lint) ("7 to 8 upgrades") renders correctly.

Added blank line to have linter rules render properly

---

cylc/flow/cfgspec/workflow.py
tests/functional/cylc-config/00-simple/section1.stdout

* Closes #5010
* Set `[scheduling][queues][default]limit=100`.

queues: set default limit

---

CHANGES.md
cylc/flow/scripts/clean.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/03-multi.t
tests/unit/test_workflow_files.py

These changes close #4963
When cleaning all runs or the last remaining run in a workflow dir, `cylc clean` will now also remove the `_cylc-install` and top level directory, if it is empty.

cylc clean: remove top level dir when no run dirs left

---

CHANGES.md
cylc/flow/workflow_db_mgr.py
tests/integration/test_workflow_db_mgr.py
tests/integration/utils/flow_tools.py

Closes #4918
A bug was causing the restart number to be wiped from the `workflow_params` table in the DB on reload.

Fix restart number bug

---

cylc/flow/task_proxy.py
tests/functional/reload/25-xtriggers.t

* Closes https://github.com/cylc/cylc-flow/issues/4866
* Reload causes new instances of each task to be created.
* The attributes of the old instances are copied onto the new ones.
* Retry xtriggers were not copied so were lost.
* This means that all retry pending tasks would run immediately on reload.

reload: preserve retry xtriggers on reload

---

CHANGES.md
cylc/flow/cycling/__init__.py
cylc/flow/cycling/iso8601.py
cylc/flow/time_parser.py
tests/unit/test_config.py

These changes close #4908
Fix bug where specifying multiple datetime offsets would not obey the given order.
E.g. `final cycle point = +P1M-P1D` would lead to it calculating `icp - P1D + P1M` (smallest unit to largest unit order) instead of `icp + P1M - P1D` (given order).

Fix chained offset bug

---

cylc/flow/pathutil.py
tests/unit/test_pathutil.py

Small tweak, and clarification, of an unnecessarily verbose error message from `cylc install`.
Before (with line breaks added):
```
WorkflowFilesError: Unable to create symlink to /big/disk/$PROJECT/oliverh/cylc-run/bug/run3.
'$DATA/$PROJECT/$USER/cylc-run/bug/run3' contains an invalid environment variable.
Please check configuration.
```
After:
```
WorkflowFilesError: Can't symlink to /big/disk/$PROJECT/oliverh/cylc-run/bug/run3
Undefined variables, check global config: $PROJECT
```
**Check List**

Shorten error msg

---

conda-environment.yml
cylc/flow/async_util.py
setup.cfg
tests/integration/test_async_util.py

* Closes #5006
* We were using pyuv to perform directory listing.
* Unfortunately pyuv is no longer actively maintained.
* Switching to the simpler method of running `os.listdir` in an executor
ala aiofiles.
* Unblocks #4524

scan: switch from pyuv to os.listdir in asyncio executor

---

cylc/flow/task_proxy.py
tests/functional/reload/25-xtriggers.t

8.0.x version of https://github.com/cylc/cylc-flow/pull/5040

reload: preserve xtriggers on reload

---

CHANGES.md
cylc/flow/loggingutil.py
cylc/flow/main_loop/auto_restart.py
cylc/flow/scheduler.py
cylc/flow/task_remote_mgr.py
cylc/flow/workflow_files.py
tests/conftest.py
tests/functional/lib/bash/test_header
tests/functional/restart/34-auto-restart-basic.t
tests/functional/restart/41-auto-restart-local-jobs.t
tests/integration/main_loop/test_auto_restart.py
tests/integration/test_scheduler.py
tests/unit/main_loop/test_auto_restart.py

- Fix bug where sometimes the scheduler log would rollover unnecessarily on auto restart, with clashing log count number in the filename (closes #4945)
- Ensure the workflow restarts with the same verbosity.
- Fix bug where the workflow was failing to abort if auto restart was attempted in no-detach mode
- Prevent unexpected exceptions raised during auto restart from being swallowed
Reviewers should run `tests/functional/restart` tests
**Check List**

Fix auto restart bugs

---

CHANGES.md
cylc/flow/loggingutil.py
cylc/flow/main_loop/auto_restart.py
cylc/flow/network/__init__.py
cylc/flow/network/scan.py
cylc/flow/parsec/fileparse.py
cylc/flow/scheduler.py
cylc/flow/task_proxy.py
cylc/flow/task_remote_mgr.py
cylc/flow/tui/app.py
cylc/flow/workflow_files.py
cylc/flow/xtriggers/echo.py
tests/conftest.py
tests/functional/lib/bash/test_header
tests/functional/reload/25-xtriggers.t
tests/functional/restart/34-auto-restart-basic.t
tests/functional/restart/41-auto-restart-local-jobs.t
tests/integration/main_loop/test_auto_restart.py
tests/integration/test_scheduler.py
tests/unit/main_loop/test_auto_restart.py

8.0.x: bugfixes

---

CHANGES.md
lib/cylc/task_pool.py

These changes close #4516
Fix bug where failed tasks could be polled back to incorrect states on restart.

add owner@host for SUCCEEDED and FAILED tasks

---

cylc/flow/network/scan.py

* During a scan directories are listed asynchronously and recursively.
* If a directory is queued for listing, but then deleted before the
listing takes place a FileNotFoundError will occur.
* This is highly unlikely IRL, however, in the integration tests, where run
dirs are created and destroyed at scale and in parallel this is
actually quite likely.
Example fail: https://github.com/cylc/cylc-flow/runs/7805964418?check_suite_focus=true
Likely caused by #5028, not sure why, perhaps it didn't raise the error, perhaps it was more eager with its scheduling.
Tested with 110X parallelism (`pytest -n 110 tests/integration`), couldn't reproduce post-fix.
**Check List**

scan: ignore FileNotFoundError

---

CHANGES.md
cylc/flow/scheduler.py
tests/unit/test_scheduler.py

Fix bug where any preparing local jobs would get orphaned during the shutdown before an auto restart.
You could reproduce this bug by changing
```diff
diff --git a/tests/functional/restart/42-auto-restart-ping-pong.t b/tests/functional/restart/42-auto-restart-ping-pong.t
index 5f897b33e..ecf58e99f 100644
--- a/tests/functional/restart/42-auto-restart-ping-pong.t
+++ b/tests/functional/restart/42-auto-restart-ping-pong.t
@@ -74,5 +74,5 @@ log_scan2() {
}
-EARS=5  # number of times to bounce the workflow between hosts
+EARS=40  # number of times to bounce the workflow between hosts
NO_TESTS="$(( EARS * 5 + 1 ))"
set_test_number "${NO_TESTS}"
```
and running the test, eventually it would orphan a preparing job and cause the test to fail.
**Check List**

Wait for preparing tasks to submit before auto restart

---

CHANGES.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Partially addresses #5052 - 
- Hardcodes the numbers for the Style fails
- Adds the ability to ignore individual exception codes using `--ignore` or `-n`.
**Check List**

Lint.hardcode style index numbers

---

CHANGES.md
cylc/flow/data_store_mgr.py
tests/functional/restart/58-removed-task.t
tests/functional/restart/58-removed-task/flow.cylc

Close #5057 
Fix datastore bug on restart after removing a task from the graph.
**Check List**

Datastore fix for removed taskdef.

---

.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
.github/workflows/test_manylinux.yml
setup.cfg

Add support for Python 3.10.
Note 3.11 is now nearing release but we can't install our deps with it just yet...
> **Note:** We may need to change the conda-forge metadata for the 8.1.0 release.

python: Add 3.10 support

---

CHANGES.md
cylc/flow/task_pool.py

add platform on reload for SUCCEEDED and FAILED tasks

---

CHANGES.md
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-rainfall
cylc/flow/etc/tutorial/cylc-forecasting-workflow/lib/template/map.html
setup.cfg

- Map HTML file was broken due to the Jinja2 (?) double curly brackets being broken over lines
- `urllib3` requests no longer working with Met Office proxy, used `requests` instead, which is nicer actually
**Check List**

Fix tutorial workflows

---

cylc/flow/task_pool.py

These changes partially address #4990
Preparing tasks might have written their job file at time of reload (we're not sure), so amend the warning that preparing tasks get at reload to say they "may" be active with pre-reload config.
**Check List**

Slightly different warning for preparing tasks on reload

---

CHANGES.md
cylc/flow/cycling/__init__.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/task_state.py
tests/functional/reload/26-stalled.t

These changes close #5103
Reloading a stalled workflow was causing the workflow to stall again (twice). This PR prevents reloads from unstalling the workflow, so the subsequent stalls do not happen
**Check List**

Fix repeated stall when reloading a stalled workflow

---

CHANGES.md
cylc/flow/cfgspec/workflow.py
cylc/flow/parsec/upgrade.py
tests/functional/deprecations/00-pre-cylc8.t
tests/functional/deprecations/01-cylc8-basic/validation.stderr
tests/unit/parsec/test_upgrade.py
tests/unit/scripts/test_lint.py

Partially address #5116 
Deprecation warnings are being printed with section brackets, even for non-section items: 
`[cat][dog][fish]` instead of `[cat][dog]fish`
**Check List**

Fix deprecation warning format.

---

lib/cylc/review.py
lib/cylc/review_dao.py

Closes #5108 
@datamel tagged for code review.
@dpmatthews tagged for functional review as originator of the bug report.
Installing a workflow (Cylc 7 or 8) without starting it causes no `broadcast_events` or `broadcast_states` tables to be created in the suite database, but I don't see why this should lead to error messages in the table. I suspect it's not come up before because I doubt anyone has run `rose suite-run -i` and then moved straight to Cylc Review.
The log files menus have become a touch confused. To keep things simple I have set up Cylc review to put all log items in the "cylc" menu if it's a Cylc 8 workflow, but to maintain existing behavior otherwise. If the reviewer insists I'll create a new issue to tidy up the menu items. One could even split up the different log …

Fix assorted cylc review bugs

---

CHANGES.md
cylc/flow/loggingutil.py
cylc/flow/scheduler.py
tests/functional/logging/05-validation-detach.t

Closes #4982, follow-up to #4836
Fix bug where a validation error on workflow startup was not being printed before demonization (aka detach), which made it look like nothing was wrong. Also the return code was zero instead of non-zero as it should be.
This partially reverts some of the logging re-ordering from #4836
**Check List**

Revert order of scheduler `configure()` & `log_start()`

---

CHANGES.md
cylc/flow/network/publisher.py
cylc/flow/network/replier.py
cylc/flow/network/server.py
cylc/flow/scheduler.py
tests/integration/test_server.py
tests/integration/test_zmq.py
tests/unit/network/test_publisher.py

Closes #5092 
Fix bug where the final deltas were not being published before stopping the `WorkflowRuntimeServer` at shutdown
**Check List**

Ensure queued deltas are published before shutdown

---

CHANGES.md
cylc/flow/remote.py
cylc/flow/subprocpool.py
cylc/flow/task_events_mgr.py
tests/functional/events/17-task-event-job-logs-retrieve-command.t

Closes https://github.com/cylc/cylc-flow/issues/5113
rsync version 3.2.4 version drops (seemingly undocumented) support for use of `$HOME` in the command. This is historically the implementation we have been using for some time, without issue but requires fixing due to this rsync change.
Note $HOME is only removed for rsync (remote file installation and log retrieval), not for other use cases of the remote run directory, e.g. job submission.
**Check List**

Remove HOME Env Variable from get_remote_workflow_run_dir

---

etc/cylc-bash-completion

The Cylc 7 completion breaks in a nasty way with Cylc 8.
This change prevents stderr from getting to the user's console.
**Check List**

completion: make completion compatible with Cylc 8

---

CHANGES.md
cylc/flow/xtriggers/workflow_state.py
tests/unit/xtriggers/test_workflow_state.py

Closes #5126 
Infer the run number if not specified in the `workflow_state` xtrigger
**Check List**

`workflow_state` xtrigger: infer run number

---

tests/functional/lib/bash/test_header

The test function `create_test_global_config` should create a valid global config file even if `global-tests.cylc` contains Jinja2 code.
This only affects tests, and is a trivial fix, so I don't think it needs a test itself, or a change log entry.
**Check List**

Assume Jinja2 used in global-tests.cylc.

---

cylc/flow/parsec/jinja2support.py
tests/functional/cylc-get-site-config/04-homeless.t

Fix a functional test broken by merge of #5148 
Change log not needed (only affects a test)
**Check List**

Fix Jinja2 support if HOME undefined.

---

.github/workflows/bash.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
.github/workflows/test_tutorial_workflow.yml

I think without this the Codecov patch coverage figure for PRs on 8.0.x branch were not accurate as it was using the wrong base commit (because it didn't have coverage for any of the merge commits, including squash-merges).
**Check List**

Run GH Actions tests on push to `8.*.x` branches

---

CHANGES.md
cylc/flow/install_plugins/log_vc_info.py
tests/unit/post_install/test_log_vc_info.py

Closes #5117. Fixes bug where `cylc install` would hang if the uncommitted diff of the source dir repo was large.
Instead of using `subprocess.PIPE` for the output of git/svn diff commands, use the file object itself. This avoids blocking the pipe if the diff is large, and also has the benefit of not loading large amounts of text into memory.
**Check List**

`log_vc_info`: Redirect diff straight to file to avoid blocking pipe

---

CHANGES.md
cylc/flow/cfgspec/workflow.py
cylc/flow/remote.py
tests/functional/remote/01-file-install.t
tests/unit/test_remote.py

* The `ana/` directory is used by `rose_ana` to load "compotators" (custom comparison thinggies).
* These are typically run where the data is generated which is often remote.
* These directories typically contain a small number of Python files.
**Check List**

remote-install: add "ana/" to the default install list

---

cylc/flow/network/__init__.py
cylc/flow/network/client.py
cylc/flow/network/publisher.py
cylc/flow/network/replier.py
cylc/flow/network/server.py
cylc/flow/network/subscriber.py
cylc/flow/scheduler.py
tests/integration/test_server.py

Plus some tidying & adding type annotations.
This was split off from #5098
**Check List**

Simplify `WorkflowRuntimeServer` stop logic

---

cylc/flow/parsec/fileparse.py

@oliver-sanders - in response to your question on Element chat.  One review will do.
Stop logging of "Section already encountered" during config parsing.
**Check List**

Don't log duplicate config sections.

---

CHANGES.md
cylc/flow/exceptions.py
cylc/flow/id_cli.py
cylc/flow/network/resolvers.py
cylc/flow/option_parsers.py
cylc/flow/scheduler.py
cylc/flow/scripts/message.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/task_message.py
cylc/flow/task_pool.py
tests/flakyfunctional/cylc-poll/16-execution-time-limit.t
tests/functional/cylc-message/02-multi.t
tests/functional/events/26-workflow-stalled-dump-prereq.t
tests/functional/events/27-workflow-stalled-dump-prereq-fam.t
tests/functional/hold-release/02-hold-on-spawn.t
tests/functional/hold-release/18-hold-cycle-globs.t
tests/functional/hold-release/19-no-reset-prereq-on-waiting.t
tests/functional/lib/bash/test_header
tests/functional/optional-outputs/07-finish-fail-c7-backcompat.t
tests/functional/reload/25-xtriggers.t
tests/functional/remote/05-remote-init.t
tests/functional/remote/06-poll.t
tests/functional/spawn-on-demand/07-abs-triggers.t
tests/functional/spawn-on-demand/11-abs-suicide.t

> Built on #5081
> Addresses #3647
Follow on from #5081, tidy up some additional logging.
1) Remove the "CRITICAL" log message for failed tasks.
* Task failure is logged either two or three times.
* If the failure is a problem we will get a "did not complete required outputs" message at a higher level.
```diff
2022-09-29T08:49:27Z INFO - [20191209T1200Z/foot running job:01 flows:1] => failed
-2022-09-29T08:49:27Z CRITICAL - [20191209T1200Z/foot failed job:01 flows:1] failed
2022-09-29T08:49:27Z WARNING - [20191209T1200Z/foot failed job:01 flows:1] did not complete required outputs: ['succeeded']
```
2) Bump "Incomplete tasks" messages from WARNING to ERROR
* Incomplete outputs require operator intervention to overcome.
* This represents an error in graph execution.
* This should be made …

Further log tidy

---

CHANGES.md
conda-environment.yml
cylc/flow/scripts/lint.py
setup.cfg
tests/functional/cylc-lint/00.lint.t
tests/functional/cylc-lint/01.lint-toml.t
tests/unit/scripts/test_lint.py

Closes #5052 
**Check List**
- It has [no dependencies](https://github.com/hukkin/tomli#why-this-parser)
- [Uses MIT licence](https://github.com/hukkin/tomli/blob/master/LICENSE)

pyproject.toml: cylc lint settings

---

cylc/flow/exceptions.py
cylc/flow/host_select.py
cylc/flow/scripts/psutil.py
tests/unit/test_exceptions.py
tests/unit/test_host_select.py
tests/unit/test_host_select_remote.py

Currently we can configure Cylc to select the host with the LEAST available memory:
```
virtual_memory().available
```
But not the most:
```
-1 * virtual_memory().available
```
Because the required operator is not on the whitelist. This PR adds the required operator to the whitelist allowing us to use it and adds more logging / error output for host selection to make it more transparent when things go wrong.
**Check List**

host select: allow unary operators in ranking expressions

---

CHANGES.md
cylc/flow/workflow_files.py
tests/integration/test_reinstall.py

Fixes two separate, but related bugs (one of which was partially protecting us from the other, except when using rose stem):
`cylc reinstall` relied on the rsync stdout being empty to choose not to reinstall. Under some circumstances messages such as `cannot delete dirctory: opt` were causing re-installations unnecessarily.
Under many circumstances the first bug was allowing re-installation to be triggered when only the `rose-suite.conf` had changed, despite `rose-suite.conf` being on the list of files excluded from the rsync.
With the first bug fixed users could change the source `rose-suite.conf` and have Cylc tell them that nothing required re-installing.
**Check List**

reinstall changes to `rose-suite.conf`

---

cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Unbackticked code in docstring causing spellcheck failure
Seealso https://github.com/cylc/cylc-doc/pull/550
**Check List**

fix docstring with literal unquoted

---

CHANGES.md
cylc/flow/rundb.py
cylc/flow/scheduler.py
cylc/flow/workflow_db_mgr.py
cylc/flow/workflow_files.py
tests/functional/job-submission/01-job-nn-localhost/db.sqlite3
tests/functional/restart/57-ghost-job/db.sqlite3
tests/integration/conftest.py
tests/integration/test_workflow_db_mgr.py

Follow-up #5023 
Supersede #5173 
Automatically upgrade pre-8.0.3 DBs (at restart) by adding the new task_states "is_manual_submit" column.
**Check List**

Db upgrade 8.0.3

---

.github/workflows/test_functional.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
**Check List**

GH Actions: upgrade deprecated set-output command

---

CHANGES.md
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

This is a trivial fix, but diagnosing the problem was complicated by #5186 
With the example of #5185, on this branch:
Run till stalled with 1,2,3,4,5/b failed.
-  `cylc remove bug//1/b:failed` removes `1/b`, and the scheduler releases `6/b` from runahead :+1:
-  `cylc remove bug//*/b:failed` removes all failed `b`, and the scheduler releases the next 5 cycles from runahead :+1: 
- (`cylc remove bug//*/*:failed` still causes a shutdown, because the scheduler erroneously removes `6/b:waiting` via bug #5186 :-1:  ... fixed by #5188 :+1: )
**Check List**

Recompute runahead limit after `cylc remove`

---

CHANGES.md
cylc/flow/id.py
cylc/flow/scripts/hold.py
cylc/flow/scripts/kill.py
cylc/flow/scripts/poll.py
cylc/flow/scripts/release.py
cylc/flow/scripts/remove.py
cylc/flow/scripts/set_outputs.py
cylc/flow/scripts/show.py
cylc/flow/scripts/trigger.py
tests/unit/test_id.py

* Selectors were not correctly preserved for the `task` and `workflow` properties of `Tokens` objects.
* This effectively stripped cycle/task selectors from IDs passed to `cylc trigger`.
* Closes https://github.com/cylc/cylc-flow/issues/5186
**Check List**

id: preserve selectors for "task" and "workflow" properties

---

cylc/flow/scheduler.py

Fixes a problem where an unexpected exception raised during the scheduler shutdown - before it gets to closing the workflow runtime server thread - would cause Cylc to hang because Python doesn't like that.
**Check List**

Make shutdown more robust

---

CHANGES.md
cylc/flow/network/client.py
cylc/flow/network/scan.py
cylc/flow/scheduler.py
tests/integration/test_scan_api.py

This fixes a bug found by @dpmatthews and not recorded elsewhere.
- Create a simple workflow with a long running task on a remote host.
- Start workflow, noting the PID.
- Copy the workflow contact file
- Kill the workflow using the PID
- Restore the workflow contact file
- Run Cylc Scan
Traceback from an uncaught Exception.
```
File "/home/h03/fcm/cylc-8.0.2-1/lib/python3.9/site-
packages/cylc/flow/network/scan.py", line 464, in graphql_query
ret = await client.async_request(
File "/home/h03/fcm/cylc-8.0.2-1/lib/python3.9/site-
packages/cylc/flow/network/client.py", line 198, in async_request
self.timeout_handler()
File "/home/h03/fcm/cylc-8.0.2-1/lib/python3.9/site-
packages/cylc/flow/network/client.py", line 331, in _timeout_handler
raise …
```

fix an error handling bug in Cylc Scan

---

CHANGES.md
cylc/flow/scripts/install.py
tests/integration/test_install.py
tests/integration/test_scan.py

Close #5127
Scan and report any running instances of a workflow at install time.
(Note I've used the WARNING color, but without saying "WARNING:" on grounds that already-running instances of an installed  workflow might possibly indicate user error, but probably do not ... but I'm not particularly invested in this coloring!).
**Check List**

Scan workflow name during install.

---

.github/workflows/test_fast.yml
.github/workflows/test_functional.yml

The Codecov upload action is failing very flakily with 404 errors (https://github.com/codecov/codecov-action/issues/598). I have seen commits on other repos referencing that issue where they explicitly pass the Codecov token as an arg to the action, worth a shot. Apparently the 404 errors may be due to rate-limiting, so hopefully using the token will use an independent limit.
I've also skipped linkcheck on MacOS to help speed it up a bit.
**Check List**

GH Actions Codecov upload: try using token arg

---

CHANGES.md
cylc/flow/etc/tutorial/consolidation-tutorial/etc/met-office-sites.dat
cylc/flow/etc/tutorial/consolidation-tutorial/flow.cylc

Fix consolidation tutorial

---

cylc/flow/scheduler_cli.py
cylc/flow/terminal.py
cylc/flow/workflow_db_mgr.py
tests/functional/job-submission/01-job-nn-localhost.t
tests/functional/job-submission/02-job-nn-remote-host.t
tests/functional/restart/57-ghost-job.t
tests/integration/test_workflow_db_mgr.py
tests/unit/test_scheduler_cli.py
tests/unit/test_terminal.py

* Closes #4039
* When restarting a workflow, check the version it previously ran under
against the current version in order to determine if the change is
sensible.
* Restart normally if the restart would:
* Not change the version.
* Increase the maintenance number.
* Prompt (override with --yes) for confirmation if the restart would:
* Reduce the maintenance number.
* Increase the minor number.
* Exit with nasty error (override with --force or --yes --yes?) if
the restart would:
* Decrease the minor number.
* Change the major number.
* This also moves the pre-existing workflow DB check from post-detatch
to pre-detach.
**Check List**

play: check Cylc version on restart

---

CHANGES.md
cylc/flow/cycling/iso8601.py
tests/unit/cycling/test_iso8601.py

Responds to comment at https://github.com/cylc/cylc-doc/issues/19#issuecomment-499054436
e.g. `icpt = now (T-15, T-45)` should be `icp = now (T-15; T-45)`
current behavour: Fail with scary traceback
new behaviour: Fail with helpful message
**Check List**

Handle comma separated ICP lists elegantly

---

cylc/flow/exceptions.py
cylc/flow/network/ssh_client.py
cylc/flow/network/subscriber.py
cylc/flow/parsec/empysupport.py
cylc/flow/parsec/jinja2support.py
cylc/flow/platforms.py
cylc/flow/scheduler_cli.py
cylc/flow/task_state.py
cylc/flow/timer.py

Fixes MyPy failing on master because `--no-implicit-options=True` is not default. See https://github.com/python/mypy/pull/13401
I think that this is a single reviewer change.
**Check List**

Allow for MyPy making --no-implicit-optional default

---

.github/workflows/test_functional.yml

It looks like the TB is failing all of a sudden with traceback suggesting `at` is not installed.
**Check List**

actions: install at

---

cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
tests/unit/network/test_schema.py

Follow-up to #5138, use custom object type `RuntimeSetting` instead of `GenericScalar` in schema
**Check List**

Enable broadcast from UI Edit-Runtime form

---

cylc/flow/scripts/view.py

Allow the removal of some instances of subprocess from Cylc Rose in https://github.com/cylc/cylc-rose/pull/196.
**Check List**

make cylc view api importable

---

cylc/flow/parsec/util.py

Low-hanging fruit spotted when profiling a workflow with a very high number of tasks:
* `pop(0)` is `O(N)` for lists, but `O(1)` for deques.
* For a sample graph with ~37'000 nodes this halves `m_override` compute time from ~13s to ~6.3s.
**Check List**

efficiency: switch from list to deque

---

cylc/flow/workflow_status.py
tests/unit/test_workflow_status.py

* Change the workflow message to handle the stalled state.
* The stopping state is now shown in preference to the paused state which makes more sense.
* This either closes or partially addresses #5256.
**Check List**

workflow status: handle the stalled state

---

CHANGES.md
cylc/flow/host_select.py
cylc/flow/network/ssh_client.py
cylc/flow/remote.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/cat_log.py
cylc/flow/scripts/check_versions.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py
cylc/flow/workflow_files.py
tests/functional/events/51-task-event-job-logs-retrieve-4.t
tests/integration/test_task_job_mgr.py
tests/unit/scripts/test_check_versions.py
tests/unit/test_host_select.py

* Catch NoHostsError in the code it can occur in.
* Attempt to handle the error in these contexts.
* Mark the functions where the error can crop up for future warning.
**Check List**

ihs: catch NoHostsError

---

cylc/flow/scripts/completion_server.py

A couple of small things:
* Increase the timeout of the completion server from 5 to 15 mins.
* Server timeouts are a little annoying when they happen so often.
* Could potentially increase further? We can always change this later (no reinstallation required).
* ~Rename "cat-log" to "log":
* ~"log" used to be an alias for "cat-log".~
* ~But "log" seems clearer and is easier to type.~
* ~Maintain "cat-log" as an alias.~
~Will `s/cat-log/log` in the docs if approved.~
**I have bailed out of the `cat-log` change as the way aliases are handled changed whilst this PR was under review. Can come back to that later**
**Check List**

completion: increase timeout

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/cfgspec/workflow.py

Tasks only go to the failed state if the job fails with no retries left.
Companion of https://github.com/cylc/cylc-doc/pull/571
**Check List**

Document final try fail behaviour.

---

.github/workflows/test_fast.yml

This is a small change to the working of our CI tests.
The check that links in docstrings and comments are valid does not need to be run in all 5 fast_test scenarios.

linkcheck only happens on one fast test

---

cylc/flow/config.py
tests/flakyfunctional/job-submission/19-chatty.t
tests/functional/hold-release/08-hold.t
tests/functional/triggering/16-fam-expansion.t
tests/integration/test_config.py

More low hanging fruit spotted whilst profiling a large workflow.
If you want a unique list, so long as order doesn't matter it's faster to use a set because the lookup time is so quick.
* Change the type of `descendants[<namespace>]` and `first-parent descendants[<namespace>]` fields from `list` to `set`.
* Set has faster lookup `O(1)` which makes additions faster (because the checking is faster).
* Lookups are common with these sets in `cylc.flow.config` so this may speed up a few methods.
* The method which gains the most is `compute_family_tree` where I've seen a reduction of ~34s down to ~1.75s for a workflow with a large number of task proxies.
**Check List**

config: descendants list -> set

---

cylc/flow/rundb.py
cylc/flow/scheduler_cli.py
cylc/flow/terminal.py
cylc/flow/workflow_db_mgr.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/03-multi.t
tests/functional/database/07-incompatible.t
tests/unit/test_workflow_files.py

* Closes #5270
* Only upgrade the database after the user has answered th prompt saying that they want to upgrade!
* Remove the DB upgrade from the logic used by `cylc clean` as this is currently pointless.
* Add notes and comments to ensure we preserve clean compatibility with newer versions of Cylc (or at least so we know when we break compat).
**Check List**

play: upgrade DB *after* user upgrade confirmation 

---

cylc/flow/config.py
cylc/flow/task_trigger.py
tests/functional/triggering/16-fam-expansion.t

Addresses https://github.com/cylc/cylc-flow/pull/5245#discussion_r1054704471
Ensure that conditional expressions output by `cylc show` aren't random by sorting tasks within families by name. This isn't technically a requirement of `cylc show`, but it does make the functional tests more deterministic and seems like a nice thing to do in general (tasks will now appear in expressions in name order).
Note, this extra sort shouldn't impact on performance too badly for large families as this sorting is performed once per family with a worst-case complexity of `O(nlogn)`whereas before it was checking for duplicates before each insertion which is `O(n^2)`.
Using the example which started this off the impact of this change is within the uncertainty of results.
User time (seconds): 121.79
System …

show: ensure stable expression output

---

CHANGES.md
cylc/flow/task_job_mgr.py

* Closes #5276
* Poll and kill will retry on another host if one is availible but will not reset bad_hosts.
> Note that even if polling fails, Cylc still reports `Command succeeded: poll_tasks` in the log which is a different issue - #5293.
**Check List**

poll/kill: don't retry on NoHosts error

---

CHANGES.md
cylc/flow/cycling/__init__.py
cylc/flow/scheduler.py
cylc/flow/task_job_mgr.py
cylc/flow/task_proxy.py
tests/functional/special/08-clock-trigger-retry.t

Closes #5217
Fix bug where old-style clock triggered tasks would skip execution retry delays and just retry immediately.
**Check List**

Fix clock trigger execution retry delay bug

---

cylc/flow/scheduler.py
tests/unit/test_scheduler.py

If an error occurs during auto-restart then the scheduler will wait a little while, then try again up to two more times before finally giving in and falling over.
This PR extends this retry mechanism to cover DNS errors in order to make the auto-restart logic more robust to transient DNS issues.
**Check List**

auto-restart: improve robustness to DNS errors

---

cylc/flow/scripts/validate_reinstall.py
tests/unit/scripts/test_validate_reinstall_units.py

This PR documents the bug as well as fixing it. There is no related issue. Follow-up to #5229
`--set` and `--set-file` were included by mistake in `cylc vr` because I copied the general form of VR from `cylc vip` where it makes sense. Reinstall doesn't use these CLI variables so they won't change the workflow. This is potentially misleading to users.
```ini
#!jinja2
[scheduler]
allow implicit tasks = ture
[scheduling]
[[graph]]
{{CYCLE}}= foo => bar => baz
```
then,
On the command line
```bash
cylc vip --set 'CYCLE="PT1H"'
...
cylc vr --set 'CYCLE="PT2H"' 
```
**Check List**

Restrict `--set` & `--set-file`  options in `cylc vr`

---

tox.ini

This is a very small change designed to silence flake8-bugbear B028, which:
- Doesn't work with Python 3.7
- Isn't necessarily easier to read

Silence flake8-bugbear B028

---

conda-environment.yml
cylc/flow/async_util.py
cylc/flow/main_loop/__init__.py
cylc/flow/workflow_files.py
setup.cfg

* Aiofiles is a simple wrapper for a thread pool executor. We don't need a 3rd party library to do this for us.
* Closes #5306
**Check List**

deps: remove aiofiles

---

cylc/flow/id.py

Profiling revealed `Tokens` computed properties and `detokenise()` were being called many times and so was acting as a bit of a bottleneck (within the bottleneck of data store manager's `increment_graph_window()` - #5315).
- Remove a couple of unnecessary nested comprehensions
- Precompute certain sets
Partially addresses #5315 & #5183
<details>
<summary>Click to see `flow.cylc`</summary>
```
#!Jinja2
{% set TASKS = TASKS | default(100) %}
{% set CYCLES = CYCLES | default(1) %}
{% set SLEEP = SLEEP | default(1) %}
[meta]
description = """
Example scaling workflow with {{ (TASKS * 2) + 2 }} tasks and {{ (TASKS ** 2) + (TASKS * 2) }}
dependencies per cycle which runs for {{ CYCLES }} cycles.
"""
[task parameters]
x = 1..{{ TASKS }}
y = 1..{{ TASKS }}
[scheduling]
cycling mode = integer …
```

Optimize ID/tokens code

---

cylc/flow/data_store_mgr.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py

Partially addresses #5315
Supersedes #5316 
**Check List**

data-store graph window efficiency/refactor

---

cylc/flow/network/scan.py
cylc/flow/rundb.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/cat_log.py
cylc/flow/scripts/report_timings.py
cylc/flow/templatevars.py
cylc/flow/workflow_db_mgr.py
cylc/flow/workflow_files.py
tests/unit/test_rundb.py
tests/unit/test_scheduler_cli.py
tests/unit/test_templatevars.py
tests/unit/test_workflow_db_mgr.py

Partially addresses same issue as #5313
- **Do not create tables by default**, only if specified via kwarg
- Provide context manager functionality to automatically close DB connection
- A `WorkflowDatabaseManager` should only be created by `Scheduler`; just use `CylcWorkflowDAO` elsewhere, or certain static methods on `WorkflowDatabaseManager`
**Check List**

DB interface & safety improvements

---

conda-environment.yml
setup.cfg

A very small change to the format of the setup.cfg to make it work with the latest version of setuptools.
Non fast-tests cancelled.
See also https://github.com/pypa/setuptools/blob/v67.0.0/CHANGES.rst
(Still digging to find out what part of PEP508 or 440 was the problem)
Caused by [this PR](https://github.com/pypa/packaging/pull/634) fixing.
[Reference: Using setuptools comments to make requirements py version dependent](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html)

fix to make setup.cfg work with setuptools v67.0.0

---

cylc/flow/data_store_mgr.py

Something I spotted whilst doing #5328.
This doesn't matter at the moment as the only use of this function calls it with `satisfied=True`.
**Check List**

data store: support unsatisfied ext_trigger

---

CHANGES.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

A ticket combining a number of small fixes for Cylc lint:
Closes: 
- Closes #5362 - With style check warn user that `platform = $(some script)` is still possible, but platform logic means that it's probably not a great idea. Additionally with 728 check warns that ``host=\`some script\` ` will break at Cylc 8.
- Closes #5356 - Lint to check family names contain _no_ lowercase letters. Additionally checks for family names by searching for `FAMILY:trigger-all` and `trigger-any`.
- Closes #5355 - Lint wasn't checking for Jinja2 at all, although I'd written in the switch to turn such tests off in the absence of a shebang line.
- Closes #5226 - Lint warns that apparently commented jinja2 will be processed.
**Check List**

Cylc lint fixes

---

conda-environment.yml
cylc/flow/network/client.py
setup.cfg

* Closes https://github.com/cylc/cylc-flow/issues/5272
* Closes https://github.com/cylc/cylc-flow/issues/5311
* Unblocks https://github.com/cylc/cylc-uiserver/issues/411
tldr; We should be good to loosen off on this requirement, full rationale in the issue.
* The ZMTP protocol provides robust forward & backward compatibilit from libzmq version 3.2.2 onwards.
* Since this is the minimum version compatible with pyzmq, we can safely loosen this version coupling.
* For more information see the rationale in https://github.com/cylc/cylc-flow/issues/5311#issuecomment-1414073472

deps: loosen pyzmq dependency

---

CHANGES.md
cylc/flow/scripts/view.py

This PR closes an issue documented in the PR.
Cylc view does not have access to the Cylc Rose command line options (`-O`, `-S`, `-D`), when it ought to have.
I have added the Cylc Rose CLI options to `cylc view`. It works manually, but ought to be tested in Cylc Rose.
Question - do we want to test the Cylc Rose option adder in this repo by looking at the `--help` output?
**Check List**

fix no rose vars in cylc view

---

CHANGES.md
cylc/flow/option_parsers.py
tests/unit/test_option_parsers.py

`--workflow-name foo` was fine.
Caused by removal of unwanted sys.argv for Cylc VIP not removing items not exactly matching items in the Command line options arguments.
This is a small fix for a bug without an issue.
**Check List**

Fix a bug preventing `cylc vip --workflow-name=foo` from working.

---

cylc/flow/scripts/install.py

Sort the scan results displayed by `install` so that the runs are in order:
```
NOTE: 3 runs of "generic" are already active:
▶ generic/run1 vld601.cmpd1.metoffice.gov.uk:43072
▶ generic/run2 vld601.cmpd1.metoffice.gov.uk:43137
▶ generic/run3 vld601.cmpd1.metoffice.gov.uk:43141
```
**Check List**

Install scan sort

---

CHANGES.md
cylc/flow/__init__.py
cylc/flow/network/schema.py
cylc/flow/scripts/set_verbosity.py
tests/functional/cli/03-set-verbosity.t

Fix set-verbosity GraphQL bug

---

CHANGES.md
cylc/flow/job_runner_handlers/pbs.py
tests/unit/job_runner_handlers/test_pbs.py

This is a pull request describing the issue to be fixed.
If `global.cylc[platforms][<platform>]job name length maximum` is unset `cylc.flow.job_runner_handlers.pbs.PBSHandler.format_directives` will fail with a key error.
Instead it should fall back to the value contained in `JOB_NAME_LEN_MAX`.
**Check List**

Restore default for PBS max job name len.

---

CHANGES.md
cylc/flow/platforms.py
tests/unit/test_platforms_get_platform.py

Platform selection from a platform group was missing a `break` in the `for` loop, leading to the possibility of the wrong platform being selected.
**Check List**

Stop searching platform groups after first match.

---

tests/functional/job-submission/03-job-nn-remote-host-with-shared-fs.t

Minor issue, documented in this PR
This test requires an `--upgrade` switch because it relies on an older database.
Found on 8.1.x when checking that my setup can run tests.
**Check List**

add upgrade switch to a test using an older db

---

cylc/flow/job_runner_handlers/documentation.py
cylc/flow/job_runner_mgr.py
cylc/flow/task_job_mgr.py

> **Sibling:** https://github.com/cylc/cylc-doc/pull/594
The documentation for the job runner handler interface is poor but I found a docstring in cylc-flow with valuable information which wasn't being auto-documented.
* Move existing documentation into a class for easier auto-documentation.
* Pull in a little content from cylc-doc and attempt to pad things out a little.
* Pull in lists of fields for `job_conf` and `submit_opts` obtained from the codebase.
I'm not taking the time for a full documentation re-write right now (no time) so this is mostly just what was already there reformatted and auto documented. The important thing is to expose this documentation as there are people trying to write handlers ATM.
@hjoliver if you get a chance to skim this that would be great.
**Check List**

job runners: document the handler interface

---

cylc/flow/remote.py

Add a note about `sys.exit` behaviour in the remote interfaces.

remote: add note about sys.exit behaviour

---

CHANGES.md
cylc/flow/scheduler_cli.py
cylc/flow/scripts/install.py
tests/functional/cylc-trigger/06-already-active.t
tests/functional/optional-outputs/00-stall-on-partial.t
tests/functional/optional-outputs/01-stall-on-incomplete.t
tests/functional/optional-outputs/03-c7backcompat.t
tests/functional/optional-outputs/04-c7backcompat-blocked-task.t
tests/functional/optional-outputs/05-c7backcompat-blocked-task-2.t
tests/functional/optional-outputs/06-c7backcompat-family.t
tests/functional/optional-outputs/07-finish-fail-c7-backcompat.t
tests/functional/optional-outputs/08-finish-fail-c7-c8.t
tests/functional/restart/58-removed-task.t
tests/functional/rnd/05-main-loop.t
tests/functional/triggering/18-suicide-active.t

Closes #5227
* Rename `-n` for `--no-detach` to `-N`. This removes the conflict with `--workflow-name` allowing the option to be used in `cylc vip`.
* Add `-r` as a short option for `--run-name`.
Note, `-r` is used as a short option for the `--raw` output option, however, this doesn't conflict with install/play/clean/reload/reinstall/tui so shouldn't be a conflict risk with any future compound commands.
**Check List**

CLI: short option changes

---

cylc/flow/task_pool.py

Some low-hanging fruit spotted whilst investigating #5435
The task_pool code was repeatedly requesting the same sorted list of tasks which was starting to bite for a 7001 task workflow.
* Re-use the cached task list where appropriate.
* Switch to using the task dictionary for "in" comparisons for faster performance.
I profiled this using the example in #5435 and the [flawed] patch from https://github.com/cylc/cylc-flow/issues/5435#issuecomment-1487031362. I pressed ctrl+c once the first `b<x>` task has submitted.
This diff brings the time taken by the `can_spawn` function down from 16.93s to 0.2046s which is a saving of ~5% of the overall runtime!
~Question: 8.1.3 or 8.2.0?~
**Check List**

task_pool: avoid listing tasks where not necessary

---

cylc/flow/broadcast_mgr.py
cylc/flow/data_store_mgr.py
cylc/flow/id.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
tests/unit/test_id.py

A small efficiency improvement which reduces the number of times the tokenise/detokenise interfaces get hit by passing the parsed objects around as arguments.
Profiling results for a workflow with a single task:
| Method | Before (calls) | After (calls) |
| --- | --- | --- |
| tokenise | 21 | 6 |
| detokenise | 37 | 36 |
So that's a reduction of 15 tokenise and 1 detokenise call per task. The tokenise calls take 7.095e-06s so not a big deal, but collectively they can add up.
**Check List**

efficiency: pass tokens instances to get_broadcast

---

cylc/flow/scripts/reinstall.py
cylc/flow/scripts/validate_reinstall.py
cylc/flow/tui/app.py
cylc/flow/tui/data.py
cylc/flow/tui/overlay.py

Response to user feedback:
* Add a `--yes` option to `cylc reinstall` / `cylc vr`.
* Add `cylc vr` into `cylc tui`.
This also presents a box which tells the user that a command is running to avoid confusion with longer-running commands e.g. `play`, `clean`, `validate-reinstall`.
**Check List**

tui: add vr

---

tests/functional/cylc-clean/06-nfs.t

Follow on to https://github.com/cylc/cylc-flow/pull/5359
Add a functional test that flags NFS'like issues in `cylc clean` / `cylc cat-log -m t` interaction.

clean: test cat-log interaction on NFS filesystems

---

cylc/flow/job_runner_handlers/documentation.py

Spotted some missing entries in the job runner handler docs.
Attempted to fill in the blanks from an inspection of the code:
https://github.com/cylc/cylc-flow/blob/edc60e9774923400a0a64b23093615b96d1372dd/cylc/flow/job_runner_mgr.py#L484-L528
**Check List**

job runner handlers: docs++

---

CHANGES.md
cylc/flow/scripts/reinstall.py
tests/integration/test_reinstall.py

This caused the same variable to be added multiple times causing errors from clashing options.
Related to questions asked by @MetRonnie in https://github.com/cylc/cylc-rose/pull/219
**Check List**
- In the case of the change to `get_option_parser` we would largely be testing Python functionality.
- In the case of moving ReinstallOptions we haven't done anything except move it to the test where it's used.
- You can manually test before/after with `cylc reinstall --help`.

Stop Cylc Reinstall modifying global variables

---

cylc/flow/option_parsers.py
cylc/flow/platforms.py
cylc/flow/scripts/lint.py

This is a small fix following flake8-comprehension https://github.com/adamchainz/flake8-comprehensions/pull/427
Don't use any([i for i in iterable])
use
any(i for i in iterable).
It's more efficient because we don't have to expand the entire thing.
**Check List**

Fix flake8-comprehensions C419

---

CHANGES.md
cylc/flow/scheduler_cli.py
tests/unit/test_scheduler_cli.py

* Closes https://github.com/cylc/cylc-flow/issues/5159
**Check List**

play: preserve colour formatting when detaching

---

cylc/flow/scripts/message.py

List possible severity levels for Cylc message in `cylc message --help` doc.
**Check List**
I believe that it's small enough for 1 review.
I am intending to do a PR to cylc-doc with details of how to use messages to add info to workflow logs (as opposed to triggering task outputs.)

upgrade cylc message internal help with details of severity levels

---

CHANGES.md
cylc/flow/scripts/cat_log.py
tests/functional/cylc-cat-log/00-local.t
tests/functional/cylc-cat-log/00-local/flow.cylc
tests/functional/cylc-cat-log/06-log-rotation.t
tests/functional/cylc-clean/06-nfs.t
tests/functional/job-submission/16-timeout.t

> **Built atop:** https://github.com/cylc/cylc-flow/pull/5414
* Add support for viewing other workflow log files e.g. the `install/` and `config/` logs.
* Provide single letter abbreviations for the most recent workflow log file of each type.
* Allow specifying the job submit number in the ID.
* Fix a minor bug which allowed users to request cycle point log files.
**Check List**

cat-log: support workflow files

---

CHANGES.md
cylc/flow/config.py
cylc/flow/parsec/upgrade.py
cylc/flow/parsec/validate.py
tests/functional/validate/76-section-section-transpose.t
tests/integration/test_config.py

* Closes #4955
* If an item in the spec is a section but the user specified an option, raise an IllegalItemError if it is.
**Check List**

parsec: catch section/option conflict in validation

---

.github/workflows/build.yml
.github/workflows/test_manylinux.yml
CHANGES.md
conda-environment.yml
cylc/flow/scripts/cylc.py
setup.cfg

Fixes
```
$ cylc help license
File "~/.conda/envs/tmp/bin/cylc", line 8, in <module>
sys.exit(main())
File "~/.conda/envs/tmp/lib/python3.10/site-packages/cylc/flow/scripts/cylc.py", line 626, in main
print_license()
File "~/.conda/envs/tmp/lib/python3.10/site-packages/cylc/flow/scripts/cylc.py", line 396, in print_license
pkg_resources.get_distribution('cylc-flow').get_resource_string(
File "~/.conda/envs/tmp/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1456, in get_resource_string
return self._get(self._fn(self.module_path, resource_name))
File "~/.conda/envs/tmp/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1684, in _get
with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: …
```

Fix broken `cylc help license` command

---

cylc/flow/scripts/cat_log.py
tests/functional/cylc-cat-log/00-local.t

cat-log: don't list directories which don't exist

---

cylc/flow/task_job_mgr.py

Spotted whilst reviewing #5475, writing to the activity log takes ~0.035 seconds per task which is ~8% of the `main_loop` runtime.
This PR reduces that to ~0.025s (~28% saving), not entirely sure why this is faster, but, meh.
I profiled this with:
```
a => <b> => c
```
Although you don't need 100 tasks and you could just time the method call.
**Before:**
**After:**
**Check List**

task_job_mgr: move compute out of open call

---

cylc/flow/data_store_mgr.py

data-store graph walk restricted

---

cylc/flow/platforms.py

Use the cached global config for platform selection.
Spotted whilst profiling the "complex" workflow as `get_platform` accounted for ~19% of the main_loop runtime.
We are currently reloading the global config for platform selection which wasn't the plan. I'm not sure why we're using the cached config, the change was made a while back in a commit with "fixed caching problem" in the description:
https://github.com/cylc/cylc-flow/commit/91be2ffb1c61e616c09fa01d177be325b0d272fd#diff-f2c9506863bbbf888bfe92fe41bcd6f87f64f6a7818180cc3b7ace81848ba6b1R449
But that doesn't make much sense to me? The tests seem to agree.
**Check List**

platforms: use cached global config

---

cylc/flow/etc/syntax/cylc.vim
etc/syntax/reference-files/flow.cylc

~Will try these changes out for a while, then put up for review.~
Adds support for:
* xtriggers
* parameters
* optional outputs
* ISO8601 settings (e.g. `^+PT1H = foo => bar`)
Changes Jijna2/empy to use the (new?) `PreProc` text type thinggy (for info `:help hi` then search for `Constant`).
**Before:**
**After:**
**Check List**

syntax: small changes to vim highlighting

---

CHANGES.md
cylc/flow/data_store_mgr.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
tests/integration/test_scheduler.py
tests/integration/test_task_pool.py
tests/integration/utils/flow_tools.py

On restart we assume that all prerequisites of a spawned task are recorded in the DB. This will not be the case on restarting after adding new dependencies to that task.
Example:
```ini
[scheduling]
[[graph]]
R1 = """
a => z
b => z
"""
[runtime]
[[a]]
script = "sleep 20"
[[b, c, z]]
```
To reproduce the bug:
- install and play
- do `cylc stop --now` when `a` is still running and `z` has been spawned by `b:succeeded`
- uncomment `# c => z` to add a new prerequisite (`c`) task for `z`
- reinstall and play: scheduler will crash
The fix: if a prerequisite does not exist in the DB, assume that it is unsatisfied.
**Check List**

Apply prerequisite changes to spawned tasks, on reload & restart

---

.dockerignore
dockerfiles/cylc-dev/Dockerfile
dockerfiles/cylc-remote/Dockerfile
tests/functional/events/11-cycle-task-event-job-logs-retrieve.t
tests/functional/events/11-cycle-task-event-job-logs-retrieve/flow.cylc

> This fixes the remote CI tests, it's not strictly necessary for 8.1.3 so don't let it get in the way of release.
We were using the minconda Docker image which is now dead it seams.
Switch to the superior and less deceased Mamba image.
This also switches up the build process:
* Before we started with a Conda image, created the Cylc environment and committed it as a layer on that image.
* Now we start with a Mamba image, create the Cylc environment, then conda-pack it onto a base image of our choice.
This means we have free choice of base image and we don't have to have Mamba installed on the final image which slims it down a little (no more base env).
**Check List**

swarm: fix docker builds

---

tests/functional/platforms/11-platform-gone-on-restart.t

Closes #5500
> @wxtim - that test was added pretty recently in #5395
> 
> It looks to me like it will fail unless the restart happens so quickly that the task `foo` is still running (or more likely the shutdown is quick enough that the task hasn't returned success status yet). Otherwise the restart will auto-shutdown with nothing to do rather than complain about missing platforms. To avoid adding a flaky sleep you could probably a one quick downstream task to the graph, which would run on the restart ...
https://github.com/cylc/cylc-flow/pull/5466#issuecomment-1524930266
**Check List**

Fix flaky test

---

cylc/flow/prerequisite.py
tests/unit/test_prerequisite.py

The `Prerequisite` class contains two attributes with overlapping information, `target_point_strings` and `satisfied`.
See https://github.com/cylc/cylc-flow/pull/5466#discussion_r1178887978
Remove `target_point_strings` (only used internally) to save memory.
**Check List**

prerequsite: remove target_point_strings attribute

---

CHANGES.md
cylc/flow/task_remote_mgr.py
tests/functional/job-submission/19-platform_select.t
tests/functional/job-submission/19-platform_select/flow.cylc
tests/unit/test_task_remote_mgr.py

Fixes bug where `flow.cylc[runtime][X][remote]host = $(subshell cmd)` would always result in localhost.
Follow up to #5343
Closes #5462
**Check List**

Fix `eval_host()` localhost bug & plug testing gap

---

cylc/flow/prerequisite.py
cylc/flow/task_state.py
tests/integration/test_data_store_mgr.py
tests/integration/test_task_pool.py
tests/unit/test_prerequisite.py

Closes #5508
* Remove an unused code interface.
* Also add some parameter IDs for tests to make them CLI friendly.
**Check List**

prerequisite: remove set_not_satisfied

---

CHANGES.md
cylc/flow/scripts/cat_log.py
tests/functional/cylc-cat-log/00-local.t
tests/functional/cylc-cat-log/00-local/flow.cylc
tests/functional/cylc-cat-log/01-remote.t

* Include job-activity.log file if present even if listing is remote.
* List local files for submission-failed tasks.
**Check List**

cat-log: fix file listing errors

---

CHANGES.md
cylc/flow/flow_mgr.py
cylc/flow/rundb.py
cylc/flow/task_pool.py
tests/integration/test_trigger.py

Close #5079: if there are no active flows present (e.g. on restarting a finished workflow), triggered tasks should get (by default) the most recent previous flow numbers.
This is more of an enhancement than a bug fix, so targeting master.
**Check List**

Tweak triggering when no flows present

---

CHANGES.md
cylc/flow/network/schema.py

* Some mutations e.g. "stop" remain applicable even when a workflow is shutting down. E.G. you could tell a workflow to shut down, then upgrade that to "--now" with a subsequent mutation.
* The UI now uses metadata stored in mutations "description" field to filter out mutations which are not applicable, causing these to be disabled at present.
To test, try starting a workflow like this:
```
[scheduling]
[[graph]]
R1 = a
[runtime]
[[a]]
script = sleep 1000
```
* Then, opening this workflow in the GUI and pressing the stop button.
* The workflow should now show as stopping, but not actually stop due to the running task.
* Then open the mutations menu for the workflow and edit the stop mutation. (stop was disabled in the menu before)
* Change the mode to NOW_NOW and press submit.
* The …

schema: enable selected mutations for the stopping workflow state

---

.github/workflows/branch_sync.yml

Add workflow for automatically creating sync PRs on push to `8.*.x` branches (or by `workflow_dispatch`). This will not create a PR if one is already open.
**Check List**

GH Actions: auto sync 8.1.x -> master

---

CHANGES.md
cylc/flow/loggingutil.py
cylc/flow/scripts/clean.py
cylc/flow/scripts/get_resources.py
cylc/flow/scripts/validate.py
cylc/flow/scripts/validate_install_play.py
cylc/flow/scripts/validate_reinstall.py
tests/unit/test_loggingutil.py

Closes #5505
Cylc Validate disables the use of timestamps in logging. I've added a command to allow it to be restarted before these commands play a workflow.
**Check List**

Turn log timestamps back on before running Cylc Play in VIP & VR

---

cylc/flow/scheduler.py

* Closes #5530
* Timeouts should no longer trigger the "unexpected error" message.
**Check List**

scheduler: separate "expected" and "unexpected" errrors

---

cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

**Check List**
Currently, `inherit = None` fails the linter as None contains lowercase characters. But, [None is acceptable according to the docs](https://cylc.github.io/cylc-doc/8.1.4/html/workflow-design-guide/efficiency.html#task-families-and-visualization). This fixes the bug.

S007 now does not match inherit = None

---

cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

The linter suggests that Cylc parses Jinja2 when it is commneted, which I agree with. However if it is a Jinja2 comment wrapping Jinja2 , then it will parse the comment and ignore the inside. It should not be a warning. 
**Check List**

Fix S011 lint

---

CHANGES.md
cylc/flow/scripts/lint.py
tests/functional/cylc-lint/00.lint.t
tests/functional/cylc-lint/01.lint-toml.t

Closes https://github.com/cylc/cylc-flow/issues/5545
**Check List**
~No tests - I didn't think they were needed for this change.~
I have not updated docs as I didn't see where it would be appropriate to add anything about this.
Targetting the 8.1.x branch, but can change if required.

cylc lint non zero code from warnings

---

cylc/flow/scheduler.py
tests/functional/cli/03-set-verbosity.t
tests/functional/hold-release/00-workflow/flow.cylc
tests/functional/hold-release/05-release.t
tests/functional/pause-resume/00-workflow/flow.cylc
tests/functional/pause-resume/12-pause-then-retry/flow.cylc
tests/functional/reload/25-xtriggers.t
tests/functional/spawn-on-demand/05-stop-flow/flow.cylc
tests/functional/spawn-on-demand/06-stop-flow-2/flow.cylc
tests/integration/test_resolvers.py

```
INFO - Command succeeded: poll_tasks(['1/foo'])
```
"Succeeded" is perhaps too strong a word. What's happened is the command finished without any uncaught exceptions but it doesn't mean that it necessarily did what the user expected (e.g. in this case there were no available hosts which is logged in a separate debug message).
**Check List**

Logging: say command actioned instead of succeeded

---

cylc/flow/scheduler_cli.py

Companion to https://github.com/cylc/cylc-uiserver/pull/455
**Check List**

`cylc play`: add suggestion for `--upgrade` in non-interactive terminal

---

cylc/flow/cfgspec/globalcfg.py
tests/functional/cylc-cat-log/12-delete-kill.t
tests/functional/cylc-clean/06-nfs.t

Remove `-F` (which implied `--retry`) from tail command template.
Used by https://github.com/cylc/cylc-uiserver/pull/457 & https://github.com/cylc/cylc-ui/pull/1306
**Check List**

cat-log: exit when file is deleted

---

CHANGES.md
cylc/flow/job_file.py
tests/unit/test_job_file.py

* Long environment variables can eat into the shell's address space causing subsequent commands to fail.
* Redact the `CYLC_TASK_DEPENDENCIES` variable when there are more than 50 upstream tasks.
* If a task cycle point is ~25 chars and the name up to ~75 chars then that's 100 chars per task x 50 tasks => 50'000 chars which should be within the limit (~126'000 on my system).
* Closes https://github.com/cylc/cylc-flow/issues/5551
**Check List**

job: redact the CYLC_TASK_DEPENDENCIES variable if too long

---

cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Closes #5558
This rule should now permit:
* Parameters.
* Jinja2.
* Empy.
* `none`, `None`, `root`.
~Regex playground: https://regex101.com/r/gyRD8h/1~ outdated
Worth trying this out with some real workflows to see if there are any other surprises.
**Check List**

lint: fix spurious lowercase family style warnings

---

cylc/flow/__init__.py
cylc/flow/install_plugins/log_vc_info.py
cylc/flow/scripts/install.py
cylc/flow/workflow_files.py
tests/unit/post_install/test_log_vc_info.py

This fixes a scary traceback when installing a workflow from an untracked subdirectory of an SVN repo. In general, it presents any non-zero exit from a VCS command as a warning rather than an error.
**Check List**

log_vc_info: catch info command errors and present them as warnings

---

CHANGES.md
cylc/flow/scripts/install.py
cylc/flow/scripts/validate_install_play.py
cylc/flow/workflow_files.py
tests/integration/test_install.py

(Show "real" args used by Cylc Play in VIP)
Part fixes a bug spotted by a user and not documented as a separate ticket: Cylc install behaviour was inconsistent between `cylc install` and `cylc vip` in the example described in https://github.com/cylc/cylc-rose/issues/230 because `cylc install` did not set the `cylc7_compat_mode` until after the pre_configure plugin ran.
**Check List**

Allow pre configure plugin to access compat mode info in cylc install.

---

cylc/flow/data_store_mgr.py
cylc/flow/id.py
cylc/flow/prerequisite.py

Attempt to reduce the overheads of creating prerequisite objects in the data store.
At Cylc7 we only created prerequisite objects for tasks in the pool. At Cylc 8 we create pbPrerequsite objects for each task in the n=1 window by default, expandable out to large n numbers by request.
These prereq objects are costly to generate. The bulk of that is due to a high number of `detokenise` calls. Since there is no real function to having the tokens objects around for data store prerequsites which don't technically exist yet, we may as well go back to string formatting here.
Also make some minor optimisations on route and fix what looks like a bug in the expression for non-conditional prerequisites.
**Check List**

data_store: reduce the cost of creating prerequisite objects

---

cylc/flow/scripts/lint.py

A failure to add a line-break after an indented chunk of rst was causing the docs build to fail.
To test: Make the Cylc docs with this checked out.
**Check List**

Fix missing line break in docs

---

CHANGES.md
cylc/flow/parsec/validate.py
cylc/flow/subprocctx.py

Tolerate comas within strings and equals signs withing kwarg strings.
* Closes #5575
* Closes #5576
**Check List**

xtriggers: improve parser

---

tests/unit/conftest.py
tests/unit/test_install.py

Closes #5172
Fixes Test `tests/integration/cylc_install`, which previously installed workflows in Cylc Src.
**Check List**

Stop Unit tests symlinking on workflow installation

---

cylc/flow/config.py
tests/unit/test_config.py

Currently in `config.py` we infer a run directory, and work and share sub-directories, and export associated environment variables, even when parsing a source workflow (which may not be installed) or when parsing an installed workflow but not running the scheduler (in which case work etc. may not exist).
The original motivation for this PR was:
*There are use cases where src-dir needs to be distinguished from run-dir at config parsing time.  Example: dependency graph constructed on the fly according to the content of some workflow sub-dir.  For validation of the source workflow, the location of this content is relative to the source dir; for validation of the installed workflow (or at scheduler start-up) it must be relative to the run directory.*
#5589 now provides a better solution to …

Fix runtime environment (scheduler, validation, etc.)

---

CHANGES.md
cylc/flow/cycling/iso8601.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

* Closes https://github.com/cylc/cylc-flow/issues/5603
* Fixes an infinite loop which could occur where one or more task sequences terminate before the start point.
* This triggered a bug whereby the runahead limit was disabled on startup causing an infinite spawning bug.
**Check List**

pool: fix infinite loop with --start-cycle-point

---

conda-environment.yml
setup.cfg

Once a new version of `packaging` has been released:
- https://github.com/pypa/setuptools/issues/3802#issuecomment-1427689516
**Check List**

Remove upper pin on setuptools

---

CHANGES.md
cylc/flow/param_expand.py
tests/unit/test_param_expand.py

Closes #5118 
The form `FAM<foo,bar>` is already supported in graph strings and `[runtime][task]inherit`, while the functionally equivalent `FAM<foo><bar>` is only supported in graph strings. This PR adds full support for the latter
**Check List**

Support expanding `<param1><param2>` in inherited family names

---

CHANGES.md
cylc/flow/option_parsers.py
cylc/flow/scheduler.py
cylc/flow/scripts/check_versions.py
cylc/flow/scripts/diff.py
cylc/flow/scripts/view.py
cylc/flow/templatevars.py
tests/integration/test_template_variables_cli.py
tests/unit/test_templatevars.py

Closes #5433
Allow -z simple template variable string lists.
As part of this work I have replaced all instances of `load_template_vars` (which takes 3 keyword args) with `get_template_vars` (which takes a CLI options object and pulls the args for `load_template_vars` out). I have left the separation of the two functions because it reduces testing.
Additionally I have added error handling for this case:
`cylc vip -s "FOO"` - which previously failed with traceback. It now raises a CylcError subclass which is handled nicely.
**Check List**

Added -z option

---

CHANGES.md
cylc/flow/network/schema.py

Partially addresses: #5612
There are a few folks poking around with the GraphQL schema which is great, but the documentation is a bit lacking.
Add a quick description to the most commonly used fields.
* Mark a couple of fields as obsolete/deprecated, see #5610
* Mark a couple of fields I couldn't provide descriptions for with TODO's (#5612).
**Check List**

schema: add more documentation

---

CHANGES.md
cylc/flow/parsec/fileparse.py
tests/unit/parsec/test_fileparse.py

Allow the template processor to access workflow files - in the source dir for a source workflow, or the run dir for installed workflows.
This is the most straightforward way to cater to [this kind of use case](https://github.com/cylc/cylc-flow/pull/5570#issue-1744687086)
(I can't think of any downside...)
**Check List**

cd to workflow dir during file parsing.

---

cylc/flow/parsec/validate.py
cylc/flow/subprocctx.py
tests/integration/test_subprocctx.py

This closes a small issue not logged elsewhere:
Due to a change in the `__str__` method of the subprocess context object the results of printing to stdout/err in extrigger scripts was no longer logged.
To replicate  the problem on master try the [first Toy example of an xtrigger from the docs](https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/external-triggers.html#echo)
**Check List**

ensure output from xtrigger scripts are logged

---

CHANGES.md
conda-environment.yml
setup.cfg

relates to https://github.com/pypa/setuptools/issues/3802
`setuptools` at v67 results in failure running cylc
```
(flow) sutherlander@cortex:cylc-flow$ cylc --version
File "/home/sutherlander/.envs/flow/lib/python3.10/site-packages/pkg_resources/__init__.py", line 629, in _build_master
ws.require(__requires__)
.
.
.
pkg_resources.DistributionNotFound: The 'metomi-isodatetime==1!3.0.*' distribution was not found and is required by cylc-flow
```
**Check List**

blacklist setuptools v67

---

CHANGES.md
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

pool: prevent no-flow tasks from spawning downstreams in compat mode

---

CHANGES.md
cylc/flow/job_runner_handlers/pbs.py
cylc/flow/job_runner_mgr.py
tests/unit/job_runner_handlers/test_pbs.py

* Closes #4051
Candidate fix for #4051.
**Check List**

pbs: trim trailing text from job ids

---

cylc/flow/cfgspec/workflow.py

Document whitespace in env vars:
See https://github.com/cylc/cylc-flow/issues/5080#issuecomment-1637842468
**Check List**

doc: explain whitespace in env vars

---

changes.d/5631.fix.md
cylc/flow/clean.py
cylc/flow/command_polling.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/clean.py
cylc/flow/scripts/cycle_point.py
cylc/flow/scripts/ext_trigger.py
cylc/flow/scripts/scan.py
tests/functional/cylc-clean/01-remote.t
tests/unit/test_clean.py

Fix `cylc clean` remote re-invocation bug

---

.github/workflows/1_create_release_pr.yml
.github/workflows/test_fast.yml
CHANGES.md
CONTRIBUTING.md
changes.d/changelog-template.jinja
pyproject.toml
setup.cfg

https://towncrier.readthedocs.io/en/stable/index.html
If we go for this it means no more changelog conflicts 🎉 Instead you either
- write your changelog entries to a file at `changes.d/<PR-number>.<break|feat|fix>.md`
- or run `towncrier create <PR-number>.<break|feat|fix>.md --content "<insert content here>"`
and before the release they get collated into `CHANGES.md`.
Also it guarantees changelog entries go under the right release section despite any milestone bump-backs or cherry-picks that happen.
**Check List**

Use towncrier for changelog generation

---

changes.d/5571.feat.md
cylc/flow/parsec/empysupport.py
cylc/flow/parsec/fileparse.py
cylc/flow/parsec/jinja2support.py
cylc/flow/scripts/view.py
tests/functional/cylc-cat-log/01-remote.t
tests/unit/parsec/test_fileparse.py
tests/unit/test_config.py

What it says.  Make this sort of thing work during `flow.cylc` parsing:
```
{{ CYLC_WORKFLOW_RUN_DIR | default("not defined") }}
``` 
See explanation in https://github.com/cylc/cylc-flow/pull/5570#issue-1744687086
If agreed, I'll document this, and do the same for Empy.
Will need to document that this should not be used in place of the associated environment variables in task definitions (they get evaluated at job run time and will therefore always be defined).
[UPDATE: for the linked use case, #5589 makes this PR redundant. But this might be useful for other reasons]
**Check List**

Add CYLC_ variables to template engine globals.

---

.github/workflows/branch_sync.yml

- Try fast-forward merge of `8.*.x` branch into `master` and push if that's successful.
- Otherwise always create PR from sync branch instead of creating a PR from `8.*.x` into `master` direct

GH Actions: sync PR improvements

---

cylc/flow/cfgspec/globalcfg.py

Goes with https://github.com/cylc/cylc-doc/pull/632
Better linking into docs, straighten out similar doc labels.

event handlers: improve docs

---

cylc/flow/scheduler.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py
cylc/flow/workflow_events.py
tests/functional/job-submission/01-job-nn-localhost/db.sqlite3
tests/integration/test_examples.py
tests/integration/test_scheduler.py
tests/integration/test_workflow_files.py

Ensure that UUID is retrieved from database on workflow restart.

---

.github/workflows/branch_sync.yml

Sorry can't resist tinkering with this. This will hopefully reduce overhead as it will fast-forward the `8.*.x-sync` branch if possible otherwise leave us to merge the sync PR first

GH Actions: fast-forward sync branch if possible

---

cylc/flow/data_store_mgr.py

closes #5595 
~~This improves the issue, but there's momentary higher `succeeded` counts while pruning is immanent (which is the underlying cause of the problem).~~
#5650 may have improved this too, by updating the store more frequently (as flagged by the store). 
**Check List**

Succeeded state totals fix

---

cylc/flow/cfgspec/workflow.py

Fix incorrect clock-expire docs

---

cylc/flow/cfgspec/workflow.py

I did a grep for other possible unintentionally hidden admonitions and couldn't find any others.

Docs: fix hidden note

---

changes.d/5685.fix.md
cylc/flow/scripts/pause.py

`cylc pause` targets workflows, not tasks, but the command help is printing the task-matching documentation as well.
Small fix, not much point in tests for this.
**Check List**

Cylc pause help fix

---

cylc/flow/scheduler_cli.py

Partially addresses #5324
**Check List**

`cylc play`: print downgrade message to stderr so that it shows in GUI

---

cylc/flow/scripts/show.py

Trivial command output message change.
One review will do. Not tests or doc needed.
Close #5678

Make cylc-show "n=0" message clearer.

---

changes.d/5237.feat.md
cylc/flow/dbstatecheck.py
cylc/flow/rundb.py
cylc/flow/scripts/workflow_state.py
cylc/flow/xtriggers/workflow_state.py
tests/unit/test_workflow_db_mgr.py
tests/unit/xtriggers/test_workflow_state.py

Address #5236 
Sibling of #5238 
**Check List**

workflow-state command back compat.

---

changes.d/5694.fix.md
cylc/flow/parsec/fileparse.py
tests/unit/parsec/test_fileparse.py

Close #5688 
But note https://github.com/cylc/cylc-flow/issues/5688#issuecomment-1679921665 
Is it worth doing this?
**Check List**

file parsing: check for CWD existence

---

changes.d/5704.fix.md
cylc/flow/cfgspec/workflow.py
cylc/flow/parsec/upgrade.py
tests/functional/deprecations/01-cylc8-basic/validation.stderr
tests/unit/cfgspec/test_workflow.py
tests/unit/parsec/test_upgrade.py
tests/unit/test_config_upgrader.py

Closes a bug noted locally by a customer.
Previously the converted was `x -> 'P{x}'`, but the runahead limit should be `'P{x-1}'`.
Additional feature - allow the converter description to include the templates for old and new values.
**Check List**

Fix upgrader for max active cylc points to runahead limit.

---

changes.d/5708.fix.md
cylc/flow/cycling/__init__.py
cylc/flow/task_pool.py
tests/integration/test_task_pool.py
tests/unit/cycling/test_cycling.py

Close #5705 
When computing the runahead limit at start-up (before the task pool is loaded), recurrence start points beyond the limit have to be ignored. 
Getting this right for "max cycles" limits (e.g. `P3` in integer or datetime cycling, as opposed to `PT3H` in datetime cycling) requires counting sequence points for all sequences.
**Check List**

Fix initial runahead limit, for offset recurrence start

---

setup.cfg

[Prevent this error](https://github.com/cylc/cylc-flow/actions/runs/6099619962/job/16552197418)
MyPy appears to be objecting to a walrus operator added to coverage at 7.3.1. This is odd, because it only objects to it at python 3.10 & 3.11 where the Walrus operator is valid (Probably the python version set in `mypy.ini`). 
I'm not at all happy that this appears to be happening, but a quick investigation wasn't able to sort out the problem, and upper-pinning fixes the CI.

Upper pin coverage at 7.3.0

---

cylc/flow/cfgspec/workflow.py

Sibling to https://github.com/cylc/cylc-doc/pull/637
We don't want to show these in the TOC tree

Hide autoclass objects from `flow.cylc` reference

---

cylc/flow/cfgspec/workflow.py

https://github.com/cylc/cylc-flow/pull/5710#issuecomment-1714152645 went into master but also wanted on 8.2.x
>Sibling to https://github.com/cylc/cylc-doc/pull/637
>
>We don't want to show these in the TOC tree
>
>![image](https://github.com/cylc/cylc-flow/assets/61982285/98dfeefb-7e62-4f2a-980e-6924d981580d)

8.2.x: hide autoclass objects from `flow.cylc` reference

---

CHANGES.md
CONTRIBUTING.md
cylc/flow/cfgspec/globalcfg.py

Closes https://github.com/cylc/cylc-uiserver/issues/238
Added hub url to global config.
This is used by cylc-ui-server (see https://github.com/cylc/cylc-uiserver/pull/507) for routing users to the hub on execution of 
`cylc gui`
**Check List**

added hub url config to globalcfg

---

cylc/flow/network/client.py

Closes #5013
* The `detect_old_contact_file` check serves two purposes:
1. It removes the contact files of crashed workflows.
2. It helps the client to differentiate between a communication timeout (e.g. network error or blocked port) and a stopped workflow.
* Remote platforms don't necessarily have SSH access back to the scheduler host which can cause confusing errors.
* Due to the potentially large number of jobs, this check can cause a flurry of SSH'es which isn't great.
* The consequence of this change is that WorkflowStopped errors will be replaced by ClientTimeout errors in job stderr.
Note this applies to the `cylc message` commands built into the job script, but also to any command run within a user's job e.g. `cylc message -- <msg or custom output> `, `cylc broadcast`, etc. …

client: don't attempt to clean up old contact files in task messages

---

cylc/flow/scripts/completion_server.py
tests/unit/scripts/test_completion_server.py

* Options and arguments are now correctly listed for command aliases.
* No options or arguments were listed for aliases before.
* Arguments are now correctly listed for `vip`.
* It was listing installed workflows before, it now lists source workflows.
* Some default options are now correctly listed for `gui` and `hub`.
* No options were listed for `gui` or `hub` before.
To test:
* Install the [auto completion](https://cylc.github.io/cylc-doc/stable/html/installation.html#shell-auto-completion).
* Check out this branch and activate your Cylc environment.
* Then use the shell completion as normal.
* Check the three bullet points above are correct.
Note: To stop your completion server `ps -faux | grep cylc` then `kill <pid>`.
**Check List**

completion_server: minor fixes

---

changes.d/5755.fix.md
cylc/flow/task_outputs.py
cylc/flow/task_pool.py
tests/functional/intelligent-host-selection/02-badhosts/flow.cylc
tests/functional/spawn-on-demand/18-submitted.t
tests/functional/spawn-on-demand/18-submitted/flow.cylc
tests/functional/spawn-on-demand/18-submitted/reference.log
tests/integration/test_task_pool.py

* This fixes a bug where submit-failed tasks were incorrectly identified as complete.
* E.G. `foo:finish => bar`.
* A task is incomplete if:
* it finished executing without completing all required outputs
* or if job submission failed and the :submit output was not optional
* See: https://github.com/cylc/cylc-admin/blob/master/docs/proposal-new-output-syntax.md#output-syntax
**Check List**

opt outputs: submitted is implicitly required

---

cylc/flow/network/multi.py

The word "Done" after a CLI command is issued is less than helpful.
This changes it to something more descriptive of what's actually happening.
Before:
```
$ cylc trigger blah
Done.
```
After:
```
$ cylc trigger blah
Command submitted; the scheduler will log any problems.
```
**Check List**

Improve CLI 'Done' stdout.

---

changes.d/5753.fix.md
cylc/flow/task_events_mgr.py
tests/integration/test_task_events_mgr.py

Response to a bug not otherwise recorded:
If the sum of `execution polling intervals` < `execution time limit` the remainder should be added to the first, but only the first `execution time limit polling interval`. Currently the remainder is always added to the first items in the list of `execution time limit polling intervals`.
The last item in the list of `execution time limit polling intervals` is repeated until the final itask timeout. At the moment if we set only one item in `execution time limit polling intervals` then every polling interval is `execution time limit polling intervals[0] + remainder`.
```
execution_time_limit = 60
execution_polling_intervals = [50]
execution time limit polling intervals = [10]
list_of_polling_intervals_is = [50, 20] # polls onwards at intervals of …
```

Fix execution time limit polling intervals [cylc 8]

---

cylc/flow/network/client.py
cylc/flow/scripts/dump.py

Issue from a Discourse thread: https://cylc.discourse.group/t/cylc8-migration-issues/733/37
The `cylc dump` command requires a bit of scheduler-side processing and sometimes isn't complete before the 5 second default comms-timeout. I tried testing this with the complex workflow (simulation mode) and got responses of ~3 seconds which is flying a bit close to the limit.
This PR ups the default comms timeout for the `cylc dump` command to 15 seconds and better explains the `ClientTimeout` error.
**Check List**

Dump timeout

---

cylc/flow/job_runner_handlers/slurm.py

Clarify the formats permitted for directives to SLURM.
Record investigations:
```ini
[[[directives]]]
-H               # Fails Cylc validation
-H=              # Works
--hold           # Fails Cylc validation
--hold=          # Holds your SLURM job as you'd hope
-b now+60        # Fails Cylc validation
-b=now+60        # Sbatch fails with invalid options
-b now+60=       # Sbatch ... just no
--begin=now+60   # Works
```
**Check List**

clarify SLURM job handler docs

---

CHANGES.md
lib/cylc/review_dao.py

Fixes a bug reported by a user.
Pagination in Cylc Review works on number of cycles in database up to the limit per page, whether or not those cycles will be displayed!
```ini
[scheduling]
cycling mode = integer
initial cycle point = 0
runahead limit = P20
spawn to max active cycle points = true
[[[P1]]]
graph = foo[-P1] => foo
[runtime]
[[foo]]
script = sleep 600
```
1. Run this workflow, wait until all the tasks have spawned out to the runahead limit.
2. Open a copy of Cylc Review and click on the link to the Cycles List of this workflow.
3. Try changing the number of entries per page for i in range(21,23). 
`ready` state has become `preparing`. States `queued`, `runahead`, `retrying` and `submit-retrying` can no longer be identified from the database.
**Check List**

Fix.cycle task states query

---

changes.d/5776.fix.md
cylc/flow/task_pool.py
tests/functional/spawn-on-demand/19-submitted-compat.t

* Closes https://github.com/cylc/cylc-flow/issues/5771.
* Ensure that submit-failed tasks are marked as incomplete.
* See also https://github.com/cylc/cylc-flow/pull/5755
**Check List**

back-compat: submitted is implicitly required

---

cylc/flow/data_store_mgr.py
cylc/flow/network/resolvers.py
cylc/flow/scheduler.py

Partially addresses https://github.com/cylc/cylc-uiserver/issues/485
The `reloaded` field wasn't being set/sent, this change fixes it:
**Check List**

Fix data-store reloaded flag

---

conda-environment.yml
setup.cfg

We released isodatetime 3.1.0 which was basically a bugfix release apart from dropping support for Python 3.6. The only real change in it was fixing mistake in the `isodatetime` command CLI help text.
**Check List**

Allow isodatetime 3.1

---

cylc/flow/scripts/show.py

**Built On:** #5780 
Whilst reviewing #5780 I noticed that the xtrigger description returned by `cylc show` gives the wallclock time for the wallclock xtrigger in seconds epoch. This proposes to convert that back into an ISO8601 format.
I'v currently not tested it since I want to canvass objections &c,
**Check List**

show: display wall_clock xtrigger times in ISO8601 rather than unix epoch seconds

---

changes.d/5727.break.md
cylc/flow/etc/tutorial/cylc-forecasting-workflow/etc/python-job.settings
cylc/flow/scripts/cylc.py
tests/unit/scripts/test_cylc.py

Closes #5124 
> * Remove from `sys.path` anything in `PYTHONPATH`.
>   
>   * This prevents `PYTHONPATH` from breaking Cylc.
> * Add to `sys.path` anything in `CYLC_PYTHONPATH`.
>   
>   * This allows us to continue to install Cylc plugins via environment variable.
**Check List**

Cylc to ignore PYTHONPATH: Use CYLC_PYTHONPATH for custom Python for Cylc

---

CHANGES.md
lib/cylc/task_events_mgr.py
lib/cylc/tests/test_task_events_mgr.py
lib/parsec/fileparse.py

Fixes 2 bugs without issues reports.
1. Backport of [this fix](https://github.com/cylc/cylc-flow/pull/5753) - ticket contains a fuller explanation.
2. Prevent task events manager modifying the list of `execution time limit polling intervals` in `glbl_cfg`, which was causing the first polling interval after the execution time limit to increment every time this code was run.
**Check List**

Fix execution time limit polling intervals [Cylc 7]

---

CONTRIBUTING.md
changes.d/5709.feat.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/remote.py
tests/unit/cfgspec/test_globalcfg.py
tests/unit/test_remote.py

Allow users to specify environment variables that get forwarded from the submit host to the workflow host.
Define variables to forward in `global.cylc` like:
```
[scheduler]
[[run hosts]]
ssh forward environment variables = PROJECT, LUSTRE_DISK
```
This will add `PROJECT` and `LUSTRE_DISK` to the list of variables exported in SSH commands to launch the scheduler on remote hosts (if they have been set in the current environment).
Once they are available on the scheduler they can be used in the `global.cylc` templating, e.g:
```
[scheduler]
[[run hosts]]
ssh forward environment variables = PROJECT, LUSTRE_DISK
[install]
[[symlink dirs]]
[[[hpc]]]
run = {{ environ['LUSTRE_DISK'] }}
[platforms]
[[hpc]]
submit method = pbs
[[[directives]]]
-P = {{ environ['PROJECT'] }}
```
See #5418 
**Check …

Forward arbitrary environment variables over SSH

---

tests/unit/cycling/test_iso8601.py

We were not testing the case of `next()` and `previous()` where the truncated properties were the same as the current datetime. E.g.
```
>>> now = 2020-10-19T13:53Z
>>> next(--10-19)
2020-10-19T00:00Z
>>> previous(--10-19)
2019-10-19T00:00Z
```
This behaviour does not seem to have been rigorously defined before? Adding these test cases ensures we do not break compatibility
**Check List**

Add missing test cases for `next()`/`previous()`

---

changes.d/5791.fix.md
cylc/flow/task_proxy.py
cylc/flow/xtrigger_mgr.py
tests/integration/test_xtrigger_mgr.py
tests/unit/test_task_proxy.py

Closes #5783 
The task proxy object was caching the value of clock trigger time. Only the first xtrigger was checked!
**Check List**

Fix.all xtriggers on an itask are the same

---

.github/workflows/test_fast.yml
conda-environment.yml
cylc/flow/__init__.py
cylc/flow/cfgspec/globalcfg.py
cylc/flow/network/scan.py
cylc/flow/parsec/fileparse.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/completion_server.py
cylc/flow/scripts/cylc.py
cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py
cylc/flow/terminal.py
cylc/flow/workflow_db_mgr.py
setup.cfg
tests/functional/cli/01-help.t
tests/integration/test_install.py
tests/unit/plugins/test_pre_configure.py
tests/unit/scripts/test_completion_server.py
tests/unit/scripts/test_cylc.py

* Closes #5775
* Replace the pkg_resources library (deprecated) with newer alternatives.
* This resolves an efficiency issue due to the high import time of pkg_resources. This import time hits every single Cylc command including `cylc message`.
The pkg_resources library can take a glacial age to import. To see this for yourself and test the difference try this:
```python
from cylc.flow.scripts import cylc
from cylc.flow.scripts import message
```
```console
$ python -X importtime test.py 2> import.log
$ pip install tuna
$ tuna import.log
```
Results:
<table>
<tr>
<td>
<b>Before</b>
</td><td>
<b>After</b>
</td>
</tr>
</table>
To measure the impact of this change on end-to-end performance, I used this diff to turn off the actual work of `cylc message`:
```diff
diff --git …
```

replace pkg_resources with importlib_metadata and packaging

---

changes.d/5801.fix.md
cylc/flow/graph_parser.py
tests/unit/test_graph_parser.py

Fix a bug where using parentheses on the right hand side of a graph trigger would cause traceback.
```
R1 = a => (b & c)
```
```console
$ cylc validate
```
<details><summary>Traceback</summary>
<p>
```
File "~/.conda/envs/cylc8/bin/cylc", line 8, in <module>
sys.exit(main())
File "~/cylc-flow/cylc/flow/scripts/cylc.py", line 660, in main
execute_cmd(command, *cmd_args)
File "~/cylc-flow/cylc/flow/scripts/cylc.py", line 286, in execute_cmd
entry_point.resolve()(*args)
File "~/cylc-flow/cylc/flow/terminal.py", line 232, in wrapper
wrapped_function(*wrapped_args, **wrapped_kwargs)
File "~/cylc-flow/cylc/flow/scripts/validate.py", line 133, in main
_main(parser, options, workflow_id)
File "~/cylc-flow/cylc/flow/scripts/validate.py", line 137, in _main …
```

Handle parentheses on RHS of trigger expression

---

changes.d/5772.feat.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Make 'url' key optional in check specification.
Document pyproject.toml fields.
A couple of small fixes I found when looking at Cylc Lint for my talk on Thurs.
**Check List**

Lint: Add a check for indentation being 4N spaces.

---

cylc/flow/task_queues/independent.py
tests/unit/test_indep_task_queues.py

Fix `IndepQueueManager` test

---

changes.d/5803.feat.md
cylc/flow/scheduler_cli.py
cylc/flow/scripts/reinstall.py
cylc/flow/scripts/validate_reinstall.py
tests/functional/cylc-reinstall/00-simple.t
tests/integration/test_reinstall.py

closes https://github.com/cylc/cylc-flow/issues/4579
To make the reinstall operation work for multiple workflows we need to make the main function asynchronous. To do this we **switch out the `reinstall_cli` function which is called in def `main` for a `call_multi` function which is passed `reinstall_cli` wrapped in a `partial`**. 
We then have to go through the call stack and make sure that async and await keywords are used in the correct places - or that async versions of functions are used. So in this case the `reinstall_cli` function needed the `async` keyword added and `get_option_parser` multiworkflow=True.
That would be job done - however `cylc_reinstall` is also imported in `validate_reinstall` so we have to repeat the process of making everything conform with the asynchronous …

made reinstall work on multiple workflows

---

cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

I did a review of my older code as a training exercise, and started refactoring.
- The big win - remove duplication by merging `get_reference_text` and `get_reference_rst`.
- Turned on the Hyperlinks in the documentation. Test this by building Cylc Doc.
- Spun as much as possible out of the main function.
- Added typing to more functions.
There's plenty more refactoring I'd like to do, but I really shouldn't be prioritizing this.
**Check List**

Refactor.lint

---

changes.d/5821.fix.md
cylc/flow/install_plugins/log_vc_info.py
cylc/flow/pipe_poller.py
tests/unit/test_pipe_poller.py

* Log the commands run by log_vc_info (debug level).
* Handle the risk of large command output clogging up the buffer causing commands to hang.
**Check List**

log_vc_info: handle long command output

---

.github/workflows/test_tutorial_workflow.yml

I take it Cylc 8.2 will not support Python 3.12 due to report-timings. (8.3 will support it - #5794)
This gets the tutorial tests passing
**Check List**

GH Actions: limit tutorial workflow to Python 3.11

---

changes.d/5838.feat.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

`rose date` → `isodatetime`
Opening on 8.2.x even though this is a feature, as it's hard to see how this could be dangerous
**Check List**

`cylc lint`: add rule to catch `rose date` usage

---

changes.d/5841.fix.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Previously something like `a = $((10#$foo)) {{ bar }}` would trigger S011 in Cylc Lint, assuming that this was jinja after a comment. I've made it ignore this synatx. By ignoring this syntax there is of course a potential that `#$  a real comment {{ jinja }}` will be ignored, but I think it quite unlikely an edge case which would require making the regex more complex to work through.
This is not a perfect fix for https://github.com/cylc/cylc-flow/issues/5682 but an improvement. Perhaps a sufficient enough fix that it can be closed though.
**Check List**

lint - S011 no longer warns against 0{{a}}

---

cylc/flow/scripts/lint.py

Very small change to make Cylc Doc build correctly.

Fix.bad toml example in lint docstring

---

cylc/flow/tui/updater.py
tests/integration/tui/test_updater.py

* These tests were trying to be a bit too clever, testing the updater whilst it was running.
* This wasn't really needed for what the tests were tring to assert, there are other tests which run Tui for real (live updater and all), those tests didn't exist when these ones were written.
* This commit freezes the updater so we can run it in lock-step with the tests.
Tests tests passed on the PR (https://github.com/cylc/cylc-flow/pull/5731), but failed when the PR was merged into master, three weeks later. I'm not sure what changed between these points, but they appear to be stable now.
Try me: `while true; do if ! pytest tests/integration/tui/test_updater.py::test_filters -s; then break; fi; done`
**Check List**

tests/i: fix flaky tui/test_updater tests

---

cylc/flow/scripts/cylc.py
tests/unit/scripts/test_cylc.py

Port [this review observation](https://github.com/metomi/rose/pull/2736#discussion_r1406525959) back into Cylc.

maintain order for CYLC_PYTHONPATH

---

cylc/flow/tui/app.py

* Respond to deprecation warning:
> DeprecationWarning: 'urwid.wimp' is not expected to be imported
> directly. Please use public access from "urwid" package. Module
> 'urwid.wimp' is deprecated and will be removed in the future.
> from cylc.flow.tui.app import TuiApp
**Check List**

tui: avoid deprecated import

---

changes.d/5789.fix.md
cylc/flow/rundb.py
cylc/flow/scheduler.py
tests/integration/test_mode_on_restart.py

Closes #5781 
There is some debate on the ticket about what action Cylc should take if `if run_mode != og_run_mode` - it probably makes sense to discuss that on #5781 - but the rest of the logic can be reviewed.
**Check List**

Test.sim mode changes on restart

---

cylc/flow/parsec/fileparse.py
tests/unit/parsec/test_fileparse.py
tests/unit/plugins/test_pre_configure.py

Plugins should not be called when parsing global.cylc. This can become problematic if the plugin wants to access the global config.
**Check List**

Do not allow plugins to act on global.cylc

---

changes.d/5872.feat.md
cylc/flow/clean.py
cylc/flow/scripts/clean.py
tests/functional/cylc-clean/01-remote.t
tests/unit/scripts/test_clean.py
tests/unit/test_clean.py

Closes #5867 
- Increase default remote `--timeout` to 5 mins and allow ISO 8601 durations
- Provide a shorter and clearer error message for remote timeouts
**Check List**

`cylc clean` remote timeout improvements

---

changes.d/5885.fix.md
cylc/flow/cycling/iso8601.py
tests/unit/test_config.py

Closes https://github.com/cylc/cylc-flow/issues/5047
- When calculating the offeset relative to the base_point it now checks if there are multiple opperators in the expression.
- If there are it splits the expresion into multiple expressions and calculates the offset by adding or subtracting each expression in turn.
- If there are not it executes as it would previously
- Added a unit test to cover chained offset expressions
**Check List**

added chain offset logic

---

changes.d/5600.break.md
cylc/flow/scripts/dump.py
tests/functional/runahead/06-release-update.t
tests/integration/scripts/test_dump.py

* This restores the old `cylc dump` behaviour of displaying only the pool contents.
This also fixes a bug where many n=0 tasks were reported as being in the n=1 window.
**Check List**

dump: restrict window to n=0

---

cylc/flow/id_cli.py

Catch a niche traceback for invalid IDs like `workflow///cycle/`.
**Check List**

id: catch traceback in ID parsing

---

changes.d/5831.feat.md
cylc/flow/subprocpool.py
setup.cfg
tests/functional/xtriggers/04-respect-cylc-pythonpath.t
tests/functional/xtriggers/04-respect-cylc-pythonpath/dir/echo.py
tests/functional/xtriggers/04-respect-cylc-pythonpath/flow.cylc

This creates a clean way to add xtriggers from python packages. xtriggers no longer need to be directly in the PYTHONPATH but can instead be from a general installation location using an entry_point `cylc.xtriggers`. Similar could be done for other things perhaps, like Jinja2Globals, although I have not looked.
I do not have an Issue for this, but I think it may be or at least relate to #3456, although I do not add the built in xtriggers with this PR, perhaps they should be but I think that can be a bit of work for someone else.
**Check List**
I've not added tests as I've not looked at how it coudl be done (can it cleanly?). I'll update CHANGES and cylc doc only if/when this is agreed to.
Example of use below, but note that with this approach, you do not actually need to have a file per …

Add a new entry_point for xtriggers

---

changes.d/5890.feat.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

partially closes https://github.com/cylc/cylc-flow/issues/4917
Also applies to ROSE_VERSION & FCM_VERSION
**Check List**

lint: Warn users that `CYLC_VERSION={{CYLC_VERSION}}` is deprecated

---

.codecov.yml
.coveragerc

* Exclude the deprecated report-timings command from code coverage.
* Don't allow coverage to dip below 90%.
**Check List**

coverage: exclude report-timings and set 90% as the lower limit

---

cylc/flow/option_parsers.py
tests/functional/cli/03-set-verbosity.t

Closes https://github.com/cylc/cylc-flow/issues/5829
The `CYLC_DEBUG` environment variable was not being set when using `cylc set-verbosity DEBUG`
This pr fixes this by correcting a conditional in the `log_level_to_verbosity` utility function
**Check List**

set CYLC_DEBUG env var when set-verbosity DEBUG

---

changes.d/5909.fix.md
cylc/flow/option_parsers.py
tests/unit/test_option_parsers.py

as well as --workflow-name foo
Closes #5905 
**Check List**

Ensure that sys argv cleaner cleans up --workflow-name=foo

---

changes.d/5902.fix.md
cylc/flow/task_job_mgr.py
tests/integration/test_task_job_mgr.py

Closes #5891 
Formerly a suppress statement was supressing cases when we wanted to set itask.summary['execution time limit'] = None.
Added tests.
**Check List**

Made execution time limit unsettable by reload or broadcast.

---

CHANGES.md
bin/cylc-suite-state
lib/cylc/dbstatecheck.py
lib/cylc/rundb.py
lib/cylc/xtriggers/suite_state.py

Address #5236 
Sibling of #5237 
**Check List**

suite-state command forward compat.

---

tests/unit/test_flow_mgr.py
tests/unit/test_id_cli.py

`caplog.set_level` can conflict with other instances of caplog if the logger isn't set in the tests. This was causing the manylinux tests to fail, and would have caused the same problem if all pytests were run in the same task in the fast tests.
https://github.com/wxtim/cylc/actions/runs/7501317283 (PR's with changes to Python tests only trigger the fast-tests workflow - a neat feature, but somewhat unhelpful in this particular case)
**Check List**

Fix.ensure logger set for all caplog.set level

---

tests/integration/test_xtrigger_mgr.py

Follow on to #5908, add an integration test to check that a DB entry is created for the xtrigger and that satisfied xtriggers are not re-run when the workflow is restarted.

xtriggers: test db / restart interaction

---

tox.ini

See https://github.com/PyCQA/flake8-bugbear/issues/451
The following files fail the new flake8-bugbear B038 check:
- The two cases in `async_util` are probably legitimate exceptions to the rule, parly because they are while loops using the modification to empty an object.
- The one in `broadcast_report` is also using a while loop, but might not need to: It's not a quick fix though - it's 9 YO code and as far as I can see has no unit tests. IMO needs a suite of unit tests existing behaviour before changing. Not a quick win.
- The one is in `network/scan.py` and `option_parsers.py` are the result of the bug.
**Check List**
* Bugbear have fixed their issue.
* When we have time to devote to the other three issues.

Turn off flake8-bugbear check 038 becuase it gave false positives.

---

changes.d/5769.feat.md
cylc/flow/id.py
cylc/flow/id_cli.py
cylc/flow/scripts/completion_server.py
cylc/flow/task_events_mgr.py
cylc/flow/task_id.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
cylc/flow/workflow_db_mgr.py
tests/functional/events/09-task-event-mail.t
tests/functional/events/29-task-event-mail-1.t
tests/functional/events/30-task-event-mail-2.t
tests/functional/restart/44-reinvoke.t
tests/integration/events/test_task_events.py
tests/integration/test_task_pool.py
tests/unit/test_id.py
tests/unit/test_id_cli.py

#5566 turned out to be remarkably awkward to solve, as a result there are two other changes on this PR.
* Tokens objects are now immutable.
* Partially addresses #5183
* This means we can use them as dict keys and in sets which is greatly advantageous.
* It also opens the door to caching as needed.
* Task events now use a named tuple and the fields have been rationalised.
* Closes https://github.com/cylc/cylc-flow/issues/5566
* The separate cycle/task/job fields have been combined into tokens.
* The `key1` field has been flattened out.
* The message field is now available to event handlers.
* This means we can get access to task messages.
* There is a caveat attached to this, I haven't added a message column to the DB. This would be awkward as the table is shared with task action timers, …

events: refactor key and make the event message available to handlers

---

cylc/flow/network/resolvers.py

**Requires:** https://github.com/cylc/cylc-flow/pull/5769
In the data store we sometimes need to strip duplicate items from an iterable whilst maintaining iteration order.
If we didn't need to maintain order, we would use sets. This new method is more efficient than the old one for iteration use cases.
<details>
<summary>Simple performance test:</summary>
```python
from random import random, shuffle                                
from time import time                                             
from cylc.flow.network.resolvers import uniq, iter_uniq           
N = 1000                                                          
M = 1000                                                          
_0 = [round(random(), 5) for _ in range(N)]                       
_10 = [*_0[:int(N * 0.9)], …
```

resolvers: optimize "uniq" iteration

---

cylc/flow/scripts/tui.py
cylc/flow/tui/app.py
cylc/flow/tui/updater.py

Spotted whilst investigating a large workflow.
Client timeouts weren't getting reported so the workflow just looked like it's loading. This:
* Reports timeouts and other errors.
* Makes the `--comms-timeout` configurable.
Due to a [lazy] implementation detail, updates are blocking to each other, i.e. if one workflow takes a while to respond, no other updates will come through from other workflows in the mean time. As a result, configuring a low timeout is preferable.
**Check List**

tui: handle client timeout more elegantly and make it configurable

---

changes.d/5933.fix.md
cylc/flow/parsec/validate.py
cylc/flow/scripts/broadcast.py
tests/functional/broadcast/10-file-1/broadcast.cylc
tests/unit/parsec/test_validate.py

- Fix traceback when using `cylc broadcast --file` with a relative filepath
- Fix bug where everything after a `#` character in a broadcast string setting (e.g. the script setting) would be  stripped out - #5932
**Check List**

Fix bugs in `cylc broadcast`

---

.github/workflows/test_tutorial_workflow.yml
changes.d/5873.feat.md
cylc/flow/etc/tutorial/consolidation-tutorial/.validate
cylc/flow/etc/tutorial/cylc-forecasting-workflow/.validate
cylc/flow/etc/tutorial/retries-tutorial/.validate
cylc/flow/etc/tutorial/retries-tutorial/flow.cylc
cylc/flow/etc/tutorial/runtime-introduction/.validate
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Lint packaged workflows

---

README.md
cylc/flow/etc/examples/README.md
cylc/flow/etc/examples/converging-workflow/.validate
cylc/flow/etc/examples/converging-workflow/flow.cylc
cylc/flow/etc/examples/converging-workflow/index.rst
cylc/flow/etc/examples/datetime-cycling/.validate
cylc/flow/etc/examples/datetime-cycling/flow.cylc
cylc/flow/etc/examples/datetime-cycling/index.rst
cylc/flow/etc/examples/event-driven-cycling/.validate
cylc/flow/etc/examples/event-driven-cycling/README.rst
cylc/flow/etc/examples/event-driven-cycling/bin/trigger
cylc/flow/etc/examples/event-driven-cycling/flow.cylc
cylc/flow/etc/examples/event-driven-cycling/index.rst
cylc/flow/etc/examples/hello-world/.validate
cylc/flow/etc/examples/hello-world/flow.cylc
cylc/flow/etc/examples/hello-world/index.rst
cylc/flow/etc/examples/integer-cycling/.validate
cylc/flow/etc/examples/integer-cycling/flow.cylc
cylc/flow/etc/examples/integer-cycling/index.rst
cylc/flow/etc/examples/inter-workflow-triggers/.validate
cylc/flow/etc/examples/inter-workflow-triggers/README.rst
cylc/flow/etc/examples/inter-workflow-triggers/downstream/flow.cylc
cylc/flow/etc/examples/inter-workflow-triggers/index.rst
cylc/flow/etc/examples/inter-workflow-triggers/upstream/flow.cylc
cylc/flow/resources.py

* Partially addresses https://github.com/cylc/cylc-doc/issues/627
* Sibling PR: https://github.com/cylc/cylc-doc/pull/666
* Add some examples of Cylc workflow implementation patterns.
This is essentially a cut-down version of what we had at Cylc 7 - https://github.com/cylc/cylc-flow/tree/7.8.x/etc/examples
These examples will get auto-documented in the user-guide in cylc-doc.
One obvious omission, sub-workflows, @hjoliver, got a good flow.cylc to contribute?
**Check List**

add example workflows

---

cylc/flow/etc/examples/event-driven-cycling/README.rst

Causing cylc-doc test failures. MB.

doc: correct spelling

---

cylc/flow/task_pool.py
cylc/flow/workflow_db_mgr.py
tests/integration/conftest.py
tests/integration/test_workflow_db_mgr.py

Closes https://github.com/cylc/cylc-flow/issues/5911
n.b. I tried to find a more sophisticated method than `startswith('wall_clock(...')` to identify the correct xtriggers, but I think this will do. 
**Check List**

Don't record satisfied wall clock triggers in the DB

---

changes.d/5864.feat.md
cylc/flow/xtriggers/suite_state.py
setup.cfg
tests/functional/xtriggers/04-suite_state.t
tests/unit/xtriggers/test_workflow_state.py

closes https://github.com/cylc/cylc-flow/issues/5835
The suite_state xtrigger was renamed to workflow_state, this breaks Cylc 7-8 interoperability.
I have just added a new xtrigger called suite_state which imports from workflow_state
**Check List**

added suite state xtrigger for back-compat

---

changes.d/5956.break.md
cylc/flow/scripts/lint.py
tests/functional/cylc-lint/01.lint-toml.t
tests/unit/scripts/test_lint.py

cylc lint: deprecate `[cylc-lint]` in favour of `[tool.cylc.lint]` in `pyproject.toml` 

---

changes.d/5943.feat.md
cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/parsec/validate.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
tests/functional/cylc-play/09-invalid-cp-opt.t
tests/integration/test_stop_after_cycle_point.py
tests/unit/test_config.py

* Closes #5939
* Support offsets (measured from the ICP) for the `stop after cycle point` to mirror the behaviour of the `final cycle point`.
* Add integration test to lock-down `stop after cycle point` interactions.
**Check List**

stop after cycle point: support offsets

---

cylc/flow/task_remote_mgr.py

* This line was adding a trailing space onto the end of every symlink dir path.
* Not sure if this was symptomatic but it's definitely not right.
**Check List**

remote_init: remove trailing space from symlink paths

---

cylc/flow/cfgspec/globalcfg.py

Sibling: https://github.com/cylc/cylc-doc/pull/685
Adds a link to the workflow events section of the user guide for each workflow event.
**Check List**

doc: link workflow event configs to user guide section

---

cylc/flow/option_parsers.py

Closes https://github.com/cylc/cylc-flow/issues/5964
**Check List**

option parsers: fix "-z" option help text

---

cylc/flow/job_runner_handlers/documentation.py

Improve job runner handler docs to cover a likely gotcha.
Cylc expects the output to be lines, so no trailing newline leads to submit-fail.

job runner handers: update submit method docs

---

cylc/flow/option_parsers.py
cylc/flow/scripts/hold.py

- (re)emphasize that globs only match active tasks
- fix a typo and minor grammar issues 
- document that a held running task can still spawn downstream action
One quick review should do.

CLI: glob and hold help tweaks

---

conda-environment.yml
setup.cfg

Closes https://github.com/cylc/cylc-flow/issues/5985
**Check List**

setup: exclude urwid versions that break Tui

---

cylc/flow/async_util.py
cylc/flow/parsec/fileparse.py
cylc/flow/plugins.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/install.py
cylc/flow/scripts/reinstall.py
cylc/flow/scripts/validate.py
cylc/flow/scripts/validate_install_play.py
cylc/flow/scripts/validate_reinstall.py
tests/functional/cylc-combination-scripts/01-vr-reload.t
tests/functional/cylc-combination-scripts/02-vr-restart.t
tests/functional/cylc-combination-scripts/04-vr-fail-validate.t
tests/functional/cylc-combination-scripts/05-vr-fail-is-running.t
tests/integration/conftest.py
tests/integration/scripts/test_validate_integration.py
tests/integration/test_get_old_tvars.py
tests/integration/test_install.py
tests/integration/test_reinstall.py
tests/integration/utils/entry_points.py
tests/unit/parsec/test_fileparse.py
tests/unit/plugins/test_pre_configure.py

This is one of a triplet of PRs which closes https://github.com/cylc/cylc-rose/issues/274
* https://github.com/cylc/cylc-rose/pull/276
* https://github.com/metomi/rose/pull/2744
---
* Await any background tasks started by a plugin before continuing. See https://github.com/cylc/cylc-rose/issues/274
* Centralise the plugin loading/running/reporting logic.
* Fix the installation test for back-compat-mode.
---
* It does what it says on the tin.
* (re)Install logging works as expected.
* Errors in file installation are reported as expected.
---
This diff will make file installation take longer:
```diff
diff --git a/metomi/rose/config_processors/fileinstall.py b/metomi/rose/config_processors/fileinstall.py
index 937ed746..9797c042 100644
--- a/metomi/rose/config_processors/fileinstall.py
+++ …
```

post_configure: ensure asyncio tasks created by plugins are awaited

---

cylc/flow/tui/app.py

Address warnings as recommended on https://github.com/cylc/cylc-flow/issues/5985
* AttrWrap -> AttrMap
* __super -> super()
* _body -> body
**Check List**

tui: address urwid deprecation warnings

---

setup.cfg

MyPy 1.9 has dropped support for Python 3.7.
n.b. Cancelled all but the fast tests, I think that's enough for this.

Upper-pin MyPy to <1.9

---

tox.ini

Closes #5931
B038 has been changed to an optional "opinionated" warning B909 - [PyCQA/flake8-bugbear#456](https://github.com/PyCQA/flake8-bugbear/pull/456)
**Check List**

Remove burninated flake8 code

---

cylc/flow/rundb.py
cylc/flow/task_pool.py

Spotted mistake in type annotation from #5658

Fix type annotation & tidy

---

changes.d/6029.feat.md
cylc/flow/data_store_mgr.py
cylc/flow/network/resolvers.py
tests/integration/test_data_store_mgr.py

Preserve n-window depth on reload

---

changes.d/5738.feat.md
cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/data_store_mgr.py
cylc/flow/scheduler.py
cylc/flow/subprocctx.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
cylc/flow/unicode_rules.py
cylc/flow/xtrigger_mgr.py
cylc/flow/xtriggers/wall_clock.py
tests/functional/cylc-config/00-simple/section1.stdout
tests/functional/xtriggers/04-sequential.t
tests/integration/test_config.py
tests/integration/test_sequential_xtriggers.py
tests/unit/test_xtrigger_mgr.py

supersedes #5732 
Spawning parentless xtrigger tasks out to the run ahead limit is unnecessary in the majority of cases, and creates a lot of UI clutter.
This PR makes sequential spawning on xtrigger satisfaction for parentless tasks optional, with non-sequential the default (no change). And the default for clock triggers.
Justification:
- Naturally clock trigger tasks are sequential in time, so it makes sense to only spawn the next parentless clock-triggered task when the current clock trigger is satisfied.
- Most workflows are sequential, and so workflows/downstream-workflows usually don't need to check xtriggers out to the runahead limit (i.e. `workflow_state`).
- It makes little difference (split seconds) in "catch-up" mode, where all xtriggers will be satisfied on first check.
- It …

parentless sequential xtrigger spawning

---

changes.d/5959.fix.md
cylc/flow/scheduler.py
tests/integration/test_examples.py
tests/integration/test_workflow_events.py

The result of attempting to document workflow events here: https://github.com/cylc/cylc-doc/pull/685
Write some integration tests, discovered that a couple events weren't being fired in some situations.
[edit] It turns out that the way the scheduler terminates the subproc pool on shutdown means that, whilst this PR fixes the "event not being fired" problem, the event handler still won't actually run. This part of the issue has been bumped to #5997
**Check List**

workflow events: fix an issue where "timeout" events would not fire

---

cylc/flow/config.py
cylc/flow/rundb.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/validate.py
cylc/flow/task_events_mgr.py
cylc/flow/task_pool.py
cylc/flow/workflow_status.py
tests/integration/test_mode_on_restart.py
tox.ini

I recently set up a new development environment in Python 3.11 on NFS. For some reason it is susceptible to an issue where the DB connection is not closed on restart causing integration test teardown to fail.
I traced this unclosed DB connection to https://github.com/cylc/cylc-flow/pull/5789
**Check List**

Refactor run mode restart check to avoid unclosed DB connection

---

cylc/flow/pathutil.py
cylc/flow/subprocpool.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
cylc/flow/xtrigger_mgr.py
tests/functional/events/02-multi.t
tests/integration/test_task_job_mgr.py

Otherwise they get swallowed and there is no way to see that symlink dir creation failed due the path already existing (e.g. caused by mirror task such as fcm_make2)
**Check List**

Log subprocpool stdout/stderr at debug level

---

changes.d/fix.5924.md
cylc/flow/graph_parser.py
tests/unit/test_graph_parser.py

Closes #5844
Raise an error if a graph has a dependency offset only on the RHS of a graph pair.
**Check List**

Error if graph has a dependency offset exclusively on the RHS

---

changes.d/6036.fix.md
cylc/flow/task_events_mgr.py
tests/integration/test_task_events_mgr.py

Fixes a bug not otherwise reported:
Using the following workflow
```
[scheduler]
allow implicit tasks = true
[scheduling]
[[graph]]
R1 = foo
[runtime]
[[foo]]
[[[simulation]]]
fail cycle points = all
default run length = PT0S
fail try 1 only = False
```
Open either TUI or GUI and see that the repeated tries to run the job are not displayed correctly:
The expected result is 
(Thanks to @MetRonnie for the bug report)
**Check List**

Fix.sim mode no increment

---

changes.d/6031.fix.md
cylc/flow/id_cli.py
cylc/flow/pathutil.py
cylc/flow/scripts/workflow_state.py
cylc/flow/workflow_files.py
cylc/flow/xtriggers/workflow_state.py
tests/unit/test_id_cli.py
tests/unit/xtriggers/test_workflow_state.py

Close #6030
~Targeting 8.3.0 because it seems we're unlikely to get another 8.2 release out before then, and 8.2.x has some conflicting changes.~ (Can rebase to 8.2.x if really necessary <--- done).
TODO:
**Check List**

Fix workflow-state alternate run-dir

---

changes.d/fix.5924.md
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/consolidate-observations
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/forecast
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-observations
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/get-rainfall
cylc/flow/etc/tutorial/cylc-forecasting-workflow/bin/post-process
cylc/flow/graph_parser.py
tests/unit/test_graph_parser.py

* Address feedback that the workflow runs too quickly.
* Add 2-4s sleeps to slow it down.
* Closes #6041
**Check List**

tutorial: make the tutorial workflow run a little slower

---

.mailmap
CONTRIBUTING.md
cylc/flow/xtrigger_mgr.py

add s after string templates in documentation
closes  #6050
tests im assuming arent needed for change, since its only a 2 character change to documentation.
**Check List**

update documentation for string templates on "External Triggers" page

---

tests/integration/tui/conftest.py

Address a deprecation warning in the integration test code.

tests/integration: address urwid deprecation warning

---

changes.d/6068.break.md
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py

& Reload should not mess with Cylc Rose CLI options.
Companion to https://github.com/cylc/cylc-rose/pull/312
Cylc Play was ([according to the proposal doc](https://github.com/cylc/cylc-admin/blob/master/docs/proposal-cylc-rose-installing-rose-configs.md)) never intended to take Rose config CLI options (`-O`, `-D` and `-S`).
For example:
```
cylc install -S 'foo=1'
cylc play -S 'foo=2' --pause
```
Would lead to foo = 2 being stored on the scheduler as `self.options.rose_template_vars`: If we then do
```
cylc reinstall -S 'foo=3'
cylc reload  
cylc vr -S 'foo=3'
```
Will lead to the installed files updating, but reload cannot update the `self.options.rose_template_vars` object created by Cylc Play, so we cannot get rid of `foo=2`.
Without the scheduler storing these items, reload can …

Play should have no cylc rose options

---

changes.d/6072.feat.md
cylc/flow/etc/syntax/cylc.nanorc

Add a limited amount of Cylc syntax highlighting for Nano - I wrote this a while back, because Nano is my in terminal editor of choice, and handy for smaller toy workflows.
**Check List**

cylc.nanorc

---

changes.d/6071.fix.md
cylc/flow/subprocctx.py
cylc/flow/xtrigger_mgr.py
tests/integration/test_subprocctx.py
tests/unit/scripts/test_config.py

Include xtrigger function signatures in `cylc config`

---

cylc/flow/scheduler.py

On scheduler start, it tries to load workflow template variables from the public database. However, if the user has deleted the private database, it is not a restart, so it shouldn't try to load the public DB either.
The simple solution to this is to delete the public DB file (if it exists) immediately after checking and finding the private DB does not exist.
**Check List**

Delete public DB if private DB does not exist on scheduler start

---

cylc/flow/option_parsers.py
cylc/flow/scripts/lint.py
cylc/flow/task_state_prop.py
cylc/flow/terminal.py
tests/unit/test_task_state_prop.py
tests/unit/test_terminal.py

- `--color=never` was not always being respected
- The scheduler log would get a spurious color reset char (`ESC[0m`) at the start of the "DONE" line when not in no-detach mode
**Check List**

Fix terminal/log color issues

---

changes.d/6078.fix.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Closes #6075
Pertains to rule: S007 (family names should not contain lowercase chars)
Fixes ReDoS-like bug (possibly exponential scaling with length of input line).
**Check List**

`cylc lint` S007: fix regex catastrophic backtracking

---

cylc/flow/cfgspec/workflow.py

The "consecutive" terminology can be a little confusing.
See also https://github.com/cylc/cylc-doc/pull/660
**Check List**

doc: clarify runahead limit

---

.github/workflows/build.yml
.github/workflows/test_fast.yml
setup.cfg

Don't use Python 3.7 on MacOs on CI.
Exclude non-function releases of pytest-asyncio
**Check List**

Bump pytest-asyncio version

---

cylc/flow/cfgspec/workflow.py

Fixes a docs build error.
**Check List**

docs: reference active tasks entry in the glossary

---

cylc/flow/network/schema.py
tests/unit/network/test_schema.py

Follow-up to #5658
This is needed by the UI to disable mutations that are not valid for the workflow state. At present, "set" is not disabled for stopped workflows as it should be:
**Check List**

Add "valid for" states to schema def for `cylc set`

---

changes.d/6096.fix.md
cylc/flow/data_store_mgr.py

closes https://github.com/cylc/cylc-ui/issues/1787
Some deltas we discard (if the nodes they apply to are about to be pruned), we needed to delete any associated edges too..
**Check List**

prune suicide edges fix

---

cylc/flow/config.py
cylc/flow/workflow_files.py
tests/unit/test_config.py

Works with https://github.com/cylc/cylc-rose/pull/322 to close https://github.com/cylc/cylc-rose/issues/319.
Functional test provided by https://github.com/metomi/rose/pull/2779
**Check List**

Add an option to the workflow config to force use of compat mode

---

tests/conftest.py

Should help to resolve possible issues where one test sets a flag (but not via monkeypatch) and another accesses that value.

tests: reset global state before each test

---

changes.d/6102.fix.md
cylc/flow/option_parsers.py
cylc/flow/scripts/validate_install_play.py
cylc/flow/scripts/validate_reinstall.py
tests/unit/test_option_parsers.py

Follow-up to #6068
**Check List**

`cylc vip/vr`: do not pass rose options to `cylc play`

---

changes.d/6123.fix.md
cylc/flow/id.py
cylc/flow/id_cli.py
tests/unit/test_id.py
tests/unit/test_id_cli.py

Closes #6110 
Before:
```python-console
>>> from cylc.flow.id import tokenise
>>> dict(tokenise('//2050-01-01T00:00Z'))
{'cycle': '2050-01-01T00', 'cycle_sel': '00Z'}
```
After:
```pyth-console
>> from cylc.flow.id_cli import cli_tokenise
>>> dict(cli_tokenise('//2050-01-01T00:00Z'))
{'cycle': '2050-01-01T00:00Z'}
>>> dict(cli_tokenise('//2050-01-01T00:fail'))
{'cycle': '2050-01-01T00', 'cycle_sel': 'fail'}
```
I decided to have a go at supporting the long format rather than disallowing it, seeing as it isn't much diff. Performance-wise this should have negligible impact as the "expensive" part of it is only going to be hit once by users running a CLI command.
**Check List**

Tokens: handle ISO 8601 long format cycle points

---

changes.d/fix.6109.md
cylc/flow/exceptions.py
cylc/flow/platforms.py
cylc/flow/task_job_mgr.py
cylc/flow/task_remote_mgr.py
tests/integration/test_platforms.py

Closes: https://github.com/cylc/cylc-flow/issues/6100
Bad host reset was only happening if we ran out of hosts during job submission, not during preparation phase, and hosts being added to the list of bad hosts in this way were waiting for the main loop plugin to remove them.
**Check List**

platforms: fix unreachable hosts not reset on platform group failure

---

cylc/flow/id_cli.py
tests/unit/test_id_cli.py

ID parsing for the CLI is broken with respect to the `max_workflows` constraint - it doesn't count workflows if the ID is "task-like" (which may include workflow).
A pretty trivial fix, so tentatively targeting 8.3.0.
**Check List**

Fix ID workflow count.

---

cylc/flow/network/ssh_client.py

Bug discovered when running local tests in preparation for 8.3.0 release.
* SSH->TCP client was missing the `ssh forward environment variables` key.
* This PR gives it an empty placeholder value for now.
To replicate the bug try:
```console
$ ctb -p _remote_background_shared_ssh -v tests/functional/remote/02-install-target.t
```
Or try running any of the other SSH client tests.
**Check List**

client: fix SSH client

---

cylc/flow/dbstatecheck.py
cylc/flow/task_outputs.py
cylc/flow/xtrigger_mgr.py
cylc/flow/xtriggers/wall_clock.py
cylc/flow/xtriggers/workflow_state.py
tests/integration/test_dbstatecheck.py
tests/integration/test_sequential_xtriggers.py
tests/unit/test_db_compat.py

Built on/needs:
- #5809
**Check List**

Fix xtrigger `sequential` arg validation & improve docs

---

tests/functional/cylc-cat-log/01-remote.t
tests/functional/events/11-cycle-task-event-job-logs-retrieve.t
tests/functional/reload/24-reload-file-install.t

Fix a couple of functional tests spotted with Cylc 8.3.0 release testing.
(non-release blocker obviously, just test fixes)
These tests don't run in CI, they don't generally get run until release time.
Check the comments on each commit, make sure the fix makes sense.
**Check List**

Test fixes

---

cylc/flow/xtriggers/workflow_state.py

The cylc-doc spellcheck doesn't like these return args.

xtriggers: doc change

---

setup.cfg

Spotted during release, the colorama dependency has a strange upper pin.
This goes right back to before the setup.cfg file (8b510ab4cecc9ca20054ff463df3264a29f7d24e).
Change this to match the correct value in the conda-environment.yml file.
**Check List**

setup: fix colorama upper pin

---

cylc/flow/xtrigger_mgr.py

Small change with no associated issue
Can test by installing a custom xtrigger module with a `validate` function that raises a `RuntimeError`, for example
**Check List**

Xtrigger validation: log traceback for unexpected user validation errors

---

changes.d/6130.fix.md
cylc/flow/command_validation.py
cylc/flow/commands.py

Doing so can cause the scheduler to crash.
Branched from #6112 - drafted until that is in.
Closes #6125 
**Check List**

Prevent commands which take Tasks IDs taking Job IDs.

---

cylc/flow/scripts/cylc.py
tests/functional/cli/01-help.t

While testing on GH Actions MacOS 14, I found that `sys.executable`/`sys.prefix` gave different locations to `$ command -v cylc`. But `sys.argv[0]` is consistent (tested on Ubuntu too).
On the MacOS 14 runner:
```console
$ cylc version --long
8.3.1.dev (/Library/Frameworks/Python.framework/Versions/3.9)
...
```
```console
$ command -v cylc
/Users/runner/hostedtoolcache/Python/3.9.13/arm64/...
```
**Check List**

`cylc version --long`: ensure correct path is printed for `cylc` executable

---

changes.d/fix.6170.md
cylc/flow/scheduler_cli.py

Fixes #6166.
We don't have reinvokation tests in CI ATM, so manual testing please. The logo should appear once and only once, in the user's terminal and no where else.
@wxtim, please review and assign (2) when happy.
**Check List**

play: print the logo to the user's terminal only

---

tests/functional/lib/bash/test_header

The `comm` command can't tell the difference between ✓ & ⨯ when `$LANG` is set to a UTF-8 setting e.g. `en_US.UTF-8`
See https://stackoverflow.com/q/78678882/3217306
---
Edit: Ah, interesting!
```console
$ cat c.txt
✓
⨯
✓
⨯
$ LANG=en_US.UTF-8 sort c.txt
✓
⨯
✓
⨯
$ LANG=C sort c.txt
✓
✓
⨯
⨯
```

Tests: fix `contains_ok` UTF-8 issue

---

changes.d/fix.6178.md
cylc/flow/tui/app.py

It has been reported that Tui can hang on shutdown.
The easiest way to reproduce this is to press "q" as soon as starting Tui. Sometimes this can cause it to hang.
```
$ cylc vip <workflow>
$ cylc tui <workflow>
q
```
This PR adds a timeout on the updater shutdown to prevent any hanging operation stopping Tui from exiting.
This isn't really the "right" way to solve the problem, getting the updater to exit cleanly in all circumstances would be nicer. However, it's a reasonable fail safe and since the updater is a read-only process (i.e. the only "resources" it's managing are Cylc clients which have timeouts built in) there are no ill effects of terminating it.
**Check List**

tui: prevent hang on shutdown

---

cylc/flow/hostuserutil.py

Closes #6147
Frustratingly, the arpa address returned by `socket.getfqdn` on Mac OS is different with Python 3.9 than 3.7 (conda-forge).
For context see https://github.com/cylc/cylc-flow/pull/4296
I'm not especially keen on fiddling this exception every time it changes, but can't really think of a better way to do this safely.
**Check List**

portability: permit arpa address

---

changes.d/6176.fix.md
cylc/flow/task_events_mgr.py
tests/integration/test_task_events_mgr.py

Closes #6172 
Repro:
```
[scheduling]
[[graph]]
R1 = foo
[runtime]
[[foo]]
platform = borked
submission retry delays = 5*PT10S
```
With `global.cylc`:
```
[platforms]
[[borked]]
hosts = bogus
```
**Check List**

Ensure jobs are created if task is in waiting state

---

changes.d/6200.fix.md
cylc/flow/commands.py
cylc/flow/data_store_mgr.py
cylc/flow/scheduler.py
cylc/flow/tui/util.py
cylc/flow/wallclock.py
cylc/flow/workflow_status.py
tests/unit/test_workflow_status.py

Closes #6199. A stalled paused workflow would incorrectly have a status of running instead of paused.
**Check List**

Fix stall status bug

---

changes.d/6206.fix.md
cylc/flow/xtrigger_mgr.py
tests/integration/test_xtrigger_mgr.py

sequential clock spawning fix

---

cylc/flow/data_store_mgr.py
tests/functional/cylc-show/06-past-present-future.t

closes #6114
Using example from above produces:
The solution was to create a delta from the new task proxy (instead of trying to overwrite the existing).
existing tests should cover code (?)
**Check List**

flow-nums data-store fix

---

changes.d/6137.feat.md
cylc/flow/job_runner_handlers/loadleveler.py
cylc/flow/job_runner_handlers/lsf.py
cylc/flow/job_runner_handlers/moab.py
cylc/flow/job_runner_handlers/pbs.py
cylc/flow/job_runner_handlers/sge.py
cylc/flow/job_runner_handlers/slurm.py
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Lint.job runner specific timeout

---

changes.d/6186.fix.md
cylc/flow/scripts/set.py
cylc/flow/task_pool.py
tests/integration/test_dbstatecheck.py
tests/integration/test_task_pool.py

Damn it, found a bug in 8.3.0 for `cylc set --flow=new` on future tasks: the task_outputs table won't be updated because of "WHERE flow is n" in the DB statement.
From: https://github.com/hjoliver/ecox-interventions?tab=readme-ov-file#scenario-2-rerun-some-tasks-from-upstream-of-a-failed-task
Example:
```ini
[task parameters]
m = 1..3
[scheduling]
[[graph]]
R1 = "a => b => c<m> => d"
[runtime]
[[root]]
pre-script = sleep 5
[[a, b, d]]
[[c<m>]]
[[c<m=2>]]
script = """
if (( CYLC_TASK_SUBMIT_NUMBER == 1 )); then
false
fi
"""
```
The scenario:
- `1/c_m2` fails, stalling the workflow due to a corrupted output from `1/b`
- want to rerun `1/b` and `1/c_m2`, but not `1/c_m1, m3`, then continue to `1/d` and finish
Method: 
- run a new flow (2) from `1/b` after setting `1/c_m1, m3` to succeeded in …

`cylc set` bug fix for new flows

---

tests/integration/test_dbstatecheck.py

Spotted reviewing #6186.
Rather than sleeping for an arbitrary period (flaky), call the update method that the test requires synchronously.
Also remove the dedent (the flow writer does this automatically).

tests/i: remove sleep

---

tests/functional/shutdown/08-now1/flow.cylc

Low priority test improvement for an issue spotted whilst reviewing #6181
* Test relied on an action occurring within an arbitrary sleep period which is potentially flaky.
* Replaced the sleep with a poller to make it more reliable.
**Check List**

tests/f: make shutdown/08 more explicit

---

cylc/flow/task_pool.py
tests/integration/test_task_pool.py

runahead: handle a workflow with an empty graph

---

cylc/flow/etc/examples/extending-workflow/.validate
cylc/flow/etc/examples/extending-workflow/index.rst
cylc/flow/etc/examples/extending-workflow/simple/flow.cylc

> [!IMPORTANT]
> This is #5947 with the "complex" example (to which we do not currently have a generic solution) chopped of. The remainder of that PR will need to wait, however there is pressure for us to get the simple bit documented now.
Document the preferred approach to "extending" a workflow.
Partially addresses: https://github.com/cylc/cylc-doc/issues/525
Partially addresses: https://github.com/cylc/cylc-flow/issues/5875
**Context:**
A common pattern in some areas is to run a workflow until it stops. Then modify the final cycle point to extend the workflow and restart.
This isn't an easy working pattern to port to Cylc 8 due to the difficulty of re-populating the start tasks. We have a plan to make this easier, see https://github.com/cylc/cylc-flow/issues/5416, however, this working …

example: extending workflow

---

cylc/flow/scripts/stop.py

Small docs fix. We removed the `--mode` option a long time ago.
**Check List**

stop: remove reference to Cylc 7 --mode option

---

changes.d/6242.fix.md
cylc/flow/config.py

closes #6240
Test case:
```
(flow) sutherlander@cortex-vbox:share-bin$ ls
flow.cylc  share-src
(flow) sutherlander@cortex-vbox:share-bin$ cat share-src/bin/hello.sh 
#!/bin/bash
echo 'Hello! handler activated!'
touch ${CYLC_WORKFLOW_SHARE_DIR}/handler_activated
```
```
[meta]
title = "Test calling a handler from share/bin"
[scheduling]
cycling mode = integer
initial cycle point = 1
[[graph]]
R1 = "foo => bar"
[runtime]
[[root]]
pre-script = sleep 10
[[[events]]]
handlers = hello.sh
handler events = succeeded
[[foo]]
script = """
rm -rf ${CYLC_WORKFLOW_SHARE_DIR}/bin
cp -rf ${CYLC_WORKFLOW_RUN_DIR}/share-src/bin ${CYLC_WORKFLOW_SHARE_DIR}/
chmod 0755 ${CYLC_WORKFLOW_SHARE_DIR}/bin/*
"""
[[bar]]
script = """
if ! [[ -f ${CYLC_WORKFLOW_SHARE_DIR}/handler_activated ]]; then
false
fi
"""
``` …

add share/bin to env path

---

cylc/flow/config.py
tests/integration/validate/test_outputs.py

* Closes https://github.com/cylc/cylc-flow/issues/6056
**Check List**

messages: enforce unique task messages

---

6103.fix.md
cylc/flow/taskdef.py
tests/integration/test_data_store_mgr.py

Closes #5845
Include absolute graph edges into the data store.
At present, absolute graph parents apply only when the parent is in the same cycle as the child.
E.G. Taking this example:
```
R1 = build
P1 = build[^] => run
```
The `build => run` graph edge would only exist in the R1 cycle (the one in which the build task was scheduled to run) rather than all subsequent cycles to which it applied.
The cause of the bug was a bit of code that was purposefully filtering out absolute graph edges which point to tasks in cycles other than the one that the child task is in. The code contained this comment which suggests doing this resolved some other issue:
```
```
Taking this code out fixes #5845, but I'm worried that this code served a purpose and that by deleting it I'm solving one problem by …

data store: add absolute graph edges

---

changes.d/6241.fix.md
cylc/flow/data_store_mgr.py
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

Supersede #6232 
Close #6174 
**Check List**

flow merge for force-triggered n=0 (e.g. queued) tasks

---

changes.d/6249.fix.md
cylc/flow/cfgspec/glbl_cfg.py
cylc/flow/cfgspec/globalcfg.py
tests/integration/test_config.py

Sibling: https://github.com/cylc/cylc-rose/pull/336
* Use the new `reload` kwarg rather than calling the `.load()` method.
* Fixes https://github.com/cylc/cylc-flow/issues/6244
* The `.load()` method mutates the existing config, due to the use of logging within (and outside of) this routine and the use of `glbl_cfg` in the logging, this created a race condition.
* The new `reload` kwarg creates a new config instance, then sets this as the default.
To assert that the test captures the issue, try applying this diff to test the old reload method:
```diff
diff --git a/tests/integration/test_config.py b/tests/integration/test_config.py
index 231fb12f8..eb56ed5cb 100644
--- a/tests/integration/test_config.py
+++ b/tests/integration/test_config.py
@@ -588,7 +588,9 @@ async def …
```

glbl_cfg: reload without mutating the original

---

pyproject.toml
setup.cfg

Supersedes https://github.com/cylc/cylc-flow/pull/6216
`towncrier build` will now fail as part of CI if you create a file in `changes.d/` with an invalid fragment file name, thanks to my PR https://github.com/twisted/towncrier/pull/622 (needs the `ignore` setting added to the towncrier config).
**Check List**

Upgrade towncrier

---

changes.d/feat.6168.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/pathutil.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/00-basic.t
tests/functional/cylc-clean/01-remote.t
tests/functional/cylc-install/01-symlinks.t
tests/functional/remote/04-symlink-dirs.t
tests/unit/test_pathutil.py

Allow Symlinking for log/job

---

changes.d/6266.feat.md
cylc/flow/scripts/show.py
tests/integration/scripts/test_show.py

**Check List**
Closes https://github.com/cylc/cylc-flow/issues/6266
```
Task ID: 20240728T0000Z/b
Task ID: 20240727T0000Z/b
Task ID: 20240729T0000Z/b
Task ID: 20240730T0000Z/b
Task ID: 20240731T0000Z/b
Task ID: 20240801T0000Z/b
```
```
Task ID: 20240727T0000Z/b
Task ID: 20240728T0000Z/b
Task ID: 20240729T0000Z/b
Task ID: 20240730T0000Z/b
Task ID: 20240731T0000Z/b
Task ID: 20240801T0000Z/b
```
```
$ cylc show basic-workflow //*/d
No matching active tasks found: */d
```
No tests added as I didn't think they were really needed.

Sort cylc show task proxies

---

changes.d/6267.fix.md
cylc/flow/scheduler_cli.py
tests/unit/test_scheduler_cli.py

Fixes a bug not recorded in an issue. I think this bug has been present since the introduction of the interactive upgrade mechanism (#5074)
TL;DR - remote reinvocation would not work after interactively upgrading a workflow to a new Cylc version on the CLI.
With `run hosts` configured in `global.cylc`
```cylc
[scheduler]
[[run hosts]]
available = <server1>, ...
```
Start a workflow and stop it, then fiddle the workflow DB to make it look like it was run with an older version:
```
sqlite3 wflow/.service/db 'UPDATE workflow_params SET value="8.1.7" WHERE key="cylc_version"'
```
Now restart it with `cylc play`, and type 'y' at the interactive upgrade prompt. When it re-invokes on the run host, you should see an error
```
This workflow was previously run with 8.1.7.
This version of Cylc is …
```

`cylc play` (restart): fix bug affecting run host reinvocation after interactive upgrade

---

CONTRIBUTING.md
cylc/flow/etc/syntax/cylc.lang

The regex for jinja2 subsitution in gedit syntax highlighter is too greedy, for example if you have two variables on a single line then all the text between the two variables gets highlighted as jinja2 instead of just the variables. e.g.
> {{VAR1}} extra text {{VAR2}}
would have the "extra text" syntax highlighted as jinja2, where as with the change only the {{VAR1}} and {{VAR2}} would be syntax highlighted as jinja2.
**Check List**

Made jinja2 subsitution regex less greedy in gedit syntax highlighter

---

cylc/flow/task_pool.py
cylc/flow/task_state.py

These manually cached satisfaction states have the possibility to drift out of sync with individual `Prerequisite` satisfaction states, especially with `cylc remove` work in progress #5643 (`cylc remove` will have to unset any satisfied prerequisites that the removed task provided).
It looks like they are barely used in the first place (at least not anymore):
- `_is_satisfied` only has any savings at this call to `TaskState.prerequisites_are_not_all_satisfied()`:
https://github.com/cylc/cylc-flow/blob/80fa008e18a6feb8ecb21123bde16c048fd1b599/cylc/flow/task_pool.py#L1755-L1760
which is the case for absolute triggers e.g. `foo[2001] => bar` which are not so common?
- `_suicide_is_satisfied` only has any savings at the call above and this call: …

`TaskState`: remove cached prereq satisfaction in preparation for `cylc remove`

---

cylc/flow/timer.py
tests/functional/lib/bash/test_header
tests/unit/test_timer.py

```
WARNING - stall timer stopped
```
is a bit noisy, demoted it to `INFO`
---
Functional tests: `contains_ok`
Setting `LANG=C` at the start of
```bash
LANG=C comm <(sort $FILE1) <(sort FILE2)
```
only applies to `comm` and not the `sort`s in the process substitutions
---
**Check List**

Demote "timer stopped" warning to info & fix functional tests `contains_ok` function

---

changes.d/6264.fix.md
cylc/flow/install.py
tests/unit/test_install.py

Check run name as well as workflow name in Cylc install

---

cylc/flow/data_store_mgr.py
cylc/flow/prerequisite.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
cylc/flow/task_state.py
cylc/flow/task_trigger.py
cylc/flow/taskdef.py
cylc/flow/workflow_db_mgr.py
tests/integration/scripts/test_set.py
tests/integration/test_data_store_mgr.py
tests/integration/test_task_pool.py
tests/unit/test_prerequisite.py
tests/unit/test_task_state.py

Follow-up to #6287, split off from `cylc remove` work (#5643).
The caching of satisfaction state on a `Prerequisite` object is handled manually at the moment, which could have led to nasty bugs had I not spotted this, as `cylc remove` will unset any satisfied prerequisites that the removed task provided.
I have made the `Prerequisite.satisfied` dict private and exposed a `__setitem__ / __getitem__` API which automatically resets the cached satisfaction state.
**Check List**

Rework `Prerequisite` class to ensure caching of satisfaction state is handled automatically

---

tests/functional/lib/bash/test_header

Fix tests failing locally due to unbound `$CI` variable, while still [running](https://github.com/cylc/cylc-flow/actions/runs/10372770706/job/28716276626?pr=6300#step:16:142) or [skipping](https://github.com/cylc/cylc-flow/actions/runs/10372770706/job/28716278817?pr=6300#step:16:32) as appropriate on GH Actions

Functional tests: fix unbound env var failure

---

cylc/flow/etc/examples/extending-workflow/index.rst

* Fix incorrect heading level
* Add a note about scheduling tasks to run at the "stop after cycle point".
**Check List**

examples: extending workflow

---

cylc/flow/network/schema.py

Currently poking around the schema looking at possible ways out of the graphql deadlock. Noticed some small things:
* Consistent string quotation.
* Consistent termination punctuation.
* Correct some ReST literals (double backquotes).
* Correct one incorrectly closed markdown literal.
**Check List**

schema: minor docs changes

---

tox.ini

Stop ignoring this flake8-bugbear rule:
> B028: No explicit stacklevel argument found. The warn method from the warnings module uses a stacklevel of 1 by default. This will only show a stack trace for the line on which the warn method is called. It is therefore recommended to use a stacklevel of 2 or greater to provide more information to the user.
The code that was meant to be ignored according to the comment in `tox.ini` was:
> B907: Consider replacing f"'{foo}'" with f"{foo!r}" which is both easier to read and will escape quotes inside foo if that would appear. The check tries to filter out any format specs that are invalid together with !r. If you're using other conversion flags then e.g. f"'{foo!a}'" can be replaced with f"{ascii(foo)!r}". Not currently implemented for python<3.8 or …

Flake8: remove wrongly ignored error code

---

cylc/flow/config.py
cylc/flow/dbstatecheck.py
cylc/flow/main_loop/health_check.py
cylc/flow/network/__init__.py
cylc/flow/param_expand.py
cylc/flow/scripts/cylc.py
cylc/flow/scripts/lint.py
cylc/flow/scripts/report_timings.py
cylc/flow/workflow_db_mgr.py
cylc/flow/workflow_files.py
cylc/flow/xtrigger_mgr.py
tests/unit/scripts/test_lint.py
tox.ini

- B904 already mostly tackled by #6161 
- https://docs.python.org/3/tutorial/errors.html#exception-chaining
- Made some changes to not swallow potentially useful context of caught exceptions
- [B910 new in latest release](https://github.com/PyCQA/flake8-bugbear/issues/323)
**Check List**

flake8-bugbear: opt-in to a couple of opinionated warnings

---

.github/workflows/bash.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml

https://github.com/actions/upload-artifact/issues/602

GH Actions: include hidden files when uploading `~/cylc-run` artifact

---

changes.d/6214.fix.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint_checkers.py

fix.lint.U013 incomplete message

---

cylc/flow/param_expand.py

Whils**t** investigating a bug, I found the workflow I was investigating loaded extremely slowly (~85-87s).
Over 90% of that time was down to the `_expand_graph` routine. We may be able to implement this more efficiently, but without getting too into it, there were three obvious improvements which bring it down to ~61s (~30% saving) without changing how the method works.
**Check List**

param expand: efficiency improvements

---

changes.d/6310.fix.md
cylc/flow/scheduler_cli.py
cylc/flow/scripts/validate_install_play.py
cylc/flow/scripts/validate_reinstall.py

* Closes #6291
* Supersedes https://github.com/cylc/cylc-flow/pull/6297
* The `cylc play` command would sometimes produce traceback when detaching workflows (the default unless `--no-detach` is used).
* This traceback does not appear to have had any ill effects, but may have suppressed the normal Python session teardown logic.
* It was only reported on Mac OS, but may potentially occur on other systems.
* This PR mitigates the circumstances under which the traceback occurred by separating the asyncio event loops that are run before and after daemonization.
We don't have particularly effective testing of workflow daemonization so reviewers, please test this extensively. Please check:
* `cylc play`, `cylc vr --yes` and `cylc vip`
* With the scheduler running/stopped
* With/without the …

play: fix spurious traceback observed on some systems

---

cylc/flow/prerequisite.py
tests/flakyfunctional/cylc-show/00-simple.t

https://github.com/cylc/cylc-ui/pull/1886#discussion_r1718434619
Not sure why "c" was ever included in the prerequisite alias. It is somewhat confusing when you have single-letter task names as we do in test workflows.
**Check List**

Remove `c` char from prereq API dump

---

.mailmap
CONTRIBUTING.md
changes.d/6332.fix.md
cylc/flow/graph_parser.py

Closes #6331 . Test not needed because I literally just added a character
**Check List**

Added f to format string

---

cylc/flow/install.py
cylc/flow/loggingutil.py
cylc/flow/tui/util.py
tests/unit/test_loggingutil.py

Fixes tests that were failing on my `cylc remove` branch due to a change in order
Running these 2 tests in this order would guarantee `test_Timer` would fail.
```
pytest -n 0 \
tests/integration/scripts/test_show.py::test_workflow_meta_query \
tests/unit/test_timer.py::test_Timer
```
This is due to the way we were temporarily changing the Cylc logger level during `Scheduler.start()`
https://github.com/cylc/cylc-flow/blob/cadf1ef057145873f869092ffcab9784ad7c082e/cylc/flow/loggingutil.py#L426-L437
`Logger.getEffectiveLevel()` will return the root logger level if `Logger.level` is `NOTSET`.
In pytest the root logger level is `WARNING`, so in the tests, there were cases where the Cylc logger was being incorrectly reset to `WARNING` instead of `NOTSET`

Correctly reset log level when temporarily changing it

---

changes.d/6337.fix.md
cylc/flow/task_queues/__init__.py
cylc/flow/task_queues/independent.py
tests/integration/test_task_pool.py

Close #6329 
In the example of 6329 an upstream failure generates a bunch of partially satisfied tasks - i.e. active (`n=0`) but not queued. Triggering them manually causes them to be added to a `forced_released` list - wrongly as they were not queued in the first place.
A bit later, the `forced_released` tasks top up the list of naturally released tasks. But by then there is some overlap between the two lists, so the queue limit matters (along with some task-state related race condition which I haven't fully understood, but that doesn't matter) as to how many of these tasks end up getting submitted again.
**Check List**

Fix duplicate job submissions.

---

changes.d/6335.fix.md
cylc/flow/broadcast_mgr.py
cylc/flow/scripts/broadcast.py
tests/integration/scripts/test_broadcast.py

* Fix an issue that could cause issues when broadcasting "coerced" configurations to multiple namespaces.
* Specifying the same namesapce multiple times doesn't make sense, we should strip duplicates earlier on in the process.
* Closes https://github.com/cylc/cylc-flow/issues/6334
**Check List**

broadcast: fix issue with multiple namespaces

---

changes.d/6175.fix.md
cylc/flow/dbstatecheck.py
cylc/flow/scripts/workflow_state.py
cylc/flow/task_state.py
cylc/flow/xtriggers/workflow_state.py
tests/flakyfunctional/xtriggers/01-workflow_state/flow.cylc
tests/functional/shutdown/08-now1/flow.cylc
tests/functional/workflow-state/05-output.t
tests/functional/workflow-state/07-message2.t
tests/functional/workflow-state/11-multi.t
tests/functional/workflow-state/11-multi/flow.cylc
tests/unit/test_dbstatecheck.py
tests/unit/xtriggers/test_workflow_state.py

* Do not allow users to poll for transient statuses.
* Reject invalid task states.
* Reject polling waiting and preparing tasks (not reliably pollable).
* Closes #6157
(minor bug as upgrade advice encouraged users to adopt invalid configurations which were not subsequently rejected)
**Check List**

workflow_state: reject invalid configurations

---

changes.d/6351.fix.md
cylc/flow/task_events_mgr.py
tests/integration/run_modes/test_simulation.py

Fixes a bug discovered by @oliver-sanders in the process of reviewing skip mode work (https://github.com/cylc/cylc-flow/pull/6039#issuecomment-2321147445). The bug however, is long-standing (it goes back at least as far as Cylc 8.0.0.
In simulation mode, job starting is done by the job submission pathway as a side-effect (because in sim mode the two might as well be identical). However, the pathway is not currently spawning children of started.
Run this
```flow.cylc
[scheduling]
[[graph]]
R1 = a? & a:started => b
[runtime]
[[root]]
run mode  = skip
```
**Check List**

Fix.simulation mode started bug

---

changes.d/6353.fix.md
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

Closes https://github.com/cylc/cylc-flow/issues/6284
**Check List**

expiry: prevent expired tasks from retrying automatically

---

cylc/flow/command_validation.py
cylc/flow/commands.py
cylc/flow/scripts/trigger.py

While working on `cylc remove`, I had a bit of a look at the new command validation and think there are a couple of things that can be moved into the first validation step when running commands
**Check List**

Command validation: include more in validation step

---

cylc/flow/data_store_mgr.py
cylc/flow/task_events_mgr.py
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

Small change with no associated issue
**Check List**

Fix potential type error & a few small mistakes

---

changes.d/6364.fix.md
cylc/flow/clean.py
cylc/flow/pathutil.py
tests/unit/filetree.py
tests/unit/test_clean.py
tests/unit/test_pathutil.py

Fixes a bug possibly (?) seen before by some users at the Met Office, but not tracked by an issue.
If `share/cycle` is a symlink directory, it must also be cleaned first when only specifying `--rm share`.
```cylc
[install]
[[symlink dirs]]
[[[localhost]]]
share = $HOME/sym-other
share/cycle = $HOME/sym-cycle
```
```
$ cylc play <workflow>
$ cylc stop <workflow>
$ cylc clean <workflow> --rm share
$ cylc play <workflow>
WorkflowFilesError: Symlink dir target already exists: (~/cylc-run/<workflow>/share/cycle ->) ~/sym-cycle/cylc-run/<workflow>/share/cycle
Tip: in future, use 'cylc clean' instead of manually deleting workflow run dirs.
```

`cylc clean`: fix bug where `--rm share` would not clean `share/cycle` symlink first

---

cylc/flow/etc/examples/cycle-over-irregular-dates/.validate
cylc/flow/etc/examples/cycle-over-irregular-dates/index.rst
cylc/flow/etc/examples/cycle-over-irregular-dates/inter-dependent/flow.cylc
cylc/flow/etc/examples/cycle-over-irregular-dates/simple/flow.cylc

Closes #6336 
Requires https://github.com/cylc/cylc-doc/pull/759
Not perfect, but it saves us duping this support.
**Check List**

example: cycle on irregular intervals

---

cylc/flow/pathutil.py
pyproject.toml

I often find myself typing out some code that wouldn't pass flake8, then hitting "format selection" or "organise imports" in VSCode. I am using [isort](https://pycqa.github.io/isort/index.html) and [ruff](https://docs.astral.sh/ruff/) for this (having briefly used [black](https://black.readthedocs.io/en/stable/index.html) before ruff).
I think it would be useful to define our configs for these tools on a project level so we can agree the style and avoid unnecessary diff resulting from this going forwards.
I've chosen defaults that I think best match our current prevailing style. If we want to haggle over this, make it brief!
To illustrate, I've ruffened/blackened and isorted `pathutil.py` as a small example. 
**Check List**

Add ruff, black & isort configs

---

setup.cfg
tox.ini

https://github.com/flake8-implicit-str-concat/flake8-implicit-str-concat
Use these 2 rules (better documented by ruff!):
- https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
- Prevents:
```
z = "The quick " "brown fox."`
```
(I spotted an example of this somewhere a while ago, can't remember where though)
- https://docs.astral.sh/ruff/rules/multi-line-implicit-string-concatenation/
- Prevents:
```
z = "The quick brown fox jumps over the lazy "\
"dog."
```
**Check List**

Use `flake8-implicit-str-concat`

---

changes.d/6376.fix.md
cylc/flow/subprocpool.py

In some situations, these missing arguments could cause tasks to submit fail as the result of a host outage rather than moving onto the next host for the platform.
The bug is as old as the 255 callback - https://github.com/cylc/cylc-flow/pull/4184/files#diff-577155476a8501cbb774dad9dfc50a2ed7b846d577835e58d9bb4dfdb5d56b34R243-R244
**Check List**

subprocpool: populate missing 255 callback arguments

---

cylc/flow/task_job_mgr.py

* Spotted whilst reviewing https://github.com/cylc/cylc-flow/pull/6330
* Replace duplicated logic with a centralised implementation.
**Check List**

task job mgr: use broadcast_mgr.get_updated_rtconfig interface

---

changes.d/6316.fix.md
cylc/flow/config.py
cylc/flow/workflow_db_mgr.py
tests/flakyfunctional/database/00-simple.t
tests/functional/cylc-combination-scripts/09-vr-icp-now.t
tests/functional/cylc-combination-scripts/09-vr-icp-now/flow.cylc
tests/functional/data-store/00-prune-optional-break.t
tests/functional/flow-triggers/10-specific-flow.t
tests/functional/flow-triggers/10-specific-flow/flow.cylc
tests/functional/reload/26-stalled.t
tests/functional/triggering/08-fam-finish-any.t
tests/unit/test_config.py

Closes #6262  
Validate may alter the content of options objects passed to it: In this case by replacing `icp = now` with `icp = <actual time>` which is an invalid restart option.
Pass validate a copy of the options object to prevent changes made to the options by validate affecting subsequent steps.
Whilst in principle we probably shouldn't let the options object be mutated by the `cylc validate` this shouldn't affect us anywhere except in `cylc vr`.
**Check List**

Cylc VR: Validate should not change options

---

changes.d/6397.fix.md
cylc/flow/data_store_mgr.py

broadcast: fix dictionary changed size during iteration error

---

.github/workflows/build.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
.github/workflows/test_tutorial_workflow.yml
etc/bin/swarm
tests/flakyfunctional/cylc-poll/16-execution-time-limit.t
tests/flakyfunctional/xtriggers/00-wall_clock.t
tests/functional/lib/bash/test_header
tests/functional/reload/17-graphing-change.t

https://github.com/actions/runner-images/issues/10636 - Ubuntu 24 is rolling out as `ubuntu-latest`, dropping Python 3.7 and bringing a new version of shellcheck.
We can keep using `ubuntu-22.04` for Python 3.7
**Check List**

GH actions: Ubuntu 24

---

changes.d/6414.fix.md
cylc/flow/cycling/__init__.py
cylc/flow/cycling/integer.py
cylc/flow/cycling/iso8601.py
cylc/flow/cycling/loader.py
tests/integration/scripts/test_broadcast.py

* Closes https://github.com/cylc/cylc-flow/issues/6407
**Check List**

broadcast: reject truncated cycle points

---

cylc/flow/tui/updater.py

Tui uses a "natural" sort (similar to the UI) to make things sort more nicely, e.g:
Lex sort:
* 1
* 10
* 2
"Natural" sort:
* 1
* 2
* 10
This is already turned on for tasks, but it wasn't turned on for workflows.
**Check List**

tui: sort workflows in natural order

---

changes.d/6431.fix.md
cylc/flow/task_proxy.py
tests/integration/test_xtrigger_mgr.py

closes #6423 
```
[scheduler]
cycle point format = CCYYMMDDThh
allow implicit tasks = True
[scheduling]
initial cycle point = 20241017T22
[[xtriggers]]
clock_PT25M31S = wall_clock(offset=PT25M31S):PT20S
[[graph]]
T-00 = """
@clock_PT25M31S => a
"""
[runtime]
[[root]]
script = sleep $((1 + $RANDOM % 10))
```
**Check List**

fix CPF wall_clock offset precision constraint

---

changes.d/6433.fix.md
cylc/flow/task_pool.py
tests/integration/test_flow_assignment.py

Close #5635 
What: see title
Why: triggering (or setting) with `--flow=none` should by definition have no impact on current or future flows.
(Tasks in `n=0` have flows assigned already, and only `cylc remove` can undo that).
**Check List**

Ignore requests to trigger or set active tasks with flow=none

---

changes.d/6263.fix.md
cylc/flow/commands.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
cylc/flow/xtrigger_mgr.py
tests/integration/test_sequential_xtriggers.py
tests/integration/test_task_pool.py

Close #6259 
Close #6260
User-defined xtriggers (including wall-clock) need to be reconstructed after reload (to pick up changes), but auto-defined ones (retries) must be retained.
**Check List**

Reconstruct xtriggers at reload time.

---

.github/workflows/test_fast.yml

The Tui integration tests are flakily failing quite a lot on GH Actions, so I've made it so that they re-run any failures.
Tried re-triggering several times, couldn't get it to fail 🤷‍♂️. Perhaps splitting it off from the other integration test run was enough.
**Check List**

GH actions: re-run failed Tui tests

---

changes.d/4983.fix.md
cylc/flow/task_pool.py
tests/integration/test_compat_mode.py
tests/integration/utils/flow_tools.py

* Update the runahead limit when tasks are removed (i.e. by suicide trigger) to prevent erroneous stall.
* Also closes #4983 (by adding a test for it)
Whilst writing the test, I noticed the n-window values for the "bar" tasks look wrong to me, although that's a different issue.
**Check List**

pool: update the runahead limit after task removal

---

changes.d/6445.fix.md
cylc/flow/rundb.py
cylc/flow/task_pool.py
cylc/flow/util.py
tests/unit/test_rundb.py
tests/unit/test_task_pool.py

Split off from #6370 as I think it's already a bug.
If you `cylc trigger` a task when there are no active flows (e.g. on restarting a completed workflow), it looks in the DB for the latest flow number(s). However, if the latest was `flow=none`, this would result in the task being triggered with `flow=none` as well.
**Solution:** choose the latest flow number(s) that is not `flow=none`.
With #6370 making it so that `cylc remove` will demote tasks to `flow=none`, you could end up with the situation where all tasks in the DB are `flow=none`, so again this would still result in the task being triggered with `flow=none`.
**Solution:** fall back to `flow=1`.

Ensure `cylc trigger` does not fall back to `flow=none` by default

---

changes.d/6444.feat.md
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
tests/functional/rnd/01-signals.t
tests/integration/test_scheduler.py

* Closes #4914
* Closes #6438
* If any of these signals are received, set the workflow to stop NOW.
* If the workflow is already stopping NOW, escalate that to NOW NOW (e.g. to handle stuck subprocpool processes)
* SIGINT is no longer handled as an exception (panic shutdown).
**Check List**

gracefully handle SIGINT, SIGTERM and SIGHUP

---

changes.d/6326.fix.md
cylc/flow/task_events_mgr.py
tests/integration/test_task_pool.py

* Closes https://github.com/cylc/cylc-flow/issues/6314
* There are niche situations where the job is not stored in "TaskProxy.jobs".
* This handles the situation as gracefully as we are able to.
The solution is far from ideal, the job config info has been lost for starters, however, I think that is non-functional at this stage?
@hjoliver, any better ideas?
**Check List**

task_events_mgr: handle missing job config

---

cylc/flow/data_store_mgr.py
tests/integration/test_data_store_mgr.py

An awkward bodge to work around https://github.com/cylc/cylc-flow/issues/6307
I'm not sure we want to go ahead with this, at least not in the long term, however, it should be enough to unblock (at lest the review of) https://github.com/cylc/cylc-ui/pull/1886
**Check List**

data store: dont update outputs incrementally

---

changes.d/6404.fix.md
cylc/flow/scripts/config.py
cylc/flow/scripts/graph.py
cylc/flow/scripts/list.py
cylc/flow/scripts/validate.py
cylc/flow/scripts/validate_reinstall.py
cylc/flow/scripts/view.py

Closes #6286 
Set `options.against_source` to the rundir of the workflow, allowing re-install and validate against source to access previous CLI opts as stored in rose-suite-cylc-install.conf
Paired with https://github.com/cylc/cylc-rose/pull/345
**Check List**

Pass pre-install plugins the value of workflow rundir

---

tests/functional/cli/05-colour.t
tests/functional/lib/bash/test_header

Like the description says. Split off from #6370 
**Check List**

Functional tests: allow `grep_fail` to accept options

---

.github/workflows/shortlog.yml

This avoids the action failing on PRs due to the merge commit checked out by default having different author details to the locally pushed changes by that contributor

GH Actions shortlog: check out head ref

---

cylc/flow/etc/tutorial/consolidation-tutorial/flow.cylc
cylc/flow/etc/tutorial/cylc-forecasting-workflow/flow.cylc
cylc/flow/etc/tutorial/retries-tutorial/flow.cylc
cylc/flow/etc/tutorial/runtime-introduction/flow.cylc
cylc/flow/etc/tutorial/runtime-tutorial/flow.cylc

`UTC mode` is a legacy setting which isn't required any-more for tutorial workflows.
Companion of https://github.com/cylc/cylc-doc/pull/769
**Check List**

Remove `UTC mode` from tutorial workflows

---

cylc/flow/workflow_files.py

If you use `cylc play` to resume a paused workflow, currently its says:
```
Workflow "bug/run101" is already running, listening at "<host>:<port>".
To start a new run, stop the old one first with one or more of these:
* cylc stop bug/run101              # wait for active tasks/event handlers
* cylc stop --kill bug/run101       # kill active tasks and wait
* cylc stop --now bug/run101        # don't wait for active tasks
* cylc stop --now --now bug/run101  # don't wait
* ssh -n "<host>" kill <pid>      # final brute force!
```
Two minor annoyances with the above advice:
- you don't have to, and may not want to, stop this run before starting another
- there's a blank line in the middle for no apparent reason
```
Workflow "bug/run101" is already running, listening at …
```

Tweak 'cylc play' resume help.

---

cylc/flow/config.py
cylc/flow/cycling/__init__.py
cylc/flow/scripts/list.py
tests/functional/cylc-config/09-platforms.t
tests/functional/rnd/08-cylc-list.t
tests/integration/scripts/test_list.py
tests/integration/scripts/test_validate_integration.py
tests/integration/test_config.py
tests/integration/test_get_old_tvars.py
tests/unit/cycling/test_integer.py
tests/unit/cycling/test_iso8601.py

Had a go at filling in some coverage holes whilst ill last week and struggling to work on anything else:
* [refactor] Move "cylc list" specific functions out of the config module and into the script module.
* [test] Test the "cylc list" command.
* [fix] Fix some uncaught "cylc list" option combinations.
* [refactor] Make the unused PointBase.standardise method raise NotImplementedError (both implementations override this method).
* [test] Add test for invalid start task detection in the config module.
* [test] Address some coverage holes in the cycling modules.
* [refactor] Remove unused `is_null` interface (separate commit).
**Check List**

coverage: fill some coverage holes

---

changes.d/6440.feat.md
cylc/flow/scripts/dump.py
tests/flakyfunctional/hold-release/14-hold-kill/flow.cylc
tests/flakyfunctional/restart/21-task-elapsed.t
tests/functional/queues/qsize/flow.cylc
tests/functional/reload/03-queues/flow.cylc
tests/functional/runahead/06-release-update.t
tests/functional/spawn-on-demand/13-trigger-runahead/flow.cylc
tests/functional/spawn-on-demand/14-trigger-flow-blocker/flow.cylc
tests/integration/scripts/test_dump.py

This has been annoying me forever.
Master 🤮: 
```
$ cylc dump -t bug --flows
foo, 100, running, not-held, not-queued, not-runahead, [1]
foo, 101, waiting, not-held, not-queued, runahead, [1]
foo, 96, running, not-held, not-queued, not-runahead, [1]
foo, 97, running, not-held, not-queued, not-runahead, [1]
foo, 98, running, not-held, not-queued, not-runahead, [1]
foo, 99, running, not-held, not-queued, not-runahead, [1]
```
This branch:
```
$ cylc dump -t bug --flows
91/foo:running flows=[1]
92/foo:running flows=[1]
93/foo:running flows=[1]
94/foo:running flows=[1]
95/foo:running flows=[1]
96/foo:waiting (runahead) flows=[1]
```
**QUESTION**: is it OK to make the new format the default? 
(As I have done, with `-l/--legacy` to generate the old format)
**Check List**

Modernise 'cylc dump -t' print format.

---

changes.d/6459.feat.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Lint: Tell users that backslashes are no longer necessary after => & |

---

cylc/flow/scripts/workflow_state.py
cylc/flow/xtriggers/workflow_state.py

Follow-up to https://github.com/cylc/cylc-flow/pull/6175
**Check List**

Fix workflow state docs

---

changes.d/6459.feat.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Reverts cylc/cylc-flow#6459 - Blocks Sync PR's Because Lint reference number already taken

Revert "Lint: Tell users that backslashes are no longer necessary after => & |"

---

changes.d/6475.feat.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/network/schema.py
tests/unit/cfgspec/test_globalcfg.py

From an issue raised by @dpmatthews 
Allow comma separated lists of install targets in  `global.cylc:[install][symlink dirs][__MANY__]`
@oliver-sanders tagged for code review, @dpmatthews for concept review.
**Check List**

Expand comma separated lists in `global.cylc:[install][symlink dirs]`

---

changes.d/6459.feat.md
cylc/flow/scripts/lint.py
tests/unit/scripts/test_lint.py

Replaces https://github.com/cylc/cylc-flow/pull/6459 which blocks sync PRs
Otherwise the same diff.
Seealso @MetRonnie's Comment on https://github.com/cylc/cylc-flow/pull/6459#issuecomment-2497686715
Probably OK to be a single review since it's a copy of an already accepted PR.

`cylc lint`: S015/U017 line continuation chars

---

cylc/flow/scripts/lint.py

Cylc Docs build was broken by the single backtick in https://github.com/cylc/cylc-flow/pull/6493

Fix rst output from cylc lint

---

changes.d/6511.fix.md
cylc/flow/scripts/cat_log.py
tests/integration/scripts/test_cat_log.py

cat-log list-dir mode: fail gracefully

---

cylc/flow/network/schema.py

* A documented use case for `cylc remove` is "orphaning" stuck submissions, e.g. jobs that we can no longer poll or kill due to platform or network issues.
* It is conceivable that we might need to do this whilst a workflow is shutting down
**Check List**

remove: enable command for stopping workflows

---

cylc/flow/config.py
cylc/flow/scheduler.py
cylc/flow/task_pool.py
cylc/flow/taskdef.py
cylc/flow/workflow_db_mgr.py
tests/integration/test_optional_outputs.py
tests/integration/test_reload.py
tests/integration/test_remove.py
tests/integration/test_stop_after_cycle_point.py
tests/integration/test_task_pool.py
tests/integration/utils/flow_tools.py

Closes https://github.com/cylc/cylc-flow/issues/6502
Unreleased bug. To reproduce:
1. Start a workflow `a & a:started => b` where `a` is either a long running task or is set to fail
2. Change the graph to just `b` and reload the workflow
3. Do `cylc remove a`
4. This results in a `KeyError` which crashes the scheduler
**Check List**

Fix KeyError when using `cylc remove` after a reload changed the graph

---

changes.d/6499.feat.md
cylc/flow/commands.py
cylc/flow/network/schema.py
cylc/flow/scheduler.py
cylc/flow/scripts/pause.py
cylc/flow/scripts/trigger.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
cylc/flow/task_queues/__init__.py
cylc/flow/task_queues/independent.py
tests/functional/cylc-trigger/07-kill-trigger.t
tests/functional/cylc-trigger/07-kill-trigger/flow.cylc
tests/functional/cylc-trigger/07-kill-trigger/reference.log
tests/functional/restart/58-waiting-manual-triggered.t
tests/integration/conftest.py
tests/integration/run_modes/test_skip.py
tests/integration/scripts/test_dump.py
tests/integration/test_flow_assignment.py
tests/integration/test_force_trigger.py
tests/integration/test_optional_outputs.py
tests/integration/test_queues.py
tests/integration/test_scheduler.py
tests/integration/test_task_pool.py
tests/unit/test_scheduler.py

Close #5963
Supesede #6192 (it was getting messy)
Close #6398
------
New behaviour for triggering when the workflow is paused
**DEFAULT: run triggered tasks NOW even if the workflow is paused**
- supports the common use case *"I want to pause the workflow and just trigger individual tasks"*
- (NIWA priority raised by both ops and research users in early Cylc 8 migration meetings)
**OPTION: `--on-resume` - run triggered tasks only when the paused workflow is resumed**
- this supports [the broadcast-to-past-tasks workaround](https://github.com/cylc/cylc-flow/pull/6192#issuecomment-2486785465) until broadcast is fixed (prob. 8.5.0)
- the option can be removed in the future, once broadcast is fixed, if there are no other use cases
-----
Implementation:
- separate start of job submission from …

Trigger now if workflow paused

---

changes.d/6526.fix.md
cylc/flow/graph_parser.py
tests/flakyfunctional/cylc-show/04-multi.t
tests/functional/graphing/06-family-or.t
tests/integration/reftests/test_pre_initial.py
tests/unit/test_graph_parser.py

Fix output consistency check when there are offsets.

---

cylc/flow/scripts/trigger.py

Currently, in `cylc trigger --help`:
```
...
Attempts to trigger active tasks will be ignored.
...
Active tasks (in the n=0 window) already belong to a flow.
* by default, if triggered, they run in the same flow
*...
...
```
This seems inconsistent at first glance, so I've been a bit more explicit
As far as I'm aware, the terminology we've settled on is:
- "active tasks" are literally active (submitted, running)
- (users will definitely assume this, so let's not mess with that terminology)
- the "active window of the workflow" (n=0) contains both active and waiting tasks
- (this is not illogical or inconsistent, but we need to be careful not to call this "the active tasks")
One review will do.
**Check List**

Clarify trigger command help.

---

.github/workflows/test_fast.yml
cylc/flow/scripts/dump.py
cylc/flow/scripts/show.py

For some reason, Flake8 was not detecting some problems on python 3.9.
**Check List**

Fix flake8 E231

---

.github/workflows/test_conda-build.yml

>[!NOTE]
>Min Python version for conda is 3.8, not 3.7, due to lack of protobuf build for 3.7. See https://github.com/conda-forge/cylc-flow-feedstock/pull/93
Unfortunately we didn't spot this in https://github.com/cylc/cylc-flow/pull/5828 because we were not testing on Python 3.7
**Check List**

GH Actions: test conda on min python version

---

cylc/flow/job_runner_mgr.py
tests/integration/test_job_runner_mgr.py

Close #6529 
```diff
diff --git a/cylc/flow/job_runner_mgr.py b/cylc/flow/job_runner_mgr.py
index b8ddaaa05..de7817170 100644
--- a/cylc/flow/job_runner_mgr.py
+++ b/cylc/flow/job_runner_mgr.py
@@ -568,8 +568,8 @@ class JobRunnerManager():
self._create_nn(job_file_path)
for name in JOB_LOG_ERR, JOB_LOG_OUT:
-            with suppress(OSError):
-                os.unlink(os.path.join(job_file_path, name))
+            with suppress(FileNotFoundError):
+                os.unlink(os.path.join(os.path.dirname(job_file_path), name))
```
Suppressing OSError here hid a bug:
```
NotADirectoryError: [Errno 20] Not a directory: '/home/oliverh/cylc-run/bug/run32/log/job/1/a/01/job/job.err'
```
This fixes the path error and just suppresses FileNotFoundError.
**Check List**
- (there are no reports of …

Fix unlinking old job out/err files.

---

.github/workflows/2_auto_publish_release.yml
.github/workflows/branch_sync.yml
.github/workflows/test_conda-build.yml

This will avoid the need for dependabot PRs

GH Actions: automatically use latest `pypa/gh-action-pypi-publish`

---

cylc/flow/option_parsers.py
cylc/flow/scripts/tui.py

cli: correct --comms-timeout docs

---

cylc/flow/commands.py
cylc/flow/run_modes/__init__.py
cylc/flow/run_modes/dummy.py
cylc/flow/run_modes/simulation.py
cylc/flow/run_modes/skip.py
cylc/flow/scheduler.py
cylc/flow/task_job_mgr.py
tests/integration/conftest.py
tests/integration/run_modes/test_mode_overrides.py
tests/integration/run_modes/test_nonlive.py
tests/integration/run_modes/test_simulation.py
tests/integration/run_modes/test_skip.py
tests/integration/test_job_runner_mgr.py
tests/integration/test_platforms.py
tests/integration/test_task_events_mgr.py
tests/integration/test_task_job_mgr.py

Split off from https://github.com/cylc/cylc-flow/pull/6535
**Check List**

Tidy `TaskJobManager`: remove unecessary `workflow` arg from many methods

---

changes.d/6551.fix.md
cylc/flow/scripts/lint.py

Closes #6550 
`-W` should only be highlighted by Cylc lint when being used in a way which indicates use of LSF.
**Check List**

Lint S014: Only warn about `-W` when used for LSF

---

conda-environment.yml
cylc/flow/network/ssh_client.py
setup.cfg
tests/integration/test_publisher.py
tests/integration/test_replier.py
tests/integration/test_server.py
tests/integration/test_workflow_events.py
tests/integration/tui/test_updater.py
tests/integration/utils/flow_tools.py

https://pypi.org/project/async-timeout/
>### DEPRECATED
>
>This library has effectively been upstreamed into Python 3.11+.
>
>Therefore this library is considered deprecated and no longer actively supported.
>
>Version 5.0+ provides dual-mode when executed on Python 3.11+: `asyncio_timeout.Timeout` is fully compatible with `asyncio.Timeout` and old versions of the library.
>
>Anyway, using upstream is highly recommended. `asyncio_timeout` exists only for the sake of backward compatibility, easy supporting both old and new Python by the same code, and easy misgration.
>
>If rescheduling API is not important and only `async with timeout(...): ...` functionality is required, a user could apply conditional import
**Check List**

Deprecate async-timeout dependency

---

.github/workflows/bash.yml
.github/workflows/build.yml
.github/workflows/test_conda-build.yml
.github/workflows/test_tutorial_workflow.yml

If one run in the matrix fails let the others keep running in case it's a one-off or python-version-specific failure

GH Actions: don't fail fast

---

lib/cylc/review.py
lib/cylc/url.py

Hopefully the final set of Cylc Review changes.
Closes https://github.com/cylc/cylc-flow/issues/6171
Addresses https://github.com/cylc/cylc-flow/issues/3441
**Check List**

review: small fixes

---

CHANGES.md
lib/cylc/batch_sys_handlers/pbs.py

* Addresses #6531 on the 7.8.x branch.
* Update the PBS job runner to reflect a change in error message.
* The new pattern will also match the old format.
**Check List**

pbs: update connection failed error message

---

changes.d/6480.fix.md
cylc/flow/scripts/cat_log.py
tests/functional/cylc-cat-log/13-remote-out-err-tailer.t
tests/functional/cylc-cat-log/13-remote-out-err-tailer/flow.cylc

Closes https://github.com/cylc/cylc-flow/issues/5802
List log files that are not present on disk but which are available via a tailer.
**Check List**

cat-log: list out/err files when available via tailer

---

cylc/flow/option_parsers.py
cylc/flow/scripts/cylc.py

To avoid any ambiguity, change globs match *"active tasks" to "tasks in the n=0 active window"*.
And mention `cylc show` as an exception - globs match in the n-window there.
(This is easier than separately providing different glob help for `cylc show` and for the rest; good enough for now as this will change again in the near-ish future).
https://cylc.discourse.group/t/cylc-trigger-isnt-triggering-anything/1117/4
(I also made several lines in the ID help more concise - it's good to incrementally improve existing docs when we get a chance. If you can say it just as clearly in fewer words, that's a good thing, but it's damn near impossible to get optimal clarity+conciseness first try)
**Check List**

Clarify task ID glob help

---

changes.d/6506.fix.md
cylc/flow/network/scan.py
cylc/flow/workflow_files.py

Closes https://github.com/cylc/cylc-flow/issues/6506 (hopefully!)
NFS filesystems have a caching mechanism that can take a while to clear. This may cause workflows to appear stopped on the CLI, in the Tui & GUI when they are in fact running.
Refresh NFS cache before:
* Scanning workflows:
* Fixes: Delay between startup and workflows appearing in `cylc scan`, `cylc tui` and `cylc gui` (on other servers).
* Cost: We've traded a file access for a directory listing (`.service` dir only contains a few files, no biggie).
* Loading the contact file:
* Fixes: Delay between workflow startup and the CLI being able to operate on the workflow on other servers (the second three cases in the test script).
* Cost: An additional file access (always) and additional directory listings (only when needed).
* …

work around NFS caching issues

---

changes.d/6616.fix.md
cylc/flow/etc/cylc

Wrapper script: fix `PATH` override preventing selection of Cylc version in GUI under Cylc Hub

---

cylc/flow/etc/examples/expiry/.validate
cylc/flow/etc/examples/expiry/index.rst
cylc/flow/etc/examples/expiry/one/flow.cylc
cylc/flow/etc/examples/expiry/three/flow.cylc
cylc/flow/etc/examples/expiry/two/flow.cylc

Companion: https://github.com/cylc/cylc-doc/pull/796
Document workflow design patterns using automated task expiry.
I put together a couple of examples for user support today and realised the expiry docs were a bit lacking.
These will now be documented workflow design patterns with functional tests.
**Check List**

examples: document expiry workflow design patterns

---

changes.d/6625.fix.md
cylc/flow/task_trigger.py
cylc/flow/taskdef.py
pytest.ini
tests/integration/test_graphql.py
tests/integration/test_taskdef.py
tests/unit/test_task_trigger.py

Closes https://github.com/cylc/cylc-flow/issues/6619#issuecomment-2668932069
**Check List**

Fix duplicate task triggers

---

tests/integration/test_workflow_db_mgr.py
tests/unit/test_db_compat.py
tests/unit/test_rundb.py
tests/unit/test_templatevars.py

* Closes https://github.com/cylc/cylc-flow/issues/6630
* Didn't find any functional breakages with newer versions of sqlite3 (tested with 3.49.1).
* Fixed failing tests by moving away from templating variables into SQL statements.
Note: We can't presently test this compatibility in our CI setup as we are dependent on the GH "setup-python" action. We need to look at switching over to Mamba to provision Python at some point so we can test with bleeding edge Python / Conda stack.
No functional issues detected, so no need to push this into 8.4.x
There are functional issues in metomi-rose however :(
**Check List**

tests: remove string templating in SQL statements

---

cylc/flow/network/schema.py

Closes https://github.com/cylc/cylc-flow/issues/6392
**Check List**

doc: improve NamespaceIDGlob description

---

changes.d/6645.fix.md
cylc/flow/scripts/stop.py

**Check List**
I did not update any tests. The pathway leads to failure no matter what, this just fixes the exception type and message. No documentation updates are required.

fix typo in stop.py - options.max_poll -> options.max_polls

---

changes.d/6656.fix.md
cylc/flow/data_store_mgr.py
tests/integration/test_data_store_mgr.py

Closes https://github.com/cylc/cylc-ui/issues/1999
https://github.com/cylc/cylc-ui/issues/1999#issuecomment-2701024180
> #### Steps to reproduce:
> 
> ```cylc
> [scheduler]
>     allow implicit tasks = True
> [scheduling]
>     cycling mode = integer
>     [[graph]]
>         P1 = foo[-P1] => foo => bar
> [runtime]
>     [[root]]
>         [[[simulation]]]
>             default run length = PT0S
> ```
> 
> 1. Start the workflow in simulation mode
> 2. Wait until several cycles have run, then stop the workflow
> 3. Navigate away and then back to the workflow
> 
> ![Image](https://github.com/user-attachments/assets/2000f58f-42a9-4147-ab34-2696ac355a82)
> 
> This is caused by an **accumulation of jobs** for the task `bar`:
> 
> ![Image](https://github.com/user-attachments/assets/15533380-00ac …

Fix data store job accumulation bug

---

.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
tests/flakyfunctional/database/00-simple.t
tests/flakyfunctional/hold-release/15-hold-after.t
tests/flakyfunctional/job-submission/19-chatty.t
tests/flakyfunctional/restart/46-stop-clock-time.t
tests/functional/cylc-cat-log/05-remote-tail.t
tests/functional/cylc-poll/11-event-time.t
tests/functional/cylc-set/00-set-succeeded.t
tests/functional/cylc-set/03-set-failed.t
tests/functional/cylc-set/04-switch.t
tests/functional/cylc-set/05-expire.t
tests/functional/database/06-task-message.t
tests/functional/events/20-workflow-event-handlers.t
tests/functional/job-file-trap/00-sigusr1.t
tests/functional/job-submission/11-garbage-platform-command.t
tests/functional/pre-initial/12-warm-restart.t
tests/functional/reload/10-runahead.t
tests/functional/remote/00-basic.t
tests/functional/restart/08-stop-after-cycle-point.t
tests/functional/restart/13-bad-job-host.t
tests/functional/restart/20-event-retry.t
tests/functional/restart/26-remote-kill.t
tests/functional/restart/30-outputs.t
tests/functional/restart/33-simulation.t
tests/functional/restart/45-stop-task.t
tests/functional/restart/51-final-point-reload.t
tests/functional/restart/52-cycle-point-time-zone.t
tests/functional/runahead/04-no-final-cycle.t

* Provision Python , Bash and other deps from conda-forge.
* Divorce from the OS environment and give us more flexibility in the software versions we utilise.
* Reduce usage of `apt get` (to `at`) and remove usage `brew install` completely.
* Fix SQL statements in the functional tests to comply with changes in sqlite3 3.46.0+ (closes https://github.com/cylc/cylc-flow/issues/6630)
* Fix a functional test (wasn't failing before for unknown reasons, but the fix makes sense)
* Install subversion to ensure `svn` tests aren't skipped.
* Fix installation of the mock `mail` command to ensure mail tests aren't skipped.
**Check List**

actions: provision python from conda-forge

---

cylc/flow/task_pool.py

~Remove~ Demote an unnecessary log message:
* This message tells us that the task's outcome was loaded from the DB rather than from memory.
* This information isn't pertinent information for the user.
* This message duplicates information that is already in the log.
* This message gets duplicated once for each trigger, potentially resulting in a very large number of messages.
Accept or close.
**Check List**

task pool: demote "already finished" log message

---

changes.d/6583.fix.md
cylc/flow/config.py
cylc/flow/graph_parser.py
cylc/flow/task_outputs.py
tests/integration/reftests/test_pre_initial.py
tests/integration/test_dbstatecheck.py
tests/integration/test_optional_outputs.py
tests/integration/validate/test_outputs.py
tests/unit/test_config.py
tests/unit/test_graph_parser.py

Fix.no validation of outputs from graph singletons

---

cylc/flow/unicode_rules.py

Refine documentation of Validators

---

.github/workflows/1_create_release_pr.yml
.github/workflows/2_auto_publish_release.yml
.github/workflows/bash.yml
.github/workflows/build.yml
.github/workflows/test_conda-build.yml
.github/workflows/test_fast.yml
.github/workflows/test_functional.yml
.github/workflows/test_tutorial_workflow.yml

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
>| Supported platform | `shell` parameter | Description | Command run internally |
>| --- | --- | --- | --- |
>| Linux / macOS | unspecified | The default shell on non-Windows platforms. **Note that this runs a different command to when `bash` is specified explicitly.** If `bash` is not found in the path, this is treated as `sh`. | **`bash -e {0}`** |
>| All | `bash` | The default shell on non-Windows platforms with a fallback to `sh`. When specifying a bash shell on Windows, the bash shell included with Git for Windows is used.| **`bash --noprofile --norc -eo pipefail {0}`** |
This was added to the docs in https://github.com/actions/runner/issues/1955; I was unaware that there was a …

GH Actions: use explicit `bash` shell & other defaults

---

changes.d/6623.fix.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/host_select.py
tests/functional/restart/43-auto-restart-force-override-normal.t

Supersedes https://github.com/cylc/cylc-flow/pull/6623
Fix an issue with host-select which prevented us from condemning hosts in "force mode".
Also, better link into the "auto restart" docs which can be found here: https://cylc.github.io/cylc-doc/stable/html/plugins/main-loop/built-in/cylc.flow.main_loop.auto_restart.html#module-cylc.flow.main_loop.auto_restart
I am **not** going to go applying terminology changes to this long-standing feature as part of this bugfix (out of scope).
**Check List**

host-select: fix compatibility with force-condemned hosts

---

.github/workflows/build.yml

* The COPYING file appears to have moved from `dist-info/COPYING` into `dist-info/licenses/COPYING`.

actions: update build action to support python 3.13

---

changes.d/6639.fix.md
cylc/flow/subprocpool.py
cylc/flow/workflow_events.py
tests/integration/test_workflow_events.py

Close #6615 
Shutdown handlers aren't run via the subprocess pool, which gets closed on shutdown, so they weren't subject to the process pool timeout. This PR imposes
the timeout on them anyway, outside of the pool.
**Check List**

Kill foreground event handlers on timeout

---

changes.d/6638.fix.md
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

* Closes #6154
* Fix a traceback which can occur in some niche circumstances where there are no sequences left within the `start cycle point` -> `stop cycle point` window after a restart.
* This can happen as the result of a graph change.
**Check List**

runahead: handle no sequences within start-stop cycle interval

---

changes.d/6710.fix.md
cylc/flow/install.py
tests/functional/cylc-reinstall/01-file-transfer.t

Follow on from https://github.com/cylc/cylc-flow/pull/6658#discussion_r2031123602, we've got a reinstall log file, but it's missing the one thing we actually want from it!
* Accidental omission, the reinstall log was missing, well, the log of what got reinstalled :(
* This commit includes it in the same format seen in the install log.
**Check List**

reinstall: log reinstallation in the reinstall log

---

changes.d/6602.fix.md
cylc/flow/taskdef.py
tests/integration/test_taskdef.py

Suicide trigger prevents later cycles starting

---

changes.d/6722.fix.md
cylc/flow/tui/app.py
setup.cfg

Fix a slow memory leak in Tui:
* Urwid has a cache (CanvasCache) that caches the render of each widget to speed up future render cycles.
* Tui is a dynamic tool, it creates a new TuiNode for each update.
* The old TuiNode and its child nodes were not being cleared out of the urwid cache preventing Python's garbage clearance from doing its job.
* This change explicitly clears the urwid cache for each Tui update.
* Preserving the cache post-update isn't really a performance boost for Tui as pretty much every node on the screen has changed anyway (besides the application header and footer). So this is likely of little consequence performance wise. The cache is still active between updates so things like expand/collapse operations will still benefit.
* There is an open issue in urwid for a …

Tui memory leak

---

changes.d/6721.fix.md
cylc/flow/xtrigger_mgr.py
tests/integration/test_xtrigger_mgr.py

Close #6720 
Just needed one call to the datastore after loading xtriggers for restart.
**Check List**

Update datastore xtriggers on restart.

---

changes.d/6730.feat.md
cylc/flow/rundb.py
tests/unit/test_rundb.py

For python >= 3.11, we can access [detailed error codes](https://sqlite.org/rescode.html), making debugging SQLite errors easier.
This change checks for the existence of the attributes so it's compatible with earlier versions of python.
**Check List**
- Just changing print statements
- N/A
- Feature
Fixes #6730

Add SQLite detailed error codes to error messages

---

changes.d/6711.fix.md
cylc/flow/broadcast_mgr.py
cylc/flow/scheduler.py
tests/integration/test_broadcast_mgr.py

Prevent illegal platform host broadcast

---

changes.d/6733.fix.md
cylc/flow/scripts/psutil.py
cylc/flow/workflow_files.py
tests/integration/test_workflow_files.py
tests/unit/test_psutil.py

We have recently seen a case where the `_is_process_running` check would timeout every time for a certain user.
Why only this one user is affected is something I do not understand, however, it's clear that the `cylc psutil` call made by this function is returning way too much data, we only need one field!
Reviewers, please ensure this change is back-compatible, note you can invoke the `cylc psutil` command like so:
```
$ cylc psutil <<< '[["Process", 1]]'
```
To active this logic in a functional test, try:
```
cylc vip --pause <x>
cylc vr --yes <x>
```
You might want to use this patch to confirm that the logic is being called and the cmdline is being returned as expected:
```diff
diff --git a/cylc/flow/workflow_files.py b/cylc/flow/workflow_files.py
index add79adbb..64e748e47 100644
--- …
```

psutil: allow accessing psutil object methods

---

changes.d/6574.fix.md
cylc/flow/broadcast_mgr.py
cylc/flow/broadcast_report.py
cylc/flow/network/resolvers.py
cylc/flow/network/schema.py
cylc/flow/util.py
tests/functional/broadcast/00-simple/expected-prep.err
tests/integration/run_modes/test_simulation.py
tests/integration/scripts/test_broadcast.py
tests/integration/test_broadcast_mgr.py

broadcast: report invalid settings
* We already report invalid cycle points and namespaces.
* However, we have been relying on client-side validation for settings  (which doesn't apply to the GraphQL mutation).
* This also raises the potential for inter-version compatibility issues going unreported.
* This commit explicitly handles invalid settings in the same way as invalid cycle points and namespaces so that they are reported back to the user.
* Closes the issue part of #6429.
* Additionally:
* This change also strips duplicate entries from broadcast reports.
* And fixes the CLI options in broadcast report to match `cylc broadcast`.
**Check List**

broadcast: report invalid settings

---

changes.d/6509.feat.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/commands.py
cylc/flow/network/schema.py
cylc/flow/scripts/reload.py
cylc/flow/scripts/validate_reinstall.py
cylc/flow/task_proxy.py
tests/functional/reload/29-global.t
tests/functional/reload/29-global/flow.cylc
tests/functional/reload/30-global-rollback.t
tests/functional/reload/30-global-rollback/flow.cylc
tests/integration/test_reload.py
tests/unit/cfgspec/test_globalcfg.py

Add a `--global` flag to `cylc reload` that will reload the server's global configuration when set. This can be used to update platform definitions while a workflow is running.
Note that:
* Most changes to the `[scheduler]` section (ports, process pool size, etc.) require a server restart to take effect.
* Already installed platforms cannot have their symlink paths changed.
* Some changes to platforms (such as changing the hosts) may prevent Cylc from communicating with existing jobs (through polls, kill etc.).
Closes #3762
**Check List**

Allow 'cylc reload' to reload global configuration

---

cylc/flow/scripts/cylc.py
tests/functional/cli/01-help.t
tests/unit/scripts/test_cylc.py

Spotted some coverage holes in the CLI code when reviewing something else:
https://app.codecov.io/gh/cylc/cylc-flow/commit/6b6f0037e05aee5f001d9047683a341952374cf0/blob/cylc/flow/scripts/cylc.py?dropdown=coverage#L649
I think the `sys.exit` calls made within the `with pycoverage` block can prevent the capture of coverage.
This change moves the `sys.exit` outside of the block and adds a couple of missing tests.
**Check List**

cylc: fix blindspot and fill some CLI coverage holes

---

cylc/flow/cfgspec/globalcfg.py

If you restart a completed workflow, you currently get PT2M to trigger tasks to allow the workflow to continue.
From recent experience, this is a bit short for users to load the GUI, locate the workflow, figure out what tasks they want to trigger and fire off the mutation.
5 mins seems more reasonable.
I can't see this as being contentious, one review should do.

increase restart timeout to PT5M

---

tests/functional/cylc-play/06-warnif-scp-after-fcp.t
tests/functional/restart/20-event-retry/bin/my-handler
tests/functional/startup/01-log-flow-config.t

* These tests restart workflows with empty task pools.
* In early Cylc 8, the workflow would have just shut down (empty pool).
* In later Cylc 8, a restart timeout was introduced.
* These tests subsequently hung on the restart timeout and failed (due to hitting the inactivity timeout) when the restart timeout was extended in #6787.

tests/f: fix tests which hang on restart timeout

---

changes.d/6745.fix.md
cylc/flow/exceptions.py
cylc/flow/host_select.py
cylc/flow/hostuserutil.py
cylc/flow/main_loop/auto_restart.py
cylc/flow/remote.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
tests/flakyfunctional/restart/39-auto-restart-no-suitable-host.t
tests/functional/cylc-play/11-remote-reinvoke-uncontactable.t
tests/unit/main_loop/test_auto_restart.py
tests/unit/test_exceptions.py
tests/unit/test_host_select.py
tests/unit/test_host_select_remote.py
tests/unit/test_scheduler.py
tests/unit/test_scheduler_cli.py

This fixes a bug where remote reinvocation would exit 0 even if it failed when `[scheduler][run hosts]ranking` is empty (which means random host selection).
- Now it exits non-zero if it failed.
- It also keeps trying hosts if any are uncontactable, until it either finds one that is contactable or exhausts all listed run hosts. (Contact-ability is checked by an empty `cylc psutil <<< '[]'` call on the host)
- Also fixes traceback if an invalid run host is specified in the global config
```cylc
[scheduler]
[[run hosts]]
available = somehost1, somehost2, somehost3
ranking =  # (empty!)
```
```ini
Host somehost*
User borked
```
```console
$ cylc play AnyWorkflow
▪ ■  Cylc Workflow Engine 8.4.2
██   Copyright (C) 2008-2025 NIWA
▝▘    & British Crown (Met Office) & Contributors …
```

Run hosts random-selection bug

---

cylc/flow/scheduler.py

Spotted whilst investigating something else, we still have the vestigial remains of the interface that powered the Cylc 7 GUI in the Scheduler!
**Check List**

scheduler: remove obsolete info_get_graph_raw interface

---

changes.d/6798.fix.md
cylc/flow/task_job_mgr.py

* Closes https://github.com/cylc/cylc-flow/issues/6797
* Fixes an issue where multiple tasks being submitted in the same batch could interact via the "bad hosts" set.
* This would result in one task entering an infinite submission retry loop despite this not having been configured.
I fear this one is going to be a right pain to test, or that the test will become a false negative check. The cause was simple variable scope error, so maybe not in need of a direct test?
**Check List**

fix infinite submission retry bug

---

cylc/flow/network/schema.py

Should fix an integration failure reported in https://github.com/cylc/cylc-uiserver/pull/672#issuecomment-2988076657
* This worked under graphene v2 but not v3 for reasons unknown.
* However, the default appears to be unnecessary which makes sense since it's `List(LogRecords)` not `List(NonNull(LogRecords))`.
Reviewer(s), please test the end-to-end functionality of [this feature](https://github.com/cylc/cylc-ui/pull/2169) on the graphene v3 branches before approving.
**Check List**

schema: remove list default value

---

cylc/flow/command_validation.py

* Closes #6756
* The `allow_new_or_none` argument wasn't respected in one branch of the code.
**Check List**

validation: correct flow validation failure message

---

cylc/flow/config.py
cylc/flow/rundb.py
cylc/flow/task_events_mgr.py
cylc/flow/task_pool.py
tests/functional/database/04-lock-recover.t
tests/unit/test_config.py
tests/unit/test_workflow_files.py

Closes #6760 
https://github.com/cylc/cylc-ui/pull/2169 adds streaming warnings to the UI, but this highlights some warnings which may be either very large, or of no interest to the user.
I am aware that this change may engender controversy - feel free to persuade me that my choices are wrong.
**Check List**

demote unnecessary warnings

---

cylc/flow/commands.py
cylc/flow/config.py
cylc/flow/run_modes/skip.py
cylc/flow/scheduler.py
tests/integration/test_config.py
tests/unit/run_modes/test_skip_units.py

Some more warnings that I think are likely to frustrate users.
I don't think these should be controversial.
**Please bump to 8.6.0 rather than delay 8.5.0 if it comes to it.**
**Check List**

demote warnings

---

changes.d/6902.feat.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/parsec/config.py
cylc/flow/parsec/validate.py
tests/unit/parsec/test_validate.py
tests/unit/test_config.py

* Turns out a lot of workflows have invalid mail/handler events.
* Turn this hard error into a soft warning to make migration easier.
* Also include the list of valid task events in the config docs. Closes https://github.com/cylc/cylc-flow/issues/6870
Docs build:
**Check List**

config: turn invalid workflow event errors into warnings

---

cylc/flow/remote.py

Process polling was added in 5d9e469d98.
I believe the intention was to detect remote processes which had become orphaned as the result of a collapsed SSH connection. The PID of these processes changes when this happens.
See `def elucidate` in `bin/cylc-cat-log`, elucidate!
The code polls the process twice every second which is pretty extreme. With Cylc Hub these processes are concentrated onto one machine, we're seeing a lot of these polling processes.
I think it should be reasonable to turn down the frequency.
**Check List**

cat-log: reduce process poll frequency

---

cylc/flow/cfgspec/globalcfg.py

* Config was removed in https://github.com/cylc/cylc-flow/pull/3093
* But was somehow reincarnated at a later date.
* It does nothing as [`bash` is hardcoded](https://github.com/cylc/cylc-flow/blob/30253e2847faf52b84a417dd2d9fa81c170c27c6/cylc/flow/job_file.py#L158).
* The Bash interpreter can still be configured by prepending it to `$PATH` in `.bashrc` / `.bash_profile`.
**Check List**

remove obsolete config item

---

changes.d/6844.feat.md
cylc/flow/id_match.py
cylc/flow/task_pool.py
tests/functional/cylc-trigger/00-compat/flow.cylc
tests/integration/test_task_pool.py
tests/unit/test_id_match.py

trigger: support ^/$ syntax for referencing the initial/final cycle points

---

changes.d/6909.fix.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/clean.py
cylc/flow/exceptions.py
cylc/flow/network/client.py
cylc/flow/scheduler.py
cylc/flow/scheduler_cli.py
cylc/flow/scripts/clean.py
cylc/flow/scripts/ping.py
cylc/flow/scripts/reinstall.py
cylc/flow/scripts/validate_reinstall.py
cylc/flow/workflow_files.py
tests/functional/cylc-clean/00-basic.t
tests/functional/cylc-combination-scripts/05-vr-fail-is-running.t
tests/functional/cylc-play/00-contact.t
tests/integration/test_reinstall.py
tests/integration/test_workflow_files.py
tests/unit/test_clean.py

Close #6846 
~~Partially address #6261 (by documenting exactly what `cylc vr` does now, rather than changing its behaviour)~~ [off-topic, punted to #6354]
> We currently perform the `detect_old_contact_file` check before we resume a workflow (i.e. `cylc play`) and additionally for`cylc vr`.
> With all other commands, we only perform this check if a network timeout has occurred. But in these situations we just do it anyway.
> I don't think there is any good reason to perform these checks, we should be able to replace it with a simple cylc ping type check 
The `detect_old_contact_file` check runs `cylc psutil` over ssh on a hard-wired 10 second timeout. With NFS latency issues on HPC, that may not be nearly long enough.
This change:
- do a (typically much faster) ping type check first, and …

Address play and vr timeouts: ping first

---

changes.d/6910.fix.md
cylc/flow/commands.py
cylc/flow/scripts/trigger.py
tests/integration/test_force_trigger.py

Close #6858 
Re-spawn **in-group** children of already-completed group start task outputs - because triggering is event-driven and group trigger removes in-group tasks and their already-completed prerequisites.
**Check List**

Group trigger: re-use already-completed outputs of active group start tasks.

---

changes.d/6926.fix.md
cylc/flow/data_store_mgr.py
cylc/flow/task_events_mgr.py
cylc/flow/task_job_mgr.py
tests/integration/network/test_graphql.py
tests/integration/test_data_store_mgr.py
tests/integration/test_task_events_mgr.py
tests/integration/tui/test_logs.py

- Submitted time[^1]
- Job runner
- Job ID in the job runner (on restart, as it was wiped from DB on submit-failure)
[^1]: Submitted time in this case is really the time of failed submission, but useful to know. It is recorded in the DB but wasn't showing in the UI.
**Check List**

Fix data store missing info for submit-failed jobs

---

changes.d/6848.fix.md
cylc/flow/cfgspec/workflow.py
cylc/flow/platforms.py
cylc/flow/task_remote_mgr.py
tests/functional/job-submission/19-platform_select.t
tests/functional/job-submission/19-platform_select/flow.cylc
tests/functional/job-submission/19-platform_select/reference.log
tests/unit/test_platforms_get_platform.py

This so that we can do e.g.
```cylc
platform = $(rose config platform hpc_live)-bg
```
Currently we have to resort to
```cylc
platform = $(echo "$(rose config platform hpc_live)-bg")
```
**Check List**

Allow platform setting to have prefix/suffix around subshell

---

changes.d/6903.fix.md
cylc/flow/cfgspec/globalcfg.py
cylc/flow/scheduler.py
tests/functional/restart/08-stop-after-cycle-point/flow.cylc
tests/integration/test_workflow_events.py

* If a workflow hits the `final cycle point` and is restarted, it is considered complete.
* If a `restart timeout` is configured, the scheduler will stay up for a configured period.
* However, if a workflow hits the `stop after after cycle point` and is restarted, the `restart timeout` event is not yielded and the scheduler will instantly shut down again.
This has been reported as a problem for people following this design pattern: https://cylc.github.io/cylc-doc/stable/html/user-guide/examples/extending-workflow/index.html
**Check List**

restart timeout: fire event for stop after cycle point scenarios

---

cylc/flow/remote.py
tests/functional/cylc-cat-log/12-delete-kill.t

Follow-up to #6871
When cat-log is run in tail mode, and the log file is deleted or the tail process is killed, cat-log exits after 60s since #6871.
However, the test `tests/functional/cylc-cat-log/12-delete-kill.t` is waiting 60s for the cat-log process to exit so the test has become slow + flaky.
This fix allows customising the interval for watching the tail process via an env var so that the test can be made to run quickly.
**Check List**

Fix cat-log test timing out

---

changes.d/6952.fix.md
cylc/flow/cfgspec/workflow.py
cylc/flow/scripts/broadcast.py

* Closes #6950
* Disable an upgrader-patched validation check which is incompatible with `cylc broadcast --cancel`.
So `cylc broadcast` runs config fragments via `cylc.flow.cfgspec.workflow` in order to run them through the upgraders.
Cute, means you can still broadcast deprecated settings, not sure why we support that though?
We have patched some validation stuff into the upgrader (naughty) which is incompatible with this usage.
**Check List**

fix broadcast cancel error

---

cylc/flow/cfgspec/globalcfg.py
cylc/flow/host_select.py

* Closes https://github.com/cylc/cylc-doc/issues/829
* `cpu_percent` typically returns `0.0` on the first call as the monitoring period elapses from module import.
**Check List**

docs: always specify an interval with `cpu_percent`

---

changes.d/6920.feat.md
cylc/flow/command_validation.py
cylc/flow/commands.py
cylc/flow/id.py
cylc/flow/id_match.py
cylc/flow/network/schema.py
cylc/flow/option_parsers.py
cylc/flow/run_modes/simulation.py
cylc/flow/scheduler.py
cylc/flow/scripts/cylc.py
cylc/flow/task_pool.py
cylc/flow/task_proxy.py
tests/integration/network/test_graphql.py
tests/integration/network/test_resolvers.py
tests/integration/run_modes/test_mode_overrides.py
tests/integration/run_modes/test_nonlive.py
tests/integration/run_modes/test_skip.py
tests/integration/scripts/test_set.py
tests/integration/test_data_store_mgr.py
tests/integration/test_flow_assignment.py
tests/integration/test_force_trigger.py
tests/integration/test_id_match.py
tests/integration/test_optional_outputs.py
tests/integration/test_remove.py
tests/integration/test_sequential_xtriggers.py
tests/integration/test_task_pool.py
tests/integration/test_xtrigger_mgr.py
tests/integration/tui/test_app.py
tests/unit/test_command_validation.py
tests/unit/test_id_match.py

* Implement a single task ID matching interface which will satisfy all currently documented use cases / requirements.
* Closes #5827. Allow IDs including families or globs to match against inactive tasks.
* Closes #5750. Only match tasks to release against the "pool" of tasks which are actually held.
* Addresses #4357 & #5677 Abstract task matching from task pool objects. This simplifies its logic, but also unlocks the ability to add a command / GraphQL interface for listing IDs that match provided patterns. The remaining work required for this is outlined in https://github.com/cylc/cylc-uiserver/issues/720.
* Additionally:
* Standardise task ID parsing, validation and standardisation and perform it upfront in `cylc.flow.commands` to ensure validation is not required in internal …

id_match: extend task matching to inactive tasks for globs and families

---

cylc/flow/task_events_mgr.py
tests/unit/test_task_events_mgr.py

All subprocs are already logged at DEBUG level by the subprocpool:
https://github.com/cylc/cylc-flow/blob/3706f18bc49fe7a2d0cc40cd128cbd86278b1ac1/cylc/flow/subprocpool.py#L250-L252
So no need to repeat that just for job-log-retrieval.
**Check List**

job log retrieval: remove duplicate logging

---

changes.d/6835.feat.md
cylc/flow/cfgspec/workflow.py
cylc/flow/config.py
cylc/flow/graph_parser.py
cylc/flow/task_pool.py
tests/integration/test_task_pool.py

Close #6813
This simplifies the system a bit by unifying suicide triggers with task expiry.
Also fixes a long-standing bug: tasks removed by suicide triggers can respawn by other dependencies.
Rationale explained at https://github.com/cylc/cylc-flow/issues/6813#issuecomment-3021516979. Summary:
> On master, suicide triggers just delete tasks from the active pool (n=0)
> - (the bug is: no record of the removal, so suicided tasks can respawn by other dependencies)
> 
> On this branch, suicide triggers just expire tasks
> - expired tasks leave the active pool immediately (which is exactly what suicide is supposed to do)
>   but they're recorded as expired, which stops them respawning
> - every existing suicide test passes as-is
> 
> **The only functional change is**: if a suicide-triggered …

Reimpliment suicide trigger as expire trigger

---

changes.d/6964.feat.md
cylc/flow/config.py
cylc/flow/cycling/iso8601.py
cylc/flow/scheduler.py
pytest.ini
tests/conftest.py
tests/flakyfunctional/xtriggers/01-workflow_state.t
tests/functional/broadcast/00-simple.t
tests/integration/test_broadcast_mgr.py

* Partially addresses #6308
* Broadcasts for a cycle are expired when there are no more active tasks in the cycle.
* At Cylc 7, there was (almost) always a succeeded task in the pool one cycle behind each active task.
* So the broadcast expire limit was the oldest cycle with active tasks *minus* the duration of the longest cycling sequence.
* This commit restores the Cylc 7 broadcast expire limit which ensures that the broadcasts for the previous instance of any given task are preserved.
* This better satisfies the use case of winding back a workflow to the previous cycle (i.e. to retrigger a task, reflow from a task or warm restart).
The solution suggested in #6308 was:
* Don't expire broadcasts automatically.
* Maintain a window of broadcasts in memory.
* Go to the DB to retrieve …

broadcast: reduce the broadcast expire limit

---

cylc/flow/cfgspec/workflow.py

The "optional" term has been removed, changed to "optional output".

doc: fix missing term

---

cylc/flow/main_loop/log_data_store.py
cylc/flow/main_loop/log_memory.py

Fix a minor issue in a developer extension.
Plot legends could contain a partial list of the lines plotted if some of the lines were partial.
Hard to replicate, but you can prove the code still works by running:
```
cylc vip --main-loop='log memory' --main-loop='log data store'
```
And opening the PDF files that get generated in the workflow run dir on shutdown.
**Check List**

profiler: fix minor plotting issue

---

cylc/flow/config.py
tests/integration/test_optional_outputs.py

Trivial change to follow up #6999
Can go in 8.6 if there's time, but no biggie.
- put new debug logging behind a verbosity check - https://github.com/cylc/cylc-flow/pull/6999#discussion_r2390559839
- correct several comments in new tests (was a final commit on 6999 that I neglected to push) - https://github.com/cylc/cylc-flow/pull/6999#pullrequestreview-3279543552
**Check List**

Tweak outputs logging, fix test comments (follow-up 6999)
